raiden/app.py
raiden/channel.py
raiden/channelgraph.py
raiden/contracts.py
raiden/encoding.py
raiden/messages.py
raiden/mtree.py
raiden/raiden_protocol.py
raiden/raiden_service.py
raiden/serializable.py
raiden/tasks.py
raiden/tests/encoding_speed.py
raiden/tests/speed.py
raiden/tests/test_app.py
raiden/tests/test_channel.py
raiden/tests/test_messages.py
raiden/tests/test_settlement.py
raiden/tests/test_transfer.py
raiden/tests/utils.py
raiden/transfermanager.py
raiden/transport.py
raiden/utils.py
setup.cfg

Various fixes:
- unused imports
- unused variables
- complexity
- comment formatting
- placement of imports

Fix flake8

---

raiden/network/discovery.py
raiden/smart_contracts/EndpointRegistry.sol
raiden/tests/smart_contracts/test_endpointregistry.py

Refactoring of the discovery contract to be simpler and for the accompanying proxy class to match the old discovery mock up.

Discoverycontract refactor

---

raiden/tests/smart_contracts/test_netting_channel.py

PR to merge the minor changes made to test_netting_channel.py

add more asserts to ensure values are correct

---

raiden/app.py

This fixes an issue when raiden is using a RPC backend that is not running on the same machine, in which case interacting with the console gets extremely slow (to the point where it's almost impossible to type any command).
@hackaugusto Do you think we should apply this to raiden/master?

Apply gevent monkey patch

---

docker/Dockerfile

* Image size is `539.8 MB`.
* This aims to be the production repository image: It will get the `raiden` contents from `HEAD`.
* User should adjust rev required in `Dockerfile` if a specific one is needed.
docker build -t raiden-network/raiden -f docker/Dockerfile .
docker run -ti --rm raiden-network/raiden <parameters>

Docker image

---

.travis.yml
raiden/channel.py
raiden/smart_contracts/ChannelManagerContract.sol
raiden/smart_contracts/ChannelManagerLibrary.sol
raiden/smart_contracts/EndpointRegistry.sol
raiden/smart_contracts/HumanStandardToken.sol
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/smart_contracts/Registry.sol
raiden/smart_contracts/StandardToken.sol
raiden/smart_contracts/Token.sol

- Adding pragma statement on all contracts
- Modifiers now need a semicolon after the underscore keyword
- Libraries can't have a fallback function
- Check results of `call()`. Potential failures should be handled.
- Miscellaneous style fixes

Make all smart contracts compilable by solc v4.0

---

raiden/blockchain/net_contract.py
raiden/channel.py
raiden/console.py
raiden/encoding/messages.py
raiden/messages.py
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/tests/test_channel.py
raiden/tests/test_transfer.py
raiden/tests/utils/transfer.py

/s/transferedAmount/transferredAmount/
/s/transfered_amount/transferred_amount/
Fix #103

transfered -> transferred

---

raiden/tasks.py

- acessing the wrong attribute
- needs to register the message after signing (so that the sender field is set)

Refund fixes

---

tox.ini

This should be sufficient to close #159

fail fast, integration after unit tests #159

---

raiden/console.py
tools/genesis_builder.py
tools/tmuxtest.sh

Using a pre-configured genesis block to speed up the blockchain startup time.

improved tmuxtest.sh

---

raiden/assetmanager.py
raiden/raiden_service.py
raiden/tasks.py
raiden/transfermanager.py
tools/tmuxtest.sh

- Added tasks for asset exchanges
- Checking values for SecretRequest
- Better state transitions for mediated tasks
Please review after #156
This may fix #3 ?

Asset Exchange

---

raiden/app.py

Avoids prompting for a password.

Allow password to be passed by parameter (for scripted use)

---

raiden/tests/utils/tests.py

reinit gevent hub after each test

---

raiden/raiden_service.py
raiden/smart_contracts/ChannelManagerContract.sol
raiden/smart_contracts/ChannelManagerLibrary.sol
raiden/smart_contracts/EndpointRegistry.sol
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/smart_contracts/Registry.sol
raiden/tests/integration/test_blockchainservice.py
raiden/tests/smart_contracts/DecoderTester.sol
raiden/tests/smart_contracts/test_channel_manager.py
raiden/tests/smart_contracts/test_netting_channel.py
raiden/tests/smart_contracts/test_registry.py
raiden/tests/utils/mock_client.py

This PR makes sure that all variable names use consistent casing. @LefterisJP and I decided to use snake case for variable names and let the function names me mixed case, since this is a nice way to distinguish smart contract calls in the python code.
I also made a few changes to make the smart contracts look a bit better. This was mainly done by splitting up some very long function declarations.

Consistent casing and smart contract facelift

---

CONTRIBUTING.md

Please provide feedback if this accurately reflects what we want to have as a developer's/contributor's guide in Raiden.

Developer guide

---

raiden/network/discovery.py
raiden/network/rpc/client.py
raiden/network/transport.py
raiden/raiden_protocol.py
raiden/raiden_service.py
raiden/smart_contracts/EndpointRegistry.sol
raiden/tests/fixtures/blockchain.py

A small PR fixing minor typos and style issues at various part of the codebase I was reading up on while addressing other issues.

Typos, spelling and style

---

raiden/raiden_protocol.py
raiden/raiden_service.py
raiden/tasks.py

wait for greenlets to quit

---

tox.ini

@hackaugusto Please have a look.

Move flake8 out of default tox command

---

.travis.yml
.travis/download_geth.sh
.travis/download_solc.sh
.travis/make_dag.sh
raiden/tests/fixtures/variables.py
requirements.txt

Using a build environment variable for each kind of build, it might improve the build speed a bit. this will depend on the number of machines that travis has available for opensource projects.
~This is built on top of PR #220~
https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines

Travis build

---

raiden/app.py

- Fix #228 (keypath docstring)
- Fix #229 (Show error when there is no accounts to select)

Minor fixes related to accounts

---

CONTRIBUTING.md

As requested by @schmir I added an explanation of how core contributors can add commits to other people's Pull Requests.
Also some simple rules for nice committing.

Contributing to others prs

---

.travis.yml
raiden/channel.py
raiden/network/rpc/client.py
raiden/tests/conftest.py
raiden/tests/fixtures/__init__.py
raiden/tests/fixtures/blockchain.py
raiden/tests/fixtures/raiden_network.py
raiden/tests/fixtures/tester.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/test_endpointregistry.py
raiden/tests/integration/test_settlement.py
raiden/tests/smart_contracts/test_registry.py
raiden/tests/unit/test_webui.py
raiden/tests/utils/blockchain.py
raiden/tests/utils/mock_client.py
raiden/tests/utils/network.py
raiden/tests/utils/tester_client.py
raiden/utils/__init__.py
tools/create_compilation_dump.py
tools/genesis_builder.py

Normal py.test run:
> 61 passed, 1 skipped, 6 xfailed in 1752.06 seconds
Run with genesis cache enabled:
> 61 passed, 1 skipped, 6 xfailed in 303.34 seconds

Build cache

---

tox.ini

`[devenv:unit]` wasnt working, changed to `[testenv:unit]`

fixed tox.ini envs

---

.travis.yml

making the test suite more verbose

travis: enable geth logging

---

raiden/tests/conftest.py
raiden/tests/fixtures/__init__.py
raiden/tests/fixtures/blockchain.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/test_blockchainservice.py
raiden/tests/utils/blockchain.py

unique ports for the integration tests, fix for the build failure:
https://travis-ci.org/raiden-network/raiden/jobs/176376590#L410-L412

tests: unique port numbers for each test

---

raiden/assetmanager.py
raiden/network/protocol.py
raiden/network/transport.py
raiden/raiden_service.py
raiden/tests/fixtures/blockchain.py
raiden/tests/unit/test_transfer.py
raiden/tests/utils/network.py
raiden/transfermanager.py

Addresses valid messages from unknown senders of issue #72 and has tests for these cases.

Handle valid messages from unknown senders

---

raiden/channel.py
raiden/network/channelgraph.py
raiden/network/protocol.py
raiden/tests/unit/test_transfer.py

It's a part of https://github.com/raiden-network/raiden/issues/72

Ignore out of order messages

---

README.md
raiden/ui/cli.py

Add ropsten deployed contracts

---

raiden/smart_contracts/NettingChannelContract.sol
raiden/tests/smart_contracts/test_netting_channel.py

adding event for `updateTransfer`

add event to update transfer

---

.bumpversion.cfg
setup.py

Bump version: 0.0.2 → 0.0.3

---

raiden/tests/smart_contracts/test_netting_channel.py

Test that if someone transfers tokens directly to a channel it's not
being considered as part of the contract's net balances and not
dispersed in anyway to the channel participants but is instead
burned/locked forever in the contract.

Test for unauthorized token transfer to channel

---

.bumpversion.cfg
setup.py

Raiden POC 4 - El Cabrito
- Don't swallow errors when talking to the Github API:
https://github.com/raiden-network/raiden/pull/283
- Better specify and improve the channel closing strategy.
https://github.com/raiden-network/raiden/pull/276
- Test that unauthorized token transfers to a channel do not
disrupt the netted token balance and the overall channel
operation.
https://github.com/raiden-network/raiden/pull/284

Release 0.0.4

---

raiden/assetmanager.py
raiden/channel.py
raiden/network/protocol.py
raiden/network/rpc/client.py
raiden/raiden_service.py
raiden/tasks.py
raiden/tests/utils/tester_client.py
requirements.txt

Changes introduced by the PR:
- Remove the LogListenerTask to reduce the number of json-rpc calls.
- Cache of the current block number in RaidenService.

Blockchain cache

---

raiden/channel.py

Removes ChannelEndState.compute_merkleroot_without

---

.travis.yml
requirements-dev.txt
requirements.txt
tox.ini

Also pinned the version of these developement dependencies to their current latest version.
This closes issue #214

separated the developement requirements

---

raiden/tasks.py

moved the magic number 2 into a single line and added a note to fixit (not the real fix, just a reminder about it)

fixme: remove the magic constant

---

raiden/tests/integration/test_blockchainservice.py
raiden/tests/integration/test_settlement.py

Temporary fix for: https://github.com/raiden-network/raiden/issues/319

Skip tests that cause travis to hang

---

raiden/channel.py
raiden/network/rpc/client.py
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/tests/fixtures/blockchain.py
raiden/tests/fixtures/raiden_network.py
raiden/tests/fixtures/tester.py
raiden/tests/fixtures/variables.py
raiden/tests/smart_contracts/test_netting_channel.py
raiden/tests/unit/test_channel.py
raiden/tests/utils/mock_client.py
raiden/tests/utils/network.py
raiden/tests/utils/tester_client.py

This should fix https://github.com/raiden-network/raiden/issues/82.

Monitor channels and dispute

---

raiden/tests/fixtures/blockchain.py
raiden/tests/utils/blockchain.py

using consistent names to make navigation/searching easier.

consistent naming for the fixtures

---

raiden/network/rpc/client.py

Does not need to be necessarilly merged, just want to start a discussion to see if others would find a function like this useful.

Add function to check if geth transaction threw

---

README.md

Suggested corrections for the Raiden README.md to clarify details on the installation instructions and some formatting for readability.

Formatting and clarification in README.md

---

setup.py

thanks to @nicksavers for pointing it out

Fix upstream location in setup.py

---

raiden/tests/utils/blockchain.py

`geth_create_blockchain` can be used for testing or for setting up test
environments, for test environments it make sense to redirect the geth
output to log files and not clutter the user's terminal.

geth: Introduced config for a log directory

---

raiden/smart_contracts/ChannelManagerContract.sol
raiden/smart_contracts/ChannelManagerLibrary.sol
raiden/tests/smart_contracts/test_channel_manager.py

Adding ChannelDeleted event to the ChannelManagerContract

---

raiden/network/protocol.py
raiden/raiden_service.py
raiden/tests/unit/test_transfer.py
raiden/tests/utils/tester_client.py
raiden/transfermanager.py

Should close https://github.com/raiden-network/raiden/issues/72

Final additions for the hardening against error conditions

---

CONTRIBUTING.md
docs/Overview-Raiden-Classes.md
raiden/blockchain/__init__.py
raiden/blockchain/net_contract.py

minor typo corrections in code and docs

---

raiden/smart_contracts/NettingChannelLibrary.sol

remove unsused variable and superflous blank line

---

raiden/tests/integration/test_blockchainservice.py
raiden/tests/unit/test_callbacks.py
raiden/tests/unit/test_transfer.py
setup.py

Just getting rid of some things that I believe should not be there.

Minor cleanup of tests and setup.py

---

raiden/assetmanager.py
raiden/network/rpc/client.py
raiden/tests/utils/mock_client.py
raiden/tests/utils/tester_client.py

Creating this pull request which fixes https://github.com/raiden-network/raiden/issues/294

Adding one filter for all the events

---

raiden/ui/cli.py

closes first half of issue #131

replaced underscores with dashes in 4 long optional arguments in (GNUStyle)

---

raiden/network/rpc/client.py
raiden/smart_contracts/ChannelManagerContract.sol
raiden/smart_contracts/ChannelManagerLibrary.sol
raiden/smart_contracts/Registry.sol
raiden/tests/smart_contracts/test_channel_manager.py

As I started to work on #369 I realized that most functions are already constant, which means that they should not cause a problem. And the functions that existed that made state changes now use constant functions to get the indices they need for removing and adding elements to the data structures. 
@LefterisJP I am not entirely sure if this was what you meant, but it seems like a solution to me.

Use mappings with arrays for indices

---

docs/api.rst
docs/conf.py

First version of the API specification

---

raiden/smart_contracts/NettingChannelContract.sol

I believe these docstrings are accurate to how each of these functions perform.
For issue #335

added docstring to nettingchannelcontract.sol

---

raiden/api/encoding.py
raiden/api/mock.py
raiden/api/objects.py
raiden/api/resources.py
raiden/api/rest.py
raiden/api/test_encoding.py
raiden/channel.py
raiden/network/rpc/client.py
raiden/raiden_service.py
raiden/tests/fixtures/__init__.py
raiden/tests/unit/test_callbacks.py
raiden/transfermanager.py
raiden/utils/__init__.py
requirements.txt

This is all work done by @ezdac for the Rest API as seen here: https://github.com/raiden-network/raiden/pull/384/.
I squashed it into one commit and rebased on master, since it was impossible to rebase 30 commits going back 3 months. Too much changed in the meantime.

Rest api squashed

---

raiden/tests/smart_contracts/test_netting_channel.py

Fixes issue #370 . Please review this pull request.

Adding test_netting for testing transfers that exceed the deposit amount

---

raiden/raiden_service.py

Left over from: https://github.com/raiden-network/raiden/pull/409

removed unused APIEventManager

---

raiden/tests/unit/test_transport.py

This is a proposal to tackle the flakyness ( #389 ) of
`raiden.tests.unit.test_transport.py::test_throttle_policy_ping`.
Instead of tracking actual sleep times this now just tests for the correct
calls to `gevent.sleep` in the throttle policy implementation.

Use deterministic time progress in test

---

raiden/encoding/messages.py
raiden/messages.py
raiden/tests/benchmark/speed_decoding.py

locksroot is not being used, removing because then I don't need to integrate it with the restartable task

removed locksroot reject message

---

raiden/main.py
raiden/ui/cli.py
raiden/ui/console.py

Have been trying to create a small demo of Raiden and while doing so found a few things that need to be fixed in order to get to the old CLI interface.

Some changes to enable running raiden as an app

---

raiden/api/test_encoding.py
raiden/api/wamp_server.py
raiden/blockchain/abi.py
raiden/channel.py
raiden/network/rpc/client.py
raiden/tests/benchmark/speed_simulation.py
raiden/tests/unit/transfer/mediated_transfer/test_mediator.py
raiden/tests/unit/transfer/mediated_transfer/test_target.py
raiden/tests/utils/mock_client.py
raiden/tests/utils/tester_client.py
raiden/ui/web.py
tools/config_builder.py
tools/scenario_runner.py

This addresses the missing parts of #227.
```
$ cat sed_script.sed 
s/asset/token/g
s/Asset/Token/g
s/ASSET/TOKEN/g
$ for file in $(ag -il --python 'asset'); do sed -f sed_script.sed $file > $file.rename; mv $file.rename $file; done
```

Replace all instances of asset with token in *.py

---

raiden/smart_contracts/NettingChannelContract.sol

PR #392 missed the @params on the unlock function.
The PR was in response to #335.

Add missing docstring (@param) for the unlock function.

---

raiden/ui/cli.py

bugfix: encoding mismatch

---

docs/api.rst
raiden/api/rest.py
raiden/network/rpc/client.py
raiden/raiden_service.py
raiden/tests/integration/test_events.py
raiden/tests/utils/mock_client.py
raiden/tests/utils/tester_client.py

Api and events

---

.travis.yml
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/raiden_service.py
raiden/tests/api/test_api.py
raiden/utils/__init__.py

Fix the API tests and add them to Travis.

Fix api tests and include them in Travis

---

raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol

NettingChannelLibrary simplification

---

raiden/network/rpc/client.py

Using ` estimated_gas = min(estimated_gas * 2, GAS_LIMIT) ` to make sure sufficient gas is provided, but at the same time, does not exceed block gas limit.
Solves #244

Use proper gas estimation

---

docs/api.rst
raiden/api/objects.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/raiden_service.py
raiden/tests/api/test_api.py
raiden/tests/fixtures/api.py
raiden/tests/integration/test_events.py
raiden/tests/utils/apitestcontext.py

Fix: https://github.com/raiden-network/raiden/issues/467

Expose blockchain events in api

---

docs/api.rst
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/raiden_service.py
raiden/tests/api/test_api.py
raiden/tests/fixtures/api.py
raiden/tests/unit/test_transfer.py
raiden/tests/utils/apitestcontext.py
raiden/tests/utils/transfer.py
raiden/transfermanager.py

Close https://github.com/raiden-network/raiden/issues/440

Expose an API endpoint for transfer creation

---

tools/create_compilation_dump.py

This fixes a small error in one of the helper scripts.

Fix syntax error

---

raiden/app.py
raiden/ui/cli.py
raiden/ui/console.py

This PR makes the RPC server the default when starting raiden. 
The cli can optionally be started together with the RPC server or without the RPC server.

Expose rest api

---

raiden/app.py

I removed the if statement to make it more clear what was going on and
easier to read after Augusto pointed this out

Removed if statement

---

raiden/ui/cli.py

Give more tries to user for passphrase unlock

---

raiden/encoding/messages.py
raiden/smart_contracts/NettingChannelLibrary.sol

Removed the field secret from DirectTransfer encoding

---

raiden/smart_contracts/NettingChannelLibrary.sol

removed unused variable

---

raiden/smart_contracts/NettingChannelLibrary.sol

Instead of modifying the Participant struct in place it returns the
necessary values.

Simplified decode functions

---

raiden/api/rest.py
raiden/channel.py
raiden/messages.py
raiden/network/protocol.py
raiden/network/rpc/client.py
raiden/raiden_service.py
raiden/tasks.py
raiden/tests/api/test_api.py
raiden/tests/fixtures/api.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/test_e2e.py
raiden/tests/integration/test_tokenswap.py
raiden/tests/unit/test_transfer.py
raiden/tests/utils/apitestcontext.py
raiden/tests/utils/tester_client.py
raiden/transfer/mediated_transfer/target.py

Token swap

---

raiden/ui/console.py

fixed tools.create_token

---

raiden/network/rpc/client.py
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/tests/integration/test_settlement.py
raiden/tests/smart_contracts/test_netting_channel.py
raiden/tests/utils/mock_client.py
raiden/tests/utils/tester_client.py

Closed #504 by mistake, sorry about that!
Creating a new PR and rebased master.
Solves  #476 @hackaugusto @czepluch

rename unlock to withdraw

---

raiden/channel.py

While reading the code in channel.py just fixed some typos and removed
unused exceptions

Some cleanup in channel.py

---

raiden/channel.py
raiden/transfer/state.py

I cherry picked Konrad's [commit](https://github.com/raiden-network/raiden/pull/400/commits/cc28a2a0196008e106f7eebdd702219a43290205) from the [automatic channel provisioning](https://github.com/raiden-network/raiden/pull/400/) PR since this is a fix we need in master asap to avoid some flaky failing tests.

Introduce INITIALIZING state for channels

---

raiden/blockchain/net_contract.py
raiden/constants.py
raiden/encoding/format.py
raiden/encoding/messages.py
raiden/messages.py
raiden/tests/fixtures/tester.py
raiden/tests/smart_contracts/test_decoder_netting_channel.py
raiden/tests/smart_contracts/test_netting_channel.py
raiden/tests/unit/test_channel.py
raiden/tests/unit/test_namedbuffer.py
raiden/tests/utils/tester.py

Decoder tests for messages with missing bytes

Decoder tampered

---

raiden/raiden_service.py
raiden/ui/console.py

fixed the broken raiden console

---

raiden/smart_contracts/ChannelManagerContract.sol
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol

This is my first solidity PR, all feedback is appreciated.
Replacing all throws with require/assert
Implementing #604

Use require and assert in smart cotracts

---

raiden/raiden_service.py
raiden/tests/unit/test_transfer.py

This fixes the first part of #596

Invitation pings for nat

---

requirements.txt
setup.py

Use a tag instead of a branch for the pyethapp dependency
Also remove `-e` since it's not needed.

Use a tag for pyethapp dependency

---

raiden/tests/fixtures/api.py

Fix for https://github.com/raiden-network/raiden/issues/389#issuecomment-305551563

wait for the flask socket

---

raiden/encoding/signing.py
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/tests/smart_contracts/netting_channel/AuxiliaryTester.sol
raiden/tests/smart_contracts/netting_channel/test_auxiliary_netting_channel.py

Fix signature split

---

raiden/api/rest.py
raiden/ui/cli.py
requirements.txt

Cors enable

---

.travis.yml
tools/ansible/contrib/inventory/ec2.py

Fixed PEP8 in the tools/ansible.

---

raiden/raiden_service.py
raiden/tests/integration/test_e2e.py
raiden/tests/unit/functional/test_directtransferlog.py
raiden/tests/unit/test_statechange_log.py
raiden/tests/unit/transfer/mediated_transfer/test_initiator.py
raiden/tests/unit/transfer/mediated_transfer/test_mediator.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/state_change.py

direct transfer state change

---

docs/Rest-Api.rst
raiden/api/rest.py
raiden/api/v1/resources.py
raiden/tests/api/test_api.py

Add address endpoint to Rest API

---

raiden/connection_manager.py

Some severely needed cleanups for the ConnectionManager code. Thanks for nagging, @schmir !

Clean up ConnectionManager

---

raiden/raiden_service.py

Clarification on state change logging functions

---

.travis.yml

Now including @konradkonrad's PR to fix the DAG generation problem: https://github.com/ethereum/go-ethereum/pull/14598

Bump geth to v1.6.6

---

MANIFEST.in
setup.py

This replaces the manually assembled list of packages in `setup.py` with `find_packages()`.

Use find_packages() instead of hardcoded list in setup.py

---

CONTRIBUTING.md

This only contains package installation instructions for Ubuntu/Debian. Other systems TODO.
#183

Basic doc for setting up a dev environment (contribution to #183)

---

raiden/channel/netting_channel.py

Tried to clarify the comments about the settlement timeout check.

clarified settle timeout check

---

raiden/smart_contracts/ChannelManagerContract.sol
raiden/smart_contracts/ChannelManagerLibrary.sol
raiden/smart_contracts/EndpointRegistry.sol
raiden/smart_contracts/HumanStandardToken.sol
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/smart_contracts/Registry.sol

This PR addresses warnings given by the solc compiler version 0.4.13

smart contracts: using revert/require/assert syntax

---

raiden/network/upnpsock.py

This addresses #696 and some other error conditions recently reported.

Improve upnp error handling

---

raiden/raiden_service.py
raiden/tests/fixtures/variables.py
raiden/ui/cli.py

Make database dir configurable

---

raiden/ui/cli.py

This small PR aims in replacing usage of Flask internal dev web server by [gevent's WSGIServer](http://www.gevent.org/gevent.pywsgi.html).
Flask's development server is [strongly advised against](http://flask.pocoo.org/docs/0.12/api/#flask.Flask.run) for anything besides basic development execution. It doesn't support co-routines, and blocks while running (currently, that's the case, although we run it in it's own Greenlet).
As we're already using gevent loop in the whole application, it is interesting to put Flask server on this loop, using a WSGI-compliant webserver, and `gevent.wsgi.WSGIServer` fits nicely, being a good tradeoff between as little configuration as possible, while taking full advantage of gevent's loop and async handling, and also one of flask's [recommended deployment …

Use WSGIServer for serving Flask API [proposal][needs testing]

---

docs/Rest-Api.rst
raiden/api/rest.py
raiden/tests/api/test_api.py

Fix https://github.com/raiden-network/raiden/issues/748

Return 204 and empty body for API connect/leave

---

raiden/network/upnpsock.py

Better fix for #754 as a replacement for #755, also gets rid of unnecessary recursion.

Cleaner fix for UPnP unicode address issues + removed recursion

---

raiden/network/rpc/client.py
raiden/tests/integration/test_blockchainservice.py

This is a reopened PR for PR #387 and issue #371

Check duplicated netting channel

---

raiden/raidenwebui/src/app/components/token-network/token-network.component.html
raiden/raidenwebui/src/app/components/token-network/token-network.component.ts
raiden/raidenwebui/src/app/services/raiden.service.ts

Makes a dialog for user to Join a token network through the raiden webui

Connection management ui

---

Makefile
docs/Makefile
docs/conf.py
raiden/api/rest.py
raiden/app.py
raiden/connection_manager.py
raiden/messages.py
raiden/raiden_service.py
raiden/transfer/architecture.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/state.py
raiden/ui/console.py

- enabled napoleon extension to parse google docs properly
- removed sphinx-api call - sphinx can run it by itself
- fixed some docstrings

Fix for API docs generator

---

raiden/api/rest.py
raiden/ui/cli.py
raiden/ui/web/.angular-cli.json
raiden/ui/web/package.json
raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/services/raiden.service.ts
raiden/ui/web/src/assets/config/config.production.json
raiden/ui/web/src/environments/environment.prod.ts
raiden/ui/web/src/polyfills.ts

First we build the webui using `ng build --aot  --prod`. The built web app then lies in the `dist` folder. We try to serve out the webui adding a  flask route. The HTML is being served correctly but the associated `js` and `css` files fail to load. Researching a little more about it.

Deploy webui through flask routes

---

raiden/ui/web/package.json
raiden/ui/web/src/app/app.component.ts
raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.html
raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
raiden/ui/web/src/app/components/event-list/event-list.component.html
raiden/ui/web/src/app/components/event-list/event-list.component.ts
raiden/ui/web/src/app/models/event.ts
raiden/ui/web/src/app/pipes/keys.pipe.spec.ts
raiden/ui/web/src/app/pipes/keys.pipe.ts
raiden/ui/web/src/app/pipes/subset.pipe.spec.ts
raiden/ui/web/src/app/pipes/subset.pipe.ts
raiden/ui/web/src/app/services/raiden.service.ts
raiden/ui/web/src/polyfills.ts

Now, events can be watched through Channels view. Network Events are always shown. Specific events can be selected for viewing through Channel menu. Activity icons are shown on events tab when a new activity is detected. Channel events tabs can be closed, and reopened at will.

Webui events

---

raiden/api/python.py
raiden/api/rest.py
raiden/tests/utils/apitestcontext.py

Changing function arguments keys to match the call

---

raiden/ui/cli.py

Implements #719
`raiden removedb` deletes `~/.raiden`
`raiden removedb --datadir <dir>` deletes `<dir>`
`raiden removedb --address <address>` deletes `~/.raiden/<address>[:8]`
`raiden removedb --datadir <dir> --address <address>` deletes `<dir>/<address>[:8]`

removedb console command

---

raiden/tests/conftest.py
raiden/tests/unit/test_messages.py
raiden/ui/cli.py
raiden/utils/profiling/constants.py
raiden/utils/profiling/cpu.py
raiden/utils/profiling/graph.py
raiden/utils/profiling/sampler.py
raiden/utils/profiling/timer.py
raiden/utils/profiling/trace.py

Added some profiling logic, this was initially developed for pyethapp I made some modifications to avoid global state and added some hooks to profile from pytest and enable profiling at runtime.

added profiling integration

---

raiden/network/protocol.py
raiden/network/transport.py
raiden/raiden_service.py
raiden/tests/fixtures/api.py

Postpone protocol transport startup to make sure every member of RaidenService is set up properly.
Should fix #839

Alarmtask startup fix

---

raiden/channel/netting_channel.py
raiden/encoding/messages.py
raiden/message_handler.py
raiden/messages.py
raiden/raiden_service.py
raiden/tests/benchmark/speed_decoding.py
raiden/tests/integration/test_e2e.py
raiden/tests/unit/test_service.py
raiden/tests/unit/test_transfer.py
raiden/tests/unit/transfer/mediated_transfer/factories.py
raiden/token_swap.py

This adds the required fields to make a Secret message a valid balance proof.

Secret message as a balance proof

---

raiden/messages.py
raiden/tests/integration/test_e2e.py

Typos and one function abstraction after review of #843

Typos and one function abstraction

---

raiden/network/protocol.py
raiden/tests/unit/test_notifyingqueue.py
raiden/utils/notifying_queue.py

regression test for https://github.com/raiden-network/raiden/pull/846

added regression test for queue copy

---

raiden/raiden_service.py

If for some reason geth node's RPC api goes offline or stops responding, endpoint registry may fail. In this case Raiden is left in an undefined state.
This patch will print an error message and terminate Raiden in such case, forcing user to check geth's status and restart.
Fixes #802.

Handle endpoint registry exceptions

---

raiden/raiden_service.py

Handle loading of a channel which was settled while we were offline.
We were getting this exception when we were offline and one of our
channels was settled and then we try to load it up from the serialized data.
```
File "/home/lefteris/.virtualenvs/raiden/bin/raiden", line 11, in <module>
File "/home/lefteris/ew/raiden/raiden/__main__.py", line 11, in main
run(auto_envvar_prefix='RAIDEN')
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 722, in __call__
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 697, in main
File …
```

Handle loading of channel settled while offline

---

raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
raiden/ui/web/src/app/components/event-list/event-list.component.ts
raiden/ui/web/src/app/components/token-network/token-network.component.html
raiden/ui/web/src/app/components/token-network/token-network.component.ts
raiden/ui/web/src/app/components/transfer-dialog/transfer-dialog.component.html
raiden/ui/web/src/app/components/transfer-dialog/transfer-dialog.component.spec.ts
raiden/ui/web/src/app/components/transfer-dialog/transfer-dialog.component.ts
raiden/ui/web/src/app/services/raiden.service.ts

Needs testing, but should work as well as the API.

Transfer dialog

---

raiden/tests/integration/test_blockchainservice.py
raiden/tests/smart_contracts/test_channel_manager.py

Added a test to check if https://github.com/raiden-network/raiden/issues/892 is a problem with the smart contract code.

channel manager: test getChannelsParticipants with many channels

---

raiden/ui/web/src/app/app.component.css
raiden/ui/web/src/app/app.component.html
raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.html
raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
raiden/ui/web/src/app/components/event-list/event-list.component.html
raiden/ui/web/src/app/components/join-dialog/join-dialog.component.html
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.html
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.spec.ts
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
raiden/ui/web/src/app/components/register-dialog/register-dialog.component.html
raiden/ui/web/src/app/components/swap-dialog/swap-dialog.component.ts
raiden/ui/web/src/app/components/token-network/token-network.component.html
raiden/ui/web/src/app/components/token-network/token-network.component.ts
raiden/ui/web/src/app/components/transfer-dialog/transfer-dialog.component.html
raiden/ui/web/src/app/models/channel.ts
raiden/ui/web/src/app/services/raiden.service.ts
raiden/ui/web/src/styles.css

Mostly of this PR is a lot of CSS and usability improvements.
Buttons goes up, Open Channel own component dialog, Channels table sortable, Tokens table shows when the user is already participating in a token network.
As improvement, add the possibility of calling `connect` on Token Networks where the use is already participating.

WebUI Join already connected Token Networks

---

raiden/channel/netting_channel.py

Fix race condition at channel settling

---

raiden/network/discovery.py

In the current Discovery model, registering an endpoint is an on-chain transaction. So far, we always registered the address.
With this PR, we now check for an existing `node_address` - `endpoint` mapping and compare
it to the value about to be registered. If it matches, we skip endpoint registration.

Avoid double endpoint registration in Discovery

---

raiden/channel/balance_proof.py
raiden/channel/netting_channel.py
raiden/channel/participant_state.py
raiden/message_handler.py
raiden/messages.py
raiden/raiden_service.py
raiden/tests/api/test_api.py
raiden/tests/unit/test_channel.py
raiden/tests/unit/transfer/mediated_transfer/test_target.py
raiden/tests/utils/apitestcontext.py
raiden/tests/utils/tester.py
raiden/tests/utils/transfer.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/state.py

Note: This is a breaking change for the WAL, since the class BalanceProof is changing name.

Balance proof simplification

---

raiden/tests/utils/smoketest.py
raiden/ui/cli.py

Adds a check that tries to do a request on the REST api.
Fixes #768

Added REST api check to smoketest

---

raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/resources.py
raiden/tests/api/test_api.py
raiden/tests/fixtures/api.py
raiden/tests/utils/apitestcontext.py

This PR implements https://github.com/raiden-network/raiden/issues/921

Api query connection manager

---

tools/testnet/files/dockerfiles/raiden/raiden
tools/testnet/files/dockerfiles/raiden/raiden_echo_node

Apply json serializer fix to echo node entrypoint script

[testnet] Fix echo node entrypoint script

---

docs/rest_api.rst
raiden/api/rest.py

Some fixes and rewording of the REST API documentation.

Rest api documentation fixes

---

docs/overview_and_guide.rst
docs/what_is_the_dev_preview.rst

also fixed dublicate explicit targers warning

fixed typo and fixed title level inconsistency

---

docs/rest_api.rst
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/tests/api/test_api.py
raiden/utils/__init__.py

Required for supporting this option in webUI.

Support reveal_timeout in open channels API

---

.bumpversion.cfg
setup.py

Release 0.0.6

---

raiden/network/protocol.py

Because we serialize the protocol data and the `receivedhashes_to_acks` dictionary can be loaded from a file that is old, it is quite possible that the `host_port` pair for a message may have changed since the time we saved it to the mapping.
This change introduces a check for the current `host_port` of the sender, and if different from what is saved in the mapping the mapping is updated and the message is resent to the new host/port pair.

Check if host_port didnt change when sending ACK

---

docs/api_walkthrough.rst
docs/index.rst
docs/overview_and_guide.rst
docs/rest_api.rst
docs/webui_tutorial.rst
docs/what_is_the_dev_preview.rst

Work in progress PR for implementing feedback to the documentation
Collaborative PR:
- Send your doc comment as a commit to this branch.
- **commit with `[skip ci]` in commit message!**
- **Don't just push, always do** `git pull --rebase && git push`.
- Only the current Assignee is allowed to rebase against master/force push.
- We will squash changes before merging.

Polish the documentation

---

raiden/raiden_service.py

Move the restoring from snapshot after the registering of the registry

Fix restoring from snapshot

---

raiden/raiden_service.py

RaidenService had a race among the alarm task and the filter removal,
that allowed the filter to be uninstall before the next poll callback was
executed, resulting in exceptions like the following:
JSONRPCClientReplyError: filter not found
This change adds synchronization, requiring the alarm task to
completely stop before the events are removed.

alarm task stopped before filter uninstall

---

.bumpversion.cfg
docs/conf.py
setup.py

Testing deployment and docs generator
automated PR!

Release 0.0.7

---

raiden/ui/web/src/app/components/home/home.component.html

[skip ci] Add doclink to webui

---

raiden/tests/fixtures/blockchain.py
raiden/tests/fixtures/variables.py
raiden/tests/utils/blockchain.py

this adds a random marker for each test run, used to check if the ethereum node used is the intended one.

added check for concurrent and conflicting test runs

---

tools/testnet/roles/logstash/tasks/main.yml
tools/testnet/roles/traefik/tasks/main.yml
tools/testnet/roles/traefik/templates/rules.toml.j2
tools/testnet/roles/traefik/templates/traefik.toml.j2
tools/testnet/roles/traefik/vars/main.yml

The domain change on the testnet somehow fell through the cracks and never got committed.

Fix testnet domain

---

.bumpversion.cfg
docs/conf.py
setup.py

Another test release
automated PR!

Release 0.0.8

---

README.rst

Also removed outdated versioning information

Update contract addresses in README

---

docs/api_walkthrough.rst
docs/overview_and_guide.rst

I changed the documentation to discourage the more complicated source
installations for non-raiden developers.

Rework the install section of the docs

---

raiden/ui/web/package.json
raiden/ui/web/src/app/app.component.html
raiden/ui/web/src/app/app.component.ts
raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.html
raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
raiden/ui/web/src/app/components/home/home.component.html
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
raiden/ui/web/src/app/components/swap-dialog/swap-dialog.component.ts
raiden/ui/web/src/app/components/token-network/token-network.component.html
raiden/ui/web/src/app/components/token-network/token-network.component.ts
raiden/ui/web/src/app/components/transfer-dialog/transfer-dialog.component.ts
raiden/ui/web/src/app/models/channel.ts
raiden/ui/web/src/app/models/usertoken.ts
raiden/ui/web/src/app/models/withmenu.ts
raiden/ui/web/src/app/pipes/token.pipe.spec.ts
raiden/ui/web/src/app/pipes/token.pipe.ts
raiden/ui/web/src/app/services/raiden.config.ts
raiden/ui/web/src/app/services/raiden.interceptor.ts
raiden/ui/web/src/app/services/raiden.service.ts
raiden/ui/web/src/app/services/shared.service.ts

Small improvements in webUI efficiency and consistency:
- better union typing across models
- decrease number of requisitions for basic token fetching (e.g. on dialogs, which only needs simple token info)
- Better and more consistent token information across token lists (now, using format `[symbol] name (address)` for all tokens list)
- Better use of `/connection` API when needed
- Use of http interceptors for `busy` indicator
- Better use of async behavior when getting token information

webUI: improvements and fixes

---

docs/changelog.rst
raiden/channel/netting_channel.py
raiden/network/rpc/client.py
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/tests/smart_contracts/test_channel_manager.py
raiden/tests/unit/test_channel.py
raiden/tests/utils/apitestcontext.py
raiden/tests/utils/tester_client.py

Remove settled attribute

---

.travis.yml
tools/testnet/files/dockerfiles/geth-testnet/Dockerfile

@ulope Please check if all docker locations were also modified.
Fix https://github.com/raiden-network/raiden/issues/1034

Use geth 1.7.0

---

docs/changelog.rst
docs/conf.py
raiden/network/sockfactory.py
raiden/network/stunsock.py
raiden/network/upnpsock.py
raiden/ui/cli.py
raiden/utils/echo_node.py
requirements.txt

Fixes #870 
Also includes a small drive-by docs config fix.

User selectable NAT traversal

---

raiden/network/rpc/client.py
raiden/tests/unit/test_channel.py

It's really a mystery how they made it into master.

Fix some flake8 errors.

---

docs/changelog.rst
docs/rest_api.rst
raiden/api/rest.py
raiden/tests/api/test_api.py

Add `errors` field in unsuccesful rest api responses

---

docs/changelog.rst
raiden/ui/cli.py

Some small additions after #882.
- Turn sync check on by default
- More info on sync message
- Add missing changelog entry

Small fixes to sync check

---

raiden/ui/cli.py

Fixes https://github.com/raiden-network/raiden/issues/1037

added show_defaults to some cli options

---

tools/deploy.py

Make deploy script gas price configurable instead of using the ridiculous pyethapp default of 60 GWei.

Make deploy script gas price configurable

---

docs/index.rst
docs/smart_contracts.rst

First attempt at documenting the deployment, usage, and verification of the smart contracts.
Architecture remains TODO.
I'm not really happy with the verification section but for now, have no better idea how to structure it.

Initial smart contract docs

---

docs/api_walkthrough.rst
docs/changelog.rst
docs/rest_api.rst
raiden/api/rest.py
raiden/ui/web/src/app/services/raiden.service.ts

Rename /connection endpoint to /connections

---

docs/changelog.rst
raiden/constants.py
raiden/network/rpc/client.py
raiden/raiden_service.py
raiden/smart_contracts/NettingChannelContract.sol
raiden/tests/api/test_api.py
raiden/tests/smart_contracts/netting_channel/test_invariants.py
raiden/tests/utils/apitestcontext.py
raiden/tests/utils/tester.py
raiden/tests/utils/tester_client.py

Settle timeout upper limit

---

raiden/smart_contracts/ChannelManagerContract.sol
raiden/smart_contracts/ChannelManagerLibrary.sol
raiden/smart_contracts/EndpointRegistry.sol
raiden/smart_contracts/HumanStandardToken.sol
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/smart_contracts/Registry.sol
raiden/smart_contracts/Token.sol
raiden/smart_contracts/Utils.sol

fixed solc 0.4.17 warnings

---

.travis.yml
raiden/smart_contracts/EndpointRegistry.sol
raiden/smart_contracts/HumanStandardToken.sol
raiden/smart_contracts/StandardToken.sol

https://github.com/raiden-network/raiden/pull/1056 Missed some files

Solc 0 4 17

---

raiden/ui/cli.py

The blockchain service is no longer querying the blockchain for the
discovery address, so the previous message about the json rpc interface
was not working.
This adds an explicit function for checking if the JSON RPC interface is
enabled and a temporary check disabling the Parity client.

Checking the JSON RPC interface is working.

---

docs/glossary.rst

Add missing bracket in glossary

Add missing bracket in glossary

---

CONTRIBUTING.md

Mention the documentation style in CONTRIBUTION.md

[skip ci] Mention the documentation style in CONTRIBUTION.md

---

raiden/network/rpc/client.py
raiden/tests/fixtures/blockchain.py
raiden/tests/integration/test_blockchainservice.py
raiden/tests/utils/blockchain.py
raiden/ui/cli.py
raiden/utils/events.py
requirements.txt
tools/deploy.py
tools/init_blockchain.py
tools/transfer_eth.py

removed unused methods / properties:
- new_abi_contract
- coinbase
- find_block
removed patches:
- patch_send_transaction
- patch_send_message

JSON RPC Client cleanup

---

raiden/__main__.py
raiden/accounts.py
raiden/api/python.py
raiden/api/rest.py
raiden/app.py
raiden/blockchain/abi.py
raiden/network/channelgraph.py
raiden/network/rpc/client.py
raiden/network/sockfactory.py
raiden/network/upnpsock.py
raiden/tests/api/test_api.py
raiden/tests/benchmark/speed_decoding.py
raiden/tests/integration/test_settlement.py
raiden/tests/unit/test_accounts.py
raiden/tests/unit/test_service.py
raiden/tests/unit/test_statechange_log.py
raiden/tests/utils/apitestcontext.py
raiden/tests/utils/genesis.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/tests.py
raiden/tests/utils/transfer.py
raiden/transfer/log.py
raiden/ui/cli.py
raiden/ui/console.py
raiden/utils/echo_node.py
raiden/utils/profiling/sampler.py
raiden/utils/profiling/stack.py

Changed most strings to the single quote style

standardized code to single quotes

---

raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py

Review after #1111 
Fixed a few issues with the REST api that bothered static linting and streamlined the route declaration.

Restapi cleanup

---

CONTRIBUTING.md

Add dict/list init style rule

---

raiden/blockchain/abi.py
raiden/tests/conftest.py
raiden/ui/cli.py

Solc check

---

docs/macos_install_guide.rst
docs/overview_and_guide.rst
raiden/network/transport.py
raiden/tests/conftest.py
raiden/tests/fixtures/api.py
raiden/tests/utils/blockchain.py
raiden/tests/utils/network.py

Cherry-picked from #1101 
This only fixes the macOS test issues, travis setup will be handled in #1130 
Fixes: #1021

Fix tests on macOS

---

raiden/network/proxies/token.py

Approve check

---

raiden/tests/unit/test_accounts.py

Found some missing asserts in the account tests.

Add missing asserts in account tests

---

raiden/tests/integration/rpc/RpcTest.sol
raiden/tests/integration/rpc/test_assumptions.py

This tests that a filter with a given from_block parameter includes events from this block.
@hackaugusto Is this what you had in mind?

Including filter from assumption test

---

.gitignore
Makefile
README.rst
docs/changelog.rst
raiden.spec
raiden/api/rest.py
raiden/utils/__init__.py
requirements.txt
setup.py
tools/pyinstaller_hooks/hook-Crypto.py
tools/pyinstaller_hooks/hook-bitcoin.py
tools/pyinstaller_hooks/hook-raiden.py
tools/pyinstaller_hooks/runtime_encoding.py
tools/pyinstaller_hooks/runtime_pyeth.py

PyInstaller macOS bundle generation

---

raiden/network/rpc/client.py

Move the reconnect decorator out of the RPCClient class body

---

.travis.yml
.travis/before_install.sh
.travis/download_geth.sh
.travis/download_solc.sh
.travis/install.sh
.travis/prepare_os_linux.sh
.travis/prepare_os_osx.sh
docs/overview_and_guide.rst

Another try, hopefully we have figured out all problems by now.

Enable macOS packaging on travis

---

tools/deploy.py

4 wei gas price is never gonna get mined :)
Related to https://github.com/raiden-network/raiden/issues/1166

Deploy.py gas price is in gwei.

---

CONTRIBUTING.md

Merge after the CLA setup is done.

Add information about CLA and the signing process [skip ci]

---

README.rst

Changed http:// to https:// on some links in README.rst

Changed http:// to https:// on some links

---

raiden/ui/web/src/app/services/raiden.service.ts

webUI: Better error messages for http responses

---

raiden/tests/unit/test_cli.py
raiden/ui/cli.py

fixes #937 `removedb` sanity checks assumes incorrect prefix

---

raiden/tests/conftest.py
raiden/tests/fixtures/tester.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/tester.py

Bring back `pytest` as of https://github.com/raiden-network/raiden/pull/1175#issuecomment-349830900

Remove the pytest requirement in smoketest

---

raiden/tests/unit/test_channel.py

The test was made for DirectTransfers with a secret field. It was the
case that direct transfers could have a secret field and that the secret
was registered *before* the transfer message was fully validated.
Since then direct transfers don't have the secret field anymore, so the
incosistent state is not reachable anymore.
- The test was introduced by: baad50952173ef75b681ad6de09d9e31f0f9b54e
- The bug was fixed by: 9d341acb885360fb20d7a33adb6081f83cc59c84
- Direct transfer's secret field removed by: 05e79d9eda8f850a019893432ba12d78c2de07bf

Removed test test_register_invalid_transfer

---

raiden/exceptions.py
raiden/network/blockchain_service.py
raiden/network/proxies/channel_manager.py
raiden/network/proxies/discovery.py
raiden/network/proxies/netting_channel.py
raiden/network/proxies/registry.py
raiden/network/proxies/token.py
raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/network/rpc/transactions.py
raiden/tests/fixtures/blockchain.py
raiden/tests/integration/rpc/test_assumptions.py
raiden/tests/integration/test_blockchainservice.py
raiden/tests/smart_contracts/netting_channel/test_invariants.py
raiden/tests/utils/tester_client.py
raiden/ui/console.py
tools/deploy.py
tools/init_blockchain.py

This change forces the code to be explicit about doing a transaction or
a call, and removes the magic used in the proxy constructor to set its
attributes

Remove the method proxy magic

---

requirements.txt
setup.py

Use a, hopefully temporary, fork of pystun for python3 compatibility

Use a forked pystun repo for py3 compatibility

---

raiden/network/proxies/channel_manager.py
raiden/network/rpc/client.py
raiden/network/rpc/filters.py
raiden/network/rpc/smartcontract_proxy.py
raiden/tests/integration/rpc/test_assumptions.py
raiden/ui/console.py
raiden/utils/__init__.py
raiden/utils/events.py
raiden/utils/typing.py

This adds more type annotations and fixes some smaller issues I found on the way.

Add type annotations, smaller cleanups

---

raiden/token_swap.py

Remove async result from TakerTokenSwap

---

raiden/network/rpc/smartcontract_proxy.py
raiden/tests/integration/rpc/test_assumptions.py

Update forgotten docstrings

---

raiden/tests/integration/rpc/test_assumptions.py

Test case to simulate issue #1061

added test for duplicated transactions

---

requirements.txt

This avoids #1235 in the future.
Fixes #1235

Fix the marshmallow version.

---

.github/ISSUE_TEMPLATE

Changed our issue template to target our users instead of being a template for our description of tasks.

[skip ci] simplified default issue template

---

docs/overview_and_guide.rst

Add a warning for upgrading from python 2 to python 3

---

requirements.txt
setup.py

The pypi problem is now fixed: https://github.com/mbr/tinyrpc/issues/45

Bump tinyrpc to 0.8

---

docs/overview_and_guide.rst

Update the linux docs for the pyinstaller binary.

Fix linux package docs [skip-ci]

---

docs/changelog.rst
raiden/api/rest.py

Json error for invalid endpoint

---

docs/changelog.rst

Add some bug fixes that weren't mentioned before.

Add bugfixes to changelog [skip ci]

---

raiden/utils/typing.py

Added types:
- secret
- signature
- keccak256
- block_number
- token_amount

Added some types

---

raiden/storage/serialize.py
raiden/storage/sqlite.py
raiden/storage/wal.py

Introduces the WAL class. This is the entry point of state changes for the app.
The `PickleSerializer` and `SQLiteStorage` classes are almost identitical, the biggest change is the breaking in the `SQLiteStorage` interface (get methods were renamed and return values changed).

Single entry wal

---

raiden/transfer/state.py
raiden/transfer/state_change.py

This PR introduces the state objects used to represent the registry / channel manager and an umbrela state object to hold the whole app state.

State hierarchy

---

.travis.yml
.travis/prepare_os_osx.sh

Fix macOS deployment for good. 🎅

Fix macOS deployment (once more) [skip ci]

---

raiden/messages.py

these methods will be used on the event handler.

added utility methods to convert messages

---

raiden/tests/unit/test_channel.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/state.py

Merge/Review after: #1272 
Review with care

Channel logic

---

raiden/transfer/state_change.py
raiden/transfer/token_network.py

Token Network logic

---

raiden/transfer/events.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/state.py
raiden/transfer/state_change.py

added `__repr__` , `__eq__` and `__ne__` to most `State`, `StateChange` and `Event` classes

Utility methods

---

raiden/network/protocol.py
raiden/tests/api/test_pythonapi.py
raiden/tests/unit/test_transfer.py
raiden/transfer/state.py
raiden/transfer/views.py

These are shortcut functions, used to get state for a given node.

State views

---

raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/state_change.py

Added changes to the initiator state machine that are required to integrate with the new channel state.
Functions name ending with a  `2` will be renamed and replace the alternative in the future.

Initiator logic

---

CONTRIBUTING.md

Python requirement updated in CONTRIBUTING.md

---

raiden/transfer/mediated_transfer/target.py

Target logic

---

raiden/tests/unit/test_channelstate.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/state_change.py

Test channel state

---

raiden/waiting.py

Functions to wait until blockchain events are processed

waiting utilites

---

raiden/messages.py
raiden/raiden_event_handler.py

Handlers for `Event` objects. This is the code responsible to do IO triggered by events emitted after processing a `StateChange`

raiden event handler

---

raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/mediated_transfer/target.py

The new init state changes were not introduced by #1290 #1291 #1292

Fixed initiator/mediator/target init state changes

---

raiden/transfer/node.py
raiden/transfer/state_change.py

Entry point for the state changes.
All state changes will be dispatched through a single write-ahead-log instance, this is the top-level logic  used to handle all state changes.

added node logic

---

raiden/tests/unit/transfer/mediated_transfer/test_mediator.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/factories.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/state_change.py

Mediatorstate tests

---

raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py

Target state tests

---

.travis.yml
requirements.txt
tools/testnet/files/dockerfiles/raiden/Dockerfile

Update pyethereum, supports solc 0.4.21 now

Update pyethereum, supports solc 0.4.21 now

---

raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/api/test_pythonapi_regression.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/test_settlement.py
raiden/tests/integration/transfer/test_directransfer_events.py
raiden/tests/integration/transfer/test_directransfer_invalid.py
raiden/tests/integration/transfer/test_directtransfer_statechanges.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/tester.py
raiden/tests/utils/transfer.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediator.py
tools/scenario_runner.py

These are some commits which were added to https://github.com/raiden-network/raiden/pull/1329 right before approval but somehow got lost in the rebase I suppose. 
Thankfully I found them laying around in my local repo and cherry picked them.
@hackaugusto can you take a quick look?

Missed commits

---

raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/transfer/token_network.py

Implements the dynamic dispatching style suggested by @schmir on #1308
Review only after #1329 has been merged

Dynamic dispatch with type

---

raiden/network/proxies/channel_manager.py
raiden/network/rpc/client.py
raiden/network/rpc/filters.py
raiden/network/rpc/smartcontract_proxy.py
raiden/routing.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/views.py
raiden/utils/__init__.py
raiden/utils/typing.py

capitalized type names

---

docs/changelog.rst
raiden/constants.py
raiden/ui/cli.py

Fix https://github.com/raiden-network/raiden/issues/1328

Separate dbdir per network

---

raiden/messages.py
raiden/tests/unit/test_binary_encoding.py
raiden/tests/unit/test_dict_encoding.py
raiden/tests/unit/test_messages.py

This can be used to json encode the messages

Added methods to encode and decode messages to and from dicts

---

docs/Thoughts-on-Performance.md
docs/spec.rst
raiden/encoding/messages.py
raiden/messages.py
raiden/network/protocol.py
raiden/tests/benchmark/speed_decoding.py
raiden/tests/unit/test_binary_encoding.py
raiden/tests/unit/test_operators.py
raiden/tests/unit/test_service.py
raiden/udp_message_handler.py

For this issue: https://github.com/raiden-network/raiden/issues/1341

Rename 'Ack' messages and logic to 'Processed'

---

raiden/utils/typing.py

Fix for https://github.com/raiden-network/raiden/pull/1342/files#r182083553

Fix an oversight in new type definitions

---

raiden/connection_manager.py

ConnectionManager: Use partner_state.address

---

raiden/encoding/messages.py
raiden/messages.py
raiden/raiden_event_handler.py
raiden/tests/benchmark/speed_decoding.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/test_settlement.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/smart_contracts/netting_channel/test_withdraw.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_dict_encoding.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/tests/utils/factories.py
raiden/tests/utils/messages.py
raiden/tests/utils/transfer.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/udp_message_handler.py

the state objects are already named lockedtransfer

renamed mediatedtransfer -> lockedtransfer fix #140

---

raiden/encoding/messages.py
raiden/messages.py
raiden/network/protocol.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/unit/test_binary_encoding.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_service.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/tests/utils/transfer.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/transfer/state_change.py
raiden/udp_message_handler.py
raiden/utils/typing.py

Processed send

---

raiden/app.py
raiden/encoding/signing.py
raiden/messages.py
raiden/network/blockchain_service.py
raiden/network/matrixtransport.py
raiden/network/protocol.py
raiden/network/utils.py
raiden/raiden_service.py
raiden/tests/api/test_pythonapi.py
raiden/tests/api/test_restapi.py
raiden/tests/benchmark/speed_simulation.py
raiden/tests/fixtures/__init__.py
raiden/tests/fixtures/matrix.py
raiden/tests/fixtures/raiden_network.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/conftest.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/long_running/flaky/test_token_networks.py
raiden/tests/utils/matrix.py
raiden/tests/utils/network.py
raiden/ui/cli.py
raiden/utils/__init__.py
raiden/utils/cli.py
raiden/utils/echo_node.py
requirements-dev.txt
requirements.txt
setup.py
tools/scenario_runner.py

This is an implementation of the Raiden protocol on Matrix.
* Fixes #1378 
* Fixes #1379
* Fixes #1377
* Refs #1387 
* Refs #1381
* **Requires** raiden-network/raiden-libs#85 ✅

Matrix protocol

---

raiden/api/rest.py
raiden/ui/cli.py

- gevent's WSGI server can only work with stdlib logger

Fix WSGI log

---

.travis.yml

This code was not working anyway.
Made some experiments in [this](https://github.com/raiden-network/raiden/compare/work_on_cronjobs) upstream branch but they were very unsuccesfull, so I would not recommend to use Travis for cron jobs at this time.
All the daily cron jobs I scheduled, apart from the first had failed.
Perhaps Travis has issues right now. I will test cron jobs with the aforementioned branch again later.

Remove travis cron code

---

raiden/api/python.py
raiden/api/rest.py
raiden/blockchain/abi.py
raiden/blockchain/events.py
raiden/blockchain_events_handler.py
raiden/network/proxies/discovery.py
raiden/network/proxies/netting_channel.py
raiden/network/rpc/client.py
raiden/network/rpc/filters.py
raiden/network/rpc/smartcontract_proxy.py
raiden/raiden_event_handler.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/rpc/test_assumptions.py
raiden/tests/integration/test_blockchainservice.py
raiden/tests/integration/test_echo_node.py
raiden/tests/integration/test_events.py
raiden/tests/integration/test_pythonapi.py
raiden/transfer/state.py
raiden/utils/__init__.py
raiden/utils/echo_node.py
raiden/utils/events.py

- removes ContractTranslator and replaces it with compatible eth_* libs
calls

Remove pyethereum's ContractTranslator

---

requirements.txt

Remove rlp dependency

---

raiden/accounts.py
raiden/log_config.py
raiden/routing.py
raiden/tests/conftest.py
raiden/ui/cli.py
raiden/utils/cli.py
tools/create_compilation_dump.py
tools/deploy.py
tools/testnet/files/dockerfiles/geth-testnet/run.py
tools/testnet/files/dockerfiles/raiden/raiden
tools/testnet/files/dockerfiles/raiden/raiden_echo_node

This restores the ability to configure log levels from the CLI

 Re-add CLI log level configurability

---

raiden/network/rpc/client.py

In the end this turned out to be smallish PR: rpc client and contract proxy basically reimplement stuff that's in `web3` already and without some refactoring there isn't much to do
One way forward would be removing `JSONRPCClient`'s methods from like `send_transaction` or `eth_estimateGas` from proxy constructor arguments and use `web3.eth.contract` internally in the proxies - I'll leave this open to discussion.

Use `web3.contract.constructor` for deploy

---

raiden/network/matrixtransport.py

Hey @ulope can you check this small PR? Structlog does not have `trace()` and also we decided to not have the `isEnabledFor()` checks.

Matrix logging fixes

---

raiden/messages.py
raiden/ui/cli.py
raiden/utils/cli.py
requirements.txt

This add a command line parameter for the expected network id.
It also adds code to calculate the signature of the new balance proof.
Fixes #1476

Add network id, new BP signature code

---

raiden/raiden_service.py

removed useless attribute from raiden service.

removed _block_number

---

raiden/network/rpc/smartcontract_proxy.py

How the fuck was this error introduced and passed Travis? My other PR is failing on flake8 tests for this right now: https://travis-ci.org/raiden-network/raiden/jobs/388245320

Fix flake8 errors in rpc proxies

---

raiden/network/rpc/client.py

Remove warning about data parameter encoding

---

raiden/api/python.py
raiden/network/blockchain_service.py
raiden/network/discovery.py
raiden/network/matrixtransport.py
raiden/network/proxies/channel_manager.py
raiden/network/proxies/discovery.py
raiden/network/proxies/registry.py
raiden/network/proxies/token.py
raiden/network/transport/udp/udp_transport.py
raiden/raiden_service.py
raiden/routing.py
raiden/utils/__init__.py

Get rid of all usages of `raiden.utils.isaddress` function

Remove usage of raiden.utils.isaddress function

---

raiden/blockchain/events.py
raiden/network/proxies/channel_manager.py
raiden/network/proxies/netting_channel.py
raiden/network/proxies/registry.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/rpc/filters.py
raiden/tests/integration/rpc/test_assumptions.py

Simplify some code around the current filters, making it easier to change in the future.

Simplify the current filtering code

---

raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py

Update new contracts to use web3 contract call()

---

raiden/network/blockchain_service.py
raiden/network/rpc/client.py
raiden/ui/cli.py
raiden/utils/__init__.py

Get rid of all usages of raiden.utils.quantity_decoder function.

Remove usage of raiden.utils.quantity_decoder function

---

raiden/blockchain/events.py
raiden/blockchain_events_handler.py
raiden/messages.py
raiden/network/matrixtransport.py
raiden/network/proxies/channel_manager.py
raiden/network/proxies/netting_channel.py
raiden/network/proxies/registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/test_blockchainservice.py
raiden/tests/utils/smoketest.py
raiden/ui/cli.py
raiden/utils/__init__.py

Get rid of all usages of raiden.utils.address_decoder function.

Remove usage of raiden.utils.address_decoder function

---

raiden/network/proxies/__init__.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py

Add PaymentChannel as a replacement for the NettingChannel

---

.travis.yml
raiden/constants.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network_registry.py
raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/tests/integration/contracts/conftest.py
raiden/tests/integration/contracts/fixtures/__init__.py
raiden/tests/integration/contracts/fixtures/contracts.py
raiden/tests/integration/contracts/test_network_registry.py
raiden/tests/integration/contracts/test_secret_registry.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/utils/__init__.py
raiden/utils/__init__.py

Unit tests for contract proxies

---

raiden/api/rest.py
raiden/network/proxies/registry.py
raiden/network/rpc/smartcontract_proxy.py
raiden/network/transport/udp/healthcheck.py
raiden/network/transport/udp/udp_transport.py
raiden/network/transport/udp/udp_utils.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/routing.py
raiden/tests/integration/rpc/test_assumptions.py
raiden/tests/utils/transfer.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/udp_message_handler.py
raiden/ui/cli.py
raiden/utils/__init__.py
raiden/waiting.py

- Running flake8 outside the venv seems to have shown a lot more errors than running it inside the venv. Curious ... we should figure out why this happened
- Fixed a bug (seen thanks to flake8) where an empty list was given as the default argument.

Flake8 fixes and a tiny bug fix

---

raiden/api/python.py

Super small change I noticed while working on my current issue

Fix batch close timeout message

---

Makefile
raiden/encoding/signing.py
raiden/network/matrixtransport.py
raiden/tests/fixtures/variables.py
raiden/tests/utils/blockchain.py
raiden/transfer/mediated_transfer/transition.py
raiden/utils/profiling/profiler.py
requirements-dev.txt
setup.cfg
tools/config_builder.py
tools/process_results.py
tools/startcluster.py

This adds
- [flake8-tuple](https://github.com/ar4s/flake8_tuple)
- [flake8-bugbear](https://github.com/pycqa/flake8-bugbear)
and fixes the issues reported by them.

More flake8

---

docs/rest_api.rst
raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/connection_manager.py
raiden/network/proxies/netting_channel.py
raiden/smart_contracts/NettingChannelContract.sol
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/test_blockchainservice.py
raiden/tests/integration/test_events.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/utils/network.py
raiden/ui/console.py

Still some things to test -- WIP for now.
Fix #1539

Make deposit idempotent

---

raiden/network/matrixtransport.py
requirements.txt
setup.py
tools/install_synapse.sh

Requires https://github.com/raiden-network/raiden-libs/pull/95

Matrix logout

---

raiden/encoding/messages.py
raiden/smart_contracts/NettingChannelLibrary.sol
raiden/tests/unit/test_channelstate.py
raiden/transfer/merkle_tree.py

fixes https://github.com/raiden-network/raiden/issues/1599

Change expiration from uint64 to uint256

---

raiden/tests/integration/contracts/test_token.py
raiden/tests/integration/contracts/test_token_network.py

- Fixes test failures that happen with tester backend

Update contract tests

---

raiden/ui/cli.py
raiden/ui/console.py
raiden/waiting.py
tools/deploy.py

Fixes in this PR allowed me to be able to run Raiden on a local geth node as well as running console which have tools that i used for deploying a token ... etc

Raiden private node & console fixes

---

raiden/encoding/messages.py
raiden/messages.py
raiden/network/matrixtransport.py
raiden/raiden_service.py
raiden/tests/conftest.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/conftest.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/unit/test_binary_encoding.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_dict_encoding.py
raiden/tests/unit/test_messages.py
raiden/tests/unit/test_operators.py
raiden/tests/utils/factories.py
raiden/tests/utils/transfer.py
raiden/ui/cli.py
requirements.txt
setup.py

- Better validation of signatures, uses `eth_sign` format/hasher
- Check for room parameters before joining, to avoid joining invalid/multiple rooms
- Makes `sender` a cached property calculated from signature. Fix #1431

Matrix improvements

---

raiden/transfer/channel.py

Fix BalanceProofData type definition [skip ci]

---

raiden/raiden_service.py

fixed the log line, these are not blockchain events, but raiden events.

fixed typo

---

raiden/api/objects.py

Just so I don't have to fix this in each PR.

Fix last magic comment [skip ci]

---

raiden/blockchain/events.py
raiden/blockchain_events_handler.py
raiden/storage/wal.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/state_change.py

Secret registry state machine

---

raiden/accounts.py
raiden/blockchain/state.py
raiden/network/proxies/channel_manager.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/state_change.py
raiden/ui/console.py
tools/ansible/contrib/inventory/ec2.py
tools/deploy.py
tools/scenario_runner.py

I used [lgtm.com](https://lgtm.com/projects/g/raiden-network/raiden/) which has already ran a few times in our project. 
- Fixed some minor issues
- Fixed bug in comparison of `ActionCancelRoute`
- Fixed shadowing of variables in inner loops in ec2.py
- Removed unused `maximum_expiration` assignment in `handle_transferrefundcancelroute`

Lgtm linter error fixes

---

raiden/network/proxies/secret_registry.py
raiden/tests/integration/contracts/test_secret_registry.py

- no parallel secret registration is allowed
- Fixes #1593

Add lock for SecretRegistry

---

raiden/log_config.py

- 3rd party loggers propagate to root
- logs are formatted by the same set of processors as raiden logs

Enable logging for 3rd party modules

---

raiden/tests/utils/smoketest.py
raiden/ui/cli.py
raiden/utils/deployment.py
tools/deploy.py

Deploy contracts for smoke tests

---

raiden/ui/cli.py

A few small improvements to make the smoketest behave a bit more user-friendly

Improve smoketest usability and error reporting

---

raiden/blockchain/events.py
raiden/network/blockchain_service.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/network/rpc/smartcontract_proxy.py
raiden/raiden_event_handler.py
raiden/tests/integration/contracts/test_payment_channel.py
raiden/tests/integration/contracts/test_token_network.py
raiden/tests/integration/test_blockchainservice.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/utils/filters.py
requirements-dev.txt

Add payment channel fn

---

raiden/blockchain/events.py

This will be needed for the contracts migration.

Add listener function for payment channels

---

raiden/tests/fixtures/variables.py
raiden/tests/integration/fixtures/backend_geth.py
raiden/tests/integration/fixtures/backend_tester.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/utils/network.py
raiden/tests/utils/smartcontracts.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/tests.py

just simplified a bit the fixtures

Fixtures reorg

---

.bumpversion_contracts.cfg
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/settings.py

Version checks

---

.travis.yml
raiden/network/matrixtransport.py
raiden/tests/integration/conftest.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/test_files/synapse-config.yaml
raiden/tests/utils/patch_connection_pool.py
raiden/tests/utils/transfer.py
tools/install_synapse.sh

Fix matrix tests

---

tools/install_synapse.sh

Should fix incompatible version being cached in Travis and locally

Switch to a commit-versioned synapse binary naming

---

raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py

Fix matrix tests 2

---

raiden/blockchain/abi.py
raiden/network/proxies/discovery.py
raiden/network/proxies/registry.py
raiden/network/proxies/token_network_registry.py
raiden/network/rpc/client.py
raiden/tests/integration/conftest.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/test_endpointregistry.py
raiden/tests/utils/geth.py
raiden/tests/utils/network.py
raiden/tests/utils/smartcontracts.py
raiden/ui/cli.py
raiden/utils/deployment.py
requirements.txt
setup.py

Add new fixtures to deploy the new smart contracts
merge after: #1671

Deploy new smart contracts

---

raiden/tests/integration/test_echo_node.py

adds a wait to give the test a chance to sync w/ matrix transport

Fix flaky `fix_event_transfer_received_success`

---

config_sample.toml
raiden/accounts.py
raiden/ui/cli.py
raiden/utils/__init__.py
raiden/utils/cli.py
requirements.txt

- Add default config file at `{datadir}/config.toml`
- Improve / fix error messages and / or spelling.
- Switch from `toml` to `pytoml` to get better error reporting

Config file follow up

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/transfer/mediated_transfer/mediator.py

Resolves #1682.
Blocked by #1653

Secret reveal tests

---

raiden/tests/integration/test_settlement.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py

Remove events for channel close

---

raiden/api/python.py

Fix leaving a token network

---

raiden/transfer/state_change.py

- ContractReceiveBatchUnlock
- ReceiveDelivered
- ReceiveProcessed

added missing dunder methods

---

raiden/tests/unit/test_channelstate.py

Re-adding:
- `test_channel_unlock_must_not_change_merkletree`
- `test_refund_transfer_matches_received`
- `test_refund_transfer_does_not_match_received`

Readd vanished channelstate unit tests

---

raiden/api/python.py
raiden/api/rest.py
raiden/exceptions.py
raiden/tests/integration/api/test_restapi.py

Fixes #1720 
⚠️ ~~Should be merged after the new contracts branch has been merged.~~

Add token limit

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py

This is just the test, it does not contain the fix

added failling test case for #1736

---

docs/rest_api.rst
raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/tests/integration/api/test_restapi.py

Most changes have been done by Lefteris already.
This also adds some more tests and fixes minor bugs.
Fixes #1669, #1690, #1689

Update REST API

---

raiden/network/rpc/client.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/contracts/fixtures/contracts.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/utils/smartcontracts.py
raiden/tests/utils/smoketest.py

Fix timing hack in smoketest

---

raiden/network/transport/matrix.py

Fix `MatrixTransport::_bound_logger` initialization

---

raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/contracts/fixtures/contracts.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/test_endpointregistry.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/utils/smartcontracts.py
raiden/tests/utils/smoketest.py

I have removed the *args in deploy_contract_web3 method.

replaced args with constructor arguments tuple [CI integration]

---

.travis/run.sh
.travis/run_smoketest.sh
raiden/ui/cli.py

Matrix default

---

raiden/app.py
raiden/constants.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/raiden_service.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/contracts/test_network_registry.py
raiden/tests/integration/contracts/test_payment_channel.py
raiden/tests/integration/contracts/test_token_network.py
raiden/tests/utils/network.py
raiden/ui/cli.py

Update settlement timeouts

---

raiden/exceptions.py
raiden/storage/sqlite.py
raiden/ui/cli.py

Provide a proper error if DB contains invalid data

---

raiden/network/transport/matrix.py

We're logging received messages at info level as well, and this is helpful for debugging stuff.

Log message sending at info level

---

raiden/ui/web/package.json
raiden/ui/web/src/app/app.component.html
raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/components/license/license.component.html
raiden/ui/web/src/app/components/license/license.component.spec.ts
raiden/ui/web/src/app/components/license/license.component.ts

Add license in the ui

---

raiden/ui/cli.py

Add experimental software disclaimer

---

raiden/api/rest.py
raiden/tests/integration/api/test_restapi.py

Fix and test channel events endpoint

---

raiden/ui/web/src/app/components/token-network/token-network.component.html

Temporarily remove the token swaps from the WebUI

---

raiden/blockchain/events.py
raiden/blockchain_events_handler.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/tests/conftest.py
raiden/tests/integration/contracts/test_payment_channel.py
raiden/tests/integration/test_settlement.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_wal.py
raiden/transfer/channel.py
raiden/transfer/node.py
raiden/transfer/state_change.py

Fix test batch unlock

---

raiden/constants.py
raiden/network/rpc/client.py

Lets start testing with factor 2, if that's not enough we can increase it further.
Fixes #1814

Increase gas prices for ropsten by factor two

---

raiden/raiden_service.py

Add comment explaining why filters are queried at installation

---

docs/rest_api.rst
raiden/api/rest.py

Return HTTP 202 Accepted for endpoints when timeouts are reached

---

raiden/utils/__init__.py

removed unused functions/constants from the utils module

cleanup utils

---

raiden/api/python.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/raiden_event_handler.py
raiden/utils/__init__.py

This fixes the crash on restart reported here: https://github.com/raiden-network/raiden/issues/1807#issuecomment-404838827

simplified lock acquisition

---

raiden/encoding/messages.py
raiden/encoding/signing.py
raiden/messages.py

- make_mesage was not used anymore
- optional_secret was part of the direct transfer and was removed a long
time ago
- address_from_keyh was not used anymore
- the classmethod from_state was not used anymore

clean up messages

---

raiden/connection_manager.py
raiden/network/blockchain_service.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/long_running/flaky/test_token_networks.py
raiden/transfer/state_change.py
raiden/transfer/views.py

- also fixes minor typos and missing class members

Second fix for `test_token_networks.py`

---

raiden/network/transport/matrix.py

Ignore messages not signed by sender

---

raiden/app.py
raiden/exceptions.py
raiden/network/transport/matrix.py
raiden/network/utils.py
raiden/ui/cli.py
raiden/utils/gevent.py

Fixes #1793
This also lays groundwork for #1829 but doesn't fix it yet.

Handle unreachable matrix servers and disconnects more graceful

---

raiden/tasks.py
raiden/ui/cli.py

A thread is spawned to verify the version of the Raiden client periodically and see for any update. This is related to #1810

Added periodical verification of the version

---

.bumpversion_client.cfg
docs/conf.py
requirements.txt
setup.py

Bump version: 0.3.0 → 0.4.0

---

docs/changelog.rst

Add basic features for the 0.4 release

---

requirements-dev.txt
requirements.txt

We use this dependency also during runtime

Move mirakuru from dev to runtime deps

---

raiden/exceptions.py
raiden/network/rpc/smartcontract_proxy.py
raiden/tests/integration/rpc/test_assumptions.py
raiden/ui/cli.py

Resolves #1841 
Blocked by #1858

Handle replacement transaction underpriced

---

docs/changelog.rst
raiden/network/rpc/client.py
raiden/ui/cli.py

Check for ethnode connection at rpcclient start

---

Makefile
docker/build.Dockerfile
raiden/utils/__init__.py
setup.py

Fixes the linux half of #1893.

Fix automatic travis building of linux bundle

---

CONTRIBUTING.md

This new rule will apply to all new code we are adding to the project. No big refactor to adjust old code will be made. If PRs are touching old code then feel free to adjust it to this style.

Add leading underscore for private class members to contributing.md

---

docs/changelog.rst
docs/rest_api.rst
raiden/api/rest.py
raiden/connection_manager.py
raiden/exceptions.py

Handle negative funds error

---

raiden/tests/integration/contracts/test_token_network.py

Follow-up to #1959 
- remove possible gevent race
- indent

Make deposit race test deterministic

---

docs/changelog.rst
docs/overview_and_guide.rst
raiden/storage/sqlite.py
raiden/ui/cli.py

Remove removedb

---

raiden/log_config.py
raiden/tests/unit/test_logging.py

Redact access_token from any log lines

---

docs/api_walkthrough.rst
docs/rest_api.rst
raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/connection_manager.py

Remove only_receiving parameter from leave network API

---

docs/changelog.rst
requirements.txt
setup.py

Bump raiden libs version

---

docs/changelog.rst
raiden/tasks.py
raiden/tests/unit/test_version_check.py

I have added a security verification. In case of some security message that we want to send to the user, we could use {SECURITY: <message>}. [ci integration]

Security alert message

---

docs/changelog.rst
raiden/log_config.py
raiden/tests/unit/test_logging.py

That's what I came up with so far, but I don't find a way to always have debug log level for the file logger.
@ulope @pcppcp Can you have a look. You probably know how to fix that.
Fixes #1844

Add debug file logger

---

docs/changelog.rst
raiden/log_config.py
raiden/tests/unit/test_logging.py

Reverts raiden-network/raiden#1868

Revert "Add debug file logger"

---

.bumpversion_client.cfg
docs/conf.py
setup.py

Release 0.4.1

---

docs/changelog.rst
raiden/storage/sqlite.py
raiden/storage/utils.py
raiden/storage/wal.py
raiden/tests/unit/test_wal.py

Add db versioning and fix corrupt connect

---

docs/changelog.rst
raiden/log_config.py
raiden/tests/unit/test_logging.py

Fix #1844 
Now working **and** tested ;)
Thanks André for the help!
A thing I removed in the last commit is timestamping of the log file as it spammed my directory. But I'm open to bring it back if you think it's good to have.

Log to file

---

.travis.yml

Fix travis stage conditions

---

.travis.yml
.travis/run.sh

Add contract tests to unit test run

---

raiden/network/transport/matrix.py
raiden/tests/integration/fixtures/transport.py
raiden/ui/cli.py
raiden/utils/http.py
requirements.txt
setup.py

Use correct url to check for synapse availability

---

raiden/exceptions.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/raiden_event_handler.py
raiden/tests/integration/contracts/test_payment_channel.py
raiden/tests/integration/contracts/test_token_network.py

Perform check on channel identifier in close, update, settle and unlock

---

raiden/api/python.py

Timeouts should instead be used by the HTTP client (e.g. WebUI,
curl, httpie).
Timeouts were removed from:
- token_network_register
- channel_open
- Set Channel Deposit
- Channel Close
Resolves: #1971

Removes timeouts for onchain calls of the REST API

---

raiden/api/python.py

Add annotations to raiden.api.python

---

docs/changelog.rst
raiden/exceptions.py
raiden/network/discovery.py
raiden/network/proxies/discovery.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network_registry.py
raiden/ui/cli.py

Handle invalid/nocode/wrongcode contract address input

---

raiden/log_config.py
raiden/tests/unit/test_logging.py

Follow up to lefteris changes, adds some test coverage.

Test logging with --disable-debug-log

---

docker/build.Dockerfile

Fix linux bundle creation

---

raiden/api/rest.py

Fix #2052 
Not sure if we should update the release tag @LefterisJP

Check that total_deposit is not None

---

docs/conf.py

Fix release links in changelog

---

raiden/network/blockchain_service.py

It's really important that each Raiden instance only used one proxy per
smart contract, otherwise the proxy synchronization wont work. The token
network proxy is an example, where the proxy needs locking to forbid
concurrent deposits (to avoid races with the ERC20 allowance).
To enforce a singleton proxy the blockchain service is used as a proxy
factory. The problem was that each proxy constructor checks the
blockchain data, which does IO and allows another greenlet to run, this
made it possible for races among two greenlets that need the same proxy.
Tho fix the above race coarse locks were added to protected the
instantiaton of each type of proxy.

Fixed race for proxies instantiation

---

raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/test_integration_events.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_settlement.py
raiden/tests/integration/transfer/test_directransfer.py
raiden/tests/integration/transfer/test_directransfer_invalid.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/unit/conftest.py
raiden/tests/unit/fixtures.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/utils/transfer.py
raiden/transfer/channel.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/token_network.py
raiden/transfer/views.py

Multiple NettingChannelStates

---

docs/api_walkthrough.rst

This PR improves some language and grammar of the API walkthrough.
It also updates the API calls and answers where it was needed.
The echo node still remains to be fixed before the documentation regarding the echo node can be tested in order to see if it's still valid

update api walkthrough doc

---

docs/api_walkthrough.rst
docs/changelog.rst
docs/rest_api.rst
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/tests/integration/api/test_restapi.py

Fixes #2084 
@czepluch Please have a look at the docs

Rename /transfers to /payments

---

raiden/connection_manager.py

Check token balance before joining a token network

---

raiden/ui/cli.py

Fix requests connection adapter issue

---

raiden/routing.py
raiden/transfer/views.py

Fixes #2101
Please check that this is the right approach.

Fix routing through unavailable channels

---

raiden/api/python.py
raiden/api/rest.py
raiden/tests/unit/test_tokennetwork.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/token_network.py

Fixing some problems I found with post-merge review of #2038 

Fix stuff after 2038

---

raiden/connection_manager.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network.py
raiden/network/transport/matrix.py
raiden/network/transport/udp/udp_transport.py
raiden/network/transport/udp/udp_utils.py
raiden/raiden_service.py
raiden/tasks.py
raiden/tests/utils/tester.py
raiden/ui/cli.py
raiden/utils/echo_node.py
raiden/utils/gevent_utils.py
raiden/utils/notifying_queue.py
tools/scenario_runner.py

Followup from 2041 -- got a lot more children of _AbstractLinkable

---

docs/changelog.rst
raiden/api/rest.py

Catch InvalidAddress in /connect endpoint

---

raiden/network/transport/matrix.py
tools/install_synapse.sh

Remove unused argument address from send_async()

---

raiden/raiden_service.py
raiden/storage/wal.py
raiden/tests/unit/test_wal.py
raiden/transfer/views.py

Resolves #2086.
Follow up issue: #2133

Transaction queue replay

---

raiden/raiden_event_handler.py
raiden/raiden_service.py

Simplify identifier_to_results and remove assert

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

Bump version: 0.4.2 → 0.5.0

---

raiden/blockchain/events.py
raiden/network/proxies/payment_channel.py
raiden/tests/integration/contracts/test_payment_channel.py

Simplify payment channel unlock filter

---

raiden/tests/unit/test_tokennetwork.py

One new test to check if the proper unlock of an old channel removes the state.

Test unlock state pruning

---

docs/api_walkthrough.rst
docs/overview_and_guide.rst
docs/rest_api.rst
docs/webui_tutorial.rst

Solves https://github.com/raiden-network/raiden/issues/2167
Glossary still needs to be updated, but there's a separate issue for fixing that https://github.com/raiden-network/raiden/issues/2030

use payment instead of transfer in the docs

---

raiden/network/transport/matrix.py
raiden/tests/integration/fixtures/transport.py
requirements.txt
setup.py

Suppress teardown matrix error when synapse server is killed before greenlets finish

---

raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/test_send_queued_messages.py
raiden/waiting.py

Test queued messages send on restart

---

.travis.yml

- Linux: temporarily disable PyPI upload until user is reactivated
- macOS: Fix PATH

Fix automatic deployment

---

raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py

Send secret reveal once

---

raiden/raiden_event_handler.py
raiden/transfer/events.py

⚠️ This is a breaking change, we need to decide when we want to merge this

Fix typo in ContractSendChannelBatchUnlock

---

raiden/ui/cli.py

This PR solves: #2134 
The constant was added. 
The version is now part of the database name.

Added database version

---

raiden/blockchain_events_handler.py
raiden/tests/unit/test_channelstate.py
raiden/transfer/channel.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/token_network.py

Handle the ContractReceiveUpdateTransfer state change

---

docs/rest_api.rst
raiden/api/python.py
raiden/api/rest.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/test_pythonapi.py

Solved some of the problems we had when calling the raiden_events endpoints, after they were added in #1962 .
This fixes: #2186

Solved serialization bug

---

.travis.yml
MANIFEST.in
docker/build.Dockerfile
setup.py

Fix building the webui in the automated deployment

---

raiden/api/rest.py

This is a quickfix for #2229 . The slashes were removed to be consistent.

Redirect fix

---

raiden/ui/web/src/app/utils/amount.converter.spec.ts
raiden/ui/web/src/app/utils/amount.converter.ts

Fix rounding error when converting from decimal

---

docs/changelog.rst

Add missing changelog entries for Testnet 6 merged PRs

---

docs/changelog.rst
raiden/api/rest.py
raiden/utils/__init__.py

This makes addresses in the rest logging user readable.

Show user friendly addresses in logs

---

raiden/ui/web/src/app/services/channel-polling.service.ts
raiden/ui/web/src/app/services/raiden.service.ts

Notifications should display proper decimals instead of scientific notation
Fixes #2249

Fix the display of numbers on notifications

---

.travis.yml
raiden.spec

Hopefully finally fixes #1893 
Workaround for the Travis issues:
- travis-ci/travis-ci#6307
- travis-ci/travis-ci#6522
- travis-ci/travis-ci#9486

Fix travis mac deployment issue

---

raiden/blockchain/events.py
raiden/blockchain_events_handler.py
raiden/network/proxies/token_network.py
raiden/network/transport/matrix.py
raiden/raiden_service.py
raiden/transfer/node.py
raiden/transfer/views.py

Remove payment channels filter, get all token network contract events, filter on event handler

---

raiden/network/transport/matrix.py

Handle 404 on user presence check on matrix

---

raiden/ui/web/src/styles.css

Fixes notification font for Webui

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/transfer/mediated_transfer/mediator.py

the channel doesn't need to be closed to do an on-chain unlock anymore

removed dead code

---

docs/changelog.rst
raiden/ui/web/src/app/pipes/decimal.pipe.spec.ts
raiden/ui/web/src/app/pipes/decimal.pipe.ts

Show scientific notation for really small fractions of tokens

---

raiden/tests/integration/cli/test_cli.py

Fix cli tests after the addition of acknowledgement of disclaimer

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/transfer/mediated_transfer/mediator.py

This fixes a bug and introduces a unit test to gurantee the event is not
lost. The integration tests did caught the bug but where not executed
with the PR that introduced the bug.
[ci intregration]

bugfix: handle_refundtransfer must forward send refund event

---

docs/changelog.rst
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/mediated_transfer/initiator.py

arguments message_identifier and payment_identifier where swapped.

bugfix #2293

---

raiden/tests/integration/transfer/test_mediatedtransfer.py

Used the wrong annotation in my web3 PR. Thanks @andrevmatos for fixing this.

Fix skip test

---

docs/changelog.rst
raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.spec.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.html
raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.spec.ts
raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.ts
raiden/ui/web/src/app/components/join-dialog/join-dialog.component.html
raiden/ui/web/src/app/components/join-dialog/join-dialog.component.spec.ts
raiden/ui/web/src/app/components/join-dialog/join-dialog.component.ts
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.html
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.spec.ts
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.html
raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.spec.ts
raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.ts
raiden/ui/web/src/app/components/token-events/token-events.component.ts
raiden/ui/web/src/app/components/token-input/token-input.component.css
raiden/ui/web/src/app/components/token-input/token-input.component.html
raiden/ui/web/src/app/components/token-input/token-input.component.spec.ts
raiden/ui/web/src/app/components/token-input/token-input.component.ts
raiden/ui/web/src/app/modules/material-components/material-components.module.ts
raiden/ui/web/src/app/services/raiden.config.ts
raiden/ui/web/src/app/services/raiden.service.ts
raiden/ui/web/src/main.ts
raiden/ui/web/tslint.json

* Extracts the token input functionality to a new component.
* Adds tslint rule about console.log and removes console log entries.
* Adds handling for error when trying to read a missing decimal property https://github.com/raiden-network/raiden/issues/2197#issuecomment-415718934415718934
Closes #2251

Add webui support for switching token input between decimal and integer values

---

docs/glossary.rst

trying to clarify the definition of `balance_proof`.
also updating some wording and fixing some typos

updating glossary

---

docs/changelog.rst
raiden/ui/web/src/app/services/raiden.service.ts

* Return default values if call for optional field fails.
Closes #2336

Fixes webui wallet page not loading data due to error.

---

docs/changelog.rst
raiden/ui/cli.py

Don't merge yet. Just review. Waiting for some feedback on this PR.
Fixes #2340

Add accept disclaimer argument

---

docs/changelog.rst
raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/components/address-input/address-input.component.css
raiden/ui/web/src/app/components/address-input/address-input.component.html
raiden/ui/web/src/app/components/address-input/address-input.component.spec.ts
raiden/ui/web/src/app/components/address-input/address-input.component.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.spec.ts
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.html
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.spec.ts
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.html
raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.spec.ts
raiden/ui/web/src/app/components/register-dialog/register-dialog.component.html
raiden/ui/web/src/app/components/register-dialog/register-dialog.component.spec.ts
raiden/ui/web/src/app/components/register-dialog/register-dialog.component.ts
raiden/ui/web/src/app/services/raiden.service.ts

Add EIP55 address validation to dialogs

---

raiden/api/rest.py

Because the RestAPI is a wrapper around the Raiden service, it's
possible to stop the service before the API. This will lead to
unexpected results, since the API will accept REST requests but the
requests cannot be completed.
This adds a check prior to every request, to make sure the service is
running. Ideally, the Rest API and Raiden Service lifecycle would be
managed togheter, but this commit does not introduce the required
changes for this.

restapi: check the Raiden service is running

---

.travis.yml

travis: always show the current checkout commit

---

raiden/transfer/mediated_transfer/events.py

Added secrethash to easy debugging

---

raiden/api/rest.py

Fix two instances of uncaught exceptions in the Rest API

---

docs/changelog.rst
raiden/ui/web/src/app/app.component.html

Rename wallet to tokens in the WebUI

---

docs/changelog.rst
raiden/ui/web/src/app/app.component.html
raiden/ui/web/src/app/app.component.spec.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.html
raiden/ui/web/src/app/components/channel-table/channel-table.component.spec.ts
raiden/ui/web/src/app/components/token-network/token-network.component.html
raiden/ui/web/src/app/components/token-network/token-network.component.spec.ts

Make addresses easier to copy paste in the WebUI

---

tools/ansible/requirements.txt

ansible: https://nvd.nist.gov/vuln/detail/CVE-2017-7481
paramiko: https://nvd.nist.gov/vuln/detail/CVE-2018-7750

Fix vulnerable ansible requirements

---

docs/changelog.rst

Changelog entry for 2356

---

raiden/constants.py
raiden/raiden_service.py
raiden/storage/sqlite.py

fix #2247
The stress test is timing out because the replay is taking too long.

increase frequency of snapshotting

---

.travis.yml
.travis/prepare_os_osx.sh
.travis/set_tag.sh
.travis/update_formula.sh
Makefile
docker/build.Dockerfile
raiden/log_config.py
raiden/tests/utils/events.py
requirements-dev.txt
requirements.txt

This PR will introduce the nightly releases. 
Fixes #1894
Also fixes #2059

Nightly releases

---

tools/install_synapse.sh

Update build of Synapse server

---

raiden/tests/integration/test_echo_node.py
raiden/tests/integration/test_recovery.py
raiden/transfer/architecture.py

Serialization cleanup

---

raiden/blockchain/state.py
raiden/network/proxies/payment_channel.py

Fix for #2408

---

raiden/network/proxies/token_network.py

removed unused function

---

raiden/tests/integration/api/fixtures.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/api/utils.py

Adding tests as followup of #2382.
Also a small restructuring in the API tests.

Add test for payment event received success and mini api tests restructuring

---

raiden/api/rest.py
raiden/exceptions.py
raiden/storage/sqlite.py

fix payments endpoint exception handling

---

docs/rest_api.rst
raiden/api/v1/encoding.py
raiden/tests/integration/api/test_restapi.py

bugfix: missing identifier in the payment response

---

docs/rest_api.rst
raiden/messages.py
raiden/raiden_event_handler.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py
raiden/tests/unit/test_node_queue.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/target.py

This is just to it consistent with the SendSecretRequest event.

Renamed SendRevealSecret -> SendSecretReveal

---

docs/changelog.rst

Adding a changelog entry for solving the family of crashes reported first by #2419 
[skip ci]

Add changelog entry for 2419

---

.gitignore
requirements-dev.txt
requirements.txt

Bump web3 to 4.7.1

---

docs/changelog.rst
raiden/tests/unit/fixtures.py
raiden/tests/unit/transfer/test_node.py
raiden/transfer/node.py

Fix crash when an unlock for our address is seen on chain

---

raiden/blockchain_events_handler.py
raiden/connection_manager.py
raiden/network/transport/matrix.py
raiden/raiden_service.py
raiden/utils/echo_node.py

Bubble up unhandled exceptions in short-lived greenlets

---

docs/changelog.rst
raiden/api/python.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/utils/events.py

Return properly filtered results from the API payments event endpoint

---

raiden/api/rest.py

raise port in use earlier

---

docs/changelog.rst
raiden/network/proxies/token_network.py
raiden/raiden_service.py

Do not crash for recoverable errors during settlement

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/critical_vulnerability_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add different issue templates

---

docs/changelog.rst

Add changelog for #2451

---

raiden/exceptions.py
raiden/network/transport/udp/healthcheck.py
raiden/network/transport/udp/udp_transport.py
raiden/raiden_service.py
raiden/tasks.py
raiden/tests/conftest.py
raiden/tests/integration/test_regression.py
raiden/tests/unit/test_udp_transport.py
raiden/tests/utils/tests.py

removed unused raiden shutting down exception

---

docs/rest_api.rst

Remove wrong debug endpoint from docs

---

requirements.txt

Package is here: https://pypi.org/project/pystun-patched-for-raiden/

Use our special patched pystun package

---

raiden/messages.py
raiden/raiden_service.py

Start transport before alarm.first_run

---

docs/changelog.rst

Fix changelog for pinned versions

---

docs/changelog.rst
raiden/ui/web/src/app/app.component.ts
raiden/ui/web/src/app/app.module.ts
raiden/ui/web/src/app/components/channel-table/channel-table.component.html
raiden/ui/web/src/app/components/payment-history/payment-history.component.css
raiden/ui/web/src/app/components/payment-history/payment-history.component.html
raiden/ui/web/src/app/components/payment-history/payment-history.component.spec.ts
raiden/ui/web/src/app/components/payment-history/payment-history.component.ts
raiden/ui/web/src/app/models/payment-event.ts
raiden/ui/web/src/app/services/raiden.service.spec.ts
raiden/ui/web/src/app/services/raiden.service.ts

Add payment history to the webui.

---

.travis/update_formula.sh

Fix automatic homebrew formula updating

---

raiden/api/rest.py

Fix handle_request_parsing_error

---

docs/webui_tutorial.rst

Adds correct default value to --rpccorsdomain to the web_ui tutorial.

---

raiden/api/rest.py
raiden/blockchain_events_handler.py

Make some arguments human-readbale and add missed arguments in some places.

Improve logging in rest.py

---

raiden/api/v1/resources.py

@eorituz Can you check if that fixes the issue for you?
Fixes #2503

Fix internal events endpoint

---

constraints.txt

Bump raiden contracts to 0.3.1

---

raiden/tests/integration/test_stress.py

Related to: https://github.com/raiden-network/raiden/issues/2492
[skip ci]

Skip stress test due to being flaky

---

raiden/log_config.py
raiden/ui/cli.py

This disabled by default the log lines from `lockfile`, the user can overwrite it if he wants:
```
2018-09-14 07:52:17 [info     ] Lock 113189658052144 acquired on /home/hack/.raiden/node_af25b952/netid_3/network_f2a175a5/.lock [filelock]
```

ui: lowered lockfile logging level

---

raiden/network/rpc/client.py

Cache gas price calculations

---

raiden/tests/integration/test_stress.py

stress test: unskipped it

---

docs/changelog.rst
raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.html
raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
raiden/ui/web/src/assets/config/config.development.json
raiden/ui/web/src/assets/config/config.production.json

Adds validation for settle timeout against reveal timeout when opening a channel from the webui

---

raiden/raiden_event_handler.py

If onchain balance hash is empty don't search the WAL

---

raiden/tests/integration/test_stress.py

Skip stress test again

---

raiden/ui/web/src/app/components/token-network/token-network.component.html
raiden/ui/web/src/app/components/token-network/token-network.component.spec.ts
raiden/ui/web/src/app/components/token-network/token-network.component.ts
raiden/ui/web/src/app/services/network-type.enum.ts
raiden/ui/web/src/app/services/raiden.config.ts
raiden/ui/web/src/app/services/raiden.service.ts
raiden/ui/web/src/assets/config/config.development.json
raiden/ui/web/src/assets/config/config.production.json

Gray out token registration functionality in the WebUI

---

raiden/network/transport/matrix.py

Fix #2502 
The issue is about some attacker triggering our node to participate in a very big number of rooms, and be required to keep downloading events in all these rooms. If the rooms are very busy, the amount of data can be big enough to delay processing of important messages and cause a DoS.
This PR makes sure the node will leave any unneeded room, and stay only in:
- the discovery room
- the first 2 (public and private) p2p rooms with each partner we want to talk (i.e. healthchecked, which is either partners we have a channel with or which we sent or received a valid transfer)
The rest will be left, and thus the node won't receive events from this room anymore.

Leave and clean unused/old/non-relevant participating rooms

---

.pylint.rc
raiden/connection_manager.py

This is likely an error since once of the branches will never be
executed.

pylint enabled bad-except-order

---

raiden/raiden_service.py
raiden/tests/fixtures/variables.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py

Clarified lock usage in Raiden service

---

raiden/blockchain/events.py

removed unused namedtuple

---

raiden/api/v1/resources.py
raiden/app.py
raiden/blockchain/events.py
raiden/messages.py
raiden/network/blockchain_service.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/test_echo_node.py
raiden/tests/unit/test_accounts.py
raiden/tests/unit/test_channelstate.py
raiden/tests/utils/network.py
raiden/transfer/architecture.py

removed unused loggers

---

docs/conf.py
raiden/api/python.py
raiden/api/rest.py
raiden/network/rpc/client.py
raiden/raiden_event_handler.py
raiden/storage/restore.py
raiden/tests/integration/test_settlement.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/tests/utils/geth.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/ui/cli.py
tools/scenario-player/scenario_player/main.py
tools/scenario-player/scenario_player/utils.py

Fix some issues found by PyCharm static analysis

Argument cleanup

---

tools/transfer_eth.py

Small update to let the send-eth tool use the same arguments as the scenario player.

Update send-eth tool to use same conventions as scenario player

---

raiden/tests/scenarios/leave-network-happy-scenario.yaml
raiden/tests/scenarios/leave-network-on-closed_channels.yaml
raiden/tests/scenarios/leave-network-with-stopped-node.yaml
tools/scenario-player/scenario_player/runner.py
tools/scenario-player/scenario_player/tasks/token_network.py

Scenario Player: leave network

---

raiden/network/transport/matrix.py

Fix #2603 
Also, optimize user invitation by removing discovery room members listing + `_maybe_invite_user` from `start` method, which is not needed (presence change will eventually trigger it, if needed), and on `_handle_presence_change`, `_maybe_invite_user` is done in a separate greenlet, to avoid it blocking while it's a simple callback.

Handle matrix errors when inviting users

---

raiden/log_config.py
raiden/tests/conftest.py
raiden/tests/integration/test_stress.py

trying to reproduce flaky test

Stress test compact logging

---

raiden/tests/scenarios/close_channel_all_channels.yaml
raiden/tests/scenarios/close_channel_one_channel.yaml
raiden/tests/scenarios/close_channel_reopen_before_settle.yaml

Add basic scenarios to test channel closing

---

raiden/blockchain_events_handler.py
raiden/network/transport/matrix.py
raiden/network/transport/udp/udp_transport.py
raiden/raiden_service.py

This will make it easier to parse the data and use tools like `jq`.
Additionally it will always contain all the necessary data, in in a
machine/human readable format.

logging StateChange/Event JSON encoded

---

raiden/network/rpc/client.py
raiden/raiden_service.py

Improve logging in send_raw_transaction

---

raiden/raiden_service.py
raiden/transfer/mediated_transfer/mediator.py

bugfix: redact was not returning the data

---

docs/changelog.rst

Add changelog for #2631

---

raiden/transfer/mediated_transfer/target.py

The signature is recovered and validated by the channel logic, therefore
this if is unnecessary

simplified code

---

raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/target.py

With the secret registry it's no longer necessary to close the channel
to unlock, the only required action is registering the secret on-chain.

Removed unused code

---

docs/changelog.rst
raiden/api/python.py
raiden/network/proxies/token_network.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/api/test_restapi.py

Raise DepositMismatch from python api if less than the current total deposit is given

---

tools/scenario-player/example-scenarios/scenario-basic.yaml
tools/scenario-player/scenario_player/tasks/token_network.py

Add join-network task

---

raiden/tests/scenarios/open-channel-different-scenarios.yaml
tools/scenario-player/scenario_player/tasks/channels.py

Almost all cases were implemented except for the open channel with 0 tokens.
Do not merge.
Fixes: #2559

Open channel scenario added

---

raiden/ui/cli.py

Fix sqlite3 version mismatch error message

---

raiden/tests/scenarios/funding-channel-scenarios.yaml

All scenarios to fund and top up a channel

---

tools/scenario-player/scenario_player/runner.py

Small fix for default settings.

Default to fast gas price in case no settings are given

---

CONTRIBUTING.md

Add a note in contributing.md about updating docs/specs

---

.travis.yml
tools/install_synapse.sh

Update to 0.33.6, plus redirect synapse server to `homeserver.log` by default

Update synapse binary test server

---

CONTRIBUTING.md

We encourage people to follow https://chris.beams.io/posts/git-commit/
therefore the contribution guide should follow this style :)

Give positive examples in the CONTRIBUTING guide

---

tools/scenario-player/example-scenarios/scenario-basic.yaml
tools/scenario-player/scenario_player/tasks/channels.py

[SP] Allow arbitrary address input in the `to` field of tasks

---

docs/rest_api.rst

Should address the comment asked by
https://github.com/raiden-network/raiden/issues/2677#issuecomment-427171165
[skip ci]

Add note on connect and initial_channel_target

---

docs/changelog.rst
raiden/connection_manager.py
raiden/tests/integration/long_running/test_token_networks.py

Sanity check for joinable_funds_target and tests for this

---

raiden/app.py
raiden/settings.py
raiden/tests/utils/network.py
raiden/ui/cli.py
raiden/utils/cli.py

Implemented in raiden-network/raiden-transport#16
Fix #2604

Fetch list of known matrix servers from raiden-transport repo

---

docs/changelog.rst

Add changelog entry for 2568

---

CONTRIBUTING.md
docs/spec.rst
raiden/network/proxies/token_network.py
raiden/network/transport/matrix.py
raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediator.py
raiden/ui/cli.py
raiden/ui/web/src/app/services/raiden.service.ts
tools/scenario-player/scenario_player/utils.py

- Fixes a crash in the scenario player
- Fixes some typos
- Adjusts some logging messages to fit the rest
- Logs the network type during startup

Various small fixes

---

docs/changelog.rst

Added changelog protocol version in Ping

---

docs/rest_api.rst

Fix API docs for unencoded hexaddress arguments

---

README.rst

Pointing to the raiden contracts repos

---

raiden/ui/web/src/app/components/token-network-selector/token-network-selector.component.ts
raiden/ui/web/src/app/components/token-network/token-network.component.ts
raiden/ui/web/src/app/services/raiden.service.ts

Temporary workaround for #2729

Avoid refreshing tokens balances on every tokens refresh

---

raiden/ui/runners.py

Resolve mixup in runner naming

---

.travis.yml
Makefile

Resolves #2701.
@ulope this implements the solution you've described in the tagged issue. Is this only testable when we want to actually do deployments? or is there a way to test this without triggering an actual release?

Clean up archive before uploading to Pypi

---

docs/rest_api.rst

fix formatting error

---

docs/rest_api.rst

Document Internal server error(500) response

---

raiden/tests/unit/test_tokennetwork.py

Add basic test for routing

---

.travis/update_formula.sh

Neues Spiel, neues Glück
Maybe fixes #2426

Fix homebrew update ssh key permissions

---

raiden/accounts.py
raiden/api/v1/encoding.py
raiden/app.py
raiden/connection_manager.py
raiden/network/rpc/client.py
raiden/network/transport/udp/udp_transport.py
raiden/tests/unit/api/test_api_events.py
raiden/tests/unit/test_accounts.py
raiden/tests/utils/genesis.py
raiden/tests/utils/geth.py
raiden/tests/utils/network.py
raiden/tests/utils/smoketest.py
raiden/transfer/channel.py
raiden/transfer/state.py
raiden/ui/app.py
raiden/ui/console.py
raiden/utils/__init__.py
tools/gas_cost_measures.py
tools/genesis_builder.py
tools/scenario-player/scenario_player/utils.py

Replace [un]hexlify with eth_utils helpers

---

docs/rest_api.rst

Small docs fixes

---

raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/utils/filters.py
requirements-dev.txt
requirements.txt

Remove some eth_tester specific code.

More eth_tester cleanup

---

docs/changelog.rst
raiden/ui/app.py
tools/pyinstaller_hooks/hook-raiden_contracts.py
tools/pyinstaller_hooks/runtime_raiden_contracts.py

Should fix https://github.com/raiden-network/raiden/issues/2776
Also fixes some other incosistencies in the use of the ContractManager

Fix contract data path in binaries

---

docs/conf.py
docs/rest_api.rst
raiden/api/python.py
raiden/network/proxies/token_network.py
raiden/network/rpc/client.py
raiden/network/upnpsock.py

Also fixes #2786 by disabling doc generation from docstrings.

Fix docstrings Sphinx warned about

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

Making the hotfix release to properly include contract data with the new contract manager

Bumpversion to v0.13.1

---

raiden/network/transport/udp/healthcheck.py
raiden/network/transport/udp/udp_transport.py
raiden/raiden_service.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_stress.py
raiden/tests/unit/test_udp_transport.py
raiden/tests/utils/network.py
raiden/ui/app.py

Issue 2785

---

raiden/raiden_service.py

Fix RaidenService typos

---

raiden/storage/sqlite.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/state.py

Remove optional field from InitiatorTransferState

---

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/state.py

Mostly type annotation fixes, but one valid typo.
Part of #2797

Fix some mypy issues

---

docs/changelog.rst

I merged #2805 without the proper changelog

added changelog for 2813 [skip ci]

---

docs/changelog.rst

changelog for poll confirmation

---

raiden/ui/cli.py

update cli disclaimer

---

.travis/update_formula.sh

- Use sed extended regexes
- Allow multiple digit version numbers
- Fix working directory bug
Fixes #2426

Fix homebrew formula updating

---

raiden/tests/integration/cli/test_cli.py

Fix cli tests for new disclaimer

---

docs/changelog.rst
raiden/network/proxies/discovery.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/settings.py
raiden/utils/__init__.py

Also reinstate version check. Fix #2836

Take expected_version from deployed contract data

---

raiden/storage/sqlite.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/utils.py
raiden/transfer/views.py

Needs to be rebased once #2814 is merged
This are only typing improvements.
Part of #2797

Mypy check2

---

docs/rest_api.rst

To address https://github.com/raiden-network/raiden/issues/2571

[skip ci] add note about concurrency for join and leave

---

raiden/tests/integration/test_settlement.py
raiden/tests/utils/protocol.py

I changed the test a bit while debugging a failure. The changes are unrelated but I think they improve the test a bit

removed test_lock_expiry timming dependencies

---

.travis.yml

No reason to run cli for both matrix and udp
[skip ci]

Remove unneeded CI stage

---

raiden/tests/unit/test_channelstate.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/transfer.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py

@hackaugusto The test for the suspected issue from this morning. Seems like your right.
Edit: I added a fix as well, but I'm not sure if this is the proper way to fix it.

Add test for balance proof update after lock expiry

---

raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/target.py

Target secret onchain

---

raiden/raiden_event_handler.py

Fix wrong arg name in handle_contract_send_secretreveal

---

CONTRIBUTING.md

Add information about the commit labels to the Contributing guide

---

docs/changelog.rst
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/cli/test_cli.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py
raiden/ui/cli.py
tools/scenario-player/scenario_player/node_support.py

Contract addresses argnames are now consistent with the contracts repo

---

docs/api_walkthrough.rst

Fixes https://github.com/raiden-network/raiden/issues/2866

add note about echo node not being available on mainnet

---

docs/overview_and_guide.rst

Make testnets optional in guide, remove bootnodes

---

docs/changelog.rst
raiden/ui/app.py

fixed bug https://github.com/raiden-network/raiden/issues/2857
and tested by connecting Raiden with local private eth , after that registered token and Raiden allowed me to do so as development switch was on.

 fixed bug https://github.com/raiden-network/raiden/issues/2857

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py

tests: removed duplicated test

---

raiden/ui/app.py
tools/scenario-player/scenario_player/main.py
tools/scenario-player/scenario_player/node_support.py
tools/scenario-player/scenario_player/runner.py
tools/scenario-player/scenario_player/tasks/base.py
tools/scenario-player/scenario_player/utils.py

Some more improvements that collected over the last few days.
[skip ci]

Improve startup time, record node's stdout / stderr

---

tools/install_synapse.sh

pyinstaller build includes html and future modules

Fix synapse build on Travis

---

raiden/raiden_event_handler.py

#2874 had this exception raised, but the information is the message is really lacking

Improved logging for failed unlock

---

raiden/log_config.py

Also increase debug file max size to 20 MB
Just to make sure no more logs get lost.

Add time to debug log file

---

.github/ISSUE_TEMPLATE/bug_report.md

Add a checklist that could help bug reports be more informative. They are mostly based on our "Requirements for safe usage" page.

Bug report checklist

---

.travis/prepare_os_osx.sh
setup.py

Follow up to #2912 
[ci nightly]

Fix Travis webui building again

---

tools/scenario-player/scenario_player/node_support.py
tools/scenario-player/scenario_player/tasks/channels.py

Allow overriding the node api-address in scenarios

Allow specifying node api address

---

docs/rest_api.rst

Fixing note boxes that wasn't displayed correctly

fix note boxes

---

tools/scenario-player/scenario_player/node_support.py
tools/scenario-player/scenario_player/runner.py

Fix address handling after #2928

---

docs/changelog.rst

Add a changelog entry for 2933

---

docs/changelog.rst
raiden/network/proxies/secret_registry.py
raiden/tests/integration/test_regression.py

Proxy must not send empty secret register txs

---

docs/changelog.rst
docs/overview_and_guide.rst
raiden/network/rpc/client.py

Fix #2951 , this is not a perfect fix, but it will allow users to use
Raidne with Infura

Fallback to transaction count if necessary

---

docs/changelog.rst

reworded changelog

---

raiden/storage/sqlite.py

Increase DB version for PR #2929

---

.github/ISSUE_TEMPLATE/bug_report.md

Switch the issue checklist to an actual checklist.

---

docs/api_walkthrough.rst
docs/rest_api.rst

update payment return objects [skip ci]

---

docs/changelog.rst

Add changelog entry for 2921

---

docs/changelog.rst
docs/overview_and_guide.rst
raiden/exceptions.py
raiden/network/rpc/client.py
raiden/ui/app.py
raiden/ui/runners.py

Check that the ethereum node has all required RPC interfaces enabled

---

constraints.txt

The Vulnerability is detailed at https://nvd.nist.gov/vuln/detail/CVE-2018-18074

Update requests to v2.20.0 to fix security vulnerability

---

docs/changelog.rst
raiden/raiden_service.py
raiden/storage/serialize.py
raiden/storage/sqlite.py
raiden/tests/integration/test_integration_events.py
raiden/tests/integration/test_settlement.py
raiden/tests/unit/fixtures.py
raiden/tests/unit/test_serialization.py
raiden/tests/unit/test_tokennetwork.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/token_network.py
raiden/transfer/views.py
raiden/utils/serialization.py

Remove object cache

---

config_sample.toml

Adjust config_sample.toml after contract argument changes

---

docs/changelog.rst
raiden/network/rpc/client.py
raiden/ui/app.py

Make infura work again

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/state.py

Cleanup unlocked/unclaimed locks upon expiry

---

raiden/tests/unit/test_state.py
raiden/transfer/state.py

Fix TransactionOrder ordering

---

tools/scenario-player/scenario_player/tasks/token_network.py

Fix the scenario player part of #2675

[SP] Properly handle 0 for 'initial_channel_target'

---

raiden/network/rpc/smartcontract_proxy.py
raiden/tests/unit/test_rpc.py

Fix parity funny return value error at estimate gas

---

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/mediated_transfer/initiator_manager.py

asserting at that point is incorrect, the state of the transfer is not
know and therefor it's not an assumption that we can test. The correct
approach is to check the current state and either ignore the request or
process it.

Fix handle_cancelpayment

---

docs/changelog.rst
raiden/api/python.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/utils/events.py

Registering a token twice should now throw a proper error

---

raiden/utils/__init__.py

At _log_raiden_run handle None version

---

.circleci/config.yml

long running tests integration, transfer, api have higher parallelism

Circle CI - Adjust Parallelism for Optimization

---

raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/state_change.py
raiden/utils/serialization.py

Each change removes one error. They are meant to be completely
uncontroversial.

Misc mypy type checking fixes

---

raiden/raiden_service.py

Clear unused exception from except

---

raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/state.py

The errors are fixed the primitive way by adding type casts. As a next
step, the number of casts can be reduced by improving the typing in
other parts of the code.
closes #3034

solve mypy errors in initiator.py

---

docs/onboarding.rst

When I was reading the onboarding documents, I didn't understand what
each message does.  Now I'm trying to describe them after conversations.

Describe intensions of some messages in onboarding doc

---

CONTRIBUTING.md

To explain when we use fuzz tests, unit tests and integration tests, respectively, and how to write them.
Fixes #3069.

Add a section on testing to CONTRIBUTING.md

---

docs/onboarding.rst

The first entry is "what is MS/PFS".  I thought about describing them more, but that would be a duplicate of the glossary in the spec.
I'll add more entries.

Add FAQ in the onboarding document

---

docs/onboarding.rst

A few people pointed out these naming conventions to me as undocumented important knowledge. So, I'm adding them in the dev onboarding document.

Document Action* Receive* naming conventions

---

docs/onboarding.rst
raiden/transfer/node.py

Explain which queues are cleared with Delivered/Processed

---

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py

Abstract away common setup code for most initiator state machine unit tests
to make them easier to write and comprehend.
Related to #3025

Abstract away common initiator unit tests setup

---

.circleci/config.yml
.travis.yml
Makefile
raiden/storage/sqlite.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/state.py
raiden/transfer/state_change.py
requirements-lint.txt

In a spirit of test-driven-development, I'm opening this PR to see a failure in CircleCI.  When I see that, I'll push a fix on top.
---
Although mypy still returns many error messages, for some files, some
kinds of errors have been eliminated.  I'm adding a partial check that's
supposed to pass.  The plan is to make this check more and more powerful
until mypy reports no errors.
This is a part of https://github.com/raiden-network/raiden/issues/3040.

Add mypy check on `BlockNumber`related errors in CIs

---

docs/changelog.rst
raiden/tests/integration/test_pythonapi.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/mediated_transfer/initiator.py

Return PaymentFailure and not hang a transfer if a lock expires

---

tools/debugging/json-log-to-html.py

Fix html rendering event filtering

---

raiden/network/transport/matrix.py

More descriptive event log name for matrix account data get

---

docs/api_walkthrough.rst
docs/changelog.rst
docs/rest_api.rst
raiden/api/rest.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/utils/smoketest.py
tools/scenario-player/scenario_player/node_support.py
tools/scenario-player/scenario_player/runner.py
tools/scenario-player/scenario_player/tasks/channels.py
tools/scenario-player/scenario_player/tasks/token_network.py

Add v prefix to api version

---

tools/debugging/replay_wal.py

Provides a template script to use when debugging a provided database file.

Replay WAL debugging script

---

docs/changelog.rst
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/transfer/mediated_transfer/mediator.py

Mediator task handling of invalid refund transfer

---

docs/onboarding.rst

Add a link to the protocol explainer video

---

Makefile
raiden/network/proxies/token_network.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/state.py
raiden/transfer/state_change.py

This commit changes Makefile to detect more mypy errors and fixes the newly found errors. The fixes are mostly adding type annotations, but I removed one default '= None'.
Related: #3040, #1206

Detect and fix mypy errors around ChannelID

---

docs/changelog.rst
raiden/tasks.py
raiden/tests/unit/test_version_check.py

 Do not crash at check_version if github request returns unexpected data 

---

tools/debugging/replay_wal.py

@rakanalh for your consideration
[skip ci]

Remove outdated state change from WAL replay script and add some useful filter functions

---

.circleci/config.yml
tools/debugging/replay_wal.py

Deploying releases are handled by an specific workflow ignoring the test suite

New workflow for release deployment only

---

docs/changelog.rst

Add changelog for 3171

---

docs/index.rst
docs/red_eyes_mainnet_tutorial.rst

This tutorial should act as a simple and easy way to get started doing payments with the Red Eyes release.
The document is not yet done, since some of the information needed is not yet available due to the release not yet being finalized.
Instructions on how to close/settle channels have deliberately been omitted to keep the tutorial as simple as possible, but they can easily be added if we want.

write initial version of simple Red Eyes tutorial

---

docs/changelog.rst

Fix red eyes version in changelog

---

docs/webui_tutorial.rst

Update WebUI tutorial

---

CONTRIBUTING.md
raiden/transfer/balance_proof.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/transfer/queue_identifier.py
raiden/transfer/secret_registry.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/utils.py
raiden/transfer/views.py

The rule is to prefer importing the class directly and use module
imports to avoid name clashes.

consistent usage of the typing module

---

raiden/transfer/mediated_transfer/target.py

> Added to the target's sanity check asserts about the lock's lifetime.
> The lock must exist while the target exist, and when the target is
> cleared the lock must be cleared.
review after: #3220

Target sanity check

---

tools/debugging/json-log-to-html.py

Allows values to be replaced before the log is being rendered to HTML. 
Supports substring and eth-address matching.
The idea is totally stolen from @konradkonrad''s `replay_wal` addition :)

[tools] Add support for value replacements to json-to-html debugging tool

---

docs/changelog.rst

Will help know what is included in the next release (the one the RC is for) and what goes in the next after that.
[skip ci]

Add v0.100.2-rc1 to the changelog

---

raiden/raiden_service.py

removed direct payment type

---

raiden/network/proxies/token_network.py
raiden/tests/integration/contracts/test_token_network.py

https://github.com/raiden-network/raiden/pull/3218#discussion_r245319411

Removed unecessary default

---

docker/Dockerfile

Updated and slimed down the outdated Dockerfile
@andrevmatos Implemented the requested deletion of the .git folder

Updated outdated Dockerfile

---

raiden/app.py
raiden/ui/app.py
raiden/ui/cli.py

Adds pathfinding service address as CLI argument and stores in config

---

.github/PULL_REQUEST_TEMPLATE/bugfix.md
.github/PULL_REQUEST_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE/refactoring.md

The goal is to introduce checklists to improve the review process.
Items in the lists are in order of importance, time should not be spend
reviewing commits if the PR is not sound to begin with.
#3066

Introduced templates for PRs

---

raiden/app.py
raiden/ui/app.py
raiden/ui/cli.py

Adds max paths to be requested as CLI argument and stores in config

---

raiden/raiden_event_handler.py

Issue #3196 proved to be hard to debug, part of the problem is that not
all data used to query the database is available, so it's hard to know
why the database record was not found. This adds the two missing data
fields to the log message, in case the error manifest itself again in
the future.

Additional details in logging for debugging

---

raiden/tests/integration/transfer/test_mediatedtransfer.py

Unskip test that was skipped for Travis builds

---

raiden/tests/unit/test_channelstate.py
raiden/transfer/channel.py

If the lock is registered on-chain the removed expired lock must be
ignored. The logic for this was correct, however, the message was
incorrect because of the ordering of the if statements.
This also fix the name of two unit tests for the channel state.

Fixed removed expired lock message

---

docs/overview_and_guide.rst

Added docker installation guide

---

.bumpversion_contracts.cfg

The smart contracts now live in raiden-contracts repo [skip ci]

removed unused file

---

raiden/network/proxies/token_network.py
raiden/tests/integration/contracts/test_token_network.py

The return values from  _update_preconditions are discarded

bugfix: Exception was not thrown

---

docs/index.rst

It was requested that we add this disclaimer to the docs

Add disclaimer to the docs [skip ci]

---

raiden/tests/unit/test_mtree.py

Saw this one while reviewing Oliver's commits one by one.

Remove unused function in test_mtree.py

---

CONTRIBUTING.md

Add note about PR reviews on Contributing.MD

---

raiden/ui/cli.py

Remove unnecessary **kwargs from cli

---

CONTRIBUTING.md

Swap skip ci with skip tests in contributing.md

---

raiden/api/python.py
raiden/api/rest.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/test_echo_node.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/transfer.py

Return PaymentStatus instead of AsyncResult

---

raiden/tests/integration/test_matrix_transport.py

Re-Add missing assert in transport test

---

raiden/utils/upgrades.py

Must have been lost during rebase or addressing review comments on my previous PR #3227.

Begin upgrade transaction

---

docs/red_eyes_mainnet_tutorial.rst

remove "(INSERT LINK ONCE READY)" and add link to the mainnet release article.

Insert Red Eyes announcement link to docs

---

LICENSE

Extended LICENSE period from 2018 to 2019.

Changed LICENSE date from 2018 to 2019

---

raiden/app.py
raiden/raiden_event_handler.py
raiden/ui/app.py
raiden/ui/cli.py

Add cli flag to enable monitoring

---

tools/debugging/json-log-to-html.py
tools/scenario-player/scenario_player/main.py
tools/scenario-player/scenario_player/utils.py

Fixes an issue in the scenario player caused by changes in Python 3.7's
logging module.
Drive by change:
- Add time range filtering in the json-log-to-html debugging tool

Fix scenario player for Python 3.7

---

raiden/tests/unit/test_upgrade.py
raiden/utils/migrations/v16_to_v17.py
raiden/utils/upgrades.py

Upgrade version update

---

raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/utils/protocol.py

This just removes a custom patching and uses the general testing utility.
The end result is **not exactly** equal, there is a race condition on the re-dispatch of the locked transfer. Because this is waiting on a async result, depending on how the test greenlet is scheduled, the locked transfer message will be dispatched any time after the reveal secret, but not necessary exactly after it.

simplified test messages_out_of_order

---

raiden/network/pathfinding.py
raiden/tests/unit/test_pfs_integration.py
raiden/ui/app.py
raiden/ui/cli.py

Add PFS info and checks at client start

---

raiden/utils/upgrades.py

Simplfied and fixed the upgrade manager docstring

---

docs/changelog.rst
docs/rest_api.rst
raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/resources.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/unit/api/test_api.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/state.py
raiden/transfer/views.py

Add API endpoint for in-flight transfers

---

docs/changelog.rst
raiden/api/rest.py
raiden/tests/integration/api/test_restapi.py

In order to get the results need to call get()

Bug: Use async_result properly

---

raiden/raiden_service.py
raiden/tests/integration/test_send_queued_messages.py
raiden/waiting.py

Prompted by
[this](https://github.com/raiden-network/raiden/commit/6695282d88962677e0bcb85ae04e7df134ed372e#r32330360) comment

Fix payment amount at payment status restoring during restart

---

raiden/raiden_service.py
raiden/storage/sqlite.py
raiden/tests/unit/migrations/test_v16_to_v17.py
raiden/tests/unit/migrations/test_v17_to_v18.py
raiden/tests/unit/test_upgrade.py
raiden/utils/upgrades.py

Each pragma has a really short description and links to the authoritative documentation. This basically enables optimizations for sqlite databases used by a single application

Sqlite pragmas

---

raiden/api/v1/encoding.py
raiden/message_handler.py
raiden/network/transport/matrix/client.py
raiden/raiden_event_handler.py
raiden/tests/unit/test_version_check.py
raiden/tests/utils/mocks.py
raiden/tests/utils/transport.py

Implementing @ulope's suggestion from https://github.com/raiden-network/raiden/pull/3474

Use @staticmethod instead of disabling no-self-use

---

raiden/raiden_service.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/unit/test_upgrade.py

This time a test to showcase the problem of the previous fix is also included.

Fix payment status amount restoration at restart -- again

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
raiden/transfer/mediated_transfer/initiator_manager.py
setup.py

This PR:
- created a new branch for release v0.100.2 called `v0_100_2_work` on the upstream branching out from `v0.100.2-rc4`.
- bumped the version to `v0.100.2`
- cherry picked the private issues fixes ... funny thing is that it seems that the diff is already somehow included .. probably some work from @rakanalh 's PR
- added the changelog entries
-----
After this PR is merged:
1. I will need to tag the tip of this branch as v0.100.2 to start the release process.
2. Cherry pick the extra commits (even thought they are empty) to master. The commit messages alone contain a lot of info on what the problem was.
3. Move the issues from the private repo to this repo
4. Include the proper issues number in the changelog.

Create v0.100.2 release

---

raiden/routing.py
raiden/tests/unit/test_pfs_integration.py

This was changed recently in order to prepare for payments.

Update PFS request to post method

---

raiden/message_handler.py

The test `test_locked_transfer_secret_registered_onchain` was used to
guarantee that a node does not reuse a known secret. It first registered
the secret and then called `start_mediated_transfer_with_secret`. Because
the Raiden node was only querying the blockchain state from confirmed
blocks the recently registered secret was missed.
In this particular instance, using `latest` as a block_identifier is
fine, we don't need a consistent view of the blockchain for that
particular call.
Note: this is a follow-up from #3548 which missed a second instance of
this.

Fix test race condition 2

---

raiden/network/rpc/client.py
raiden/tests/integration/rpc/test_assumptions.py
raiden/utils/smart_contracts.py
tools/scenario-player/example-scenarios/scenario-example-v2.yaml
tools/scenario-player/scenario_player/runner.py
tools/scenario-player/scenario_player/tasks/blockchain.py
tools/scenario-player/scenario_player/utils.py

Add assertion to query blockchain events

---

.circleci/config.yml
.circleci/fetch_geth_parity_solc.sh
raiden/network/rpc/client.py
raiden/raiden_service.py
raiden/settings.py
raiden/tests/conftest.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/contracts/test_payment_channel.py
raiden/tests/integration/contracts/test_token_network.py
raiden/tests/integration/contracts/test_token_network_registry.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/network/transport/test_udp.py
raiden/tests/integration/rpc/test_assumptions.py
raiden/tests/integration/test_matrix_transport.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/genesis.py
raiden/tests/utils/geth.py
raiden/tests/utils/smoketest.py
raiden/waiting.py
tools/startcluster.py

Add parity versions of integration tests to the CI builds.

---

raiden/raiden_service.py
raiden/tasks.py

Just some tiny improvements:
- Clarifies some of the comments
- Clarifies the events lock
- Put the transport initialization code together
- Add some assertions on the expected state of the service
- Group the methods which start side-effects

RaidenService small improvements

---

tools/scenario-player/scenario_player/tasks/blockchain.py

Small enhancement necessary to test the MS in the scenario player.
Related to https://github.com/raiden-network/raiden-services/issues/31

Use contract name in assert_events

---

raiden/messages.py
raiden/tests/unit/test_messages.py

Fixes https://github.com/raiden-network/raiden-services/issues/158

Fix deserialization of UpdatePFS message

---

docs/overview_and_guide.rst

Appended missing architecture suffix.

Update file names in install guide

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/conftest.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/test_matrix_transport.py

Reverts raiden-network/raiden#3598

Revert "Fix #3588"

---

raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py

 Use wait_assert utility together with  assert_synced_channel_state

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/conftest.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/test_matrix_transport.py

I reverted the Merge of #3598 as the tests were flaky. Reopening this, to see if the build fails again.

"Fix #3588/2"

---

raiden/network/sockfactory.py

https://github.com/raiden-network/raiden/commit/dd930c0a40cc8eab67292ed46fcc7ab20a693dac#r32859803

tigthened try-block

---

tools/scenario-player/scenario_player/runner.py
tools/scenario-player/scenario_player/tasks/blockchain.py

Don't know where my brain was when I did the changes before 😕

[SP] Set service contract addresses properly

---

Makefile
tools/scenario-player/example-scenarios/scenario-example-v2.yaml
tools/scenario-player/scenario_player/__main__.py
tools/scenario-player/scenario_player/exceptions.py
tools/scenario-player/scenario_player/main.py
tools/scenario-player/scenario_player/node_support.py
tools/scenario-player/scenario_player/runner.py
tools/scenario-player/scenario_player/scenario.py
tools/scenario-player/scenario_player/tasks/api_base.py
tools/scenario-player/scenario_player/tasks/base.py
tools/scenario-player/scenario_player/tasks/blockchain.py
tools/scenario-player/scenario_player/tasks/channels.py
tools/scenario-player/scenario_player/tasks/execution.py
tools/scenario-player/scenario_player/tasks/raiden_api.py
tools/scenario-player/scenario_player/tasks/raiden_node.py
tools/scenario-player/scenario_player/tasks/services.py
tools/scenario-player/scenario_player/ui.py
tools/scenario-player/scenario_player/utils.py

Requires and is built on top of #3596 
(My first commit here fixes some lint and circular import errors from #3596. Can be dropped, once they are fixed there.)
This adds support for PFS and UDC to the scenario player.
Explanation of the expected parameters in 
- `example-scenarios/scenario-example-v2.yaml`
- `settings.services`
- `pfs`
- `udc`
- `assert_pfs_routes`
- `scenario_player/tasks/services.py::PFSAssertTask`

[SP] Add PFS / UDC integration

---

raiden/network/pathfinding.py
raiden/ui/app.py

Temporary fix for 3670

---

raiden/tests/unit/storage/migrations/test_v19_to_v20.py

This prevents the `SerializedSQLiteStorage` from failing to deserialize objects later on when we have further changes in the state, which is exactly what happened in #3569

Replace SerializedSQLiteStorage with raw SQLiteStorage

---

raiden/tests/unit/storage/migrations/test_v16_to_v17.py
raiden/tests/unit/storage/migrations/test_v17_to_v18.py
raiden/tests/unit/storage/migrations/test_v18_to_v19.py
raiden/tests/unit/storage/migrations/test_v19_to_v20.py
raiden/tests/unit/test_upgrade.py
raiden/utils/upgrades.py

Fix upgrade manager

---

constraints.txt
raiden/ui/app.py

Upgrading raiden-contracts to v0.16.0.  I should be able to remove the temporal fix in https://github.com/raiden-network/raiden/pull/3674 .

Use raiden-contracts v0.16.0 and remove the temporal fix

---

raiden/ui/app.py

Fix #3687
We really need tests for all possible argument values in the startup ...

Fix startup for private networks

---

raiden/ui/app.py

Fix ui/app.py initialization
