raiden-network/raiden

.travis.yml, requirements.txt
Also require pyethereum>=1.3.0 (added library support for solc).
Fix for #35
=> Install solc+serpent on travis

raiden/app.py, raiden/benchmark/speed_simulation.py, raiden/blockchain/net_contract.py, raiden/channel.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/test_channel.py, raiden/tests/test_settlement.py, raiden/tests/utils/network.py, raiden/transfermanager.py
Timeout parameters were hard-coded before, in order to have a more configurable setup they were implemented in the default [config](https://github.com/brainbot-com/raiden/blob/1007f6ed06ed26dafa42d2c91e69dc99cb9f5c1d/raiden/app.py#L28-L31).
The config is accessed by other modules of the program from the [RaidenService](https://github.com/brainbot-com/raiden/blob/1007f6ed06ed26dafa42d2c91e69dc99cb9f5c1d/raiden/raiden_service.py#L90
).
In order to provide better readability of the code and providing a uniform wording, some parameters were renamed:
**reveal_timeout**  (formerly known as *min_locktime* or *hop_timeout*):
The timespan a node requires to learn the secret before the lock expires for him (time in number of blocks)
**settle_timeout** (formerly known as *locked_time*):
The time of …
=> add configurable timeouts, uniform timeout-names

raiden/network/discovery.py, raiden/tests/conftest.py, raiden/tests/smart_contracts/test_endpointregistry.py
This gives us a rough-on-the-edges but decentralized discovery service, so clients can register their endpoints automatically.
=> Add Discovery-contract + service class

raiden/app.py, raiden/utils/__init__.py
Enables raiden to receive an rpc endpoint as URL.
Now can accept: `https://host:port`, `https://host`, `http://host:port`, `http://host`, `host:port`.
Making `https` connections requires an update to `pyethapp`.
=> Accept optional (http/https) protocols and optional port for rpc ends

docker/Dockerfile
* Break RUN sections
* Removed superfluous commands
* Exposed port 40001 by default
* Use pip to install requirements (don't clone dependencies)
=> Refactor dockerfile

Makefile, raiden/tests/conftest.py, raiden/tests/fixtures/blockchain.py, raiden/tests/fixtures/variables.py, raiden/tests/utils/blockchain.py, requirements.txt, setup.py, tools/README.md
Dependencies are already tough -- removing hydrachain makes it a little
easier to keep up with all dependent versions. Also, hydrachain added
little value to the current testing framework (where it was used exclusively).
=> Remove hydrachain dependency

.travis.yml, raiden/tests/fixtures/blockchain.py
This uses a static version of `solc` from https://github.com/rainbeam/solidity-static/releases on travis-ci.
Note: this also includes a fix for an issue with the test fixtures that became only apparent after fixing solidity.
=> Use static solc

raiden/blockchain/abi.py, raiden/console.py, raiden/network/discovery.py, raiden/network/rpc/client.py, raiden/tests/fixtures/blockchain.py, raiden/tests/fixtures/tester.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_endpointregistry.py, raiden/tests/smart_contracts/test_channel_manager.py, raiden/tests/smart_contracts/test_endpointregistry.py, raiden/tests/smart_contracts/test_token.py, raiden/tests/utils/tester_client.py, raiden/utils/__init__.py, tools/create_compilation_dump.py, tools/deploy.py, tools/init_blockchain.py
This allows to import it without needing to compile all ABIs, which
in many cases is not necessary.
=> Move `get_contract_path` out of abi module

MANIFEST.in, setup.py
Fix setup to create a complete package allowing external apps to import raiden.
=> Add missing files+packages to setuptools

raiden/assetmanager.py, raiden/benchmark/profile_transfer.py, raiden/benchmark/speed.py, raiden/benchmark/speed_decoding.py, raiden/benchmark/speed_transfer.py, raiden/channel.py, raiden/encoding/messages.py, raiden/messages.py, raiden/raiden_service.py, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tasks.py, raiden/tests/integration/test_e2e.py, raiden/tests/integration/test_events.py, raiden/tests/integration/test_settlement.py, raiden/tests/smart_contracts/test_netting_channel.py, raiden/tests/test_callbacks.py, raiden/tests/test_channel.py, raiden/tests/test_messages.py, raiden/tests/test_transfer.py, raiden/tests/utils/transfer.py, raiden/transfermanager.py
This PR along with #147 addresses #139.
- **Identifier Size**: 8 bytes for alignment and parity with nonce and other numeral parts of the message
- **Added identifier field in the following messages:**
- SecretRequest
- Secret
- DirectTransfer
- LockedTransfer
- MediatedTransfer
- Identifier is now used wherever needed
=> Identifier for messages

raiden/benchmark/profile_transfer.py, raiden/benchmark/speed.py, raiden/raiden_service.py, raiden/tests/integration/test_e2e.py, raiden/tests/test_callbacks.py, raiden/tests/test_transfer.py, raiden/tests/utils/transfer.py, raiden/transfermanager.py
This PR is based on #145. **Do not** merge until that is finished.
Also addresses #139 
1. Our address
2. The asset address
3.  Our nonce
=> Add Identifier to Raiden API + Tests

raiden/benchmark/speed_decoding.py, raiden/encoding/messages.py, raiden/messages.py, raiden/smart_contracts/NettingChannelLibrary.sol
updated the `speed_decoding.py` to use the new `sign` method.
added the identifier field to the refund message and for the netting channel decoder.
=> Fixed speed_decoding.py and added identifier to RefundTransfer

raiden/assetmanager.py, raiden/channel.py, raiden/encoding/messages.py, raiden/messages.py, raiden/raiden_protocol.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/fixtures/variables.py, raiden/tests/integration/test_settlement.py, raiden/tests/test_channel.py, raiden/tests/utils/transfer.py
The bulk of the changes was to split the shared responsabilities for the `Secret` message and the `claim_lock` method.
This PR does:
- Adds the `amount` field for issue #112 
- Prepares the `Secret` message for #66 
Please review of #151 before merging.
=> Reveal Secret message

README.md
Our best guide for installation is currently in the wiki. Instead of duplicating the work, I removed the incomplete instructions here and link to the wiki section, that explains the PoC-0 installation, instead.
Fixes #167
=> Point to installation instructions in the wiki #167

tools/tmuxtest.sh
Running it with /bin/sh doesn't work:
,----
| $ sh tools/tmuxtest.sh
| tools/tmuxtest.sh: 5: tools/tmuxtest.sh: Syntax error: "(" unexpected
`----
Also, make it executable.
=> use bash for running tools/tmuxtest.sh

tools/create_compilation_dump.py
This broke tmuxtest, and probably other deployment scenarios, too.
The dependency resolver is pretty brittle, but with adding path awareness,
it should become a tiny bit more stable.
=> Fix dependency resolver

raiden/tests/test_mtree.py
besides the typo, the function called merkleroot with the first argument
being the empty string.
This looks like it should have been an empty list or a list containing
the empty string. Both of these cases are now tested in test_empty.
=> fix test_mtree.py/test_empty

raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/smart_contracts/test_netting_channel.py
This PR fixes #196 and #197 
There was a check in `updateTransfer` that dictated wrong logic. That is not fixed and a modifier has been added that makes sure that the address calling close cannot call `updateTransfer`
=> Fix failing tests for updateTransfer

raiden/mtree.py
get rid of the internal first argument, which has been used to decide if
this is the first call to merkleroot, i.e. that merkleroot is being
called from an outside caller and doesn't call itself [1].
Instead use an internal _merkleroot function, that recursively calls
itself.
Also document the perversion of proof being modified in place by
merkleroot [2].
build_lst should also probably be renamed, though I didn't do that in
this commit.
[1] the name 'first' has also been reused in the function with a
different purpose.
[2] yes, maybe I've had too much exposure to clojure lately
=> clean code in raiden.mtree, get rid of internal 'first' argument

raiden/network/transport.py, raiden/raiden_protocol.py, raiden/tests/test_service.py, requirements.txt
This fixes the Ping when node is unreachable due message resend not being disabled.
Would add the TODO/XXX related code to update the graph but will open a new issue for that and work on other branch because this already solves the general problem.
=> Deactivate re-sends after X tries without ACK

raiden/mtree.py
check_proof did clear the proof argument. There's no good reason to do
that and it's just waiting to bite you. One of the tests in
test_mtree.py already compares empty lists...
So, don't modify the proof argument.
=> do not clear the proof argument in check_proof

raiden/app.py
This reverts commit 7788e87f69c522d07b7fe39447942ba726593b71.
Orchestration is not dependent on app.py anymore so this can just be reverted.
=> Revert "Allow password to be passed by parameter (for scripted use)"

raiden/channel.py, raiden/mtree.py, raiden/tests/test_mtree.py
The previous implementation of merkleroot was hard to understand, since
it tried to do several things at the same time.
I've tried to untangle that and now we've got separate functions to
- iterate pairwise over a list of elements
- compute the layers of the merkletree
- create proofs from the merkletree layers
I've also added a Merkletree class, which is initialized with a list of
hashes. This allows to compute multiple proofs for the same tree without
recomputing hashes all the time.
The merkleroot function still exists, but eventually it will be removed.
This is work-in-progress in order to resolve issue #202.
=> untangle and cleanup raiden.mtree

.travis.yml, setup.cfg
Also remove the --quiet option from tests, we want to be able to see
what is running.
=> Remove blockchain-type=geth from Travis

.travis.yml, setup.cfg, tox.ini
posargs didn't work quite well, since the testenv had three py.test
commands trying to specify the tests to run from the command line would
run it three times
using a single commands allow the user to overwrite the tests that
should be executed through the command line, we can keep the priority of
tests from the faster to slower ones and keep the failfast flag.
=> tests: better testenv tests execution

raiden/blockchain/abi.py, raiden/network/discovery.py, raiden/network/rpc/client.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_endpointregistry.py, raiden/tests/utils/mock_client.py, raiden/tests/utils/tester_client.py
This PR removes the `geth` requirement from some integration tests, all tests will be executed on top of `blockchain_type=tester` when the `--blockchain-type=tester` flag is supplied.
=> Tests blockchain tester

raiden/tests/conftest.py, raiden/tests/fixtures/tester.py
Added an assert for gas usage.
We are using a [fairly large gas block limit](https://github.com/raiden-network/raiden/blob/040fcb15e3b6aec3953a7c947b0d83bf7dac82e1/raiden/tests/fixtures/tester.py#L24-L33) to avoid `mine`ing too often, this assert will prevent functions that use too much gas.
=> tests: checking for gas usage

raiden/app.py, raiden/channelgraph.py, raiden/console.py, raiden/raiden_protocol.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/conftest.py, raiden/tests/fixtures/__init__.py, raiden/tests/fixtures/blockchain.py, raiden/tests/fixtures/raiden_network.py, raiden/tests/fixtures/variables.py, raiden/tests/unit/test_transfer.py, raiden/tests/utils/network.py
Fixes #203.
- Keep all received messages timestamp
- Adding a Healthcheck task
- For every peer in the address queue check if he the last received message time is greater than `send_ping_time. If so, then send a ping.
- If the last received message time is greater than `max_unresponsive_time` remove the peer.
- Tests for healthcheck for both normal peers but also bad/unresponsive peers
=> Healthcheck

raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_e2e.py, raiden/tests/integration/test_endpointregistry.py, raiden/tests/integration/test_events.py, raiden/tests/integration/test_settlement.py
Some runs in travis take longer than 10min to fail because of the travis' default timeout, instead of waiting for the travis failure that doesnt output log information this PR uses an explicit 1min timeout for each integratoin test.
=> tests: added timeout of 1min for each integration test

raiden/network/rpc/client.py, raiden/tests/fixtures/blockchain.py, raiden/tests/integration/test_blockchainservice.py, raiden/ui/console.py, tools/deploy.py, tools/init_blockchain.py
This fixes the
`raiden/tests/integration/test_blockchainservice.py::test_new_netting_contract` test
=> Use pyethapp default_gasprice for contract deploy

raiden/app.py, raiden/network/transport.py, raiden/tests/unit/test_transport.py, raiden/tests/utils/network.py
This implements a token bucket algorithm for throttling, see
https://en.wikipedia.org/wiki/Token_bucket
The default policy in use is a `DummyPolicy`, a dummy provider that does not
restrict the aomunt of messages.
In `app.py` the default now is a TokenBucket policy of
capacity=10, fill_rate=10
This fixes #174
=> Implement throttling #174

raiden/channel.py, raiden/network/protocol.py, raiden/raiden_service.py, raiden/tests/unit/test_transfer.py, raiden/transfermanager.py
This PR is for:
- Unknown address in a message
- Unknown asset address in a message
- Locksroot that can't be matched to the expected locksroot
It is also a part of #72
=> Proccess message edge cases with invalid attributes

raiden/smart_contracts/NettingChannelLibrary.sol
We have to be checking for the failure of `token.transfer()`, because if
we don't a `channel.settle()` can succeed while the transfer of tokens
can fail which will result in the funds being stuck in the contract forever.
=> Check token transfer failure

raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/smart_contracts/test_netting_channel.py
This PR fixes the failing unlock test from issue #198 . The problem was that the wrong party was trying to unlock. The test is still marked as xfails however since the function call that is expected to fail doesn't fail. This will be fixed when issue #96 is taken care of. But now at least the tests are correct. 
Also I've made a small change to a modifier. This is done since the NettingChannelLibrary.sol should not use `msg.sender`
=> Fix failing unlock test + minor modifier improvement

raiden/messages.py, raiden/tests/unit/test_messages.py
~Fixes #187 in the proposed way.~
This now addresses several cases in `Lock` and `MediatedTransfer` and adds a unit test case for the message field limits.
Note: there are potentially other fields that should be size checked, too, which may or may not `raise` during (de-)serialization.
Stil fixes #187
=> Fix argument size checks in `messages`

README.md, prepare_poc_release.sh
This is part of the reason why 0.0.3 release got messed up --
the API request errored, but the script didn't give any usable
feedback.
=> Don't swallow errors when talking to GH API

.travis.yml, raiden/network/rpc/client.py, requirements.txt, setup.py
go ethereum implemented strict hex encoding for jsonrpc since https://github.com/ethereum/go-ethereum/pull/3355/files
We had one incorrect address encoding raiden, as well as there is an incorrect address encoding in pyethapp rpc client (see https://github.com/ethereum/pyethapp/pull/184).
In this PR I
- upgraded the `geth` version in travis to `v1.5.5`
- fixed the incorrect encoding in `raiden`
- temporarily switched the pyethapp requirement to the patched version from [pyethapp PR 184](https://github.com/ethereum/pyethapp/pull/184)
=> Fix issue #290

raiden/assetmanager.py, raiden/channel.py, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/smart_contracts/test_channel_manager.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/tester.py, raiden/tests/utils/tester_client.py
This PR adds nonce ranges to the netting channels. This makes sure that once #191 allows for channels to be reopened, the same transfers cannot be used again.
Tests for reopening a channel and for nonce ranges have also been added, but they are marked as `xfail` until #191 is done.
With this PR I believe that #39 can be closed
=> Use nonce ranges

raiden/network/rpc/client.py, raiden/tests/utils/tester_client.py
Simply adding some comments to explain why we got an unused argument in both `tester_client.py` and `rpc/client.py`.
Does not mean that this is a nice design decision or that it should not be fixed. But we still need to have a comment explaining why the unused arguments exist.
=> Comment on usage of our_address argument

raiden/tests/conftest.py, raiden/tests/fixtures/__init__.py, raiden/tests/fixtures/blockchain.py, raiden/tests/fixtures/raiden_network.py, raiden/tests/fixtures/variables.py, raiden/tests/utils/network.py
Needed unique port numbers for the UDP socket otherwise it wouldn't
rebind the address between tests.
=> added raiden_udp_ports fixture. #314

raiden/tests/conftest.py, raiden/tests/fixtures/blockchain.py, raiden/tests/fixtures/variables.py, tox.ini
- do not use a udp protocol for generating the genesis block, as this
will bind the port and the test itself cannot rebind.
- added the py.test command line argument to allow parallel tests to
start from different base ports.
=> MacOSX port resuse fix #314

raiden/network/rpc/client.py, raiden/smart_contracts/ChannelManagerContract.sol, raiden/smart_contracts/ChannelManagerLibrary.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/smart_contracts/test_channel_manager.py
This PR fixes #93 and should be favored instead of #191.
It makes it possible to open a channel with the same partner after settling. Replay attacks has been taken care of by #287 and #211. 
Right now the code is not very effective and quite expensive to run gas wise, but this should become a lot cheaper once PR #250 is implemented.
=> adding logic to allow to parties to open a new channel after settling

raiden/network/rpc/client.py, raiden/smart_contracts/NettingChannelContract.sol, raiden/tests/smart_contracts/test_channel_manager.py, raiden/tests/smart_contracts/test_netting_channel.py, raiden/tests/utils/tester_client.py, raiden/utils/__init__.py
There is no reason to have 3 different `close()` functions remaining in the code. With this PR I am making the interface to the channelclosing, consistent across the codebase.
=> Consistent usage of a single close() function

raiden/app.py, raiden/tests/unit/test_transport.py
If the transport is stopped before all the protocol greenlets an error
might occur if the protocol tries to send an message forward like an
Ack.
=> transport must be stopped after protocol

raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_events.py
the `test_event_new_channel` test is failing frequently with a timeout of a minute requiring manual intervention to rerun the build, increased it to a minute and a half.
=> tests: increased test_event_new_channel timeout

requirements.txt
In order to work around issue ethereum/pyethereum#412 pyrlp has downgraded their rlp dependency to version <=0.4.6
https://github.com/ethereum/pydevp2p/commit/1b4647f500bdb495c77518e55b94b97a1125739c
This prevents the following error while doing `python setup.py develop`
> error: rlp 0.4.7 is installed but rlp<=0.4.6,>=0.4.4 is required by set(['devp2p'])
=> Fix RLP dependency version error

raiden/network/rpc/client.py
Geth now requires `0x` for the raw transaction.
=> geth: proper hex encoding

raiden/messages.py, raiden/network/transport.py
Instead of using pex(msg) which just printed the zero-padding, this
change uses the pex(sha3(msg)) showing a unique signature of the
message. This improves log reading/debugging.
old repr: <Ack [00000000]>
new repr: <Ack [msghash=b01a3ac6]>
=> better repr for Ack

requirements.txt
As defined
[here](https://pip.pypa.io/en/latest/reference/pip_install/#requirement-specifiers)
a comma is needed for version ranges
Thanks to @nicksavers for noticing the problem.
=> Use comma in pypi requirements version range

raiden/network/rpc/client.py, raiden/tests/fixtures/blockchain.py, raiden/tests/integration/test_blockchainservice.py, raiden/ui/console.py, requirements.txt, setup.py, tools/deploy.py, tools/init_blockchain.py
In solidity [v0.4.9](https://github.com/ethereum/solidity/blob/develop/Changelog.md#049-unreleased) they introduced a new key for the combined-json-abi compile output.
Before merging we need to think if we want to have 2 hot-fixed requirements for `pyethapp` and `pyethereum`. And if yes for how long, i.e: How long would it take to create releases for both of these repos.
We are using changes introduced in:
- https://github.com/ethereum/pyethapp/pull/188
- https://github.com/ethereum/pyethereum/pull/432
=> Utilize pyeth changes for solc >= 0.4.9

raiden/network/rpc/client.py, raiden/tests/fixtures/blockchain.py, raiden/tests/integration/test_blockchainservice.py, tools/deploy.py, tools/init_blockchain.py
This lets the jsonrpc client's `tinyrpc` transport use a `requests.Session` instance in order to reuse addresses/ports.
(hot-) fixes #253
=> Proposed hotfix for issue 253

raiden/smart_contracts/ChannelManagerLibrary.sol, raiden/smart_contracts/NettingChannelLibrary.sol
The type of the parameters should not be added in the docstrings since
it's already available from the language itself. Additionally the
function name and signatures are not needed since a docstring always
documents the function that is following right underneath it.
=> Remove type from contract docstrings

raiden/channel.py, raiden/tests/integration/test_settlement.py, raiden/tests/unit/test_channel.py, raiden/tests/unit/test_transfer.py
This fixes the automatic settlement as tested in `tests/integration/test_settlement.py::test_settlement` and allows to remove the pytest skip on travis-CI. Due to the applied fixes a couple of other tests that apparently adjusted to the formerly broken behavior needed changes, too. 
There were a couple of issues that lead us to start skipping the test and I'd like you to give the PR a thorough review -- to ensure it fixes what it is supposed to fix and also to learn:
- The main cause for the ["flakyness"](https://github.com/raiden-network/raiden/issues/389) of the test was an incorrect [Yoda-style](https://en.wikipedia.org/wiki/Yoda_conditions) boolean comparison in the [`blockalarm_for_settle`](https://github.com/raiden-network/raiden/pull/391/commits/3bac2c5158db69ef484f56bb3713f6e99e162 …
=> Fix test_settlement

raiden/raiden_service.py
@konradkonrad that's for you buddy, to fix the `ChannelNew()` errors.
It's just one commit out of the branch I am working on.
=> Remove superfluous manager_address_bin in ChannelNew events

raiden/tests/fixtures/variables.py
Without propagation between nodes I expect tests to run a lot more reliable
(see #389).
We had a prior issue #258 about this, which conclusion was mislead by the bugs
fixed in #391.
=> Reduce the number of geth nodes in tests to 1

requirements-dev.txt, tox.ini
When using `tox` the chained calling of `coverage run -m py.test` makes `gevent`
monkeypatching hard (if not impossible). By using the pytest-cov plugin, we
can spare one level of inception.
=> Use pytest-cov instead of coverage

raiden/tests/unit/test_transport.py
Increasing the tolerance because of a Travis fail, it took ~0.060s:
> assert 0.06079816818237305 < 0.05
=> Increase tolerance

raiden/tests/utils/blockchain.py
Thanks to the [sanity checks](https://github.com/ethereum/go-ethereum/issues/3734) introduced by geth we found out that pyethereum had a [denomination that was too big](https://github.com/ethereum/pyethereum/pull/439).
In any case let's change the test account balance to a more sensible amount with this PR.
=> Change account endowment for tests, for safety

raiden/tests/unit/test_transport.py
After #412 there was another factor of flakyness, due to the incorrect assumption that `send_async` execution was dependent on `wait()`. Instead of stepping through a fake time, this now tests that the sleep times increase according to the token refill policy.
=> Freeze time and assert on increasing wait times #389

raiden/ui/cli.py, tools/ansible/run-scenario.yaml, tools/config_builder.py, tools/create_compilation_dump.py, tools/process_results.py, tools/scenario_runner.py, tools/tmuxtest.sh
The script missed a lot of changes. 
This PR makes it functional again, it is a neat little helper for a DEMO:
- creates a private `geth` backend
- deploys the raiden contracts
- creates tokens/balances for several clients
- starts all clients
- creates example channels
- drops all clients into CLI interface -> take your DEMO from here
=> Fix tmux_test.sh

raiden/ui/cli.py, raiden/ui/console.py
Use `address_decoder` in ui/cli.py instead of `decode_hex()`. We should do that all over the codebase actually.
=> Use address_decoder in ui/cli.py

requirements.txt, setup.py
Our forked dependency was necessary for make `ethereum` work with solidity>=0.4.9.
The PR was merged and released, so we can go back to the upstream.
Fixes #418
=> Use upstream ethereum>=1.6.1

.gitignore, raiden/blockchain/abi.py, raiden/utils/__init__.py, setup.py
This adds tooling to read the contract ABIs from a json file instead of compiling them at runtime. It will always check the contract source files against a recorded `sha1` checksum (and compile in case of a mismatch).
Unless the environment variable `STORE_PRECOMPILED` is set, the compiled ABIs will not be stored. There is a command in `setup.py` that stores the current contract ABIs in the expected format and place.
Usage:
python setup.py compile_contracts
Fixes #428
=> Allow to store and use precompiled ABIs

.travis.yml
Since https://github.com/ethereum/solidity/pull/1796 there are static alpine linux
based `solc` builds released on the solidity repository. No need to use the brainbot
self-baked one anymore.
=> Use ethereum/solidity released solc

requirements.txt
Fixes the following 2 errors:
- `error: rlp 0.4.6 is installed but rlp==0.4.7 is required by set(['devp2p'])`
- `error: secp256k1 0.12.1 is installed but secp256k1==0.13.2 is required by set(['devp2p'])`
=> Fixes incompatible dependencies

raiden/blockchain/net_contract.py, raiden/channel.py, raiden/network/rpc/client.py, raiden/raiden_service.py, raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/integration/test_settlement.py, raiden/tests/smart_contracts/DecoderTester.sol, raiden/tests/smart_contracts/test_channel_manager.py, raiden/tests/smart_contracts/test_netting_channel.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/mock_client.py, raiden/tests/utils/tester_client.py
This PR gets rid of the incremental nonce check since this
was a potential attack vector.
Furthermore this PR gets rid of the courtesy close. Some sort of
cooperative close should be implemented instead, but that is for another
issue.
Lastly it makes sure that `updateTransfer` can only be called once.
=> Get rid of nonce check

raiden/network/rpc/client.py
In situations with high concurrency there are two potential error conditions with our current nonce querying method:
1) the remote (blockchain rpc service) may not have updated the pending transaction count in time
2) two transactions may ask for the transaction count/nonce concurrently
I added a local nonce counter to avoid cases of 1) and added a locking Semaphore block around the newly introduced `get_nonce` method to avoid cases of 2) (see `raiden/network/rpc/client.py`).
=> Improve rpc client concurrency

raiden/tests/utils/blockchain.py
This PR should fix the `0` account balance in tests that we are seeing with latest geth.
1. Introduced a sanity check when doing `geth init` for our `custom_genesis.json` so that we catch these errors earlier.
2. Fixed the `extraData` field to always be hex encoded with a `0x` prefix as is expected by latest geth versions.
=> Fix custom genesis problems

raiden/raiden_service.py, raiden/ui/cli.py, raiden/utils/__init__.py, tools/config_builder.py, tools/tmuxtest.sh
- added a utility to test if raiden can be execute from inside a newly
created session with the provided configuration
- remove the `-g` flag in favor of the `-d` flag to speed up consective
executions of the script (encrypting the keystore is slow)
- fixed the config_builder.py keystore command, the private key was not
being decoded from hexadecimal
- removed the function keyword as it seems to be zsh specific
=> fixed tmux test and config_builder

.travis.yml, raiden/tests/utils/blockchain.py, requirements-dev.txt
If the system running the tests doesn't have enough memory to keep all
the DAG in the main memory the POW process will be slower than expected,
resulting in test flakiness, specifically for the tests that depend on
the confirmation of transactions, since this is a hard to diagnose
problem this commit adds an explicit check for the free memory and fails
the tests early. Note this will only fail the tests that are using the
geth miner, nothing happens with the purely unit/tester tests.
=> Check available memory before running the geth miner

raiden/tests/utils/blockchain.py
I don't see a reason to have bootnodes and as an extension nodekeyhex in
the test geth arguments.
If there is a reason then then at least the argument should be sanitized
to not be given without a value as I have seen it multiple times given
without a bootnode value in tests.
We are lucky geth accepts this at the moment, but this should not be our
default behaviour.
=> Bootnodes and nodekeyhex seem to be unused in test

docs/api.rst, raiden/api/objects.py, raiden/api/rest.py, raiden/api/v1/encoding.py, raiden/api/v1/resources.py, raiden/raiden_service.py, raiden/tests/api/test_api.py, raiden/tests/fixtures/api.py, raiden/tests/utils/apitestcontext.py
Close #465
- RaidenAPI's exchange() now accepts binary encoded addresses. The conversion happens at
the REST API instead.
- Created the token_swaps endpoint which exposes the token swap task
- Tests for the aforementioned API endpoint
=> Expose tokenswap in api

raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/smart_contracts/DecoderTester.sol
- Removed extraneous check for the settled variable (settled is only set if closed is set, so a check for closed is enough)
- Using index_or_throw instead of a check for each participant address
- Skipping processTransfer (one less function to follow when reading the close code)
Merge after: #502
=> Netting channel cleanup close

raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/smart_contracts/DecoderTester.sol, raiden/tests/smart_contracts/test_decoder_netting_channel.py
Removed extra attributes from the Participant struct. The removed fields
are part of message but compose the inlined Lock structure, since the
Lock strucuture must be be provided to the `unlock` function, we don't
need to save them in the Participant struct.
=> Simplified netting channel

raiden/channel.py, raiden/network/rpc/client.py, raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/utils/mock_client.py, raiden/tests/utils/tester_client.py
The function transferredAmount was used to check if the courtesy
transaction was correct, since the courtesy transaction was removed
this function is not necessary anymore.
Note: Additionally the transferred_amount is not sufficient to detect
if the proper transaction was provided, at least the nonce should be
checked but ideally the values `nonce`,  `transferred_amount`, and
`locksroot` should be verified. This is also important for third-party
services.
=> Removed transferredAmount from NettingChannelContract

raiden/network/rpc/client.py, raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/integration/test_blockchainservice.py, raiden/tests/utils/mock_client.py, raiden/tests/utils/tester_client.py
If required, this information is available through the `addressAndBalance` function
=> Removed partner function

.travis.yml, .travis/make_dag.sh, raiden/tests/utils/blockchain.py
The memory check in the blockchain fixture should not expect the DAG size of `free` memory since systems tend to use up `free` memory for caching. Instead we check now for `available` memory which includes memory currently used in caches.
=> Check for `availabe` memory instead of `free`

raiden/raiden_service.py
For Refund Transfers the hashlock is kept inside the lock structure
Was getting this kind of error when running tests:
```
raiden/tests/unit/test_transfer.py ..x....ERROR:raiden.network.protocol unexpected exception raised.
File "/home/lefteris/ew/raiden/raiden/network/protocol.py", line 357, in receive
self.raiden.on_message(message, echohash)
File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 1246, in on_message
self.message_refundtransfer(message)
File "/home/lefteris/ew/raiden/raiden/raiden_service.py", line 1325, in message_refundtransfer
message.hashlock,
AttributeError: 'RefundTransfer' object has no attribute 'hashlock'
```
Was not killing the tests and was not erroring since it is inside the greenlet.
=> Fix refund transfer on_message processing

raiden/smart_contracts/ChannelManagerContract.sol, raiden/smart_contracts/ChannelManagerLibrary.sol
we still treated the library as if we are in pre-homestead where
libraries where invoked with `CALLCODE` instead of `DELEGATECALL`. The
first did not preserve msg.sender and msg.value so code needed to
forward msg.sender to the library. That is no longer required.
=> Do not forward msg.sender in ChannelManagerLibrary

.travis.yml
The flake8 command was failing but the rest of the build was still
running and marked as failure only after the entire test suite was run
through. This is a travis issue as can be seen
[here](https://github.com/travis-ci/travis-ci/issues/1066).
Also moved it to be ran before the travis matrix commands.
=> Travis: Flake8 only once and fail fast

raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol
Initially the idea was to keep as much of the code in the library and make the contracts just a thin layer that dispatched commands to the library, but since the removal of loops from the channel manager library that idea got lost.
This PR removes one additional function from the netting channel library that is not part of the core functionality. It is not for optimization, it is for separation of concerns.
=> moved addressAndBalance to the Contract only

.travis.yml, raiden/tests/fixtures/blockchain.py, raiden/tests/utils/blockchain.py
([Confirmed](https://github.com/raiden-network/raiden/pull/472#issuecomment-290338547) as expected) ~I am not 100% sure if this is expected behaviour~ but with the latest geth master version custom genesis file parsing is becoming more strict.
If you append the `--blockchain-cache` argument while running the tests with latest geth then you are bound to hit the same problem.
Make sure to remove all caches before attempting to run this branch. If you don't you will still load the old cached genesis file. To do that run the following from the raiden root directory:
`rm -rf /tmp/<username>/pytest-of-<username>/pytest-* && rm -rf .cache `
Naturally replace `<username>` with your username.
In order to have the cached genesis accepted by geth the following were
done:
- Make sure that all hex is …
=> Make Raiden compatible with geth v1.6.0

raiden/exceptions.py, raiden/mtree.py, raiden/tests/unit/test_mtree.py
- `build_lst` -> `build_list`
- Rename and document the exception thrown if a hash is not 32 bytes in length
=> Fix name typo and better document exception

requirements.txt, setup.py
Until this PR: https://github.com/yann2192/pyelliptic/pull/56 for
pyelliptic gets merged we need to manually import the fix for OpenSSL
v1.1 to be able to use Raiden in systems where OpenSLL has been upgraded
above that version.
=> Make raiden compatible with openssl v1.1

raiden/blockchain/net_contract.py, raiden/channel.py, raiden/tests/integration/test_events.py, raiden/tests/integration/test_settlement.py
Some places were missed and are causing failures. This should fix them.
=> Rename unlock to withdraw in all remaining places

raiden/raiden_service.py, raiden/tests/integration/test_events.py, raiden/tests/utils/apitestcontext.py, raiden/ui/console.py, raiden/utils/__init__.py
It seems the functions of the programmatic API were not consistent in what they were accepting and this caused problems when contacted via the Rest API.
As discussed during the retreat, this PR is trying to enforce each different area (rest api, console tools) to do their own decoding to binary and assert that the programmatic API only gets binary address formats.
=> Programmatic api only accepts binary addresses

raiden/encoding/signing.py, raiden/raiden_service.py, raiden/tests/benchmark/speed_decoding.py, raiden/tests/integration/test_settlement.py, raiden/tests/smart_contracts/test_channel_manager.py, raiden/tests/smart_contracts/test_decoder_netting_channel.py, raiden/tests/smart_contracts/test_netting_channel.py, raiden/tests/unit/test_transfer.py, raiden/utils/__init__.py, requirements.txt
Solves #513 
Special thanks to @ofek for writing coincurve and for help.
=> Replaced secp256k1 with coincurve

raiden/channel.py, raiden/connection_manager.py, raiden/raiden_service.py, raiden/tests/api/test_api.py, raiden/tests/conftest.py, raiden/tests/fixtures/__init__.py, raiden/tests/fixtures/blockchain.py, raiden/tests/fixtures/raiden_network.py, raiden/tests/integration/test_provisioning.py, raiden/tests/integration/test_settlement.py, raiden/tests/unit/test_channel.py, raiden/tests/unit/test_cli.py, raiden/tests/utils/mock_client.py, raiden/tests/utils/network.py, raiden/tests/utils/tester_client.py
This implements the first two bulletpoints of #83:
> - [x] allow for a simplified `connect(token, available_funds)` API method that hides the `open(token, partner, funding)` steps from the user
> - [x] add a listener that will "join" freshly opened channels by depositing some `available` funds
This PR touches a couple of things:
The `ConnectionManager` is intended to allow per-token token-network connection establishment and maintenance.
It provides three functions:
- `connect(funds)` to initialize a connection
- `join_channel(partner_address, partner_deposit)` to join a channel on discovery of a newly opened channel
- `retry_connect()` to create more channels on discovery of new network participants
The `ConnectionManager` follows a certain fund-splitting strategy (configured on …
=> Automatic channel provisioning #83

.travis.yml, requirements-dev.txt
There is some exception raised with latest coverage v4.4, that wasn't
there with v4.3.4:
Can't support concurrency=gevent with PyTracer, only threads are supported
=> Pin coverage below 4.4

.travis.yml, raiden/smart_contracts/ChannelManagerContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/smart_contracts/Registry.sol
After updating to solidity version 0.4.11 solc now warns about unused
local variables. Due to this a couple of unused variables were found and
removed from the smart contracts.
Furthermore this PR updates solidity to version 0.4.11 in travis
=> removed unused local variables

raiden/channel/netting_channel.py, raiden/network/rpc/client.py, raiden/tests/utils/mock_client.py, raiden/tests/utils/tester_client.py
This PR does two things.
- Calls `updateTransfer()` only if we also did not close the channel.
- Returns `closing_Address` from the proxies making sure it's binary and not hex
=> Call updatetransfer only if we did not close

.travis.yml, raiden/network/rpc/client.py
Fix #591
It seems that with geth v1.6.1 we get an error when giving empty
`fromBlock` or `toBlock` which is going against the spec. According to
the spec it should default to "latest". An issue is
reported for it [here](https://github.com/ethereum/go-ethereum/issues/14467).
In any case it's much better to be explicit in our RPC calls and not
rely on defaults so this PR addresses that and bumps the Travis geth
version to 1.6.1.
=> Compatible with geth v1.6.1, explicit from/toBlock

README.md
Corrected testnet links in README.md to Ropsten
=> Corrected testnet links in README.md to Ropsten

raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/smart_contracts/netting_channel/DecoderTester.sol, raiden/tests/smart_contracts/netting_channel/test_close.py, raiden/tests/smart_contracts/netting_channel/test_decoder_netting_channel.py, raiden/tests/smart_contracts/netting_channel/test_updatetransfer.py, raiden/tests/smart_contracts/netting_channel/test_withdraw.py
Fix #601 
- Add tests for checking if the recipient of a
messaged submitted via close() or updateTransfer() is actually a
participant of the channel.
- In some tests in test_close.py and test_updateTransfer the nonce was
incorrectly specofied  and the test was failing due to the nonce and not
due to the expected failure.
- Add a check in both `updateTransfer()` and `close()` that makes sure the recipient of a message we try to close/update with is indeed the expected channel participant.
=> Check recipient in nettingchannel

raiden/channel/balance_proof.py
Fix #248
As per issue #248 
I've made the tree parameter optional in compute_proof_for_lock to keep compatibility with any code outside of balance_proof.py that might use this (only tests within the raiden repository but not sure if there might be anything outside of this repository that uses it).
=> Separate generation of Merkle tree from compute_proof_for_locks

tools/genesis_builder.py
Related to issue #618 this hex-encodes the 'extraData' value in the genesis block JSON as per https://github.com/ethereum/wiki/wiki/Ethereum-Chain-Spec-Format#subformat-genesis
=> Ensure that extraData is hex-encoded when creating genesis block

raiden/smart_contracts/ChannelManagerContract.sol, raiden/smart_contracts/ChannelManagerLibrary.sol, raiden/smart_contracts/HumanStandardToken.sol, raiden/smart_contracts/StandardToken.sol, raiden/smart_contracts/Token.sol
Solc 0.4.11 introduces various warnings, including the unused local
variable warnings which pinpoing two places in the contracts where we
can improve.
One was the Token.sol contract which I turned into an interface to
properly reflect its purpose.
The other is the `contractExists()` part of ChannelManagerLibrary.sol
which should be part of the contract and not the library.
=> Improve token interface and fix solc warnings

raiden/api/python.py, raiden/blockchain/net_contract.py, raiden/channel/netting_channel.py, raiden/channel/participant_state.py, raiden/connection_manager.py, raiden/network/channelgraph.py, raiden/network/rpc/client.py, raiden/raiden_service.py, raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/integration/test_blockchainservice.py, raiden/tests/smart_contracts/netting_channel/test_deposit.py, raiden/tests/smart_contracts/test_channel_manager.py, raiden/tests/unit/test_service.py, raiden/tests/utils/__init__.py, raiden/tests/utils/mock_client.py, raiden/tests/utils/network.py, raiden/tests/utils/tester_client.py, raiden/ui/console.py
This adds the proposed fixes for issue #613
In detail:
- set the NettingChannelContract opened block in the smart contract constructor
- don't call `register_netting_channel` from `RaidenAPI.open`, but wait for the event handler to process the newly created instance instead
- check the value of the `opened_block` in `ChannelEndState.__init__`, to avoid nonce ranges starting from `0`
- I also changed the reported block number in the `ChannelNewBalance` event. Previously it used the `opened` block number, which, from my point of view seems incorrect because a later call to `deposit` would always report the opened block -- since we don't need the block number #450 it is now set to `0` to let anything using the event included block number fail early.
- I changed/removed `channel.isopen()` …
=> Fix opened block #613

requirements.txt, setup.py, tools/create_compilation_dump.py
Use https://github.com/ethereum/pyethereum/pull/737
=> Use interface supporting pyethereum

tools/deploy.py
Deployment of `*Token` contracts is not necessary -- they are not used as libraries, only as interfaces.
=> Remove `HumanStandardToken.sol` from deploy stack

.travis.yml
Since `geth makedag` is broken, we have to wait for
https://github.com/ethereum/go-ethereum/pull/14598 or something
equivalent is included in a new release.
=> Downgrade geth to 1.5.9

raiden/channel/netting_channel.py, raiden/raiden_service.py, raiden/tests/benchmark/speed_transfer.py, raiden/tests/integration/test_settlement.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/transfer.py, raiden/token_swap.py
passing block number as argument to the channel instance to avoid
syncrhonization problems, were the channel is lagging behind one block
and may reject a transfer because of the block number difference.
=> create transfer with explicit block number

raiden/tests/unit/test_operators.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/state.py, raiden/transfer/state.py, raiden/transfer/state_change.py
In some of our code we were overloading the `==` operator using `__eq__`. As can be seen in [this](http://jcalderone.livejournal.com/32837.html) article that does not also overload the `!=` operator automatically which can lead to some really nasty bugs in the future.
This PR makes sure we always got a corresponding `__ne__` to each `__eq__` and also adds tests for this.
=> Add ne operator overloading

raiden/ui/cli.py
The URL to the Rest API docs in the cli was pointing to a non existing file.
=> Update Rest API url in cli hint

raiden/channel/netting_channel.py, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/smart_contracts/netting_channel/test_withdraw.py, raiden/transfer/mediated_transfer/initiator.py
Races will occur among partner nodes in respect to the latest block
number.
To avoid failure under this scenario, where *next hop* is not enforcing
the received expiration to be lower than settlement timeout:
The *initiator* learns first about a new block and uses it's number as
the base to compute a lock expiration, then the *next hop* receives the
transfer prior to learning about the same block.
=> Allowed receiving locks with a large expiration

raiden/ui/cli.py
Juist opening a normal PR from: https://github.com/raiden-network/raiden/pull/627
As address/socket pair registration requires confirmation of the
tx, polling until it appears in the next block introduces a delay
until other services/cli can be started. This fix spawns a
separate gevent for the registration to speed up the startup.
=> Do not block during startup (#511)

docs/Overview-And-Guide.rst
I updated the documentation to include examples of how to work with parity and Ropsten testnet.  The old documentation uses pyethapp, which as far as I know, can only work with Morden.
=> Updated Documentation to help future Devs

raiden/raiden_service.py
The pickled variable name was not matching the protocol variable name
and we were getting an error at shutdown
```
File "/home/lefteris/.virtualenvs/raiden/bin/raiden", line 11, in <module>
File "/home/lefteris/ew/raiden/raiden/__main__.py", line 8, in main
run()
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 722, in __call__
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 697, in main
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File …
```
=> Fix name of pickled protocol variables

tools/create_compilation_dump.py
Since geth 1.6, all hex data from genesis block are required to be
prefixed with `0x`. Even before 1.6, data would be ignored if not having this prefix, and now, `geth init` gives fatal error.
This PR makes config_builder.py generate genesis json compatible with current geth init requirements.
=> Avoid safe_lstrip_hex on genesis json

raiden/__main__.py, raiden/api/rest.py, raiden/main.py, raiden/tests/fixtures/api.py, raiden/ui/cli.py
These small adjusts allows to run raiden entirely on a docker container.
`--api-address` allows the API to be exposed to the world (e.g: `0.0.0.0:5001`), and thus still accept connections even when contained.
`--address` now also accepts its data from a environment variable, `ETH_ADDRESS`.
Account password also can be passed through another environment variable, `ETH_PASSWORD`, which didn't get exposed through click/command line option to avoid it being visible through process/command line listing tools, like `ps aux`.
TODO: document those options in proper place.
=> CLI rework

raiden/utils/__init__.py
Other than `ethereum.utils.privtoaddr`, does `raiden.utils.privatekey_to_address` not support hex-encoded keys but treats all input as binary (see below for the different behavior).
This is meant to enforce sandwich encoding of addresses and keys (binary internally, hex to the outside world).
To avoid hard to detect errors after providing hex-encoded private keys, I changed the helper to refuse input of any other length than 32.
```
In [1]: from raiden.utils import privatekey_to_address
In [2]: from ethereum.utils import sha3, privtoaddr
In [3]: key = sha3('key')
In [4]: privtoaddr(key)
Out[4]: 'X1\x88\xa9\xcfw\xe1\xb2WL\xca\xe4\n\xeb\x9ax\x94\x88\xec\xa2'
In [5]: privtoaddr(key.encode('hex'))
Out[5]: 'X1\x88\xa9\xcfw\xe1\xb2WL\xca\xe4\n\xeb\x9ax\x94\x88\xec\xa2'
In [6]: …
```
=> Refuse to generate addresses from wrong privatekey length

raiden/blockchain/abi.py, raiden/blockchain/events.py, raiden/network/rpc/client.py, raiden/tests/fixtures/abi.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_events.py, raiden/tests/smart_contracts/netting_channel/test_invariants.py, raiden/tests/utils/tester.py, raiden/tests/utils/tester_client.py
Until now anything that imported `raiden/blockchain/abi.py` invoked the
compilation of our contracts in order to get the ABI and some other
attributes.
This PR moves the logic to a class that is initialized at import but not
instantiated there. The ABI and other contract attributes are lazily
evaluated. In other words the first time something is required only then
are the contracts compiled.
Finally now we can do `raiden --help` without waiting 5-6 seconds.
=> Do not invoke contract compilation at file import

docs/Rest-Api.rst
The documentation for the `/api/1/tokens` endpoint gave the reader the
idea that it only returned the tokens that the user was participating
in, but the call actually returns all registered tokens. So the
documentation has been updated to reflect this.
=> Update documentation for tokens endpoint

raiden/tests/fixtures/blockchain.py
As
[this](https://github.com/raiden-network/raiden/pull/665#discussion_r126122831)
comment shows it is easy to mistake the functionality of the fixture due
to its name.
I assumed that the DAG is pregenerated once per session, while in fact
the fixture simply ensures it is there by generating it if it is not and
doing nothing if it is.
Renamed for clarity.
=> Rename pregenerate_dag fixture for clarity

raiden/channel/netting_channel.py, raiden/event_handler.py, raiden/message_handler.py, raiden/raiden_service.py, raiden/tests/benchmark/speed_transfer.py, raiden/tests/integration/test_settlement.py, raiden/tests/smart_contracts/netting_channel/test_close.py, raiden/tests/smart_contracts/netting_channel/test_settle.py, raiden/tests/smart_contracts/netting_channel/test_updatetransfer.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/transfer.py, raiden/token_swap.py
Adjust the setting of the settlement period's end by setting blocks_until_settlement depending on the closed_block.
Add explicit block number argument to the transfer registration
=> Transfer expiration

docs/Rest-Api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/api/v1/resources.py, raiden/network/rpc/client.py, raiden/tests/api/test_api.py, raiden/tests/fixtures/api.py, raiden/tests/unit/api/test_python_api.py, raiden/tests/utils/apitestcontext.py, raiden/tests/utils/tester_client.py
Add a REST API endpoint for the token registration along with tests for it.
In an upcoming PR will fix the return code/responses if you try to reregister.
=> Add register token endpoint to api

raiden/api/v1/encoding.py, raiden/api/v1/resources.py, raiden/tests/utils/apitestcontext.py
The marshmallow schema was wrong and was expecting the token_address
from the json data while it should only be found from the url.
=> Fix the connect API endpoint token address

docs/Rest-Api.rst, raiden/api/rest.py, raiden/tests/api/test_api.py, raiden/tests/unit/api/test_python_api.py
We were not following the api spec and returning `200 OK` in places where `201 CREATED` should have been returned. This PR fixes that.
=> Return 201 and other non-200 rest status code when needed

setup.py
A previous change I had made inadvertedly broke the static abi
compilation of contracts via setup.py. This should fix it.
=> Fix the compilation of contract ABI in setup.py

raiden/ui/cli.py
From our discussions on restartability/recoverability we should not be
closing all channels by default at shutdown unless otherwise
specifically requested.
=> Do not close/settle channels at shutdown

tox.ini
By default when we run tests with tox without specifying an environment
with the `-e` argument we run tests in both both `py27` and `coverage`
which seem to end up in two identical runs.
Thus I don't see why we should have both in the list especially since we
can manually invoke any specific environment via `-e`. The default
should be a single run. Having it in a different way makes people assume
both runs are needed.
=> Remove py27 environment from tox.ini

raiden/smart_contracts/NettingChannelContract.sol, raiden/tests/smart_contracts/netting_channel/test_deposit.py, raiden/tests/unit/api/test_python_api.py
This is a fix for the flaky failures we were getting on test_api_channel_events
```
=================================== FAILURES ===================================
[1m[31m______________________ test_api_channel_events[2-1-geth] _______________________[0m
raiden_chain = [<App f0ef4707>, <App a3c19cc4>]
[1m    @pytest.mark.parametrize('blockchain_type', ['geth'])[0m
[1m    @pytest.mark.parametrize('channels_per_node', [1])[0m
[1m    @pytest.mark.parametrize('number_of_nodes', [2])[0m
[1m    def test_api_channel_events(raiden_chain):[0m
[1m        app0, app1 = raiden_chain  # pylint: disable=unbalanced-tuple-unpacking[0m
[1m        token_address = app0.raiden.chain.default_registry.token_addresses()[0][0m
[1m        channel_0_1 = channel(app0, app1, token_address)[0m
[1m …
```
=> Use block number in ChannelNewBalance event

raiden/smart_contracts/Registry.sol, raiden/tests/fixtures/tester.py, raiden/tests/smart_contracts/test_registry.py
Before registering a token and creating a channel manager for it we have
to at least make sure the address has code, so that it can correspond to
a token contract.
To even be more pedantic and certain we could even check if the token contract returns a `>= 0` reply to the `function totalSupply() constant returns (uint256 supply);` call. All ERC20 contracts should have this function.
=> Check that address has code before adding a Token

raiden/tests/smart_contracts/test_channel_manager.py
merge after: https://github.com/raiden-network/raiden/pull/728
This PR simplifies the current test suit for the channel manager smart contract
=> Channel manager tests

raiden/channel/netting_channel.py, raiden/connection_manager.py, raiden/event_handler.py, raiden/tests/integration/test_settlement.py
The properties `deposit` and `contract_balance` are redundant. So far
most code inside `raiden` uses `contract_balance`. In order to prevent
mixed usage and to avoid the semantic clash with the `deposit(amount)`
function, I removed the `deposit` property.
=> Remove duplicated property from netting channel

raiden/smart_contracts/ChannelManagerContract.sol, raiden/smart_contracts/ChannelManagerLibrary.sol, raiden/tests/smart_contracts/test_channel_manager.py
Merge after: https://github.com/raiden-network/raiden/pull/729
The channel manager deletes the channel only when a new one is created on top.
The old implementation first cleared the netting channel from its data structures, and followed to re-add the new channel to the same data structures. While doing so, the indeces update mixed addresses values, example:
node_index[msg.sender][our_last_element] = caller_index;
`our_last_element` is a *channel address*, while node_index maps a *node address* to an array position.
To properly handle the above case a new mapping would be required, instead of adding yet another mapping I streamlined the code, instead of remove-to-add this patch just overwrite the new netting channel address on top of the old entry.
=> Channel manager delete

raiden/smart_contracts/EndpointRegistry.sol
Fixes the new solidity warning for EndpointRegistry.
```
Warning: This is a pre-release compiler version, please do not use it in production.                                                                                                                                                                                            
EndpointRegistry.sol:32:9: Warning: Variable is declared as a storage pointer. Use an explicit "storage" keyword to silence this warning.                                                                                                                                       
string old_socket = address_to_socket[msg.sender]; …
```
=> Use explicit storage keyword in endpoint registry

docs/Rest-Api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/exceptions.py, raiden/tests/api/test_api.py, raiden/tests/utils/apitestcontext.py
Fix https://github.com/raiden-network/raiden/issues/743
=> Handle invalid settle timeout in REST API open_channel

raiden/api/rest.py, raiden/api/v1/encoding.py, raiden/api/v1/resources.py, raiden/tests/utils/apitestcontext.py
In commit 75dff925b1351da6ab043a79fafb34ce37a0af97 `wait_for_settle` and
`timeout` arguments were removed from both the connection manager and
the python API leave() calls.
The Rest API call was not updated and this PR handles that.
Fix https://github.com/raiden-network/raiden/issues/744
=> Remove unneeded args from leave() Rest API call

raiden/network/upnpsock.py
Issue #754
Unsure what caused this error but disabling error ignoring works fine for now.
=> Workaround for error on IP address encoding at UPnP setup #754

raiden/accounts.py
When giving no address we failed with exception:
```
File "/home/lefteris/.virtualenvs/raiden/bin/raiden", line 11, in <module>
File "/home/lefteris/ew/raiden/raiden/__main__.py", line 11, in main
run(auto_envvar_prefix='RAIDEN')
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 722, in __call__
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 697, in main
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line …
```
=> If address is none don't fail

raiden/app.py
Solves an error the devp2p greenlet. The services variable is required to be a dict. This error occurs at the start of raiden
https://gist.github.com/agatsoh/0aeeab494cb4b2958dfa86636d54c59d
=> Making services a dict as required by the devp2p greenlet

tools/deploy.py
This updates the deploy script to take advantage of the dependency handling in pyethapp's `JSONRPCClient.deploy_solidity_contract()`.
Also add logging and other small fixes
=> Fix deploy script

.gitignore, .travis.yml, MANIFEST.in, raiden/tests/fixtures/blockchain.py, raiden/tests/utils/blockchain.py, raiden/tests/utils/genesis.py, raiden/tests/utils/smoketest.py, raiden/tests/utils/tester_client.py, raiden/ui/cli.py, raiden/utils/__init__.py, requirements.txt, setup.py, tools/genesis_builder.py
This adds a `raiden smoketest` command. This fixes #679.
The `smoketest` allows to check the "general sanity" of a raiden installation. Intended usages are
- fail early in CI (`raiden smoketest` will be run before the `pytest` sessions)
- allow to test the raiden CLI interface -- the raiden node started during the test uses the standard `raiden [OPTIONS] COMMAND [ARGS]...` interface
- allow to test the functioning of `AppImage` builds
- help with debugging user issues
The `smoketest` starts a local private go-ethereum blockchain (with clique PoA) with a minimal set of raiden smart contracts already deployed. It will connect a raiden node and assert on the intended state of the raiden node after connection. So far the checks include:
- successful connection to the `Registry` contract
- …
=> Add smoketest command

raiden/network/channelgraph.py, raiden/raiden_service.py
The attribute is not used inside the function and further complicates the (De-)Serialization of channels. I removed it, as proposed in the issue this fixes #745.
=> Remove `block_number` attribute from `add_channel`

MANIFEST.in
At this point in time, we need to ship the tests with the source
distribution (the `smoketest` commmand relies on them and it needs to be
importable from `setup.py`). This commit will also fix our `tox` setup
-- it was broken, because tox uses the `sdist` package to install for
test environments.
=> Include `raiden/tests` in MANIFEST.in / Fix tox / Fix sdist install

raiden/tests/utils/tester_client.py
This PR is related to issue #394 . For geth, ContractProxy methods closed() and opened() will return an empty string, but for tester blockchain None is returned. This inconsistency sometimes breaks tests that expect this value to be of a certain type.
=> fix different return value of contract proxy

raiden/channel/netting_channel.py
These functions are not used anywhere.
- callback_on_opened
- callback_on_closed
- callback_on_settled
=> removed buggy unused callback registration

raiden/tests/utils/smoketest.py
This fixes an import in the smoketest module.
Interestingly the previous form only causes a problem when not running inside a virtualenv.
* `docker run --rm -it python:2.7 python -c 'import distutils; distutils.spawn'`
vs.
* `docker run --rm -it python:2.7 python -c 'import distutils.spawn; distutils.spawn'`
* `docker run --rm -it python:2.7 /bin/bash -c 'virtualenv /venv; /venv/bin/python -c "import distutils; distutils.spawn"'`
=> Fix an import in smoketest

raiden/tests/utils/tester_client.py
Transfers in tests against the `tester` blockchain backend consume too many blocks (~20 per transfer). We should be able to reduce this number considerably by not mining when only querying properties from the smart contracts.
=> Remove `tester_state.mine()` from constant calls

raiden/raidenwebui/src/app/app.module.ts, raiden/raidenwebui/src/app/components/channel-table/channel-table.component.html, raiden/raidenwebui/src/app/components/event-list/event-list.component.ts, raiden/raidenwebui/src/app/components/token-network/token-network.component.html, raiden/raidenwebui/src/styles.css
In Channels and Balances views, as the columns can get quite large because of the addresses, they were overlapping on narrow windows.
This patch adds ellipsis to all datatable fields, as well as "title" for addresses.
This PR shouldn't touch anything outside UI, so can be merged right away.
=> Fix overlapping addresses in views

raiden/ui/cli.py
This also fixes an issue where you get different `datadir`s depending on whether the input address is specified with a leading `0x` or not.
=> Custom click address argument type to unify input addresses

CONTRIBUTING.md, raiden/api/python.py, raiden/channel/balance_proof.py, raiden/encoding/format.py, raiden/event_handler.py, raiden/message_handler.py, raiden/network/channelgraph.py, raiden/network/discovery.py, raiden/network/rpc/client.py, raiden/raiden_service.py, raiden/tests/benchmark/profile_transfer.py, raiden/tests/benchmark/speed.py, raiden/tests/benchmark/speed_simulation.py, raiden/tests/benchmark/speed_transfer.py, raiden/tests/integration/test_events.py, raiden/tests/integration/test_settlement.py, raiden/tests/integration/test_snapshotting.py, raiden/tests/unit/api/test_python_api.py, raiden/tests/unit/test_channel.py, raiden/tests/unit/test_transfer.py, raiden/tests/utils/smoketest.py, raiden/tests/utils/tester_client.py, raiden/tests/utils/transfer.py, raiden/token_swap.py, raiden/ui/console.py
As per our [contributing guide](https://github.com/raiden-network/raiden/blob/master/CONTRIBUTING.md) tried to enforce the proper dict naming at least in the core part of our code. Did not change dicts that are used only in tests.
There were variables like `token_manager` which were impossible to determine by simply reading the code that they were a mapping of `token` to `manager` (what manager??). It sounded more like a variable that holds a token manager (which btw does not exist). 
It was very difficult to read the code with variables like that so I finally went ahead and made the change to make it more readable.
I also took the liberty to make a change in our rule for naming dicts.
Using plural in the dictionaries is fine, but I strongly prefer it if we don't without a good reason. A …
=> Enforce dict naming using `x_to_y`

raiden/ui/cli.py
If no `--address` was passed, `address_encoder` would try to convert a `None` and fail. This fixes that.
=> Fixed address encoding if address is selected via keystore prompt

raiden/event_handler.py, raiden/tests/integration/test_settlement.py, raiden/tests/unit/transfer/mediated_transfer/factories.py, raiden/tests/unit/transfer/mediated_transfer/test_target.py, raiden/tests/utils/tester_client.py, raiden/transfer/mediated_transfer/events.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/state.py, raiden/transfer/mediated_transfer/target.py
Event close was not properly handled, the channel was not being closed when the unsafe region was entered.
=> handling ContractSendChannelClose

raiden/blockchain/events.py
Workaround for #739 
Handle ValueError to avoid raiden crashing when retrieving a channel
that killed itself after close+settle.
TODO: implement proper cleanup of such channels
=> Workaround for invalid netting channel

raiden/smart_contracts/ChannelManagerContract.sol, raiden/smart_contracts/ChannelManagerLibrary.sol
- Moved most of the logic into the library to increase code reuse.
- Removed all_channels_index storage variable.
=> move channel manager code into the library

raiden/channel/netting_channel.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/messages.py
- A node may go offline while there are locked transfers in-transit /
waiting confirmation.
- If the node comes back online *after* any of these transfers have
expired, it *must* accept them to allow progress. This happens because
the partner/sender must order the messages to keep the messages
consistent, and the sender has no logic to  #recompute/remove outdated
messages from the queue. Without accepting outdated messages the
protocol won't make progress.
Note: Accepting a message with an outdated lock is only to progress the
queue, the transfer wont complete because of it, even if the secret is
learned afterwards, and the message wont be mediated because there
isn't enough blocks left to safely mediate a transfer.
=> Accept messages with expired locks.

raiden/channel/netting_channel.py, raiden/event_handler.py, raiden/tests/benchmark/speed_transfer.py, raiden/tests/integration/test_settlement.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/transfer.py, raiden/token_swap.py
The netting channel is not at a position to properly check the
expiration of the lock. The expiration of the lock is defined by the
transfer task, and it takes into account the current pending number of
block until settlement, the payer lock.expiration, and the channel
reveal_timeout configuration. Once the function to create the locked
transfer is called the lock expiration was already decremented the
reveal timeout and the additional blocks are not required for safety.
An alternative to remove the check from the netting channel is to
provide the base expiration, and the create_lockedtransfer method then
decrements the reveal_timeout prior to creating the transfer, this
allows the channel and the transfer task that there are the required
number of blocks for safety.
=> removed lock expiration check from netting channel

raiden/tests/fixtures/blockchain.py
If `.ethash` exists but DAG is missing then we were still trying to remake the directory and failing with an exception. This fixes that.
=> Don't mkdir .ethash directory if existing

raiden/event_handler.py
Added the events in the handler to silence the unknown events log, there is nothing to do when these events happen, they are informational.
=> add missing events to event handler

raiden/event_handler.py, raiden/message_handler.py, raiden/tests/unit/functional/test_directtransferlog.py, raiden/tests/unit/test_operators.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/target.py
This allows a transfer target to reason about received transfers by other means than only matching identifiers with out of band payment requests.
This is e.g. necessary for #651 (an "echo node").
=> Add transfer details to EventTransferReceivedSuccess

raiden/api/rest.py
Return a 400 error with proper message when trying to settle a channel inside settlement period.
Fix #792
=> Return proper error when trying to settle inside settlement period

raiden/ui/web/README.md, raiden/ui/web/package.json, setup.py
Modify `setup.py` to also compile webUI files in `setup.py build`, iff `npm` is available at build time. If not, just skip webUI compilation. It should install `raiden/ui/web/node_modules` npm modules and generate files in `raiden/ui//web/dist` folder, without impacting files outside webUI folders.
=> Compile WebUI files in setup.py build

raiden/network/channelgraph.py, raiden/raiden_service.py, raiden/tests/unit/test_transfer.py
merge after: https://github.com/raiden-network/raiden/pull/724
Handle networkx exceptions when there are no routes for the given target, and set the async result to False.
=> Noroutes test

raiden/api/python.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/unit/api/test_python_api.py
Fix #784 
In the issue one raiden node registers the token and the second tries to
register but fails with "token already registered" while its token list
is empty.
The Rest API call for token registration first checks if
`manager_address_if_token_registered()` and only if it's not, it proceeds with registering.
If it is registered then it returns a 409, but without having also made sure it is registered with the
node and filled in the tokens list. This registering will happen later
if the "TokenAdded" blockchain event is processed but there is a window
where we can miss it and end up with an empty token list.
This PR addresses that.
=> Fix issue 784

docs/Rest-Api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/channel/netting_channel.py, raiden/exceptions.py, raiden/tests/unit/api/test_python_api.py
This PR addresses only a part of the issue https://github.com/raiden-network/raiden/issues/808.
> Another issue can be seen in this example: as seen in the PATCH request, channel balance isn't being updated, and following requests to /api/1/channels also return old balance.
The API call returned the channel without updating its balance. This PR makes sure that this no longer happens.
Note: The balance would eventually get updated, when the node received and processesed the `ChannelNewBalance` event.
=> Api deposit() updates channel balance

raiden/api/rest.py, raiden/exceptions.py, raiden/network/rpc/client.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/utils/tester_client.py
This fixes a situation where someone attempts to create channel with both peers set to the same address.  Instead of "Duplicate channel" more useful exception info is raised. 
The requirement is also checked in the solidity contract.
=> Fix for #785: channel with self

raiden/message_handler.py, raiden/network/protocol.py, raiden/network/rpc/client.py, raiden/tests/integration/test_endpointregistry.py, raiden/tests/utils/tester_client.py
Disabled catch-all logging in the network protocol module to see what breaks during the tests.
=> disabled catch-all exception

raiden/network/utils.py, raiden/tests/fixtures/variables.py, raiden/tests/utils/smoketest.py
Find & check a free TCP port that will be later used by geth to bind the RPC interface.
Fixes #759
=> Smoketest - find a free port for geth

raiden/event_handler.py, raiden/network/channelgraph.py, raiden/raiden_service.py, raiden/tests/unit/test_service.py
To make sure we have complete information to find the shortest route, we start healthcheck for every participant we've created a channel with.
This replaces PR #815 to fix #807.
=> Start health check for every neighbour

raiden/network/stunsock.py, raiden/ui/cli.py
Fixes isue #833. Prevents two raiden instances from listening on the same UDP port.
=> Disallow using the same port for two instances

raiden/blockchain/events.py, raiden/network/rpc/client.py, raiden/tests/integration/test_events.py, raiden/ui/web/src/app/components/event-list/event-list.component.ts, raiden/ui/web/src/app/models/event.ts, raiden/ui/web/src/app/services/raiden.service.ts, raiden/ui/web/src/polyfills.ts
Additionally, parse and return **block_number** in events filter, so most of the events retrieved from geth node will be correctly filled with the block_number it happened.
This should fix #808
=> Use '0x0' as default for from_block, instead of 'latest', to include logs since genesis. Fix #808

raiden/utils/__init__.py
=> Use channel distributable in API channel call

raiden/ui/cli.py
Expose `slogging`'s `log_json` parameter as a command line option.
This will make log aggregation on the testnet much easier and shouldn't hurt otherwise.
=> Add --log-json option

raiden/app.py, raiden/raiden_service.py, raiden/tests/utils/network.py, requirements.txt
This safety check will prevent two Raiden instances using a same data directory. It uses fcntl() on a known lock file path, and raiden will refuse to start if an exclusive lock for this file exists.
It doesn't prevent anyone from connecting to sqlite database or from altering contents of the data directory.
=> Prevent two instances from using a same dir

raiden/token_swap.py
Merge after: #843
removed block number race
- the block number might change from the time the message was created and
when the message was registered, this may lead to valdiation errors
- the maker doesnt need to decrement reveal_timeout, since it doesnn't
have a backing transfer and it controls the unlocking of the token
=> Token swap block number

docs/Rest-Api.rst, raiden/api/rest.py, raiden/tests/unit/api/test_python_api.py
Just a simple pathch fixing issue #818 - using REST api, return a proper error message instead of error 500 if address funds are insufficient to do a deposit.
=> REST returns InsufficientFunds instead of E500

raiden/raiden_service.py
This isn't really a bug, but I think smoketest shouldn't confuse user with a traceback.
=> Do not start healthcheck for a bootstrap address

raiden/api/python.py, raiden/channel/netting_channel.py
The issue was identified during webUI testing. Deposit events weren't being handled inside Raiden, and deposit http request to the API timed out, even if the event came and even showed up in the UI.
This commit fixed it, changing blocking `gevent.wait` to explicit `while` loop with `gevent.sleep`, which preempts itself in order to not block event loop from events handling.
=> Fix deposit not being identified and timing out

raiden/api/python.py, raiden/api/rest.py, raiden/exceptions.py, raiden/network/rpc/client.py
Return E409 instead of E500 for invalid inputs, such as
- token address contract contains no code
- manager for a token does not exist
- attempt to create an already existing channel
=> REST api fixes

raiden/api/python.py, raiden/channel/balance_proof.py, raiden/channel/netting_channel.py, raiden/channel/participant_state.py, raiden/encoding/messages.py, raiden/event_handler.py, raiden/message_handler.py, raiden/messages.py, raiden/mtree.py, raiden/raiden_service.py, raiden/tests/integration/test_events.py, raiden/tests/integration/test_settlement.py, raiden/tests/property/smart_contracts/test_nettingchannel.py, raiden/tests/smart_contracts/netting_channel/test_close.py, raiden/tests/smart_contracts/netting_channel/test_updatetransfer.py, raiden/tests/smart_contracts/test_channel_manager.py, raiden/tests/unit/test_channel.py, raiden/tests/unit/test_mtree.py, raiden/tests/unit/test_transfer.py, raiden/tests/unit/transfer/mediated_transfer/test_target.py, raiden/tests/utils/messages.py, raiden/tests/utils/tester_client.py, raiden/tests/utils/transfer.py, raiden/token_swap.py, raiden/transfer/mediated_transfer/state_change.py, raiden/transfer/state.py
Since https://github.com/raiden-network/raiden/pull/843 the Secret message can be used to call close / updateTransfer. This PR changes the code to properly validate the Secret transferred amount and update the available balance proof.
=> Channel and balance proof

raiden/api/python.py, raiden/network/channelgraph.py
This PR does two things:
1. Allow us to have a configurable settle timeout less than the default one. For some reason the API call was taking the default as the minimum.
2. If a channel has already been opened in the blockchain with invalid parameters we can recover from the error and simply ignore it.
=> Fix settle timeout problems

raiden/blockchain/events.py, raiden/network/channelgraph.py
Before we were only registering the node in the graph when getting the
`ChannelNew` event. If Raiden restarts and we restore either from the
Channel Manager or from the saved channels then we won't add the channel
to the Graph and will end up not finding a path.
=> Add graph edge when registering channel

raiden/blockchain/events.py, raiden/network/rpc/client.py, raiden/ui/web/src/app/components/event-list/event-list.component.html, raiden/ui/web/src/app/components/event-list/event-list.component.ts, raiden/ui/web/src/app/services/raiden.service.ts
Also, fix events fetching in webUI so it can get only events since contracts are deployed (avoid querying whole chain), and after initial events fetch, fetch only `latest` block. This should make webUI and events watching usable with **geth**.
=> Use eth_getLogs to fetch events. Fix #452

raiden/network/protocol.py, raiden/network/transport.py
The protocol may stop while an incoming packet is being handled, when
the `RaidenProtocol:receive` finish processing the incoming packet and
tries to send the ACK the transport layer may be already stopped and the
socket closed.
=> Check the socket is open prior to sending ACKs

tools/join-contracts.py
Useful helper for various cases where a single source file is needed e.g. when verifying contracts on etherscan.
=> Add tool to create combined smart contract files

raiden/raiden_service.py
If we start raiden after a contract upgrade we will get an exception due
to a key error due to trying to load channels from non-existing channel
managers.
```
No handlers could be found for logger "filelock"
DEBUG:raiden.tasks      starting block number block_number=1527082
DEBUG:eth.chain.tx      deserialized tx tx=54b07621
File "/home/lefteris/.virtualenvs/raiden/bin/raiden", line 11, in <module>
File "/home/lefteris/ew/raiden/raiden/__main__.py", line 11, in main
run(auto_envvar_prefix='RAIDEN')
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/click/core.py", line 722, in __call__
File …
```
=> Add registry address to serialized data

raiden/channel/netting_channel.py, raiden/channel/participant_state.py, raiden/raiden_service.py
If we do a few direct transfers and then shut raiden down for a bit then we have a problem.
Once we restart raiden, then the channel would show we have the same balance as
before we did any transfer since it did not restore our transferred amount or our
partner's state amount.
This PR simply adds it to the pickled data and restores it.
=> Save and restore transferred amount

raiden/api/rest.py
`EventTransferReceivedSuccess` contained the initiator address in binary and that should be exported in hex. Perhaps other events also need tweaking if the same error appears, but this is a fix for #911.
=> Fix exporting of TransferReceivedSuccess

raiden/channel/netting_channel.py, raiden/raiden_service.py
This could be a possible solution to
https://github.com/raiden-network/raiden/issues/903.
If we have made direct transfers in a channel and then restart and use
that channel again either for direct or mediated transfers the nonce our
partner would expect would be different than the one we send since it
was not being serialized.
With this PR we serialize it.
If this PR is merged it's advised to remove your `~/.raiden` directory before restarting.
=> Add our_state.nonce to serialization

raiden/channel/netting_channel.py, raiden/event_handler.py, raiden/raiden_service.py, raiden/tests/integration/test_settlement.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/transfer.py
The function `RaidenService:handle_secret` was discarding the secret balance proof and updating its local state directly by using the method `withdraw_lock`.
This PR fixes `handle_secret`, removes the method  `withdraw_lock` from the `NettingChannel`, and fixes the tests that called it directly.
=> Bugfix remove withdraw lock

raiden/channel/netting_channel.py, raiden/channel/participant_state.py, raiden/tests/unit/test_channel.py
`NettingChannel:release_unlock` was not used, and should not be used, since that function allows the sender to update it's local state (transferred_amount, merkle tree) without a creating a valid balance proof, this could lead to synchronization errors.
This PR is complementary to #925 (merge after it)
=> Bugfix remove unlock lock

Makefile, docker/build.Dockerfile, docs/overview_and_guide.rst
The AppImage creation was outdated: 
- the smoketest configuration was not included
- sqlite3 was missing
- the artifact filename changed
- the webUI was not included.
This PR fixes that.
=> Fix AppImage creation

raiden/tests/integration/test_e2e.py, raiden/transfer/mediated_transfer/mediator.py
Fix #917 
The constant assertions on the alarm task greenlet were due to an illegal `payer_state` being hit when the lock was set to expire.
It's all due to a small typo on the state machine that was not changing the `pair.payer_state` correctly when processing the `ReceiveBalanceProof` state change.
This PR also adds a test for it. The test (without the fix) also produces assertions in the logs, but what was missing was the `EventWithdrawSuccess` being fired for the mediator.
=> Bugfix: Mediator state machine properly handle BalanceProof state change

raiden/api/python.py, raiden/channel/netting_channel.py, raiden/network/protocol.py, raiden/raiden_service.py, raiden/token_swap.py
This allows to make use of the json-logging for log collection and
filtering/aggregation.
=> Use slogging kwargs instead of string format

raiden/ui/web/src/app/app.component.css, raiden/ui/web/src/app/app.component.html, raiden/ui/web/src/app/app.module.ts, raiden/ui/web/src/app/components/channel-table/channel-table.component.ts, raiden/ui/web/src/app/components/event-list/event-list.component.ts, raiden/ui/web/src/app/components/transfer-dialog/transfer-dialog.component.ts, raiden/ui/web/src/app/services/raiden.config.ts, raiden/ui/web/src/app/services/raiden.service.ts
This PR adds an indicator in the top right corner of the app, indicating how much requests are currently pending/on-the-fly. In the future, we plan also to add a menu to this indicator, showing a list of current requests, and, maybe, the possibility of cancelling any of them.
Fix #916 
This PR also moves RaidenService to the new Angular 4.3 HttpClient implementation.
Changed _Raiden_ to _Raiden Network_ on the top navbar.
Fixed channel transfer message color from red to blue.
Made some minor changes to events handling, so less requests will be made against *geth*, improving performance.
=> WebUI requests/busy indicator

raiden/connection_manager.py, raiden/network/rpc/client.py, raiden/tests/utils/tester_client.py
There is a race condition for connecting with newcomers to a token network: if the connection manager's channel target is not satisfied, it will open a channel with addresses that appear. If the newcomer first opened the channel with us, we will catch an Exception.
*edit*: the same race condition can happen during the initial `connect()` call.
We now expect the `DuplicatedChannel` exception and only `deposit` to the new channel in such cases.
=> Properly handle exception for duplicated channels

raiden/raiden_service.py, raiden/ui/cli.py
There were two annoyances with logging:
- the `filelock` logger was not properly configured
- `--logfile <path to logfile>` would not disable the streamhandler logger, hence still spamming into the console
=> Improve logging configuration

raiden/tests/utils/smoketest.py
It is not necessary and messes with the gevent monkeypatching.
=> Don't use grequests in smoketest

raiden/api/rest.py
Prior to this change, all requests to the WSGIServer ended up in
sys.stderr. With using a proper logger, we can have them inside the
standard logs of the application.
=> Use proper logger for REST-API WSGIServer

raiden/transfer/mediated_transfer/mediator.py
Expire mediated transfer pair when either unlock or withdraw failed to stop the error message from repeating.
If a channel is closed while we have a pending lock we correctly [detect](https://github.com/raiden-network/raiden/blob/a025b2f5b56888ce327bf1cb4d2ee5e16d7fc657/raiden/transfer/mediated_transfer/mediator.py#L393) it in the state machine [generate](https://github.com/raiden-network/raiden/blob/a025b2f5b56888ce327bf1cb4d2ee5e16d7fc657/raiden/transfer/mediated_transfer/mediator.py#L402) an event and then at the event handler we log an [error](https://github.com/raiden-network/raiden/blob/a025b2f5b56888ce327bf1cb4d2ee5e16d7fc657/raiden/event_handler.py#L190).
The problem is that this happens for every block between the channel `closing` and the channel `settling` when the state …
=> Expire mediated transfer pair

docs/rest_api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/exceptions.py
If a channel that does not exist was requested via the REST Api we were getting a `500 Internal Server Errror`. This PR fixes that.
=> Proper error at missing channel

raiden/api/rest.py, raiden/ui/cli.py, raiden/ui/web/src/app/services/raiden.config.ts, raiden/utils/__init__.py
With this PR, reverting back some changes made in 94a5c3cf, which avoided `--eth-rpc-address` being correctly passed to the Rest API, for providing `config.production.json` webUI config file with correct web3 address.
For that, changed `split_endpoint` to support getting `host` and `port` from URLs with protocol-prefixes (`http://`, `https://`) and path sufixes.
Last, testing for web3 endpoint on webUI, and falling back to `localhost:8545` in case of failure (e.g.: testnet).
=> webUI: fix config route

.travis.yml, .travis/before_install.sh, .travis/before_script.sh, .travis/install.sh
https://github.com/raiden-network/raiden/pull/951 added 15min to every build. 
- Until we have added caching to the docker build of the bundler (see https://github.com/travis-ci/travis-ci/issues/5358) we should not be calling `make bundle` in the deploy stage at all, when we don't plan to actually deploy it. With caching, we could have the `make bundle` step on every build on `master`, to test it.
- `before_install`, `install`, `before_script` should also only be run on tagged commits.
This also empties the `TEST_TYPE` env variable in the deploy stage to avoid confusion.
=> Shorten travis `deploy` stage on non-tagged commits

Makefile, docker/build.Dockerfile, docs/overview_and_guide.rst
This allows to build the application without `--no-cache` docker build
option and still avoid missing updates in the repository. The dependencies for the bundle build can stay cached.
=> Ensure always up to date repo checkouts in `make bundle`

raiden/ui/web/src/app/components/event-list/event-list.component.ts, raiden/ui/web/src/app/services/raiden.config.ts, raiden/ui/web/src/app/services/raiden.service.ts, raiden/ui/web/src/polyfills.ts
webUI-only changes.
Complementing #935, and implementing the initial aim of #910 on client side, add requests timeout to webUI, with proper error message.
Requests that takes longer than **60 seconds** will be cancelled. This value is configurable in the UI configuration, including `/ui/assets/config/config.*.json` dynamic endpoint for Raiden-provided configuration parameters, through the `http_timeout` config object attribute.
Together with #935 , should fix #900.
=> webUI: Implement http timeout

raiden/ui/web/src/app/services/raiden.config.ts
This should fix eternally hanging web3 test requests when web3 RPC endpoint passed by Raiden isn't acessible nor answering (DROP) from the client's perspective. On timeout, it'll fallback to `config.web3_fallback`, which defaults to `http://localhost:8545`, and make **testnet** webUI working again.
=> Add small timeout on web3 test request

docker/build.Dockerfile
`raiden version --short` needs to be called with the full path to the
script when creating the appimage
=> Fix script location [skip ci]

raiden/message_handler.py, raiden/network/protocol.py, raiden/network/transport.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/integration/test_e2e.py, raiden/tests/integration/test_settlement.py, raiden/tests/integration/test_transfer.py, raiden/tests/unit/api/test_python_api.py, raiden/tests/utils/events.py, raiden/token_swap.py
Merge after: #953
- To avoid races, moved the protocol start to the end of the
constructor. Messages may fail to be processed if the node is partially
instantiated.
- Moved the default registry registration out of the database guard.
- Unconditonally waiting for the endpoint registration.
=> Fixed order of statements RaidenService's constructor

raiden/api/python.py, raiden/raiden_service.py, raiden/tests/benchmark/profile_transfer.py, raiden/tests/integration/test_e2e.py, raiden/tests/integration/test_refund.py, raiden/tests/integration/test_regression.py, raiden/tests/integration/test_settlement.py, raiden/tests/integration/test_transfer.py, raiden/tests/unit/api/test_python_api.py, raiden/tests/unit/test_service.py, raiden/tests/unit/test_transfer.py, raiden/tests/utils/transfer.py
the direct transfer has a surprising property that is not expirable,
meaning that a transfer call that uses a direct transfer underneath may
hang forever, since this can be quite surprising for a user this removes
the optimization where a direct transfer is used by default, relying
solely on the mediated transfer that are cancellable and expirable as
the default transfer type.
=> removed direct transfer optimization

raiden/tests/long_running/flaky/test_token_networks.py, raiden/tests/long_running/test_token_networks.py, requirements-dev.txt
flaky tests have been an annoyance for some time, this PR adds the flaky package that will automatically run the annotated test, the advantage is that we don't need to restart the travis build manually to rexecute the full suite, by default the tests will be reexecute 3 times, which should be enough for most cases.
at the moment I marked only test_participant_selection as flaky, I don't recall the other ones, my idea is to have a separate module for the flaky tests, so that they can be easy to identify, and to move any flaky test to such modules.
=> added flaky

raiden/network/transport.py
This just avoids calling `gevent.sleep` when the throttle policy returns 0 seconds.
The greenlet will context-switch anyways just a few lines further down, when the packet is actually sent, so this doesn't have a negative impact on cooperation, the zero seconds context-switch was only adding unnecessary latency.
=> throttle don't sleep with 0 seconds

raiden/network/protocol.py, raiden/network/transport.py
This fixes a regression, a context switch was introduced after the check
for the state of the datagram server, this context switch exposed a race
that allowed a call to `transport.send` on a closed transport.
merge after #972
=> Fix maybe send ack

raiden/api/python.py, raiden/channel/netting_channel.py, raiden/exceptions.py, raiden/network/rpc/client.py, raiden/tests/integration/test_blockchainservice.py, raiden/utils/__init__.py
Instead of increasing the wait timeout in deposit, we remove it.
Added `wait=True` parameter to contracts methods which didn't depend on the result or exception checking, so we can call `approve` and `deposit` and only wait for the later, allowing both transactions to be mined in the same block.
As the [wait in deposit](https://github.com/raiden-network/raiden/blob/b490e2ee3fb434780733250f0c5a30879ad3a096/raiden/api/python.py#L243) doesn't need to actually wait for the whole transaction to be sent/mined, we just make a small preemptive wait to give other greenlets the opportunity to detect and process the deposit event, and update the balances.
So, it does not actually fixes #878 , as it does not need fixing, but will make deposits quicker, handling better the wide block times in Ropsten.
=> Decrease deposit wait, check and raise on transaction fail

.bumpversion.cfg, docs/what_is_the_dev_preview.rst, raiden/smart_contracts/ChannelManagerLibrary.sol, raiden/smart_contracts/EndpointRegistry.sol, raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/smart_contracts/Registry.sol, raiden/smart_contracts/Utils.sol, raiden/tests/smart_contracts/test_registry.py, setup.py
- `test_all_contracts_same_version` failed on travis `master`. This was due to `setup.py::read_version_from_git` incorrectly returned the empty string when no tags where available.
- the way the contract versions where set up, meant that we had to raise contract versions with every bugfix/patch release. I propose to use `{major}.{minor}._` as `contract_version` (i.e. replace the patch part with an underscore)
- the contract versions are now handled by bumpversion
- I added documentation about the versions
=> Improve (contract) versioning

raiden/connection_manager.py, raiden/network/rpc/client.py, raiden/tests/benchmark/profile_transfer.py, raiden/tests/benchmark/speed_simulation.py, raiden/tests/fixtures/blockchain.py, raiden/tests/fixtures/raiden_network.py, raiden/tests/utils/blockchain.py, raiden/tests/utils/network.py, raiden/tests/utils/tester_client.py, raiden/ui/cli.py, tools/scenario_runner.py
The blockchain fixture/utils was testing the balance of each address
with an unique rpc client, since the rpc client objects store the nonce
as local state, the nonces were not synchronized for the actual test
run. This may be a reason for tests with underpriced transactions
errors.
=> fixture setup using only the deploy service

raiden/tests/benchmark/speed_simulation.py, raiden/tests/fixtures/blockchain.py, raiden/ui/cli.py, tools/scenario_runner.py
We were printing all client communication by default due to a change in
the rpc client ininitialization. This provides an argument for it and
makes it False by default.
=> Don't print client comms by default

raiden/channel/netting_channel.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/transfer.py
These commits are cherry-picked from the work in progress PR #811 -- they fix an error for the channel nonce usage and add a regression test for it.
=> Fix channel nonces

raiden/exceptions.py
The format expected two arguments but only one was provided.
This fixes: travis-ci.org/raiden-network/raiden/jobs/272216632#L1050
=> fixed TransactionThrew format

docs/rest_api.rst, raiden/api/objects.py, raiden/api/python.py, raiden/api/rest.py, raiden/api/v1/encoding.py, raiden/api/v1/resources.py, raiden/connection_manager.py, raiden/tests/api/test_api.py, raiden/tests/utils/apitestcontext.py, raiden/ui/web/src/app/services/raiden.service.ts
- Adds the ability to leave all channels of a token network instead of just those that have received transfers. The default remains the current option, but with an extra argument given to the REST endpoint you can leave all channels you are part of in the token
- The `leave` endpoint now returns a response. The list of all closed/settled channels.
- Simplified the schema for returning a list of addresses. It was quite wasteful to return a list of one-key dictionaries with the same `"address"` key. We now use a simple `AddressList` schema for a list of addresses to be returned by the REST API. Used it also in the endpoint returning the list of tokens. @andrevmatos I think that the webui uses that endpoint so there is going to be a change in its consumption. Can you help point to where the …
=> Add ability to leave all channels of token network

setup.py
Our version reporting is a little brittle for non-released installs from
git: If there is no tag (yet), but the intended version maintained in
`setup.py::version` is higher than the latest available tag, the version
description will be incorrect.
With this commit, we ignore the tag part on un-tagged git commits, which
allows for a better version resolution, especially during CI (i.e. PRs
for a version bump).
=> Ignore git-tag version on non tagged commits

docs/rest_api.rst, raiden/api/rest.py
If you tried to settle inside settlement period, it'd give a `200 OK` response with the text `Settlement period is not yet over` (no JSON encoded). This PR makes it answer with `409 CONFLICT` HTTP response, which is better handled inside webUI, for example, and is consistent with other error responses in the API.
=> Fix error response when settling inside settlement period

docs/changelog.rst, docs/conf.py, docs/index.rst, requirements-dev.txt, requirements.txt
If #1008 is not merged then this PR should be. DO NOT merge both.
---
Proposing to use a changelog from here and on since we got our first
official release. We should integrate this into our release process
This PR uses `releases` for the changelog. It's kind of cumbersome and
not flexible in the way it interprets changelog entries. Each bullet
point must adhere to a specific format as seen in the [usage
docs](http://releases.readthedocs.io/en/latest/usage.html) or else the
sphinx generation of readthedocs will throw an exception.
The proposal also is for every PR that makes a notable change to also have a changelog entry added from here and on.
=> Add the changelog - v2

docs/overview_and_guide.rst
After starting Geth using the instructions in the documentation, Raiden is not able to connect:
```
[Errno 111] Connection refused
```
This can be fixed by adding the `--rpc` while starting Geth.
=> Add RPC parameter while starting geth

docs/changelog.rst, docs/rest_api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/api/v1/resources.py, raiden/connection_manager.py, raiden/tests/api/test_api.py, raiden/tests/fixtures/api.py, raiden/tests/utils/apitestcontext.py, raiden/ui/web/src/app/components/channel-table/channel-table.component.ts, raiden/ui/web/src/app/components/token-network/token-network.component.ts, raiden/ui/web/src/app/models/connection.ts, raiden/ui/web/src/app/models/usertoken.ts, raiden/ui/web/src/app/services/raiden.service.ts
This PR should:
- Test for `ConnectionManager`s with open channels to return in the `/connection` endpoint
- Use sum of deposits in all open channels for a given ConnectionManager on `/connection/<token_address>` endpoint
- ~~Plus [optimization]: try to parallelize open and deposit when joining a token network.~~
Fix #921 and improves the work done in #934 .
=> Improvements to `/connection` API

raiden/message_handler.py, raiden/raiden_service.py, raiden/tests/integration/test_regression.py
This PR fixes the race that caused this build to fail:
https://travis-ci.org/raiden-network/raiden/jobs/275826217#L915
```
Multiple RevealSecret messages arriving at the same time must be
handled properly.
Secret handling followed these steps:
The Secret message arrives
The secret is registered
The channel is updated and the correspoding lock is removed
* A balance proof for the new channel state is created and sent to the
payer
The channel is unregistered for the given hashlock
The step marked with an asterisk above introduced a context-switch, this
allowed a second Reveal Secret message to be handled before the channel was
unregistered, because the channel was already updated an exception was raised
for an unknown secret.
```
=> Fix exception for unknown secret

raiden/network/protocol.py
For channels opened manually with a partner address not yet registered,
the protocol raises an UnknowAddress exception, without being properly
handled properly the health and queue tasks would quit and not recover.
closes #861
=> protocol: waits for the endpoint registration

docs/changelog.rst, raiden/channel/netting_channel.py, raiden/channel/participant_state.py, raiden/message_handler.py, raiden/network/channelgraph.py, raiden/raiden_service.py, raiden/tests/integration/test_settlement.py, raiden/tests/smart_contracts/netting_channel/test_settle.py, raiden/tests/smart_contracts/netting_channel/test_withdraw.py, raiden/tests/unit/test_channel.py, raiden/tests/utils/transfer.py, requirements.txt
Review with care. This PR will make a new release incompatible with the dev preview.
The python code was storing the balance proof structure in the
participant state of the receiving end, this is switched in respect to
the smart contract code and makes it a bit harder to access the
transferred amount of a node since both state objects are required. This
commit switches around the balance proof property to fix these issues.
Progress towards #932.
=> Channel reverse participants

requirements.txt
The `ipaddress` module is necessary to run raiden and was probably required implicitly earlier.
=> Require ipaddress module

raiden/ui/cli.py
Fixes #1070
The address variable wasn't updated correctly, use address_hex instead
and convert when necessary.
@konradkonrad @LefterisJP
=> Pass a valid address to balance request.

.travis.yml, docs/overview_and_guide.rst, raiden/accounts.py, raiden/exceptions.py, raiden/network/rpc/client.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/tests/utils/blockchain.py, raiden/tests/utils/smoketest.py, raiden/ui/cli.py, tools/testnet/files/dockerfiles/geth-testnet/Dockerfile
- Remove dependency to geth's debugTrace call
- Upgrade to geth 1.7.1
- Use the transaction's `status` as per https://github.com/ethereum/EIPs/pull/658 to check if a transaction errored in any way.
Fix #1023
=> Use metropolis transaction error checking

raiden/ui/cli.py
Fix #1078 
With the release of [parity 1.7.6](https://github.com/paritytech/parity/releases/tag/v1.7.6), we  have a byzantium enabled parity client and raiden should now be able to work with it!
This PR also adds a version check for geth too.
=> Enable parity plus Byzantium client version check

.travis.yml, raiden/tests/unit/test_cli.py, raiden/ui/cli.py, tools/testnet/files/dockerfiles/geth-testnet/Dockerfile
- Use tuple comparison in version checks thanks to a comment by @banteg
- Bump geth to 1.7.2
=> Use tuple comparison and geth bump to 1.7.2

raiden/ui/cli.py
The first commit handles address parameters that aren't hexadecimal gracefully. 
The second commit fixes #230
=> Handle non-hex params, fix #230

raiden/network/channelgraph.py, raiden/network/protocol.py, raiden/network/transport.py, raiden/tests/fixtures/raiden_network.py, raiden/tests/integration/test_regression.py, raiden/tests/unit/test_service.py, raiden/tests/unit/test_transfer.py, raiden/tests/utils/messages.py, raiden/tests/utils/tests.py, raiden/tests/utils/transport.py
Users are experiencing problems with transfer because unknown nodes are actually unreachable. Issues #1086 and #1020
=> Disable routes to nodes at the unknown state

.gitignore, .travis/before_script.sh, raiden/network/proxies/channel_manager.py, raiden/network/proxies/discovery.py, raiden/network/proxies/netting_channel.py, raiden/network/proxies/registry.py, raiden/network/proxies/token.py, raiden/tasks.py, raiden/tests/benchmark/profile_transfer.py, raiden/tests/benchmark/speed.py, raiden/tests/unit/test_channel.py, raiden/transfer/state.py, raiden/utils/profiling/profiler.py, raiden/utils/profiling/stack.py
Errors in the [`before_script`](https://github.com/raiden-network/raiden/blob/3f8758c8/.travis/before_script.sh) currently don't block the CI. This fixes that and all accumulated problems.
=> Fail CI on errors in 'before_script.sh'

raiden/blockchain/abi.py
If the solc binary doesn't have the executable flag set, or if the
executable is compiled to a different architecture, the OSError
exception will be raised. This handles the exception and suggests a
solution for the problem.
=> improvement: handling OSError when running solc

docs/changelog.rst, raiden/api/python.py, raiden/tests/api/test_pythonapi.py, raiden/tests/api/test_pythonapi_regression.py, raiden/tests/integration/test_snapshotting.py, raiden/tests/unit/api/test_python_api.py
This fixes the python api close, add a regression test for that problem
and add general tests for it.
=> bugfix: python's api close was non-functional

raiden/network/protocol.py
Some users [report](https://gitter.im/raiden-network/raiden?at=5a1ca4e48b3a9e2c0c25a786)
about the unwanted transfers and seem to worry about them. Reducing the
log message from `log.DEV`(CRITICAL) to `log.warn` will help with users
seeing this only if they got verbose logging output
=> Reduce unwanted transfer logging level

raiden/tests/unit/test_accounts.py, requirements-dev.txt, requirements.txt
- Update to a newer pytest version which includes pytest-catchlog.
- Remove pytest from non-dev requirements (was there a good reason for it to be there?)
- Convert some exception infos to `str` before comparing.
=>  Update pytest, remove it from requirements.txt 

setup.cfg
Just a small adition to setup.cfg to prevent pytest from descending into `node_modules` rabbithole.
=> Prevent pytest from searching node modules dir

raiden/ui/console.py
`io.stringIO` class doesn't accept anything else but unicode strings for its `write()` method.
This commit changes the `io.stringIO` instance to `StringIO.StringIO`.
As a result, `lastlog` and `lasterr` calls in the Raiden's interactive console display the log again.
Fixes #1168
=> console: change io to StringIO

docs/rest_api.rst
The status code `204 NO CONTENT` did not reflect the response from the API in the code.
Instead, a `200 OK` is returned for normal operation:
https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L404
https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L98
=> Documentation: Fix status code for token-leave (API)

snap/snapcraft.yaml
This package will let you publish the latest raiden in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.
=> Add the packaging metadata to build the raiden snap

raiden/accounts.py, raiden/api/rest.py
- Removed what `datadir` in `find_datadir()` is not used by fully covered by if statements
- Fix argument name `file` of `_serve_webui`  to file_name for avoid collision with python built-in object `file`
~~Added predefine `self.wsgiserver` in `__init__ of APIServer` for start() and stop()~~
=> Fix not used, shadows built-in variables

raiden/network/rpc/client.py
Just adding endpoint info to the client connection error as it's useful to see where raiden tried to connect. Especially when you got multiple running clients.
=> Add endpoint info in the client connection error

raiden/tests/long_running/flaky/test_token_networks.py
There was a comarison between `list` and `int` that was always true. After fixing the test fails, so mark it as `xfail` for now. The issue is tracked under  https://github.com/raiden-network/raiden/issues/691
=> Fix comparison in 'test_participant_selection' and mark as xfail

raiden/ui/cli.py
When users try to run raiden on a private network we will fail with a `KeyError` at the moment due to the sync check trying to find an oracle.
With this PR we don't throw an exception but instead we provide an error message to the user to use the appropriate argument so that the sync check does not happen.
Alternative solution. If there is a keyerror automatically disable the sync check.
=> Warn user to remove nosyncheck if running in a private network

raiden/exceptions.py, raiden/network/protocol.py, raiden/network/rpc/client.py, raiden/network/transport.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/integration/test_transfer.py, raiden/tests/utils/tester_client.py, raiden/ui/cli.py
The issue is simple to reproduce. Shut down the ethereum node and wait for a bit until all greenlets start reporting the error message that the ethereum client is offline.
Then try to send a signal to stop raiden. It won't be able to. It will get stuck waiting for the greenlets to close since they are in an endless loop of repeating the RPC connection attempt.
This PR tries to address this issue by doing two things:
1. Introduing a flag in the JSONRPC client that signifies we are shutting down, flipped over when the signal to shut down is received. The reconnection attempts stop one this flag is flipped.
2. Allow for a clean exit of all greenlet by throwing a special exception `RaidenShuttingDown` from there which is caught in all the top places where rpc client calls are made. This way …
=> Stop endless loop at shutdown after connection loss

raiden/api/rest.py
At some point it used to be `file` but was renamed to `file_name` to not
overshadow the built-in python `file`.
But whoever made the change forgot to change the name of the variable in the
way `serve_webui()` determines the name of the files to serve.
Without this change webui does not start and can't load any pages. When trying
to load them we got this error:
```
INFO:raiden.api.rest    127.0.0.1 - - [2018-01-10 15:32:56] "GET /ui/vendor.636d457f414f2bb1f76f.bundle.js HTTP/1.1" 500 412 0.000945
ERROR:raiden.api.rest   [2018-01-10 15:32:56,321] ERROR in app: Exception on /ui/main.bb2c35b48259b3cf3d8f.bundle.js [GET]
File "/home/lefteris/.virtualenvs/raiden/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
response = …
```
=> Fix the file argument name for serve_webui

.travis.yml, raiden/network/rpc/smartcontract_proxy.py, raiden/utils/__init__.py
This enables developer warnings during testing. It also fixes some deprecations that get found by this.
I just removed the `linux_distribution` info for now, but could bring that back with the https://pypi.python.org/pypi/distro package if it's deemed important.
=> Enable developer warning while testing and fix deprecations

raiden/api/python.py, raiden/network/proxies/channel_manager.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_events.py, raiden/tests/utils/network.py, raiden/tests/utils/smoketest.py, raiden/tests/utils/tester_client.py
The is a small flaw in the code for creating a new `NettingChannel` in the `ChannelManager`.
https://github.com/raiden-network/raiden/blob/212d2c23dd1f6484a5f1a02db8b9ce71b81c0917/raiden/network/proxies/channel_manager.py#L93-L96
If `privatekey_to_address(self.client.privkey) == peer1` is true, then the other peer is set correctly. However, it is then assumed that `privatekey_to_address(self.client.privkey) == peer2`is true, which might be wrong.
I solved this by removing one address from the function signature and take the local clients address as the other channel participant.
=> Use the local address implicitly for NettingChannel creation

raiden/api/rest.py
As reported in gitter users were getting an internal server error after
attempting to use the connect endpoint.
```
File "/home/lefteris/.virtualenvs/raidenpy3/lib/python3.6/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
self.run_application()
File "/home/lefteris/.virtualenvs/raidenpy3/lib/python3.6/site-packages/gevent/pywsgi.py", line 908, in run_application
self.result = self.application(self.environ, self.start_response)
File "/home/lefteris/.virtualenvs/raidenpy3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/home/lefteris/.virtualenvs/raidenpy3/lib/python3.6/site-packages/flask/app.py", line 1989, in wsgi_app
return response(environ, start_response)
File …
```
=> Fix 500 internal error during connect API method

.travis.yml, raiden/exceptions.py, raiden/network/rpc/client.py, raiden/network/rpc/smartcontract_proxy.py, raiden/network/rpc/transactions.py, raiden/tests/integration/rpc/test_assumptions.py, tools/testnet/files/dockerfiles/geth-testnet/Dockerfile
- Fixes #1146 
- Bumps travis geth version to 1.7.3
Estimate gas no longer returns max gas for throwing calls but instead throws an
error.
The error in geth looks like:
`{"jsonrpc":"2.0","id":17,"error":{"code":-32000,"message":"gas required exceeds
allowance or always failing transaction"}}`
The error in parity looks like:
`{"jsonrpc":"2.0","error":{"code":-32015,"message":"Transaction execution
error.","data":"Internal(\"Requires higher than upper limit of
80000290\")"},"id":1}`
The raiden estimate gas function now returns `None` if the transaction we are
estimating would throw
=> Fix estimate gas for throwing txs

raiden/exceptions.py, raiden/messages.py, raiden/network/transport.py
Instead of a traceback, a log message is printed out.
Fixes #1137
=> Catch exception on invalid protocol data

.gitattributes
Thanks to the [new release](https://github.com/github/linguist/releases/tag/v6.0.0) of Linguist we [can now have](https://github.com/github/linguist/pull/3973) solidity syntax highlighting in Github.
=> Add Solidity language highlighting in Github

.travis.yml, .travis/prepare_os_osx.sh, raiden/tests/utils/smoketest.py, raiden/ui/cli.py, requirements-dev.txt, setup.py
Don't use detox as it pulls enum34.
Simplify some of the macOS setup with homebrew.
This is a part of #1205
=> Update macOS packaging for py3

raiden/api/python.py, raiden/api/rest.py, raiden/tests/api/test_restapi.py, raiden/tests/utils/apitestcontext.py
Fixes #1224 
I'm not sure about the test as it just tests the APITestContext, not the real implementation.
=> Fix token event API for non-registered tokens.

raiden/network/rpc/client.py
When we are done with requests.Session() we should close it.
This way we can silence all the socket warnings:
```
/home/lefteris/.virtualenvs/raidenpy3/lib/python3.6/site-packages/yaml/error.py:7: ResourceWarning: unclosed <socket object, fd=43, family=2, type=2049, proto=6>
self.name = name
/home/lefteris/.virtualenvs/raidenpy3/lib/python3.6/site-packages/yaml/error.py:7: ResourceWarning: unclosed <socket object, fd=35, family=2, type=2049, proto=6>
self.name = name
/home/lefteris/.virtualenvs/raidenpy3/lib/python3.6/site-packages/yaml/error.py:7: ResourceWarning: unclosed <socket object, fd=41, family=2, type=2049, proto=6>
self.name = name
```
=> Close Requests.Session when done

raiden/api/v1/resources.py, raiden/exceptions.py, raiden/messages.py, raiden/network/discovery.py, raiden/network/rpc/client.py, raiden/tasks.py, raiden/tests/property/smart_contracts/test_nettingchannel.py, raiden/tests/utils/transport.py, raiden/token_swap.py, raiden/ui/cli.py, raiden/ui/console.py, raiden/utils/notifying_queue.py, raiden/utils/profiling/profiler.py, tools/testnet/files/dockerfiles/mkkeystore/mkkey.py, tools/testnet/files/dockerfiles/raiden/raiden, tools/testnet/files/dockerfiles/raiden/raiden_echo_node
More small cleanups for python 3.
- Fix a type annotation in client
- use `super()` instead of `super(Type, self)`
=> More py3 cleanups

requirements.txt, setup.py
Since PyPi package 0.7 was removed and no newer release is available, we
switch to the github source install for now. Using the commit hash
instead of the tag ensures that we're installing the expected source.
=> Use tinyrpc from mbr/tinyrpc @0.7 release commit

.travis.yml, MANIFEST.in, Makefile, docker/build.Dockerfile
This commit removes the old AppImage bundling from the makefile. As a replacement the bundle target in the makefile now creates a pyinstaller image.
I'm far from being an expert with makefiles and docker, so please give this a careful look. One ugly thing is the redefinition of `GETH_URL_LINUX` in the makefile. I'd like to avoid that but don't have a good idea how. Recommendations welcome!
=> Update linux deployment to pyinstaller package

raiden/api/python.py, raiden/api/rest.py, raiden/tests/api/test_restapi.py, raiden/tests/integration/test_echo_node.py, raiden/tests/unit/api/test_python_api.py, raiden/tests/utils/apitestcontext.py, raiden/utils/echo_node.py
This is another solution for #1217 . In contrast to #1221 this PR consistently changes event names to `bytes` internally and decodes them into strings when requested by the API.
Fixes #1217
=> Make event names bytes and decode them in RestAPI

raiden/network/transport.py
With switch to Python3, event name is returned as a bytes array. Because `json.decode` can't work with bytes object, decoding to a string is required.
Fixes #1217
=> Check log settings before logging in hot path

raiden/network/rpc/client.py
Using the entire gas limit in a transaction some times results in it not getting
mined irrespective of the gas price since miners prefer smaller
transactions. Using 80% of the gas limit is working reliably from my tests.
Note: The proper gas limit solution here would be to set it from estimate gas
since estimate gas is now fixed.
This is just a step towards that to fix a problem being seen when using raiden
in ropsten at the moment.
=> Dont use all of gas limit in a transaction

docs/changelog.rst, raiden/ui/cli.py
=> Don't crash when using the '--nat=ext:IP' command line option.

raiden/encoding/signing.py, raiden/messages.py, raiden/transfer/balance_proof.py, raiden/transfer/state.py
Merge after: #1269
Added `BalanceProofUnsignedState` class. This class is used to increase type safety, used only by senders, since the signing is done outside of the state machinery, in contrast to the `BalanceProofState2` which is used only by receivers, since it's a complete balance proof with a signature.
=> Balance proof state

raiden/blockchain/events.py, raiden/blockchain/state.py
This is decoupling the `BlockchainEvents` class from our internal architecture, eventually the method `poll_blockchain_events` will be dropped and the module won't need to know about the raiden architecture.
`get_channel_proxies` is being added because it will be used on a new token network event.
=> Blockchain events

raiden/transfer/events.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/state.py, raiden/transfer/state_change.py
Review/Merge after: #1290 
This does the same thing as 1290, but for the mediator. Most of the functions changed because now we need the channel state, the new functions were added just bellow the previous ones with an `2` at the end.
=> Mediator logic

raiden/api/python.py, raiden/exceptions.py, raiden/tests/unit/api/test_python_api.py
- Renamed some methods to have prefixes (`channel_`, `token_network_`,
and `transfer_`):
- Using `waiting` and `views` modules
- Temporarily removed token_swap
=> Added version 2 of RaidenAPI

raiden/tests/unit/test_wal.py
These are the same as [ac1fd72fe20b12 unit/test_statechange_log.py](https://github.com/raiden-network/raiden/blob/ac1fd72fe20b12a97206eaf8529717b1e864b6bb/raiden/tests/unit/test_statechange_log.py) but using the `raiden.storage` classes
=> added wal tests

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/utils/factories.py, raiden/transfer/mediated_transfer/events.py, raiden/transfer/mediated_transfer/initiator_manager.py, raiden/transfer/mediated_transfer/state_change.py
These are the equivalente to [ac1fd72fe20b12 tests/unit/transfer/mediated_transfer/test_initiator.py](https://github.com/raiden-network/raiden/blob/ac1fd72fe20b12a97206eaf8529717b1e864b6bb/raiden/tests/unit/transfer/mediated_transfer/test_initiator.py) but with the channel state implementation.
=> Initiatorstate tests

raiden/tests/conftest.py, raiden/tests/fixtures/raiden_network.py
I'm using these changes on my development branch, and it seems to reduce the number of flaky tests due to the `RaidenShuttingDown` exception
=> handling RaidenShuttingDown on test tear

raiden/messages.py
decode explicitly returning None where it's needed and using the same argument name
=> fix: consistent return and argument names

raiden/tests/integration/rpc/test_assumptions.py
While testing the `BlockchainListener` in raiden-libs I found out that `toBlock` parameter in `eth-tester` is not inclusive while it is in geth. 
The Blockchain listener in microraiden relies on the geth behaviour, so I add a test for that so it's not forgotten when the test infrastructure changes.
=> Test assumption about inclusive toBlock filter parameter

raiden/network/proxies/netting_channel.py, raiden/raiden_event_handler.py, raiden/tests/fixtures/variables.py, raiden/tests/integration/test_events.py, raiden/tests/integration/test_settlement.py, raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/smart_contracts/netting_channel/test_auxiliary_netting_channel.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/tests/utils/tester_client.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/state.py
These builds failed because the lock ~expired too early~ reveal timeout was too short:
https://travis-ci.org/raiden-network/raiden/jobs/360941960#L1981
https://travis-ci.org/raiden-network/raiden/jobs/360932493#L2608
test_close_channel_lack_of_balance_proof was flaky, failling regularly
because the withdraw function was called too close to the lock
expiration.
In a sample failed test (events for the same node):
- [the secret was learned at block 10](https://travis-ci.org/raiden-network/raiden/jobs/361137080#L1904)
- [close was called on block 31](https://travis-ci.org/raiden-network/raiden/jobs/361137080#L1993)
- [close was confirmed by the event polling on block 34](https://travis-ci.org/raiden-network/raiden/jobs/361137080#L2008) (closed at block
33) and withdraw was sent
- [The …
=> Increase tests reveal timeout

raiden/smart_contracts/ChannelManagerContract.sol, raiden/smart_contracts/EndpointRegistry.sol, raiden/smart_contracts/HumanStandardToken.sol, raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/smart_contracts/Registry.sol, raiden/smart_contracts/StandardToken.sol
- explicitely declaring variables instead of using the destructuring
`var`
- using the keyword `emit` for events
- increased the version to 0.4.21 for the contracts that used events
=> fixed solidity warnings

raiden/blockchain/events.py, raiden/network/proxies/registry.py, raiden/raiden_service.py, raiden/tests/integration/test_pythonapi.py, raiden/transfer/state.py
The `RaidenAPI` calls `RaidenService.poll_blockchain_events` explicitely to
ensure that a transaction recently mined has all the events processed.
This is to update the node state and ensure the user of `RaidenAPI` will
see the expected effects applied.
The problem is that the `AlarmTask` can race with the transaction polling,
and *if* the event handler context-switches the effects may not be
applied once the `RaidenAPI` call returns. The introduced lock will
serialize all calls to `poll_blockchain_events`, forcing the `RaidenAPI`
to wait until the `AlarmTask` finish processing the events.
Note: This change will break if the events are *not* processed in the
`AlarmTask` greenlet.
=> Fix race condition for event handling 

raiden/tests/utils/blockchain.py
If geth's fixture building code fails early then we have to make sure that
we terminate the processes
=> Assure no rogue geth process if fixture fails early

CONTRIBUTING.md
=> Style guide: Multiline docstring should go on its own line

raiden/api/python.py, raiden/blockchain_events_handler.py, raiden/raiden_service.py, raiden/tests/integration/test_settlement.py, raiden/tests/integration/transfer/test_directtransfer_statechanges.py, raiden/tests/smart_contracts/netting_channel/test_close.py, raiden/tests/smart_contracts/netting_channel/test_settle.py, raiden/tests/smart_contracts/netting_channel/test_updatetransfer.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_operators.py, raiden/tests/utils/transfer.py, raiden/transfer/node.py, raiden/transfer/state.py, raiden/transfer/state_change.py, raiden/udp_message_handler.py
ActionForTokenNetwork was initially added to remove duplicated code, but turns out that it made logs harder to read, tests harder to write, and dispatch a bit less explicit.
In retrospect I don't think it's worth having this class to save a few lines of boilerplate in the state change definitions.
=> removed ActionForTokenNetwork

docs/changelog.rst, raiden/tests/utils/smoketest.py
Should fix issue #1237.
If geth binary is missing `$ raiden smoketest` will fail and inform the user what went wrong.
```
$ raiden smoketest
Error: unable to locate geth binary.
Make sure it is installed and added to the PATH variable.
$ sudo pacman -S go-ethereum
$ raiden smoketest
[1/5] getting smoketest configuration
[2/5] starting ethereum
[3/5] starting raiden
[4/5] running smoketests...
[5/5] smoketest successful, report was written to /tmp/tmpsnpvtye2.log
```
=> smoketest: check if geth binary is missing and inform user accordingly

raiden/ui/cli.py
For a mainnet etherscan query we should have the URL should start with `api` and not `mainnet`.
=> Fix etherscan API query for mainnet

raiden/connection_manager.py
Fixes #1359 
I looked at mypy output yesterday and it complained about the same thing:
```
raiden/connection_manager.py:244: error: "add" of "set" does not return a value
raiden/connection_manager.py:245: error: "add" of "set" does not return a value
```
=> Fix usage of set, sets are mutable.

raiden/blockchain/abi.py, raiden/constants.py
Adding this due to the usage of the `emit` keyword.
=> Specify minimum required solc version

CONTRIBUTING.md, raiden/network/blockchain_service.py, setup.cfg
All of a sudden flake8 started reporting a `W504` violation for our code due to us putting the line break after the operator in long expressions with operators that were broken in multiple lines.
This was introduced in the latest version of flake8 and made our code non flake8 compatible right under our noses.
I tried to change it to have the line break before the operator and then flake8 reported a `W503` violation. Damned if you do, damned if you don't.
That looked fishy so I did some digging:
https://github.com/PyCQA/pycodestyle/issues/498
https://github.com/PyCQA/pycodestyle/issues/502
> The W503 bug is already fixed as it’s added to the default ignore list but you have a ignore option configured in setup.cfg and if that’s the case the default ignores aren’t respected anymore. This is …
=> Style guide fix for W503 W504

raiden/tests/utils/smoketest.py
This fixes a regression introduced in 3658169e0ebd71e9f631175146ac8399388681da.
If an invalid RST_GETH_BINARY path is now specified, smoketest also bails out
early now.
While I'm here also use 'shutil.which' instead of
'distutils.spawn.find_executable'. The latter does not really care if the file
it returns is executable.
shutil.which has the added benefit of also handling absolute and relative paths.
see https://github.com/raiden-network/raiden/pull/1353 and
https://github.com/raiden-network/raiden/issues/1237
=> smoketest: allow geth executable to be specified via RST_GETH_BINARY

raiden/api/python.py, raiden/network/proxies/netting_channel.py, raiden/utils/__init__.py
The following pattern is not reliable:
```python
if lock.acquire(): raise Exception()
lock.release()
with lock: pass
```
The call to `lock.acquire` could succeed for the current greenlet, while
there are other greenlets waiting for the same lock with
`acquire(blocking=True)`. Under this circunstance the `release` call
would context-switch to the waiting greenlet, and the previous check
would be "invalidated".
Although the current code doesn't use `acquire(blocking=True)`, and the
problem mentioned above wouldn't occur, the code base is left in a
fragile state that is easy to break. This changes the code to only call
acquire once, and to release the lock only after the action is executed.
Since the change to introduce the `locked` method for `RLock` was rejected,
we need to use the …
=> streamline detection of concurrent operations

docs/changelog.rst, raiden/accounts.py, raiden/tests/unit/test_accounts.py
Should fix issue #1195.
`json.decoder.JSONDecodeError` gets now catched explicitly and the user is informed that the account file is not valid JSON format.
I also added the error number in case an IOError occured to ease troubleshooting.
It is still possible that `os.listdir(self.keystore_path)` raises a PermissionError, but I'm not sure if this is in scope of this PR.
=> Improve AccountManager error handling

raiden/constants.py
[skip ci]
HumanStandardToken.sol uses the `constructor` keyword and I also see other
contracts using solidity v0.4.23 only features. Adjusting the minimum version accordingly
=> Bump minimum required solc version to v0.4.23

LICENSE, setup.py
Fix #1397
We are now using setuptools_scm to read the version for setup.py. The rules are a bit different than the ones we had before but should still be fine. From the [Readme](https://github.com/pypa/setuptools_scm/blob/master/README.rst):
```
In the standard configuration setuptools_scm takes a look at 3 things:
1. latest tag (with a version number)
2. the distance to this tag (e.g. number of revisions since latest tag)
3. workdir state (e.g. uncommitted changes since latest tag)
and uses roughly the following logic to render the version:
- no distance and clean:
`{tag}`
- `distance and clean`:
`{next_version}.dev{distance}+{scm letter}{revision hash}`
- `no distance and not clean`:
`{tag}+dYYYMMMDD`
- `distance and not clean`:
`{next_version}.dev{distance}+{scm letter}{revision …
```
=> Replace read version from git with setup scm

raiden/tests/utils/smoketest.py
=> Raiden starts even if geth is not in the path

raiden/api/rest.py
Gevent 1.3.0 was released today (2018-05-11), and it removed the deprecated module `gevent.wsgi`. This fixes the import
=> gevent.wsgi -> gevent.pywsgi

Makefile, tools/deploy.py
Hello,
I found it a bit confusing to have to specify the `privatekey_hex` to be able to deploy the contracts, so i updated the code base to make the user able to specify the keystore-path as the main raiden command instead. This will use the same `prompt_account` and retrieve the `privatekey_hex` from the selected account. 
As for the `Makefile` change, i removed the `compile` target dependency from `deploy` and you can pass the `keystore-path` to the deploy script using an env var, such that:
```
KEYSTORE=/path/to/keystore/ make deploy
```
This makes things a bit easier.
=> Use prompt_account instead of directly getting privatekey_hex

raiden/accounts.py
Catch UnicodeDecodeError in `AccountManager` which may be caused by non-JSON binary files.
=> Don't choke on binary files in keystore path

docker/Dockerfile, raiden/settings.py, raiden/smart_contracts/EndpointRegistry.sol, raiden/tests/smart_contracts/test_endpointregistry.py, tools/startcluster.py, tools/testnet/main.tf, tools/testnet/roles/raiden/tasks/main.yml, tools/tmuxtest.sh
In Japanese Raiden is written as 雷電. Numerical value of the Unicode codepoint for 雷 (Rai) is 38647. It's in general unassigned according to [this](https://www.speedguide.net/port.php?port=38647) source while 40001 has [been used by some apps](https://www.speedguide.net/port.php?port=40001). In general it's a meaningful value to have as the default port. Also kind of cool.
@ulope Can you have a look? Are these changes sufficient? Also is there any way to make this into a variable used in our yaml files instead of having it hard coded in all of them?
=> Use numerical value of unicode codepoint for 雷 as default port value

raiden/messages.py, raiden/network/proxies/discovery.py, raiden/network/proxies/netting_channel.py, raiden/network/rpc/filters.py, raiden/network/rpc/smartcontract_proxy.py, raiden/settings.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/property/smart_contracts/test_nettingchannel.py, raiden/tests/smart_contracts/netting_channel/test_auxiliary_netting_channel.py, raiden/tests/smart_contracts/netting_channel/test_withdraw.py, raiden/tests/unit/test_accounts.py, raiden/tests/utils/blockchain.py, raiden/tests/utils/tester.py, raiden/tests/utils/tester_client.py, raiden/transfer/mediated_transfer/state.py, raiden/ui/cli.py, raiden/ui/console.py, raiden/utils/__init__.py, raiden/utils/events.py, requirements.txt, tools/deploy.py, tools/genesis_builder.py, tools/scenario_runner.py, tools/startcluster.py
Get rid of all usages of `ethereum.utils`.
Related to #1293
=> Remove usage of ethereum.utils module

raiden/network/matrixtransport.py, raiden/ui/console.py
I found two more uses of `slogging`. One came from the matrix branch and one was missed.
=> Remove further uses of slogging

raiden/network/stunsock.py, raiden/ui/console.py
When starting raiden I got the following error. Not sure if the fix work as intended with the new logging, please have a look @pcppcp 
```
File "/Users/paul/Work/raiden/raiden/ui/console.py", line 12, in <module>
from structlog import StreamHandler, Formatter
ImportError: cannot import name 'StreamHandler'
```
When this was fixed the following appeared:
```
File "/Users/paul/Work/raiden/raiden/network/stunsock.py", line 20, in stun_socket
log.debug('Initiating STUN for %s:%s', source_ip, source_port)
TypeError: _proxy_to_logger() takes from 2 to 3 positional arguments but 5 were given
```
=> Fix module and logging errors

raiden/tests/utils/blockchain.py
It's convenient to be able to attach to the running testing geth. No idea why ipc was disabled for tests in the first place. With ipc enabled again we can put a breakpoint in a test and then attach to the running geth and query it easily like so:
```
$ ps aux | grep geth                                                                                                                                                                                    
lefteris 26383  6.6  1.8 2130888 309100 pts/8  Sl+  15:04   0:00 geth --nodekeyhex f68952f08b60b79a5dbd3ec754ee33e6e52101fcf1d8055fc89979c253b14832 --port 29871 --rpcport 29870 --bootnodes enode://4fd93e573bf5949fadaf092a1e49341267902e76d886bd02360a550df77672b6d1a1c78c9d31
f542d1fc6633d8cc85a0535da432c221560e6e1f32dc8b25b9c9@127.0.0.1:29871 …
```
=> Enable ipc for geth tests

raiden/blockchain/abi.py, raiden/network/blockchain_service.py, raiden/network/rpc/client.py, raiden/tests/integration/fixtures/blockchain.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/tests/integration/test_blockchainservice.py, raiden/ui/console.py, raiden/utils/__init__.py, raiden/utils/solc.py, requirements.txt, tools/deploy.py, tools/init_blockchain.py
- replaces `pyethereum` `solc` helper methods and replaces them with calls from `py-solc` library
=> Replace `ethereum._solidity` with `py-solc`

raiden/blockchain/abi.py, raiden/network/blockchain_service.py, raiden/network/rpc/client.py, raiden/network/rpc/filters.py, raiden/network/rpc/transactions.py, raiden/raiden_service.py, raiden/tests/conftest.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/unit/test_cli.py, raiden/tests/utils/blockchain.py, raiden/ui/cli.py, raiden/ui/console.py, raiden/utils/__init__.py, raiden/utils/events.py, requirements.txt, setup.py
This converts the RPCClient to use the web3 client internally. 
This also removes the last usage of the `pyethereum` dependency.
=> Convert RPCClient to web3 client and remove pyethereum dependency

raiden/blockchain/abi.py, raiden/blockchain/events.py, raiden/network/proxies/channel_manager.py, raiden/network/proxies/discovery.py, raiden/network/proxies/netting_channel.py, raiden/network/proxies/registry.py, raiden/network/proxies/token.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_version.py, requirements.txt, setup.py
This integrates manager from the other repo with raiden. Since it works well, I'd merge this PR now and continue on integrating new contracts.
~~- [ ] remove all solc-related code~~
~~- [ ] move solc checks to `raiden-contracts`~~
~~- [ ] merge `raiden-contracts` changes~~
~~- [ ] update `requirements.txt` and `setup.py`~~
=> Integrate `raiden-contracts` contract manager

raiden/network/rpc/client.py, raiden/utils/solc.py, tools/deploy.py
- fixes compilation for deploy script
- also changes 'pending' to 'latest' when obtaining block number in `gasLimit()` method
(Parity "bug". See: https://github.com/paritytech/parity/issues/8703)
=> Fix `tool.deploy` compilation

raiden/app.py, raiden/blockchain_events_handler.py, raiden/tasks.py
Fix #1490 
In tests we reraise the exception and not terminate the app.
=> Unhandled greenlet exceptions should now terminate app

raiden/blockchain/abi.py, raiden/blockchain/events.py, raiden/blockchain_events_handler.py, raiden/tests/integration/api/test_pythonapi.py, raiden/tests/integration/test_events.py, raiden/tests/integration/test_pythonapi.py
fixes https://github.com/raiden-network/raiden/issues/1480
- use event name variables instead of the actual string name
- add new event decoder and handler
=> Use event name variables, add new event decoders

raiden/network/blockchain_service.py, raiden/network/discovery.py, raiden/network/proxies/channel_manager.py, raiden/network/proxies/discovery.py, raiden/network/proxies/netting_channel.py, raiden/network/proxies/registry.py, raiden/network/proxies/token.py, raiden/network/rpc/client.py, raiden/network/rpc/smartcontract_proxy.py, raiden/network/rpc/transactions.py, raiden/tests/integration/fixtures/blockchain.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_regression.py, requirements.txt
This removes old ContractProxy class - a replacement is available in web3 already.
The idea is as follows:
- any SC used by Raiden should be abstracted as one of the classes in `raiden.network.proxies`
- no contract function should be called directly - use of web3.eth.contract is permitted to proxies only (with exceptions to tests etc.)
- these classes subclass `raiden.network.rpc.smartcontract_proxy.ContractProxy` which includes some common functionality
- transactions are signed locally by the `raiden.network.rpc.client.JSONRPCClient`'s `send_transaction` method
Some of the dead code in `JSONRPCClient` and tests that basically test whatever `web3` library does have been removed as well.
=> Remove ContractProxy

raiden/ui/cli.py
We started requiring checksummed addresses, so we should display them as well.
=> Display checksummed addresses in the account prompt

raiden/app.py, raiden/tests/conftest.py
```
--- Logging error ---
File "/home/hack/work/brainbot/raiden/raiden/network/transport/udp/healthcheck.py", line 64, in healthcheck
protocol.get_host_port(recipient)
File "/home/hack/work/brainbot/venvpy3/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
v = func(*args, **kwargs)
File "/home/hack/work/brainbot/raiden/raiden/network/discovery.py", line 107, in get
endpoint = self.discovery_proxy.endpoint_by_address(node_address)
File "/home/hack/work/brainbot/raiden/raiden/network/proxies/discovery.py", line 87, in endpoint_by_address
raise UnknownAddress('Unknown address {}'.format(pex(node_address_bin)))
raiden.exceptions.UnknownAddress: Unknown address 61c808d8
During handling of the above exception, another exception occurred: …
```
=> Use gevent default exception handler instead of registering a custom one

raiden/app.py, raiden/messages.py, raiden/network/matrixtransport.py, raiden/network/proxies/channel_manager.py, raiden/network/proxies/discovery.py, raiden/network/proxies/netting_channel.py, raiden/network/proxies/registry.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py, raiden/network/rpc/client.py, raiden/tests/fixtures/variables.py, raiden/tests/integration/api/test_pythonapi.py, raiden/tests/integration/test_events.py, raiden/tests/utils/blockchain.py, raiden/ui/cli.py, raiden/utils/__init__.py, tools/deploy.py
Get rid of all usages of `raiden.utils.address_encoder` function.
Also get rid of few occurrences of `raiden.utils.isaddress` function that were added by PRs parallel to #1513.
=> Remove usage of raiden.utils.address_encoder function

raiden/app.py, raiden/network/blockchain_service.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py, raiden/raiden_service.py, raiden/settings.py, raiden/tests/integration/fixtures/blockchain.py
Use the raiden-contracts `ContractManager` for now and disable version checks.
Also fix some styling and add some type annotations.
=> Proxy fixes

raiden/blockchain_events_handler.py, raiden/messages.py, raiden/network/proxies/netting_channel.py, raiden/raiden_event_handler.py, raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/integration/test_events.py, raiden/tests/integration/test_settlement.py, raiden/tests/integration/transfer/test_mediatedtransfer_events.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_wal.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/transfer/channel.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/events.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/state.py, raiden/transfer/mediated_transfer/state_change.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/node.py, raiden/transfer/state_change.py
In preparation for adding the tokens `withdraw` functionality, we are renaming the lock withdraw related variables and functions to use `unlock` / `claimed`
Related issue: https://github.com/raiden-network/raiden/issues/1498
=> Rename lock withdraw to unlock/claimed

raiden/api/python.py, raiden/api/rest.py, raiden/api/v1/resources.py, raiden/network/proxies/registry.py, raiden/tests/integration/api/test_restapi.py
- Fix token_events_errors_for_unregistered_token and unskip it
- Reintroduce the connection_managers_info resource endpoint, fix the corresponding test and unskip it
Fixes #1533
=> Fix skipped restapi tests

raiden/tests/integration/fixtures/blockchain.py, raiden/utils/__init__.py
Simple cleanup.
Also updates the name of the `SecretRegistry` contract name constant to fix the tests.
=> Remove unused block_tag_encoder

raiden/blockchain/events.py, raiden/blockchain/state.py, raiden/blockchain_events_handler.py, raiden/transfer/state.py
Handle `TokenNetworkCreated` events in the state machine.
Fixes #1542
=> Add handling of TokenNetworkCreated events from the new contracts

raiden/tests/integration/api/test_restapi.py
Related to #1552 
Disable this test for now on travis.
=> Skip the flaky test_api_tokens test on travis

raiden/api/python.py, raiden/blockchain_events_handler.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/integration/api/test_pythonapi.py, raiden/tests/integration/fixtures/raiden_network.py, raiden/tests/integration/test_pythonapi.py, raiden/waiting.py, tools/scenario_runner.py
The dispatch of the Block state changed must guarantee the block has
been fully processed for restarts, where fully processed means all the
events have been handled, for this reason the Block state change is only
dispatch after all filters have been handled.
review after: #1505
=> Unified alarm callbacks

raiden/messages.py, raiden/network/proxies/netting_channel.py, raiden/raiden_event_handler.py, raiden/smart_contracts/NettingChannelContract.sol, raiden/smart_contracts/NettingChannelLibrary.sol, raiden/tests/utils/factories.py, raiden/transfer/balance_proof.py, raiden/transfer/channel.py
Adding the locked_amount to the signature. This also means that we add it to the old contracts.
Part of #1538
=> Add locked_amount to signature

raiden/network/matrixtransport.py, raiden/network/proxies/registry.py, raiden/network/rpc/client.py, raiden/network/rpc/smartcontract_proxy.py, raiden/tasks.py, raiden/tests/conftest.py, raiden/tests/fixtures/variables.py, raiden/tests/integration/contracts/test_secret_registry.py, raiden/tests/integration/fixtures/backend_geth.py, raiden/tests/integration/fixtures/backend_tester.py, raiden/tests/integration/fixtures/blockchain.py, raiden/tests/integration/fixtures/raiden_network.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_version.py, raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/integration/transfer/test_mediatedtransfer_events.py, raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py, raiden/tests/integration/transfer/test_refundtransfer.py, raiden/tests/unit/conftest.py, raiden/tests/utils/blockchain.py, raiden/transfer/node.py, requirements-dev.txt, requirements.txt, setup.cfg, setup.py
- adds `tester` blockchain backend that allows test being run with
`eth-tester`/`py-evm` combo (use `pytest --blockchain-backend=tester` )
- some test fixtures reorganization
- travis tests still use `geth`
check before merging:
[skip ci]
=> Add `eth-tester` backend

raiden/messages.py, raiden/transfer/balance_proof.py, raiden/transfer/state.py
This way we don't have to update all state objects for the contracts transition.
Fixes  #1538
=> Add balance_hash property to BalanceProof[Unsigned|Signed]State

raiden/api/rest.py, raiden/exceptions.py, raiden/network/sockfactory.py, raiden/ui/cli.py
Introduced 2 exceptions for both SocketFactory and RaidenAPI
servers. Each of those exceptions are raised when their designated
server's port is already in use. The CLI component in this case would
need to catch those specific exceptions and display error messages
accordingly.
Resolves #1039
=> Resolve address in use

raiden/blockchain_events_handler.py, raiden/encoding/messages.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token_network.py, raiden/raiden_event_handler.py, raiden/tests/integration/contracts/test_secret_registry.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/tests/utils/factories.py, raiden/transfer/channel.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/merkle_tree.py, raiden/transfer/secret_registry.py, raiden/transfer/state.py, raiden/transfer/state_change.py, raiden/utils/typing.py
Fixes part of  https://github.com/raiden-network/raiden/issues/1584 (reveal secret when it is about to expire)
Part of parent `META` issue https://github.com/raiden-network/raiden/issues/1496
Reveal secret when it is about to expire
- adds `events_for_onchain_secretregister` - `transfer/mediated_transfer/target.py`
- adds `ContractSendSecretReveal`
- adds `handle_contract_secretreveal` in `raiden_event_handler.py` and register the secret
- adds unit test
- adds `ContractReceiveSecretReveal`
Batch unlock:
- adds `UnlockProofState2` for the packed merkle tree data
- adds function for packing all the locks, needed to call `unlock` on-chain 
`get_known_unlocks2`
- adds `merkle_leaves_from_packed_data` to rebuild the merkle tree from packed data
- adds unit test to check above function
- adds …
=> Batch unlock

.travis.yml, bors.toml
As per our real life discussion we can test bors -- don't think that the octopus git merge will be really bad for our team due to the amount of people we got, compared to say rustlang.
Regardless they are [working on](https://github.com/bors-ng/bors-ng/issues/138) introducing a flat-commit workflow like we have at the moment so the moment they do we will both have our cake and we will eat it.
For now we can experiment with just having the cake.
P.S.: Not sure if we need to edit travis.yml too, in order to specify branches in our case. The [getting started guide](https://bors.tech/documentation/getting-started/) sounds a bit confusing to me.
=> Add bors.toml

raiden/raiden_event_handler.py, raiden/tests/unit/test_channelstate.py, raiden/transfer/channel.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/state.py
As suggested in https://github.com/raiden-network/raiden/pull/1560#discussion_r196388864
Rename `ContractSendChannelUnlock` to `ContractSendChannelBatchUnlock`
Add `_send` in contract-related raiden event handlers names
bors r+
=> Rename to ContractSendChannelBatchUnlock & contract-related raiden event handlers

raiden/network/proxies/netting_channel.py, raiden/network/proxies/payment_channel.py, raiden/network/proxies/token_network.py, raiden/tests/integration/contracts/test_payment_channel.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/utils/__init__.py, raiden/utils/filters.py
- Add `settle_timeout` function back, however this just return the right value as long as the channel is open. See discussion https://github.com/raiden-network/raiden/pull/1551#discussion_r195461907
@hackaugusto To store the correct `settle_timeout` we need to store it ourselves from the `ChannelOpened` event. I can do the changes to the state machine, but that would change the usage of the proxy anyways. 
>> was fixed by adding a filter
Fixes #1549
=> Fix the PaymentChannel proxy

raiden/transfer/channel.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/mediator.py
- validate the received state changes, since we are using python its possible to receive a json encoded message which is larger than UINT256, which needs to be validated
- validate the sum transferred_amount + locked_amount wont overflow
=> Overflow checks

.travis.yml, bors.toml
The `branches, only` stuff also stopped us from running jobs on forks.
=> Remove bors related changes [skip-ci]

raiden/transfer/mediated_transfer/mediator.py
This doesn't make sense right now as `payer_channel` and `payee_channel` would be the same.
=> Fix typo in set_secret

raiden/network/proxies/netting_channel.py, raiden/network/proxies/token_network.py, raiden/network/rpc/client.py, raiden/tests/integration/contracts/test_payment_channel.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/unit/test_accounts.py, raiden/tests/utils/blockchain.py, raiden/transfer/mediated_transfer/state.py, raiden/utils/__init__.py, tools/genesis_builder.py, tools/startcluster.py
Get rid of all usages of `raiden.utils.encode_hex` function and modify related test cases accordingly.
=> Remove usage of raiden.utils.encode_hex function

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/secret_registry.py
fixes https://github.com/raiden-network/raiden/issues/1584
- adds logic to reveal the secret on-chain in the unsafe region, for the `mediator`
- unit test
=> Secret reveal mediator

.travis.yml, .travis/before_install.sh, .travis/before_script.sh, .travis/install.sh, .travis/run.sh, Makefile, requirements-dev.txt, requirements-lint.txt
- ~Uses `eth-tester` during 'regular' Travis runs (PR, pushes, etc.).~ (Only infrastructure for now, the switch will happen once the test failures with tester are fixed)
- `Geth` is only tested during a once a day cron run
- Splits linting out into a separate build stage so failures terminate quicker
=> Travis speedup

.travis.yml, .travis/update_formula.sh, docs/changelog.rst, docs/overview_and_guide.rst
Will resolve #1243. Currently we will need to add the homebrew-raiden repo to the raiden-network namespace. This merge provides the instructions on how to install raiden for mac using homebrew. It will also contain an update to travis CI to update the homebrew formula when a new release is created.
=> WIP: Add homebrew tap installation

raiden/raiden_event_handler.py
fixes https://github.com/raiden-network/raiden/issues/1619
- use `balance_hash`
- use new channel proxy
=> New handle close channel - handle_contract_send_channelclose2

raiden/messages.py, raiden/raiden_event_handler.py, raiden/transfer/balance_proof.py
fixes https://github.com/raiden-network/raiden/issues/1620
- adds new handler for sending the update balance proof transaction `handle_contract_send_channelupdate2`
- adds utilities for signing the balance proof data + closing signature
=> New on-chain update balance proof handler

raiden/utils/__init__.py, tools/deploy.py, tools/scenario_runner.py
Get rid of all usages of `raiden.utils.decode_hex` function.
=> Remove usage of raiden.utils.decode_hex function

raiden/network/proxies/payment_channel.py, raiden/raiden_event_handler.py, raiden/transfer/channel.py, raiden/transfer/events.py
fixes https://github.com/raiden-network/raiden/issues/1622
- event now contains the participant's balance proofs
- new raiden event handler `handle_contract_send_channelsettle2`
=> New send settle transaction handler & event

raiden/transfer/mediated_transfer/state.py
Funny story on how I spotted that. I was grepping for "hashlock" but mispelled
it and came across that little beauty.
=> Remove unused slot at TargetTransferstate

raiden/tests/conftest.py, raiden/tests/fixtures/variables.py
python3 doesnt add the `L` suffix to the hex encoded number, and we can
use the eth_utils tools to remove the `0x` prefix
=> simplified random_marker fixture

raiden/blockchain/events.py
This function was used to re-install the filter if the ethereum node
went offline. It was decided a few iterations back to move out from this
model, were the Raiden node stays running and recover from external
system unavailability, to a crash-only system (introduced by
9cb9af21c2906e5bd0515f48fbe9229195dc690a)
=> remove filter creation function

raiden/blockchain/events.py, raiden/blockchain_events_handler.py, raiden/tests/integration/fixtures/backend_tester.py, raiden/tests/integration/test_blockchainservice.py
- new filter for netting channel & registry is created with a block number of the event. Default value of `pending` can't be used, because if alarm misses some blocks, some events might be missing.
- `BlockchainEvents::add_event_listener()` now won't add a listener if a listener with a same name already exists (maybe we can change `event_listeners` from `list` to `dict`)
=> Do not skip events in case some blocks are missing

requirements-dev.txt
=> Use bump2version instead of the abandoned bumpversion

raiden/tests/integration/test_echo_node.py
This test was flaky with Matrix, couldn't reproduce locally, still looking for a proper solution.
=> Skip test_echo_node.py::test_event_transfer_received_success if not udp

raiden/tests/integration/conftest.py, raiden/tests/integration/fixtures/transport.py
Fixes invalid use of `pytest.skip()` during test discovery.
=> Fixes `skip_if_not_udp` fixture

raiden/tests/integration/fixtures/transport.py
- fixture is buggy and skips everything (my bad). This fixes it so only non-udp tests are skipped.
=> Fix `skip_if_not_udp` fixture

raiden/blockchain/events.py, raiden/network/transport/matrix.py, raiden/tests/integration/api/test_restapi.py, raiden/tests/integration/fixtures/raiden_network.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_echo_node.py, raiden/tests/integration/test_regression.py, raiden/tests/integration/transfer/test_directransfer_events.py, raiden/tests/integration/transfer/test_refundtransfer.py, raiden/transfer/node.py, raiden/ui/cli.py, raiden/utils/echo_node.py, tools/install_synapse.sh
Fix #647 , #1423, #1502 , #1552 , #1704
This PR fixes a lot of problems witnessed mainly with Matrix, due to its longer response times, but were not caused by it, but mostly by events not being properly handled.
Flaky test fixed:
- `raiden/tests/integration/test_echo_node.py::test_event_transfer_received_success`
Tests fixed and unskipped:
- `raiden/tests/integration/test_echo_node.py::test_echo_node_response`
- `raiden/tests/integration/test_echo_node.py::test_echo_node_lottery`
- `raiden/tests/integration/api/test_restapi.py::test_api_tokens`
- `raiden/tests/integration/test_blockchainservice.py::test_blockchain`
- `raiden/tests/integration/test_regression.py::test_regression_unfiltered_routes`
- `raiden/tests/integration/transfer/test_refundtransfer.py::test_refund_transfer_after_2nd_ho …
=> Fix flaky `raiden_chain` fixture, re-enable tests

raiden/tests/utils/events.py, raiden/utils/echo_node.py
The echo node tests failed after the merge of smart contract integration branch. This should fix them.
=> Add token_network_identifier arg to get_channel_events_for_token

raiden/raiden_event_handler.py
The smart contract function `settleChannel` enforces order of the
arguments based on sum of transferred and locked amount.
function settleChannel(
address participant1,
uint256 participant1_transferred_amount,
uint256 participant1_locked_amount,
bytes32 participant1_locksroot,
address participant2,
uint256 participant2_transferred_amount,
uint256 participant2_locked_amount,
bytes32 participant2_locksroot
)
These values must correspond to two valid balance proofs
(TokenNetwork.sol:504):
require(verifyBalanceHashData(
participant1_state,
participant1_transferred_amount,
participant1_locked_amount,
participant1_locksroot
));
require(verifyBalanceHashData(
participant2_state,
participant2_transferred_amount,
participant2_locked_amount,
participant2_locksroot
));
And the sum of the transferred …
=> Fixed the call to settle

raiden/tests/conftest.py
tester not should be the default blockchain, it doesn't behave *exactly*
like geth and can fail differently then an actually ethereum client, as
a consequence tests passing locally does not imply that the build will
be green.
=> made geth the default blockchain

raiden/tests/conftest.py
pytest's always captures the log output and prints after the test is
executed, with separators for the test setup/execution/teardown. This
however means that all the log output from a test run is duplicated.
This will automatically disable pytest's option if `--log-config` is
used.
=> disable pytest's captlogs if --log-config is used

.gitignore, raiden.spec, raiden/network/proxies/token.py, raiden/network/rpc/client.py, raiden/network/rpc/smartcontract_proxy.py, raiden/network/sockfactory.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/tests/utils/smartcontracts.py, requirements.txt, setup.py, tools/pyinstaller_hooks/hook-raiden_contracts.py, tools/pyinstaller_hooks/runtime_encoding.py, tools/pyinstaller_hooks/runtime_gevent_monkey.py, tools/pyinstaller_hooks/runtime_raiden_contracts.py
Fixes #1550 
Requires raiden-network/raiden-contracts#169, raiden-network/raiden-contracts#178
Also includes a small drive-by-fix for the UPnP port mapper which caused exceptions when exiting Raiden while multiple Raiden nodes were running behind a common UPnP gateway.
=> Fix pyinstaller bundling for raiden-contracts

readthedocs.yml
We need to use Python 3.6 on ReadTheDocs, otherwise, it will break when using 3.6 only syntax (e.g. `var: Type` w/o value assignment).
=> Use Python 3.6 on ReadTheDocs [skip ci]

raiden/network/transport/matrix.py
=> Ensure matrix.log property returns a logger even if called on __init__

raiden/raiden_event_handler.py
At the moment if an `EventTransferReceivedInvalidDirectTransfer` is processed it's logged as an error due to being an unknown event. Since we don't handle it in any specific way yet, just add it to `UNEVENTFUL_EVENTS` so that it's not logged as an unknown event type.
=> Handle EventTransferReceivedInvalidDirectTransfer by ignoring

raiden/api/python.py, raiden/tests/integration/api/test_restapi.py, raiden/tests/utils/__init__.py, raiden/transfer/utils.py
This identifier has a nonce on the blockchain, which makes it very hard
to be calculated only from the parameters given in the request.
As there should never exist more than 1 channel open for each tuple
(registry_address, token_address, own_address, partner_address), we can
just use it to search for the channels we want to interact with.
Channel_identifier is still returned in the request, for information,
but its value is ignored in the tests.
Fix #1765 , broken by the changes introduced in https://github.com/raiden-network/raiden-contracts/pull/170
=> Remove channel_identifier usage to search for channels

raiden/tests/integration/test_events.py, raiden/utils/netting_channel.py
Small fix for one of the failing integration tests
=> Fix channel_identifier in test_events.py::test_query_events

raiden/tests/integration/contracts/fixtures/contracts.py, raiden/tests/utils/smartcontracts.py
the most recent version of the raiden-contract ContractManager includes
the test smart contracts, so we don't need to compile the smart
contracts in the fixures anymore
=> using raiden-contract's precompiled contracts

raiden/api/v1/resources.py, raiden/app.py, raiden/constants.py, raiden/raiden_service.py, raiden/tests/benchmark/speed_simulation.py, raiden/tests/integration/test_recovery.py, raiden/tests/utils/network.py, raiden/ui/cli.py, tools/scenario_runner.py
Depending on the network identifier (mainnet, ropsten e.t.c.) set a different
query start block and forward it to the api event filters.
Fix #1738
=> Set query_start_block depending on the network identifier

raiden/api/python.py, raiden/api/rest.py, raiden/blockchain_events_handler.py, raiden/exceptions.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py, raiden/tests/integration/contracts/test_network_registry.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_events.py, raiden/tests/utils/network.py
The TokenNetworkRegistry class had two methods to instantiate
TokenNetwork proxies in addition to the method available on the
BlockchainService class. This allowed multiple version of the
TokenNetworkProxy to coexist on the same process, making the locking
useless.
=> Raiden must use a single TokenNetworkProxy per TN

raiden/network/blockchain_service.py
During the start of Raiden at the sync_check we had a `to_int()` call that used to expect a hexstr. Now with web3 the conversion of the RPC call to an int happens automatically and to_int fails with the following exception trace: 
```
Traceback (most recent call last):                                    
File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)                                                                                   
File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)                                                                             
File "/home/lefteris/ew/raiden/raiden/__main__.py", line 15, in <module> …
```
=> Fix block number at sync check

docs/rest_api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/blockchain/events.py, raiden/exceptions.py, raiden/tests/unit/api/test_events.py
Apparently in geth the block number argument can only be up to 64 bits in size
and as such arguments with size bigger than that were [rejected](https://github.com/ethereum/go-ethereum/blob/f7d3678c28c4b92e45a458e4785bd0f1cdc20e34/ethclient/ethclient.go#L278) from the geth node itself.
This patch checks that all block number input to the API is within the
acceptable range and throws an error if not. Also added a unit tests for this.
Fix #1809
=> Add check for blocknumber validity

raiden/tests/integration/test_events.py
Added waiting for the newly open channel to be registered on both nodes.
The [test was failing](https://travis-ci.org/raiden-network/raiden/jobs/404382403#L1445) because `app1` didn't always have enough time to fetch the `ChannelOpened` event
```
assert_synched_channel_state(
token_network_identifier,
app0, 0, [],
>           app1, 0, [],
)
def assert_synched_channel_state(
token_network_identifier,
app0,
balance0,
pending_locks0,
app1,
balance1,
pending_locks1,
):
""" Assert the values of two synched channels.
Note:
This assert does not work for an intermediate state, where one message
hasn't been delivered yet or has been completely lost."""
channel0 = get_channelstate(app0, app1, token_network_identifier)
channel1 = get_channelstate(app1, app0, token_network_identifier)
>       assert …
```
=> fix test_query_events

raiden/blockchain/events.py, raiden/network/proxies/token_network_registry.py, raiden/network/rpc/client.py, raiden/raiden_service.py, raiden/tests/integration/long_running/flaky/test_token_networks.py, raiden/utils/filters.py
This web3's Filter replacement class keep the filter's argument, and use `eth_getLogs` on them, updating the `fromBlock` accordingly. It avoid installing the filter and depending on node's state (it's stateless on
the node, not in itself).
Fix #1785
=> Stateless filter

raiden/transfer/channel.py
because there are a few tests for update_contract_balance, instead of
removing it the code to handle the contract new balance was updated
=> function update_contract_balance was not being used

docs/overview_and_guide.rst
The reason for this PR is to remind our users, and ourselves that we have this implicit requirement that the Ethereum account for Raiden is not externally managed in anyway.
Doing so can result in strange behavior caused by:
- race with Raiden signed transactions and nonces against manually sent transactions by the user of the ethereum node
- logic of waiting for the transactions sent to the blockchain to be mined against sending transactions manually with higher gas
- e.t.c.
=> Mention account ownership requirements in the docs

raiden/api/rest.py, raiden/exceptions.py, raiden/network/proxies/payment_channel.py, raiden/network/proxies/token_network.py
This PR makes the token network proxy block instead of throwing a `ChannelBusyError`.
This is changing some behaviour of the API, but that should be fine for now.
Fixes #1839
=> Block on busy channel

raiden/app.py, raiden/ui/console.py
- Removed SigIntHandler, it was never used because the raiden.ui.cli
only instantiates Console if the flag for it is enabled.
- This class was used to enable the console once the node is running,
by hooking up to the Ctrl-C signal and starting the console then
- Removed the BaseService class, this was only used for the Console
- Stopped overwritting the start method from gevent.Greenlet, this is
not the official documented way of inhereting a greenlet.
- removed the interrupt signal from Console, since the class
SigIntHandler was removed
- Removed the related attributers in the App class, which were used by
the console, since the Console has a direct reference to it
=> console cleanup

raiden/api/rest.py, raiden/blockchain/events.py, raiden/constants.py, raiden/network/rpc/client.py, raiden/network/rpc/smartcontract_proxy.py, raiden/tests/integration/api/test_restapi.py, raiden/tests/integration/test_pythonapi.py, raiden/tests/unit/test_cli.py, raiden/tests/utils/client.py, raiden/ui/cli.py, raiden/utils/__init__.py, raiden/utils/filters.py
Fix #1815 
- Introduce a function to handle ethereum node json rpc errors depending on the underlying client
- For all errors that have to do with lack of ETH for gas for a transaction throw the `InsufficientFunds` raiden error. 
- Handle `InsufficientFunds` in the API and return the `PAYMENT_REQUIRED` api error.
- Add tests for all the API calls that create underlying blockchain transactions where the user runs out of funds.
=> Handle insufficient eth for gas

raiden/transfer/state_change.py
Got this trace when running a test. The logging function of `ContractReceiveChannelBatchUnlock` was broken.
```
File "/usr/lib64/python3.6/logging/__init__.py", line 993, in emit
msg = self.format(record)
File "/usr/lib64/python3.6/logging/__init__.py", line 839, in format
return fmt.format(record)
File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/stdlib.py", line 459, in format
record.msg = self.processor(logger, meth_name, ed)
File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/dev.py", line 210, in __call__
for key in sorted(event_dict.keys())
File "/home/lefteris/.virtualenvs/raiden/lib/python3.6/site-packages/structlog/dev.py", line 210, in <genexpr>
for key in sorted(event_dict.keys())
File …
```
=> Fix Logging at ContractReceivechannelbatchunlock

raiden/constants.py, raiden/utils/__init__.py
Small patch that adds `eth-tester` to client validation.
=> Add eth-tester validation

raiden/blockchain/events.py, raiden/raiden_service.py, raiden/tests/integration/fixtures/raiden_network.py, raiden/tests/integration/test_recovery.py, raiden/tests/integration/test_settlement.py, tools/scenario_runner.py
Fix https://github.com/raiden-network/raiden/issues/1561 for good
- Adds a test that shuts a node down, has its counterparty close the channel and when the node restarts we check the close has been seen via the blockchain event polling.
- Install all the filters that were missing at startup
- There was no filter for the SecretRegistry. Created one and also added it in the startup along with the other filters
=> Install all missing filters at startup

tox.ini
After building the web ui if you attempt to run all the tests using pytest raiden, it will try to collect tests in the web-ui's node_modules directory that belong to the node-gyp tool. This will cause the collection process to fail
=> Exclude node_modules directory from pytest detection

raiden/tests/unit/test_tokennetwork.py, raiden/transfer/token_network.py
The token network state machine was not properly cleaning up the channel
state, if the channel state machine returns a new_state set to None the
token network must remove the NettingChannelState from it's map.
fix #1882
=> Fix token network clean up

docs/changelog.rst, raiden/ui/cli.py
=> Provide error if no ethereum account files found in keystore path

docs/_static/sphinxcontrib-httpexample.css, docs/_static/sphinxcontrib-httpexample.js
According to https://github.com/collective/sphinxcontrib-httpexample/issues/28 this might fix the issue of wrongly rendered http docs.
But we need to commit and see if it works on readthedocs.
=> Add httpexample files to _static

docs/changelog.rst, raiden/ui/cli.py
=> Fix print of syncing message

raiden/network/transport/matrix.py
Resolves #1847.
The above issue was caused by having an X number of queues with Y number of messages in each queue that had to be sent away on Raiden's bootstrap. Each queue instantiates a greenlet to process the list of messages, so the more queues we have, the bigger number of greenlets get created.
=> Serially send queued messages to prevent absue of the connection pool

raiden/blockchain_events_handler.py, raiden/connection_manager.py, raiden/network/proxies/payment_channel.py, raiden/network/transport/matrix.py, raiden/raiden_service.py, raiden/tests/integration/long_running/flaky/test_token_networks.py, raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/integration/transfer/test_mediatedtransfer_events.py, raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py, raiden/tests/integration/transfer/test_refundtransfer.py, raiden/utils/filters.py, requirements.txt, setup.py
Some big, but internal to Matrix Transport, changes, which should make room creation, selection and reuse way more reliable:
- Now, matrix doesn't rely on the room name to find or validate it
- Communication rooms are choosen by creation or invitation events only, and could be anonymous rooms
- Room names are used only for better information/debugging, and optional
- When trying to contact a client, checks if we were invited to some room by him, and use it, or try to create a room and invite them. Creates an annonymous room with him if there's conflict on server (prevents a DoS by someone pre-creating the rooms with the pair names)
- This `address->room_id` mappins are stored on matrix server for persistence (done in https://github.com/raiden-network/raiden-libs/pull/107), but not …
=> Matrix improvements

raiden/constants.py, raiden/ui/cli.py
made sure to have a new line after the synching loop, and stopped using
the ansi codes since that was not working on all shells
[ci skip]
=> nicer formating for the sync message

docs/changelog.rst, docs/rest_api.rst, raiden/api/rest.py, raiden/exceptions.py, raiden/network/proxies/token_network.py, raiden/tests/integration/contracts/test_token_network.py
If two deposits are made at the same time, and second deposit is lower than the first one, `TokenNetwork` contract proxy will use incorrect (negative) amount for the update. This will cause an exception being propagated to the REST api, which will return E500 to the client.
`TokenNetwork` proxy checks if the actual on-chain value is lower than the target amount inside the lock-protected block.
Fixes #1916
=> Return E409 on concurrent deposits

raiden/tasks.py
The current `error` level might give the impression that something dangerous happened. But we handle that case internally, so I think `info` is fine.
@LefterisJP
=> Lower the logging level of missed blocks

raiden/api/rest.py
I've seen a couple of times people asking about this error, so I just wanted to add the target being offline as a possibility that hopefully will help troubleshoot faster why transfers aren't working.
=> improve error message to include target being offline

docs/api_walkthrough.rst, docs/overview_and_guide.rst
This PR makes the install instructions more explicit in regards to how
to run the Raiden binary.
Furthermore it also fixes some of the REST calls that had some missing
headers which resulted in the curl request not working
=> More explicit install instructions and minor fixes

docs/changelog.rst, raiden/api/python.py, raiden/api/rest.py, raiden/exceptions.py
- fixes bug in Python API - `open_channel` should raise an exception
if token network does not exist
Fixes #1960
=> Check if token network exists when opening a channel

raiden/tests/integration/api/test_restapi.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/integration/long_running/flaky/test_token_networks.py, raiden/tests/integration/test_recovery.py, raiden/tests/integration/test_settlement.py
The secret registration was being done before the channel was close,
that create a race which made the test fail with the matrix transport.
The test failed because the nodes learned about the secret and unlocked
the transfer off-chain before the channel was closed, making the batch
unlock unecessary, and therefor the test failed.
Fixes #1870
=> fixed test_batch_unlock

.travis/prepare_os_osx.sh, docs/macos_install_guide.rst
Also fixes the macOS install instruction docs.
Second half of the fix for #1893
=> Fix automatic macOS bundling by adding a missing dependency

docs/changelog.rst, raiden/ui/web/src/app/services/raiden.service.spec.ts, raiden/ui/web/src/app/services/raiden.service.ts, raiden/ui/web/tslint.json
If the registration of a token fails, now the application will show an error message with
title: _Token registration failed_ and description _The token was already registered before, or the registering transaction failed_.
=> Display a nicer message if token registration fails

.travis.yml, raiden/tests/integration/cli/conftest.py, raiden/tests/integration/cli/test_cli.py, raiden/tests/utils/smoketest.py, raiden/ui/cli.py, requirements-dev.txt
This pull request adds the following tests:
test_cli_missing_discovery_contract_address
test_cli_wrong_rpc_endpoint
test_cli_wrong_network_id_try_mainnet
test_cli_swap_registry_address_with_discovery_address
test_cli_full_init
test_cli_registry_address_without_deployed_contract
test_cli_missing_data_dir
test_cli_version
test_cli_malformed_registry_address
test_cli_missing_keystore_path
test_cli_missing_password_file_enter_password
test_cli_missing_nat
that test most of the CLI used parameters and wrong scenarios.
There is also a disabled test case DISABLE_test_cli_eth_client_communication
that times out due to functionality removed after commit 2ec2bad.
=> Implement raiden cli tests

raiden/constants.py, raiden/ui/cli.py
This commit adds a dictionary to the constants that maps from chain_id
to the contract addresses.
Fixes #1928
=> Contract address presets for multiple chain ids

requirements.txt
For some reason doing a `pip install -r requirements-dev.txt` was using the
commented out raiden-libs=0.1.1 and not installing the git+gitcommithash URL dependency.
Removing the commented out requirements makes it work again and raiden runs
correctly.
Was failing due to the `max_retries` argument of the GMatrixClient addition made
only after
[this](https://github.com/raiden-network/raiden-libs/commit/0477ce402a8112d1fddcdd77699151281c68e81f) commit.
=> Fix pip install requirements for raiden libs

raiden/log_config.py
In my previous [PR](https://github.com/raiden-network/raiden/pull/2021) there
was a mistake due to conditionally setting the level if disable debug logfile is
given.
This is now fixed and I tested both with and without `--disable-debug-logfile`
and the desired behaviour is now there.
=> Fix logging if debug logfile is disabled

raiden/tests/integration/cli/test_cli.py
I did not run ci integration as this is the only failing test from the daily [early morning cron job](https://travis-ci.org/raiden-network/raiden/jobs/410568868).
I just ran the test locally and confirmed the fix works:
=> Fix test_cli_registry_address_without_deployed_contract

docs/changelog.rst, raiden/ui/web/src/app/components/channel-table/channel-table.component.html, raiden/ui/web/src/app/components/channel-table/channel-table.component.spec.ts, raiden/ui/web/src/app/models/channel.ts, raiden/ui/web/src/app/pipes/token.pipe.spec.ts, raiden/ui/web/src/app/pipes/token.pipe.ts, raiden/ui/web/src/app/services/raiden.service.spec.ts, raiden/ui/web/src/app/services/raiden.service.ts, raiden/ui/web/tslint.json
* Changes `fetchUserToken` in order to propagate JSON RPC errors, previously any JSON RPC errors were suppressed.
* Since the original message is `Invalid JSON RPC response` a new error with a more informative message is thrown instead. 
* `UserToken` is now included in the channel data.
* `TokenPipe` no longer depends on `RaidenService` instead it will now take the `UserToken` from the `Channel`
* `tslint.json` now includes rules about 4 spaces in code and whitespaces in module import
=> Show a webui error when JSON-RPC requests fail

.travis.yml, docker/build.Dockerfile, tools/testnet/files/dockerfiles/geth-testnet/Dockerfile
Noticed we have not upgraded the Geth we use in Travis for a long time. I (and I guess most of you) have been using latest geth locally for a long time so I guess it's time for Travis to follow suit.
=> Bump geth to v1.8.13

requirements-dev.txt
The flaky package allows a failling test to be automatically re-executed
a number of times.
The package is quite useful but we are not using it anymore, and the
flaky plugin is messing up the stack trace of a failing test.
=> Removed flaky

raiden/network/rpc/client.py
- Updating the nonce from the ethereum client is useless if there is no
synchronization among the account's users, where a users may be another
application or multiple JSONRPCClient objects used in Raiden. Because
of this, the logic to update the local nonce view was removed, either
the Raiden node should fully control the account and only one
JSONRPCClient instance per private key is used, or remote signing should
be used.
- To debug nonce problems, i.e. transaction replacement errors, it's
necessary to know if there is more than one JSONRPCClient instance per
account, or if the locking mechanism is not working properly. For the
first case a debug log was added in the JSONRPCClient constructor, for
the latter the send raw transaction was wrapped with log lines to make
it easier to detect …
=> JSONRPCClient nonce simplification

raiden/api/python.py
Revert check for running Raiden node when instantiating python Raiden API.
Fixes: #2057
=> Python API: don't check if Raiden is running

raiden/network/rpc/client.py, raiden/network/rpc/smartcontract_proxy.py, raiden/tests/integration/contracts/test_payment_channel.py, raiden/tests/integration/contracts/test_token.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/integration/fixtures/blockchain.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/tests/utils/network.py, raiden/tests/utils/smoketest.py, raiden/ui/cli.py, tools/deploy.py, tools/init_blockchain.py, tools/scenario_runner.py, tools/transfer_eth.py
review after #2064
The arguments host and port were ignored the argument web3 was given,
this could lead to inconsistencies among the web3 instance and the
JSONRPCClient's attributes host/port. This change removes the extranous
arguments and requires the web3 instance
=> Simplify jsonrpc constructor

.travis/run.sh
This is increasing the amount of details reported by pytest on failures.
This is useful when functions are used to assert on state, e.g.
must_contain_entry, which could have the values partially hidden by the
assertion instrospection.
The flag `--show-locals` adds to the end of each frame the list of local
variables and their values.
The flag `--tb=long` shows the source code of each frame with
annotations.
=> Increased pytest reporting detail

raiden/raiden_service.py, raiden/storage/wal.py
As I found out in #2054 it is quite hard to read from the log what's happening during startup. This adds more debug logging to solve that in the future.
One open question is if we should log all state changes as they get replayed.
=> Add logging for WAL and state replay

raiden/utils/__init__.py
After #2066 the function is unused and superfluous.
Additionally, #2066 implicitly resolved #2027 by
replacing `eth-endpoint_to_hostport`.
The helper had a bug resolving tls rpc-endpoints.
=> Removes eth-endpoint_to_hostport helper

Makefile, raiden/__main__.py, raiden/main.py, raiden/transfer/utils.py, requirements-lint.txt
On most of the cases when a function is missing a parameter it's a bug.
pylint seems to be the only tool that can actually catch this type of
error, although it's not perfect and has some false positives, these
usually few and very localized.
=> Added pylint check for missing function arguments

raiden/blockchain_events_handler.py
The connection manager should be used if there are new channels opened
with the current node *and* if there are new channels available in the
network.
=> Improve connection manager connection retry

CONTRIBUTING.md, raiden/connection_manager.py, raiden/exceptions.py, raiden/network/transport/matrix.py, raiden/network/transport/udp/udp_utils.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/conftest.py, raiden/tests/integration/api/fixtures.py, raiden/tests/unit/test_utils.py, raiden/tests/utils/tester.py, raiden/ui/console.py, raiden/utils/gevent_utils.py
New approach to handle exceptions inside greenlet and make sure all unhandled exceptions bubble up to the main greenlet.
Fixes: #1829
=> Gevent exception handling

.travis/run.sh
tb=long is producing HUGE stack traces, on the order of thousands lines https://gist.githubusercontent.com/hackaugusto/543af552ca051a2bda0378d07f07ab6f/raw/6b81277867620864aff49842b059a892dd3494de/gistfile1.txt , this reverts the change and leaves the locals flag for debugging
=> removed pytest --tb=long

raiden/transfer/node.py, raiden/transfer/state_change.py
The previous implementation of the transaction queue was too restrictive. With the previous implementation if there were two transactions sent for the same purpose, e.g. two close transactions, the one that lost the race would not be removed from the queue, that was the case because only transactions sent by the local node were take into consideration, the strategy to fix that was to use additional state changes (implemented by https://github.com/raiden-network/raiden/pull/2049), but most of these are not necessary with this approach.
=> Transaction queue fixes

raiden/network/transport/matrix.py, requirements.txt, setup.py
Depends on raiden-network/raiden-libs#117
Fixes #2119, #2069, #2058, #2042 and #2029 and try to improve the handling on the hard-to-reproduce issues #1917 and #1897 . 
This PR aims to handle all possible causes of network issues by handling and retrying them at the top-level.
=> Replace max_retries for retry_timeout and retry_delay in Matrix

raiden/transfer/node.py
Review/Merge after: #2112 
This removes transactions from the queue which have been invalidated because of a race
=> Transaction queue handle races

docs/api_walkthrough.rst
Tested that the echo node docs are up-to-date still and they are.
Just made a small clarifying change.
Also changed the use of transfer(s) to payment(s), since that's what the API now uses.
=> Echo node docs fix

raiden/api/rest.py, raiden/tests/integration/api/test_restapi.py
The problem that were happening in #2108 and #2110 were caused, because of the changes I made in  #2038 where the structure of the Events was changed. More exactly payment_network_identifier and token_network_identifier were added which were then not normalized before passing them to the user here: https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L184.
This was solved by adding the encode_byte_values(new_event) in normalize_events_list.
=> Solved events serialization problem

raiden/tests/integration/test_echo_node.py
The short interval between `settle_timeout=64` and `reveal_timeout=18`, with 4 nodes in chain, possibly triggered by the waitings/retries added by latest matrix fixes, made the mediated transfer be received too late, and the [transfer be invalidated on target](https://travis-ci.org/raiden-network/raiden/jobs/414004410#L6681-L6682), which triggered some waits which would never succeed. Tweaking these values to 120/15 should avoid this issue.
Fix #2119
=> Fix test_echo_node by tweaking settle and reveal timeouts

docs/changelog.rst, raiden/constants.py, raiden/raiden_service.py
Resolves #682.
According to my discussion with @hackaugusto, we don't have enough data such as storage requirements to decide how often we need to capture a snapshot. Therefore, we're proposing this simplistic approach of capturing a snapshot every 5K blocks.
=> Snapshot every configured number of blocks

raiden/network/transport/matrix.py
This also removes the handling of `join` events, monitoring new users through the `m.presence` event sent together which includes also the displayname information, so save one http roundtrip per user, as well as handling when user changes displayName (which was triggering the bug by the events being handled before the user set its displayName).
Fix #2137
=> Handle 404 when User.get_display_name, better caching on join discovery room

raiden/transfer/node.py, raiden/transfer/state.py, raiden/transfer/views.py
Seems like pickle works if a namedtuple is defined globally in a module but won’t be able to figure out the namedtuple exists if it’s embedded inside a class.
=> Move *Task namedtuples outside the PaymentMappingState

raiden/raiden_event_handler.py
Failing test traceback during the https://github.com/raiden-network/raiden/pull/2153 PR CI tests.
```
File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/matrix_client/room.py", line 308, in _put_event
listener['callback'](self, event)
File "/home/travis/build/raiden-network/raiden/raiden/network/transport/matrix.py", line 505, in _handle_message
self._receive_message(message)
File "/home/travis/build/raiden-network/raiden/raiden/network/transport/matrix.py", line 548, in _receive_message
if on_message(self._raiden_service, message) and not isinstance(message, Processed):
File "/home/travis/build/raiden-network/raiden/raiden/message_handler.py", line 141, in …
```
=> Fix identifier to results

raiden/transfer/architecture.py, raiden/transfer/channel.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/node.py, raiden/transfer/secret_registry.py
Transactions that are time dependent, i.e. must be mined before a given
block number, must be removed from the pending queue if time window is
lost.
=> Clean expired transactions

raiden/api/rest.py, raiden/tests/integration/api/fixtures.py, raiden/tests/integration/api/test_restapi.py
Fix #2179 
Includex `xfail` test for it
=> Crash Rest API if unhandled exception happens on request

raiden/log_config.py, raiden/routing.py, raiden/ui/cli.py, raiden/utils/http.py, tools/install_synapse.sh
- Re-enable synapse logs, but output them to `stdout`, so pytest folding will keep them separated from most useful ones on `stderr`, like logging/structlog/raiden logs (can still be overriden through `--local-matrix` option/command) [requested [here](https://github.com/raiden-network/raiden/issues/2163#issuecomment-412548604)]
- Set default logging level on root logger, to avoid pytest capturing every debug log on every module, and spamming our logs (can still be overriden through `--log-config=":DEBUG"`)
- Rollover rotating debug log file on startup, to also split them per-session (maxSize will still split them on 5MB mark)
- Minor logs adaptation to structlog syntax
=> Minor logs fixes and improvements

raiden/network/discovery.py, raiden/network/proxies/discovery.py, raiden/tests/integration/test_endpointregistry.py, raiden/tests/unit/test_mock.py
The smart contract function address_by_endpoint allowed a malicious node
to set its address for an endpoint which it did not control. The
functionality was not used and buggy, this removes it.
=> Removed address_by_endpoint from the proxies

raiden/connection_manager.py, raiden/exceptions.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py, raiden/raiden_event_handler.py, raiden/tests/integration/contracts/test_network_registry.py, raiden/tests/integration/contracts/test_secret_registry.py, raiden/tests/integration/contracts/test_token_network.py, raiden/transfer/events.py
Resolves #1966 
Created follow up issues:
- https://github.com/raiden-network/raiden/issues/2194
- https://github.com/raiden-network/raiden/issues/2195
Also, skipped implementing the following points:
- Recoverable: An unlock fails because that participant channel state is already unlocked
- Unrecoverable: unlock while the channel was never settled
@hackaugusto i figured this would add some complexity to the tests as locks require gathering certain states / data to be able to pass them to the unlock call... i think it's possible to add those checks on higher-level tests where all proxy calls go through the token_network and nettingchannel state machines, but i haven't checked on what needs to be done there to implement those cases.
<table border="2" cellspacing="0" cellpadding="6" …
=> Handle Recoverable / Unrecoverable exceptions

raiden/network/rpc/client.py
=> Fix `from` key missing from tx receipt by getting it from tx directly

docs/overview_and_guide.rst
section of the docs. Uses the Infura endpoint as an example.
Resolves #2219, #2093
=> Adds description of --eth-rpc-endpoint usage to the getting started

docs/rest_api.rst
Went through all API calls to make sure they are still valid and that the responses they give are correct. Found a couple of problems for a couple of the endpoints (https://raiden-network.readthedocs.io/en/latest/rest_api.html#get--api-(version)-raiden_events-tokens-(token_address)), but will create separate issues for that.
=> fixing example responses, typos and missing json fields

raiden/network/transport/matrix.py
=> Handle json decode error when matrix display name is invalid

raiden/raiden_event_handler.py
the first argument must be a string
=> fix call to log.error

requirements.txt
Now that gevent has included a fix for https://github.com/gevent/gevent/issues/1260 in a release we should bump to it so that we don't have to manually recompile gevent whenever we use python 3.7
=> Bump gevent to 1.3.6

docs/rest_api.rst
according to Channel Object specification:
state should be the current state of the channel represented by a string. Possible value are: - 'opened': The channel is open and tokens are tradeable - 'closed': The channel has been closed by a participant - 'settled': The channel has been closed by a participant and also settled.
=> change open to opened in example responses

docs/changelog.rst, raiden/ui/web/src/app/components/channel-table/channel-table.component.ts, raiden/ui/web/src/app/components/token-network/token-network.component.ts
Sorting is now done by the decimal values.
Fixes #2277
=> Fix webui balance sorting

docs/changelog.rst, raiden/ui/web/src/app/services/channel-polling.service.spec.ts, raiden/ui/web/src/app/services/channel-polling.service.ts
Changes channel identification mechanism to include `token_address` along with `channel_identifier`
Add check for newChannel being null when checking for balance changes.
Closes #2282
Closes #2284
=> Fix polling mechanism issues

raiden/network/transport/matrix.py, raiden/tests/fixtures/variables.py, raiden/tests/integration/conftest.py, raiden/tests/integration/fixtures/transport.py, raiden/tests/integration/transfer/test_directransfer.py, raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/utils/network.py, raiden/transfer/state.py, raiden/transfer/views.py, requirements.txt, tools/install_synapse.sh
Needed for #1611 and #2208 (contains fixes unrelated to that issue which were accumlating there)
- matrix transport will retry sending a message while it's still in the queue (depending on Raiden upper logic to clean it when successful or not and stop/give up retrying)
- send only if the node is online, or else keeps waiting and send when it comes online
- send Delivered before Processed
- fix an up to 2s delay on first message sent to a partner related to join/create room loop sleep
- cache messages handling for some seconds to prevent a synapse bug when a single send/put message generates 2 event copies, and we only want to handle it once
- fix a race on create/join discovery room in tests, retrying for some times until succesful
=> Fix matrix undefined retries by watching the message queues instead of internal async_results

docs/rest_api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/api/v1/encoding.py, raiden/api/v1/resources.py, raiden/blockchain_events_handler.py, raiden/raiden_service.py, raiden/storage/sqlite.py, raiden/storage/utils.py, raiden/storage/wal.py, raiden/tasks.py, raiden/tests/integration/api/test_pythonapi.py, raiden/tests/integration/api/test_restapi.py, raiden/tests/integration/test_echo_node.py, raiden/tests/integration/test_pythonapi.py, raiden/tests/integration/test_regression.py, raiden/tests/integration/transfer/test_directransfer_events.py, raiden/tests/integration/transfer/test_mediatedtransfer_events.py, raiden/tests/unit/test_wal.py, raiden/tests/utils/events.py, raiden/tests/utils/transfer.py, raiden/ui/web/src/app/components/event-list/event-list.component.ts, raiden/ui/web/src/app/services/raiden.service.ts, raiden/utils/echo_node.py, raiden/waiting.py
The block number is provided through the
RaidenService.handle_state_change function, the block number used in
this function varies with the type of the state change.
Events from the blockchain can use a consistent value (the block number
from the event), but state changes for user actions or protocol messages
must use the current block number known by the node, which will vary on
restart. To avoid inconsistencies on the block_number on restarts, this
value was removed.
=> Removed block_number from the events storage

raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py, raiden/tests/utils/transfer.py
Following the same convention used by gevent.spawn and threading.Thread,
just to be a more familiar style
=> tests: wait_assert with function as the first argument

raiden/raiden_event_handler.py, raiden/raiden_service.py, raiden/tests/utils/transfer.py
- fixes bug where `id -> AsyncResult` pair wasn't created for direct transfers.
- repopulates `identifier_to_results` on startup if there are any pending transfers
=> Fix `identifier_to_results` items lifecycle

raiden/transfer/architecture.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/events.py, raiden/transfer/state_change.py
Some of the state changes and events which inherited from another one were not
testing for equality of attributes of the inherited class. This patch aims to
fix that.
=> User superclass __eq__ for inheriting statechanges and events

raiden/app.py, raiden/raiden_service.py, raiden/tests/utils/tests.py, raiden/ui/cli.py
The user can still close all channels through the REST API
=> Removed unused flag leave_channels

docs/changelog.rst
We forgot to add a changelog entry after https://github.com/raiden-network/raiden/pull/1859
=> Add 2170 to changelog

raiden/api/rest.py, raiden/app.py, raiden/network/rpc/client.py, raiden/network/transport/matrix.py, raiden/network/transport/udp/healthcheck.py, raiden/network/transport/udp/udp_transport.py, raiden/network/transport/udp/udp_utils.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/integration/api/fixtures.py, raiden/tests/integration/api/test_restapi.py, raiden/tests/integration/fixtures/raiden_network.py, raiden/tests/integration/test_service.py, raiden/tests/integration/test_settlement.py, raiden/tests/integration/transfer/test_directransfer.py, raiden/tests/unit/test_matrix_transport.py, raiden/ui/cli.py, raiden/utils/runnable.py
=> Exit longlived greenlets if any of them fails

docs/changelog.rst, raiden/network/proxies/token_network.py, raiden/tests/integration/contracts/test_token_network.py
Fix #2283 
If f two calls on the deposit happen one after another then a `ValueError` will be
thrown for the second one. We don't catch `ValueError`s which will result in a
crash (500 Interval server error).
Turned them to `DepositMismatch` exception and also made the error string more informative
=>  Fix set_total_deposit error handling 

raiden/network/transport/udp/udp_transport.py, raiden/network/transport/udp/udp_utils.py, raiden/utils/runnable.py
Fix udp `AttributeError` of missing `address` member of `UDPTransport`, introduced in #2345 , which broke `master`
Also, fix shadowing of `Runnable`s subclasses `AttributeError` exceptions when redirecting members' access to `Runnable.greenlet` instance, which made it harder to read the logs on this type of errors, introduced in #2208
=> Fix UDP logging

raiden/network/transport/udp/udp_transport.py, raiden/tests/unit/test_notifyingqueue.py, raiden/utils/notifying_queue.py
For the queue to be processed on restarts, where the node has pending
messages from the previous runs, the previous messages must be passed to
the queue and the queue must be set.
=> NotifyingQueue must start set if it has items

raiden/ui/cli.py
=> Handle missing values for gevent.signal callback

tools/gas_cost_measures.py
Some small changes to the gas cost measuring tool that are necessary after the raiden-contracts and eth-tester dependencies have been updated to newer versions.
=> Follow up to PR #1990

raiden/raiden_service.py, raiden/transfer/views.py, raiden/ui/cli.py
Because the REST API assumes that there is only one registry address being used, we cannot use the same database from previous runs. This PR automatically makes a new database when a new smart contract is deployed to avoid weird behavior in the API.
=> Use one database per registry

raiden/tests/integration/cli/test_cli.py
This fixes issues in the CLI integration tests. Example failure:
https://travis-ci.org/raiden-network/raiden/jobs/425197821
Failed locally for 2 reasons:
1. An error was taking place passing bytes such as `b' blah blah'` while `self.logfile.write` was expecting a string. setting `encoding` fixes that.
2. The test was expecting `You are connected` while this wasn't being printed.
=> Resolve CLI test failures. 

requirements-lint.txt, setup.cfg
It does not work with python 3.7 and renders flake8 unusable (it crashes). An issue along
with a fix has been reported to the maintainer
[here](https://github.com/tk0miya/flake8-coding/issues/16) but the repo seems to
no longer be actively maintained.
And to be honest we don't really need this module. The only thing it adds is a
check for the magic comment in the beginning of the file.
[skip ci]
=> Remove flake8-coding module

docs/changelog.rst, raiden/api/python.py
=> Do not take target address into account in filtering for events with no such attribute

requirements-dev.txt
[raiden.tests.utils.events](https://github.com/raiden-network/raiden/blob/d632594b507ea0178d881283b86ea9dc480f40d1/raiden/tests/utils/events.py#L1) uses `web3.datastructures`, which is available on the latest release only
=> test utils required web3 4.6.0

raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/target.py
Recap: To avoid having to rewrite messages, the recipient of a message
must accept a valid message for an expire transfer. This is required
because a sender may be online and try to send a transfer through a node
which just went offline, when the node comes back online the transfer's
lock could have enterred the danger zone or have expired, but the sender
did not rewrite its message queue. In this case the recipient's channel
must validate the received balance proof, but not the transfer, and the
corresponding task (either mediator or target), **must not** continue
with the protocol if the current block is after the start of the danger
zone.
This however, doesn't mean the same message must be processed twice.
It's important for a node to have deliver once semantics, which is
achieved by …
=> target: deliver once semantics

raiden/network/transport/udp/udp_transport.py
there is no synchronization from the to ensure that stop_event is set
after existing tasks which want to send messages, therefor it's not safe
to assert on the event state.
=> bugfix: transport can be used during shutdown

raiden/app.py, raiden/raiden_event_handler.py, raiden/raiden_service.py, raiden/tests/integration/test_recovery.py, raiden/tests/integration/test_send_queued_messages.py, raiden/tests/utils/network.py, raiden/ui/cli.py, tools/scenario_runner.py
Made the event handler into a class and allowed it to be injected
through the App and RaidenService. This class can now be overwritten and
the protocol can be controlled by a custom handler class. This is
intended to be used in testing, where control over the messages is
required, e.g. a test for the secret being registered on-chain needs to
stop the unlock message.
=> Added RaidenEventHandler class

raiden/network/transport/matrix.py, raiden/network/transport/udp/udp_transport.py, raiden/raiden_service.py
This changes the transport class to receive a list of message instead of
a list of events, which removes the necessity of encoding the event from
the transport and moves it to the raiden service.
fixes #2419
=> The transport layer should not know about events

raiden/tests/unit/test_serialization.py, raiden/transfer/state.py, raiden/transfer/state_change.py, raiden/transfer/utils.py
If the state of the pseudo random number generator differs during
restarts the generated message ids won't match and the state of the
nodes will become unsychronized.
=> bugfix: PRNG must be restored on restarts

Makefile, requirements-lint.txt
Also, restrict `isort` to `raiden/` subfolder and skip raiden/ui/web/node_modules/, when present, which fails isort
=> Upgrade pylint to work with python 3.7, isort skip

raiden/storage/sqlite.py
After https://github.com/raiden-network/raiden/pull/2399 we need to increment
the DB version as there has been a breaking DB change and raiden should create a
new DB.
Fix #2440
=> Increment DB version after #2399

raiden/network/proxies/token_network.py, raiden/network/transport/matrix.py, raiden/utils/runnable.py
Since raiden-network/raiden-libs#122, we handle the response in a separate greenlet, calling the callbacks serially. This made the initial sync not finish before calling `MatrixTransport._inventory_rooms`, which made we not listen on all the rooms we should. This fixes it by waiting initial sync to finish before proceeding.
Also, adds some logging to Runnable to debug if a child dies and the parent is killed
Fix #2437
=> Wait for initial sync to complete on matrix

raiden/network/proxies/token_network.py
- Add logging call before sending the RPC call to open a new channel
- Amend the logging call after the RPC call was successfull
=> Improve logging at channel creation

docs/changelog.rst, raiden/connection_manager.py
if the connection manager didnt open enough channels in the first run,
it's because there are not enough nodes in the network to open channels
with. A hot loop is useless for this scneario, instead the node should
wait until a new address join the network before retrying.
fix #2453
=> connection manager: retry only after channel new

raiden/network/proxies/token_network.py, raiden/tests/integration/contracts/test_token_network.py
If the channel is closed, and the settlement window is over, then
settle is allowed, if the transaction failled then there is a bug with
the settlement or the code which calls the smart contract.
ref: https://github.com/raiden-network/raiden/pull/2432#discussion_r217073302
I have the impression that settle failed because of https://github.com/raiden-network/raiden/issues/2410
=> fix exception type

raiden/messages.py, raiden/network/transport/matrix.py, raiden/network/transport/udp/udp_transport.py, raiden/raiden_service.py
Both transports currently basically do `send_async` on each message on these queues anyway. This was done once to allow batch send, but it was never implemented and matrix doesn't even support batch send messages, so it was useless and cluttered the interface (send_async receives a
queue of events and a Message, and start received a queue of messages since #2420).
The transports need to be aware of the events queues anyway, to eventually stop retrying the message once it's cleaned (TODO for UDP), so we can't avoid knowing about the events, but now the serialization
always occurs either in RaidenEventHandler or in RaidenService when starting the transports, so consistent usage of `messages.message_from_sendevent` 
Followup of #2420 and replaces #2458
=> Remove send queued from transports start and to service

raiden/exceptions.py, raiden/network/rpc/smartcontract_proxy.py, raiden/tests/integration/api/fixtures.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/ui/cli.py
The current test_duplicated_transaction_raises test didn't explicitly
set the gas price, this fixes this. It also adds a test for resubmitting
the same tx with the same gas price and checks that the error message
from geth is handled properly.
Also a pre-requisite for #2276
=> Add test for resubmitting a transaction with same gas price

raiden/api/rest.py, raiden/network/rpc/smartcontract_proxy.py, raiden/raiden_event_handler.py, raiden/tests/integration/test_balance_proof_check.py
- checks on-chain state of the channel balance_proof state in order to
use ensure consistent settle call even if partner used empty hash to
`close` the channel or if he didn't call `updateTransfer`
- fixes #2410
=> Check chain data when performing settle

docs/changelog.rst, raiden/app.py, raiden/network/transport/matrix.py, raiden/tests/integration/test_matrix_transport.py, raiden/tests/utils/network.py, raiden/ui/cli.py
Now, a discovery room with canonical name is tried in all available servers, starting with ours. If can join in a different server than ours, but our server doesn't have an alias for it, create the alias, so every server shares a single room, each one aliasing it to the canonical name on itself.
A discovery room creating is attempted only if can't join in any available server, and it isn't fatal, as races may occur on tests, but on tests peers doesn't actually need to join it, as they're on the same synapse test server and therefore there's no need for the discovery room
Fixes #2307
=> Decentralize discovery room

docs/changelog.rst, docs/rest_api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/api/v1/encoding.py, raiden/api/v1/resources.py, raiden/storage/sqlite.py, raiden/storage/utils.py, raiden/storage/wal.py, raiden/tests/unit/api/test_api_events.py, raiden/tests/unit/test_wal.py
Add a timestamp column to the database to record the time when internal events are logged.
Solves #2287.
=> Timestamps for internal events

raiden/api/rest.py, raiden/connection_manager.py
Handle exception described in #2499 also found an unhandled exception in rest.py which was thrown when calling [transfer](https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L947), more exactly it was thrown [here](https://github.com/raiden-network/raiden/blob/master/raiden/api/python.py#L650).
=> Handled exceptions

docs/changelog.rst, raiden/tests/unit/test_tokennetwork.py, raiden/transfer/token_network.py
It might happen that multiple close events are received. This case led
to a race condition in which the channel identifier was already removed
from the channel_id_to_partners dictionary and thus the lookup failed.
This commit fixes this case.
Fixes #2449 
We should still investigate how it happened that two closing transactions were send in #2449
=> Fix race condition for ChannelClosed events

.travis.yml, .travis/install.sh, .travis/run.sh
coveralls reports are inconsistent, probably because we have PRs that
don't run the integrations tests. Additionally the tool is slowing down
the execution of the tests. Removing it for now.
=> travis: removed coveralls

raiden/network/transport/matrix.py
The assumption is that these logs are not useful for the end user, but for us, thus the `debug` level.
An alternative is to keep the logs as info but by default only log errors, like with https://github.com/raiden-network/raiden/pull/2480
=> ui: reduced default verbosity of the transport

docs/changelog.rst, raiden/network/transport/matrix.py, raiden/tests/fixtures/variables.py, raiden/tests/integration/conftest.py, raiden/tests/integration/fixtures/raiden_network.py, raiden/tests/integration/fixtures/transport.py, raiden/tests/integration/test_matrix_transport.py, raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/utils/network.py
Fix #2501 
Fix #2507
And possibly also #473 for Matrix transport
A `config['transport']['matrix']['private_rooms']` boolean configures if we should use and require private rooms.
If `False`, we can still be invited and talk in private ones, but it isn't required and the ones we create aren't, as per the previous behavior (including canonical room names, for easy debugging), usually suited for tests deployments.
If `True`, the rooms we create are private, unnamed, invite only rooms, and only the validated users for the peer we created that room for will be invited.
If someone else creates a room and invite us, we join and that room is only valid ever to communicate with that peer which invited us (so an attacker can't pull us into talking with another peer in their room), **if and only …
=> Matrix private rooms

docs/changelog.rst, raiden/ui/web/src/app/components/event-list/event-list.component.html
=> Add descending order by block_number as default for blockchain events on webui.

.travis.yml, .travis/prepare_os_linux.sh, .travis/prepare_os_osx.sh, docs/changelog.rst, raiden/blockchain_events_handler.py, raiden/constants.py, raiden/exceptions.py, raiden/raiden_event_handler.py, raiden/raiden_service.py, raiden/storage/restore.py, raiden/storage/sqlite.py, raiden/storage/wal.py, raiden/tests/integration/test_settlement.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_wal.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/test_node.py, raiden/transfer/channel.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/events.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/initiator_manager.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/state_change.py, raiden/transfer/state_change.py, raiden/transfer/utils.py, raiden/ui/cli.py
Resolves #2414 
- Updated the Travis image to `xenial` instead of `trusty` as the Sqlite3 version is available in that distro's official repos.
- Added a check for SQLite3 minimum required version
- Fixed the check for `is_valid_lock_expire` and `is_lock_expired` to prevent expiring a lock whose secret is registered on-chain
- Update the settle logic to use balance proofs with balance hashes that match on-chain hashes.
- Update the unlock logic to create a new WAL instance, restore the state changes from the latest snapshot all the way up to a state where balance hash matches values on-chain. Use that restored state to calculate the merkle tree leaves which is then used for unlocking.
=> Old balance proof recovery

docs/changelog.rst, raiden/ui/web/src/app/app.module.ts
Closes #2517
`timeOut` is the timeout after a notification appears and has been now globally increased to 5 seconds from 3 seconds that was the default value.
`extendedTimeOut` starts as soon as the user hovers over the notification and is set to 10 seconds
I did some manual testing, and it seems to work the way we want it to work.
=> Increase the time a notification stays visible on the webui

raiden/api/rest.py, raiden/ui/cli.py
- Fixes raiden app start
- Sends a string and not an enum to the webui for network_type
=> Follow-up after network type PR

raiden/raiden_event_handler.py
=> If our balance hash is empty don't query events for our BP

.bumpversion_client.cfg, constraints.txt, docs/changelog.rst, docs/conf.py, raiden/api/python.py, raiden/tests/fixtures/variables.py, raiden/tests/integration/api/test_pythonapi.py, raiden/tests/integration/api/test_restapi.py, raiden/tests/integration/contracts/fixtures/contracts.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/integration/test_pythonapi.py, raiden/ui/cli.py, setup.py
- Bumping requirements for raiden-libs and raiden-contracts
- Fixing all places in the tests where deposits, number of tokens and token registrations were concerned and failing. Will create a follow-up issue with what needs to be reverted to work with multiple tokens again and the commits that should be looked up.
- Bump version to 0.10.0
=> Bump to 0.10.0

docs/rest_api.rst
Fixed API endpoint in the docu.
=> Docu: Deleted wrong backslash in API 

raiden/blockchain/events.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py, raiden/network/rpc/client.py, raiden/raiden_service.py, raiden/utils/filters.py
The default implementation of filters provided by web3.py rely on the
ethereum node to keep the state of the from_block number. Although this
is convenient it's a problem when either the Ethereum or Raiden node are
restarted, because the previous block number must be remembered to
re-install the filter.
Since the from_block needs to be known anyways instead of relying on the
remote ethereum node to know the from_block the stateless filter was
introduced, which always rely on the start_block number being known.
This just removes the unused code which supported the web3.py Filter
class.
=> Simplified the filter polling

raiden/tasks.py
This is mostly about not displaying `block_hash=HexBytes('0xblablabla')`.
=> Improvements for the new block logging message

raiden/api/rest.py, raiden/network/transport/matrix.py, raiden/raiden_service.py
Fix #2590 
Fix #2592 
A `KeyError` needed to be handled, as it was caused by a race when `/sync` cleaned the room from `_client.rooms` dict before `room.leave` tried cleaning it with `del self.client.rooms[room_id]`, which raised this exception even if the room was properly cleaned.
Also, rest exceptions weren't being properly raised because `flask-restful` was eating it before the default flask `errorhandler`.
=> Fix some error handlers

raiden/blockchain/events.py, raiden/tests/integration/test_integration_events.py
These functions:
- get_netting_channel_closed_events
- get_netting_channel_deposit_events
- get_netting_channel_settled_events
Weren't using the `netting_channel_identifier` argument, therefor the
events for all channels were polled. This was okay since the functions
were used only for testing.
This moves the functions to the testing module and fix the
implementation to use the parameter.
=> Fixed netting event shortcuts

raiden/network/proxies/discovery.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py
To make debugging easier some of the proxies have logs for before and
after the transaction is sent. This adds these logs lines to the missing
proxies.
The general guidelined followed was:
- logs prior to the transaction sent are debugging logs
- logs after the transaction is mined are:
- critical if the transaction failed in an unrecoverable manner
- info if the transaction failed in a recoverable manner
- info if the transaction was successful
- the logs are formatedd with `<smart_contract_function_name> <state>`,
where state is one of these:
- called
- failed
- successful
This did improve the logging but it's not covering all cases, specially
the checks done in the channel proxy which can raise an exception
=> logging: logs before & after all transactions

tools/scenario-player/scenario_player/main.py
Use a higher estimate for the gas limit for transactions in the scenario player
=> [SP] Increase gas estimates for transactions

raiden/app.py, raiden/storage/versions.py
This PR warns the user about older DB version files in the database path. The reason we need this is because at some point, a user can use a Raiden version with DB version X. Once the user upgrades to version X+1 and runs the node, some parts of the chain state will exist in the old version and some other parts in the newer version. 
Related to #2566
=> Warn if older version DB files exist

raiden/utils/cli.py
If a numeric network id is set in the config file it will be an int.
=> Allow numeric network ids

raiden/app.py
Fixes this traceback on startup on master:
```
File "/Users/paul/Work/venv-raiden/bin/raiden", line 11, in <module>
File "/Users/paul/Work/raiden/raiden/__main__.py", line 11, in main
run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 722, in __call__
File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 697, in main
File "/Users/paul/Work/venv-raiden/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
return Command.invoke(self, ctx)
File …
```
=> Fix crash on raiden startup

raiden/blockchain_events_handler.py, raiden/raiden_service.py, raiden/storage/sqlite.py, raiden/tests/integration/test_settlement.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_tokennetwork.py, raiden/tests/unit/test_wal.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/test_node.py, raiden/transfer/architecture.py, raiden/transfer/channel.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/state_change.py
Resolves #2535 
1. Changed all `ContractReceive*` state changes to have the block number at which the event was emitted.
2. Use the `ContractReceiveSecretReveal`'s block number to check against the lock the state_change is unlocking. If the lock has already expired, then the `ContractReceiveSecretReveal` becomes a no-op.
=> Onchain secret registration handling when lock has expired

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/utils/transfer.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/initiator_manager.py
If a secret is revealed on-chain then all the world knows it, including
the next hop of the transfer, therefore the initiator doesn't need to
wait for the next hop to send a secret reveal message to confirm that it
knows the secret.
=> on-chain secret reveal is the same as off-chain

raiden/network/rpc/client.py, raiden/tests/integration/test_stress.py
the cache was introducing flakyness in the tests, this happened with
tests that are long running but don't send many transactions, which
makes the block gaslimit decrease significantly after the private
blockchain fixture setup is done
=> flaky stress test

raiden/storage/sqlite.py, raiden/tests/unit/test_wal.py
From the python3's sqlite3 docs:
> As required by the Python DB API Spec, the rowcount attribute “is -1 in
> case no executeXX() has been performed on the cursor or the rowcount of
> the last operation is not determinable by the interface”. This includes
> SELECT statements because we cannot determine the number of rows a query
> produced until all rows were fetched.
rowcount always returned -1, and the code to load the latest snapshot
assumed there was never a snapshot available, as a consequence all the
state changes where replaied on restarts
=> bugfix: rowcount doesn't work with select statements

docs/api_walkthrough.rst, docs/rest_api.rst
PR to reflect the smart contract limits added to Red Eyes in the docs too.
=> reflect red eyes limits in docs

docs/overview_and_guide.rst
The install instructions referred to a file called `contraints.txt`, but
the actual filename is `constraints.txt`.
=> Fix typo in developer install instructions

raiden/raiden_service.py
=> pylint: fixed warning for inherited _run

CONTRIBUTING.md
The previous guide:
- Used py2 instead of py3
- Forgot to mention matrix
- Told the user to use `sudo pip install`
- Didn't explain why the compiler was necessary
- Didn't had a description for Archlinux :disappointed:
=> updatd the contributing guide

raiden/network/rpc/client.py, raiden/network/rpc/middleware.py, raiden/settings.py
This will cache block infos to avoid downloading the blocks again and
again for the gas price strategies.
This is in addition to #2670 , to make sure we have up to date gas price estimates.
=> Implement a cache for the eth_getBlockByHash call

raiden/network/transport/matrix.py, raiden/tests/integration/test_integration_events.py, raiden/tests/unit/fixtures.py, raiden/tests/unit/test_node_queue.py, raiden/transfer/node.py
Fix #1611, although it'll still leave behind global-per-receiver queue, but that should be cleaned upon `Delivered` instead of `Processed` (i.e. as soon as the node is online), so it won't have an indefinite lifespan as the channel specific does currently.
Includes regression tests.
Proper fix requires the refactoring being done in #2537
=> Close the specific queue when a channel is closed

raiden/constants.py, raiden/encoding/messages.py, raiden/messages.py, raiden/network/transport/udp/udp_transport.py, raiden/tests/integration/test_service.py, raiden/tests/unit/test_binary_encoding.py, raiden/tests/unit/test_messages.py, raiden/utils/typing.py
Added protocol version to the Ping message
The protocol version handshake should be tied to the healthcheck in
order to avoid race conditions. Where a target is known to be online but
its protocol version is unknown.
Without the version in the Ping message the sender must assume the
lowest protocol version, otherwise a message unknown o the target could
be sent. Because the new message is not known to the target, it would
never be processed, and the message queue for that channel would stall.
Adding this field to the Ping message fixes the above problem. This is
being added now just to introduce the strategy of protocol handshake for
future releases.
=> Added protocol version to the Ping message

raiden/transfer/node.py
I know this may be considered "unpythonic" but frankly I prefer more readable code over purism.
I spent 2-3 mins (before coffee!) looking at the code being confused why the same function checks again if the list is `None` in two different parts of the code. The second check seemed unreachable until I realized the list is modified in place and the second check is a length check.
Made it a bit more explicit.
=> Explicit check for queue length in inplace_delete_message_queue

raiden/api/python.py, raiden/tests/integration/api/test_pythonapi.py
I don't catch it in the rest api since it's not even possible to do it there
Fix #2723
=> Providing a partner address without a token address is not allowed

raiden/raiden_service.py, raiden/tests/integration/test_integration_events.py, raiden/tests/integration/test_settlement.py, raiden/tests/utils/protocol.py, raiden/tests/utils/transfer.py
The pending_mediated_transfer utility was going around the RaidenService
api and injecting state changes directly in the write-ahead-log. This
approach does produce correct results in the state logic, but not in the
RaidenService, since the AsyncResults are not properly set.
This change removed the pending_mediated_transfer in favor of a special
event handler, which allows the tests to decide which secret requests
are sent. Having the same end effect of pending_mediated_transfer while
properly setting up the RaidenService state.
=> tests: removed pending_mediated_transfer

docs/changelog.rst, raiden/ui/app.py, raiden/ui/cli.py, raiden/ui/config.py, raiden/ui/runners.py
Resolves #2708 
Depends on #2715
=> Raiden --showconfig flag

raiden/exceptions.py, raiden/raiden_event_handler.py, raiden/raiden_service.py, raiden/tests/integration/test_settlement.py
This commit fixes two bugs:
- Previously a direct transfer was overwritting the async result for a
mediated transfer which led to crashes. The crash happened because 
when the first transfer was confirmed the async result was set and
cleared from the mapping, once the second transfer confirmed the mapping
was empty and the assertion was hit. The fix is to forbid conflicting
direct/mediated transfers.
- The async result mapping must be restored on restarts, the previous
logic was only resetting it for direct transfers and not mediated
transfers.
Fixes #2744 and fixes #2745
=> bugfix: conficting payments

docs/overview_and_guide.rst, raiden/ui/cli.py, raiden/utils/http.py
Currently a local `smoketest` fails without proper logging, if `synapse` wasn't installed.
This PR documents the need for running `tools/install_synapse.sh` for developers and adds proper checks for starting `synapse`.
=> Fix smoketest matrix support

raiden/connection_manager.py, raiden/network/proxies/token_network.py
This fixes a race condition in the connection manager, which was
harmless but produced unecessary errors in the logs. The race condition
happened when `retry_connect` and `join_channel` where called, resulting
in two deposit calls, but one of always failed.
=> bugfix: race condition in connection manager

raiden/raiden_service.py
Should fix the stress test failure.
If it's a mediated transfer the event is a `SendLockedTransfer` which contains the `payment_id` inside its `transfer` attribute.
This was introduced at https://github.com/raiden-network/raiden/pull/2743.
~~But what I don't understand is how come the tests there did not catch it.~~
Thinking about it, it’s flaky. The test shuts down the nodes and restarts them. They would not always have a `LockedTransfer` stuck at the queue every time they restart. Some times they would have already sent it so it would never go inside the `else` of `_initialize_queues`
=> Fix bug at _initialize_queues

raiden/app.py, raiden/message_handler.py, raiden/network/transport/matrix.py, raiden/network/transport/udp/udp_transport.py, raiden/raiden_service.py, raiden/tests/integration/test_recovery.py, raiden/tests/integration/test_send_queued_messages.py, raiden/tests/integration/test_settlement.py, raiden/tests/integration/test_stress.py, raiden/tests/utils/network.py, raiden/tests/utils/transfer.py, raiden/ui/app.py
Adding a class to provide late binding, the previous code relied on the
free standing functions from the message_handler module to handle
messages. Although this worked it didn't provide for a mechanism to
extend the message handling, which is desirable for testing (waiting for
a message to be received before proceeding).
Note: an alternative would to just use the module as an object instead
of introducing the class, this however makes extending the behavior a
bit more burdensome, since alternative implementations would have to
reimplement the dispatching code.
=> Added MessageHandler class

docs/changelog.rst, raiden/message_handler.py, raiden/raiden_service.py, raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/tests/utils/factories.py, raiden/transfer/channel.py
Should fix https://github.com/raiden-network/raiden/issues/2730
=> Ignore a transfer if lock's secrethash is already registered onchain

docs/changelog.rst, raiden/storage/sqlite.py, raiden/transfer/state.py
So that turned out to be quite a bug, much more foundational than I initially thought.
From initial debugging with @CosminNechifor  we saw that there was a mismatch in the internal network graph which is part of the `TokenNetworkGraphState`. However all tries to reproduce this failed, the correct state changes were written to the WAL and when replaying the WAL everything was right. 
However, we finally found that we could reproduce this when we started with a snapshot. From here on the problem was easy to track down.
It turns out that that there was a problem during deserialization which made multiple `TokenNetworkState` objects reference the same `TokenNetworkGraphState`. This only happened in really special constrains, so it’s not surprising that we haven’t found this earlier:
A …
=> Fix deserialization of similar token networks

raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/transfer/channel.py
It's already checked
[here](https://github.com/raiden-network/raiden/blob/06cc18240422b042d87d05029f5a429be166cb59/raiden/message_handler.py#L151).
Also removing the relevant unit test which does not really test anything anymore.
=> Remove invalid check for onchain secret registration

raiden/routing.py, raiden/tests/unit/test_tokennetwork.py
Adding nonrefundable property to get_best_routes results ordering. This is applied as a tiebreaker, favoring refund routes over non-refund routes only if they have the same length. A more thoughtful trade off between number of hops, fees and refunding  should be made in the PFS. 
closes #2682
=> Prioritize routes which have funds for refunds

raiden/raiden_service.py
- During start Raiden uses the latest block number (as seen by the
node's Ethereum node) to initialize the node's state, this value
is dispatched and made recoverable by the WAL with the ActionInitChain
state change.
- Then all events are polled starting from block 0 until the current
block number, updating the node's view of the blockchain.
- Assuming the node crashes during polling. On restart it will use the
block number set by ActionInitChain instead of 0, which is up the latest
block number, effectively missing events not processed after the crash.
This also fixes the value 0, which should not be used. The correct value is
the block height at which the token network registry was deployed, which
is available in the RaidenService.query_start_block
=> bugfix: InitChain must use deployed blocknumber

docs/changelog.rst, raiden/transfer/state.py
This class was missing the `lockhash` attribute in order to be used like
any other lock state object.
Fixes #2794
=> Fix UnlockPartialProofState lockhash attribute

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/transfer/mediated_transfer/mediator.py
The arguments of message identifier and payment identifier were mixed up. I fixed the order and use named keyword arguments.
=> Change argument order and add regression test

raiden/tests/integration/test_stress.py
the stress test is a bit flaky in travis because of the 120 timeout limit
https://gist.github.com/hackaugusto/045edec9232bb590e44bebe12735815b#file-gistfile1-txt-L1814
=> stress test remove operation timeouts

raiden/tests/unit/test_channelstate.py, raiden/transfer/state.py
This is a fix for #2828 -- UnlockPartialProofState copies all lock
specific (as in `HashTimeLockState`) fields into its own slots, in order
to avoid `AttributeError` when being accessed in a lock context.
=> Let UnlockPartialProofState expose its Lock-ieness

raiden/utils/__init__.py
This is only temporary so that testing in Rinkeby and Kovan can go on until new
contracts are re-deployed there.
=> Temporarily skip version check

tools/scenario-player/example-scenarios/scenario-example-v2.yaml, tools/scenario-player/scenario_player/main.py, tools/scenario-player/scenario_player/node_support.py, tools/scenario-player/scenario_player/runner.py, tools/scenario-player/scenario_player/tasks/channels.py, tools/scenario-player/scenario_player/utils.py
Some improvements that collected over the last week.
- Add `settle_timeout` parameter to `open_channel`
- Use random ports for the raiden nodes to allow running multiple scenarios in parallel
- Add `reclaim-eth` CLI subcommand to reclaim eth of no longer used scenarios
Usage of `reclaim-eth`:
It will reclaim eth for the given `--chain`s from all node accounts that haven't been used to run scenarios in the last `--min-age` hours.
The eth will be transferred into the account of the given `--keystore-file`.
Example:
```
python -m scenario_player \
--keystore-file <...> \
--password <...> \
--chain kovan:<...> \
--chain rinkeby:<...> \
[--chain <...>:<...>] \
- \
reclaim-eth \
--min-age <hours>
```
(The dash before `reclaim-eth` is required as a placeholder for the not used scenario file …
=> Some SP improvements

raiden/network/proxies/token.py, tools/transfer_eth.py
If we take a look in the JSONRPCClient we can see that the
sender attribute became [address](https://github.com/raiden-network/raiden/blob/master/raiden/network/rpc/client.py#L172), and this was not changed on this
[transfer_eth.py](https://github.com/raiden-network/raiden/blob/master/tools/transfer_eth.py#L33) from tools.
=> Fixed a attribute that was renamed

docs/changelog.rst, raiden/constants.py, raiden/raiden_service.py, raiden/ui/app.py, raiden/ui/cli.py
- As discussed, `--network-type main|test` will be changed to `--environment production|development`
- If we are on the mainnet, the `--environment` option will be overriden and set to `production`. We used to check for that and abort if the setting was wrong, but it is awkward to always have to specify both options to run on mainnet.
- also adds some missing type annotations in raiden_service.py (unrelated)
Fixes #2752
=> Rename --network-type cli option

tools/scenario-player/scenario_player/node_support.py, tools/scenario-player/scenario_player/runner.py
The `--network-type` option name was changed to `--environment-type`
but there is this place where we forgot to change it.
=> Fixed a param option

raiden/tests/integration/contracts/fixtures/contracts.py, raiden/tests/integration/contracts/test_network_registry.py, raiden/tests/integration/contracts/test_token_network_registry.py, raiden/tests/utils/smartcontracts.py, raiden/tests/utils/smoketest.py
pytest was giving a warning that the `deploytoken()` fixture was being called directly and that this should be avoided.
- Ended up removing it as it was never really used as a fixture and turned it into a utility test function.
- Also gave proper name to a file testing the token network registry contract
=> Fix pytestwarning for deploytoken dontcall fixture

raiden/network/proxies/discovery.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py, raiden/network/proxies/utils.py, raiden/ui/app.py, raiden/utils/__init__.py
As seen by a user in [gitter](https://gitter.im/raiden-network/raiden?at=5bcb2de1ab17df2631c0fa6e), if a contract version mismatch is encountered we currently do not get any useful error describing expected/found version.
This PR addresses that by making sure that if there is a version mismatch the expected/deployed versions are included in the error.
=> Report problematic versions at contract version mismatch

docs/overview_and_guide.rst
- Remove the warning from python 2 migration
- Fix a small formatting error
- Mention mainnet/testnets for infura as well
=> Small docs improvements [skip ci]

raiden/tests/integration/cli/test_cli.py, raiden/ui/app.py, raiden/ui/cli.py, raiden/utils/cli.py
- Fixes a tiny bug in recognition of the environment type CLI argument.
- Makes production the default environment type
- Adds CLI tests to check that the `--environment-type` argument changes the expected readout of the client at startup.
=> Properly recognize environment type from cli

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py, raiden/tests/utils/factories.py, raiden/transfer/mediated_transfer/mediator.py
The mediator task definition of finalized was wrong. The task was
considered final the lock expired, which happens once the corresponding
block was mined.
The consequence is that during a run where the lock expired, the
mediator would send the remove expire lock message, and set the status
of the task as finalized, leading the task to be cleared. The problem is
that the mediator task is also responsible to handle the remove expired
lock messages, and if is clered these messages are not handled, leading
to synchronization problems among the participants.
=> bugfix: Mediator task must wait for expired lock

raiden/transfer/mediated_transfer/target.py
When the lock has expired the message is None, appending it to the event
will result in the string `lock expired None`.
=> Fixed log message

.travis/prepare_os_osx.sh
Brew recently updated node to v11.
Apparently there aren't pre-built binaries of some packages
(`fsevents` was the one that came up) for node v11 yet. This
causes our compile_webui task to try building those from source which
requires node-gyp which in turn requires Python 2 which isn't available
on our macOS environment.
Fixes #2907
[ci nightly]
=> Force node to v10 on macOS builds

raiden/tests/fixtures/variables.py
Only in Travis test_batch_unlock failed some times flakily with the following [logs](https://gist.github.com/LefterisJP/61827579badbc759a6e25bea28a70f6c).
What happens is that the attempted transfer:
```
[<HashTimeLockState amount:10 expiration:55 secrethash:88b432dc>]
0x88b432dc032ca2fdcc6b98a9bc0cb539f68f40971523e5698aa2f5fc28804097
```
has a lock expiration of `55`.
But according to the logs:
```
2018-10-26 23:05:21 [debug    ] Received new block             [raiden.tasks] block_hash=0x875b1450d0ca06114aafaba0f3f85a90a874ad5133ad58d8b28cf9bee33a5681 gas_limit=9492431 number=55
2018-10-26 23:05:21 [debug    ] State change                   [raiden.raiden_service] node=03ced6e8 state_change={"block_number": 50, "gas_limit": 9538911, "block_hash": …
```
=> Fix flaky test_batch_unlock

raiden/ui/runners.py
This adds logging of the system spec during startup to help with interpreting logs.
=> Log system spec on startup

docs/overview_and_guide.rst, raiden/network/rpc/client.py, raiden/tests/utils/geth.py, raiden/ui/cli.py
Using the txpool api to get the used nonces because getTransactionCount does not include the transactions from the pool.
=> Fix underpriced transaction

raiden/storage/sqlite.py, raiden/storage/utils.py, raiden/storage/wal.py, raiden/tests/unit/test_wal.py
This could become useful when debugging state changes in certain time ranges.
=> Add log_time to state changes

raiden/tasks.py
Fixes #2946 
I think the whole block info doesn't help with anything.
We might also want to lower this to debug level.
=> Don't show full block info in info message.

raiden/raiden_service.py
In order to have consistent logs with all the state changes dispatched
for a given node, the ActionInitChain should also go through the
handle_state_change method.
=> ActionInitChain dispatch through handle_state_change

raiden/log_config.py
=> Use JSON as a default logging format

raiden/transfer/node.py, raiden/transfer/token_network.py
Small improvement for #2968 , as pointed out by @LefterisJP in the review.
=> Fix shortened variable names

raiden/blockchain/events.py, raiden/blockchain_events_handler.py, raiden/exceptions.py, raiden/network/proxies/token_network.py, raiden/tests/integration/contracts/test_token_network.py
As of https://github.com/raiden-network/raiden/pull/2623#pullrequestreview-172123905 we decided to move the withdraw related code for now.
This commit can be reverted once work on issue #1498 in continued.
=> Remove code related to channel withdraw

raiden/raiden_service.py, raiden/tasks.py, raiden/tests/utils/network.py
The race happened under this circunstance:
- A node learns about a new block, updates its state, then crashes
- On restart, the block number is recovered, the filters are
installed with the latest known block.
- The race: The node finishes the above before a new block is mined
- The bug: The filter is polled during start of the RaidenService, by
calling the AlarmTask.first_run, which always executes the
callbacks, eventually using the StateFilter's to poll for new events
from a block in the future.
The fix was to give the latest known block number to the alarm task in
the as an argument for first_run, and only execute the callbacks if
there is a new block.
fixes #2838
=> Fix race condition with new blocks and filters

raiden/network/transport/matrix.py
Fixes #2981 
I didn't find a nice way to generically convert keys to strings during serialization, so I think this is the best solution. 
There is a way like described in https://stackoverflow.com/a/28079487 , but this would come with a performance penalty for all log invocations.
=> Convert QueueId keys to string before logging

raiden/network/transport/matrix.py, raiden/network/transport/udp/udp_transport.py, raiden/raiden_service.py, raiden/tests/fixtures/variables.py, raiden/tests/integration/conftest.py
Previously, we spawned a greenlet to retry each message, and kept retrying them blindly every timeout, skipping if the user was offline but despite events such as the user coming online, until the event with same `message_identifier` was cleaned from the respective `queueids_to_queue` queue.
This PR changes that to one `Runnable` per **receiver** (as, with matrix, the messages for any channel goes in the same room), and use a notification system on the loop, to allow bursts of messages to be batched (going on the body of a single Matrix's `send_text`/HTTP request, and as well being fetched on the same `/sync` response), relying then on the natural ordering of the messages on the receiver to process them in-order as well, or (if any fails) be retried if not cleared on next notify/retry …
=> Matrix per-receiver retry message queue

raiden/network/rpc/smartcontract_proxy.py
Triggered by https://github.com/raiden-network/raiden/issues/2984
- We now recognize when parity's estimate gas tells us the transaction will always fail
- Fixed a bug where we were not detecting the `TRANSACTION_UNDERPRICED` case for parity
=> Handle transaction execution error for parity

docs/changelog.rst, raiden/ui/web/src/app/components/token-input/token-input.component.css, raiden/ui/web/src/app/components/token-input/token-input.component.html, raiden/ui/web/src/app/components/token-network/token-network.component.ts
* Increased the height of the for container so that the second line of the hint doesn't have to overflow.
Closes #2963
=> Fix join dialog overflow

docs/changelog.rst, raiden/api/python.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/integration/api/test_restapi.py, raiden/tests/integration/test_pythonapi.py, raiden/tests/utils/client.py, raiden/utils/gas_reserve.py
This PR also:
- Reduces the time between gas_reserve checks to 5 mins
- Fixes a bug in the GAS_REQUIRED_FOR_CHANNEL_LIFECYCLE_COMPLETE
constant
Fixes #2923
=> Fix gas_reserve to take in-progress channel openings in account

raiden/transfer/node.py, raiden/transfer/views.py
Fix #2991
There is no state [transition](https://github.com/raiden-network/raiden/blob/761bedfee2ee326401ad5ec95d55b1ab458a5213/raiden/transfer/token_network.py#L338) that can lead to a `None` new state for the token network state machine.
With that in mind I removed the part of the `handle_token_network_action()` which does that and deletes a token network from the payment network state.
Incidentally this was also the only place `search_payment_network_by_token_network_id` was used so I also deleted that function. As pointed out in #2991 the function is wrong.
There is another function which does the same thing and does it correctly. It's [get_token_network_registry_by_token_network_identifier()](https://github.com/raiden-network/raiden/blob/761bedfee2ee326401ad5ec95d55b1ab458a5213/raiden …
=> Remove unused state machine code and view function

raiden/raiden_event_handler.py, raiden/storage/restore.py, raiden/storage/sqlite.py, raiden/storage/wal.py, raiden/transfer/views.py
The function `get_snapshot_closest_to_state_change` always returns a
tuple, which may be `(None, 0)`. In the previous code this return value
would be check for truthiness, which even though the values in the tuple
evaluate to False, the tuple itself evaluate to True because it has
elements. The end result was just improper logging.
This also improves the logging and adds assertions to easy debugging.
These are the changes I used to figure out part of https://github.com/raiden-network/raiden/issues/2931
=> Fix restore_to_state_change logging

docs/overview_and_guide.rst
`--fast` was just a shortcut for `--syncmode fast` and was removed in geth 1.8.15.
=> docs: geth --fast is now called "--syncmode fast"

raiden/log_config.py, raiden/ui/cli.py
This is avoided by not configuring the log handler in that case. I
applied the same approach for the other handlers for consistency.
The --disable-debug-logfile flag also was not passed to
configure_logging when calling `raiden smoketest`, so I added it there.
=> Don't create logfile when --disable-debug-logfile (fixes #3003)

docs/changelog.rst, raiden/storage/sqlite.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/state.py
Deleting the payment task will lead to problems when unlocking locks related to the task.
@hackaugusto Can you have a look and see if this goes in the right direction? I'll work on a test in the meantime.
Fixes #3001
=> Don't delete payment task when receiving invalid secret request

raiden/app.py, raiden/storage/versions.py, raiden/ui/runners.py
When a database version upgrade happens, the user must take action and
exit all the token networks and rename the existing database file. This
should not happen often, as the database format is choosen to be
upgradable, but to avoid problems with testing realeases and possible
future breaking changes a check was added.
This should help to prevent problems like #2931
Edit: This does **not** prevent #2931 , it's another problem.
=> Forbid invalid upgrades

tools/scenario-player/scenario_player/node_support.py, tools/scenario-player/scenario_player/runner.py, tools/scenario-player/scenario_player/tasks/base.py, tools/scenario-player/scenario_player/tasks/channels.py, tools/scenario-player/scenario_player/utils.py
Fix breakage introduced by the changed `send_transaction()` signature. 
Also includes some other small improvements:
- Hide rest api `GET`, `POST` etc. log lines in managed Raiden node logs
- Allow scenarios to specify payment identifiers or to autogenerate deterministic ones.
=> [SP] Fix send_transaction gaslimit argument

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/utils/factories.py
Note however that this gives no guarantee on the correctness or
availability of the data, meaning it's perfectly fine for the factory to
fail because the constructed objet would be inconsistent, or for the
test to fail if the values are inconsistent.
This is a big change in respect to the previous approach, which tried to
do exactly the opposite, and force the test writer to choose appropriate
values, however this is a step torwards making it possible to use value
generation (because of the type annotations and name consolidation).
This also introduces a new object named EMPTY, since `None` may be a
valid value in some cases.
=> Test: Factories with most arguments optional

docs/changelog.rst, raiden/message_handler.py, raiden/network/proxies/token_network.py, raiden/raiden_event_handler.py, raiden/storage/sqlite.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_sqlite.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/tests/utils/factories.py, raiden/tests/utils/transfer.py, raiden/transfer/architecture.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/events.py, raiden/transfer/mediated_transfer/state_change.py, raiden/transfer/state.py, raiden/transfer/state_change.py, raiden/transfer/utils.py
The shape of messages which balance proofs changes depending if it
contains a lock or not. Messages like Unlock, LockExpired and
DirectTransfer have a balance proof directly in the object itself, while
messages like LockedTransfer and RefundTransfer have their balance proof
inside a transfer object, which also contains the lock.
This difference in the shape of the objects would also require different
queries to the database. In order to not have such queries, the
serialization of the objects duplicates information, and copies the
balance proofs from the inner transfer object to the top level, allowing
a single query to work with all the above messages and their state
changes counter part.
However, such strategy is error prone, and we indeed forgot to properly
serialize two state changes, …
=> Fix Refund transfer serialization

raiden/storage/sqlite.py, raiden/storage/utils.py, raiden/tests/unit/test_sqlitestorage.py, raiden/tests/unit/test_wal.py
This help reproducing problems related to upgrades and debugging in
general (closes #3006).
Adding detect_types=sqlite3.PARSE_DECLTYPES to sqlite3.connect might
affect other parts of the code, but makes using timestamp columns more
pleasant. The unit tests run fine and failures should be obvious, so I
don't think it brakes anything.
I'm not sure where to put the test, see https://github.com/raiden-network/raiden/issues/3006#issuecomment-438962908 .
=> Save time and version in sqlite on startup

docs/changelog.rst, raiden/network/transport/udp/udp_transport.py, raiden/storage/sqlite.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/events.py, raiden/transfer/mediated_transfer/state.py, raiden/transfer/mediated_transfer/state_change.py, raiden/transfer/state.py, raiden/transfer/state_change.py, raiden/transfer/utils.py, raiden/utils/typing.py
Fixes #3013 
Right now I explicitly convert IDs from channels and payments as well as absolute block numbers and token amounts as well as the message id.
Not converted are currently:
- chain id
- gas limit
=> Serialize integers for sqlite

raiden/transfer/mediated_transfer/state.py, raiden/transfer/state.py, raiden/utils/typing.py
As part of #3040, I saw an error from mypy, saying
```
raiden/utils/typing.py:89: error: String argument 1 'TokenAddres' to NewType(...) does not match variable name 'TokenAddress'
```
So I added a missing `s`.
Then I saw four new errors from mypy.  I fixed all new errors in this PR.
=> Fix TokenAddres into TokenAddress

raiden/ui/runners.py, raiden/utils/__init__.py
In the past if a user simply does
`pip install -c constraints.txt --upgrade -r requirements-dev.txt`
without a `python setup.py`
then a `None` version is returned. This is an incorrect usage of the
software so we should enforce it.
=> Enforce proper development setup

raiden/transfer/mediated_transfer/events.py
The class is called `EventUnexpectedSecretReveal`, so the string
representation should match, as well as the return type of the
alternative constructor `from_dict`.
=> Fix inconsistent class name usage

raiden/utils/__init__.py
Before this commit, `mypy raiden/transfer/mediated_transfer/target.py
--ignore-missing-imports` returned error messages:
```
raiden/utils/__init__.py:46: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"
raiden/utils/__init__.py:52: error: Item "None" of "Optional[Match[str]]" has no attribute "groups"
```
This commit removes these errors.
This change is one step for
https://github.com/raiden-network/raiden/issues/3040.
=> Remove mypy errors: re.search() might return None

raiden/storage/sqlite.py
This commit removes error messages from
`mypy raiden/transfer/mediated_transfer/target.py --ignore-missing-imports`
namely,
```
> raiden/storage/sqlite.py:226: error: Argument "event_identifier" to "EventRecord" has incompatible type "int"; expected "ChannelID"
> raiden/storage/sqlite.py:273: error: Argument "state_change_identifier" to "StateChangeRecord" has incompatible type "int"; expected "ChannelID"
```
=> Remove ChannelID type annotation on some other IDs

docs/changelog.rst, raiden/exceptions.py, raiden/messages.py, raiden/network/proxies/token_network.py, raiden/network/transport/matrix.py, raiden/raiden_event_handler.py, raiden/tests/integration/contracts/test_payment_channel.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/unit/test_binary_encoding.py, raiden/tests/utils/factories.py, raiden/transfer/balance_proof.py, raiden/transfer/channel.py, raiden/utils/__init__.py, raiden/utils/signing.py, tools/gas_cost_measures.py
Should fix #3054 
- Moves the signing code from raiden libs to the client as discussed in our talks of moving stuff out of raiden libs. Will also make a PR to the libs to deprecate the calls.
- When trying to process a signature to recover sender address we now reject all `v` values not in `(0, 1, 27. 28)` to be in sync with the [contracts implementation](https://github.com/raiden-network/raiden-contracts/blob/aea36ce403605670edc23fe0d14cf422e2b8e69b/raiden_contracts/contracts/lib/ECVerify.sol#L27).
- Tests for the above.
=> Reject any signatures with v not in (0, 1, 27, 28)

.travis.yml, .travis/coverage.sh, .travis/install.sh, .travis/run.sh
This enables `coverage` and `coveralls` reporting on every nightly cron build in travis.
I chose to export a conditional `env` variable `RUN_COVERAGE` in the ~`before_install`~ `env.GLOBAL` stage. This allows for a streamlined conditional checking in all affected later stages/scripts.
This fixes #3020
=> Nightly coveralls

docs/onboarding.rst
It took some questions and answers for me to figure out how the messages
are encoded (https://github.com/raiden-network/spec/issues/133 ).
This commit adds what I learned in the FAQ, namely, how to figure out
the format of a message.
=> Adding messsage encoding to onboarding FAQ

.circleci/config.yml, docs/onboarding.rst
Workflow got changed so that all integration tests are running under one job resulting in 4 integration jobs(2 py versions X 2 transport medium)
=> Circle CI composed all integration tests into a single job

docs/changelog.rst, raiden/constants.py, raiden/raiden_service.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/transfer/channel.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/utils.py, raiden/utils/__init__.py
=> Client will no longer accept 0x0 as secret or keccak(0x0) as secrethash

constraints.txt, docs/changelog.rst, raiden/network/transport/matrix.py, raiden/network/transport/udp/udp_transport.py, raiden/raiden_service.py, raiden/storage/sqlite.py, raiden/tests/integration/test_matrix_transport.py, raiden/tests/utils/transport.py, raiden/transfer/node.py, raiden/transfer/state.py, raiden/transfer/state_change.py
The current issue we're facing related to the "Nonce did not sequentially change" is the fact that upon restart, the node performs a login operation with the matrix server with a default value of `sync=True` and `sync_filter_limit=10`.
The above means that upon login, we will call the sync endpoint of the matrix API with a maximum number of messages to fetch set to 10. However, this was apparently an issue when we noticed that while a node is shutting down, some messages might have already been sent to the matrix server but have not been delivered to the shutting down node. As soon as this node comes back up, it will request a maximum of 10 messages which is what causes it sometimes to not receive important messages (nonce-updating kind of messages).
The solution is to basically prevent …
=> Nonce did not change sequentially

.travis.yml
Running with `coverage` leads to frequent timeouts in the `long_running`
integration tests. In scope of the nightly coverage runs #3020 I now
selectively disable `coverage` for the two long running tests we have.
The goal is, to have any coverage results before switching CI platforms,
even if this will now underestimate our coverage (due to the two test
sets not being "covered").
=> Disable coverage on long running integration tests

docs/changelog.rst, raiden/network/transport/matrix.py, raiden/tests/integration/test_matrix_transport.py, raiden/tests/utils/transport.py
Issue #3103 was created as a follow up to issue #3046 because we assumed that as soon as the receiver node came back online, the sending node would trigger the retry mechanism and resend the messages which were not responded to.
The discovered issue was in the following line:
https://github.com/raiden-network/raiden/blob/85652fc89e35b9f47e950b5753bd4bcc05cd201c/raiden/network/transport/matrix.py#L224-L228
Where `msg_data` is an instance of `_MessageData` inner class of the `_RetryQueue`. And according to the declarations, `message_identifier` is never a member of the `_MessageData` class which triggered the line on 228 to remove the message. This meant that messages were never retried because of this bug.
- The if statement should simply check for the existence of `message_identifier` in …
=> Fix Matrix Transport retry mechanism

Makefile, raiden/transfer/channel.py, raiden/transfer/mediated_transfer/target.py, raiden/utils/__init__.py
This PR is a part of #3040, and also a preparation for #3051 .
#3040 is about removing mypy errors in `target.py`.  This PR does that for the `Address` type.
#3051 is about a better type system.  Before introducing the change, I wanted to clean up the existing error messages around the `Address` type.
=> Detect and fix mypy errors about Address type

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py, raiden/tests/utils/factories.py, raiden/transfer/mediated_transfer/mediator.py
The mediator will accept `SecretReveal` messages after having expired the transfer's lock. Which means that claiming the locked amount will always fail and therefore will cause emitting `EventUnlockClaimFailed`.
Check if the payer transfer's lock has expired before accepting `SecretReveal` messages.
Resolves #3086
=> Reject secret reveal

.travis.yml, docker/build.Dockerfile
macOS binary generation failed due to leftover line that used to compile the webui.
=> Remove compile_webui from travis configuration

requirements-dev.txt, tools/debugging/json-log-to-html.py
This is a helper script that formats (and optionally filters) json debug log files into human readable HTML.
Additionally it colorises the structlog key-value pairs according to their hash, which greatly helps spot small differences in values.
Example output:
=> [debug tool] Add json log to html formatting helper tool

tox.ini
Before this commit, `tox` gave an error message about a missing directory `raiden/tests/smart_contracts`. This directory existed in the past but not anymore.
After this commit `tox` seems to work for me.
=> Remove raiden/tests/smart_contracts from tox.ini

constraints.txt, docs/changelog.rst, raiden/log_config.py, raiden/network/proxies/token_network.py, raiden/network/transport/matrix.py, raiden/tests/integration/test_matrix_transport.py
Fixes #2779
Fixes #3113
Requires raiden-network/raiden-libs#149
This contains two new `# TODO` comments one of which is about the dead code in `_leave_unused_rooms`.
Both need to be investigated after this is merged.
=> Fix hanging transfers

docs/changelog.rst, raiden/api/python.py, raiden/network/proxies/token_network.py, raiden/tests/integration/cli/conftest.py, raiden/tests/integration/test_pythonapi.py, raiden/tests/utils/smoketest.py, raiden/ui/app.py, raiden/ui/cli.py
In development mode we unfortunately seem to still have limits as we can see from the code
[here](https://github.com/raiden-network/raiden-contracts/blob/7105cf818fc290107ad48df9497bddcdec5c540e/raiden_contracts/contracts/TokenNetwork.sol) of what is probably the pre_limits contracts.
The fix for now, is to also take that limit into account at development mode and not allow the client to send a transaction when the token amount is above the limit that development mode contracts have.
Fix #3135
=> Fix "Deposit amount decreased" crash in development mode

Makefile, raiden/api/python.py, raiden/blockchain/events.py, raiden/network/proxies/payment_channel.py, raiden/transfer/views.py, raiden/utils/__init__.py, raiden/waiting.py
This PR puts `raiden/api` and `raiden/transfer` under mypy checks.  The focus is still on `Address` related errors https://github.com/raiden-network/raiden/issues/3120.
When I solve all `Address` related mypy errors, the integration of the new type system https://github.com/raiden-network/raiden/issues/3051 will be much easier.
=> Put raiden/api and raiden/transfer under mypy checks

tools/scenario-player/example-scenarios/scenario-example-v2.yaml, tools/scenario-player/scenario_player/main.py, tools/scenario-player/scenario_player/node_support.py, tools/scenario-player/scenario_player/tasks/base.py, tools/scenario-player/scenario_player/tasks/raiden_api.py, tools/scenario-player/scenario_player/tasks/raiden_node.py
Useful features I needed while debugging the hanging transfers:
- Add `timeout` parameter to Raiden API tasks
- Add a `update_node_options` tasks to update node start options during a running scenario
=> Update scenario player

raiden/tests/unit/test_channelstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py, raiden/tests/utils/factories.py
- refactoring of new factories using property classes
- refactoring of all tests using the `make_transfers_pair` fixture
=> New factories for unit tests part 2

docs/changelog.rst, raiden/api/rest.py, raiden/tests/integration/api/test_restapi.py
We are actually properly catching the `AddressWithoutCode` exception thrown out
of the `open_channel()` function but there was an instance before the
actual opening where a `Token()` object is instantiated and throws
that same exception which is left unhandled and crashes the client.
Fix #3153
=>  If Rest API open() gets non-contract address don't crash the client

Makefile, raiden/blockchain/events.py, raiden/blockchain_events_handler.py, raiden/message_handler.py, raiden/network/blockchain_service.py, raiden/network/proxies/token_network.py, raiden/network/transport/matrix.py, raiden/network/transport/udp/udp_utils.py, raiden/raiden_service.py, raiden/routing.py, raiden/tests/integration/contracts/fixtures/contracts.py, raiden/tests/integration/contracts/test_payment_channel.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/integration/test_balance_proof_check.py, raiden/utils/filters.py, raiden/utils/typing.py
Four new directories are covered by mypy checks.
The most significant change is the introduction of a new type
``UDPMessageID`` for udp_utils.py.  This was necessary because
``MessagerID`` was used for very different two types (one was ``int``
but the other was a tuple).
Besides, some type annotations were adjusted as usual.
=> Mypy on blockchain, encoding, storage, network

.circleci/config.yml
CircleCI parallelism was decreased to 1 on f34ab26bd5dbd4989dffdb1a134c909ee1e5c0b6 to avoid hitting the limit of 4 on the smaller plan and allow all 4 sets of integration tests running together, but it pushed the time required to run a single set of tests to more than 1 hour, which made it timeout and not complete successfuly even if no test errored.
This PR increase it to 2, to decrease the time of running a single set of test to less than 1hr, but preventing all 4 sets of tests of running parallely, running 2 then 2 at a time.
=> Fix CircleCI timeout with parallelism=1 by increasing to 2

docs/changelog.rst, raiden/tests/unit/test_sqlite.py, raiden/tests/unit/transfer/mediated_transfer/test_events.py, raiden/transfer/mediated_transfer/events.py
Properly process a `SendRefundTransfer` event if it's the last one with a related balance proof before settlement and not crash the client.
Fix #3179
=>  SendRefundTransfer should have a balance_proof attribute

raiden/network/transport/matrix.py, raiden/tests/integration/test_matrix_transport.py
`_join_discovery_room` raised an exception if we tried to `join_room` on a foreign server which couldn't be contacted by our current transport server.
This PR adds a test for that, and handles the returned E500, moving on and eventually creating a discovery room on our current server if none could be found (usually happens only on private chains, as discovery rooms for all known test and main blockchains are already present on all servers).
Fixes #3171 and #3081
=> Matrix: handle E500 on join_room

docs/changelog.rst, raiden/tests/integration/transfer/test_refundtransfer.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/utils/events.py, raiden/tests/utils/protocol.py, raiden/transfer/channel.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/initiator_manager.py
- If the initiator has the lock with the transfer's secrethash also pending in the partner state (iow had a refund transfer) then don't remove the payment task at the lock expiration block but wait for a lock expire message to unlock the lock and then be free to remove it in the next block.
- As an initiator handle LockExpired messages. Your partner may send
you one if you sent him a locked transfer, he had no capacity and
sent you a refund transfer back.
Fix #3183
=> If initiator had a refund transfer dont remove payment task at lock expiration block

docs/changelog.rst, raiden/api/v1/encoding.py
Use the `get_distributable()` instead of `get_balance()` channel
functions for the balance shown to the user.
Fix #3193
=>  Channel balance returned by API takes locked amount into account 

docs/changelog.rst, raiden/raiden_event_handler.py, raiden/storage/sqlite.py, raiden/tests/integration/transfer/test_refundtransfer.py, raiden/transfer/mediated_transfer/initiator_manager.py, raiden/transfer/utils.py
Fixes #3196 
This PR fixes the issue mentioned above by doing the following in the case the node is trying to unlock:
If the partner has locked amounts, then we search for the the balance hash in the state_changes table (which we already did before), but in case it doesn't find it, it searches events so that we find the event at which the partner's balance hash was updated due to a new balance proof we sent.
If the partner has no locked amounts but our side of the channel does, then we look for events (which we already did before) but in case it doesn't find it, it searches for state changes.
We tried the fix on a test-case that crashed the lock previously on mainnet and we confirm that the fix works and the following transactions on-chain were able to restore the locked amounts for both …
=> Unlock using state change or event

docs/changelog.rst, raiden/network/rpc/client.py
Handle https://github.com/raiden-network/raiden/issues/3201 issue for Infura by essentially reverting back to `eth_gasPrice` RPC call whenever Infura + web3 cause the attribute error.
This is just a workaround that can be made on our side. The real fix should be done either upstream in web3 or Infura.
=> Workaround for Infura and gas price strategy issue

tools/debugging/replay_wal.py
This adds a new option flag `-x --names-translator`. If it points to a
json file, it will translate all keys (ignore case) with the values when
printing attributes.
E.g.:
-x names.json
```
cat names.json
{
"0xb4f44cd22a84DE0774B802e422D4c26A73Dd68d7": "initiator",
"0x7f9902e21747AC5DABbd9Ba50E96F3b1f58Ae639": "mediator",
"0x4B2F10eC7edc602915CE7db3547fc3352B09401C": "target",
"0x0Ea30825657A15a8460bc025AA0608AB3405d585": "RTT"
}
```
will lead to output like this:
```
> ActionChangeNodeNetworkState
node_address='[initiator]'
network_state='reachable'
```
Furthermore, it allows to use the names for the `-n` and `-p` switches:
```
replay_wal.py -x names.json -p mediator -n RTT db-file
```
=> Add translator to WAL replay tool

docs/changelog.rst, raiden/network/rpc/client.py, raiden/network/rpc/smartcontract_proxy.py
Fix #3211 for parity.
What we do is:
1. When we get the transaction already imported error we get all the
pending transactions from the pool via `parity_allTransactions`.
2. Search these transactions for one originating from our node and
with the expected nonce.
3. i. If the transaction is found we get the hash and proceed as usual
with polling it.
ii. If it's not found we handle this as the geth
`TransactionAlreadyPending` error and crash raiden.
3-ii can only happen if the transaction gets out of the pool between
the time we get the already imported error and the time we query it.
The only reason that 3-ii does not handle the situation gracefully is
because at that point there will be no way to get the transaction hash.
The raiden client needs a transaction hash for blockchain …
=>  Handle the Parity Transaction already imported error 

raiden/transfer/views.py
I found this function was never used. I was removing some mypy errors for #3040.
=> Remove unused get_channelstate_for_receiving()

docs/index.rst, docs/state_machines.rst, raiden/transfer/state.py
This commit adds a file that describes state machines.  As a start, I tried to describe the ``HashTimeLockState``.
This is the first bite on https://github.com/raiden-network/raiden/issues/3160
=> Start describing the state machines

docs/changelog.rst, raiden/network/proxies/token_network.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/integration/transfer/test_refundtransfer.py
Fix #3217 Fix #3216 
This PR does the following:
- Finishes the test left skipped after PR #3197. This tests all the other bullet points.
- During testing we `stop()` and `start()` raiden again. This will also
stop and start the alarm task. After the initial stop of the alarm
task the `stop_event` was never set to False again so it never ran
after a restart.  Fixed by https://github.com/raiden-network/raiden/commit/4bb56d2de98d9b53c5bee74af85f3c21d19e4254
This may be a cause for other failing integration/stress tests that deal with node restarts.
-  (#3217) If when we are handling `ContractSendChannelUpdateTransfer` we see
that the onchain state has already been updated with the nonce we were
about to send then don't send the transaction. Also if
updateNonClossingBalanceProof throws and …
=> Finish test_different_view_of_last_bp_during_unlock and address related issues

docs/changelog.rst, raiden/raiden_event_handler.py, raiden/raiden_service.py
Also remove unnecessary assert.
Fixes a race condition of using the same payment identifier and the
first transfer succeeding while the second one is just beginning.
For more details check: #3121 (comment)
Fix #3121
=>  Protect targets_to_identifiers_to_statuses with a lock 

.bumpversion_client.cfg, docs/conf.py, setup.py
Just doing `bump2version --config-file .bumpversion_client.cfg --new-version 0.100.2-rc1 patch ` did not work. I manually changed 2/3 occurrences. Would have to either try some more customization + hacks as per the discussion [here](https://github.com/peritus/bumpversion/issues/128) or just use another tool.
=> Bump version: 0.100.1 → 0.100.2-rc1

raiden/raiden_service.py, raiden/tasks.py, raiden/tests/integration/transfer/test_refundtransfer.py
Proper fix for #3216.
Check [this](https://github.com/raiden-network/raiden/issues/3216#issuecomment-451548798) and [this](https://github.com/raiden-network/raiden/issues/3216#issuecomment-451595735) comments for context.
The issue where the alarm task's events may cause blockchain transactions to be sent twice was [fixed](https://github.com/raiden-network/raiden/pull/3218/commits/59c2ae665542e836ce06c8319be2334d62a43d3c) for the test where I first noticed the problem but the fix was not covering all potential edge cases. This PR makes sure that the alarm task's first run does not generate any events which should fix all cases of the problem seen in #3216.
Also adds a check for the situation described in the discussion in #3216's comments making sure the …
=> State change handling of alarm task's first run should generate no events

Makefile, raiden/transfer/events.py, raiden/transfer/mediated_transfer/events.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/state.py
In particular, this commit removes the "unknown name" error in
`mediated_transfer/state.py` about `SendSecretReveal`. After this, it
becomes possible to remove warnings from `raiden/docs` compilation.
=> Remove mypy errors around SendSecretReveal

tools/scenario-player/requirements.txt
Pyyaml had an arbitrary code execution vulnerability in previous
versions.
Check https://nvd.nist.gov/vuln/detail/CVE-2017-18342
@ulope please take a look
=> Upgrade scenarioplayer's pyyaml dependency

constraints.txt, docs/changelog.rst
Binaries for the version where already generated manually and tested for both parity and geth using Firefox and Chrome.
=> Update WebUI to v0.7.1

docs/changelog.rst, raiden/tests/unit/api/test_api.py, raiden/transfer/views.py
=> Fix API query for channel list without a partner address

.bumpversion_client.cfg, docs/changelog.rst, docs/conf.py, setup.py
Only real changes added on top of rc1 are:
```
* :feature:`-` Update WebUI to version 0.7.1 https://github.com/raiden-network/webui/releases/tag/v0.7.1
* :bug:`3257` Requesting the channel list with a token address and not a partner address via the API should no longer cause a 500 server error.
```
Since rc1 testing did not really start yet we can start by testing rc2 directly.
=> Bump to v0.100.2-rc2

docker/Dockerfile
I mixed up my Dockerfile versions in PR #3247... 
Obviously, the repo needs to get cloned in `/app/raiden` and the git fetch is not needed.
=> Fixed folder mixup

tools/debugging/replay_wal.py
If either the `token_network_identifier` or `partner_address` parameters
weren't given the utility would fail at lines 150 or 151. This change
the values from optional to required.
=> replay_wal.py: changed command line arguments

raiden/tests/unit/test_sqlite.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/tests/utils/factories.py
- more property classes
-  refactorings of tests in `raiden/unit/test/transfer/mediated_transfer`
There will be a followup pr with:
- replacement of the old factories (`make_signed_transfer`, `make_channel` etc) where they are still used
- removal of the old factories
- introduction of randomness in the new factories, where the old factories had them
=> More new factories for unit tests

raiden/tests/conftest.py
This adds the option `--gevent-monitoring-signal` to the pytest
configuration. This option allows to inspect the gevent state when
sending
kill -SIGUSR1 $(pidof -x pytest)
to a running pytest session.
=> Add pytest option for gevent monitoring signal

raiden/api/python.py, raiden/network/proxies/payment_channel.py
- removed locks from the payment_channel proxy, since the token network
already has locks in place.
- Channel operations are no longer raising a ChannelBusy exception if
there is another concurrent operation. The new transaction will just
wait for the pending one to finish, and once the lock is held the
preconditions checks if the transaction is still valid.
- This means that if a user request for a close and there is a
deposit in flight, the close will not raise an error but wait for
the deposit and then execute.
- The same happens for the deposit waiting for a close, but the
deposit is not sent once the lock is acquired because of the
preconditions checks.
The above means we no longer need to acquire the locks for all channels
before doing a batch close, we can just dispatch the action …
=> simplified lock acquision in the python api

raiden/tasks.py, raiden/ui/cli.py
Fix #3285
When attempting to stop the smoketest after the raiden client and geth
has started we could get a JSON decoding error or a keyboard interrupt
error and the test would be stuck.
This PR handles that.
=> Fix smoketest failure at keyboard interruption

raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/transfer/mediated_transfer/state.py, raiden/transfer/mediated_transfer/target.py
The target state machine had no chek for a in-flight secret transaction,
resulting in a new transaction after each new block.
=> Target must register secret onchain once only

raiden/raiden_event_handler.py, raiden/storage/sqlite.py, raiden/tests/unit/test_sqlite.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/utils.py
merge after https://github.com/raiden-network/raiden/pull/3299
The initiator must update the channel state when the secret is
registered an on-chain secret even if the channel is closed. What the
initiator should not do is send an unlock, because that is unecessary.
=> bugfix: Initiator on-chain secret registration

.circleci/config.yml, raiden/tests/conftest.py, raiden/tests/integration/long_running/test_integration_events.py, raiden/tests/utils/geth.py, requirements-dev.txt
Previously we used file level timing based test splitting on Circle CI.
The problem with that approach is that it limits the minimum achievable runtime to the one of the longest single test file.
This PR introduces splitting the tests at the test function level instead of by file. This allows us to utilize more workers and thereby reduce the test suite runtime.
Currently it takes about 9 minutes for the entire run, but this should improve a bit more over time as more timing data is gathered and the distribution will become more even.
=> Split tests on Circle CI by test function instead of file

.pylint.rc, CONTRIBUTING.md, raiden/encoding/format.py, raiden/tests/conftest.py, raiden/tests/unit/test_logging.py, raiden/tests/utils/geth.py, raiden/utils/cli.py, raiden/utils/serialization.py
There are cases where we mistakenly redefine python built-ins in the code. Pylint allows us to add a check to avoid this.
=> Use pylint's builtin-redefine check

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/transfer/channel.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/mediator.py
A node should not send a balance proof for a closed channel, added
missing checks for the refund and removed expired lock BPs.
=> Added asserts on balance proofs

raiden/network/blockchain_service.py, raiden/network/proxies/payment_channel.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py, raiden/network/rpc/client.py, raiden/network/rpc/smartcontract_proxy.py, raiden/tests/integration/contracts/test_secret_registry.py, raiden/tests/integration/contracts/test_token.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/integration/contracts/test_token_network_registry.py, raiden/tests/integration/rpc/test_assumptions.py, raiden/tests/integration/test_pythonapi.py, raiden/utils/__init__.py
After the changes introduced by https://github.com/raiden-network/raiden/pull/2623/ we again rely on gas estimation for the gas limit to provide to an onchain call which is great since it reduces our overall ETH balance requirements.
But we don't take into account the fact that if estimateGas returns `None` it's
because the transaction will fail, either due to our account not having enough
funds or because the call will just revert somewhere down the line due to the
contract logic (e.g. calling settle before closing).
With that in mind we can now detect those bad cases a bit earlier and handle
them without sending an onchain transaction. This is what this PR is trying to achieve.
Admittedly all those cases are bad ones. Since all the checks should have stopped us from getting into that …
=> Try to handle estimateGas predicting that a call will fail

.travis.yml, .travis/install.sh
This will also probably circumvent the pip 19.0 pyinstaller
[bug](https://github.com/pypa/pip/issues/6163) that hit us in all
Travis jobs. Example: https://travis-ci.org/raiden-network/raiden/jobs/483407811
=> Don't install pyinstaller and s3cmd in jobs that don't need it

raiden/tests/integration/test_recovery.py
The test started a transfer and waited for the initiator to complete,
that, however, doesn't mean the target received the unlock. This adds a
wait condition for the unlock on the target, allowing the channel's of
the two nodes to be compared to each other
=> Fix race condition in tests

raiden/tests/integration/long_running/test_integration_events.py, raiden/tests/utils/protocol.py
- Renamed test_secret_revealed -> test_secret_revealed_on_chain
- Relying on the core logic to register the secret on-chain, instead of
using the channel proxy directly
- Asserting on the state of the other channel
Fixes #3301
=> Fix test_secret_revealed

Makefile, raiden/transfer/mediated_transfer/events.py, raiden/transfer/state.py, raiden/utils/typing.py
I chose `PaymentAmount` over `TokenAmount` because `Payment` sounded more specific.
---
but @LefterisJP pointed out that `PaymentAmount` is usually for end-to-end amounts so I changed my mind.
=> Remove mypy errors around SendSecretRequest

raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/node.py, raiden/transfer/token_network.py
This is open to discussion. I think we should either remove them and let the unknown state changes fall through, or make sure that all transition functions raise a runtime error
=> remove exceptions from state machines

raiden/tests/conftest.py, raiden/tests/unit/test_logging.py
The tests for the configure_logging produced two dozens of files for
each run, in the diretory where the pytest was executed. This
unecessarily cluterred the file system and gets annoying really quick.
This commit moves all the log files to a temp directory.
=> tests: fixed logging path

raiden/network/proxies/token_network.py
The signature of getChannelIdentifier is:
function (address, address) view public returns (uint256)
So the function will return 0 if the value exists, never the empty string
=> fix: getChannelIdentifier cannot return empty

raiden/network/proxies/token_network.py
The function had two checks for `if not gas_limit`, the first check
always exited with an exception, making the second dead code. This
merges the checks.
=> Fixed unreachable checks

raiden/network/proxies/token_network.py
Added a note to remind that this is a bad idea: https://github.com/raiden-network/raiden/pull/2985/files#r250980431
=> Note about safe usage of close [skip ci]

raiden/tests/fuzz/test_state_changes.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/transfer/mediated_transfer/initiator.py
When a transfer fails because a lock expired the corresponding events
must be emitted. This moves the event from the invalid secret request
together with the lock expiration to avoid emitting the same event
twice.
=> Fixed initiator fail events

raiden/tests/utils/geth.py, raiden/tests/utils/smoketest.py, requirements-dev.txt
- Moved the check for the process status inside the geth_wait_and_check,
otherwise that would be deadcode
- Added a check for the process name using the expected rpc port, this
should help with debugging in case there is no app using it, or
something besides geth
=> geth: added more checks for the cluster startup

raiden/tests/unit/test_accounts.py
Advice given to us during the test review [here](https://github.com/raiden-network/raiden/commit/d952a3542004c29c294110b2e9e8a9e85e2196dd#diff-3140c5bd953d5cc1ad34aeacae557b41R15)
=> Don't use deprecated yield fixtures

raiden/tests/integration/api/fixtures.py, raiden/tests/integration/api/test_restapi.py
As suggested to us during our test review
[here](https://github.com/raiden-network/raiden/commit/161373d5b2a50c9197c6c8e73f7f26a5cdd2dd2b#diff-a44bb237b7b15e261fcbc739db8ac042R15)
fixture names should never start with `test_`
=> Rename test_api_server to api_server_test_instance

raiden/encoding/messages.py, raiden/message_handler.py, raiden/messages.py, raiden/raiden_event_handler.py, raiden/tests/integration/test_recovery.py, raiden/tests/integration/test_regression.py, raiden/tests/integration/transfer/test_refund_invalid.py, raiden/tests/unit/test_channelstate.py, raiden/transfer/channel.py
Renaming Secret messages into Unlock messages.  The name Secret was chosen for historical reasons but not descriptive anymore.  Fixes #3132.
=> Rename Secret message into Unlock

raiden/tests/integration/fixtures/transport.py, raiden/tests/integration/test_matrix_transport.py
Adds round-robin scheme to `matrix_transports` fixture to support load balancing when `number_of_transports > #local_matrix_servers`. Extends `test_matrix_cross_server` to test the round-robin scheme.  Closes #3290
=> Improve matrix_transports fixture to allow generating an arbitrary number of transports #3290

.circleci/conditional_skip.sh, .circleci/config.yml, .circleci/fetch_geth_solc.sh, .circleci/fetch_pr_base_commit.sh, raiden.spec, tools/check_circleci_config.py
This includes a few fixes / improvements for CircleCI and deployment:
- Add check for consistent CircleCI workflows
Prevents the `raiden-default` and `nightly` workflows from diverging
- Allow skipping tests via commit message tag `[skip tests]`
Other than the builtin `[skip ci]` tag this prevents the tests from running but will still report a valid commit status back to GitHub
- Fix missing job dependency for CircleCI macOS deployment
The nightly macOS deploy job was missing a dependency
- Prevent PyInstaller from creating broken binaries 
When `pdbpp` is installed PyInstaller creates broken binaries due to import path hacking performed by pdbpp
=> Grab bag of CircleCI / deployment fixes

.circleci/conditional_skip.sh, docs/changelog.rst, raiden/tasks.py
Merge after #3371
----
Fix #3369
The commit which introduced this problem was
7e6dd0f
That commit had tried to fix the restart tests by resetting the alarm task's
`_stop_event` to `False` whenever a new alarm task is started during
tests.
The problem with this approach is that setting an `AsyncResult()` to
`False` at the very beginning, gives it a value. So by having a value
here:
https://github.com/raiden-network/raiden/blob/e76687c5d4dc8c6dd8888719ea60243f37c9a945/raiden/tasks.py#L151-L158
`self._stop_event.wait(sleep_time)` does not actually do any
sleeping. That's because the `AsyncResult` already has a value as we
can also see in the documentation
[here](http://www.gevent.org/api/gevent.event.html#gevent.event.AsyncResult.wait).
> If this instance already holds a value, it is …
=> Fix high CPU usage when idle.

CONTRIBUTING.md
Since 66c86686722dcc528f9d20f8a95a5bf31d6e972e no separate steps for installing Synapse are required.
=> Remove install_synapse.sh from CONTRIBUTING.md

raiden/tests/utils/protocol.py
This commit makes the testing tool HoldOffChainSecretRequest more
generic, so that it can be used with any raiden event.
=> Generalized HoldOffChainSecretRequest to any event

raiden/tasks.py
The periodical gas reserve check was checking if we have enough gas to
open `0` channels which was boiling down to a check `<= 0`. This commit
changes it to be checking for at least 1 channel
=> Gas reserve check was a no-op

raiden/network/blockchain_service.py, raiden/tests/integration/api/test_pythonapi.py, raiden/tests/integration/contracts/test_payment_channel.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/integration/long_running/test_integration_events.py, raiden/tests/integration/long_running/test_settlement.py, raiden/tests/integration/long_running/test_token_networks.py, raiden/tests/integration/test_service.py, raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py, raiden/tests/utils/geth.py
And moved the tool to the BlockchainService, since it's the only object
necessary to do the waiting.
=> Increased sleep for wait until block

raiden/api/rest.py, raiden/network/transport/udp/udp_transport.py, raiden/tests/integration/api/utils.py, raiden/tests/integration/long_running/test_stress.py, raiden/ui/cli.py, raiden/ui/runners.py
This is a cherry pick of the fixes for the REST API and UDP transport from the stress test with crashes.
There are two problems:
- The greenlets spawned to handle the incoming HTTP requests and UDP packets are not tracked if an explicit pool is not used. During normal usage this is not a problem, but for tests it means there can be a greenlet from a previous test waiting to be scheduled, resulting in *another* test failing because the RaidenService is not running anymore
- The interface with host and port in `start` was a bit error prone, so for the stress test it's just better to save that as a configuration for the REST API, so that it can be restarted and use the same port number.
This should fix the failure encountered here: https://circleci.com/gh/raiden-network/raiden/18129#tests/con …
=> Fix rest api

docs/changelog.rst, raiden/api/python.py, raiden/connection_manager.py, raiden/tests/integration/api/test_pythonapi.py
Fix #3380 
- The connection manager no longer attempts to deposit if per partner funds are zero.
- Invoking api's set total channel deposit with 0 funds is now rejected
=> Connection manager no longer attempts to deposit if per partner funds are zero

raiden/tests/integration/test_matrix_transport.py
The test was waiting for a single message in the wait loop, however it
was asserting that two messages arrived, this caused flakyness.
This additionally remove the asserts, since the number of messages is
already tests as part of the wait loop, which will timeout if the
expected number of messages is not received.
=> bugfix: flaky test_matrix_cross_server_with_load_balance

docs/changelog.rst, raiden/api/rest.py, raiden/api/v1/encoding.py, raiden/raiden_event_handler.py, raiden/raiden_service.py, raiden/tests/integration/api/test_restapi.py
allow the payment API caller to know the Secret and the SecretHash used for the payment. The secret and the hash are kept as part of the payment_status object and return to the caller as asyncresults data.
Fixes #3317
=> Feature:  Return the secretHash and the Secret as part of payment reponse

docs/api_walkthrough.rst
Docs were not updated, opening a channel requires a "total_deposit" field, not a "balance" field.
=> Update opening channel parameters

raiden/api/python.py, raiden/blockchain/state.py, raiden/message_handler.py, raiden/network/proxies/payment_channel.py, raiden/network/proxies/secret_registry.py, raiden/network/proxies/token.py, raiden/network/proxies/token_network.py, raiden/network/proxies/token_network_registry.py, raiden/raiden_event_handler.py, raiden/raiden_service.py, raiden/tests/integration/contracts/test_payment_channel.py, raiden/tests/integration/contracts/test_secret_registry.py, raiden/tests/integration/contracts/test_token.py, raiden/tests/integration/contracts/test_token_network.py, raiden/tests/integration/contracts/test_token_network_registry.py, raiden/tests/integration/fixtures/smartcontracts.py, raiden/tests/integration/long_running/test_settlement.py, raiden/tests/integration/test_balance_proof_check.py, raiden/tests/integration/test_blockchainservice.py, raiden/tests/integration/test_regression.py, raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/utils/network.py, raiden/tests/utils/smartcontracts.py, raiden/tests/utils/smoketest.py, raiden/ui/console.py
~~Merge after #3389 as its diff is also included here.~~ [Augusto: done]
This is a step towards the completion of https://github.com/raiden-network/raiden/issues/2885
In the spirit of smaller PRs for easier review I am making this a standalone PR.
- Add `block_identifier` to all proxy query functions that were missing it and make sure the call chain uses it properly.
- Add `given_block_identifier` (a better name suggestion is also welcome) to all proxy functions that send an on chain transaction. This block identifier will be used for all onchain queries for preconditions required for the action. Should eventually come from the state machine. Also added it to functions that don't have any preconditions for consistency's sake.
- Add the comment `# LEFTODO: Supply a proper block id` for all …
=> Add block_identifier to all proxy functions that were missing it

readthedocs.yml, requirements-dev.txt, requirements-docs.txt
Needed to be able to have a python 3.6 venv when building read the docs:
https://github.com/rtfd/readthedocs.org/issues/4713
=> Split out docs requirements into separate file

raiden/tests/integration/network/transport/test_udp.py, raiden/tests/integration/test_raidenservice.py
This:
- rename the tests to make their goal clear
- moved the transport specific test to a transport specific place
- renamed the `test_service` to `test_raidenservice` to make it cleared that it's testing the `RaidenService`
- Added a small description to the regression test, so that people don't have to open github to understand what the test is about.
=> tests: reorg for test_service

raiden/network/blockchain_service.py, raiden/tests/integration/contracts/test_payment_channel.py, raiden/tests/integration/contracts/test_token_network.py, raiden/ui/app.py, raiden/ui/cli.py
The contract manager is *required* to instantiate any of the proxies
through the BlockchainService. Without a contract manager the service is
effectively useless, since it's main responsability is to be a container
of proxies, to ensure proxy instances are shared making sure the locks
work.
This changes code to alwas give a reference to the contract manager
while instantiating a blockchain service.
=> fixed partial initialization

raiden/transfer/architecture.py, raiden/transfer/channel.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/initiator_manager.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/node.py, raiden/utils/typing.py
Not all state transitions can result in a None state, namely the chain,
and the token network can never be deleted. For this reason the
`Optional[]` part of the type was moved out of the `TransitionResult`.
This additionally add the missing type parameter to the most functions.
=> typing: Made TransitionResult state not optional

raiden/tests/integration/contracts/fixtures/contracts.py, raiden/tests/integration/fixtures/smartcontracts.py, raiden/tests/utils/smartcontracts.py
This PR does:
- Removes the extra tool to `deploy_contract` that does the same things as `JSONRPCClient.deploy_solidity_contract` 
- Removes a duplicated fixtures to deploy these smart contracts:
- Secret registry
- Token Network Registry
=> Simplify fixtures

raiden/network/blockchain_service.py, raiden/tasks.py, raiden/ui/runners.py
This PR takes the conversation from
[here](https://github.com/raiden-network/raiden/pull/3418#discussion_r254208431)
and presents an alternative approach.
Instead of having a cache on the network ID, we simply store it once
in the blockchain service at startup. From that point on we
periodically check the underlying ethereum node's network id and if it
changes under our feet we crash and burn (with a nice explanation).
Supersedes https://github.com/raiden-network/raiden/pull/3418. If this is merged I will close that old one.
=> Only check ethereum network id periodically

raiden/api/rest.py
Currently we only perform logging at the beginning of REST-API calls making it difficult to diagnose issues with API responses.
This adds logging calls to the `api_response` and `api_error` helpers which should cover all cases.
=> Add logging of REST-API results

raiden/exceptions.py, raiden/raiden_service.py, raiden/storage/serialize.py, raiden/storage/sqlite.py, raiden/tests/unit/migrations/test_v16_to_v17.py, raiden/tests/unit/test_sqlite.py, raiden/tests/unit/test_upgrade.py, raiden/tests/unit/test_wal.py, raiden/tests/utils/mocks.py, raiden/utils/migrations/v16_to_v17.py, raiden/utils/upgrades.py, tools/debugging/migrate_db.py, tools/debugging/replay_wal.py
- Separate serialization logic into `SerializedSQLiteStorage` while `SQLiteStorage` returns raw data.
- Introduced `transaction` method in storage to start an explicit transaction. 
- Introduced `maybe_commit` will only commit if we're outside an explicit transaction.
- Introduced `get_snapshot` and `update_snapshot` in  `SQLiteStorage`
Resolves #3423
=> Raw & Serialized SQLiteStorage

raiden/api/python.py, raiden/encoding/messages.py, raiden/messages.py, raiden/tests/integration/test_pythonapi.py, raiden/tests/unit/test_messages.py, raiden/tests/utils/messages.py, raiden/transfer/balance_proof.py, raiden/utils/typing.py
This
- adds an encoding spec for `RequestMonitoring` messages
- the message `RequestMonitoring`
- and finally a **python** API endpoint                                                                
create_monitoring_request(                                                                    
balance_proof,                                                                       
reward_amount,                                                                            
)                                                                                             
that will create a signed `RequestMonitoring` message from the (signed) partner's `balance_proof` and the given `reward_amount`.   
Bundling the message creation in `RaidenAPI` allows for flexible integration of the actual …
=> Add monitoring message

raiden/storage/serialize.py, raiden/storage/sqlite.py, raiden/utils/upgrades.py
@rakanalh for your consideration.
I guess "SerdeBase" was some kind of abbreviation for "Ser[ialization]de[sierialization]Base".
Took me some time to figure out it wasn't a typo. I think my proposal may be more readable. Serialization encompasses the deserialization part too in the naming.
=> Better name for shared serialization/deserialization class

raiden/blockchain/events.py, raiden/blockchain_events_handler.py, raiden/exceptions.py
The code had the following problems:
- called decode_event_to_internal twice
- the function decode_event_to_internal duplicated some of the values
from args into the event dict itself, but not all of them, so some of
the event handlers only needed the event outer dictionary, while others
also had to look up in the inner args dict
- because of the above, most of the values form args were duplicated in
the event dict
- some of the handlers used web3's naming convetion (blockNumber,
transactionHash), while other used raiden's naming convetion
(block_number)
- the checks for transaction hash were duplicated through out many
handlers
=> Simplified event handling

raiden/tests/utils/smartcontracts.py, raiden/ui/console.py, raiden/utils/__init__.py, raiden/utils/smart_contracts.py
The smart contracts are not part of the raiden code anymore, the
contract manager from the raiden-contracts must be used. This removes
the util get_contract_path since it pointed to a phantom folder, and
changes the utility code to deploy from the contract manager.
=> Removed broken util get_contract_path

raiden/network/transport/matrix/__init__.py, raiden/network/transport/matrix/transport.py, raiden/network/transport/matrix/utils.py, raiden/tests/unit/test_matrix_transport.py
Follow-up of #3393 , implement some leftovers from that PR
=> Split matrix server selection into utility function

raiden/network/transport/matrix/transport.py, raiden/network/transport/udp/udp_transport.py, raiden/tests/integration/test_matrix_transport.py
Method to send messages to one of the configured global rooms.
Needed for #3273 , based on top of #3427 so should be merged after it.
=> MatrixTransport.send_global method

.codecov.yml
By default, the codecov check fails whenever coverage decreases, which is impractical with our current workflow. This pr disables the github checks for now.
=> Change codecov config

raiden/utils/upgrades.py
Prior to this change, raiden (esp. tests) did create the files
`None` and `None.lock` in the cwd.
=> Don't run migration if `old_db_filename` is None

raiden/messages.py
Some colleagues IDE's were complaining about the missing definitions...
=> Add missing classes to `__all__` in raiden/messages.py

constraints.txt
This doesn't change anything for raiden as the older contracts are used, but will make the integration into the MS easier: https://github.com/raiden-network/raiden-services/pull/95
=> Update raiden-contracts to 0.10.1

raiden/messages.py, raiden/tests/unit/test_messages.py
Since `RequestMonitoring` is a complex message with three signatures,
verifying signatures is error-prone and incomplete verification can lead
to accepting tampered messages (see #3455).
=> Add a simplified verification interface to RequestMonitoring

docs/changelog.rst, raiden/api/python.py, raiden/api/rest.py, raiden/api/v1/resources.py, raiden/constants.py, raiden/exceptions.py, raiden/raiden_service.py, raiden/tests/integration/api/test_restapi.py
Feature: secret and/or hash with payment request - closes #3318 
This feature allows the payer to optionally provide a secret and/or a secret_hash that should be used for the payment. If no secret and secret_hash provided as part of the payment request the secret and the hash should be selected by Raiden. If only a secret is provided the secret hash should be extracted from the given secret. If both secret and secret hash provided they should match. Providing only the secret hash is not currently supported.
=> Feature: secret and/or hash with payment request

raiden/raiden_service.py, raiden/tests/integration/test_send_queued_messages.py
Resolves #3432.
https://github.com/raiden-network/raiden/blob/cbbe30f440d0f2cea9afed7f3714af94fbdb253a/raiden/raiden_service.py#L618-L642
The problem is as follows:
1. The above code looks at the `event_queues` and then tries to `register_payment_state` if we find that we have a `SendLockedTransfer` event that the current node emitted.
2. When the client crashes / is stopped, the queues are not restored to the state it had previously (this only happens when a snapshot is taken)
Possible solutions i have in mind:
1. Snapshot when the raiden client is stopped
2. Somehow restore the queues between runs based on `SendMessageEvent`s stored in the DB (though there is no guarantee to know which ones were sent and which ones were not).
Thoughts @hackaugusto, @LefterisJP?
=> Initiator restart crash fix

raiden/tests/integration/transfer/test_refundtransfer.py, raiden/transfer/state.py
All calls to `lockstate_from_lock` received and returned an instance of `HashTimeLockState`
=> Removed useless lockstate_from_lock util

.circleci/config.yml, Makefile, docker/build.Dockerfile, raiden.spec
add arm binary build to circle
add architecture information to docker builds
In the build process circle ci triggers the arm build process for armv7 and aarch64 (armv8). 
closes #3401
=> Enable Arm binary build in CI

raiden/transfer/mediated_transfer/state_change.py
Eight errors squashed:
```
raiden/transfer/mediated_transfer/state_change.py:237: error: Argument "secrethash" to "ReceiveLockExpired" has incompatible type "bytes"; expected "SecretHash"
raiden/transfer/mediated_transfer/state_change.py:237: error: Argument "message_identifier" to "ReceiveLockExpired" has incompatible type "int"; expected "MessageID"
raiden/transfer/mediated_transfer/state_change.py:296: error: Argument "payment_identifier" to "ReceiveSecretRequest" has incompatible type "int"; expected "PaymentID"
raiden/transfer/mediated_transfer/state_change.py:296: error: Argument "amount" to "ReceiveSecretRequest" has incompatible type "int"; expected "PaymentAmount"
raiden/transfer/mediated_transfer/state_change.py:296: error: Argument "expiration" to "ReceiveSecretRequest" has …
```
=> Added type annotation to mediated_transfer/state_change

raiden/blockchain_events_handler.py
Two mypy errors squashed:
```
raiden/blockchain_events_handler.py:141: error: Item "None" of "Optional[NettingChannelState]" has no attribute "our_state"
raiden/blockchain_events_handler.py:200: error: Incompatible types in assignment (expression has type "ContractReceiveRouteClosed", variable has type "ContractReceiveChannelClosed")
```
=> Added type annotation to blockchain_events_handler

.circleci/config.yml, raiden/tests/integration/fixtures/blockchain.py, raiden/tests/utils/geth.py
Currently a single test session will run multiple tests, each test
starts a new set of geth nodes /sharing/ the log paths, because geth
overwrites logs on subsequent runs this results in loss of logs.
This commit adds an explicit logpath to the fixtures, allowing all logs
to be collected in a single folder, which can be used to publish these
logs as artificats from the CI.
Because each new geth cluster uses a different set of private keys, the
address of each node will be different, meaning that log file names
won't collide.
=> Geth: Moved logging to a separate folder

raiden/blockchain/events.py, raiden/blockchain_events_handler.py, raiden/network/rpc/client.py, raiden/raiden_service.py, raiden/tests/fuzz/test_state_changes.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_node_queue.py, raiden/tests/unit/test_pfs_integration.py, raiden/tests/unit/test_tokennetwork.py, raiden/tests/unit/test_wal.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/tests/unit/transfer/test_node.py, raiden/tests/utils/factories.py, raiden/transfer/architecture.py, raiden/transfer/state_change.py, raiden/transfer/views.py
This is the third PR for the consistent blockchain view issue: https://github.com/raiden-network/raiden/issues/2885
- Adds the `blockchash` as an extra argument to all the `ContractReceiveXXX` state changes.
- Initializes the `ContractReceiveXXX` state changes at `blockchain_events_handler.py` with the blockhash of the corresponding block number the event came from.
- Changes all the tests for the above. This is, unfortunately, the biggest part of the diff.
=> Consistent blockchain view - Iteration number 3

raiden/api/python.py, raiden/blockchain/state.py, raiden/blockchain_events_handler.py, raiden/message_handler.py, raiden/raiden_event_handler.py, raiden/raiden_service.py, raiden/tests/integration/long_running/test_integration_events.py, raiden/tests/unit/test_raiden_event_handler.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py, raiden/tests/unit/transfer/test_node.py, raiden/transfer/architecture.py, raiden/transfer/channel.py, raiden/transfer/events.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/secret_registry.py, raiden/ui/console.py
~~Don't merge before https://github.com/raiden-network/raiden/pull/3485.~~ done
This PR depends on it.
----
This PR adds the `blockhash` to all ContractSendXXX events and utilizes it later in the event handling to forward it to the proxies to achieve consistent blockchain view of what generated the event and what the proxy checks right before sending a transaction.
In two places marked with comments in the code, there is no way to get the current blockhash from inside the state machine. For all other places I get it from the `ContractReceiveXXX` state changes.
But for `ContractSendChannelClose` and for `ContractSendSecretReveal` only
in the case a mediator receives an offchain secret reveal we don't
have any way of getting the block hash. We have the block number, but
we can't make an I/O …
=> Consistent blockchain view Iteration 4 -- blockhash in ContractSendXXX events

raiden/tests/utils/smoketest.py, raiden/ui/cli.py
With the introduction of `contextlib.redirect_stdout`:
- step `[7/8]` was no longer printed to stdout. I added the `file`
target to `print_step`, so we always print steps to the original stdout
- the `--debug` pdb post-mortem hook was no longer displayed at stdout.
I pass the original stdout to the smoketest function, in order to
recover it on `pdb.post_mortem()`.
=> Fix smoketest stdout redirection

raiden/network/transport/matrix/client.py, raiden/network/transport/matrix/transport.py, raiden/raiden_service.py, raiden/tasks.py, raiden/tests/integration/fixtures/raiden_network.py, raiden/tests/utils/network.py
bugfix: Matrix transport hang forever
- `gevent.wait` will block forever if there is an **unstarted**
`gevent.Greenlet` in the list.
- `Matrix._get_retrier` always adds the `RetryQueue` item to its
internal mapping
- If the `Matrix._stop_event` is set, the retrier is not started.
- During a call to `Matrix.stop` the first thing done is to set
`_stop_event`, and then the transport waits on the existing greenlets
and *retries*
- Because there is additional logic after setting the event and waiting
for the retriers which does context switch, a race existed which would
add an unstarted retrier to the transport mapping and wait on it.
=> Matrix dead lock fix

raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_sqlite.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py, raiden/tests/utils/factories.py
This was noticed while trying to fix tests for https://github.com/raiden-network/raiden/pull/3515 and I split it out into a different PR to make reviews easier.
`test_locked_transfer_secret_registered_onchain` was using
`make_signed_transfer()` as a factory of `LockedTransfer` while it's a
factory of `LockedTransferSignedState`.
The `test_locked_transfer_secret_registered_onchain`
test was not failing since the secret registration check got us
out of the function early enough to not hit any attribute errors.
This commit splits `make_signed_transfer()` into two different
factories and uses the correct one in test_locked_transfer_secret_registered_onchain
=> Split make_signed_transfer() factory in two and fix test

.bumpversion_client.cfg, .circleci/config.yml, docs/changelog.rst, docs/conf.py, setup.py
These are the commits from v0.100.2 that bumped the version, added the critical fixes to the changelog and fixed the build for github deployment in CircleCI. Also contains the fix for the issues which in master turns out to be a no-op commit since the diff is already in there.
=> Update master with v0.100.2 commits

docs/rest_api.rst, raiden/api/python.py, raiden/api/rest.py, raiden/api/v1/resources.py, raiden/tests/integration/api/test_restapi.py, raiden/tests/utils/smoketest.py, raiden/transfer/views.py
Add as GET endpoint to `/tokens/<hexaddress:token_address>'`
This is necessary for #3509 to get the corresponding token networks address for a given token.
=> Add GET endpoint to /token/<address>

raiden/network/transport/matrix/transport.py, raiden/raiden_event_handler.py, raiden/raiden_service.py, raiden/tests/integration/test_matrix_transport.py, raiden/transfer/mediated_transfer/events.py, raiden/ui/app.py
This implements #3454 : after recovery, a state diff against an empty state is generated. This will yield all latest received balance proofs of the recovered state. Those are then sent to the broadcast room (if configured).
This PR also changes the way that monitoring requests are generated in general: instead of relying on a specialized event & event handler, `RaidenService` will now directly send the monitoring requests (if configured).
=> Monitoring requests on recovery

raiden/raiden_service.py
The test `test_locked_transfer_secret_registered_onchain` was used to
guarantee that a node does not reuse a known secret. It first registered
the secret and then called `start_mediated_transfer_with_secret`. Because
the Raiden node was only querying the blockchain state from confirmed
blocks the recently registered secret was missed.
In this particular instance, using `latest` as a block_identifier is
fine, we don't need a consistent view of the blockchain for that
particular call.
=> Fix test race condition

.circleci/config.yml
@ulope please take a look if this will do the trick. I am not sure if wildcard will work there, and the `ghr` tool's [docs](https://github.com/tcnksm/ghr) don't have an example with excluding files.
=> Omit LATEST_XXX.txt from release artifacts when uploading to github

raiden/tests/unit/test_channelstate.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/transfer/channel.py, raiden/transfer/mediated_transfer/mediator.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/node.py, raiden/transfer/token_network.py
- Removed unused PRNG from the functions arguments, as a consequence the
PRNG doesn't need to be instantiated in some tests
- Added a `is_` prefix to a predicate function
- Added a siple docstring explaining some predicated functions
=> Simplified some channel.py functions

raiden/accounts.py
Newest `astroid` version 2.2.0 started to complain about `no-member` for
`Exception.errno` for `(JSONDecodeError, KeyError, UnicodeDecodeError)`,
albeit there was an `isinstance` check before accessing it. By
separating the `except` blocks, I was able to mute that problem.
=> Fix no-member complaint by pylint

tools/parallel_tests.sh
This adds a small utility `tools/parallel_tests.sh` that run pytest in parallel.
=> Added utility to run tests in parallel

.dockerignore, .gitignore, tools/testnet/.gitignore
The linux deployment builds contained a `dirty` version tag since there was a mismatch between `.gitignore` and `.dockerignore` leading to files being seen as modified inside the build container that didn't actually change.
Fixes #3531
=> Fix incorrect deployment build version

raiden/messages.py, raiden/network/proxies/token_network.py, raiden/raiden_event_handler.py, raiden/tests/unit/test_messages.py, raiden/tests/utils/factories.py, raiden/transfer/balance_proof.py, raiden/transfer/channel.py, raiden/transfer/node.py, raiden/transfer/state.py, raiden/utils/__init__.py
As raised in #3493 we want to tighten the definition of what identifies a channel.
This PR introduces the new type `CanonicalIdentifier` as a (named) tuple of 
`(chain_identifier, token_network_address, channel_identifier)`.
- In order to allow for a gradual introduction, I chose to use the identifier with signed balance proofs first.
- In order to avoid migrations at this point in time, the identifier is used as an `__init__` argument, but then destructured into the existing fields.
- To minimize the amount of mypy casts introduced by this, `CanonicalIdentifier.token_network_address` is typed as a union of `TokenNetworkAddress` and `TokenNetworkID` for now.
=> Introduce CanonicalIdentifier

raiden/tests/unit/test_sqlite.py, raiden/tests/utils/factories.py, raiden/transfer/channel.py, raiden/transfer/state.py
This is the next iteration for #3493 -- introduced the `CanonicalIdentifier` to the next State item.
=> Use CanonicalIdentifier in BalanceProofUnsignedState

docs/overview_and_guide.rst
Removed mentioning synapse installer in order
to run `raiden smoketests`.
=> Remove outdated Synapse mention in smoketest docs.

raiden/tests/integration/cli/conftest.py
In the past, the `raiden/tests/integration/cli/test_cli_*` family created `raiden-debug*` logfiles in the project directory. Since there aren't any assertions on the creation of the debug log, I just disabled them via `--disable-debug-logfile` in the `cli_args` fixture.
=> Disable debug logfile in automated ci tests

raiden/tests/integration/test_matrix_transport.py
Our `--pdb` hook for debugging greenlets interferes with the test logic in `test_matrix_tx_error_handling`. To spare other developers from debugging a non existing test failure, I marked the test to skip if run with the `--pdb` option.
=> Skip test when running `pytest --pdb`

constraints.txt, raiden/tests/fixtures/constants.py, raiden/tests/fixtures/variables.py, raiden/tests/utils/eth_node.py, raiden/tests/utils/smoketest.py, requirements-dev.txt, requirements.txt
`smoketest` does not need `pytest`, but some of its imports did also import `pytest`. Since it were only three constants, I could just move them into an independent module and allow for pytest free smoketest execution:
python -m raiden smoketest
or
raiden smoketest
now work without `pytest` being installed.
cross-ref #3580
=> Make smoketest test dependencies independent of pytest

raiden/network/transport/matrix/transport.py, raiden/storage/serialize.py
Added documentation to clarify that we do automagic module imports in the storage encoder, and remove the usage of the encoder from the matrix transport to avoid any future problems
=> Json encoder

raiden/api/rest.py, raiden/network/transport/udp/udp_transport.py
Very small commit cherry-picked from the crash stress test.
Most of the changes have been done in other PRs, this just make the log lines consistent and remove a duplicated from the udp transport.
=> logging: Added logs for the runnables lifetime

.pylint.rc, Makefile, raiden/api/python.py, raiden/connection_manager.py, raiden/network/transport/matrix/utils.py, raiden/tests/integration/contracts/test_secret_registry.py, raiden/tests/integration/test_pythonapi.py, raiden/tests/integration/test_regression.py, raiden/tests/utils/network.py, raiden/utils/echo_node.py, tools/pylint/gevent_checker.py
This adds a custom pylint linter to enforce the first argument of
gevent.waitall to be a set. This is necessary to avoid deadlocks because
of duplicated elements in the container used to wait for.
This is a custom linter to avoid problems related to deadlocks found during development of https://github.com/raiden-network/raiden/pull/3556
=> lint: checking for gevent.waitall usage

.pylint.rc, CONTRIBUTING.md, raiden/tests/unit/test_serialization.py, raiden/tests/utils/transport.py
Hence, remove that requirement from the
styleguide in CONTRIBUTING.md.
=> No need to subclass from object in Py3.

raiden/log_config.py, raiden/tests/unit/test_cli.py, raiden/utils/__init__.py, tools/scenario-player/scenario_player/main.py, tools/scenario-player/scenario_player/node_support.py
Fixes: #3582 
Fixes: #2739
Small drive by fixes:
- Include architecture in `get_system_spec` output.
- Fix scenario player file logging (`debug` level messages were missing from file log)
=> Fix Scenario Player release download

raiden/tests/unit/test_messages.py
Adds a test that shows how an attacker can tamper with a `RequestMonitoring` Message after it was signed. Can be used as a regression test if/when merged/fixed.
=> Tampering with RequestMonitoring 

raiden/tests/utils/transport.py
Was having issues running tests because spawning the matrix server process claimed to have failed because the configuration file did not exist:
```
________________________________ ERROR at setup of test_batch_unlock[matrix-False-2] _________________________________
request = <SubRequest 'local_matrix_servers' for <Function test_batch_unlock[matrix-False-2]>>
transport_protocol = <TransportProtocol.MATRIX: 'matrix'>, matrix_server_count = 1
synapse_config_generator = <function generate_synapse_config.<locals>.generate_config at 0x7ffba1237a60>
@pytest.fixture
def local_matrix_servers(
request,
transport_protocol,
matrix_server_count,
synapse_config_generator,
):
if transport_protocol is not TransportProtocol.MATRIX:
yield [None]
return
starter = matrix_server_starter( …
```
=> Fix spawn transport

raiden/utils/__init__.py
This adds the serialization methods `to_dict` / `from_dict` to `CanonicalIdentifier`.
=> Add *dict* serialization methods to CanonicalIdentifier

raiden/blockchain/state.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_messages.py, raiden/tests/unit/test_sqlite.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/test_state_diff.py, raiden/tests/utils/factories.py, raiden/transfer/channel.py, raiden/transfer/mediated_transfer/initiator.py, raiden/transfer/mediated_transfer/target.py, raiden/transfer/state.py, raiden/utils/__init__.py
This adds usage of `CanonicalIdentifier` in the constructor of `NettingChannelState`.
It does **not** change serialization behavior and therefore should not need migrations.
It also adds a factory method for use in tests, `make_canonical_identifier` that allows for minimally specified identifiers (uses default unit test values for unspecified attributes). Using the factory in tests also has the benefit of minimizing the changes, that would be necessary if the import path of `CanonicalIdentifier` should ever change.
This is a follow-up to #3584 and should be reviewed/merged only after it.
=> Netting channel canonical constructor

raiden/blockchain_events_handler.py, raiden/storage/restore.py, raiden/transfer/node.py, raiden/transfer/views.py, raiden/waiting.py
Add usage of `CanonicalIdentifier` as an argument in view functions for the channel state.
It also refactors two functions in the `waiting.py` module, to share the common code and deletes an almost duplicated view function.
=> Canonical identifier in views/get_channelstate

raiden/api/python.py, raiden/blockchain_events_handler.py, raiden/tests/fuzz/test_state_changes.py, raiden/tests/integration/test_matrix_transport.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_node_queue.py, raiden/tests/unit/test_pfs_integration.py, raiden/tests/unit/test_tokennetwork.py, raiden/tests/unit/test_wal.py, raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/test_node.py, raiden/transfer/node.py, raiden/transfer/state_change.py, raiden/utils/__init__.py
This PR changes the constructors of (applicable) classes from `raiden/transfer/state_change.py` to use `CanonicalIdentifier` instead of isolated identifier arguments.
This is still serialization compatible (where the deserialization doesn't have `chain_identifier` available, it will use a dummy value).
This is one more step for #3493 
Some notes for reviewers:
- All commits are self-contained and can be reviewed in isolation!
- `ContractReceiveChannelBatchUnlock` so far does not receive a `channel_identifier`. However, the channel will be identified later in the processing. I suggest to move the `channel_identifier` resolution into the event creation, so we can treat it as a fully identified channel event (see 6364801a1a6730e3de644187c012d09d8749943a)
- `ContractReceiveChannelNew` so far …
=> Add CanonicalIdentifier to state change constructors

constraints.txt, raiden/api/rest.py
The CVE description can be found
[here](https://nvd.nist.gov/vuln/detail/CVE-2019-9710#vulnCurrentDescriptionTitle).
Essentially webargs JSON parsing uses a short-lived cache to store the parsed JSON body. This cache is not thread-safe, meaning that incorrect JSON payloads could have been parsed for concurrent requests.
**side note**
We really should put all of our requirements back into `requirements.txt` and just keep the non-direct dependencies pinning in `constraints.txt`. We no longer get github security updates because of our current structure. I saw this due to another project.
=> Fix Rest API affected by webargs CVE-2019-9710

docs/changelog.rst, raiden/network/rpc/client.py, raiden/network/rpc/middleware.py, raiden/utils/filters.py
Fix #3558 
This PR does two things to address the problems seen in #3558.
1. Introduces the same middleware they use in PFS for retrying requests with backoffs for web3 as seen [here](https://github.com/raiden-network/raiden-services/blob/51b2b3093915c482e3d8307a09f2952ffa3c6c7e/src/pathfinding_service/middleware.py). This change alone fixes the crash for geth but not for parity or infura.
**side note**
@palango I made a few changes to the code when copying. You are using the native built-in `ConnectionError` while you should use the one from requests. Also ... we should probably have these stuff in some common code repository as long as we don't go for the monorepo approach
2. Querying filter for new entries now queries up to 100k blocks with each query. Querying all 7,8 million blocks …
=> Fix raiden crashing at startup if starting from a fresh DB

raiden/api/python.py, raiden/blockchain_events_handler.py, raiden/messages.py, raiden/tests/integration/long_running/test_integration_events.py, raiden/tests/integration/test_matrix_transport.py, raiden/tests/unit/test_channelstate.py, raiden/tests/unit/test_messages.py, raiden/tests/unit/test_node_queue.py, raiden/tests/unit/test_raiden_event_handler.py, raiden/tests/unit/test_tokennetwork.py, raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py, raiden/tests/unit/transfer/test_node.py, raiden/transfer/balance_proof.py, raiden/transfer/channel.py, raiden/transfer/events.py, raiden/transfer/state.py
This adds the `CanonicalIdentifier` for #3493 to the classes in `raiden/transfer/events.py` (where applicable).
It also adds a transient `.canonical_identifier` property to `NettingChannelState` (based on the already existing partial identifiers), which allows for a lot of code simplification.
`pack_reward_proof` now also uses a `CanonicalIdentifier` as an argument (instead of the singular arguments).
This is still all done without serialization changes.
=> CanonicalIdentifier in Events (plus some cleanups)

raiden/raiden_event_handler.py, raiden/tests/unit/test_sqlite.py, raiden/transfer/utils.py
This uses `CanonicalIdentifier` when querying the DB for #3493
=> CanonicalIdentifier in `raiden.transfer.utils`

raiden/tests/utils/genesis.py
This is an attempt to speed up `--blockchain-type=parity` integration tests by reducing the `stepDuration` to `1`(down from `3`) in `chainspec.json`.
=> Reduce parity `stepDuration` in integration tests

Makefile, raiden/network/sockfactory.py, requirements-lint.txt
This gets some additional cases in respect to the pycodestyle tool. Namely:
```
Correct deprecated or non-idiomatic Python code (via lib2to3). Use this for making Python 2.7 code more compatible with Python 3. (This is triggered if W690 is enabled.)
Normalize files with mixed line endings.
Put a blank line between a class docstring and its first method declaration. (Enabled with E301.)
Remove blank lines between a function declaration and its docstring. (Enabled with E303.)
```
=> Added autopep8 as a linting tool

CONTRIBUTING.md
- Add return types to all good examples.
- Add note about typing `__init__ -> None`
[skip tests]
=> Change style guide examples

raiden/message_handler.py, raiden/raiden_service.py, raiden/routing.py, raiden/tests/integration/long_running/test_token_networks.py, raiden/tests/integration/transfer/test_mediatedtransfer.py, raiden/tests/unit/test_tokennetwork.py
Turn the `privkey` argument (which is necessary to sign IOUs for the pathfinding service) of `raiden_service.get_best_routes` from an optional to a mandatory argument. It used to be optional in case we only wanted to use internal routing, e. g. in tests. However, in some calls to `get_best_routes` it was accidentally ommited, which caused it to only use internal routing there too.
Closes #3660
=> Fix call to pfs

.circleci/config.yml, .circleci/fetch_geth_parity_solc.sh, constraints.txt, raiden/tests/integration/rpc/RpcTest.sol, raiden/tests/integration/rpc/test_assumptions.py, raiden/utils/solc.py
We use `solc` in raiden only to compile one contract in the assumptions
test.
Our tests right now don't work with solidity >= v0.5.0 and the
contracts actually use solidity v0.5.4.
This PR fixes the tests and makes them work with solidity v0.5.4 which
is the same as in the contracts repo.
There is one tiny problem I need help from either @palango or @ulope for
=> Parity between solc version used in client and contracts

tools/scenario-player/scenario_player/constants.py, tools/scenario-player/scenario_player/exceptions.py, tools/scenario-player/scenario_player/runner.py, tools/scenario-player/scenario_player/scenario.py
This Commit slims down the `__init__` method of
scenario_player.runner.ScenarioRunner by moving
exception and defaults handling to specialized
wrapper classes for the yaml configuration.
Two new classes have been introduced:
- Scenario: A wrapper for the most of a scenario's yaml file.
- NodesConfig: A wrapper for the node configuration section
of a scenario's yaml file.
Additionally, a few new exceptions have been added, in order
to provide more descriptive error categories:
- MultipleTaskDefinitions
- InvalidScenarioVersion
- UnexpectedScenarioVersion
- MissingNodesConfiguration
=> Slim down ScenarioRunner.__init__

raiden/network/pathfinding.py
Token network addresses were accidentally not converted to hex.
Closes #3671
=> Use proper url to call the pathfinding service

raiden/network/rpc/client.py, raiden/tests/integration/rpc/test_client.py
Before I got a warning that `str`  and `int` could not be concatenated.
```
File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/paul/Projects/brainbot/raiden/tools/scenario-player/scenario_player/__main__.py", line 9, in <module>
prog_name='python -m scenario_player',
File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
File "/Users/paul/Projects/brainbot/raiden/venv/lib/python3.7/site-packages/ …
```
=> Fix nonce calculation for geth

setup.py
When other packages import raiden, the raiden type signatures will not
be used by mypy unless that package declares itself as properly types.
This can be done via PEP561:
https://mypy.readthedocs.io/en/latest/installed_packages.html#using-pep-561-compatible-packages-with-mypy
Adding this will greatly improve type checking quality in
raiden-services (and potential other packages) whenever imports from
raiden are used.
=> Declare raiden to be typed via PEP561

constraints.txt, requirements.txt
This PR should remove one obstacle against private net deployment.  Currently, with `click==6.7`, contract deployment scripts fail.  `raiden-contracts 0.17.0` specifies `click>=7.0`.  This PR specifies `click==7.0` and `raiden-contracts==0.17.0`.
=> Use raiden-contracts v0.17.0 and introduce click 7.0

tools/scenario-player/scenario_player/tasks/blockchain.py, tools/scenario-player/scenario_player/utils.py
because now it's deprecated.
`get_contracts_deployment_info()` has a nicer name and has more functionalities. After removing the usage of the old function, `raiden_contracts` can remove the old function.
=> Replace get_contracts_deployed() calls
