tools/scenario-player/example-scenarios/scenario-example-v2.yaml
tools/scenario-player/scenario_player/runner.py
tools/scenario-player/scenario_player/tasks/blockchain.py
tools/scenario-player/scenario_player/tasks/channels.py
tools/scenario-player/scenario_player/utils.py

As we use the same MonitoringContract for all token networks, we need a stateless version of the `assert_events` task.
The `assert_ms_claim` is quite specific (and hopefully can be better abstracted in the future. It calculated the `reward_id` for a given channel and checks that a `Claim`  event for that channel exists.

[SP] Add assert_ms_claim task, to check for MS claim events

---

constraints.txt
requirements-dev.txt

Not sure if this is still needed. Let CircleCI decide.

Remove eth-tester dependency

---

raiden/raiden_service.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_version_check.py
raiden/tests/unit/transfer/test_state_diff.py
raiden/transfer/views.py

Before this PR only changes in BPs of channel partners were observed. This is what's necessary for the MS to work, but for the PFS to work correctly both the partners as well as a nodes own BPs changes need to be observed.
This PR changes the `detect_balance_proof_change` function to also check for changes in the nodes own BPs.  The changes are furthermore annotated with the information of which BP changed (`OWN` or `PARTNER`, in theory the type should be enough, but I chose not to trust it here).
This information is then used to send the appropriate monitor requests and updates to the PFS.

Send PFS updates on own BP changes as well

---

docs/adr/0002-testing-strategy.md
docs/adr/template.md

We had a discussion of where to place ADRs. I think the best proposal was to have ADRs per project, so I'm not adding it for the main repo.
If we agree this is the right approach, I will also create a corresponding folder in the raiden-contracts and raiden-services.
I am adding the testing ADR as it is right now and a template we can follow.

adding dir for adrs and testing adr doc

---

requirements-lint.txt

This also seems to avoid the problem we started seeing with the
following discrepancy between isort locally and in Circle:
```diff
--- /home/circleci/raiden/raiden/transfer/views.py:before	2019-04-03 15:35:36
+++ /home/circleci/raiden/raiden/transfer/views.py:after	2019-04-03 15:38:08.183534
@@ -1,6 +1,5 @@
+from dataclasses import dataclass
from enum import Enum
-
-from dataclasses import dataclass
from raiden.transfer import channel
from raiden.transfer.architecture import ContractSendEvent, State
```

Upgrade isort to 4.3.16

---

raiden/tests/integration/test_echo_node.py

Skipping echo node tests so that people can work and merge their PRs. Fixing the tests is tracked by: https://github.com/raiden-network/raiden/issues/3750

Skip echo node tests

---

tools/scenario-player/example-scenarios/scenario-example-v2.yaml
tools/scenario-player/scenario_player/node_support.py
tools/scenario-player/scenario_player/tasks/api_base.py
tools/scenario-player/scenario_player/tasks/services.py

This PR add the `assert_pfs_routes` task to the scenario player.
This is a simple way to check that the PFS got certain information from nodes and will help to make some initial integration tests run.

[SP] Add assert_pfs_routes task

---

constraints.txt
requirements.txt

I might see mypy errors after this because raiden-contracts now
exposes typing data to the outer world https://github.com/raiden-network/raiden-contracts/pull/813 .

Update raiden-contracts to for using mypy typing information from raiden-contracts.

---

raiden/encoding/messages.py
raiden/messages.py

This adds the current constant mediation fee to the UpdatePFS message.
This needs to be changed once the representation of mediation fees
changes, but is a good enough for now.
Fixes #3754

Add mediation fee to UpdatePFS message

---

raiden/network/pathfinding.py
raiden/network/rpc/client.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/utils/smartcontracts.py

Fix #3757 
The solution is not ideal as it's not using Raiden Chain State's
confirmed block, but the two should be identical.
The reason why this is not using Raiden chain state's confirmed block
is that at the startup when the proxies are instantiated is when
`get_random_service()` is called. And at that point there is no raiden
App and no raiden service so the chain state has not been initialized yet.

get_random_service() should use the confirmed block

---

raiden/api/rest.py
raiden/exceptions.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network_registry.py
raiden/tests/integration/network/proxies/test_token_network_registry.py

Fix #3697 
As per the issue this does not guarantee that the token implements the ERC20 interface, but it implements the same check the contracts have, so the client at least won't be caught by surprise at registration time.

Check if token contract implements totalSupply function.

---

raiden/ui/app.py

When deployment metadata is available, the deploy block number must be
used. This is necessary to avoid filtering over many blocks.
This is a partial fix for #3801 , tests are missing.

Using deployed block number

---

raiden/tests/utils/eth_node.py

This fix a conflict for the datadir and logpath when
`run_private_blockchain` is called with the same value for
`base_datadir` and `log_dir`.

Fixed tools/startcluster.py

---

raiden/network/rpc/client.py

web3.eth.generateGasPrice() when there are not many transactions in the chain.
This fixes https://github.com/raiden-network/raiden/issues/3244 on the procedure documented in
https://github.com/raiden-network/raiden/blob/fe45769dd3c3f339b30a214599d028eb8351dc6a/docs/private_net_tutorial.rst

Workaround for web3 throwing exception in

---

.circleci/config.yml

Added a comment explaining why https://github.com/raiden-network/raiden/pull/3792 is a bad idea

Extended docs for the checkout job [skip ci]

---

raiden/storage/sqlite.py
raiden/storage/versions.py
raiden/tests/unit/storage/migrations/test_v16_to_v17.py
raiden/tests/unit/storage/migrations/test_v17_to_v18.py
raiden/tests/unit/storage/migrations/test_v18_to_v19.py
raiden/tests/unit/storage/migrations/test_v19_to_v20.py
raiden/tests/unit/storage/migrations/test_v20_to_v21.py
raiden/tests/unit/storage/test_versions.py
raiden/tests/unit/test_upgrade.py
raiden/tests/unit/utils/upgrades.py
raiden/tests/utils/smoketest.py
raiden/ui/cli.py
raiden/utils/upgrades.py

Fixed a bug introduced by: https://github.com/raiden-network/raiden/pull/3643 . The offending change is the removal of this check:
https://github.com/raiden-network/raiden/pull/3643/files#diff-fa75f1f3933a68f8046af87ad43aff37L28
Without that check the values of `old_db_filename` and `current_db_filename` could be the same:
https://github.com/hackaugusto/raiden/blob/edfebfe0ed7fa9d3462320054cff742f419127c7/raiden/utils/upgrades.py#L171
Additionally, this fix the special case were the cleanup is not executed:
https://github.com/hackaugusto/raiden/blob/edfebfe0ed7fa9d3462320054cff742f419127c7/raiden/utils/upgrades.py#L193-L196
Which can happens with a sigkill

Bugfix kill during migration

---

raiden/blockchain_events_handler.py
raiden/network/proxies/utils.py
raiden/storage/migrations/v19_to_v20.py

Small change that simplified a bit the interface of `get_onchain_locksroots`.
Depends on #3653 to fix the reference cycles.

Simplified get_onchain_locksroots

---

.circleci/config.yml

In the past we had multiple cases where building the binaries on CI
failed for one reason or another.
This caused a problem since the PyPI upload used to happen in parallel
with building the binaries and therefore could happen despite the
binaries failed to build.
Additionally PyPI doesn't allow to overwrite a release, which then causes
problems in subsequent runs fixing the binary building.

Move CI PyPI deployment to after binary building

---

raiden/raiden_service.py
raiden/storage/sqlite.py
raiden/tests/unit/storage/test_storage.py
raiden/utils/upgrades.py

Resolves #3832 
Causes of failure:
1. `KeyboardInterrupt` was not triggering a rollback as this its parent class is a `BaseException` which wasn't included in the `except` block.
2. At some point, instantiating `SQLiteStorage` caused an implicit `update_version` in the constructor which stored `RAIDEN_DB_VERSION` in that database and overrode what the upgrade manager was expecting.
@czepluch ran the branch on his failing account and confirms the fix works.

Rollback transaction for any exception

---

raiden/raiden_service.py
raiden/tests/unit/transfer/test_state_diff.py
raiden/transfer/views.py

This commit removes unnecessary classes and simplifies type handling.
Based on https://github.com/raiden-network/raiden/commit/e8cb79007622319dec593966b502529b888b02be#r33209631

Improve balance proof update handling for services

---

.circleci/config.yml

I opened this PR to explain what I meant [here](https://github.com/raiden-network/raiden/pull/3809#discussion_r275251700), however this may not be necessary, I guess the existing rationale is to only have integration tests depend on the relevant smoketest, e.g. the geth integration tests depends on the geth production and geth development smoketest but not on the parity smoketest.

integration tests wait on all smoketests

---

raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/api/test_pythonapi_regression.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/test_balance_proof_check.py
raiden/tests/integration/test_blockchainservice.py
raiden/tests/integration/test_echo_node.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refund_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/detect_failure.py

This change introduces an utility to run the tests an monitor the test's
apps. This is useful because exceptions are always propagated on the
Raiden code base, tests which use this tool will fail faster with the
actual raised exception.
~~Review/Merge after: #3818~~

Integrations tests raise if an app crashes

---

raiden/network/pathfinding.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_startup.py
raiden/tests/utils/factories.py

Add the missing arguments in the request body.
Closes #3850.

Fix call to pathfinding service's /iou endpoint

---

raiden/tests/conftest.py
raiden/tests/utils/transfer.py
raiden/utils/typing.py

the test `test_recovery_happy_case` seems flaky, and the assertion error is not very useful for debugging, this adds extra information to the assert message, and also enables pytest assert rewrite for the tests.utils

Extended asserts

---

.circleci/config.yml
Makefile

This commit adds the mypy check (as is) to the lint target in the
Makefile. It also removes the mypy task in CircleCI which should save us
some credits there.

Add mypy to lint task

---

raiden/network/rpc/client.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/rpc/test_assumptions.py

Merge/Review after: #3831
This adds the test for estimate gas on geth, parity has a strange behavior which has to be handled (tracking issue https://github.com/raiden-network/raiden/issues/3835 )

added estimate gas assumption test

---

raiden/tests/integration/cli/test_cli_development.py

Increasing the timeout because the test failed during tear down
culprit: https://circleci.com/gh/raiden-network/raiden/41313#tests/containers/14

increase test_cli_change_environment_type timeout

---

Makefile
raiden/message_handler.py
raiden/messages.py
raiden/tests/unit/test_messages.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/token_network.py
raiden/transfer/views.py
raiden/utils/signer.py
raiden/utils/typing.py

Big chunk of work towards https://github.com/raiden-network/raiden/issues/3798.
At the tip of this PR: `mypy raiden/transfer/ --ignore-missing-imports` returns `0`
This has uncovered a few places where perhaps the architecture of the state machine could be changed but I think that these places can be improved when it is switched to data classes.

All mypy complaints under the transfer directory adressed - Mypywork 5 

---

raiden/tests/integration/long_running/test_token_networks.py

The previous value of 6 was resulting in intermittent failures in the
build, this sligltly incrase the settle timeout to fix the flakyness.

Increase test's settle timeout

---

raiden/tests/integration/test_recovery.py
raiden/tests/utils/transfer.py

Fixed a race condition:
test_recovery_happy_case asserts on the state of mediator channels, but
the existing tools to do transfers do not synchronize the mediators.
This adds a new tool that will assume the provided path is used and wait
until all nodes are synchronized.
note: the tool can be improved by checking the locked transfer message
is sent to the exptected node, this however can be done as a later step.

Fix recovery happy case race

---

raiden/network/blockchain_service.py

This fixes the remaining 9 mypy errors for `raiden/network/blockchain_service.py`, as seen on
```
mypy --ignore-missing-imports raiden |grep -v "raiden.tests"|grep -i error|grep blockchain_service
```
Part of #3798

Fix mypy errors for `blockchain_service.py`

---

raiden/raiden_event_handler.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/unit/transfer/test_node.py
raiden/transfer/node.py

This solves the problem of having a Batch Unlock transaction in the
pending transaction queue which doesn't get cleared properly.
The pending transaction doesn't get cleared because our transaction
invalidation logic includes checks for the transaction clearing our
partner's side of the channel which is not true any more since the
current node could be trying to unlock it's own side of the channel.
The change basically clears batch unlock pending transaction in case
both sides of the channel were unlocked (channel got cleared).
```
- A sends B a transfer (secret is not revealed)
- B sends A a transfer (secret is not revealed)
- Channel is closed
- Wait for settle
- Crash A
- Wait for unlock from B (trying to unlock it's side)
- Restart A
- Assert A has unlocked it's side.
```
Resolves …

Clear ContractSendChannelBatchUnlock on restart properly

---

raiden/network/transport/matrix/__init__.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_matrix_presence.py

Extract user/address mapping and presence handling from Matrix transport
- Extract the user/address mapping and presence handling into a separate utility class (`UserAddressManager`)
- This allows the services to use this functionality as well (Fixes #3720)
- Complete unit test coverage of the new `UserAddressManager`
Refs: #3124, #3252

Extract user/address mapping and presence handling from Matrix transport

---

raiden/messages.py

When updating the raiden commit in the services it started complaining about this.

Fix signature typing in UpdatePFS message

---

raiden/network/proxies/secret_registry.py
raiden/raiden_event_handler.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/transfer/test_mediatedtransfer.py

The block identifier is unecessary for the secret registration because
the action is always valid (there are no preconditions to check), for
this reason the blockhash is unecessary.
In order to preserve a consistent blockchain view, this removed the
unecessary argument and start using the latest confirmed block as a
reference point. This removes problems with prunned blocks and chain
reorgs.

Fixed secret registration

---

raiden/utils/upgrades.py

The PR #3644 forgot to include the migration in the upgrade manager.
This fixes #3960

Actually run migrations v21 to v22

---

raiden/accounts.py
raiden/utils/__init__.py

Part of #3798 
The `accounts` module follows a "return-value-or-None" pattern, but many functions were typed non-optional. I changed the return types and added asserts to properly support mypy with type inference/checking.
Impact:
```
mypy --ignore-missing-imports raiden |grep -v raiden.tests |wc -l
55
mypy --ignore-missing-imports raiden |grep -v raiden.tests |wc -l
46
```

Properly type account/key operations

---

raiden/encoding/messages.py
raiden/messages.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py

This PR enables sending messages to a whitelisted node via `transport.send_to_device`. 
- A ToDevice message can be send to all known devices of a user without creating a room first
- The receiver transport receives the message via `_sync` and handles it. 
To do's:
Caveats: 
The message is  delivered exactly once and is non retrievable.

Add send_to_device method to matrix transport. 

---

raiden/network/pathfinding.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/ui/cli.py
raiden/ui/startup.py
raiden/utils/cli.py

Part of #3798 
```
mypy --ignore-missing-imports raiden |grep -v raiden.tests|grep -v transport|wc -l
32
mypy --ignore-missing-imports raiden |grep -v raiden.tests|grep -v transport|wc -l
6
```

Fix mypy errors in startup / cli

---

raiden/tests/fixtures/variables.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/utils/app.py
raiden/tests/utils/network.py
raiden/utils/upgrades.py

This saves the raiden node's database as CI artifacts. It can be useful for debugging.
Additionally it tries to name the directories in a way that matches our tests, e.g.:
https://github.com/raiden-network/raiden/blob/5df09ee128ec343eafa09456d55c74ef5ea4d9b2/raiden/tests/integration/test_raidenservice.py#L99-L101
`app0` and `app1` will be part of the node's datadir name

Saving raiden node logs

---

Makefile
raiden/message_handler.py
raiden/network/discovery.py
raiden/network/sockfactory.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/network/transport/udp/udp_transport.py

Part of #3798
```
mypy --ignore-missing-imports raiden/network/transport|grep -v raiden.tests|wc -l
15
mypy --ignore-missing-imports raiden/network/transport|grep -v raiden.tests|wc -l
0
```
Please especially check the sanity of the commits:
- `Silence mypy`

Mypy fixes for `raiden/network/transport`

---

Makefile
raiden/app.py
raiden/utils/smart_contracts.py
setup.cfg

Part of #3798
This fixes the remaining 3 mypy errors in the main codebase, yay!
This also enables `mypy raiden --ignore-missing-imports` in `make lint`.
Note however, that there are still `~301` remaining errors in the tests.

Mypy last codebase fixes

---

raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/utils/typing.py

The current update transfer method in the token network proxy is utterly unnecessarily complex, this PR does a few changes:
- Remove some unused methods
- Properly handle state pruning by relying on exceptions (explanation in the comments)
- Reduce the number of RPC calls by removing unnecessary indirection
- Streamlines the logic by:
- Removing indirection
- raising the exception *where the check is done*, this means we don't have to spend time digging through the logs to understand why an exception was raised, and reduce the changes for some errors (like not raising the exception)
- split the the checks for unsuccessful transaction execution and unsuccessful gas estimation

Token network update transfer

---

raiden/network/utils.py
raiden/tests/conftest.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transport.py
raiden/ui/cli.py
tools/parallel_tests.sh

psutils cannot be used for mac, however it works reliably in the CI
system. The solution based on socket bind/TIME_WAIT is flaky and leads
to multiple build failures a day. This adds back the psutils for
non-macos systems only, the goal is to decrease the number of flaky
build failures.
Note: The problem may persist for MacOS systems, since SO_REUSEADDR
behaves differently across Unixes, ref:
https://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

Reintroduced psutils based port generator

---

raiden/blockchain_events_handler.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/storage/restore.py
raiden/storage/sqlite.py
raiden/storage/wal.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/unit/test_raiden_event_handler.py
raiden/tests/unit/test_wal.py
raiden/tests/utils/protocol.py
raiden/transfer/architecture.py
raiden/waiting.py

The event handler for a ContractSendChannelBatchUnlock needs to load the
channel's data from the ChainState. However the event handler and the
state change dispatch are /not/ synchronized, meaning that once the
event handler has a chance to run other events may have been processed
meanwhile.
Consider this:
- Node A process the contract receive channel settled event, as a
side-effect it produces a contract send batch unlock to unlock the
only pending merkle tree (say from A->B). This event is then added to
a queue of raiden events to be processed (currently the queue is not
explicit, but it exisits in the form of multiple greenlets waiting to
be executed). This means the processing of the event may take a while.
- At the same time Node B process the same event, and it too decides to
unlock …

Fixed data races on node state

---

setup.cfg

While rebasing some PRs I noticed some interaction between `black` and `isort`. 
According to https://black.readthedocs.io/en/stable/the_black_code_style.html#how-black-wraps-lines (end of section, "a compatible isort.cfg"), these settings should keep the tools happier together.

Make sure isort and black do not interfere

---

raiden/blockchain_events_handler.py
raiden/network/proxies/utils.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/utils/network.py
raiden/tests/utils/transfer.py

~Merge after #3961~
Handle pruned data on channel settle event
The handler for the channel settle blockchain event may be
executed long after the event happened. This may lead to errors because
the node has to query the blockchain to recover th locksroot, and by
default it uses the block at which the event was emitted.
This adds a exception handler which just retries the query using the
latest block. The rationale is that it is preferrable to have the
contract receive channel settle with the correct data, which is
available at the block in which settle was called. However, there is no
risk of loss of funds if the data is not recovered, so in order to
continue the node's operation if the emitting block was pruned, then a
new query is done using latest.
Fixes #3856 .

Fix for settle blockchain event handler

---

Makefile

A little bit less duplication, and the nice side effect that mypy runs earlier during `lint`.

Use mypy target in lint

---

raiden/app.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/cli/test_cli_development.py
raiden/tests/integration/cli/test_cli_production.py
raiden/tests/integration/cli/util.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/utils/mocks.py
raiden/tests/utils/network.py
raiden/ui/app.py
raiden/utils/http.py
raiden/utils/runnable.py

Fixes: #3765 (see there for a detailed explanation what's happening)
This also fixes a whole bunch of the cli tests which were silently failing due to pexpect timeouts being ignored with just a print.

Fix global room use in Matrix transport

---

raiden/tests/unit/test_channelstate.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py

Part of #3996 
This adds a new event `EventRouteFailed` and emits it when a `RefundTransfer` reaches the initiator and therefore a route didn't work.
This will be used to trigger route feedback to the PFS.
The second commit renames `refund_transfer_matches_received` to `refund_transfer_matches_transfer` which fits usage better.

Add and emit EventRouteFailed

---

raiden/tests/integration/long_running/test_settlement.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/unit/transfer/test_channel.py
raiden/tests/utils/factories.py
raiden/transfer/channel.py

the channel state must be cleared only after all unlocks have been done.
After the close/updateTransfer/settle cycle, there are three
scenarios:
- None of the participants had pending locks, so both merkle trees are
empty and the channel can be cleared at settle time
- One of the participants had pending locks, this may be the current
node or its partner. Under this case the channel should be cleared
after the only unlock.
- Both partcipants had pending locks. In this case the channel should be
cleared after both unlocks.
To implement the above this is changing the `onchain_locksroot`
attribute during ContractReceiveChannelUnlock, and if both locksroots
are EMPTY then the channel can be safely cleared.
fixes: #4024

fixed channel state clearing

---

.circleci/config.yml

This should be enough to trigger the `nightly` image creation.
Variable `NIGHTLY_BUILD_TRIGGER` was added via circle-ci web app.

Add docker hub build trigger to nightly workflow.

---

.circleci/config.yml

This seems to work in general, however there is some strange behavior:
The codecov website shows 100% coverage for each flag (unit, fuzz or integration test), but the overall coverage is fine. I'm not sure if this just happens because it's the first time this is measured or something is wrong with this PR
I'm not sure either if we need the finalize step, but I guess it's needed for the later tasks.

Submit code coverage for different test types with flags

---

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/factories.py
raiden/tests/utils/transfer.py

- Remove duplicated setup code in `test_initiatorstate.py`
- Test hitherto untested paths in initiator and mediator modules
Closes #3953

Improvements to mediated_transfer unit tests

---

Makefile
pylintrc

Pylint now uses all intended settings even when run without command line
arguments. This is done by:
* renaming .pylint.rc to pylintrc (the default config file name)
* adding the gevent checker in the config file

Make pylint pick up all settings by default

---

tools/test_and_report.sh

This adds a script that intends to make it easier to check test coverage
locally. Without any configuration
tools/test_and_reports.sh
will run all `unit` and `fuzz` tests from raiden, create the
`coverage` html report and open it in the default browser.
Configuration is done entirely through environment variables. Most
interesting may be
- `ONLY`: given a complete path to a python module, it will generate the
report for only this module (if given, it will by default only open this
report).
- `SUITE`: allows to only run specific test paths (default
`raiden/tests/unit raiden/tests/fuzz`)
- `OPEN`: allows to configure the browser for display (default
`xdg-open` on `linux`, `open` on `Darwin`)
More examples can be found inside the script.

Add tool for creating local coverage html reports

---

raiden/message_handler.py
raiden/network/pathfinding.py
raiden/raiden_service.py
raiden/routing.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_tokennetwork.py

This commit adds handling for the feedback token returned from the PFS
and adapts the tests accordingly.
Part of #3996

Handle feedback token from PFS

---

raiden/tests/integration/long_running/test_settlement.py
raiden/tests/unit/test_mtree.py
raiden/tests/unit/transfer/test_channel.py
raiden/transfer/channel.py
raiden/transfer/merkle_tree.py

Task 3 of #3993 
Test formerly untested branches of channel.py and remove some dead code paths.
**Edit**: now at 90% https://codecov.io/gh/raiden-network/raiden/pull/4014/src/raiden/transfer/channel.py?before=raiden/transfer/channel.py *phew*

Coverage raiden transfer channel

---

raiden/app.py
raiden/network/pathfinding.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_low_capacity.yaml
raiden/tests/scenarios/pfs7_simple_path_rewards.yaml
raiden/tests/unit/test_cli.py
raiden/tests/unit/test_startup.py
raiden/tests/utils/mocks.py
raiden/tests/utils/smartcontracts.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/ui/startup.py
raiden/utils/cli.py

Now that the PFS includes its eth address in the `/info` endpoint response, we don't need a cli and config option to configure it anymore.
Closes #4054

Remove --pathfinding-eth-address option

---

.circleci/config.yml
raiden/network/pathfinding.py

Reverts raiden-network/raiden#4022
So codecov seems to have some problems with big projects right now: https://community.codecov.io/t/big-slowness-during-opening-pr-changes/58/6
@ulope sent them a mail, but for now we decided to revert the change.

Revert "Submit code coverage for different test types with flags"

---

raiden/network/utils.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/smoketest.py

This removes the calls to geth and parity import. This was done because parity account import hangs every so often and makes our CI flaky.
I did this because another build failed with a hanging account import: https://circleci.com/gh/raiden-network/raiden/48224#tests/containers/2

Removed parity geth account import

---

MANIFEST.in
Makefile
raiden/network/resolver/client.py
raiden/storage/migrations/v17_to_v18.py
raiden/storage/migrations/v18_to_v19.py
raiden/storage/migrations/v19_to_v20.py
raiden/storage/migrations/v21_to_v22.py
setup.py

`setuptools_scm` forcibly includes all files under version control into the sdist package, ignoring `MANIFEST.in` and `find_packages`.
This fixes this by replacing the `find_files` function with a dummy one (see `setup.py::EggInfo.__init__()`).
See pypa/setuptools_scm#190
Additionally this uncovered that we had two directories that were missing `__init__.py` files (thereby being turned into namespace packages). That lead to mypy and pylint not covering them. 
This is now also fixed here (including two bugs in migrations mypy found).

Fix sdist package

---

raiden/tests/unit/test_sqlite.py
raiden/tests/unit/transfer/test_utils.py

Some additional unit tests to increase the coverage some small modules:
- `transfer.utils` to 92%
- `transfer.secret_registry` to 100%
- `transfer.identifiers` to 81% 
The still uncovered statements in `transfer.identifiers` will mostly be removed with the switch to dataclasses.
Closes #3910.

Increase unit test coverage of small modules in raiden/transfer/

---

raiden/storage/migrations/v21_to_v22.py
raiden/storage/sqlite.py
raiden/tests/unit/storage/migrations/data/v21_statechanges.json
raiden/tests/unit/storage/test_storage.py

This fixes several bugs that occured in the `v21_to_v22` migration:
During the migration of state changes, some `ContractReceiveBatchUnlock` instances are queued for deletion (because the user is not part of the unlock). This failed the constraint checking which previously stated that all `ContractReceiveBatchUnlock` need to have a valid canonical identifier.
This PR fixes the constraint checking by skipping deleted state changes.
I added testdata to cover the case for deleting unrelated `ContractReceiveBatchUnlock`
The function to delete state changes incorrectly operated on the table `state_events`.
Some `SQLiteStorage` manipulation functions incorrectly introduced a second transaction context. This became a problem when trying to rollback after an error.
This PR removes the extra `with …

Fix v21-v22 migration and fix sqlite transaction model

---

raiden/tests/integration/rpc/assumptions/test_rpc_call_assumptions.py
raiden/tests/smart_contracts/RpcTest.sol

An exception must be raised if the smart was not deployed at the given block.

Assumption tests for bad output

---

.circleci/config.yml
raiden/network/utils.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transport.py
raiden/ui/cli.py

This adds the option `--report-path` to the `raiden smoketest` command. It allows to optionally configure a path for the report file.
We use this option, to store the smoketest artifacts on CircleCI runs.
This fixes #4051

Store smoketest artifacts on CircleCI

---

Makefile

The clean-pyc rule should not touch vim's backup files. [skip ci]

Maintaining vim's backup file around

---

.circleci/config.yml
.coveragerc
raiden/tests/unit/transfer/mediated_transfer/test_state_and_state_change.py
raiden/tests/unit/transfer/test_events.py

Test runtime type checks and argument sanity checks in three modules and ignore all `if TYPE_CHECKING` blocks and `repr` methods in coverage reports.
Unit test coverage improvement:
`raiden.transfer.events` from 87% to 91%
`raiden.transfer.mediated_transfer.state` from 86% to 100%
`raiden.transfer.mediated_transfer.state_change` from 87% to 100%
Closes #3907
Closes #3950 
Closes #3951

More unit test coverage

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml

To avoid flakiness if blocktimes increase and to optimize the time it takes to run the scenarios

use blocks instead of seconds for wait in ms scenarios

---

raiden/raiden_service.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/transfer/mediated_transfer/test_events.py
raiden/transfer/mediated_transfer/state.py

As commented here: https://github.com/raiden-network/raiden/pull/3969#discussion_r285510704
> I checked this point out. Most of the disable=E1101 were added because partner_state and our_state are defined as field(repr=False). However, i would argue that setting them to be included in repr would be a bit too much because of the amount of data that will end up being logged.
Do you think we should accept this and remove field assignment to those attributes?
@hackaugusto

Dataclasses - Remove some disable E1101

---

requirements.txt

The version number was missing an `r` in `rc1`. Also update to `rc2`,
which includes a fix required by the services.

Fix and update marshmallow-dataclasses dependency

---

raiden/tests/integration/cli/conftest.py
raiden/tests/utils/smoketest.py
raiden/ui/cli.py

This PR:
1. Expands the block covered by the debug flag for smoketests
1. removed code that only made sense when udp was a transport
1. Passes some arguments explicitly instead of using a dictionary
1. flattens the logical depth of a smoketest.
Instead of:
- raiden.ui.cli:smoketest
- setup_testchain_and_raiden / setup_testchain / setup_raiden
- matrix_server_starter
- run_smoketest
- redirect_stdout
- smoketest_perform_tests
it does:
- raiden.ui.cli:smoketest
- redirect_stdout / setup_testchain / matrix_server_starter
- run_smoketest
Which should a bit easier to follow

Simplify smoketest

---

constraints.txt

I missed that in eb4a9948b8bf64d9b1d2a0f81b8b4d672be78f87. A CI check for these inconsistencies would be nice. Didn't @hackaugusto provide one at some point?

Update constraints after changing requirements.txt

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/factories.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py

Both the initiator and mediator had a function next_channel_from_routes.
This commit unifies them in the channel module.

Unify next_channel_from_routes for initiator and mediator

---

.gitignore
raiden/raiden_service.py
raiden/routing.py
raiden/tests/fuzz/test_state_changes.py
raiden/tests/unit/api/test_api.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/tests/unit/transfer/mediated_transfer/test_state_and_state_change.py
raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/tests/utils/factories.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/state.py

This PR adds a new state that stores complete routes for a payment. This is used for the initiator and mediator and will be used for source routing and routing feedback.
The new state is called `RouteState`  and stores a list of addresses, from initiator/mediator to the target. A different state that was used before to track state linked to a specific channel was renamed to `HopState` in the hope that this is more intuitive.

Store complete routes in Initiator

---

raiden/network/proxies/README.md
raiden/network/proxies/payment_channel.py

This just made the checks in the payment channel constructor stricter and removed an outdated comment from the README

Small changes to payment channel proxy

---

raiden/transfer/views.py

and not None. That was clear from the assertion in the function,
but the type annotation stated something else.
This commit changes the type annotation according to the assertion.

secret_from_transfer_task takes a TransferTask

---

raiden/constants.py
raiden/message_handler.py
raiden/raiden_service.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/views.py

All other constants that are named EMPTY_* have non-zero length and
have zeros in it. I also want an EMPTY_SECRET that has 32 bytes of
zeros.
So I rename EMPTY_SECRET = b"" into ABSENT_SECRET.  This value is
currently being used to indicate the absense of the secret.
https://github.com/raiden-network/raiden/issues/3944 keeps track of
replacing ABSENT_SECRET with None.

Rename EMPTY_SECRET into ABSENT_SECRET

---

raiden/messages.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_binary_encoding.py
raiden/tests/unit/test_messages.py

Also remove the corresponding tests and the support for hex-encoded
messages in the matrix transport.

Remove `unpack` method from messages

---

raiden/tests/unit/test_cli.py
raiden/ui/cli.py
raiden/utils/__init__.py

Useful for debugging as well as for the the scenario player.
(Also adds a hidden convenience `--version` flag to the cli)

 Include DB version number in `version` subcommand output 

---

raiden/tests/integration/cli/conftest.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/utils/ci.py
raiden/tests/utils/smoketest.py
raiden/ui/cli.py
raiden/ui/runners.py

Saving the logs of the ethereum node and the raiden nodes to figure out why some tests are flaky. 
Example: https://circleci.com/gh/raiden-network/raiden/52357#tests/containers/16

Save cli tests logs

---

raiden/message_handler.py
raiden/network/pathfinding.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/unit/api/test_api.py
raiden/tests/unit/api/test_api_events.py
raiden/tests/unit/test_operators.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/utils/factories.py
raiden/tests/utils/mocks.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/state.py
raiden/ui/app.py

Final pieces of the client side routing feedback.
This adds:
- A mapping `route_to_feeback_token` to the `RaidenService` in which the feedback token for routes are stored (only when the PFS is used)
- The `PFSFeedbackEventHandler`, which handles PFS feedback (only enabled when PFS is enabled).
- A function `post_pfs_feedback` which sends feedback to the PFS
Fixes #3996

Track feedback token for routes, add PFSFeedbackEventHandler

---

raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/proxies/utils.py

Consistent logging for transaction. Every transaction will log before and after sending the transaction, with success or the failing exception. This also uses changes to checksumed addresses instead of pex and standardize the log entries (every call site has `node` and `contract` to identify the node on CI)

Log transactions

---

raiden/api/rest.py
raiden/raiden_event_handler.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py

the raiden_event_handler now returns to the payment rest layer an instance of EventPaymentSentFailed or EventPaymentSentSuccess. Better handling for error situation and allow the failure reason to be provided back to the caller.

PR - Better handling of async_result (payment_done)

---

raiden/tests/conftest.py

When modules are already imported, pytest can't rewrite their
assertions. To avoid this, just do the rewrite before all imports.

Avoid test warning by doing pytest rewrite first

---

.unittest-coveragerc
constraints-dev.txt
raiden/tests/conftest.py
raiden/tests/fixtures/variables.py
raiden/tests/unit/test_accounts.py
raiden/tests/utils/transport.py
raiden/utils/http.py
requirements-dev.txt

Use pytest-xdist for parallel test execution instead of tools/parallel_tests.sh. The only reason we didn't do this before was that gevent monkeypatching broke xdist. This is avoided by reducing monkeypatching.
We should be able to leverage this in CircleCI to cut both our runtime and our costs significantly, but I had problems with some tests which I couldn't reproduce locally as well as problems with the coverage generation. So the xdist is for local execution only at this point.

Parallel tests with xdist

---

raiden/tests/utils/mocks.py
raiden/ui/startup.py

In #4141 we added a check between the raiden and PFS token network
registry settings. The check only worked for the case where
`tokennetwork_registry_contract_address` was explicitly given.

Fix token_network registry check

---

raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/utils/mocks.py

`s/route_to_feeback_token/route_to_feedback_token/`

Fix variable name typo

---

pylintrc
raiden/api/python.py
raiden/app.py
raiden/blockchain_events_handler.py
raiden/connection_manager.py
raiden/encoding/messages.py
raiden/message_handler.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/rpc/client.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/routing.py
raiden/storage/wal.py
raiden/tasks.py
raiden/tests/utils/eth_node.py
raiden/utils/filters.py
raiden/waiting.py

Pylint seems to require all constants to be uppercase. By adding `log`
to the "good names" in `pylintrc`, we can make an exception for the
logger instances.
This saves us some noise from the logger constructors, as we don't need
to disable the name check individually for every module.

Add `log` to the pylint allowed constant names

---

raiden/ui/cli.py

The `raiden.tests.utils.transport` module imports a bunch of dev only requirements (e.g. twisted). Therefore we shouldn't import it at the module level and instead only in the smoketest itself.

Move smoketetst utility import into function

---

.unittest-coveragerc
raiden/api/python.py
raiden/api/rest.py
raiden/blockchain/events.py
raiden/blockchain_events_handler.py
raiden/connection_manager.py
raiden/encoding/encoders.py
raiden/messages.py
raiden/network/blockchain_service.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/raiden_event_handler.py
raiden/storage/restore.py
raiden/tasks.py
raiden/tests/utils/transfer.py
raiden/transfer/architecture.py
raiden/transfer/identifiers.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/secret_registry.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/views.py
raiden/utils/echo_node.py
raiden/utils/timeout.py
raiden/utils/typing.py
raiden/waiting.py

Adds the following parts of the code to be omitted in unit test coverage measurement:
- runtime typechecks (Introduces a `typecheck` function too to reduce the amount of boilderplate code and be able to find the checks in the code)
- classes that have a direct or indirect attribute of type `RaidenService`
- functions that take arguments of a complex type and are too small to be split (mainly wrappers and dispatchers, more of these wil be omitted in the following pull requests.)
Coverage increase: 64% to 72%.

Mark code to be omitted in unit test coverage report

---

raiden/raiden_service.py
raiden/storage/sqlite.py
raiden/tests/unit/test_upgrade.py
raiden/utils/upgrades.py

This fixes the following error:
```python
Exception ignored in: <function SQLiteStorage.__del__ at 0x7f1b809158c8>                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                                            
File "/home/karl/raiden/raiden/storage/sqlite.py", line 573, in __del__ …
```

Forcing the storage to be `close`d manually

---

raiden/raiden_service.py
raiden/tests/unit/transfer/test_views.py
raiden/tests/utils/factories.py
raiden/transfer/views.py

Task 2 of #3993 
Apart from implementing tests for previously untested branches, this also removes some dead code from views.py and should push coverage to the target of >=90%.
**Edit** now at 91%

Coverage raiden transfer views

---

raiden/blockchain_events_handler.py
raiden/messages.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_messages.py

This if the first step towards using the new FeeUpdate message. The following things are left out on purpose and will follow in the next PRs:
- increasing nonce to avoid replay attacks
- using proportional or imbalance fee
- not sending the message depending on privacy settings
- removal of mediation fee from `UpdatePFS` message
Relates to https://github.com/raiden-network/raiden/issues/3542

Send new UpdateFee message to PFS via matrix

---

raiden/network/rpc/client.py
tools/gas_cost_measures.py
tools/startcluster.py
tools/transfer_eth.py

I did this because I got the following linting error from
.circleci/enforce_decreasing_lint_errors.sh in CI:
```
> tools/gas_cost_measures.py:179: error: Argument "additional_hash" to
"pack_balance_proof" has incompatible type "bytes"; expected
"AdditionalHash"
> tools/startcluster.py:40: error: Argument "rpc_port" to
"EthNodeDescription" has incompatible type "int"; expected "Port"
> tools/startcluster.py:40: error: Argument "p2p_port" to
"EthNodeDescription" has incompatible type "int"; expected "Port"
> tools/startcluster.py:55: error: Argument "chain_id" to
"GenesisDescription" has incompatible type "int"; expected "ChainID"
> tools/startcluster.py:60: error: Argument "verbosity" to
"run_private_blockchain" has incompatible type "int"; expected "str"
> tools/startcluster.py:60: error: …
```

Improve typing in `tools`

---

.circleci/enforce_decreasing_lint_errors.sh

The comment in the script has an explanation/example

develop should not fail if lint errors increase

---

raiden/tests/unit/fixtures.py
raiden/tests/unit/transfer/test_node.py
raiden/tests/unit/transfer/test_views.py
raiden/transfer/node.py
raiden/transfer/state_change.py
raiden/transfer/token_network.py
raiden/transfer/views.py

Task 1 of #3993 
Apart from implementing tests for previously untested branches, this also removes some dead code from `node.py` and should push coverage to the target of >=90%.
**Edit**: ~now at 88%~
now at 87%

Coverage raiden transfer node

---

constraints.txt
requirements.txt

Link: https://nvd.nist.gov/vuln/detail/CVE-2016-10745
@ulope Does this make sense?

Upgrade jinja2 constraint due to CVE2016-10745

---

raiden/tests/integration/rpc/assumptions/test_parity_rpc_assumptions.py
raiden/tests/integration/test_regression_parity.py

There were a few instances where it read `PRUNNING` instead of `PRUNING`...

Fix typo prunning vs pruning

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml

It works without, but we don't want to test if transactions are mined in short time.

Add 10 blocks wait for MS scenarios

---

.circleci/enforce_decreasing_lint_errors.sh
.circleci/lint_report.py

The line number should not interfere in the status of the report, only
the type and quantity of errors.
This also groups the same type of error per file.

mypy decreasing error report

---

raiden/encoding/format.py
raiden/encoding/messages.py
raiden/storage/sqlite.py
raiden/tasks.py
raiden/tests/unit/storage/test_serialization.py
raiden/tests/unit/test_encoding.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/test_waiting.py
raiden/tests/utils/factories.py

Coverage increase: Total unit test coverage 74% to 75%
`raiden.encoding.encoders` 82% to 100%
`raiden.encoding.format` 77% to 95%
`raiden.encoding.messages` 81% to 100%
`raiden.storage.restore` 79% to 100%
`raiden.storage.serialization.fields` 78% to 100%
`raiden.waiting` 33% to 100%
Closes #3878
Closes #3918
Closes #3919
Closes #3920

Some unit tests for miscellaneous modules

---

.pre-commit-config.yaml

This adds a configuration file for https://pre-commit.com/ to be used with Raiden. 
It respects all linting/styling preferences shared in the repository, and can be used voluntarily. 
If installed (see header of `.pre-commit-config.yaml`), every commit will be ensured to pass CI-side linting.

Add `.pre-commit-config.yaml`

---

raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py

This moves the `Optional` out of the description in `TransitionResult`. The idea here is that `node.transition_result` must not return `None`, while some of the state transitions for the initiator/mediator/target may.

Stricter type for TransitionResult

---

raiden/blockchain_events_handler.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/storage/restore.py
raiden/storage/sqlite.py
raiden/storage/ulid.py
raiden/storage/utils.py
raiden/storage/wal.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/test_balance_proof_check.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/unit/storage/test_ulid.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/test_upgrade.py
raiden/tests/unit/test_wal.py
raiden/tests/utils/events.py
raiden/tests/utils/factories.py
raiden/utils/typing.py
requirements.txt
setup.cfg
tools/debugging/replay_wal.py

This PR ended being a bigger than what I wanted. Here is what it does:
- Remove the dependency on `lastrowid` [example](https://github.com/raiden-network/raiden/blob/0ae7627d8e484c78b35f37e3b2f5d660b5ca670d/raiden/storage/sqlite.py#L146), which [requires synchronization](https://github.com/raiden-network/raiden/blob/0ae7627d8e484c78b35f37e3b2f5d660b5ca670d/raiden/storage/sqlite.py#L89-L102) and [does not work with `executemany`](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.lastrowid).
- This removed some race conditions, which on the current code base were unlikely to be hit. ([Inserts that are not protected by the write lock](https://github.com/raiden-network/raiden/blob/0ae7627d8e484c78b35f37e3b2f5d660b5ca670d/raiden/storage/sqlite.py#L113-L118) which may result in the …

Introducing ULIDs

---

raiden/tests/integration/api/test_restapi.py

This is a blind shot at fixing the flakyness of 
```
raiden/tests/integration/api/test_restapi.py::test_api_withdraw[matrix-False-10001-2] Too long with no output (exceeded 10m0s)
```
In the test parametrization, there were two runs with `deposit=1000` configured (the intended meaning probably was a deposit of `1000` for both of the `number_of_nodes=2` nodes).
I removed the second `1000`, so this test will run only once -- this should at least reduce flakyism by 50% :tada:

Remove unnecessary second test run

---

constraints.txt

That was forgotten when upgrading flask.

Fix constraint for Flask 1.0.3

---

raiden/network/pathfinding.py
raiden/raiden_event_handler.py
raiden/routing.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_startup.py
raiden/tests/utils/mocks.py
raiden/tests/utils/smartcontracts.py
raiden/ui/app.py
raiden/ui/startup.py

This PR introduces dataclasses for bits of data that are handled together when interacting with the PFS. Besides better readability (in my opinion) this also gives us better type checking (before there was a weird mix of hex and canonical address for example)
- `PFSInfo` includes all the info the PFS returns
- `PFSConfig` includes all client side PFS settings as well as the currently known settings of the PFS (which will be required in the future)
- `IOU` collects all information needed for a PFS payment, as well as some signing and serialisation code.
The rest of the changes are test updates.
Part of https://github.com/raiden-network/raiden/issues/3735
Prerequisite for https://github.com/raiden-network/raiden/issues/4100

Clearify PFS interaction code

---

raiden/raiden_event_handler.py

Otherwise a log message about unknown events is thrown.

 Add `EventRouteFailed` to UNEVENTFUL_EVENTS

---

CONTRIBUTING.md

We're not using Travis anymore and that part does not apply to CircleCI,
which only supports `[skip ci]`.

Remove Travis-specific part of `CONTRIBUTING.md`

---

raiden/tests/conftest.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/utils/ci.py

This also fixed a bug in the get_artifacts_storage usage, which added
the test name twice in local runs.
fixes #4234

Separate debug log for each test

---

raiden/network/proxies/user_deposit.py

because the global constants in raiden_contracts.constants are obsolete.
The change mimicks what's been done in the TokenNetwork proxy in 75d04070ef .

UserDeposit proxy now uses gas.json

---

raiden/network/proxies/token_network.py
raiden/utils/gas_reserve.py

because the gas measurements in raiden_contracts.constants are old.

Use gas.json contents not raiden_contracts.constants

---

raiden/messages.py
raiden/tests/integration/network/proxies/__init__.py
raiden/tests/unit/test_utils.py
raiden/utils/packing.py
raiden/utils/signing.py

This allows
* easier matching between value and type
* more concise code
* easier editing

`pack_data` takes tuples instead of two lists

---

raiden/tests/conftest.py
raiden/tests/utils/ci.py

Fix the build. Some of the tests parametrize fixtures are very long when encoded as strings, resulting in build failures because of the path length.

Fix test logpath size

---

raiden/blockchain_events_handler.py
raiden/encoding/messages.py
raiden/messages.py
raiden/services.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_messages.py

This means:
`FeeUpdate` -> `PFSFeeUpdate`
`UpdatePFS` -> `PFSCapacityUpdate`

Consistently name PFS messages

---

raiden/blockchain/events.py
raiden/blockchain_events_handler.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/tests/unit/test_channelstate.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py

Based on @hackaugusto feedback in #4130

Withdraw fixes

---

raiden/network/pathfinding.py
raiden/raiden_event_handler.py
raiden/tests/unit/test_pfs_integration.py

Only send routing feedback when the routing mode is not `PRIVATE`

Take privacy into account when sending feedback

---

Makefile
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

Due to an unintentional dependency upgrade of psycopg2 our nightly macOS builds failed 
(see #3745 for details).
Drive-by fix: Developer local requirements from `requirements-local.txt` could be mangled with repeated runs of `make install-dev`.

Fix macOS nightly build

---

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/test_source_routing.py
raiden/tests/utils/factories.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/node.py
raiden/transfer/routes.py

Resolves #4036 
Resolves #4254 
Resolves #4255 
When looking for routes to use for initiating a mediated transfer, we now check the status of the partner's node (if it is online, if it is has not been part of a refunded transfer, etc). 
The `MediatedTransferState` now includes information for a list of `refunded_channels`, which gets updated as part of the handling of a refund transfer. This information can then be used by the `mediate_transfer` function in determining which route to use.
The PR also does some refactoring related to functions that calculate/filter routes, and is located on `raiden.transfer.routes.py`. These functions are then used by all initiator- and mediator-related functions that need to define routes to be used.

Check partner's network availability when initiating mediated transfers

---

.dockerignore
Makefile
docker/build.Dockerfile

With the introduction of the new deps system a check for an active v(irtual)env was introduced. 
This failed inside the bundle docker container since it didn't use a venv previously.

Fix docker based nightly builds

---

raiden/blockchain_events_handler.py
raiden/raiden_service.py
raiden/services.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_blockchain_events_handler.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/unit/transfer/test_channel.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/node.py
raiden/transfer/state_change.py
raiden/transfer/token_network.py

This PR updates the balance fees after a deposit or withdraw for the channel has been received. This is done by emitting `ActionChannelUpdateFee` (renamed from `ActionChannelSetFee`) state changes when such a blockchain event is received.
Part of #3542

Recalc imbalance fees after balance change

---

raiden/tests/integration/test_send_queued_messages.py

I don't think this is a good idea, but it's better than blocking all PRs
because they don't get through CI.
The ticket to investigate this is https://github.com/raiden-network/raiden/issues/4312.

Increase timeout for `test_send_queued_messages`.

---

.circleci/config.yml

CircleCI does not like wildcards in cache dirs. That only works for
workspaces.
Proof that this works:
* First run: https://circleci.com/gh/raiden-network/raiden/60394
* Second run: https://circleci.com/gh/raiden-network/raiden/60398

Fix CI caching directories

---

raiden/tests/integration/cli/conftest.py
raiden/ui/cli.py

Since the internal routing is deprecated, we want to use PFS routing by default.

Use PFS routing by default

---

raiden/messages.py

If found @hackaugusto's comment at https://github.com/raiden-network/raiden/issues/4297 informative, so I added it to the docstring.
[skip tests]

Add docstring to `EnvelopeMessage`

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_low_capacity.yaml
raiden/tests/scenarios/pfs7_simple_path_rewards.yaml

This allows for the scenarios to use a local venv installation instead of relying on the nightlies to build.

use local venv instead of nightlies [skip tests]

---

raiden/tests/integration/test_send_queued_messages.py

When a node is sending a transfer forward is does a connectivety check
for each available route, and then offline partners are then filtered
out. The test had a flaky condition that would cause the presence
change for `app1.stop()` to be processed, which resulted in an empty
transfer queue, leading to a failure on the assert.

Fixed race condition on test_send_queued

---

raiden/network/proxies/token.py

Revisit the error handling in `Token.approve()` and `Token.transfer()`. There was not much to do since there are no preconditions, but the error handling after failed gas estimations and transactions was extended to check for insufficient eth and for the case when the token balance has dropped under the required amount in the time between the triggering event and the transaction.
Closes #4197 
Closes #4198

State pruning in token proxy

---

raiden/network/proxies/token_network.py
raiden/tests/integration/network/proxies/test_token_network.py

Catch possible `ValueError` due to missing block when checking the precondition. Other than that the error handling in `new_netting_channel` is already up to date.
Closes #4199

State pruning in TokenNetwork.new_netting_channel

---

raiden/network/proxies/token_network.py
raiden/utils/gas_reserve.py

As suggested by @hackaugusto in the review to #4229, use `channel_operations_lock` for channel creation too.

Simplify handling of concurrent channel creation attempts

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt

It seems that 0.3.1 got deleted from pypi, so all builds will fail if
they are pinned to that version. *sigh*
https://pypi.org/project/flake8-tuple/#history

Upgrade flake8-tuple to 0.4.0

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/transfer/mediated_transfer/mediator.py

The flexible mediation fees are meant to be calculated for both the incoming and the outgoing channel. Previously, we only cared for the outgoing channel.
Closes https://github.com/raiden-network/raiden/issues/3542.

Use `FeeSchedule` for incoming channel

---

raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/network/transport/test_matrix_transport.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

This unblocks PR while we work at fixing the flaky tests. Tickets for
that have been created:
https://github.com/raiden-network/raiden/issues/4340
https://github.com/raiden-network/raiden/issues/4338
https://github.com/raiden-network/raiden/issues/4337
https://github.com/raiden-network/raiden/issues/4336
To get it to build I had to include https://github.com/raiden-network/raiden/pull/4339 in this PR, which I could not merge before, because it does not pass the flaky tests.

Add flaky package and mark flaky tests

---

raiden/tests/scenarios/ms3_simple_monitoring.yaml

Changes MS3 scenario such that the scenario succeeds even if the final assertion fails (as intended by the author). In this scenario, the monitoring service cannot claim a reward, since the node came back online and updated the channel information itself, there was no work for the monitoring service

Changes MS3 scenario s.t. final claim fails

---

raiden/network/pathfinding.py
raiden/network/resolver/client.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/utils/mocks.py
raiden/tests/utils/smoketest.py
raiden/ui/sync.py

The requests module has some undercover magic of using a different implementation
depending on whether the simplejson package is installed, which makes the built-in
requests.response.json() method unreliable
To avoid this issue, we are removing all calls to response.json() and parsing the
response using python's built-in json module.
Resolves #4174

Change method of getting json data out of HTTP requests

---

.circleci/config.yml
raiden/tests/conftest.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/utils/ci.py
raiden/tests/utils/tests.py

cb2558342318f11aaee75db0ce5715519e28bc4a fixed the path name for the unit tests but broke it for the integration tests. This adds a tool to compute a shortened path, if necessary, and uses it consistently.

ci: grouped logs into a single folder

---

raiden/messages.py

Some additional cleanup after the refactoring in https://github.com/raiden-network/raiden/pull/4284.
This changes the signatures of all `EnvelopeMessage`s. So if that is a problem, block this PR!

Cleanup after signing changed

---

raiden/api/python.py
raiden/blockchain/decode.py
raiden/blockchain_events_handler.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_data/db_statechanges.json
raiden/tests/unit/test_state.py
raiden/tests/utils/network.py
raiden/transfer/channel.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/token_network.py
raiden/waiting.py

This was inconsistent in the codebase and should be closer to how stuff
is called in the contracts afterwards.

Rename occurrences of newbalance to deposit

---

raiden/messages.py
raiden/tests/unit/test_messages.py
raiden/utils/packing.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

The reward proof definition has changed in the smart contracts
(https://github.com/raiden-network/raiden-contracts/pull/1119).
Using the `pack_reward_proof` function from raiden-contracts will make
it easier to fix signature mismatches in the future since we will get a
mypy error instead of a signature error when the signature changes the
next time.

Update contracts and reward_proof

---

raiden/settings.py

I forgot to change these in 12d4d7977e04feef4de79ba7cce6bcb266833d05.
The DEVELOPMENT_CONTRACT_VERSION is now set to always reflect the
installed contracts version.

Update contracts versions in `raiden/settings.py`

---

raiden/network/pathfinding.py
raiden/network/utils.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/unit/test_pfs_integration.py

Substitute calls for response.json() for one that calls python's built-in json.

---

raiden/network/transport/matrix/transport.py

If multiple global messages were to be sent to a single recipient during startup the `_global_send_queue.join()` call would block forever since the number of calls to `task_done()` was unbalanced with the number of items in the queue.
Thanks @offerm for the bug report and investigation.
Fixes: #4383
A regression test for this case will be added in a separate PR.

Fix global queue handling during transport startup

---

raiden/transfer/mediated_transfer/mediation_fee.py

Counter-intuitively, mypy's `NewType`s don't get replaced by their base
class during runtime but by a dummy function just returning their
argument. So a call like `x = FeeAmount(1.1)` will return a float
despite `FeeAmount` having `int` as a base type.
Fixes https://github.com/raiden-network/raiden/issues/4373.
This would not have happened if `FeeAmount` was an actual subclass of
`int`. If the performance implications are acceptable, that sounds like
a better solution.

Cast imbalance fees to `int` and then `FeeAmount`

---

raiden/raiden_service.py

_initialize_messages_queues is called before transport.start() s.t. the call has no effect. Start_health_check_for will be called after transport.start().

Remove start_health_check_for call during _initialize_messages_queues.

---

raiden/exceptions.py
raiden/network/transport/matrix/utils.py
raiden/storage/serialization/serializer.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_serialization.py
raiden/tests/unit/test_wal.py

Reraise any exceptions during (de-)serialization as a unified `SerializationError`.
Fix the handling of this in the Transport since the previous implementation was broken (and therefore presented a DoS vector) with the move to dataclasses.

 Tighten (de-)serialization error handling

---

raiden/tests/integration/transfer/test_mediatedtransfer.py

The test was not waiting for the mediator to synchronize with the first
transfer, so this was possible:
- App0 sends LockedTransfer to App1, which forwards it to App2
- App2 requests the secret and reveals it backwards
- App0 and App1 send the unlock (but none receive yet)
- App2 receives the unlock
At the point above, from App0's perspective the transfer is completed,
the unlock has been sent. Same thing for the App2, the Unlock has been
received, however that is not the same thing for App1.
If the second transfer is started fast enough, it is possible that App1
will reject the payment because the channel App1->App0 doesn't yet have
enough capacity (the 200 tokens are still locked from App1's
perspective).

Fixed race condition on test with entire deposit

---

raiden/api/python.py
raiden/connection_manager.py
raiden/tests/integration/long_running/test_token_networks.py

`test_participant_selection` had become flaky due to two inconsistencies we introduced during the recent reworking of the contract proxies. (State pruning issues)
Fixes #4340
Also removes an obsolete todo comment from the early matrix days and resolves another todo related to issue #4220.

Avoid crashes in test_participant_selection

---

raiden/tests/conftest.py
raiden/tests/integration/cli/test_cli_production.py
setup.cfg

That configuration flag was enabled because the fixture teardown for the
parity private chain was hanging. The hanging caused timeouts for some
tests, which made the build flaky. Because of this the flag was added,
making the test fail only if running it took too long.
The problem with the above approach is that it does not remove the
flakyness of the fixture. The fixture teardown may still hang, and
without the timeout exception it will be killed by the continious
integrations timeout, which does not produce logs, making it hard to
debug the issue.

Reverted pytest-timeout timeout_func_only

---

raiden/tests/integration/long_running/test_stress.py

this just marks the test as flaky

mark stress test as flaky #4380

---

raiden/blockchain/events.py
raiden/blockchain/exceptions.py
raiden/exceptions.py

~review/merge after #4389~
This splits the decoding failures into two, internal and external. The first is considered unrecoverable while the later is recoverable. The exception for external smart contracts is not used but it was added to make it clear for future usage that the two exceptions are not the same.

Blockchain exception

---

raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
raiden/tests/smart_contracts/RpcWithStorageTest.sol

This assumption test shows that neither Geth nor Parity takes the
pending block into account.

Added test for the estimate gas behavior.

---

raiden/utils/http.py

This adds logs around the wait_for operation and the kill methods. The
intention is to know if and when the managed processed is killed.

Extended logging for the HTTPExecutor

---

raiden/tests/conftest.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
tools/pip-compile-wrapper.py

```
Removes a corner were a timeout kills the test suite.
`pytest-timeout` uses the `pytest_runtest_protocol` hook to install and
clear the timeout handlers. The problem is that this hook does not
handle exceptions, there are a few places were an exception can be
raised and result in a build failure because pytest itself is killed.
This change makes the period of time were a timeout can be raised
shorter. This is achieve by installing the signal inside
`pytest_runtest_setup`, and uinstalling it at `pytest_runtest_teardown`.
Ideally an exception should only be raised while execution is inside
`pytest_runtest_setup`, `pytest_runtest_call` or
`pytest_runtest_teardown`, but **not** in-between these calls. However there is no
hook available for that and this change would require additional …
```

Test timeout fix

---

raiden/messages/path_finding_service.py

Using `marshmallow.fields.DateTime` should make sure we get the same
result as in the `DictSerializer` while giving the message much less
potential to trigger different code paths thus reducing the possibility
of bugs and potential attack surface.

Don't use `DictSerializer` in `_data_to_sign`

---

raiden/tests/integration/test_send_queued_messages.py
raiden/tests/utils/protocol.py

The test was waiting on the reveal secret message could be sent many
times. This adds a property to differentiate among the messages, in
order to avoid the exception from the hold event handler.

Fixed flaky test test_payment_statuses_are_restored

---

raiden/tests/conftest.py

The pytest hook to report on flaky tests was a bit overeager and always reported at least one `FLAKY` even for tests succeeding the first time.

Fix flaky test reporter

---

raiden/tests/integration/long_running/test_stress.py

The test runs into CircleCI's timeout, otherwise. This is a simple
measure to speed it up by ~20%.
Should close https://github.com/raiden-network/raiden/issues/4380.
This obsoletes and thus closes https://github.com/raiden-network/raiden/pull/4429.

Reduce the number of transfers in `test_stress`

---

raiden/tests/conftest.py

I was getting
```python
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_setup(item):
>       timeout = item.config.getvalue("timeout")
E       ValueError: no option named 'timeout'
```
when running tests locally after https://github.com/raiden-network/raiden/pull/4420. I don't see why it worked in CI, but the following changes made it work fine for me and should also be an improvement by themselves:
* `getvalue` replaced (deprecated, see
https://docs.pytest.org/en/latest/reference.html?highlight=addini#_pytest.config.Config.getvalue)
* use both values from cli and `setup.cfg`
* cast values from `setup.cfg` to int, which is necessary for them to be
actually used
* add docstring describing settings precedence

Improvements to timeout option handling

---

.circleci/config.yml
.circleci/run_tests.sh
raiden/tests/conftest.py
raiden/tests/utils/detect_failure.py
raiden/utils/debugging.py
tools/kill_if_no_output.py

```
This tool is being added to help misbehaving builds. The continuous
integration services, e.g. Travis and CircleCI, will kill the build if
the process doesn't output any data. Because the whole environment is
kill, e.g. the container or the VM is killed, there is no logs available
to debug the problem.
This tool should be used to send a user signal before the CI timeout is
reached, the test suite should run a signal handler to print debugging
data and exit. If the test suite doesn't exit in a timely manner then it
will be forcefully killed.
```

Stop tests before ci kill it

---

raiden/tests/integration/test_echo_node.py

This cleans up the tests and removes gevent.sleeps()
Fixes #3750

Unskip `test_echo_node_lottery`

---

raiden/tests/integration/long_running/test_stress.py

This causes problems with PRs as well as with the build of nightlies
Until  #4380 is fixed

Skip `test_stress` until is runs reliably

---

raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/transfer/mediated_transfer/mediation_fee.py

There were multiple problems with `calculate_imbalance_fees`:
- With a `channel_capacity` of 0 it raised an AssertionError
- With a `channel_capacity` of 1, only one grid point was calculated and
the extrema were wrong
Fixes #4446

Fix problems in `calculate_imbalance_fees`

---

raiden/tests/integration/test_echo_node.py

That wasn't fixed, we should skip it for now.
See #3750.

Skip `test_echo_node_lottery` again

---

raiden/network/proxies/token_network.py

The with block above either returns or raises an exception.
So the control never falls through the with block.
@hackaugusto: it can't.

Remove unreachable code

---

raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/cli/test_cli_development.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_send_queued_messages.py

Specifically skipped:
- test_cli_development.py::test_cli_full_init_dev - issue #4450
- integration/network/test_matrix_transport.py::test_reproduce_handle_invite_send_race_issue_3588 - issue #4379
- integration/api/test_restapi.py::test_api_withdraw - issue #4344
- integration/network/test_matrix_transport.py::test_matrix_invite_private_room_unhappy_case_2 - issue #4336
- integration/network/test_matrix_transport.py::test_matrix_invite_private_room_happy_case - issue #4338
- integration/network/test_matrix_transport.py::test_matrix_cross_server_with_load_balance - issue #4337

Skipped tests for which flaky issues have been registered in Github

---

raiden/tests/conftest.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/transport.py
setup.cfg

This is a very intricate change, it should be fairly well documented both in the commits and the code itself. tl;dr it fixes the tear down of parity nodes that can potentially take minutes.

Fix parity teardown

---

docker/build.Dockerfile

The official docker python image switched to use the latest debian `buster` release as its base.
This leads to bundles build on there not being usable on older systems.
This switches back to use the older `stretch` based images.
Refs #4414 (this is only a partial fix since even stretch is relatively new)

Use debian stretch based image to build linux bundle

---

raiden/tests/integration/cli/test_cli_development.py

The tests `test_cli_full_init_dev` and
`test_cli_manual_account_selection` failed because the existing timeouts
were too short. This is a problem of composability of timeouts, were the
outer timeout can be set without synchronizing with the inner timeouts.
What happened with the above mentioned tests is that the teardown was
expecting to have 10 seconds of time to properly cleanup the private
chain, while the complete test had only 45 seconds in total, and the
setup and test ran took 35s out of the 45s. This left the test with a
race condition were sometimes it was enough time to do a teardown, and
sometimes it was not (If this was enough time depended on the actual
time the test took to run, or if the parity process was well behaved)
Some additional edge cases existed in the timeout …

Unskip cli tests

---

raiden/transfer/channel.py
setup.cfg

Markers have to be explicitly declared, or they will raise warnings
during test execution.
See https://docs.pytest.org/en/latest/mark.html#registering-marks.

Silence pytest warning about timeout marker

---

raiden/blockchain_events_handler.py

The PFS listens to channel creation events on the blockchain. When a
channel is created the capacity is always zero and fee schedules do not
apply, since no mediation is possible. So sending this message is
unnecessary.

Don't update the PFS when creating a channel

---

raiden/constants.py
raiden/network/rpc/client.py
raiden/tests/conftest.py
raiden/tests/unit/test_cli.py
raiden/ui/checks.py
raiden/utils/ethereum_clients.py

I was just bittten by thinking the flaky tests were due to some problem
that ended up being due to geth v1.9.0. So I am adding this check on
tests to make sure that when we run the tests they are not with a
version that is not supported.
~~Not sure how to keep config.yaml with the raiden/constants.py~~
No need to. The build failing would show us that these two have fallen out of sync

Add check for highest/lowest parity/geth supported version.

---

raiden/tests/conftest.py
raiden/tests/utils/detect_failure.py

This reverts commit b3280da865cb896c99ebd775f3a813c130bc4d41.
Fixes #4479

Revert "disable output capture on signal handler"

---

requirements/requirements.in
requirements/requirements.txt

This is done only because of the Literal["foo", "boo"] construct. It
needs the typing extensions in order to exist.
Another way to go around adding this to requirements is to define all
literals in `raiden/utils/typing.py` and with an `if TYPE_CHECKING:`
change the type to `Any`.
Fix #4474

Add typing_extensions to production requirements

---

raiden/tests/integration/long_running/test_stress.py

The previous reduction didn't make the flakyness disappear. I've run this four times without having a failure in `test_stress`, so this is likely to close https://github.com/raiden-network/raiden/issues/4380.
Reducing the amount of work in the stress test this much might not be a good idea, but it *is* better than completely skipping the test.

Further reduce test_stress deposit to improve reliability

---

raiden/network/pathfinding.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/utils/mocks.py

We need to remove the "settings" info from the pfs info endpoint. It was removed from the pfs code today, see https://github.com/raiden-network/raiden-services/pull/484

Remove pfs info settings

---

.circleci/config.yml

Also support the canonical and alternate spellings of PEP440 versions.
e.g.:
- `1.2.3-rc1`
- `1.2.3.rc1`
- `1.2.3rc1`

Make CI tag regex also recognize dev builds

---

raiden/tests/utils/detect_failure.py

This just groups the logging lines into a single entry to make it easier on the eyes.

Test failure log declutter

---

raiden/api/exceptions.py
raiden/api/python.py
raiden/api/rest.py
raiden/exceptions.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/test_pythonapi.py
raiden/utils/__init__.py
raiden/utils/cli.py

~review/merge after #4389~
Changes to Address exceptions
- Split exceptions used for checksummed and binary addresses.
- Added an exception for unexisting channel, instead of using the
invalid address exception, which is misleading.
- Extended the docstring of the exceptions explaining their usage.
- Remove a try-block in the matrix transport. Andre mentioned it is not
necessary anymore.

Split address exception

---

raiden/raiden_event_handler.py

Fix #4502
A bit surprising that `mypy` didn't find that.

Fix spelling mistake in route_to_feedback_token

---

raiden/tests/integration/test_echo_node.py

Skip echo node test until the reason for flakyness is found: #3750

Skip echo node test again

---

Makefile
tools/transfer_eth.py

Just makes `transfer_eth` a bit more convinient to use.

Disable confirmation_prompt for `transfer_eth` tool

---

raiden/tests/utils/eth_node.py
raiden/utils/ethereum_clients.py

Versions >= 1.9 require `--allow-insecure-unlock` while versions before
can't take this parameter. To make the tests run on either version, we
check for the version and only add the parameter for later geth
versions.
As long as we officially support geth 1.8 it is good to have a way of
running the tests on it.

Allow running tests on geth < 1.9

---

raiden/raiden_service.py
raiden/storage/serialization/serializer.py

Having to double decode the state_changes and events while debugging is
just annoying and unecessary. This fixes that by using the
DictSerializer instead of the JSONSerializer.

Fixed double encoding on logging.

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/tests/unit/transfer/test_channel.py
raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/utils/typing.py

Replace `SuccessOrError` type alias for a proper class.
We are using currently a custom-defined `SuccessOrError` type for the cases where we need to test if a condition is valid *and* we also would like to have a message indicating *why* the condition is not true.
This `SuccessOrError` is was basically an alias to a `Tuple[bool, str]`, which did not help much in terms of programmer ergonomics (we would still have to destructure the tuple to check on the condition) and did not help much with type-enforcing.
The alternative proposed was to replace `SuccessOrError` with a simple `ErrorMsg` type and having the functions returning `Optional[ErrorMsg]`.  This could make things a bit simpler but still did not help much in the ergonomics part (e.g, the return value would be `True` whenever a …

Better error handling for `SuccessOrError` type

---

raiden/constants.py
raiden/network/proxies/secret_registry.py
raiden/raiden_service.py
raiden/tests/unit/utils/test_secrethash.py
raiden/tests/utils/factories.py
raiden/tests/utils/transfer.py
raiden/tests/utils/transport.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/state_change.py
raiden/utils/__init__.py
raiden/utils/secrethash.py

This isolates the hash function, the main goal here is to avoid getting in the habit of casting everywhere.

added sha256_secrethash

---

raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/rpc/test_client.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/transfer/test_refundtransfer.py

Sleep has been kept in:
* wait loops, there using `gevent.sleep` makes sense and is safe
* `test_token_swap`, which is skipped right no without a documented reason (https://github.com/raiden-network/raiden/blob/develop/raiden/tests/integration/test_pythonapi.py#L280-L326)
I added timeouts in many places where I removed sleeps, so that waiting for an event won't be done for unreasonably long times when the test is broken. These timeouts should be chosen generously, so that slow tests won't cause flakyness.
Closes https://github.com/raiden-network/raiden/issues/4368.

Remove `gevent.sleep` from tests

---

raiden/network/pathfinding.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/utils/smartcontracts.py
raiden/ui/startup.py

This adds additional latency to the selection process. We can later add
greenlets to do some of the setup in parallel, but for now simplicity is
more important.
Closes https://github.com/raiden-network/raiden/issues/4394.

Check fees during PFS selection

---

raiden/api/v1/encoding.py
raiden/network/proxies/token_network.py
raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/services.py
raiden/storage/sqlite.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/tests/utils/mocks.py
raiden/transfer/channel.py
raiden/transfer/state.py
tools/check_circleci_config.py
tools/debugging/json-log-to-html.py

Tests seems fine in general, however it was never adapted to the
addition of the PFSFeeUpdate message. This was added and a more fine
grained checking for which messages should be queued added.
One problem than was found after this is that two identical
PFSCapacityUpdate were queued. This was fixed by calling
update_monitoring_service_from_balance_proof directly.
Closes #3714

Fix flaky 3714

---

raiden/tests/integration/rpc/assumptions/test_geth_rpc_assumptions.py

The behaviour seems to be analogous to parity (tested with geth 1.9). So this is enough to close https://github.com/raiden-network/raiden/issues/4204.
Unfortunately, this test is really slow (~2min). I didn't find a faster way to exercise this behaviour. Maybe we should skip this test by default and only check it after major geth version changes and similar occasions? If someone finds a way to make geth prune quickly, that would be best, of course.

Add assumption test for geth pruned block handling

---

raiden/blockchain/decode.py
raiden/blockchain/events.py
raiden/blockchain/state.py
raiden/raiden_service.py
raiden/storage/wal.py
raiden/tasks.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/utils/network.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transfer.py
raiden/ui/app.py
raiden/ui/checks.py
setup.cfg

Note that the race documented in the issue itself is not possible anymore, it was fixed by 956afb28a7, that instead of arbitrarily using `latest` as the goto value https://github.com/raiden-network/raiden/commit/956afb28a72d186ef22efcef27d18d1c865568d7#diff-5fb0421ebe327aba371c460a48364cf8L88 it did a two step process, first trying the event's block number and only falling back to latest if needed https://github.com/raiden-network/raiden/commit/956afb28a72d186ef22efcef27d18d1c865568d7#diff-5fb0421ebe327aba371c460a48364cf8R217-R225 .
However, the case below was still possible:
Fixes race condition from #4344
This is a tricky race condition, it is unlikely to happen with the
current version of the code, but it is fixed by this commit neverthless.
The race condition manifests itself when the …

Fix for #4344

---

raiden/blockchain/decode.py
raiden/blockchain/state.py

Follow up for #4466
This removes the code that is pre-fetching the balance of a channel in the channel new event handler. Eventually the channel deposit will be processed and the state will updated, so this is just uncessary extra code that resulted in race conditions.

Update channel balance from events only

---

raiden/network/rpc/client.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/test_echo_node.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_matrix_presence.py
raiden/tests/unit/test_messages.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_raiden_event_handler.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/test_wal.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/tests/unit/transfer/test_channel.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/factories.py
raiden/utils/smart_contracts.py
raiden/utils/typing.py
setup.cfg

Use `check_untyped_defs = False` instead of turning everything off with
`ignore_errors = True`. Now `raiden.tests.utils` is the only package
where mypy checking is completely turned off.

More mypy type checking in tests

---

docs/changelog.rst
raiden/api/v1/encoding.py

This is a fix for #4348 
The solution is to return the *balance* instead of the *distributable*.
I'll also create a follow up issue to discuss if *distributable* should be added to the channel infos in the API, as it might be interesting for user facing tools.
Closes #4348

#4348: Return correct channel balance in API

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

Apparently having a dev[N] version suffix can't work:
https://github.com/pypa/setuptools_scm/issues/213
We are switching to a new way of testnet releases using aN as a
suffix. Stands for Alpha0, Alpha1, e.t.c.

Bump to v0.100.5a0

---

.circleci/config.yml
.circleci/enforce_decreasing_lint_errors.sh
Makefile
raiden/app.py
raiden/log_config.py
raiden/network/proxies/utils.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/raiden_service.py
raiden/tests/conftest.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_logging.py
raiden/tests/unit/test_matrix_presence.py
raiden/tests/unit/test_matrix_transport.py
raiden/ui/runners.py
raiden/utils/http.py

During transport shutdown some greenlets weren't properly being kept
track of which in combination with the long-polling used by Matrix could
lead to incorrect behaviour.
Additionally the `UserAddressManager` had no life-cycle control as well
which again could lead to reachability events appearing after transport
shutdown (esp. in tests).
This also splits the tests using a mocked matrix server out into a separate module and runs those parallel to the unit tests.
Fixes: #4336, fixes #4337, fixes: #4338, fixes #4379
(Technically) fixes #4030:
- The `ping_pong_message_success` helper now correctly emulates the raiden queues. This fulfils the requirements to properly test the transport but does need to be taken into account when testing the transports without this helper.

Fix transport life-cycle handling

---

tools/debugging/split_debug_logs.sh
tools/debugging/state_machine_report.py

Scripts take the json data from the raiden log and extracts the state machine changes + events
from a raiden log file, split by raiden node.

Add shell script + python command for integration test debugging

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

This scenario aims to test the happy path of most of the functionality of the Raiden API combined. The scenario should be pretty self explanatory and comply with how it's outlined in the spreadsheet defining the scenarios.
This should not be merged before `withdraw` functionality is merged into the SP.

Implement Basic Functionality scenario [skip ci]

---

docs/changelog.rst
raiden/api/v1/encoding.py
raiden/storage/utils.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/unit/api/test_api_events.py
raiden/tests/unit/api/test_encoding.py

The API documentation states that records that provide a timestamp should follow the ISO8601 spec.
Meanwhile, our database tables were defined as storing the default `CURRENT_TIMESTAMP` format from sqlite, which do not hold milisecond information.
This commit changes all tables to start using TIMESTAMP fields with formatted with milisecond as well.
Fixes #4560
- Safety
- Commits

Change formatting of timestamp to be closer to ISO8601

---

.circleci/config.yml
.circleci/fetch_geth_parity_solc.sh

We started to have weird build failures on CircleCI due to symlinks not being able to be created.
This makes the symlinking more robust.
/edit: Those changes definitely don't hurt but it seems the root cause was that the CI base image recently gained a pre-existing `~/.local` directory which interfered with out symlinking.

Make CI prepare-system symlinking more robust

---

raiden/raiden_service.py
raiden/storage/restore.py
raiden/storage/wal.py
raiden/tests/unit/test_wal.py
raiden/utils/logging.py
tools/debugging/state_machine_report.py

The restore logging was:
- Producing bad output, because the objects were serialized with
`__repr__`. Now the state changes are encoded as dictories and produce
parseable json.
- Not properly redacting secrets. Now the same utility used for the
normal execution of the node is also used by the recovery.
- Not logging the node address.
- Safety
-  Code …

Fixed restore logging

---

raiden/api/python.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/test_blockchainservice.py
raiden/tests/utils/network.py

Fixes: #4470 
- Enforce confirmed block in api/python.py get_token_network() calls. This addresses the problem described in this [comment](https://github.com/raiden-network/raiden/issues/4470#issuecomment-521233420) of #4470 
- Also disallow default argument for block_identifier for get_token_network. This will only lead to bad surprises. Let's just be explicit
Test that opening a channel via the API provides the confirmed block and not
the latest block as given_block. The discrepancy there lead to potential timing issues where the token network was deployed for the state in the "latest" block but not yet in the confirmed state and a BadFunctionCallOutput exception was thrown from web3.
- Safety
- …

Enforce confirmed block usage in api/python.py get_token_network() calls

---

raiden/messages/monitoring_service.py
raiden/network/proxies/token_network.py
raiden/raiden_event_handler.py
raiden/tests/conftest.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/test_balance_proof_check.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/unit/test_messages.py
raiden/utils/packing.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

This PR upgrades a dependency `raiden-contracts` to `0.30.0`. It contains a bug fix so monitoring services can no longer close channels.
This PR
* changes some MessageTypeId.BALANCE_PROOF into MessageTypeId.BALANCE_PROOF_UPDATE.
* adds one argument to the constructor argument of OneToN contract.
- Safety
- Commits

Upgrade raiden-contracts to 0.30.0

---

raiden/network/proxies/token_network.py

Without this the locks are printed as binary, which is harder to read

Encoding locks for logging

---

raiden/storage/restore.py
raiden/tests/integration/api/test_pythonapi_regression.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/test_echo_node.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py
raiden/tests/utils/events.py
raiden/tests/utils/factories.py
raiden/tests/utils/transfer.py
raiden/waiting.py

Assert that no failed unlocks occur in happy path transfer tests.
Closes #4369

Add assertions to transfer integration tests

---

raiden/tests/unit/test_cli.py
raiden/utils/ethereum_clients.py

If the eth client version had `0` for patch/minor version there was a
bug in the check. This fixes it and adds a test

Fix eth client version check

---

raiden/tests/integration/network/transport/test_matrix_transport.py

The test must wait for the initial mutual healthcheck to update the reachability state to reliably perform the actual test.
Fixes: #4658

Fix test_matrix_invite_private_room_unhappy_case_3 flakyness

---

raiden/network/rpc/client.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py

Fixes: #3835 
Running our function for `estimate_gas` would hang for 15+ minutes for parity when the contract required a long calculation. The main reason is that parity blocks for the request and web3 confuses that for a timeout, which leads to retries for the same request from two of middlewares that are installed:
- Our own 'http_retry_with_backoff_middleware", which retries failed connections for 10 times, at increasing intervals
- web3's built-in "http_retry_request" middleware, which retries failed connections 5 times after a timeout of 10 seconds.
This leads to long-running calls to be tried and retried 50 times, 
1. (50 + 0.2) seconds 10 s timeout for each of try from the http_retry_request) + initial sleep from backoff initial of 0.2s
1. (50 + 0.4) seconds:  (our middleware …

Check build with timeout on patched web estimate_gas

---

raiden/blockchain/decode.py
raiden/blockchain/state.py
raiden/raiden_service.py
raiden/tests/utils/network.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/utils/__init__.py
tools/debugging/replay_wal.py

Fixes: #4653 
This PR adds the possibility to set the flat mediation fee on a per token network basis. This is required as tokens in different networks have different values and therefore different settings are required.
This is accomplished by changing the `--flat-fee XXX` CLI flag to take two arguments: The checksummed address of the token network and the flat fee for that network (`--flat-fee 0xdeadbeef 123`). This flag can be set multiple times for different networks.
In the future we should introduce a `MediationFeeConfig` class to collect all related settings.
- Safety
- Commits

Set flat_fee per token network

---

raiden/tests/integration/rpc/assumptions/test_geth_rpc_assumptions.py

According to the geth devs if we run a PoA chain (clique, dev mode) and
HEAD-127 doesn't contain any transactions, then the state of HEAD-127 will
be the same as HEAD-128, so it will still be referenced and not deleted.
To avoid this and make sure the pruned_block_number is pruned let's mine
buffer period more blocks while at the same time sending transactions
Fix #4545
- Safety
- Commits

Attempt to fix flakiness at geth_request_pruned_data test

---

raiden/accounts.py
raiden/tests/unit/test_accounts.py
raiden/ui/prompt.py

Display proper error if account does not have a keystore file

---

raiden/network/blockchain_service.py
raiden/tasks.py

This PR is a collection of various smaller changes:
- Expand docstring of BlockChainService after I discussed it with Augusto.
- Remove duplicated `get_block_header`, something I found while reading the code.
- Cleanup and type `AlarmTask`: Some cleanups also found during looking through the code. (Ref. https://github.com/raiden-network/raiden/issues/4033)
- Safety
- Commits

Improve docstring, add typing

---

.circleci/config.yml
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

This PR upgrades `raiden-contracts` dependency.  It also contains some workarounds for https://github.com/raiden-network/scenario-player/issues/230#issuecomment-522009612.
- Safety
- Commits

Raiden contracts 0.31.0

---

raiden/network/proxies/token_network.py
raiden/tests/integration/test_recovery.py
raiden/transfer/events.py
raiden/transfer/node.py
raiden/waiting.py

Fixes: #4639 
Looking at the stacktrace posted in the issue, it was obvious that the node was being restarted and the withdraw transaction was being sent on-chain during the initialization phase.
What happened?
1. A withdraw was initialized
2. Withdraw was signed by both participants and the transaction was queued.
3. Node goes offline
4. Partner closes channel
5. Node goes back online and tries to execute the withdraw transaction on-chain.
The problems that caused this were:
1. A race condition of trying to withdraw after having lost the race with the partner node which closed the channel was not handled. Raiden was raising an Unrecoverable error when the transaction failed because the channel state on-chain was not open
2. When initializing the transaction queue, the withdraw …

Fix set_total_deposit failure after channel is closed

---

raiden/app.py
raiden/blockchain/decode.py
raiden/raiden_service.py
raiden/settings.py
raiden/tests/integration/rpc/assumptions/test_geth_rpc_assumptions.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/utils/typing.py

Fixes: https://github.com/raiden-network/raiden/issues/4654
This makes the definition of the imbalance penalty fee relative to the
capacity to the channel. The goal is to make the setting more useful
until we implement a endpoint to configure it in the API.
- Safety
- Commits

Change `--max-imbalance-fee` to `--proportional-imbalance-fee`

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/storage/serialization/serializer.py
raiden/storage/serialization/types.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/mocked/test_matrix_transport.py

These are considered an implementation details and should not be visible
in the wire protocol.
I don't like two things about the implementation in this change set:
* MESSAGE_NAME_TO_QUALIFIED_NAME needs to be maintained manually.
We could do this automatically, but that would require importing all
message classes in the serializer module, which is ugly in a different
way.
* The check whether the type has to be expanded or not just looks at the
presence of a dot in the `_type`. Maybe we should be more explicit
about when to expand the type by passing a parameter to `deserialize`,
like the one that has been added to `serialize` in this change?
Fixes https://github.com/raiden-network/raiden/issues/4427.
- Safety
- …

Remove module name from message `_type`

---

raiden/blockchain/events.py
raiden/blockchain/filters.py

Fixes: #4102
If we have many blocks to sync, add an info-level log message with blocks left and blocks processed per second and update it every 5 seconds.

Add a log message for blockchain event syncing progress

---

raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Fixes: #4592
This PR creates a scenario for testing that the PFS correctly reacts when a node goes offline
It also adds a scenario to check that the PFS reacts correctly if a node makes a partial withdraw

Add scenarios for node offline and partial withdraw scenarios

---

docs/index.rst
docs/overview_and_guide.rst
docs/webui_tutorial.rst

This PR is part of the "Documentation for the pragmatic developer" issue.
An infobox has been added on the index page and on the "Web Application Tutorial" page which notifies visitors about the current process of updating the docs and provides a link to the new (incomplete) GitBook version.

Link to GitBook docs

---

raiden/__main__.py
raiden/accounts.py
raiden/app.py
raiden/blockchain_events_handler.py
raiden/connection_manager.py
raiden/log_config.py
raiden/message_handler.py
raiden/network/transport/matrix/transport.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/storage/serialization/cache.py
raiden/storage/serialization/fields.py
raiden/storage/serialization/serializer.py
raiden/storage/sqlite.py
raiden/storage/ulid.py
raiden/storage/utils.py
raiden/tasks.py
raiden/tests/utils/transfer.py
raiden/ui/app.py
raiden/waiting.py
setup.cfg
tools/transfer_eth.py

To make sure that no new modules are added to raiden without typing, the
default is now to enforce typing via mypy. Some packages are excluded
for now to make this work without major effort. Before, typing has only
been enforce in selected packages. So we went from a white list to a
black list.
The main change is in `setup.cfg`. The other changes are mostly
straightforward type additions which should not introduce any problems.
These type additions have been made to keep the black list reasonable
short.
- Safety
- Commits

Enforce typing by default in `raiden`

---

raiden/api/python.py
raiden/api/rest.py
raiden/connection_manager.py
raiden/exceptions.py
raiden/tests/integration/api/test_pythonapi.py

Maybe fix #4451 
If a channel is not open, or is in a closing state (still open but
waiting on the closing transaction result) the `set_total_deposit`
function was throwing a `ValueError`.
That is a valid and recoverable race condition so this commit
introduces an appropriate error and handles it in all places where it
can be thrown.
From the stack trace shown in #4451 this seems to have been the problem but without logs it's hard to say with 100% certainty.
- Safety
- Commits

 Treat trying to deposit on a closed channel as recoverable error

---

raiden/connection_manager.py

If I had these logs when debugging this:
https://github.com/raiden-network/raiden/issues/4451#issuecomment-527405820
things would have gone much faster.

Add more logs to the connection manager

---

raiden/connection_manager.py

Fixes: #4725 
The second paramter of the function call was wrong.
- Safety
- Commits

Fix wrong parameter in connection manager

---

raiden/api/rest.py

I added the type for the RaidenService so that jedi can jump around the definitions. That caught two bugs in the connection manager endpoint.

typing for rest.py

---

raiden/raiden_service.py
raiden/routing.py
raiden/settings.py
raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/api/test_api.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/test_source_routing.py
raiden/tests/utils/factories.py
raiden/tests/utils/transfer.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/state.py

Fixes: #4710
We found out that the client never used the fee estimates the PFS sends together with the routes.
This leads to payments failing as soon as any mediator in the route enables mediation fees.
The fix is to use the provided fee estimates from the PFS. This PR also removes the `fee` parameter from many functions where it doesn't make sense (a fee is always bound to a certain route, and not to a payment).
- Safety
- Commits

Use fee estimates from PFS for payments

---

README.md

Edited the Raiden Wizard link to point to the Quick Start section in the new documentation and some minor grammar edits.
I think we should keep the link for the old documentation in the "Look at the documentation" link. Because this is the main repo and for now our old docs are much more comprehensive. I did a PR yesterday where I mention the new docs in the old docs so anyone visiting the old docs will have the option to look at the new docs as well.

Added GitBook link

---

raiden/transfer/identifiers.py

This just adds a `__str__` that encoded the token address as a checksum address. I introduce this because the current format while [logging](https://github.com/raiden-network/raiden/blob/8ff88a3fb1f6852156ab0505a92778d5a3b8f7b8/raiden/waiting.py#L478-L481) this value looks like this `canonical_identifier=CanonicalIdentifier(chain_identifier=42, token_network_address=b'#\xe1\xf3\xb0\x0e\t\xb6\x00D\xb2#\xba\xce\xe8\x1e\xad\xf8\xf50\xff', channel_identifier=1)`
- Safety
- Commits
- Specs

Added __str__ to CanonicalIdentifier

---

raiden/transfer/identifiers.py

This just adds a __str__ that encoded the recipient address as a checksum address. I introduce this because the current format while logging this value looks like this `QueueIdentifier(recipient=b'\\xe0\\x90\"\\x84\\xc8Z\\x9a\\x03\\xda\\xa3\\xb5\\xab\\x03.#\\x8c\\xc0\\\\\\xff\\x9a', canonical_identifier=CanonicalIdentifier(chain_identifier=42, token_network_address=b'#\\xe1\\xf3\\xb0\\x0e\\t\\xb6\\x00D\\xb2#\\xba\\xce\\xe8\\x1e\\xad\\xf8\\xf50\\xff', channel_identifier=1))`
(Note: The token network address is fixed by: https://github.com/raiden-network/raiden/pull/4753)
- Safety
- Commits
- Specs

Added __str__ to QueueIdentifier

---

raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py

Fixes: https://github.com/raiden-network/raiden/issues/4747
Test different fee schedules in an integration test. This showed the need to relax existing checks in the Raiden code base which are not true anymore after the introduction of the mediation fees. See commit messages for more details. 
- Safety
- Commits
- Specs

Test fee integration with different fee schedules

---

raiden/api/python.py

New channels cannot be open if the deprecation switch is on. This adds the missing check to the open operation.
- Safety
- Commits
- Specs

Add missing check for the deprecation switch on channel open

---

raiden/tests/utils/mediation_fees.py
raiden/transfer/mediated_transfer/mediator.py
raiden/ui/app.py
raiden/utils/mediation_fees.py

Part of #4748
The CLI args are given as "per mediation", while the channel fees are
applied per channel that takes part in the mediation. This leads to
counter-intuitive behaviour, which is fixed by this PR.
- Safety
- Commits
- Specs

Properly calculate per channel fees from CLI args

---

raiden/network/proxies/token_network.py
raiden/tests/integration/network/proxies/test_token_network.py

This reuses the failure messages from the gas estimation in the
transaction failure for a the channel deposit. This change is only
cosmetic, to improve the error message.
This commit also removes _get_channel_state, that was only adding an
extra indirection layer without any useful logic, it made bit harder to
review the code.
- Safety
- Commits
- Specs

Improved messages for failure on deposit

---

raiden/tests/integration/network/proxies/test_token_network.py

In https://github.com/raiden-network/raiden/pull/4766 the question comes
up whether the contracts check the settle timeout in exactly the same
way. We've already checked for failure of values outside the expected
bounds, but to make sure things match in all cases, we also have to test
for success.
- Safety
- Commits
- Specs

Check `settle_timeout` threshold for success, too

---

raiden/network/proxies/token_network.py

Part of #4763
The call to `balance_of` does an rpc call to query the state of the
blockchain at the block `given_block_identifier`, which may have been
pruned. For thir reason the call must be inside the try block.
- Safety
- Commits
- Specs

Blockchain query have to be inside the try block.

---

raiden/tests/unit/storage/test_serialization.py

Fixes: #4738
Provide a test which checks that the SendWithdrawRequest is serializable/deserializable.
- Safety
- Commits
- Specs

Make sure that SendWithdrawRequest is deserializable

---

raiden/storage/restore.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/unit/test_sqlite.py
raiden/tests/utils/transfer.py

Replace `gevent.Timeout` by `BlockTimeout` in integration tests where it makes sense, to make sure we wait long enough in every test run.
Related issue: #4524
Edit: The issue has been postponed to the next milestone, so this pr is only for the part of the tests that have been adapted so far. There will be a follow-up pr for the remaining tests.

Use block timeout in events integration test

---

raiden/tests/utils/eth_node.py

`--nodiscovery` was given to make sure the test network didn't try to
join any mainnet nodes. This however has the negative side effect of
disabling discovery even if the `--bootnodes` flag is given, meaning
that only the miner node can be used for an integration test.
To allow more than one geth node on a test network that flag cannot be
used. Our private network should be independent of the main network
because we overwrite the `--bootnodes`.
- Safety
- Commits
- Specs

Remove --nodiscovery from the fixture setup

---

raiden/tests/integration/transfer/test_mediatedtransfer.py

in `test_mediated_transfer_with_fees`. In its current form, the test
works without this change. But changing the fee amount in the test or
the DEFAULT_MEDIATION_FEE_MARGIN will break the test without clearly
showing the cause. So it's better to handle this case explicitly.
- Safety
- Commits
- Specs

Use `DEFAULT_MEDIATION_FEE_MARGIN` in test

---

raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/utils/network.py

Fixes: #4743 
We need a test that the PFSCapacityUpdate is triggered by deposit and withdraw. The PFS does not listen to the blockchain anymore.
- Safety
- Commits
- Specs

adds integration test of sending capacity updates

---

raiden/exceptions.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/transfer/mediated_transfer/mediator.py

Otherwise the next transfer will be be zero or less, which does not make
any sense. Better handle this case with an explicit exception. We could
try a refund for that case, but it's worth the complexity for such a
rare case.
Fixes: https://github.com/raiden-network/raiden/issues/4750
- Safety
- Commits
- Specs

When fees >= amount, drop transfer

---

docs/changelog.rst
raiden/network/proxies/token_network.py

This PR improves the error checking for withdraws noticed on https://github.com/raiden-network/raiden/issues/4749#issuecomment-528455275 , instead of:
> raiden.exceptions.RaidenUnrecoverableError: unlock failed for an unknown reason
This will use:
> raiden.exceptions.RaidenRecoverableError: setTotalWithdraw would have failed because current block is higher than the withdraw expiration expiration_block=13274504 transation_checked_at=13299685
- Safety
- Commits
- Specs

Set total withdraw expired message

---

raiden/network/proxies/token_network.py
raiden/tests/integration/network/proxies/test_token_network.py

Part of #4763
Added check for the channel identifier.
The function `set_total_deposit` is provided with a channel identifier
and a partner address. This is necessary because the smart contract does
not store the participants addresses to save storage and reduces costs.
These values must validated, otherwise it is possible to call the
proxy's `set_total_deposit` with a correct channel id which the current
node is not a participant, where correct is just a channel that was
created at some point in the past.
The check is not complete: Because of state prunning the preconditions
cannot always be checked, and because once theis removed the id is
removed from the smart contract storage, the check can only be performed
if the state of the channel is at OPENED or CLOSED.
Quality check list that …

Validate the channel id on deposit

---

raiden/tests/utils/eth_node.py
raiden/tests/utils/smoketest.py

This is just a cosmetic change. Because most of our log lines use the address instead of the private key, it's easier to match the logs to the files in the file system if the node's address is used instead.
- Safety
- Commits
- Specs

Using node address for storage path

---

raiden/tests/integration/transfer/test_mediatedtransfer.py

This PR skips a flaky test called `mediated_transfer_messages_out_of_order`. The test failed in
https://circleci.com/gh/raiden-network/raiden/76964#queue-placeholder/containers/23
when I made an unrelated change (added a function that's never used now).
Issue for the flakiness: https://github.com/raiden-network/raiden/issues/4804
- Safety
- Commits
- Specs

Skip a flaky test

---

raiden/raiden_event_handler.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/initiator.py

During my work on I found out that there is currently no event emitted when a `SecretReveal` is received, which has an amount that is smaller than the intended transfer amount.
This PR adds `EventInvalidSecretRequest` for that case.
- Safety
- Commits
- Specs

Add EventInvalidSecretRequest

---

raiden/tests/scenarios/pfs2_simple_no_path.yaml

Removes a duplicate assert. This doesn't change the behaviour of the scenario, but is merely a cosmetic fix.

Remove superfluous assert [skip tests]

---

raiden/network/proxies/token_network_registry.py
raiden/tests/integration/network/proxies/test_token_network_registry.py

I'm adding a new function get_token_networks_created(). This function
is a simple wrapper over `token_network_created` public variable in
TokenNetworkRegistry contract.
The reason for this change is to introduce a check for the `canCreateTokenNetworks()` modifier in the client.  This function will be useful for determining whether the TokenNetworkRegistry has too many tokens registered, in https://github.com/raiden-network/raiden/pull/4796/files
- Safety
- Commits
- Specs
- Is it a …

Add get_token_networks_created()

---

raiden/network/proxies/token_network_registry.py
raiden/tests/integration/network/proxies/test_token_network_registry.py

which is a getter for max_token_networks public variable in
TokenNetworkRegistry. The variable shows how many tokens can
be registered in the registry. Having this getter is useful
for checking preconditions for createERC20TokenNetwork()
in the proxy.
This is a part of #4795.
The PR adds a new getter function `get_max_token_networks()` in the TokenNetworkRegistry proxy.
There is not much design space.
- Safety
- Commits
- Specs

Add TokenNetworkRegistry.get_max_token_networks()

---

raiden/blockchain/decode.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/unit/test_channelstate.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/utils/mediation_fees.py

Fixes a bug described here:
https://github.com/raiden-network/raiden/pull/4802#issuecomment-530153318
While fixing the tests, and specifically [this](https://github.com/raiden-network/raiden/blob/3b12c5564b99e8bdda7d7f143c4608754fca3f76/raiden/tests/integration/test_raidenservice.py#L222) one I discovered a bug at how fees are set.
At the moment when an on-chain deposit is seen
https://github.com/raiden-network/raiden/blob/3b12c5564b99e8bdda7d7f143c4608754fca3f76/raiden/blockchain/decode.py#L382-L390
we generate both the state change to [process the deposit](https://github.com/raiden-network/raiden/blob/3b12c5564b99e8bdda7d7f143c4608754fca3f76/raiden/blockchain/decode.py#L386) and the state change to [change the fees](https://github.com/raiden-network/raiden/blob/3b12c5564b99e8bdda7d7f143c …

Fee updates should be triggered after onchain events processing

---

raiden/constants.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/utils/smoketest.py

These constants used to be hardcoded in the smart contracts. Now they
are configurable through the smart contract constructors, and therefore
their value can vary. Because of this Raiden must query the limits from
the smart contracts and cannot rely on the constants anymore.
The only usages left of the constants in the codebase were for the
tests. This reduces the constant footprint and leave them as the default
for the default fixture setup, just because this value works fine for
now.
- Safety
- Commits
- Specs

Removed old RedEyes constants from the main module.

---

raiden/tests/scenarios/pfs7_multiple_payments.yaml

Also update UDC stipend to prevent PFS service refusal.
Fixes #4810
Requires raiden-network/scenario-player#314

Update pfs7 scenario to only match distinct routes

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Reasoning: When we add default fee values, it is easier to
set fees for that one token address to 0 than doing so for
every newly created TokenNetwork for every scenario
Fixes BF1 the last assert was wrong

Defines one TokenAddress per Scenario and fixes bf1

---

raiden/api/python.py
raiden/network/proxies/token_network_registry.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/utils/smoketest.py
raiden/ui/console.py

First, since there is no longer add_token_without_limits() function,
the function can be simply named add_token().
Second, since we no longer have similar functions with different sets of keyword
arguments, we don't have to pass the keyword arguments in a dictionary.
As a result, the typechecking becomes more effective.
It's a refactoring.  Arguably the change is not necessary now.  Even without making the change I can probably add the `block_identifier` argument (#4830 ).  So this PR is a detour.  But I think other people don't have to ask "what does with_limits mean?"
Quality …

Simplify add_token_with_limits()

---

raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/unit/utils/test_mediation_fees.py
raiden/utils/mediation_fees.py

After https://github.com/raiden-network/raiden/issues/4844, we need to
handle do the fee-per-mediation to fee-per-channel conversion slightly
differently.
This is also a good occasion to use the same function in the test, where
we have the same need.
Fixes https://github.com/raiden-network/raiden/issues/4860.
- Safety
- Commits
- Specs

Update handling of proportional fees given on cli

---

raiden/api/python.py
raiden/network/proxies/token_network_registry.py
raiden/network/rpc/client.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/utils/smoketest.py

Fixes: #4830
TokenNetworkRegistry.add_token() never raised `BrokenPreconditionError` because the precondition checks were missing.  This PR implements the precondition check in `TokenNetworkRegistry.add_token()` against "token already registered".
I had to add an argument `block_identifier` so I changed all callers.
- Safety
- Commits
- Specs

Precondition check in add_token

---

raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/unit/utils/test_mediation_fees.py
raiden/tests/utils/mediation_fees.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/mediated_transfer/mediator.py

Fixes: #4856 
This adds `raiden.tests.utils.mediation_fees.get_initial_payment_for_final_target_amount` which calculates the necessary initial amount, so that the target receives a certain payment amount after fees have been deducted.
We should add more tests, but this is a good enough for converting the tests to mediation fees.
- Safety
- Commits
- Specs

Add test helper to backwards calculate fees

---

.github/auto_assign.yml

Configures https://probot.github.io/apps/auto-assign/ to add one
reviewer to each new PR in the Raiden repo.
I've requested the App above to be added to the Raiden repo. An admin
will have to accept that request before it starts working.
I've not tested this configuration. If it does not work as intended,
I'll create a repo to test this.
Closes https://github.com/raiden-network/team/issues/602
- Safety
- Commits
- Specs

Enable auto-assign probot

---

raiden/blockchain/decode.py
raiden/blockchain_events_handler.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/transfer/test_channel.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/node.py
raiden/transfer/state_change.py
raiden/transfer/token_network.py
raiden/utils/mediation_fees.py

In https://github.com/raiden-network/raiden/pull/4827, we've added
`TriggerFeeUpdate` in addition to having `ActionChannelUpdateFee`. This
commit remove these in favor of one simple `SendPFSFeeUpdate` event. The
main purpose of this is to make sure that balances and fees are always
consistent by changing them during the same state change.
Pro:
- Easier to enforce consistency
- No `ActionChannelUpdateFee` in `blockchain_events_handler.py` (I don't
think it belonged there)
- Less state changes
- Shorter code
Cons:
- Needed to add `fee_config` to deposit and withdraw state changes
- Will probably need to reintroduce a state change once users can change
fees during runtime.
- Quite a lot of changed lines for not that much gain.
Closes https://github.com/raiden-network/raiden/issues/4852. …

Reduce the number of state changes for fee updates

---

raiden/api/python.py
raiden/api/rest.py
raiden/connection_manager.py
raiden/exceptions.py

TransactionThrewn exception was defined but never raised.
So this commit removes this exception from the codebase.
It's refactoring.  The PR removed an exception that was never used. It also updates docstrings that mention this exception `TransactionThrew`.
- Safety
- Commits
- Specs

Remove an exception that is never thrown

---

raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py
raiden/tests/utils/eth_node.py
raiden/utils/typing.py

Merge after #4800
This is just one of my hypothesis for #4749 it does not fix it.
This assumption test is a bit of a surprise to me, I expected the transaction to never be included in any block.
- Safety
- Commits
- Specs

Gas price set to zero

---

raiden/constants.py
raiden/network/blockchain_service.py
raiden/network/proxies/metadata.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/utils.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/test_balance_proof_check.py
raiden/tests/utils/network.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py
raiden/utils/typing.py

Partially solves: #3958
The main objective of this PR is to define the *lower bound* to used for a query logs `fromBlock` which is not the genesis block.
With this PR the deployment of the contract `TokenNetworkRegistry` is used. If that metadata is not available, then either the Constantinople fork or the genesis block is used. Note that because Constantinople is used, instead of Byzantium, this is yet another incompatible change with Red Eyes.
There are a few problems left to be fixed in the future with this PR:
- It assumes only one `TokenNetworkRegistry`.
- It doesn't query the `TokenNetworkCreated` event, it just uses the same `filters_start_at` as the registry. This will also degrade have a negative impact in performance over time.
- It introduces the …

Smart contract metadata

---

docs/rest_api.rst
raiden/api/rest.py
raiden/api/v1/resources.py
raiden/tests/integration/api/test_restapi.py

This PR adds an API endpoint (`/api/v1/version`) that shows the version of Raiden using the existing `get_system_spec` function.
This is useful for applications utilizing the API of Raiden so that they can ensure compatibility with the underlying service. Similar to what Raiden is doing with its version checks for GETH and Parity.
- Safety
- Commits
- Specs

Added API endpoint to get Raiden version

---

raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/utils/runnable.py

- Move transport greenlet generation into runnable,
- greenlet scheduling simplified to one func, with an optional delay arg
closes  #4598
- transport._spawn and transport._spawn_later renamed to _schedule_new_greenlet
closes  #4597

Transport greenlet generation

---

.github/auto_assign.yml

Hopefully this will allow github notifications to properly tell the
user they were requested to review the PR.

Also auto-assign the PR itself and not only add review

---

raiden/exceptions.py
raiden/network/rpc/client.py
raiden/network/rpc/middleware.py
raiden/tasks.py
raiden/tests/unit/network/rpc/test_client.py
raiden/ui/checks.py
raiden/ui/runners.py

fix #2226
The existing middleware doubled the number of RPC calls, because prior
to every RPC call a check for connectivity was done.
Additionally this EthNodeCommunicationError removes Instead of wrapping
the underlying exceptions (ConnectTimeout, JSONDecodeError), this just
let them to propagate.
I'm surprised this didn't appear on #4872 , perhaps the result was being cached?
- Safety
- Commits
- Specs

Remove unecessary RPC calls

---

.github/auto_assign.yml

Apparently, the requested reviewer is not the same as assignee

Revert assignee for the github bot

---

raiden/api/python.py
raiden/tests/integration/api/test_pythonapi.py

Issue #918 needs that the reveal timeout and settle timeout are validated against each other.
- Safety
- Commits
- Specs

Added a test for #918

---

raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/mediation_fees.py
raiden/transfer/mediated_transfer/mediation_fee.py

The amount has to have the opposite sign for incoming and outgoing
channels. Otherwise, the fees would not properly represent the balance
moving back and forth.
- Safety
- Commits
- Specs

Fix imbalance fee direction for incoming channel

---

docs/changelog.rst
docs/rest_api.rst
raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/raiden_service.py
raiden/tests/integration/api/test_restapi.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/state.py

Example:
```
curl -X POST http://localhost:5001/api/v1/payments/0xF6f11bb624aabb2782FD53CcbF10db73f303F367/0x22b001098c212eA447EF291dE687Bf5C2Ef40914 -H 'Content-Type: application/json' --data-raw '{"amount": 500, "identifier": 987654326, "secret": "0x78c8d676e2f2399aa2a015f3433a2083c55003591a0f3f3349b6e50fc9ca44f1", "lock_timeout": 50}'
```
for a channel to be used, the lock_timeout should be bigger than reveal_timeout and not bigger than settle_timeout.
Fixes #4669

feature: lock_timeout can be provided when making a payment

---

raiden/api/python.py
raiden/api/rest.py
raiden/exceptions.py
raiden/network/proxies/token_network_registry.py
raiden/tests/integration/network/proxies/test_token_network_registry.py

because then the call to TokenNetworkRegistry will fail.
This fixes #4875.
~~Fixes: 4815~~
After this PR, TokenNetworkRegistry proxy refuses to register a token contract at address 0x00000000....00.  The constructor of TokenNetwork contract checks against this case, so the contract proxy needs to check this condition.
I didn't add post-failure checks because the precondition checks will completely remove the possibility that the token address is 0x00000000..00.
- Safety
- Commits
- Specs
- Is it a user facing …

Avoid adding a token at NULL_ADDRESS

---

raiden/message_handler.py
raiden/messages/withdraw.py
raiden/tests/unit/test_channelstate.py
raiden/transfer/channel.py
raiden/transfer/state_change.py

Fixes: #4934
This reduces the options of tampering with the message for attackers. It
also makes the signature different from the `WithdrawRequest` one.
Ideally all messages and proofs are guaranteed to have different
signatures.
- Safety
- Commits
- Specs

Include all fields in `WithdrawExpired` signature

---

raiden/api/python.py

A variable prestate was renamed into chainstate but in a comment
the old variable name stayed. This commit changes the variable
name in the comment.
Before this PR, a comment talked about a variable that no longer exists in the codebase.
- Safety
- Commits
- Specs

Catch up with variable rename in a comment

---

raiden/app.py
raiden/exceptions.py
raiden/network/proxies/token_network_registry.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/test_pythonapi.py

Fixes: #4889 
Fixes: #4888 
Fixes: #4886 
Fixes: #4884 
Fixes #4882 
- Safety
- Commits
- Specs

Token network registry preconditions

---

docs/changelog.rst

Fixes: #4958
Fixes #4764
The changelog included a version number that crashed Sphinx. I added a dash in it, so that readthedocs can build again.
- Safety
- Commits
- Specs

Fix crash in sphinx due to version number

---

raiden/api/rest.py

Proxies raise RaidenRecoverableErrorr when the failure was not
the caller's fault but because of somebody else interacting
with the blockchain.  This fits perfectly with the "conflict"
situation.  So the HTTP status should indicate "conflict".
It's a bug fix.  When a proxy raises `RaidenRecoverableError`, that should indicate the fact that there was a race.  So the HTTP status should indicate a conflict.
- Safety
- Commits
- Specs

RaidenRecoverableError indicates conflicts.

---

raiden/network/proxies/token_network_registry.py

TokenNetworkRegistry.createERC20() succeeds even when the stored
chain_id value is different from the current chain_id of the blockchain.
Since the proxies should not check what's not checked onchain,
I'm removing the checks that do not exist in the onchain contracts.
This PR comes from this conversation https://github.com/raiden-network/raiden/pull/4936#discussion_r327028792
It's a bug fix.  Before this PR, the proxy failed even when the transaction would succeed.
- Safety
- Commits
- Specs
- Is it a user …

Remove checks that are not in the onchain contract

---

raiden/api/python.py
raiden/tests/integration/api/test_restapi.py

Fix #4937
- Safety
- Commits
- Specs

Handle RecoverableError in the python api's set_total_deposit

---

raiden/network/resolver/client.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/utils/network.py
tools/dummy_resolver_server.py

This PR merge changes related to external resolver (XUD) done in private fork of raiden. 
feature: add chain_height and chain_id to the resolver request
---------------------------------------------------------------
chain_height is needed for the extraction of the lock_duration from the expiration.
chain_id can be used to ensure that the request is coming from the right chain.
remove unneeded members
replace sha3 with sha256
----------------------------
the dummy resolver can be used to simulate a payment where the payee has the secret. Since raiden changed the hash function of the secret to sha256 we also need to do this for the dummy resolver.
Allow payment with secret_hash and no secret
-------------------------------------------------
restore functionality added in the past. It is …

external resolver related changes

---

docs/proxies.rst

I was mistaken about how proxies work.  I thought that after a transaction fails in a block, proxies check conditions at the beginning of the failing block.  However, the condition checks happen at the end of the failing block.  This PR clarifies that point in the proxy documentation.
- Safety
- Commits …

The post-failure checks happen at the end of the failing block, not at the beginning.

---

raiden/messages/withdraw.py

This should have been in https://github.com/raiden-network/raiden/pull/4935 already, but I missed it because the field was defined in a superclass.
- Safety
- Commits
- Specs

Add message_identifier to WithdrawExp. signature

---

docs/changelog.rst
docs/overview_and_guide.rst
docs/private_net_tutorial.rst
raiden/network/rpc/client.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/utils/eth_node.py
raiden/ui/checks.py

Fixes: #4976 
- Safety
- Commits
- Specs

Geth stop using txpool api

---

docs/changelog.rst
raiden/constants.py
raiden/tests/unit/test_cli.py

Set 1.8.21 to lowest supported geth version
This is to have the eth_getTransactionCount fix:  ethereum/go-ethereum#2880
- Safety
- Commits
- Specs

1.8.21 is now the  lowest geth supported

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml

Otherwise the MS won't have acted before the assert in all cases.
Fixes https://github.com/raiden-network/raiden/issues/4988
[skip tests]
- Safety
- Commits
- Specs

Update scenarios after `settle_timeout_min` change

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/utils/synapse_config.yaml.template
raiden/tests/utils/transport.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

(Not mergable currently because of #4634. Temporarily uses the base64 solution mentioned in the issue.)
This updates our testing dependency to matrix-synapse 1.2.1.
The Synapse config files generated by the integration tests have been updated to align with new / changed options.
Additionally this no longer uses local TLS certificates speeding up tests.
Fixes: #3387
Required for: #4292
Blocked by: #4634

Switch to Synapse >= 1.0

---

raiden/network/resolver/client.py

if resolver is configured, retry to resolve the secret until:
- the resolver provides the secret
- the resolver confirms that it has not such secret
- the lock timeout expires
This improvement is needed in order to handle situation of resolver not being available temporary due to restart or other problems. In such cases we would like the request to wait until the resolver is back.

resolver retry loop

---

raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/unit/transfer/test_channel.py
raiden/tests/utils/mediation_fees.py
raiden/transfer/mediated_transfer/mediation_fee.py

When the slope exceeds 1, I could balance the channels more cheaply
myself. It also makes fee calculations ambiguous.
Hopefully fixes https://github.com/raiden-network/team/issues/623
- Safety
- Commits
- Specs

Calculate imbalance penalty with slope <= 1

---

raiden/ui/cli.py

This is a requirement of the new imbalance fee function, so we should
enforce this here as well.
- Safety
- Commits
- Specs

Limit imbalance fee CLI arg to 5%

---

raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/utils/mediation_fees.py
raiden/transfer/mediated_transfer/mediation_fee.py

We add iteration to the test helper for backwards fee calculation as is intended in the PFS. This allows us to write a test that checks a complete fee calculation round trip of
* PFS calculates fees from target amount
* Initiator sends target_amount + fees
* Mediator takes fees based on amount sent by initiator
* Amount sent by mediator is approx. target amount 
The fee margin is currently not included.
- Safety
- Commits
- Specs

Add fee round trip test

---

raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Without a wait function, the PFSCapacityUpdate might not reach the pfs in time. This was the reason ot the failure of Oct 6 nightly runs in pfs5. 
- Safety
- Commits
- Specs

Adds wait_blocks to pfs scenarios before transfers to prevent PFSCapacityUpdate latency

---

tools/debugging/gather-test-addresses.py
tools/debugging/json-log-to-html.py

Some more small improvements to the json-log-to-html tool.
Adds a `--truncate-logger` option to shorten logger names so they take up less space on screen.
Also adds another small utility that collects the active node addresses from log files and generates a replacement file mapping the addresses to nicer human readable strings usable with json-log-to-html.
Example usage:
```
~$ python3 raiden/tools/debugging/gather-test-addresses.py *.log replacements.json
~$ cat replacements.json
{"0xabcdef1234567890abcdef1234567890abcdef12": "<<A>>", "0x0987654321fedcba0x0987654321fedcba0x0987": "<<B>>"}
~$ python3 raiden/tools/debugging/json-log-to-html.py [... other options ...] -f replacements.json
```

Some more json-log-to-html improvements

---

docker/hooks/build

In order to build the proper raiden version from `Dockerfile`, we need
to pass the intended `RAIDENVERSION` build argument. According to
https://github.com/docker/hub-feedback/issues/508 the current way of
doing this is via build hook.
dockerhub has the `SOURCE_BRANCH` environment variable available, that
should translate just fine to the values we want in `RAIDENVERSION`.
Fixes: the root cause of #5049 -- merging this PR will not magically fix the incorrectly tagged/build docker image.
- Safety
- Commits
- Specs

Add dockerhub build hook

---

docs/changelog.rst
raiden/blockchain/decode.py
raiden/messages/path_finding_service.py
raiden/raiden_service.py
raiden/settings.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/unit/transfer/test_channel.py
raiden/tests/unit/utils/test_mediation_fees.py
raiden/tests/utils/mediation_fees.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/utils/mediation_fees.py
tools/dummy_resolver_server.py

Fixes: #5053
This PR:
- Adds fee capping, so that the sum of all mediation fee components can not get smaller than 0
- Adds a CLI flag `--cap-mediation-fees/--no-cap-mediation-fees` to enable/disable this. The default is to enable fee capping
- Adds test for capped fees
- Fixes existing tests
- Safety
- Commits
- Specs

Add fee capping

---

docs/changelog.rst
raiden/storage/serialization/types.py
raiden/tests/unit/storage/test_serialization.py

Fixes: #5055
During deserialization, marshmallow should know how to deserialize messages inside `queueids_to_queues`.
```
SendMessageEvent: CallablePolyField(
serialization_schema_selector=message_event_schema_serialization,
deserialization_schema_selector=message_event_schema_deserialization,
allow_none=True,
),
```
This is how it is done. However, the matches we have did not include withdraw-related messages. This PR adds missing classes to the match list.
- Safety
- Commits
- Specs

Match withdraw messages for schema generation during deserialization

---

raiden/api/python.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/ui/config.py
raiden/ui/console.py
raiden/ui/runners.py
raiden/ui/sync.py
setup.cfg

Fixes: #5071
This was a leftover from the recent `ProxyManager` refactoring I did. 
This PR also adds type annotations, as mypy easily found that as soon as it started checking that file.
- Safety
- Commits
- Specs

Fix console, add type annotations

---

raiden/messages/transfers.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/unit/test_binary_encoding.py
raiden/tests/unit/test_dict_encoding.py
raiden/tests/unit/test_messages.py
raiden/tests/utils/factories.py
raiden/tests/utils/transfer.py

Fixes: #4991
As discussed in the call yesterday (see https://github.com/raiden-network/team/issues/628) we won't use `LockedTransfer.fee` in the short term.
This PR removes it to have a clean protocol for Alderaan. This is up for discussion, but I think it would be most clear to remove it instead of having it set to 0 all the time (even though there are mediation fees).
- Safety
- Commits
- Specs

Remove `fee` from LockedTransfer

---

raiden/constants.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py
raiden/tests/integration/transfer/test_refund_invalid.py
raiden/tests/utils/factories.py
raiden/tests/utils/mocks.py
raiden/tests/utils/protocol.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transport.py
setup.cfg

This brings us roughly half the way towards enabling `check_untyped_defs = True` for all integration tests.
- Safety
- Commits
- Specs

Increase mypy coverage in tests

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediator.py

Fixes: #4998 
This implements resume for waiting transfers, if a newer `Block` changes the expiry validation. Previously, if a mediator received a transfer, which had a lock expiry higher than `current_block + settlement_timeout`, it would enter the `waiting_transfer` status (so far, so good) **and** be considered `expired` on the next incoming `Block`. The only way for a waiting transfer to be resumed was a change in partner availability.
As described in the addressed issue, this behavior could lead to unexpected results when users have very low margins between `reveal timeout` and `settlement timeout`.
This PR introduces "resume attempts" for waiting transfers on _every_ new `Block` that is seen by the client. I chose to attempt the resume every time, in order to not duplicate the code …

Resume waiting_transfer on `Block`

---

docs/Makefile
docs/adr/0002-testing-strategy.rst
docs/adr/0005-withdraw-expiry.rst
docs/adr/template.rst
docs/index.rst

Reduces the number of warning in the raiden docs.
- Remove autodoc for now
- Fix headings and some markup
- Safety
- Commits
- Specs

Reduce Sphinx warnings

---

raiden/routing.py

I saw this in some logs: `"can_use_pfs": null`
It worked before as well, but after this fix it's a proper boolean.
- Safety
- Commits
- Specs

Fix check if PFS can be used

---

raiden/api/python.py
raiden/tests/integration/api/test_restapi.py

Fixes: #5099 
- Safety
- Commits
- Specs

Correctly format addresses in duplicate channel open API error

---

tools/debugging/analyze_sp_logs.py

It is often tedious to collect all addresses, db paths, etc.
from logfiles of a scenario player run.
This tool scans a scenario player combined log folder for all user
addresses, token network addresses and db files and has a bare bone
TUI wizard in order to run `replay_wal.py`.
Example run:
```
$ python tools/debugging/analyze_sp_logs.py /tmp/debug/mfee4_combined_fees     
/tmp/debug/mfee4_combined_fees/scenario-player-run_mfee4_combined_fees_2019-10-16T05:39:05.log
Parsing run [25].
Select token_network: 
-> Autoselected the only option: 0x9526EC0E58ac5Bb1e24d655E964f0eAA46054d16
[0] Alice - 0xeEbE2633aa9083e655564978e859ca1904EB9252
[1] Bob - 0xeb66a4D7E46Da483d87edb637Af6aF94ba920A74
[2] Carol - 0x2B1B8D2f51903Eb2b38402AdcAB021393B4AEdb5
[3] Dan - …
```

Add a tool for simplified scenario debugging

---

raiden/messages/transfers.py
raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/unit/api/test_api.py
raiden/tests/unit/test_channelstate.py

Rmoves remaining usages of `sha256(secret).digest()` that can be replaced with `sha256_secrethash`.
- Safety
- Commits
- Specs

Remove remaining usages of sha256(secret).digest()

---

raiden/network/rpc/client.py
raiden/tests/integration/api/test_pythonapi.py

Just cherry picking the typo fixes from https://github.com/raiden-network/raiden/pull/5107 as the test does not make sense to be merged since can't reproduce the exact issue that lead to #5051

Typo fixes

---

raiden/messages/abstract.py
raiden/messages/decode.py
raiden/messages/encode.py
raiden/messages/metadata.py
raiden/messages/monitoring_service.py
raiden/messages/path_finding_service.py
raiden/messages/synchronization.py
raiden/messages/transfers.py
raiden/messages/withdraw.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_messages.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/target.py
setup.cfg

Part of #4033 
Add strict type checking for the `raiden.messages` module.
- Safety
- Commits
- Specs

Enable strict type checking for raiden.messages

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_presence.py

Description
This PR
- removes caching from UserAddressManager._fetch_user_presence to give us the most recent Reachability
- adds a Greenlet, that set our Presence periodically and fetches PresenceUpdates from our peers. 
Rationale: 
We might miss PresenceUpdates from the Server or the Server might fail to notify us. With this PR, we renew our own Presence with the Server and poll for PR Reachability.
- Safety
- Commits
- Specs

Refresh presence

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

This reverts commit 77e8d6b5d23551d84f013e2dd58cfb13ca853d92.
Works around https://github.com/raiden-network/raiden/issues/5122.
- Safety
- Commits
- Specs

Revert "requirements/deps upgrade raiden-contracts"

---

raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/events.py
raiden/tests/utils/transfer.py
setup.cfg

The next step will be to enable it for all integration tests except those in `raiden/tests/integration/network`. 
- Safety
- Commits
- Specs

Enable `check_untyped_defs` in `tests/integration/transfer`

---

raiden/network/proxies/proxy_manager.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_secret_registry.py
setup.cfg

Part of #4033 
Enables strict typing for `raiden.network.rpc`  module.
- Safety
- Commits
- Specs

Enable strrict mypy checks for raiden.network.rpc

---

docs/changelog.rst
raiden/network/pathfinding.py
raiden/tests/unit/test_pfs_integration_refactored.py

Fixes: #5064 
Displays a nicer error message instead of some cryptic parser error.
- Safety
- Commits
- Specs

More user friendly error message when PFS request fails

---

raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/api/test_pythonapi_regression.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/test_balance_proof_check.py
raiden/tests/integration/test_echo_node.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/integration/test_send_queued_messages.py
setup.cfg

the ones in `integration.network`.
- Safety
- Commits
- Specs

Check untyped defs in all integration tests except

---

raiden/network/pathfinding.py
raiden/raiden_service.py
raiden/transfer/architecture.py
raiden/transfer/events.py

Some events when printed in the logs have attributes such as hashes or
addresses which are printed in binary.
By adding `__repr__` functions to these events the hex string
representation should be now visible in the logs making it easier
to debug.
- Safety
- Commits
- Specs

Add __repr__ function to classes needing it for better debugging

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/transfer/routes.py

The matrix presence information is currently not reliable. Temporarily
disable this check until it is fixed properly.
See https://github.com/raiden-network/raiden/issues/5156
- Safety
- Commits
- Specs

Workaround: skip presence check

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/transfer/routes.py

This is what caused the regression for https://github.com/raiden-network/raiden/issues/5159 , node3 is trying to use a route that should work from the PFS perspective, however node3 cannot communicate with the node4 used by the PFS.

Revert "Workaround: skip presence check"

---

raiden/ui/cli.py

@nlsdfnbch expressed interest in having a full list of all cli flags for
use in the SP in https://github.com/raiden-network/raiden/issues/5158.
This is provided in this commit, including the negative flags for
boolean parameters.
Closes https://github.com/raiden-network/raiden/issues/5158.
- Safety
- Commits
- Specs

Provide list of CLI params for use in SP

---

.gitattributes

The hunk-header is a bit of text used to contextualized a hunk (a
change).
Example, if a class named `App` has one of its class attributes changed,
the hunk header will be similar to:
@ raiden/app.py:54 @ class App:  # pylint: disable=too-few-public-methods
The test after the second at-sign, `class App:...` is costumizable, and
it is used to give context about the change.
This value is determined by a regular expression. The default regex does
work on some cases, like the example above, but if fails on many cases,
for instance, when a method of the class is changed, the context should
be the function, but with the default regex the class is used as
context. Example, if the method `_check_and_send` from the `_RetryQueue`
is modified, with the default regex this is the hunk header:
@ …

Enable python specific hunk-header

---

raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_node_queue.py
raiden/tests/unit/transfer/test_node.py
raiden/transfer/channel.py
raiden/transfer/identifiers.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py

The function `enqueue_global` could be a bit confusing since there are
both global queues and global rooms. The function `enqueue_global` is
used to put a `Delivered` message into the global queue (which is not
sent to the global room).
To avoid the above confusion this changes from "global queue" to
"unordered queue".
The unordered queue is used to send messages that don't need to be
processed in a given order to the partner node. Which is different from
a global room, which is used to broadcast messages to multiple nodes
(particularly the services).
This is just a naming change, the goal is to clarify the different between global rooms and global queues.
- Safety
- Commits
- …

Renamed CANONICAL_IDENTIFIER_GLOBAL_QUEUE

---

Makefile
docs/macos_install_guide.rst

Fixes: #4679 
Add a Makefile check for OSX so that users that have python which can not import `MONOTONIC_CLOCK_RAW` can know what's wrong and visit the docs to find out how to fix it.
Also add a doc entry on the OSX installation letting the users know that they should manually install python if they encounter this problem.

Docs and make-install-dev step for detecting faulty python in OSX

---

raiden/api/rest.py
raiden/connection_manager.py
raiden/exceptions.py
raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/raiden_event_handler.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
raiden/tests/integration/test_pythonapi.py

This PR introduces an exception class for the case that onchain actions fail due to insufficient eth, and handles it by issuing a warning.
Related issue: #1861
Closes #5048 (issue from manual testing where this surfaced recently)
For the nonce mismatches in #5048, there will be a follow-up issue and pull request.
We also introcude an exception class for unexpected errors of the eth node. Raiden will still crash when that happens, but we want to avoid crashing with cryptic error messages like `ValueError: {'code': -32000}`

Handle insufficient eth during channel settlement

---

raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py

Fixes: #5127
We we're using `_address_to_userids` in `refresh_address_presence`. That could cause flakiness during teardown of tests when while we were iterating over it. 
- Safety
- Commits
- Specs

Closes #5127

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml

The following recent raiden changes force changes in the scenarios:
* Changed fee margin
* Changed default imbalance curve
* Mediation fee capping on by default
Includes the updated numbers due to https://github.com/raiden-network/raiden/pull/5197 for mfee4.
[skip tests]
Fixes: https://github.com/raiden-network/raiden/issues/5131
- Safety
- Commits
- Specs

Update mfee scenarios

---

raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/mediated_transfer/mediator.py
raiden/utils/mediation_fees.py

The standard double-precision floats can't precisely represent integers
larger than ~10**16. This has the effect that balances above that caused
relatively large inaccuracies even for small payments (errors of
multiple tokens for a single token transfer).
This is fixed by calculating with fractions instead of floats at the
cost of decreased performance. Benchmarks will follow to assess the
impact. This might especially problematic for the PFS when optimizing
routes.
To exercise this problem in the unit tests, the increase the amounts in `test_fee_round_trip` and add`test_fee_add_remove_invariant`.
- Safety
- Commits
- Specs
- Is it a …

Use `Fraction`s to increase fee calculation accuracy

---

raiden/ui/app.py

Fixes: #5153 
This case is triggers when trying to use --enable monitoring
on a private ethereum network
- Safety
- Commits
- Specs

Add a check to notify about the monitoring contract requirement

---

.pre-commit-config.yaml
pylintrc
raiden/ui/runners.py
tools/pre-commit/pre-commit-wrapper.py
tools/pylint/gevent_checker.py

This adds mypy to the pre-commit config and changes the way pylint is invoked via pre-commit.
Previously a repo-local pylint hook was used. That lead to pylint only being invokable if the project venv was activated in the context the pre-commit hook was called from. That usually isn't the case when using GUI git clients or IDE / editor integrations.
Instead it uses the default pylint mirror provided by pre-commit with a wrapper script that ensures the project requirements are available and adds the project root to the `PYTHONPATH`. That
allows the project local pylint plugins to be importable while still using the normal pre-commit hook venv isolation.
The same wrapper is used for mypy since it also needs access to third  party library code in order to successfully check type definitions. …

Improve pre-commit config

---

raiden/network/transport/matrix/transport.py

This lock is a large source of contention and from what I gathered from
@ulope it is not necessary. I don't completely understanding what was
the intention of the lock since there are no commits or comments that
explain the rationale, so I'm relying on @ulope's advice to remove the
lock.
Fixes: #5206
- Safety
- Commits
- Specs

Removed _getroom_lock

---

raiden/network/transport/matrix/transport.py

This just extends the docstring of the function `_get_user` after @ulope clarified it's usage.
- Safety
- Commits
- Specs

Extended docs for `_get_user` [skip tests]

---

raiden/api/rest.py
setup.cfg

Part of #4033 
Just enables stricter type checks for the REST API.
- Safety
- Commits
- Specs

Enable strict type checks for raiden.api.rest

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/bf3_multi_directional_payment.yaml

Fixes: #5205 
This adds a scenario that makes parallel payments in two different directions along a path.
Currently, there is a problem that one of the last asserts fail. It should not fail, so I recommend we merge the PR and then get it into the nightlies.

Add scenario for multi direction payments

---

docs/changelog.rst
docs/overview_and_guide.rst
raiden/network/rpc/client.py
raiden/tests/unit/test_app.py
raiden/ui/app.py

Fixes: #5217 
- Fully supports Infura
- Removes all warnings
- Safety
- Commits
- Specs

Fully support Infura and remove all warnings concerning its usage

---

raiden/network/transport/matrix/transport.py

These changes are mostly cosmetic, at first I assumed that the metadata was shared and it could be an attack vector. However @andrevmatos explained that the metadata is private, and therefore can only be modified by a malicious matrix operator. I'm opening the PR anyways with a comment that explains the above and also:
- Removes the automatic upgrade for the value of `network.raiden.rooms`
to a list. Since Red Eyes this value is always a list of strings, the
old format where it contains just a single room_id doesn't have to be
supported anymore.
- Adds a check for every entry of the metadata. If the values are
corrupted either there is a Raiden bug or a malicious matrix server.
- Reduces the critical section of the self._account_data_lock to exactly
the lines that interact with the …

`_get_room_ids_for_address` changes

---

raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_presence.py

Fixes: #5240
The container `_address_to_userids` is a defaultdict used to store the
known `UserId`s for a given `Address`. This container can be modified by
multiple threads (e.g. `UserAddressManager`, and blockchain event
handling that may start a whitelist/healthchecking), this can lead to
the container being modified while it is being iterated, which is a
runtime error.
This worksaround the problem by iterating over a copy of the keys,
instead of iterating over the dictionary key view.
- Safety
- Commits
- Specs

Fix runtime error: dict modified while iterating

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py

Review after #5241 
The default `__repr__` is missing a lot of information from the message
(currently the format is `<{klass} [msghash={msghash}]>`). This makes it
harder to correlate the logs from the sender with the receiver. This
just uses the DictSerializer so that all fields will be available.
- Safety
- Commits
- Specs

Extend message logging for Matrix

---

raiden/network/transport/matrix/utils.py

From the matrix documentation:
Controls whether the client is automatically marked as online by
polling this API. If this parameter is omitted then the client is
automatically marked as online when it uses this API. Otherwise if
the parameter is set to "offline" then the client is not marked as
being online when it uses this API. When set to "unavailable", the
client is marked as being idle. One of: ["offline", "online",
"unavailable"]
The default value from the MatrixSDK is to omit the value. This means
the `listen_forever` thread is sufficient to maintain the status of the
user.
- If it's a new feature, describe the feature this PR is introducing …

Removed extra call to `set_presence_state`

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_matrix_presence.py

This rewrites the displayname cache to avoid using the Matrix SDK internals.
- Safety
- Commits
- Specs

displayname cache rewrite.

---

raiden/tests/unit/api/test_encoding.py

pytest will interpret every class starting with `TestXXXX` as a test
class during test discovery,
From the [docs](https://pytest.readthedocs.io/en/2.8.7/goodpractices.html)
> Test prefixed test classes (without an __init__ method)
And that's why we were getting a warning:
```
raiden/tests/unit/api/test_encoding.py:6
/home/lefteris/ew/raiden/raiden/tests/unit/api/test_encoding.py:6: PytestCollectionWarning: cannot collect test class 'TestSchema' because it has a __init__ constructor (from: raiden/tests/unit/api/test_encoding.py)
class TestSchema(BaseSchema):
```
Since TestSchema appeared like a Test class to pytest and also had a
constructor via BaseSchema. Just changed the name to remove the warning.

Fix pytest warning about TestClass collection

---

raiden/routing.py
raiden/tests/unit/test_pfs_integration.py

Fixes: #5184 
When a request to the PFS has failed we no longer fall back to internal routing. Also modified the tests to confirm that we don't.
- Safety
- Commits
- Specs

Do not fallback to internal routing if PFS request fails

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_matrix_transport.py
raiden/tests/utils/mocks.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transport.py
raiden/ui/cli.py

The previous code tried to create a broadcast room and setup the alias
if either of these were missing. This introduce a serious race condition
for the discovery room setup for new servers deployment, which resulted
in the failure to run Raiden in our test network.
This commit removes that code that is susceptible to race conditions,
and instead move the responsibility of properly setting up the discovery
room and its alias to the Matrix operator.
- Safety
- Commits
- Specs

Simplified joining of broadcast rooms

---

raiden/messages/path_finding_service.py

Merge after #5249 
This changes the FeeUpdates timestamp to have no timezone.
This is related to raiden-network/raiden-services#619
- Safety
- Commits
- Specs

Fix fee update datetime type

---

raiden/storage/serialization/fields.py
raiden/tests/unit/storage/test_serialization.py

On any invalid input, marshmallow fields should only raise
ValidationErrors, not ValueErrors or TypeErrors. Otherwise problems like
https://github.com/raiden-network/raiden-services/issues/620 can happen.
Catching those exceptions in custom fields is consistent with the
builtin marshmallow fields and is preferable to catching those whenever
schemas are validated.
IntegerToStringField and OptionalIntegerToStringField are made more
robust by inheriting from the Integer field. They could also be done as
simply factory functions construction Integer fields, but I stayed with
classed for more consistency with the other fields.
- Safety
- Commits
- …

Only raise ValidationErrors in marshmallow fields

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_matrix_presence.py

Reverts raiden-network/raiden#5225 , this may the reason for the latest scenario player failures. Reverting the changes to test the hypothesis.

Revert "displayname cache rewrite."

---

raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/test_echo_node.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/events.py
raiden/tests/utils/transfer.py

Fixes: #4369
This is a follow-up for pr #4469. It adds the assertions for no unexpected unlock failures to some tests that are still missing them. With it all tests should be covered; see issue #4369 for the list of intentionally excluded tests.

Add missing no-failed-unlock assertions to integration tests

---

raiden/network/transport/matrix/__init__.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_matrix_transport.py

Random user IDs with the random sufix are not accepted by the current
version of the `eth_auth_provider`, any attempt to use that user name
would result in a crash. Therefore its usage was removed.
This changes the login process to assume the server will always have our
authentication plugin installed as requested by @ulope. The assumption
here is the Matrix servers used with Raiden are not part of the normal
Matrix federation, otheriwse these servers would replicate normal chat
messages that are not of interest to the Raiden network. Since we assume
there is this initial configuration step, it is also assume the plugin
will be installed.
- Safety
- Commits
- Regression test for …

Removed random user id / Assume Matrix auth plugin

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_matrix_presence.py

This commit changes when the display name cache is warmed. The goal here
is to not have a cache for usernames that are not whitelisted, since
that is not of interest for the Raidne node and can have a negative
impact for the startup performance, the reason being that the first sync
of the matrix server returns the presence update of every user in a
shared room, and since all Raiden nodes are in the broadcast rooms the
presence a node will receive a presence update for every single node on
the first sync, if a HTTP request is done for each address it can result
in thousands of request to the Matrix server, which has very bad
performance implications.
Additionally this adds a try-except to handle a corner case for a Matrix
federation that has a given userid but the profile of the user is …

Fixes for presence checking on first sync

---

raiden/tests/utils/transport.py

The `NoTLSFederationMonkeyPatchProvider.check_password` function wasn't a generator function which is required for `defer.inlineCallbacks()`.
It's normally not actually used (we only reach it if the EthAuthProvider couldn't authenticate a login attempt, which doesn't happen in the tests).
Since we don't perform any deferred calls a simple return statement works fine.

Fix matrix test helper

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

Fixes: https://github.com/raiden-network/raiden/issues/5219
This PR moves the close call of the bf1 scenario to after the balance asserts in order to make the results predictable. 
Currently the PR has not run locally due to other problems, but I suggest we just merge it and then if the nightlies show problems with the scenario itself, we fix it.

Move channel close to after balance assert [skip ci]

---

raiden/network/proxies/proxy_manager.py
raiden/tests/integration/long_running/test_settlement.py

- Removes unused function token_network_from_registry()
- next_block() was only used by an old test and is replaced by wait_until_block()
- Safety
- Commits
- Specs

Remove unused code from the ProxyManager

---

raiden/network/rpc/smartcontract_proxy.py

The `decode_transaction_input()` function is not used anywhere
- Safety
- Commits
- Specs

Remove unused function from smartcontract_proxy

---

raiden/tests/utils/transfer.py

Fixes a type error that was introduced in `raiden.tests.utils.watch_for_unlock_failures` a couple of days ago.

Fix a type error in test utils

---

raiden/raiden_service.py
raiden/tasks.py
raiden/tests/integration/api/fixtures.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/detect_failure.py
raiden/tests/utils/smoketest.py
raiden/ui/runners.py
raiden/utils/runnable.py
setup.cfg

The usage of getattr breaks the statically linting tools and let small
bugs cripple in.
- Safety
- Commits
- Specs

Remove getattr from runnable

---

raiden/ui/runners.py

The removal of the getattr function from the Runnalbe class broke the
initialization code, since that code expected all the methods form the
Greenlet class to be available.
This fixes the code by having two lists that differentiates both types,
and uses the underlying `greenlet` attribute when necessary.
- Safety
- Commits
- Specs

Fix the runner code

---

raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py

This made the unit tests fail occasionally. Hypothesis complains about having to generate too many examples due to the tests' many `assume()` statements.

Disable hypothesis health check on fee unit tests

---

docs/changelog.rst
raiden/log_config.py
raiden/tests/conftest.py
raiden/tests/integration/cli/conftest.py
raiden/tests/unit/test_logging.py
raiden/ui/cli.py
raiden/ui/runners.py

Fix #5050
In OSX Catalina the application is launching in a sandbox mode and as
such the current directory would be "/". Naturally raiden is not
allowed to write on the root directory and as such raiden crashes.
This commit attempts to address this by not writing the debug log file in
the current directory but in diffeent directories depending on the OS.
- OSX: ~/Library/Raiden
- Linux: ~/.raiden
- Windows: ~/AppData/Roaming/Raiden
- Safety
- Commits
- Specs

Do not write debug logfile in the current directory

---

raiden/messages/abstract.py

To generate the msghash value the message has to be packed into the
binary format, which is very time consuming. This removes the hashing
from the default `__repr__` implementation since the time spent on the
packing was significant (as measured by a sample profiler and later
plotted in a flamegraph).
thanks @LefterisJP for the profiling session

Remove msghash from the default __repr__

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/bf5_join_and_leave.yaml

Fixes: https://github.com/raiden-network/raiden/issues/5297
This adds a scenario for joining and leaving token networks and some different cases hereof. Currently the assert on line 143 of the scenario fails locally for some reason I haven't understood yet.

Add scenario for joining and leaving networks

---

raiden/tests/utils/mocks.py

Before this fix all tests that were instantiating Mock Raiden services
had a warning of uncaught and ignored exception in the logs during teardown:
```
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fed6e5fecb0>
File "/home/lefteris/ew/raiden/raiden/storage/sqlite.py", line 731, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fed6e5fecb0>
File "/home/lefteris/ew/raiden/raiden/storage/sqlite.py", line 731, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
```
Adding a proper `stop()` of the service's WAL storage fixes that.
- Safety
- …

Fix exception thrown due to MockRaidenService not stopping properly

---

raiden/tests/scenarios/bf4_multi_payments_same_node.yaml

We overlooked fixing a `wait` that was located inside a parallel task, where it does do much good. Moved it out of the task so that all payments can finish properly before asserting.

Move wait out of parallel task 

---

raiden/transfer/mediated_transfer/mediation_fee.py

Since a `None` value is not acceptable, instead of having two asserts
that may result in runtime errors, this enforces the function to be
called with a non-optional value, allowing mypy to catch call errors.

Tightned signature of `_collect_x_values`

---

.circleci/conditional_skip.sh

The check for the skip tag (`[skip tests]`) was also skipping builds
on branches, not only PRs. This was not intended and is now fixed.

CI: Never skip non-PR builds

---

raiden/transfer/mediated_transfer/mediation_fee.py

Calculating fees when the receiving channel is already "full" and can't receive a single token is an edge case that causes the calculation to misbehave. Just skip it like we do for the edge case of sending with a capacity of zero.
Regression test in https://github.com/raiden-network/raiden-services/pull/646.
Fixes https://github.com/raiden-network/raiden-services/issues/636.
Quality check list that cannot be …

Skip fee calc when no tokens can be received

---

tools/debugging/analyze_sp_logs.py

I ran into this while checking https://github.com/raiden-network/raiden/issues/5235
The problem was that the script didn't look for the latest log file.
This is fixed by ordering the files before selecting the latest ones.
- Safety
- Commits
- Specs

Fix analyze_sp_logs script

---

raiden/utils/profiling/timer.py

Before `__del__` called `stop`, which caused `stop` to be called twice
when the Timer is properly used. This caused an AttributeError on the
second `stop` call.
Now, `__del__` does nothing but assert that the Timer has been stopped.
- Safety
- Commits
- Specs …

Allow proper cleanup of profiling Timer

---

raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transport.py
raiden/ui/cli.py

Check that a federated broadcast room keeps working after the original server goes down.
This creates a federation of three matrix servers and a client for each.
It then checks that all nodes receive messages from the broadcast room.
Then the first matrix server is shut down and a second message send to
the broadcast room, which should arrive at both remaining clients.
Fixes: #5355
- Safety
- Commits
- Specs

Add federation room assumption test

---

raiden/messages/path_finding_service.py

Just a minor fix for stricter typing.
- Safety
- Commits
- Specs

Fix type of reveal_timeout in PFSCapacityUpdate

---

raiden/tests/integration/cli/test_cli_production.py
raiden/ui/runners.py

Fixes: #4610 
We are catching now the `ReadTimeoutError` in [runners.py](https://github.com/raiden-network/raiden/blob/develop/raiden/ui/runners.py). This can be caused if the transport server or the pathfinding service does fail to react to a request. 
The error message shown in that case is changed and is more generic now. 
- Safety
- Commits
- Specs

Catch urlib3 Read-Timeout

---

raiden/network/transport/matrix/client.py

This allows to wait for the next sync to make sure that you're working
on sufficiently up-to-date data.
This is required to make the PFS wait for the first sync until it
calculated routes. Otherwise it won't have valid presence information
for a while (see https://github.com/raiden-network/raiden-services/issues/658). But it's probably also useful in other cases.
- Safety
- Commits
- Specs

Add `synced` event to matrix client

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_presence.py

The presence handling was blocking the sync processing and thus causing
delayed message processing. Now we handle the presence asynchronously.
The updates are numbered to prevent old updates from overwriting more
recent ones.
The counter and pool would be nicer to have in the UserAddressManager. But that involved making that a greenlet. Let's see if this helps with our problems before spending too much time on it.
This should fix at least some cases of https://github.com/raiden-network/raiden-services/issues/673
- Safety
- Commits
- Specs

Handle matrix user presence in greenlets

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Updates the WebUI to v0.10.2. This is only a bugfixing release.
Check https://github.com/raiden-network/webui/releases/tag/v0.10.2 for changelog.
- Safety
- Commits
- Specs

Updates WebUI to v0.10.2

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py

Replaces https://github.com/raiden-network/raiden/pull/5425, which can't be reopened.
It is not important to call `_handle_response` in a greenlet. We wait
for it to finish anyway before calling it the next time.
However, this will increase the latency a bit because we only do the
next sync after the handling has been done. The different should not be
noticeable in most cases, but it's hard to tell for sure.
If you think this PR provides a bad simplicity/latency tradeoff, please close.
- Safety
- Commits
- Specs

Simplify by avoiding a greenlet

---

tools/debugging/stress_test_transfers.py

This script will orchestrate transfers among nodes in a chain topology,
the goal is to stress the system from the same APIs that an end user
would use, using the real infrastructure.
This script works in rounds, each round will:
- choose the initiator and target pair that have a path in the network.
- plan a set of transfers that are guaranteed to succeed, and that once
all have complete, the state of the channels is restored to the
initial position.
- the transfers from the plan are then scheduled in an arbitrary order
- the transfers are executed concurrently and their success is checked.
Besied the above, this script also manages the lifecycle of the Raiden
processes under stress.
Fixes: https://github.com/raiden-network/raiden/issues/5420

Added stress test script

---

raiden/tests/scenarios/ci/sp1/bf1_basic_functionality.yaml
raiden/tests/scenarios/ci/sp2/bf5_join_and_leave.yaml
raiden/tests/scenarios/ci/sp2/bf7_long_path.yaml

Fixes: #5451 
According to the issue the PR adds the transport04 server in the `node_options` for each node.
- Safety
- Commits
- Specs

Adding transport04 to bf1, bf5, bf7

---

raiden/api/rest.py

This PR fixes the connections API endpoint to also return integers as strings.
- Safety
- Commits
- Specs

Fixes connections endpoint to return integers as strings

---

tools/debugging/stress_test_transfers.py

This fixes a few problems with the stress script, namely proper exiting if a node dies, a bugfix on the wrong type of variable, and a small improvement on the logging.
closes #5420
```
Greatly simplified stress_test_transfers.py
- The current problems are not related to the amount of transfers, so
the planners to produce varying amount were removed.
- The planner signature was simplified to generate a single plan.
- A new planner that does a fixed number of transfers was introduced.
- The previous defaults took a long while to start stress testing with
mediated transfers, this changes the concurrent settings and the
number of transfers to speed things up.
- Some of the documentation was misleading because of changes introduce
while developing:
- The total capacity doesn't have to be …
```

stress script simplification

---

raiden/tests/scenarios/ci/sp2/bf7_long_path.yaml

I removed the shorter reveal and settle timeouts from this scenario in #5473 but forgot to remove the lock_timeouts in the transfers. That led to a shorter lock_timeout 30 than the reveal timeout, which on default is 50. 
The scenario, therefore, failed because no route could have been used.
- Safety
- Commits
- Specs

removes lock_timeout from bf7 [skip tests]

---

raiden/tests/scenarios/ci/sp1/bf3_multi_directional_payment.yaml

I removed the shorter reveal and settle timeouts from this scenario in https://github.com/raiden-network/raiden/commit/eae27322a48d664be029bec49526e05b2d78873b but forgot to remove the lock_timeouts in the transfers. That led to a shorter lock_timeout 30 than the reveal timeout, which on default is 50.
The scenario, therefore, failed because no route could have been used.
- Safety
- Commits
- Specs

Removes lock_timeout from transfers [skip tests]

---

raiden/raiden_service.py
raiden/routing.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/utils/mocks.py

Small change, this just uses the `PFSConfig` type instead of the generic `Dict[str, Any]`

using explicit type for pfs config

---

raiden/raiden_service.py
raiden/routing.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py

The message generated by the Raiden node is too generic, which makes it
harder to understand why a failure happened in the PFS. This change
forwards the error message given by the PFS to the Raiden API consumer,
which should help with understanding why something failed.

Forwarding PFS message to the API caller

---

tools/debugging/stress_test_transfers.py

This was added for two reasons:
- The old socket should go away, so that the healthcheck doesn't think
the node is running.
- The new socket has to use the same port number, otherwise the
RunningNode URL would have to be updated.

Added sleep on restart

---

raiden/utils/profiling/stack.py
tools/debugging/stress_test_transfers.py

Adds an option `pathfinding-service-address` in the `ini` used by the stress script, so that a user can configure the pfs that is used by the nodes.

Allow user to configure pfs url

---

CONTRIBUTING.md
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/conftest.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/utils/detect_failure.py

In some of our integration tests, it can happen that a node crashes silently and the test continues with a missing node. To make debugging flaky tests easier in the future, we want them to fail instantly and with a descriptive error message if that happens.
We already have a `@raise_on_failure` decorator for this, but it is not consistently used and easy to miss out on new tests. Therefore, this PR
- introduces a new decorator, `@expect_failure`, for integration tests where we actually expect node crashes
- enforces the use of either decorator on each test that runs `RaidenService` instances
- adds the appropriate decorators to all tests where it was missing.
Unfortunately, I did not find a way to set `raise_on_failure` as the default without getting too hacky with pytest hooks. The …

Check for node crashes in all integration tests

---

raiden/api/python.py

When doing a refund, the paymentmapping does not get cleaned up
properly. This causes an exception when querying the pending transfers
via API. This is just a work around the real fix will be #5515.
Closes #5480
- Safety
- Commits
- Specs

Fix pending transfers API call

---

docs/alderaan_mainnet_tutorial.rst
docs/index.rst
docs/overview_and_guide.rst

Update the Red Eyes tutorial in the docs, and the installation guide it relies on, to Alderaan. The role of the services has changed, a new token will be whitelisted, and one of the example requests was outdated too.
Closes #5431

Update Red Eyes tutorial to Alderaan

---

raiden/ui/cli.py

The previous filename format would clash if two nodes were started at
the same time with flamegraph enabled. This adds the address and
milisecond resolution to fix the problem.

Avoid conflicting data file names

---

raiden/api/rest.py

Partly fixes: #5472 
It is very important to have a timeout when stopping the wsgiserver, the existing endpoints only return once the operation is completed, which for a deposit it means waiting for the transaction to be mined and confirmed, which can potentially take a few minutes. If a timeout is not provided here, that would lead to a very and unpredictable shutdown timeout, which leads to problems with our scenario player tooling.
- Safety
- Commits
- Specs

Adding a wait of 5s before stopping the API

---

tools/debugging/stress_test_transfers.py

- disabled all fees, otherwise the balances would be unpredictable and
the test could not run in a loop.
- fixed the path generation functions, the backward transfers were
missing.

fix stress test

---

.circleci/config.yml
.circleci/run_tests.sh

This takes a long time and is unnecessary.
This reduces the runtime from 9:40 to 3:00.
Fixes: https://github.com/raiden-network/raiden/issues/5479
- Safety
- Commits
- Specs

Don't split logs for unit tests

---

raiden/api/rest.py
raiden/ui/cli.py
raiden/ui/runners.py

Without this, the orchestration tools cannot tell if the node is being
restarted or it crashed. This is a problem for the stress test and
scenario player.

Always return an error code if the node dies with an exception

---

raiden/raiden_service.py
raiden/routing.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_tokennetwork.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py

Extended routing error messages
Now the node will always validate the transfer before doing a PFS
request. If the node does not have channels that can even start the
transfers, then an error is reported and the PFS is not requested, this
includes:
- If there are no channels open
- If there are no channels with enough distributable to start to mediate
the transfer (this assumes transfers are not split)
- If there is no route to the target with any of the existing channels
(this assumes the route will always be in the same token network).

Better pfs error msgs

---

raiden/network/pathfinding.py
raiden/tests/integration/network/test_pathfinding.py
raiden/tests/unit/test_startup.py
raiden/ui/app.py
raiden/ui/checks.py
raiden/ui/cli.py
raiden/ui/startup.py

this just continues the changes from https://github.com/raiden-network/raiden/pull/5534 , it uses exceptions instead of `sys.exit`, and handles the exceptions on the top-level.

Cli improvements

---

raiden/network/proxies/one_to_n.py
raiden/tests/unit/test_app.py
raiden/ui/app.py
raiden/ui/startup.py

Fixes: #5550 
This PR removes a check during startup that looked for a token address from the one_to_n contract, but that contract doesn't have a token_address specified. 
It also fixes the initial problem that was introduced by what seems to be a copy/paste bug where the one_to_n proxy used the contract ABI of the monitoring services.
I am not sure if this is the best fix for this problem, but it works as a temporary fix during christmas time so that the nightlies start running again. At least the scenarios and Raiden itself now run locally again.

Fix contract for one_to_n proxy and remove wrong check on startup

---

raiden/network/utils.py
raiden/tests/unit/fixtures.py
raiden/tests/unit/test_utils.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements-docs.txt
requirements/requirements.txt

The `get_http_rtt()` utility method did not check the return code of the passed URL.
This lead to servers returning error status codes (4xx, 5xx) to still be considered usable.
Related: 
- #5544
- raiden-network/raiden-service-bundle#76

Ignore Matrix servers with non 2xx HTTP status

---

raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/integration/transfer/test_mediatedtransfer.py

Unskips three integration tests that seem to be no longer flaky. (10 test builds plus local runs with no failures.) These tests have been skipped since September 2019 or longer; since then, multiple changes to make the integration tests more reliable have happened, as well as changes in the tested code.
Also a minor correction of the stress test (make sure 0 isn't used as a payment identifier).
Closes #5133 
Closes #5195 
Related issue: #4312 (already closed)

Update on flaky tests

---

.codecov.yml

Our jobs submit code coverage separately and codecov.com merges them for
us. Without this change, the coverage informations is posted to github
as soon as it is submitted to codecov. This can irritate developers who
see low coverage for a while until the remaining CI jobs finish and add
their coverage.
- Safety
- Commits
- Specs

Codecov: post to github after coverage is complete

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/settings.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py

Fixes: #5276
~Blocked-by: #5352~
Don't listen on broadcast rooms even when erroneously invited by a malfunctioning / rogue peer.
Also adds a a regression test to prevent this from reoccurring.

Don't listen on broadcast rooms even when invited

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/network/utils.py
raiden/tests/unit/test_matrix_transport.py
raiden/tests/unit/test_utils.py

This does two changes:
- When starting up, instead of waiting for all servers to be ranked on RTT, it returns the fastest. The problem with the previous approach is that the function would always degrade to the slowest server, which adds latency.
- When starting up, first handle the inventory rooms, if the user has joined a broadcast room in the past, don't do it again since joining is a slow operation

Matrix small startup speedups

---

raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_data/db_statechanges.json
raiden/tests/unit/test_logging.py
raiden/tests/unit/test_sqlite.py
raiden/transfer/node.py
raiden/transfer/state_change.py

This value doesn't have to be synchronized with the protocol messages
and therefore doesn't have to go through the heavy weight code path of
the state machine.

Removed ActionUpdateTransportAuthData

---

docker/build.Dockerfile

This is a Hail Mary to see if perhaps #5511 can be fixed where the
dockerfile is not built for armv7l and aarch64.

Add libffi-dev to build.Dockerfile

---

raiden/constants.py
raiden/transfer/state.py

- The attribute last_transport_authdata is not set/used anymore.
- The state change for setting the auth data was removed, meaning the db
version has to be bumped (the previous state change can not be
decoded).
[skip tests]

Bugfix: Left over of the authdata removal

---

Makefile

make lint: Run flake8 before other checks and don't run mypy twice
- Safety
- Commits
- Specs

make lint: Run flake8 before other checks and don't run mypy twice

---

raiden/network/proxies/proxy_manager.py
raiden/utils/gas_reserve.py

The task `check_gas_reserve` was creating a token network proxy for
every existing token network. This should be avoided because the proxy
constructor will check the target address`s bytecode, to detect
configuration errors. The problem is that for a large registry, e.g. >=100 
token networks, executing the aforementioned test will take a
while. This is specially bad since the tokens are only necessary to get
the counter of current pending channel opennings, which is 0 for new
token network proxy (If the proxy does not exist then there is no
pending transactoins for it).
This commit changes the code to, instead of looping over all token
network addresses, to loop over the currently instantiated proxies. This
means the cost of instantiating the proxies will be amortized and only
paid when …

Fixes bad `check_gas_reserve` performance.

---

raiden/messages/synchronization.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/unit/test_notifyingqueue.py
raiden/utils/notifying_queue.py

~Review/Merge after #5216~ done
The `_sync` has to be done often enough because that is the mechanism
used by the Raiden node to keep it's status as online with the Matrix
server. If a `_sync` returns a huge amount of data that has to be
processed by the node, which may lead to the processing thread taking a
long time to process the server's response, it is possible for the time
in between `_sync` calls can be too large, leading to problems with the
presence checking of the node.
This introduces a message queue, guaranteeing the server responses are
processed in order, since that is necessary for the client state to be
consistent, and that the processing thread will not block the synching
thread.
- Safety
- …

Added Matrix sync response queue

---

raiden/transfer/mediated_transfer/initiator.py
raiden/ui/app.py

Fixes: #5575
We forgot to set `settle_timout` and `reveal_timout` in the config after https://github.com/raiden-network/raiden/pull/5548 so this fixes it. 
- Safety
- Commits
- Specs

Adds settle & reveal timeout back to Raiden Config

---

raiden/tests/scenarios/ci/sp1/bf1_basic_functionality.yaml
raiden/tests/scenarios/ci/sp1/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/ci/sp2/pfs2_simple_no_path.yaml

We introduced a check if the direct channel is usable for the transfer, so no IOU is sent in some scenarios, see #5532

Fixes scenarios after #5532 [skip tests]

---

raiden/messages/synchronization.py

I've seen a flame graph where >50% of the time was spent just packing
these two message types for signing. Using the python builtins is much
faster than using `map_abi_data`.
- Safety
- Commits
- Specs

Faster data packing for synchronization messages

---

raiden/storage/sqlite.py

by using `to_hex` instead of `to_checksum_address` during serialization.
If someone has an idea how to do that without monkeypatching (and without rewriting half of the serialization), that would be great!

Improve `write_state_snapshot` performance

---

.pre-commit-config.yaml

Using pre-commit wrapper fails due to wrong pip-tools dependency. The latest pip (>=19.3) needs pip-tools 4.2.0. 
This is a quick fix binding the additional dependency for pip-tools in `.pre-commit-config.yaml`  to `4.2.0`

Fix pre-commit wrapper for mypy and pylint

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_transport.py

Fixes: #3512
Prevent message batches exceeding max Matrix event size.
(This time without dependency on #5604 ;))

Respect Matrix max event size (redux)

---

raiden/raiden_service.py
raiden/tests/integration/test_integration_pfs.py

Raiden should send a PFSFeeUpdate whenever the balance in the channel
changes, also for deposit and withdraw events
Fixes: #5621
incl. tests

Fixes sending PFSFeeUpdates at every channel dep. or withd.

---

raiden/network/transport/matrix/transport.py
raiden/tests/mocked/test_matrix_transport.py

Fixes: #4111
Fixes: #4600
Changes the order of constructing the messages to be sent and their
removal from the RetryQueue. This prevents unnecessary duplicate sending.
Also adds a test for this behaviour.
Since this was touching the same places this additionally implements killing idle RetryQueues after a timeout (#4600).

Don't retry messages unnecessarily

---

raiden/messages/encode.py
raiden/messages/transfers.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/storage/serialization/types.py
raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/protocol.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/state.py

This has been broken in 0e9e3f5.
Closes #5612.
- Safety
- Commits
- Specs

Send PFS update after unlock

---

raiden/routing.py

This makes it obvious that this error originated in the PFS.
Are there any other cases that need prefixing? Logs like
```
"event": "Pathfinding Service rejected IOU"
"error": "ServiceRequestIOURejected('The provided payment is lower than service fee. (2104)')",
```
are already sufficiently descriptive IMO.
Closes https://github.com/raiden-network/raiden/issues/5645.
- Safety
- Commits
- Specs

Prefix ServiceRequestFailed errors with `PFS:`

---

raiden/storage/serialization/fields.py
raiden/storage/sqlite.py

This not only broke some filtering code which looked for checksum
encoded addresses, due to the monkeypatching it broke it in a way that
was not detected by the tests because the tests exercised the unpatched
code.
To gain back at least some of the speed improvement, we use
`bytes.hex()` for the networkx graphs when serializing.
- Safety
- Commits
- Specs

Remove monkey patching from `storage/sqlite.py`

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/utils/transport.py

change account data to local caching in transport.py
Fixes: #5558 
Refactoring the use of account_data feature of matrix. It is not planned to use one raiden address on different nodes. Therefore the account_data (which is currently only a mapping address -> room_ids) can be recreated and stored locally from the events fetched on first sync.

Remove use of Matrix "account_data"

---

raiden/network/transport/matrix/utils.py

Increase matrix connect timeout

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/utils/notifying_queue.py

This adds the time a particular response was received from the Matrix `/sync` call to the tuple stored in the queue.
Once that item is being processed the lag is logged.

Log the transport queue event processing lag

---

raiden/network/transport/matrix/utils.py

The `if` statement was comparing values of different types, it was
always false. Thanks @ulope for the catch.

bugfix: invalid if statement

---

raiden/api/objects.py
raiden/messages/path_finding_service.py
raiden/raiden_service.py
raiden/routing.py
raiden/services.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/scenarios/ci/sp1/bf2_long_running.yaml
raiden/tests/scenarios/ci/sp2/pfs8_mediator_goes_offline.yaml
raiden/tests/utils/network.py
raiden/tests/utils/transport.py
setup.cfg

This fixes a bug with (not) sending PFSFeeUpdatesduring withdrawels.
A mixed bag of minor improvements made during looking into https://github.com/raiden-network/raiden/issues/5627
- Add PFS error message to log
- Remove duplicated line from bf2 scenario
- Test target and mediator in `test_pfs_send_capacity_updates_during_mediated_transfer`
-  Test target in `test_pfs_send_capacity_updates_on_deposit_and_withdraw`
- Improve tests by using `TestMatrixTransport` instead of monkey patching
Also fixes the first two tasks of https://github.com/raiden-network/raiden/issues/5652
- Safety
- Commits
- Specs
- Is it a user facing feature/bug …

Improve test for PFS update messages (also fixes a bug)

---

raiden/tests/integration/test_integration_pfs.py

I thought I fixed the flakyness on `test_pfs_send_capacity_updates_on_deposit_and_withdraw`, but I was wrong.
Tracked in https://github.com/raiden-network/raiden/issues/5680

Skip flaky test

---

raiden/ui/cli.py

Utility to help understand thread starvation, the code will measure the
amount of time the event loop is waiting. A low waiting (<1%) time shows
there is a high cpu pressure, and therefore thread starvation.

Debug: Added Idle measurement

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Duplicates scenarios for Asnible-setup testing.
Scenarios are no longer divided up on the project level, and all scenarios are supplied by default in the docker container to run the nightlies. The distinction between sp1 and sp2 will therefore become deprecated and removed after migration is complete.

Duplicate Scenarios for Ansible Testruns

---

raiden/messages/synchronization.py
raiden/messages/transfers.py

This increases performance while keeping the results identical.
This PR also includes two small bug fix commits.
Closes https://github.com/raiden-network/raiden/issues/5694

Use python builtins to pack transfer messages

---

raiden/ui/cli.py
raiden/ui/runners.py
raiden/utils/debugging.py

During startup the node will synchronize with the blockchain, while
doing so it will fetch large batches of events that have to be decoded
and converted to internal state changes, which will take considerable
time. To avoid crashing the node during initialization the monitoring is
only enable after the runnables have started.

Ignoring slow funciton during startup

---

requirements/requirements-ci.in
requirements/requirements-ci.txt

Upgrade is needed to fix a vulnerability:
https://github.com/advisories/GHSA-7fcj-pq9j-wh2r
It's Windows only so it does not affect Raiden, but upgrading should be good nonetheless.
@ulope take a look please
- Safety
- Commits
- Specs

Bump pyinstaller to 3.6 - CVE-2019-16784

---

raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py

This isn't necessary since https://github.com/ethereum/web3.py/pull/893

Don't encode addresses as checksums with web3

---

raiden/network/transport/matrix/client.py
raiden/ui/cli.py
raiden/utils/debugging.py

The problem with the previous code was the priority of the prepare
watcher. Its priority was too high, so the timing included the runtime
of gevent's deferred callbacks. This fixes the problem by setting a low
priority for the prepare handler and a high priority for the check
handler.

Fix Idle measurement

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/utils/notifying_queue.py

The previous code was calling _handle_response individually for each
entry in the queue. Which means each response would be a separate set of
StateChanges. With this change all the currenlty pending messages are
processed in a single batch, this reduces the number of deepcopies, and
databases writes from `n` to `1`.

Batch processing of the current queue

---

raiden/storage/serialization/serializer.py
raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/test_channel.py
raiden/tests/unit/transfer/test_node.py
raiden/tests/unit/transfer/test_views.py
raiden/transfer/architecture.py
raiden/transfer/node.py
raiden/utils/copy.py
raiden/utils/echo_node.py

After profiling @karlb found out that deepcopy is measurably slow, the fix is to use a different approach to deepcopy the data, which can be done using a serialize/deserialize cycle. This is not optimal, but it is significantly better than deepcopy, this just changes the other places that still used the stdlib implementation.

Replaced deepcopy with faster implementation

---

raiden/network/transport/matrix/transport.py

Removes the following warnings for me:
```
AssertionError
2020-01-20T15:42:30Z <callback at 0x10c68b780 stopped> failed with AssertionError
AssertionError
2020-01-20T15:42:30Z <callback at 0x10c68b690 stopped> failed with AssertionError
AssertionError
2020-01-20T15:42:30Z <callback at 0x10c68b780 stopped> failed with AssertionError
AssertionError
2020-01-20T15:42:30Z <callback at 0x10c68b0f0 stopped> failed with AssertionError
AssertionError
2020-01-20T15:42:30Z <callback at 0x10c68b780 stopped> failed with AssertionError
AssertionError
2020-01-20T15:42:30Z <callback at 0x10c68b140 stopped> failed with AssertionError
AssertionError
2020-01-20T15:42:30Z <callback at 0x10c68b780 stopped> failed with AssertionError
AssertionError
2020-01-20T15:42:30Z <callback at 0x10c68b690 stopped> failed …
```

Fix assertions during response_queue cleaning

---

raiden/messages/abstract.py
raiden/network/transport/matrix/utils.py

This reduces the time we spend on checking message signatures.

Cache parsed messages and their `sender`

---

raiden/blockchain/decode.py
raiden/constants.py
raiden/network/pathfinding.py
raiden/routing.py
raiden/tests/integration/network/test_pathfinding.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_pfs_integration_refactored.py
raiden/tests/unit/test_startup.py
raiden/tests/unit/transfer/test_source_routing.py
raiden/tests/unit/transfer/test_views.py
raiden/tests/utils/factories.py
raiden/transfer/state.py

The race happens because the default number of confirmations blocks is different on Raiden and the PFS.
This will check the reported confirmed block of the PFS and if the channel has not been seen by the PFS, Raide will wait before sending the PFS request.
This requires: https://github.com/raiden-network/raiden-services/pull/705

Fix pfs request race condition

---

raiden/network/pathfinding.py
raiden/tests/integration/network/test_pathfinding.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_pfs_integration_refactored.py

We assumed a different response from the PFS in
https://github.com/raiden-network/raiden/pull/5671 than is actually
returned.
- Safety
- Commits
- Specs

Fix access to confirmed_block_number in PFS resp.

---

tools/debugging/stress_test_transfers.py

This is just convenient to get the backup after the first run
[skip tests]

stresstest: add option to wait after first sync

---

docs/changelog.rst
raiden/connection_manager.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/long_running/test_token_networks.py

Fixes: #5583 
- Safety
- Commits
- Specs

 If a node is offline connect() no longers opens a channel with it

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml

The timeouts have only been temporarily changed to accommodate stricter values in a specific contracts deployment. With the latest deployment, this is not needed, anymore.
Also fixed https://github.com/raiden-network/raiden/issues/5741, which only a result of the temporary changes.

Revert scenario timeouts

---

raiden/network/proxies/token_network_registry.py
raiden/utils/debugging.py

Instead of letting the measurement list go empty, this handle the case were the last measurement was larger than the `measurement_interval`, and added a special log line for it.

Idle: Added special case for blocking functions

---

raiden/network/proxies/token_network_registry.py
raiden/network/proxies/utils.py

This is useful when the same transaction is sent twice, which is the
case for some of our tests.

Added token to identify the transaction.

---

requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements-docs.txt
tools/debugging/stress_test_transfers.py

Adds py-spy as a dev dependency and change the stress test to use it. This should be a more performant version since it is effectively a sampler profiler, while our current implementation is really a tracer.

Added py-spy and changed the stress script to use it

---

raiden/messages/abstract.py
raiden/network/transport/matrix/transport.py

`RetriableMessage` is used as a mixin in `SignedRetrieableMessage`.
Since it didn't inherit from `Message` before checks of the form `if isinstance(message, RetrieableMessage):` (where `message` was annotated as `Message`) caused mypy to never evaluate the branch since the condition could never (from mypy's perspective) be true.
Since Python uses C3-linearization for multiple inheritance the resulting diamond MRO will not cause any issues.

Make `RetriableMessage` inherit from `Message`

---

raiden/api/python.py
raiden/connection_manager.py
raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/ui/checks.py
raiden/ui/startup.py
raiden/waiting.py

Those were found with a newer `mypy`, but I couldn't remove all warnings
right now, so I picked the easy ones out.
This is mostly about `bytes` objects in format strings and some other
small changes.

Typing improvements, mostly to error messages.

---

raiden/network/transport/matrix/utils.py

Setting the display name is a bit slow (as measured with mitmproxy

skip set display name if not necessary

---

raiden/api/python.py
raiden/blockchain_events_handler.py
raiden/message_handler.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/tests/integration/network/transport/test_matrix_transport.py

The initiator has to start a health check to the target on the beginning
of a transfer, this is necessary to processs the secret request message
from the target. The problem is that the health check may trigger the
creation of a room, which adds a measurable amount of latency to the
start of a transfer. This changes the code so that a healthcheck can be
done in the background, allowing this latency to be hidden from the
first transfer.

Added async health check.

---

raiden/utils/profiling/greenlets.py

This makes it easier to find the corresponding entries in other logs.

Use datetime in switch tracing

---

raiden/constants.py
raiden/network/pathfinding.py
raiden/network/transport/matrix/transport.py
raiden/settings.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/network/test_pathfinding.py
raiden/ui/app.py
raiden/ui/cli.py

During `setup_matrix` the yaml with the servers URLs should only be
downloaded if the configuration was set to auto.
This also removed the magic constant.

Dont download server list if an URL is provided

---

.circleci/config.yml

The current version of Codecov keeps sending failed status reports to
github for no reason. This will be reverted when their next version is
released.

Temporarily disable Codecov

---

raiden/raiden_service.py

Recoverable errors are by definition expected and recoverable, it should
not be logged as an error since that leads to confusion.

Decrease log level for recoverable errors.

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt

Upgrade cryptography to fix a openssl dependency issue on macOS:
https://github.com/pypa/pip/issues/7254

Upgrade cryptography to 2.8

---

raiden/api/rest.py
raiden/tests/integration/api/test_restapi.py

The exception for an already existing channel has to be handled and the
execution has to fall-through, otherwise the deposit will not be at the
expected values.

Handle channel open race

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/mocked/test_matrix_transport.py

There was some inconsistency of how filters are used upon `sync()` request.
- Filtering Broadcast Rooms: Filtering events from broadcast rooms was done by creating a server-side filter and then passing the received `filter_id` upon sync.
- Limiting timeline events upon first sync (to remove long first sync periods) to zero events was done by setting the sync_filter (json) within the client
This introduced a little bug because upon sync. The `sync()` method always got the `filter_id` passed. Therefore the first sync was actually never been filtered.
All filters are handled by server-side filtering. Filters are applied by using the `filter_id` consistently.
The client has a `filter_id_to_filter` dictionary.   Whenever a filter is created the filter gets stored in the dictionary. 
Also …

Create consistent Filtering model on sync()

---

tools/debugging/extract_sp_exceptions.sh

We use regexes to parse the directory listings. The markup for those has
changed due to the switch to nginx. This commit parses the new markup.
HTTP is not well standardized for doing such operations. Using an scp
like tool with wildcards would be nicer and more robust.
I also added some code to write the errors into separate files in an `errors` dir.

Parse nginx directory indexes

---

raiden/tests/scenarios/bf2_long_running.yaml

Fixes bf2 scenario after #5770 Opening an already existing channel will return a 200

Opening an already existing channel returns 200 after #5770

---

raiden/tasks.py

Killing a greenlet raises an exception. In `check_version`, this
exception can trigger the finally clause, causing the greenlet to wait
for three hours before terminating. Since the raiden client waits for
all greenlets to terminate, this will keep the whole raiden client from
terminating for three hours.

Fix slow stop of check_version greenlet

---

docs/changelog.rst
docs/rest_api.rst
raiden/api/rest.py
raiden/exceptions.py
raiden/network/proxies/token_network_registry.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/network/proxies/test_token_network_registry.py

This introduces a new exception for this case and handles it in the API.
Fixes #5779

Handle the token network maximum being reached

---

raiden/network/transport/matrix/transport.py

The whitelist and track_address_presence still have a measurable
performance impact, their removal has a positive impact in performance,
so this offloads the whole processing into the background task.

Removed duplicate efforce from async health check.

---

raiden/network/transport/matrix/client.py

I think we had a mental flaw here, the first sync is `sync_iteration` 0, that is measured when `sync_iteration` 1 is called.
So then the first "proper" sync is done, which will be evaluated in `sync_iteration` 2. Therefore we need to skip that one as well.

Correctly skip the first full sync

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml

Reduce waits in scenarios.
- This improves runtime of all scenarios (in sequence) by 91mins
- It should be safe as we use `wait_blocks: 2` (which is max. 30s on goerli) in other scenarios for a while already

Reduce scenario waits

---

raiden/tests/scenarios/bf2_long_running.yaml

The deposit is successful to the existing channel,
that messes with the numbers. Test cases already covered in api tests
Fixes: #5801

We need to remove the whole check after #5770 [skip tests]

---

tools/debugging/stress_test_transfers.py

Without this check, the greenlet will continue past that point and start
the new node even when the old one did not exit cleanly. When starting
the new node, a switch happens right after the Popen, before the new
process is tracked in the nursery. This causes the process to be left
over when the stress test script stops.
To debug and test this error case, I just added an exception during the
raiden shutdown, which show the above behaviour completely reproducibly.
See https://github.com/raiden-network/raiden/issues/5790.
[skip tests]
- If it's a refactoring, …

Check exit code when stopping node (stress test)

---

raiden/utils/http.py

They are used in some integration tests, in one of the tools and in the
smoketest, but not in the actual client. So they are irrelevant for the
coverage measure.
This closes the last of the unit test coverage issues.
Closes: #3887

Ignore mirakuru subclasses in coverage reports

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml

This reverts commit 46fb5714196623121b85cff825ffa37c25b460cf.
I thought we were faster than we are, or at least there are edge-cases in the SP.
Fixes: https://github.com/raiden-network/raiden/issues/5814

Revert "Reduce scenario waits [skip tests]"

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Fixes: https://github.com/raiden-network/scenario-player/issues/472
This upgrades `mirakuru` to the latest version. This adds a check that prevents the above error: https://github.com/ClearcodeHQ/mirakuru/blob/4e6a948b927eac249807c61a4365c0a072ff903d/src/mirakuru/base.py#L500

Upgrade mirakuru to latest version

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml

Fixes: https://github.com/raiden-network/raiden/issues/5818
This increases the `settlement_timeout` of the MS scenarios in order to make sure that the MS has time to kick in. We should keep in mind that this is just temporary until we are sure that the MS is fast enough to always react. Or alternatively, make the lowest allowed `settlement_timeout` higher in the contracts.

increase settle timeout for MS scenarios [skip tests]

---

CONTRIBUTING.md
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/detect_failure.py

Some tests that use the `raiden_network` and `raiden_chain` fixtures stop and restart their nodes, which makes `raise_on_failure` lose track of uncaught exceptions that might happen inside of them. This PR adds a function for the safe restarting of nodes and applies it everywhere in the tests.
Fixes #5555

Make @raise_on_failure work with node restarts

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

Tonight the BF1 scenario failed because some `assert_sum` tasks failed. This increases the wait before.

Increase waits in BF1 before assert_sum tasks [skip tests]

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/mocked/test_matrix_transport.py

This will be used in the services to only listen to the rooms we want
Ref.: https://github.com/raiden-network/raiden-services/issues/713

Allow whitelisting rooms in matrix sync filter

---

raiden/network/transport/matrix/client.py

This logged a field of the base class which never changed.

Fix logging sync filter

---

raiden/storage/serialization/serializer.py
raiden/tests/unit/test_serialization.py

You should not be able to crash a raiden node by sending bogus data, so
this must raise a SerializationError and no other exception.
Closes https://github.com/raiden-network/raiden-services/issues/717.

Catch error when message is not a dictionary

---

raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/tests/integration/api/utils.py
raiden/tests/integration/test_recovery.py
raiden/transfer/channel.py
tools/debugging/stress_test_transfers.py

Fixes a number of typos in lines that match `/wh?e.?re/i`.

We're where we were (fix typos) [skip tests]

---

raiden/network/transport/matrix/transport.py

```
The healthcheck does the following:
- whitelist the address
- create the matrix room if necessary
- search for every user for the given address
- validate all their signatures
- updates the address manager with the new presence data
These operations in aggregate are very expensive, and once the
healthcheck is enabled, the updates from /sync should be sufficient to
keep the transport's state up-to-date.
This short-circuits the above operations, so that we don't have
extra load with the synapse server.
```

Optimization: Healthcheck should be a noop on the second call

---

raiden/tests/integration/api/test_pythonapi.py

Skipping the test, the fix is tracked by https://github.com/raiden-network/raiden/issues/5744

Skip flaky 'test_token_registered_race' [skip tests]

---

tools/debugging/extract_sp_exceptions.sh

The run-nightlies script was changed to automatically compress the logs
of the services, this results in a significant shorter download time.
The logs of the MSs were also added, and now they can be downloaded with
a single `scp` command, which provides a nice progress bar.

Download all services logs, faster.

---

tools/debugging/stress_test_transfers.py

The stress test assumes that the tokens can be transferred back and
forth without paying any mediation fees. To make sure that this is the
case, we must always set the fees for the used token to zero.
Before this commit, the token address was hard coded.
[skip tests]

Stress test: turn of fees for token given in conf

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py

Matrix requests will now use "Raiden" followed by the version number as
user agent string. This provides additional context when debugging and
is generally good behavior.

Use raiden user agent string

---

.circleci/config.yml

The upload of the artifacts can take a few minutes in the worst case,
the approach recommended by the circleci documentation is to upload a
compressed file.

compressing log run data

---

.circleci/config.yml

Without this, the logs for failed runs will be unavailable. Thanks @karlb
for the fix.

Always compress the log files

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_matrix_transport.py
raiden/tests/utils/transport.py
raiden/utils/typing.py

Rooms need to be checked if users from multiple nodes joined. As a safety measurement, a room should always be left when multiple users joined the room. Also when joining a room with multiple users the node immediately leaves the room again.
For better handling, if room joining or leaving fails a wrapper for API calls triggered by the transport is introduced. This refactoring removes code redundancy and aims for better handling of MatrixErrors in the future. 
The PR also includes the handling of the rare case when an invitation is received from an offline synapse server or a de-whitelisted one. It furthermore rejects the invitation to not receive it again on next restart.
Fixes: #5596, #5640

Room protection in case of multiple nodes 

---

.circleci/config.yml

This is already done by after each commit in the tag `latest` and it didn't work either.
Part of https://github.com/raiden-network/raiden/issues/5737

Remove nightly docker image build

---

tools/transfer_eth.py

Each transaction slot can only be used once

fix transfer_eth

---

raiden/network/proxies/token_network.py

The channel id will be None if there is no channel, the previous message
was ignoring that case.

Fixed precondition message

---

raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_presence.py

In my thought model, we can skip the call when we already know
the reachability. Please double check that this is actually true!
Alternatively, we could call `start_health_check` less often. I'm not
sure it's needed in `start_mediated_transfer_with_secret` and
`handle_message_lockedtransfer`.
Or we could do a similar check in `start_health_check` to avoid even more work.
This change makes transfers in the stress test twice as fast for me.
- If it's a refactoring, describe why it is necessary. What are its pros and cons in respect to the previous code, and …

Skip unnecessary track_address_presence calls

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py

There was a little bug that the user tried to leave the broadcast rooms if multiple members joined which happens by definition. This is only a problem at first sync because we do not filter state events of broadcast rooms there. In all other syncs it shouldnt be a problem. Once we switch to filter the state events in all syncs this shouldnt be a problem, anymore. The doublecheck before leaving might be still worth to keep.

Broadcast rooms are not left after multiple members joined

---

raiden/api/python.py
raiden/network/proxies/token_network.py
raiden/raiden_service.py
raiden/tests/integration/api/test_pythonapi.py
raiden/utils/gas_reserve.py

Under some corner cases this can break the gas reserve check. This,
however, is not a security issue, and should be a hard to hit corner
case. Since the change to synchronize the open counter and the API
requires a big refactoring to the `new_netting_channel` method, it is
not done here.

Allow parallel channel open

---

docker/build.Dockerfile

- Our nightly builds on arm architecture failed due to missing wheel package
---> Added installation of wheel in dockerfile

Installing wheel additionally

---

raiden/tests/unit/test_utils.py

The test failed in
https://app.circleci.com/jobs/github/raiden-network/raiden/110849
I doubled the safety margin for this test, which should be enough
considering that it rarely failed in the past.

Avoid flakyness in test_get_http_rtt_happy

---

raiden/network/proxies/token_network.py

Fixes: #5447
Only hold the lock until the set_total_deposit is sent, the transaction should be correctly ordered because of the nonces.
This is a test PR, the change seems to fail with the concurrent deposit test.

Reduce critical section of approve

---

raiden/network/transport/matrix/transport.py
raiden/raiden_service.py

We had two separate concepts of whitelisting and health_checking addresses. These concepts are quite similar and had to coexist. By recent optimizations it is not necessary anymore to keep the difference between the two of them. We can now merge it together and just call it healthchecking. We only healthcheck users of interest and "whitelist" them therefor. The UserAddressManager keeps this information about known nodes. 
Fixes: #5858

Remove Concept of Whitelisting

---

raiden/network/transport/matrix/client.py

The exemption has been introduced when we counted the time between sync
starts. This was a problem for initial (potentially slow) syncs. Now we
check the time between syncs, which will only fail when the raiden node
is blocked by too high load or a bug. We do want an error in those
cases, so the exemption does not make sense anymore and only masks the
problem which will manifest as nodes being treated as offline.
Closes https://github.com/raiden-network/raiden/issues/5898
- If it's a refactoring, describe why it is necessary. What are its pros and cons in …

Check sync timeout during all iterations

---

.circleci/config.yml

For unknown reasons, the previous version caused tar files that were
gzipped twice. I did not find out why that was the case, but this code
results in a tar that is only gzipped once.
I also changed the name of the download to include the `.tar.gz` ending.

Gzip CI artifacts only once

---

raiden/network/transport/matrix/client.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/utils/synapse_config.yaml.template
raiden/tests/utils/transport.py

Server Admins should be able to purge inactive users from broadcast rooms. In order to do so they need the respective power levels (at least Moderator >= 50). The first Server in the list of known servers will create the broadcast rooms. Upon creating the room, the API allows adding multiple parameters to the request to modify the room settings. Currently the python sdk does not expose this feature.
In order to enable **server side inactive user purging** the room creator aka the first server in the list of known servers must be able to set the power levels upon creating the room. This PR exposes the API feature to do so to the matrix client. When creating the room it will give the respective rights to the other server admins to be able to purge inactive users. 
> **_NOTE:_** This PR …

Change Matrix API to enable admin rights for ServerAdmins in Broadcast Rooms

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/sync_progress.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/ui/runners.py

This is a proposal to introduce a new Helper Class to make writing tests easier and prevent flakiness. This is achieved by the helper class storing information about the current sync process and if responses are already processed or not.
I experienced that some integration tests are flaky due to the fact of asynchronicity between the nodes, matrix servers as well as the chain and the difficulty to handle a proper synchronization. When a test, i.e. relies on a message to arrive at another node, one has to wait for the syncing and processing of the response to be done properly. Since we have some upper bounds for syncs (block time, matrix sync timeout) we use the time as an indicator that a message should have arrived. Especially when you do not know the system on where the test runs (aka …

Sync Helper to control the sync and response processing in tests

---

.circleci/config.yml

bash only uses the first element when you write `$list`, you need
`${list[@]}` instead.

Upload all logs as artifacts

---

raiden/messages/metadata.py

These dataclasses are frozen, so it's safe to use `cached_property`.
Otherwise, the hashes get recalculated each time messages containing
metadata are used in a comparison, e.g. in
https://github.com/karlb/raiden/blob/1021fde2412bf16ac72885ffe6138e38c617e719/raiden/network/transport/matrix/transport.py#L140-L143

Cache metadata hashes

---

raiden/tests/integration/api/test_pythonapi_regression.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/transfer.py

Many integration tests have ad-hoc timeouts of 10 or 30 seconds when waiting for transfer-related events, so they may become flaky in case of performance issues. So we replace these timeouts with `BlockTimeout`s and wait until the settle_timeout of the channel in question.
Follow-up to #4579
Fixes #4524

Use block timeouts in integration tests

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml

Increasing the settle timeout doesn't help, because the MS has to assume
the minimal possible settle timeout anyways.
This makes the scenatios a bit faster to run.
@karlb Feel free to stall this while investigating #5919

Shorten MS scenarios

---

raiden/network/transport/matrix/client.py
raiden/tests/utils/transport.py

When joining a room we populate the aliases. This used to be done by downloading the entire rooms state only to then immediately discard any non-alias event.
This PR changes the behaviour so that only alias events are fetched form the server.
Unfortunately due to a limitation in the Matrix API it's not possible to query for *all* aliases of a room, only aliases for a given specific server can be fetched, see: matrix-org/synapse#6908
However, since in Raiden we always have server local aliases set for all broadcast rooms, this is sufficient.

Optimize room alias fetching

---

raiden/tests/fixtures/variables.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py
raiden/tests/utils/eth_node.py
raiden/utils/keys.py

Replaced these 3 fixtures:
- blockchain_private_keys
- blockchain_rpc_ports
- blockchain_p2p_ports
With just a fixture named `eth_nodes_configuration`. The same data is
available but through a datastructure.

fixtures: simplified blockchain fixtures

---

raiden/api/python.py
raiden/api/rest.py
raiden/exceptions.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/api/test_pythonapi.py

Raiden crashed when we tried to send a payment to ourself at the room_creating here https://github.com/raiden-network/raiden/blob/561370ae3406e90b4d7e2d62ac12c0f46587875e/raiden/network/transport/matrix/utils.py#L896-L903
We should catch this error already in the api when a user tries to transfer to himself.
Fixes: #5922 

Catches exception if tranferring to myself

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/mocked/test_matrix_transport.py

First sync for large rooms takes quite a while to process all state events (At 30000 state events ~ 5s). The only reason why we keep processing these events at first sync is to see if we already joined the broadcast rooms or not. This was done because it took a long time to join the rooms. This problem was recently fixed by #5892. 
Since the API call of joining broadcast rooms should be fast now (It used to download all 30000 state events) the transport can now simply call the `join_room()` API even if it already joined the room. 
Broadcast Rooms can be filtered even at first sync.
`Initialize_room_inventory` can be removed due to redundancy. 
Fixes: #5913

filter broadcast rooms at first sync

---

raiden/tests/scenarios/bf5_join_and_leave.yaml

Ugly, but adding a wait after nodes joined the network seems to help in that specific scenario.
Fixes: #5918

Adds wait to bf5 to prevent lock_expire [skip tests]

---

tools/debugging/replay_wal.py

Before, running the script failed for me when redirecting the script
output to a file with
```
File "tools/debugging/replay_wal.py", line 289, in <module>
main()  # pylint: disable=no-value-for-parameter
File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/karl/tools/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "tools/debugging/replay_wal.py", line 284, in main …
```

Terminal width fallback for replay_wal.py

---

raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
raiden/tests/smart_contracts/RpcWithStorageTest.sol

A reliable strategy is necessary to avoid race conditions on
approve+setTotalDeposit. Polling for the transaction to be mined seems
to be the only reliable way the test could pass

Assumption test for estimate gas on depend transactions

---

raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/utils/network.py
raiden/tests/utils/smartcontracts.py

Review/Merge after: https://github.com/raiden-network/raiden/pull/5886
With this change the smart contracts are deployed in parallel during fixture setup.
Before (measured on e3ff9b4c5fa1c3304f7bd695b3451e95a65a51c8):
```
38.57s setup    raiden/tests/integration/test_blockchainservice.py::test_channel_with_self[0-1]
0.60s teardown raiden/tests/integration/test_blockchainservice.py::test_channel_with_self[0-1]
0.05s call     raiden/tests/integration/test_blockchainservice.py::test_channel_with_self[0-1]
```
After
```
24.32s setup    raiden/tests/integration/test_blockchainservice.py::test_channel_with_self[0-1]
0.72s teardown raiden/tests/integration/test_blockchainservice.py::test_channel_with_self[0-1]
0.09s call     raiden/tests/integration/test_blockchainservice.py::test_channel_with_se …
```

Fixtures parallel smart contract deployment

---

raiden/network/pathfinding.py
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/unit/test_pfs_integration.py

The Semaphore was not set properly. Every transfer started its own semaphore within the for loop before. We changed that to a global Semaphore within the module.
Fixes: #5951 
We might think about a follow-up issue to establish a more elaborated semaphore handling like described in the issue. However, this quick fix seems to solve the problem.

Fixing a bug with the Semaphore

---

raiden/network/transport/matrix/transport.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_raiden_event_handler.py
raiden/tests/utils/mocks.py
raiden/tests/utils/protocol.py
raiden/tests/utils/transport.py

During initialization of the Raiden node events are restored from the
snapshot and pushed to the transport layer. Each message was queued
individually, which depending on how the greenlets are scheduled by the
gevent's hub may result into multiple unnecessary HTTP requests to push
the messages to Matrix. This results in a slow restart of nodes in the
stress test, which may have lots of pending messages in the queue.
This commit fixes the above by pushing the events in batch, which
doesn't rely on the greenlet scheduling to reduce the number of HTTP
requests.

Batch event processing

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_cli.py
raiden/utils/cli.py

With the recent changes, some small refactorings and optimizations are possible to make the code more readable. 
This includes:
- remove the redundancy of `should_listen` and `stop_event`
- remove `first_sync` flag at sync
- prevent possible attack vector of joining rooms with large number of addresses due to ecrecover
Fixes: #5921

Refactoring in client.py/transport.py

---

raiden/network/rpc/client.py
raiden/tests/unit/test_cli.py
raiden/utils/typing.py

```
The method `allocate_next_slot` existed for 3 reasons:
- Allow concurrent transaction to be instantiated (without waiting for
the precondition/postcondition validation).
- Protect the `_available_nonce` with a lock, since the `nonce` must be
used only once (ignoring transaction overwrites). The lock exists to
ensure only one transaction will use the given nonce.
- Wrap the value of the `nonce` in a poors man linear type, to log and
throw an exception when the allocated nonce is not used to avoid
stalling the account's transaction queue.
However, the code had an annoying corner case. If a transaction is
created using values that cannot be correct serialized, or if the
blockchain node rejects the transaction, the nonce would be allocated
for a transaction that would never be sent. If …
```

Hardened nonce usage

---

.circleci/config.yml

Add a job which checks out the Scenario Player and runs unit tests and smoketest in the Raiden CI with the current Raiden branch. 
It checks the basic integration of the SP and Raiden
Fixes: https://github.com/raiden-network/scenario-player/issues/496

Include Smoketest of SP in Raiden CI

---

raiden/tests/integration/cli/conftest.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transport.py
raiden/ui/cli.py

This encapsulates a large part of the smoketest setup into its own reusable contextmanager. This simplifies the code in `raiden/ui/cli.py` and allows progress on https://github.com/raiden-network/scenario-player/issues/491

Factor out smoketest setup into contextmanager

---

raiden/api/python.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/network/proxies/user_deposit.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/utils/network.py
raiden/ui/cli.py

- renamed `deposit` to `approve_and_deposit`
- renamed `set_total_deposit` to `approve_and_set_total_deposit`.
- added a plain `deposit` to `UserDeposit`
- reduced the critical section of the `approve_and_deposit` in the `UserDeposit`, allows for more concurrent `approve` transactions.

User deposit without allowance

---

raiden/utils/profiling/profiler.py

py2.7 has not been supported for a long while, this just remove the
compatibility check, and remove the needs to disable the type checker.

Removed compatibility for py2.7

---

raiden/network/proxies/custom_token.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/proxies/utils.py
raiden/network/rpc/client.py
raiden/network/rpc/transactions.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/rpc/assumptions/test_geth_rpc_assumptions.py
raiden/tests/integration/rpc/assumptions/test_parity_rpc_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
raiden/tests/unit/test_rpc.py

```
- In some places the value `cumulativeGasUsed` from the receipt was
used, which is not the correct value to check for problems with the
gas estimation. The correct vaue is `gasUsed`. The cumulative value,
*includes* the gas usage of the other transactions in the same block,
while the `gasUsed` only contains the gas usage of the current
transaction.
- The `TransactionSlot` is not exposed anymore. Since the slot object is
not available outside the `transact` method anymore, we can guarantee
the slot is used. There is no need for the `_sent_lock` and the slot
state. The slot class was kept because it merges the
`TransactionEstimated` and `EthTransfer` into a single concept, which
makes the code simpler to read.
- Added the type `TransactionMined`, which allows for better type
checking. …
```

Added type for sent transactions

---

MANIFEST.in
setup.py

This is required for supporting the `scenario_player` smoketest.

Bundle the synapse testing config template

---

tools/pylint/gevent_checker.py

Extend the gevent linter to make sure that `raise_error` is provided when `Group.join` is used.

Added linter for pool.join

---

pylintrc
raiden/accounts.py
raiden/api/python.py
raiden/api/rest.py
raiden/blockchain/state.py
raiden/connection_manager.py
raiden/messages/monitoring_service.py
raiden/network/proxies/utils.py
raiden/network/rpc/client.py
raiden/network/transport/matrix/transport.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/services.py
raiden/storage/restore.py
raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/utils.py
raiden/transfer/views.py
raiden/utils/profiling/profiler.py
raiden/utils/upgrades.py
tools/pylint/__init__.py
tools/pylint/assert_checker.py
tools/transfer_eth.py

Our custom pylint assert checker wasn't included in the list of enabled messages.
Because of this there are currently 89 `assert`s without messages in the main Raiden code.
The messages should be added to this PR before it's merged

Enable pylint assert checker

---

raiden/network/transport/matrix/utils.py

Fixes: https://github.com/raiden-network/raiden-services/issues/733
This is the case when the servers disk is full.
The displayname is used and we cannot continue when it is not set.

Raise exception when `user.displayname` cannot be read

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/long_running/test_token_networks.py

The healthcheck problems in the bf5 scenarios are caused by`force_check_address_reachability`, which is only used in the connection manager. When that is called, the address and its presence become known, which prevents the room from being created in `immediate_health_check_for`.
This PR removes all side-effects from `force_check_address_reachability`, thereby resolving this issue.
Closes https://github.com/raiden-network/raiden/issues/5918

Side-effect free connection manager healthcheck

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py

Joining rooms is a bit slow, this parallelizes it, should make the first run a tidy bit faster (roughly 10 seconds).
This also moves the sync code to a separate init function with explicit assumption checks.

parallelize broadcast room join

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt

Matrix had a [security advisory](https://github.com/matrix-org/synapse/blob/master/CHANGES.md#security-advisory) for a vulnerability issue related ro request-smuggling attacks. nice discovery @palango 
Should not be too much of an issue for our use case but they provided an easy fix.

Update twisted to 20.3.0 due to vulnerability fix

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt

We never use or update canonical alias. The alias we use is stored in `room.aliases`. Therefore we can remove the usage of canonical alias until Matrix restructures its alias system (planned)

Remove the usage of canonical alias

---

raiden/tests/integration/long_running/test_token_networks.py

`test_transfer_after_connect_works` had a little race condition in synchronizing the block which led to the test being flaky. The cause was, that while `node_0` and `node_2` opened a channel to each other and were waiting for the block being processed, `node_1` might be "one block behind" and therefor cannot see the potential partner to join. 
In the next step the connection manager tries to connect to potential partners. If the block with the channel opening is not processed yet by `node_1` the network seems to be "empty". Therefor, the node will not connect to any potential partner.
I get the block number of `node_0` and wait until `node_1` has processed this block. This should ensure that the channel opened by `node_0` and `node_2` is already seen by `node_1` and will therefore connect …

fix test_transfer_after_connect_works

---

pylintrc
raiden/storage/sqlite.py
raiden/utils/profiling/timer.py
tools/pylint/del_method_checker.py

(Based on #5564, merge after)
`__del__` methods are notoriously unreliable and have caused multiple issues in the past (#5561, #4346, #3559).
We should avoid using them in the code base in general.
This adds a pylint plugin that adds two new checks:
- C6493: A `C`onvention level check that recommends against using `__del__` methods in general
- E6494 An `E`rror level check that warns against raising exceptions in `__del__` methods

Add pylint checker that disallows __del__ methods

---

tools/debugging/extract_sp_exceptions.sh
tools/debugging/sp_download_scenario_logs.sh

- Added pv to show the current download speed for the scenario logs
- Changed the code to gradually download logs, start from the end of the
last run. Useful for unreliable connections, were the download can be
interrupted before finishing. Note: This won't fix partial downloads.
- To do this, the list of local folder has to be removed from the
remote scenarios. To implement this the script couldn't be provided
inline, so a new file was introduced (the alternative would be to
expand the script locally, at the cost of escaping a lot of special
characters).

Incremental download of logs

---

raiden/transfer/mediated_transfer/mediator.py
setup.cfg

Make mypy a bit stricter, no changes needed otherwise.

Enable mypy's renundant-casts check

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Remove all environment dependent values from the scenarios. For those cases, where we want to set different values for different nodes or scenarios, use placeholders than can be filled in by the templating engine in https://github.com/raiden-network/scenario-player/pull/536.
Merge after https://github.com/raiden-network/scenario-player/pull/536.

Use placeholders in scenarios

---

raiden/tests/unit/utils/test_nursery.py
raiden/utils/nursery.py

Fixes: https://github.com/raiden-network/scenario-player/issues/539
By changing `Janitor._stop` to be an `AsyncResult` it becomes possible to propagate `AsyncResult.exception`.

Let Nursery propagate process exit errors

---

raiden/routing.py

The `f` was missing so the error was not being replaced in the string contents.

Fix error format

---

raiden/network/transport/matrix/transport.py
raiden/utils/notifying_queue.py

The healthcheck uses (via `NotifyingQueue`) an gevent `Event` to wait for items to be available in the Queue.
If a node already has open channels items will be put into thehealthcheck queue during startup leading to the internal event to already be set before the first run of the worker.
This triggers gevent/gevent#1540 leading to AssertionErrors to be printed on stderr.
For now switch the healthcheck worker to a busy loop until the gevent bug is fixed.

Fix AssertionError during node startup

---

raiden/raiden_service.py
raiden/tests/integration/cli/test_cli_development.py
raiden/tests/integration/cli/test_cli_production.py

Geth performance for `eth_getLogs` doesn't degrade well with the total
number of events in the blockchain. The testnets response times are
acceptable because the Blockchain does not have that many events,
however, for the Mainnet the number of events is large enough to trigger
timeouts in the client.
Below are the measurements, all o results include time to decode the
response using web3.py (that is why the response time can be higher than
the read timeout):
Geth on Mainnet *without filtering* for Raiden smart contracts.
number of blocks | `eth_getLogs` timing | number of events
--- | --- | ---
0                | 4.715455055236816    | 165
100              | 7.663008451461792    | 14000
200              | 12.996556758880615   | 27559
300              | 15.118395805358887   | 41357
400 …

Reduce batch size of the event polling because.

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Our mainnet test setup needs different settings than our usual test setup. To avoid having to maintain two sets of scenarios, let's use the templating to make the same scenarios work across all environments.
Merge after https://github.com/raiden-network/scenario-player/pull/541, or nightlies will break.
This is the main part of https://github.com/raiden-network/raiden/issues/6061

Prepare scenarios for mainnet testing

---

raiden/storage/serialization/fields.py
raiden/storage/serialization/serializer.py
raiden/storage/serialization/types.py
raiden/tests/unit/storage/test_serialization.py

Without the PolyField, all `ContractSendEvent` subclasses will just be restored as `ContractSendEvent` instances, losing their subclass information.
Only the first commit is necessary to fix the bug, the rest is just refactoring. If we want to minimize the amount of changes for the next RC, we could cherry pick only the first commit.
Closes https://github.com/raiden-network/raiden/issues/6075

Fix (de)serialization for ContractSendEvents

---

raiden/exceptions.py
raiden/network/pathfinding.py

The PFS provides additional debugging information in most error cases.
There should not get lost when the error response is converted to an
exception.

Preserve the error details sent by the PFS

---

raiden/network/pathfinding.py

The error message `The Service Registry has no registered Pathfinding Service and basic routing is not used.` was not correct if simply none of the registered pfs' were online, the user would see that above message.

Changes wrong error msg

---

raiden/network/proxies/monitoring_service.py
raiden/network/proxies/one_to_n.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/rpc/client.py
raiden/tests/integration/rpc/assumptions/test_geth_rpc_assumptions.py
raiden/tests/integration/rpc/assumptions/test_parity_rpc_assumptions.py
raiden/tests/utils/smartcontracts.py

`eth_getCode` can fail if the target block was pruned
fix #6083

handle pruned blocks while checking address for code

---

raiden/blockchain/events.py
raiden/blockchain/exceptions.py
raiden/blockchain/utils.py
raiden/constants.py
raiden/raiden_service.py
raiden/settings.py
raiden/tests/unit/utils/test_dynamic_block_batch_size.py

Fixes: #5538
The batch size used while syncing with the Blockchain in the `eth.getLogs()` calls is now dynamically adjusted based on the response time.
The currently chosen default values are:
- min batch size: 5
- max batch size: 100_000
- initial batch size: 1_000
Also adds tests and fixed the calculation of the block range and blocks / s values in `RaidenService._log_sync_progress`.

Dynamically adjust block batch size

---

docs/rest_api.rst

In the API documentation, there was an incorrect endpoint example for the `status` API.

Fix `/status` endpoint in docs

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

There was quite a mix-up of different values with different purposes and
some outright wrong and useless entries. Currently, we really only have
three different cases which are solved as follows:
* No UDC required: omit `deposit: true`
* Need deposit for a few PFS payments: use `deposit: true` with defaults
* Need enough for the MS to trigger:
set `balance_per_node: {{ ms_reward_with_margin }}`

Clean up UDC balances in scenarios

---

raiden/network/transport/matrix/transport.py

In one of my last PRs a false docstring location got merged into develop. Here is the fix

move docstring to correct place

---

.pre-commit-config.yaml
tools/pip-compile-wrapper.py

pip-compile supports a `--pre` flag to allow resolving packages to pre-release versions.
This adds the possibility of passing that flag via our `pip-compile-wrapper` utility.
This recently came up during the RC release process and the need to use an rc release of raiden-contracts.

Add support for --pre flag to pip-compile wrapper

---

raiden/api/python.py
raiden/blockchain/state.py
raiden/messages/transfers.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/proxy_manager.py
raiden/network/proxies/token_network.py
raiden/network/proxies/utils.py
raiden/raiden_event_handler.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/utils/mocks.py
raiden/tests/utils/network.py

The function get_channel_participants_from_open_event relied on fetching
the channel open event from the ethereum node. This, however, is an
operation with linear complexity on both geth and parity, which requires
a lot of CPU from the node and leads to timeout issues. Since this API
can not be safely used in production/mainnet the interface is being
removed, instead the code is relying on the event polling code to be
correct, and assuming that if a NettingChannelState instance is only
created for valid events. This removes the performance drawback from
freshly fecthing the events from the blockchain while maintaining a
level of type safety.
fix #6106

Remove get_channel_participants_from_open_event

---

raiden/network/rpc/client.py

Logging should be done after the log_details is updated with the token,
otherwise it is not possible to correlate the pending transaction with
the its other states. [skip tests]

Fix logging order

---

raiden/network/rpc/client.py

The signature allowed for `None` to be used, but that resulted in a
runtime error. Instead of having an error at runtime this enforces the
caller to provide a privatekey statically.
The privatekey is required because transactions are signed locally.

JSONRPCClient requires a privatekey.

---

raiden/network/rpc/client.py

[skip tests]
`to_address` could also be bytes, as seen in the logs https://github.com/raiden-network/scenario-player/issues/548#issuecomment-621866896

Format contract address for logging

---

raiden/network/rpc/client.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py

The nonce management has always been tricky, added a bit of context on how the function changed over time, specially why the txpool is not necessary anymore, since at first sight I thought the code was buggy.

Added documentation for get nonce function

---

raiden/network/rpc/middleware.py
raiden/utils/cli.py

Part of #6132 
Adds a new gas price strategy that returns higher values that are closer to what https://www.ethgasstation.info recommends.

Create a gas price strategy that's closer to ethgasstation

---

raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/resources.py
raiden/tests/integration/api/rest/test_rest.py

This can then be used in the WebUI.
Closes https://github.com/raiden-network/raiden/issues/6113.

Provide API endpoint to shutdown Raiden

---

raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml

This was converted to templates with a small error, this PR brings back
the missing factor of two.
See https://github.com/raiden-network/raiden/commit/657b21925408f026c19dc17a2eb5ddcf60498d2b#diff-418d7f34cecc7db3f39a553e5e3b909fR120
Resolves #6129

Fix IOU assertion in PFS8

---

raiden/tests/scenarios/ms4_udc_too_low.yaml

When adding templating to the scenarios this was changed to have a
proper deposit, which is not what the scenario requires.
https://github.com/raiden-network/raiden/commit/6999c650235c975639b5d4d1582a628da460ee34#diff-e7057410e2e4ef3cfbf88ae30193f1cc
Instead we change it to be 10x the PFS price, so that it works on both
testnet and mainnet.
Resolves https://github.com/raiden-network/raiden/issues/6130

Fix deposit in MS4

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

We need enough to pay for PFS routes in addition to paying the MS.
[skip tests]

Fix BF1 UDC desposit

---

raiden/ui/cli.py

The previous approach redirectered the stacktrace to a file to avoid
showing it to a end users, however it makes it harder for our tooling to
make the stacktrace available for debugging, since the scenarios are
executed inside a docker container and the tmp folder is not mapped.
This changes the code to print the exception to the stderr to make it
available for debugging.

Always print the exception to stderr

---

raiden/network/rpc/client.py

Removes the double period in this message
```
[TokenNetworkRegistry]Address 0x3DE1B1E10Ae71C3E3b793e545A047d1B4FAB587a has wrong code.. Please update your Raiden installation.
```
As seen in #6070

Small no code exception message fix [skip tests]

---

tools/debugging/extract_sp_exceptions.sh

We had more than one person having trouble executing the script because a binary was missing, this should make things a bit smoother.

Add checks for binaries

---

raiden/exceptions.py
raiden/network/rpc/client.py
raiden/tests/unit/test_cli.py
raiden/ui/cli.py
raiden/ui/startup.py

This should make issues like https://github.com/raiden-network/raiden/issues/6070 easier for the user.
Output will look like:
```
Select one of them by index to continue: 0
Enter the password to unlock ...:
The Raiden API RPC server is now running at http://127.0.0.1:5001/.
See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html
Checking if the ethereum node is synchronized
[TokenNetworkRegistry]Address 0x3DE1B1E10Ae71C3E3b793e545A047d1B4FAB587a does not contain code. This may happen if an external ERC20 smart contract selfdestructed, or if the configured address is misconfigured, make sure the used address is not a normal account but a smart contract, and that it is deployed to ropsten. …
```

Better error message for problematic smart contracts

---

raiden/tests/scenarios/pfs7_multiple_payments.yaml

Part of #6158
After increasing the PFS cost, we need to adapt the UDC deposit as well.

 Fix UDC deposit for PFS7 [skip tests]

---

raiden/tests/unit/test_logging.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Version 19.2.0 is the first version supporting python3.8 and we were one
version behind: https://www.structlog.org/en/stable/changelog.html#id10

Upgrade structlog to 20.1.0 for py3.8 compat

---

raiden/network/proxies/user_deposit.py

The deposit function accepts a beneficiary, which is the address that
will have the UDC deposit changed. The preconditions checks correctly
used the beneficiary, whoever the post conditions mistakenly used the
local node address.

bugfix: using wrong address

---

raiden/settings.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/cli/test_cli_development.py
raiden/tests/integration/cli/test_cli_production.py
raiden/tests/utils/transport.py
raiden/ui/app.py

The CLI integration tests implicitly used the matrix servers defined in the RSB known servers list.
This caused the tests to be dependent on external services and therefore be flaky.
This now uses the existing infrastructure to run a local Synapse server thereby removing this dependency.
Fixes: #4642

Use local synapse server in cli tests

---

raiden/constants.py

DAI switched to a new contract, we need to adapt for that.
Part of #6188 
Address according to https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/data_0.37.0/deployment_mainnet.json#L43

Correct DAI contract address [skip tests]

---

raiden/network/pathfinding.py
raiden/tests/integration/network/test_pathfinding.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_pfs_integration_refactored.py
raiden/tests/unit/test_startup.py
raiden/ui/startup.py

The Raiden client and the PFS must be in the same matrix federation,
otherwise the PFS will not see the node as online. To verify this, check
that the PFS uses on of the `available_servers`, which should contain
all servers in the matrix federation.
The typical symptom of the error we avoid is `PFS: Source not online.
Approximate block at the time of the request ... (PFS error code:
2201)`. We had this error twice due to a matrix mismatch, so it's worth
the additional code for the check.

Check PFS matrix server

---

raiden/tests/fuzz/test_state_changes.py
raiden/tests/fuzz/utils.py

This PR completes the long planned redesign of the fuzz test (see the closed issue #4013), using multiple nodes and testing transfers between them rather than a single node and mocked events/messages. We stick to the idea of fuzzing subsets of the state machine, but of course with multiple nodes and actual transfers, the initiator, mediator and target roles cannot be tested in isolation, as originally planned. The new plan is to have five fuzz tests in the end:
- `TestDirectTransfers`, introcuded in this PR, testing only direct transfers over one single channel (thus initiator and target roles)
- `TestOnchainEvents`, testing opening, closing, topping up etc. of channels
- `TestDirectTransfersAndOnchainEvents`, testing direct transfers over a dynamic set of channels
- …

Complete redesign of fuzz test setup and fuzz test of the initiator role

---

raiden/network/pathfinding.py
raiden/tests/integration/network/test_pathfinding.py

Fixes: #6222
The check ran into problems when comparing addresses with and without protocol strings.

Ignore protocol string for matrix server comparison

---

raiden/network/pathfinding.py
raiden/ui/app.py

Fetch matrix server list before PFS check, otherwise the checks will always fail.
To allow usage of custom servers for testing this check is only done if the matrix server isn't given explicitly.

Fetch matrix server list before PFS check

---

.circleci/config.yml

This let's the long running tests run in parallel, shaving a few minutes of CI

Move the SP integration test to the long tests

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

This reverts commit 2bd0f708339653e6130545336eeaa6456cf2b0b2.
Test if that update made stuff more flaky..
One idea is that many test now fail in teardown, with an error that looks like it was changed recently: https://github.com/ClearcodeHQ/mirakuru/commit/b25cb28b02fca2f77b8186568b6c44e03af356c1

Revert "Bump mirakuru from 2.1.2 to 2.3.0 in /requirements"

---

raiden/routing.py
raiden/utils/typing.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

With these changes the tests run fine (but flakyness) on python 3.8. (see https://app.circleci.com/pipelines/github/raiden-network/raiden/9066/workflows/15513948-033e-4a7b-8938-b1953e591d5f)
I'll add CI jobs for 3.8 in a different PR.
Part of https://github.com/raiden-network/raiden/issues/6166

Prepare for python 3.8

---

raiden/network/pathfinding.py
raiden/raiden_service.py
raiden/routing.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/utils/packing.py
raiden/utils/typing.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
setup.py

These types are used in both packages, so they have to be in the
contracts repo, since the dependency is "raiden -> raiden-contracts".
See raiden-network/raiden-contracts#1394.
To make such changes work without releasing a new raiden-contracts package every time, I had to add an ugly workaround to allow git dependencies. See first commit.

Use types from contracts

---

raiden/storage/ulid.py

This changes the `CLOCK_MONOTONIC_RAW` resolution requirement for the `ULID` generator to be only `microsecond` scale.
On some systems (i.e. Linux Subsystem for Windows), the monotonic time
resolution is larger than nanoseconds.
The requirement for the monotonic clock resolution is, that it needs to
be finer than consecutive calls to `time.clock_gettime_ns`, which should
still be satisfied with a `microsecond` (`1e-06`) resolution.
See also 
- https://github.com/raiden-network/raiden/issues/6224#issuecomment-640582410
- https://www.python.org/dev/peps/pep-0564/#annex-clocks-resolution-in-python
This fixes #6224

Relax ULID time_monotonic resolution

---

.circleci/config.yml
setup.py

Add CI jobs for Python 3.8
This makes use of the new matrix syntax in CIrcleCI and uses that to also simplify the current job setup.
The integration tests are currently not run on python 3.8.
Part of https://github.com/raiden-network/raiden/issues/6166

Add Python 3.8 CircleCI jobs

---

raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/tests/integration/api/rest/test_channel.py
raiden/tests/integration/api/rest/test_rest.py
raiden/tests/unit/api/test_encoding.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

Updating to the latest webargs version breaks multiple things. Since we don't use much functionality from webargs, this is a good opportunity to reduce the number of dependencies.

Remove webargs

---

raiden/blockchain/events.py
raiden/ui/app.py
tools/generate_snapshot.py

This tool can be used to fetch all the events which are useful for
Raiden from a ethereum node and then dumped to a file, this then can be
used to front load the state for multiple instances faster.
https://github.com/raiden-network/raiden/issues/4455

Added snapshot tool

---

docs/rest_api.rst
raiden/api/rest_utils.py

As @weilbith found HTTP 408 is not used in the codebase any more. This removes it from the docs.

Remove mentions of HTTP error 408

---

.circleci/config.yml

it looks like `tar cf` no longer compresses the file by default.
~note: before merging we have to download the logs and check if it is gziped, and only once.~ done, all seem good

tar cf no longer compress the file

---

raiden/utils/cli.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

Fixes: #6243 
Remove the unmaintained `pytoml` package and use `toml` instead, which is already used by other dependencies.

Switch from pytoml (unmaintained) to toml

---

raiden/tests/utils/eth_node.py

CI machines have a strongly varying level of performance, so it does not
sound unreasonable to allow up to 20s for starting up geth. Currently
~30% of our flakiness is due to geth not staring up within 10s.
Hopefully, this will mostly eliminate that category of flakiness.
See https://github.com/raiden-network/raiden/issues/6101.

Give eth nodes 20s to start up

---

raiden/tests/conftest.py
raiden/tests/integration/conftest.py
raiden/tests/integration/exception.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements.txt

This can be refined by raising the RetryTestError exception only in more
specific cases.
See https://github.com/raiden-network/raiden/issues/6101.

Rerun tests that are too slow on setup_and_call

---

raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/resources.py
raiden/storage/sqlite.py
raiden/tests/integration/api/rest/test_rest.py

Fixes: #6226 
We applied `limit` and `offset` as parameters before filtering the queried events for `token_network` and partner. That led to the bug described in #6226 . Now we apply `limit` and `offset` for this particular query to the list of events that is already filtered.

Applying limit and offset to filtered events

---

tools/debugging/split_debug_logs.sh
tools/debugging/state_machine_report.py

I noticed that this could take minutes on CI just for the test
`test_assumption_search_user_directory_returns_federated_users`, which
is unreasonable. Timing different approaches on my machine revealed that
the semaphore approach seems to have a high overhead and is only usable
for longer running processes. So I switching to the classical way to
call GNU parallel, which is also a bit simpler IMO.
Timing from my machine:
parallel with semaphore: 120s
xargs: 40s
parallel classic: 20s

Faster log splitting

---

raiden/tests/utils/transport.py

CI machines can be very slow occasionally and there's not harm in
increasing the timeout. This should avoid failures like
https://app.circleci.com/pipelines/github/raiden-network/raiden/9287/workflows/18a2c404-4f45-4a25-b615-d50bacdc7f3d/jobs/128639/test

Give synapse up to 30s to start up

---

raiden/tests/conftest.py

I missed on `fail` in
https://github.com/raiden-network/raiden/pull/6312/files that should
have been turned into a `RetryTestError`, leading to a non-retried
failure in
https://app.circleci.com/pipelines/github/raiden-network/raiden/9309/workflows/8478b7fc-f513-449a-a9c6-7b1e33541239/jobs/129235/tests .

Allow retry on setup and call (2nd try)

---

raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_presence.py

Fixes: raiden-network/raiden-services/issues/799
There seem to be situations, where matrix servers can not serve user profiles. Previously we raised a `TransportException` in these cases. For raiden-services, this could lead to a cascading error, where services started to aggressively re-query the affected user profiles and ultimately triggered the rate limiting, taking down the entire federation.
With the current layout of the matrix client code we need to fix it here.

Matrix display name failsafe

---

raiden/raiden_service.py

Fixes: #6342
Link exceptions in the `ApiServer` to the `App`, so that crashed in the API propagate properly.

Link ApiServer greenlet correctly (#6342)

---

raiden/blockchain_events_handler.py
raiden/connection_manager.py

Fixes #5706
Instead of spawning a new ConnectionManager `retry_connect` greenlet on every new channel blockchain event, we have *one* long running greenlet, that listens for a signal (`gevent.event.Event`), which is set from the blockchain event.

Don't spawn individual greenlets for every channel

---

docs/changelog.rst
raiden/api/rest.py
raiden/tests/integration/api/rest/test_rest.py

Fixes: #6323
The exception `InsufficientEth` was not handled the token minting endpoint

Handles exeption insufficient funds at minting

---

docs/changelog.rst
raiden/api/rest.py
raiden/api/v1/resources.py
raiden/tests/integration/api/rest/test_payments.py

Fixes: #6217 
`flask-restful` assumes that parameters for a given request are available. The only way to make parameters optional is to add the same resource with different URLs.
This led to problems with the `/payments` endpoint, where all parameters are non-optional for the `POST` method, but optional for the `GET` method. The solution is to split the resource for the different parameters.

Don't crash on /payments when no target is given (#6217)

---

docs/changelog.rst
raiden/services.py
raiden/settings.py
raiden/tests/integration/network/transport/test_matrix_transport.py

Fixes #6353
This is a naive approach, basically only when a
user holds >1$ she wants to spend 1$ for monitoring.
If we want to keep our current MS design, we need to
find a smarter solution for that.

Adds min channel balance for monitoring mainnet

---

raiden/tests/scenarios/bf2_long_running.yaml

Should fix the BF2 failures last night

Add wait after node start in BF2 [skip tests]

---

pylintrc
raiden/ui/sync.py
raiden/utils/nursery.py
tools/README.md
tools/debugging/stress_test_transfers.py
tools/pip-compile-wrapper.py
tools/pylint/gevent_checker.py

- Add a lint forbidding usage of `sys.std(in|out|err)`
- Fix race conditions in the stress test script
- Fix stress test to use the status endpoint

Stress test fixes

---

raiden/settings.py
raiden/tests/integration/cli/conftest.py

Since the raiddit contracts are still under development, we use the latest (`=None`) `raiden-contracts` version for now.

Contract version latest

---

raiden/tests/integration/long_running/test_token_networks.py

This is a small little naming fix: in the test, the name `token_network_registry_address` was used incorrectly, where `token_network_address` was correct.

Fix a variable name

---

raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/blockchain/events.py
raiden/tests/integration/api/rest/test_rest.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/network/proxies/test_secret_registry.py

Removes `/api/_debug/blockchain_events/*`. Those used a full range RPC request which would most likely not work (on mainnet) and aren't actively used.

Remove API endpoints for blockchain events

---

raiden/claim.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/raiden_service.py
raiden/tests/conftest.py
raiden/tests/fixtures/raiddit.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/api/rest/test_channel.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/integration/test_regression.py
raiden/tests/utils/network.py
raiden/transfer/state.py

In this PR I fix tests, that fail after #6377:
- the TokenNetworkRegistry.add_token method expects an argument for the `operator_address` (contract-side `_claim_signer`). 
- tests in `raiden/tests/integration/network/proxies/test_token_network.py` are skipped

[Raiddit] Fix integration tests

---

raiden/blockchain/decode.py
raiden/claim.py
raiden/message_handler.py
raiden/messages/abstract.py
raiden/messages/metadata.py
raiden/network/proxies/token_network.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/fuzz/utils.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/unit/test_channelstate.py
raiden/tests/utils/factories.py
raiden/tests/utils/network.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transfer.py
raiden/transfer/channel.py
raiden/transfer/state.py
raiden/transfer/views.py
raiden/utils/datastructures.py

Claims need to be stored somewhere to be available upon settlement.
Claims are stored in `NettingChannelEndState`.
`views.py` provides a function to receive the claims for a given channel with a partner.

Storing Claims in NettingChannelEndState

---

raiden/raiden_service.py
raiden/tests/integration/test_raiddit.py
raiden/ui/cli.py
raiden/utils/claim.py

instead of a hard-coded one in `claims.py`.
Relates to raiden-network/raiddit#51.

Use configured default reveal timeout

---

raiden/routing.py

The raiddit client does not know about all channels, so it can't
correctly check for the availability of routes. Skip the check.
Relates to https://github.com/raiden-network/raiddit/issues/51.

Disable route checking using internal routing

---

raiden/api/v1/encoding.py

`total_burn` was missing in the RESTAPI's response. I added that field to the channel schema.

Addings the total_burn to the channel schema

---

tools/raiddit/generate_claims.py

This works around the old `click.Path` vs `pathlib.Path` oddity.

[Raiddit] Fix cmdline tool for claim generation

---

raiden/raiden_event_handler.py
raiden/raiden_service.py

We want to see feedback for all successful routes, even if the same route is used multiple times.

[Raiddit] Allow multiple feedback tokens for the same route

---

raiden/tests/conftest.py
raiden/tests/fixtures/blockchain.py
raiden/tests/fixtures/variables.py

We previously already had a complicated implementation intending to fix too long temp dir paths on macOS.
This simplifies it greatly by overriding the base temp directory to use the public `/tmp` instead of the default per-user private long one.
(Also fix some flake8 warnings)

Fix pytest temp dir on macOS

---

.circleci/config.yml

Fixes: #6035
Requires: raiden-network/homebrew-raiden#15
Previously the deployment process used `sed` to update the formula file. This has proven to be extremely fragile.
With this change the target formula is instead rendered from a template.

Fix automatic updating of the homebrew formula on release

---

raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/storage/sqlite.py
raiden/storage/utils.py
raiden/tests/unit/test_wal.py

Before the wrapped event was either a str or an event. This wasn't type
checked because a namedtuple was used.

Correct usage of TimestampedEvent

---

raiden/network/rpc/client.py
raiden/tests/utils/eth_node.py
raiden/ui/checks.py

Fixes usage of deprecated geth flags. In the geth logs this looked like:
```
WARN [07-16|15:40:07.821] The flag --rpc is deprecated and will be removed in the future, please use --http 
WARN [07-16|15:40:07.821] The flag --rpcaddr is deprecated and will be removed in the future, please use --http.addr 
WARN [07-16|15:40:07.821] The flag --rpcport is deprecated and will be removed in the future, please use --http.port 
WARN [07-16|15:40:07.821] The flag --rpcapi is deprecated and will be removed in the future, please use --http.api 
```

Remove usage of deprecated geth flags

---

raiden/blockchain/decode.py
raiden/message_handler.py
raiden/raiden_service.py

Some cleanup taken out of https://github.com/raiden-network/raiden/pull/6449 in order to make the PR smaller.
- Pass more detailed parameters to `blockchainevent_to_statechange`
- Remove unused `RaidenService.set_node_network_state`

Cleanup state handling

---

raiden/tests/integration/api/test_pythonapi.py

Since we can't reliably get the reason for an estimateGas error at the
moment, there is a small chance or raising an unrecoverable error in
this test. Rerun the test until the eth clients provide better APIs.
Closes https://github.com/raiden-network/raiden/issues/5744.

Enable flaky test but rerun on failure

---

raiden/ui/cli.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

The `--console` option is only added to the cli when ipython is
installed. This allows removing ipython from the normal requirements,
which greatly cuts down on installed packages.
Lazily importing ipython improves the startup speed even when
ipython is installed.

Only use ipython in dev requirements

---

raiden/tests/conftest.py

The timeout was initialized when instantiating the test and decreased
during setup and call. When the setup was too slow and the test was
retried, the remaining timeout was already negative, causing the test
setup to fail.
The fix is to set the timeout during setup, so it gets reset at the
start of the retry.

Reset setup_and_call timeout on retry

---

raiden/network/rpc/client.py
raiden/tests/conftest.py
raiden/tests/unit/test_cli.py
raiden/ui/app.py
raiden/ui/checks.py
raiden/utils/ethereum_clients.py
tools/generate_snapshot.py

The old check caused two kinds of problems:
* It prevented users from running on recently release eth clients
* It did not catch compatibility problems for changes in minor and patch level versions (which unfortunately do happen)
New behavior:
* Reduce version check error to a warning
* Warn for any version outside of the known range, event if it only changes in the patch level
This is not great, but it looks like an improvement to me.
Closes https://github.com/raiden-network/raiden/issues/6423
The SP integration test failure will be fixed by https://github.com/raiden-network/raiden/pull/6426/commits/40a50392f50f4c63b9e2971add687542aaabcb72 when https://github.com/raiden-network/raiden/pull/6426 is merged.

Change eth client version check

---

raiden/constants.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/settings.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_matrix_presence.py
raiden/tests/unit/test_utils.py
raiden/tests/utils/network.py
raiden/utils/capabilities.py
raiden/utils/typing.py

Fixes: #3283 
- sedes of capabilities are in a new module `utils/capability.py` https://github.com/raiden-network/raiden/pull/6482/files#diff-f02562dc4c1065f371e6994f4ba7c2c2
- this add manipulation of the matrix `avatar_url` with capability strings of the format defined in https://github.com/raiden-network/raiden/issues/3283#issuecomment-601270304
- the predefined capabilities are in `constants.py` https://github.com/raiden-network/raiden/pull/6482/files#diff-fc15643f6fbeaa49665008430fe239bbR85-R94
- the current client default settings are in `settings.py` https://github.com/raiden-network/raiden/pull/6482/files#diff-14a4915b775dfbab039e080a28553d78R130-R137
- on client startup the default settings are published during `login` of `matrix/utils.py` …

Introduce capabilites

---

raiden/raiden_service.py
raiden/storage/sqlite.py
raiden/storage/wal.py
raiden/tests/unit/test_wal.py
raiden/tests/utils/mocks.py
raiden/transfer/architecture.py
tools/debugging/replay_wal.py

The fix #6470 brought some performance problems because the `ChainState` was copied for every state change (see performance measurements below).
This PR wraps the state change processing for blockchain events into an atomic state manager, so that the copy isn't necessary.
At the same time all database writes are put into a database transaction. This leaves the proxies with an up-to-date block number which results in better and more informative error messages.
Fixes https://github.com/raiden-network/raiden/issues/6474
This brings performance back after #6470 and makes it ~36% faster than current `develop`:
```
num_state_changes=2 time_per_sc=0.011809587478637695
num_state_changes=1 time_per_sc=0.003674030303955078
num_state_changes=1 time_per_sc=0.004012107849121094
num_state_changes=437 …
```

Add AtomicStateChangeDispatcher and use it for blockchain events

---

raiden/network/pathfinding.py
raiden/tests/integration/network/test_pathfinding.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_pfs_integration_refactored.py
raiden/utils/http.py

Requests to the pathfinding service will now send the raiden system specification as the `User-Agent` string in the header.
The PR also changes the way that `requests` is used in the pathfinding client module: Instead of using bare `requests.<METHOD>` calls, it uses a `requests.sessions.Session` now. The `session` sets the `User-Agent` and also mounts a default timeout adapter.
This fixes #6455.

Use specific User-Agent in pfs requests

---

raiden/services.py

Fixes:
- The logs for skipping monitoring request dont specify for which token they are doing it. It could be helpful to know the token address.

include token address in skip monitoring log

---

raiden/network/transport/matrix/transport.py
raiden/tests/integration/test_send_queued_messages.py

This fixes the flakyness of `test_payment_statuses_are_restored`. What
happened before was the following:
* The address manager was stopped and reset it's state when stopping
* The client's sync thread was still running for a short time and wrote
to the address manager.
* After the node restart, the address manager's state was unclean, which
led to misbehaving health checks
* The Presence updates were not correctly handled, since the node was
not whitelisted
* Some messages get stuck in the queue because the other node seemed
offline
While this fixes the problem, I think it is unwise to have such state
reset code as we currently have in the address manager. Removing the
objects on stop and creating them again on restart is far safer and
probably even less code.

Unflake test_payment_statuses_are_restored

---

raiden/network/resolver/client.py
raiden/raiden_service.py
raiden/storage/restore.py
raiden/storage/sqlite.py
raiden/storage/utils.py
raiden/storage/wal.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/storage/test_serialization.py
raiden/tests/unit/test_raiden_event_handler.py
raiden/tests/unit/test_serialization.py
raiden/tests/unit/test_upgrade.py
raiden/tests/unit/test_wal.py
raiden/tests/utils/mocks.py
raiden/transfer/architecture.py
raiden/transfer/node.py
raiden/transfer/state_change.py
raiden/transfer/views.py
tools/debugging/replay_wal.py
tools/debugging/stress_test_transfers.py

Resolves https://github.com/raiden-network/raiden/issues/4569
Based on https://github.com/raiden-network/raiden/pull/5525
Currently the state in the state machine is an optional type because the state might be uninitialized. This causes additional checks and branches which complicate the code.
This PR removes this optionality by initializing the state before the state machine is initialized.

Make state machine state non-optional

---

raiden/api/rest.py
raiden/utils/nursery.py
tools/debugging/stress_test_transfers.py

- Added more granular log lines to better understand what is going on.
- Fixed the usage of `kill` and `throw` by the nursery.
- Added waiting routine to check the reachability state of a partner node that is required by the transfer script.
- Simplified some of the function and structure types

Multiple fixes for the stress test

---

raiden/network/transport/matrix/utils.py

as described in #6555 there is only one case for an assert, all other unexpected behavior returns None. This removes the assertion and also returns None if the displayname is not set.
Additionally, I added some warnings for better logging. 
Fixes: #6555

Always return None if validate_user_id fails

---

requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements-docs.txt
requirements/requirements.txt

Synapse uses treq, which uses six. Unfortunately, the recent treq
version requires six>=1.13.0 but does not declare that in the
dependencies. This works ok for the current Raiden setup, since the
versions of all dependencies are frozen and the treq version is old
enough to not require the recent six version.
However, this is not true for the SP, which only versions direct
dependencies. I added the workaround to this repo rather than in the SP
repo, so that we won't get the same breakage again when one of the
dependencies is updated here.
See also https://github.com/twisted/treq/commit/934e127a2b915bf02be86d23f2cf8a65bcdb2533#r42782781

Avoid six version conflict in scenario player

---

raiden/blockchain/decode.py
raiden/constants.py
raiden/routing.py
raiden/storage/serialization/schemas.py
raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/network/test_pathfinding.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/unit/fixtures.py
raiden/tests/unit/test_data/db_statechanges.json
raiden/tests/unit/test_serialization.py
raiden/tests/unit/test_startup.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/unit/transfer/test_node.py
raiden/tests/unit/transfer/test_views.py
raiden/tests/utils/factories.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/token_network.py
raiden/transfer/views.py
raiden/ui/cli.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

Fixes: https://github.com/raiden-network/raiden/issues/6496
Remove internal routing.
Note: This doesn't remove `ContractReceiveRouteNew` yet, as it is used by the connection manager.

Remove internal routing

---

raiden/ui/cli.py

If this option is missing in some cases, the list of options passed
around needs defaults for missing values. Otherwise you can get errors
like
```
File "/home/karl/raiden/raiden/ui/cli.py", line 624, in run
run_services(kwargs)
File "/home/karl/raiden/raiden/ui/runners.py", line 25, in
run_services
if options["console"]:
KeyError: 'console'
ReturnCode.FATAL
```
Instead of adding a default, I chose to add a disabled hidden option, so
that you will get an informative error when trying to use the option.

Add disabled --console option when missing ipython

---

raiden/ui/cli.py

I didn't properly test https://github.com/raiden-network/raiden/pull/6570, so I didn't notice
the always failing callback. Callbacks are called on flags, even when
the flag is false. So the exception raising callback needs to check the
parameter value.

Fix disabled console option

---

raiden/tests/unit/fixtures.py
raiden/transfer/node.py
raiden/transfer/state.py

After deserialization, the TokenNetworkStates in `token_network_list`
and and `tokennetworkaddresses_to_tokennetworks` were equal but not
identical.  When one of them was mutated, the other stayed unchanged,
leading to inconsistent results for the same token network.
To avoid this problem, only the `token_network_list` attribute is
serialized and `tokennetworkaddresses_to_tokennetworks` is derived from
that after deserialization.
It is still possible to modify these two attributes separately, but by
adding and using the `add_token_network` method, this is made less
likely. I did not find a way to completely remove the possibility
inconsistencies without breaking our (de)serialization mechanism.

Fix inconsistent TokenNetworkRegistryState

---

raiden/constants.py
raiden/network/transport/matrix/utils.py
raiden/settings.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_utils.py
raiden/utils/capabilities.py

This changes the capabilities according to the proposed changes in https://github.com/raiden-network/raiden/issues/6503#issuecomment-700001383 and/or https://github.com/raiden-network/raiden/issues/6503#issuecomment-704310156 
Fixes: #6503 
copy and past from the issue:
```python
"mxc://raiden.network/cap?{capabilities_url_encoded}"
```
where `{capabilities_url_encoded}` is the url query parameter encoding of capabilities.
Rules for url encoding:
- `bool` values are encoded as `"0"` for `False` and `"1"` for `True`
- other values are encoded as strings
- lists of values are allowed
The final interpretation of capability values is up to the receiving client, or rather the specified capability.
- intentionally omitting (falsy or whatever) known default values is **discouraged**. Client …

Change Capabilities format

---

raiden/blockchain/state.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/node.py
raiden/transfer/state.py

The "fail early" style is more compact and easier to read, since you
can quickly understand the failure cases without reading all the way to
the end of the function.

Refactor get_token_network_by_address and fix typos

---

raiden/__main__.py
raiden/constants.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/rtc/utils.py
raiden/network/transport/matrix/rtc/web_rtc.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_web_rtc.py
raiden/ui/console.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements.txt
tools/debugging/channels_with_minimum_balance.py
tools/debugging/matrix/generate_messages.py
tools/debugging/matrix/load_with_generate_messages.py
tools/debugging/matrix/presence_report.py
tools/debugging/matrix/presence_update.py
tools/debugging/stress_test_transfers.py
tools/pyinstaller_hooks/runtime_gevent_monkey.py

a couple of issues to be fixed:

Refactorings web rtc

---

docs/overview_and_guide.rst
docs/private_net_tutorial.rst
docs/raiden_services.rst

The option of local routing is not available, anymore. Therefore, it
should not be mentioned in the documentation.
[skip tests]

Remove local routing from the docs

---

raiden/network/transport/matrix/rtc/web_rtc.py

Scenario BF6 crashed due to closing an web rtc channel was not awaited on. This is a quick fix for it.

fix break upon web rtc close

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

Fixes #6590
Since removal of local routing, the amount of PFS requests has changed,
because finding out that a transfer is not possible now needs a
Routing Request to the PFS in all cases.
This commit also contains a number of yaml fixes -- pre-commit
validation wouldn't accept jinja templating fields (`{{ ... }}`)
without quotes.

Fix bf1 request_count mismatch

---

docs/changelog.rst
raiden/api/rest.py
raiden/api/v1/resources.py
raiden/tests/integration/api/rest/test_rest.py

Fixes: #6582
Adds a `/api/v1/settings` endpoint that only returns the URL of the used pathfinding service, because it is needed for the connection manager replacement in the webui. The endpoint should provide more settings in the future (#5011). 
The response from a `GET http://localhost:5001/api/v1/settings` looks like this at the moment: 
```
{
"pathfinding_service_address": "https://pfs.demo001.env.raiden.network"
}
```
I will update the docs accordingly.

Add api/v1/settings endpoint

---

raiden/constants.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/settings.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_web_rtc.py
raiden/utils/capabilities.py

Resolves #6627
This adds support for toDevice messages in Matrix.
- Adds a capability for `toDevice` messages
- Support receiving `toDevice` messages
- Support sending `toDevice` messages
- Don't open matrix rooms when `toDevice` capability is enabled.
- Disable webRTC for now

toDevice message support

---

docs/changelog.rst

The changelog item was not included in
https://github.com/raiden-network/raiden/pull/6608.
[skip tests]

Include synapse update in changelog

---

raiden/network/rpc/client.py

[cherry picked from b9e06e1d07a33b884321bbde4a97fe3c7e0c8e3f on develop]
This is the minimal change to make the tests pass, again. The code is
cleaned up in the following commits.
See https://github.com/ethereum/go-ethereum/releases/tag/v1.9.15 for
more information about the changes in error handling.

Handle new errors raised by geth v1.9.15

---

.circleci/run_tests.sh
raiden/tests/integration/conftest.py
setup.cfg

We always had problems with eth nodes that started without errors but
never reliably processed blocks. This is the reason why we allow test
retries when they fail during startup. The [recent forced upgrade](https://github.com/raiden-network/raiden/commit/d99a477c7102a700cc1d759e193fbe87e4a50bb8) to
openethereum made this problem more pronounced, so that a high
percentage of CI runs failed due to a hanging node startup.
The combination of the following changes in this PR seems to be
effective:
* Allow tests to run up to 20mins (we have a separate timeout for times
without output)
* Allow up to three runs for test that fail during startup
* Reduce the allowed time for startup to 4 minutes, so that we don't
wait unnecessarily long for hanging eth clients.

Work around flaky eth node startup in CI

---

raiden/api/python.py
raiden/api/rest.py
raiden/network/proxies/custom_token.py
raiden/tests/integration/network/proxies/test_custom_token.py
raiden/tests/utils/smartcontracts.py

The documentation of the public REST-API falsely claimed that the
transaction_hash will be returned in the response-body
for the endpoint at `POST /api/v1/_testing/tokens/<addr>/mint`.
Since no methods in the call stack of that endpoint returned
the transaction_hash, this behavior is implemented now -
the conversion from HexBytes to a HexString is done in the
most outer REST layer.
Fixes: #6649

Return tx_hash for `mint_for` APIs in all layers

---

raiden/api/python.py
raiden/network/proxies/custom_token.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_custom_token.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/network/proxies/test_token.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/network/proxies/test_user_deposit.py
raiden/tests/utils/network.py
raiden/tests/utils/smartcontracts.py
raiden/tests/utils/smoketest.py
raiden/ui/console.py

In order to keep the interface consistent, all blockchain proxy
methods that internally call `JSONRPCClient.poll_transaction( )`
somewhere in their call-stack will now also return
the transaction hash, a list of transaction hashes or
an optional transaction hash.
Fixes: #6688

Return tx-hash for blockchain proxy methods

---

README.md
raiden/log_config.py
raiden/ui/cli.py
raiden/utils/debugging.py
tools/pyinstaller_hooks/hook-coincurve.py

This fixes multiple issues when trying to build a self-contained Raiden executable for Windows that does not require WSL. This does not fix all issues, yet. E.g. the ffmpeg dependencies won't be bundled correctly, but https://github.com/raiden-network/raiden/issues/6672 might help with that.
See https://github.com/raiden-network/raiden/issues/2482

Improve Windows support

---

.github/workflows/dependent-issues.yml

Actions on forked PRs usually only have read only access to the target repo.
With `pull_request_target` they are run in the context of the base repo / branch and therefore have read/write access.
See:
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

Use 'pull_request_target' instead of 'pull_request' action

---

Makefile

`pip >= 20.3` is using a new resolver that no longer accepts extras in constraints files.
In the `install-dev` task we used to pass our requirements-dev.txt file verbatim as a constraints file to ensure additional local developer tools (via `requirerments-local.txt`) don't cause breakage.
For now pre-process the requirements file with sed to remove extras.
See: https://github.com/pypa/pip/issues/9209

Fix install-dev make target with new pip versions

---

raiden/constants.py
raiden/network/proxies/secret_registry.py

The previous calculation did not make any sense. That has been obscured
by taking the maximum of the calculation and the gas estimate. But the
gas estimate can be wrong when other nodes try to register the same
secret at the same time.
The new approach of calculating the gas cost could be better, but the
new assert should alert us when the values go out of sync with the
expectations of the contracts.
Closes https://github.com/raiden-network/raiden/issues/6725.

Fix gas costs for registerSecretBatch

---

.circleci/config.yml
raiden/api/python.py

Recent PR #6707 had a bug in the Python API checking for the minimum reveal timeout 
in `channel_open( )` and `set_reveal_timeout( )` methods.
This caused the smoketest to fail, when the default reveal timeout was the minimum reveal timeout.
Weirdly,  the PR itself did pass the CI.

Fix Python API min reveal-timeout check

---

raiden/constants.py
raiden/network/transport/matrix/rtc/aiogevent.py
raiden/network/transport/matrix/rtc/utils.py
raiden/network/transport/matrix/rtc/web_rtc.py
raiden/network/transport/matrix/transport.py
raiden/tests/unit/network/rtc/test_web_rtc_manager.py
raiden/tests/utils/transport.py

This PR solves a couple of bugs and the until now unsolved reason why the python client was slower than the light client.
`channel.send()` only appends the message into a queue
`peer_connection._data_channel_flush()` which is scheduled in `channel.send()` only takes the message from `data_channel_queue` and puts it into `_outbound_queue`. 
`peerconection.sctp.transmit()` transmits the data chunk in `_outbound_queue`.
`Pitfall: If there is still a data chunk in `_outbound_queue`, `peer_connection._data_channel_flush()` won't do anything`
Connections can be closed due to many reasons. The channel can simply be broken/expired. The user can go offline or close the connection on his side. As well as the channel could not get established in the beginning. A callback after closing a peer …

Enforce aiortc to send messages

---

.circleci/config.yml
tools/pyinstaller_hooks/hook-coincurve.py

Before this PR, the CI was using the system Python from the MacOS executors, which is fixed to version 
`3.7.0`. This would cause that not all Raiden requirements were able to beinstalled for the MacOS builds, due to incompatibilities with Python `3.7.0`.
As of this commit, `pyenv` is used for all MacOS builds to install a custom version of Python.
If the CI's `py-version parameter` is set to `3.7`, this will use Python version `3.7.9`.
Additionally, it is now possible to use Python `3.8.6` for MacOS builds.
Future upgrades to other Python versions are now easier, since arbitrary versions can be passed to `pyenv install`.
The ARM builds will be removed for now, until #6178 is solved.
Fixes: #6705

Fix MacOS nightly builds

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

There is a dependency conflict with py-evm used in eth-tester in the raiden-services repo.

update rlp, eth-account, eth-rlp

---

raiden/constants.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/rtc/utils.py
raiden/network/transport/matrix/rtc/web_rtc.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/settings.py
raiden/tests/conftest.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_matrix_presence.py

Signalling messages have been sent only via rooms and thus required the peers to have a room with each other. This makes the `toDevice` and the `webRTC` capability incompatible.
This PR modifies `MatrixTransport._send_raw()` such that it also can send signaling messages which are `msgType == "m.notice`.
It is then reused when sending signalling messages. 
fixes: #6701 
depends on: #6711

Enable to device for signaling

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py

[Workaround](https://github.com/raiden-network/raiden/issues/6724#issuecomment-747755358) for the presence bug by @andrevmatos. In this implementation a random interval after `transport.start()` is used to set presence in a distributed non-deterministic manner.

set presence to online after random interval

---

raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/scenarios/ms1_simple_monitoring.yaml

Fixes: #6756 -- this should help generally with the problem of a node being stopped when there are still Monitoring Requests in flight. It does however not secure us against forced shutdowns.

Safe broadcast stop

---

raiden/network/transport/matrix/transport.py

Having nodes submit the presence up to once a second might degrade the
service quality for other users too easily. Let's set it to 15-60 seconds.

Reduce max presence update frequency

---

pylintrc
tools/pylint/gevent_checker.py

In old versions of gevent passing the same greenlet multiple times to `joinall()` caused a deadlock.
Therefore we implemented a custom pylint checker to only allow sets as the first argument.
This bug is no longer present and therefore the checker has been removed.
Fixes: #6683

Remove pylint rule to enforce sets as first argument to `gevent.joinall()`

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml

This completes what has been started in https://github.com/raiden-network/raiden/commit/3e466b852d31d0e1807e3184ecf5cc7e31d4e867
When shutting down a node it should send outstanding MRs without the need of additional waits. This removes the waits from the remaining MS scenarios.
This has been fixed in https://github.com/raiden-network/raiden/pull/6763 and showed problems in the LC: https://github.com/raiden-network/light-client/pull/2505

SP: cleanup MS scenarios

---

raiden/raiden_service.py
raiden/settings.py
raiden/tests/scenarios/ms1_simple_monitoring.yaml

Running MS1 failed on mainnet, since this check identified the balance as too for being worthy of monitoring. This was caused by two problems (each of them would fail the scenario by itself on mainnet):
* The checked balance was outdated
* The values were below our monitoring threshold
Closes #6736

Fix balance check for sending MR

---

raiden/blockchain/decode.py
raiden/blockchain/state.py

Fixes: #6792 
There's no need to throw an `RaidenUnrecoverableError` here, but we should log the problem.
I'm not so happy about the added `str, bool` return value., If someone has a better idea let me know.

Don't throw unrecoverable error when local state for unlock event is missing

---

raiden/raiden_event_handler.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/unit/test_channelstate.py
raiden/tests/unit/transfer/test_channel.py
raiden/transfer/channel.py
raiden/transfer/events.py

Using outdated channel information caused the wrong node to call unlock. See the commit messages for details.
Closes #6706.
Supersedes and thus closes https://github.com/raiden-network/raiden/pull/6708.

Update old channel state before deciding whether to unlock

---

raiden/network/transport/matrix/utils.py

Fixes: tbd.
Previously `matrix/utils.py` used the library provided `user.get_avatar_url()` call, which needed that capabilities have a `mxc://` protocol prefix. If the prefix was missing, `user.get_avatar_url()` would raise a `ValueError` when trying to generate the `download_url`.
Since this is external input, we need to make sure `avatar_url` can not break a client.
Therefore this PR 
- changes the `user.get_avatar_url` call to the raw matrix API call (`client.api.get_avatar_url(user_id)`) which does not perform `download_url` generation
- adds extra exception handling for `ValueError`

Fix value error

---

tools/pyinstaller_hooks/hook-raiden.py

eth-hash introduced circular deps into raiden between versions 0.2.0 and
0.3.0. This threw our pyinstaller hook-raiden.py into an infinite loop.
Fixes https://github.com/raiden-network/raiden/issues/6798.

Avoid circular dependencies in pyinstaller hook

---

raiden/constants.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/unit/test_matrix_transport.py
tools/debugging/matrix/generate_messages.py
tools/debugging/matrix/presence_report.py

In order to send to specific devices, `device_id` needs to be passed as an argument at `login()`. Since services uses them as well. Additionally, there is a new Enum class for consistent Device_ID setting.  
Fixes: #6812
Currently, also `RAIDEN` as a device ID is used in test. I did not see a reason to have a test device ID.

pass device_id as argument upon login

---

raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/mocked/test_matrix_transport.py

With the introduction of toDevice and WebRTC rooms are no longer needed for node-to-node communication.
Since their management takes up a lot of code and also is the reason for a whole host of race conditions.
This needs to be discussed with the rest of the Python and Light Client teams before being able to be merged.

Remove Matrix rooms for node-to-node communication

---

raiden/blockchain/decode.py
raiden/blockchain/events.py
raiden/blockchain/filters.py
raiden/network/transport/__init__.py
raiden/network/transport/matrix/transport.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/transfer/events.py
raiden/transfer/node.py
raiden/transfer/state_change.py
raiden/ui/app.py

Fixes: #6813 
This adds
- a mapping for `service_address => validity_timestamp` to `MatrixTransport`
- methods for populating and modifying the mapping
- actions on new `Block` to prune services with expired validity
- a blockchain event filter to listen for new `ServiceRegistry.sol::RegisteredService` events
- an almost effect-less ("phony") state change on such blockchain events (does not change state, but yields a raiden event, see below)
- a raiden event to update the service addresses in the transport
This should give us the necessary data structure in `MatrixTransport` to send `toDevice` messages to the services.

Registry services addresses

---

.circleci/config.yml
.pre-commit-config.yaml
raiden/tests/conftest.py
raiden/tests/integration/cli/conftest.py
raiden/tests/unit/test_cli.py
raiden/tests/utils/cli.py
raiden/tests/utils/smoketest.py
raiden/ui/cli.py
raiden/utils/cli.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
setup.cfg

Refactor the config-file option parsing, since before it was not re-usable and very fine-grained, replicating `click` library's internal behaviour.
What this Refactoring does in detail:
- Now CLI options can additionally have a `Parser`-classes concrete implementation-class attached, which can alter all other parsed command line options (for e.g. config-file parsing based on a config-file CLI option, for injecting/overwriting options based on a provided policy-option, etc.)
- Priorities can be provided to the additional parsers to determine option overwrite-precedence
- The parser-wrapped command functions (e.g. `run` / `smoketest`) have now better introspection into what source 
set a specific option, via the `Context.get_parameter_source( option_name )`, which returns a …

Refactor CLI-parsing

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

rlp 2.0.0 used to unconditionally log a recommendation to install rusty-rlp.
This has been fixed in 2.0.1. See ethereum/pyrlp#129.

Upgrade rlp to 2.0.1 to get rid of warning

---

docs/rest_api.rst
raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/exceptions.py
raiden/tests/integration/api/rest/test_rest.py

Fixes: #5497 
This adds a `api/v1/user_deposit` endpoint as specified in the linked issue for interacting with the UDC.
It has three possibilities for POST requests depending on the body parameter:
- deposit: `{total_deposit: <amount>}`
- plan a withdraw: `{planned_withdraw_amount: <amount>}`
- withdraw: `{withdraw_amount: <amount>}`
This is needed for having a user-friendly interface to the UDC in the WebUI.

UDC deposit and withdraw API

---

raiden/network/transport/matrix/transport.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/network/transport/test_web_rtc.py
raiden/tests/mocked/test_matrix_transport.py
raiden/utils/typing.py

This is defining the interface of how the transport will receive
additional address-metadata that can be bound to individual messages.
This information will be used to specify more specific information
about transport specific user-ids and capabilities - that can
be forwarded to the node's transport from other peer's forwarded
metadata or from the PFS.
The transport will be able to send messages without the metadata.
We decided to first  add the interfaces and the transport internal processing of address-metadata,
and then step by step add passing that metadata from the different locations (PFS query, peer messages)
to the transport.
If there is no metadata provided, the transport will construct the user-ids from the transport based
on the known matrix servers, so that the messages will …

Add optional AddressMetadata processing to transport

---

tools/debugging/matrix/generate_messages.py
tools/debugging/stress_test_transfers.py

Fixes: https://github.com/raiden-network/raiden/issues/6878
Upgrading mypy exposed this type incompatibility. This PR fixes the errors and returns the develop branch to a green state.

Fix mypy unexpected type error

---

raiden/raiden_event_handler.py
raiden/tests/unit/storage/test_serialization.py
raiden/tests/unit/test_node_queue.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/transfer/mediated_transfer/test_events.py
raiden/tests/unit/transfer/test_node.py
raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/utils/typing.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

With the new interface described in #6875 every message will ciom with optional AddressMetaData. This can also be None. As this is attached to the recipient of a message, this PR introduces a field `recipient_metadata` in order to pass it through the state machine. 
For now this is set to None but will be changed in the following PRs

Add Recipient Metadata to SendMessageEvent

---

requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

The matrix-synapse 1.27.0 lib has a known issue with some versions of postgresql: https://github.com/matrix-org/synapse/issues/8996
This has been fixed in version 1.28.0, and the latest version, 1.29.0, seems to work well for us.

upgrade matrix-synapse

---

.circleci/config.yml
raiden/network/rpc/client.py
raiden/tasks.py
raiden/tests/conftest.py
raiden/tests/integration/api/rest/test_api_wrapper.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/rpc/assumptions/test_geth_rpc_assumptions.py
raiden/tests/integration/rpc/assumptions/test_parity_rpc_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_call_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_events_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
raiden/tests/unit/test_web3_assumptions.py
raiden/tests/utils/client.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/smartcontracts.py
raiden/ui/checks.py
raiden/ui/console.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements-docs.txt
requirements/requirements.in
requirements/requirements.txt
setup.cfg

We had accrued a big bunch of deprecation warnings (which usually showed up when running the tests) which would cause  reakage in future Python versions.
This upgrades packages as necessary and fixes most warnings.
The remaining ones are being tracked here:
- raiden-network/raiden-api-client#1
- matrix-org/synapse#9641
- matrix-org/synapse#9642
- slezica/python-frozendict#25
This also temporarily removes the docs requirements from the dev set since there's a conflict between `releases` and `py-solc-x` pinned versions of `semantic-version`. See: bitprophet/releases#94
This requires some fixes in raiden-contracts.
Requires raiden-network/raiden-contracts#1443

Fix a whole bunch of deprecation warnings

---

raiden/constants.py
raiden/raiden_service.py
raiden/tasks.py
raiden/tests/unit/test_version_check.py
raiden/tests/utils/mocks.py
raiden/ui/runners.py

https://github.com/raiden-network/raiden/pull/6871 introduced the Notifications service. This PR is using the service, sending some logs to it, on top of still logging the messages as they were.

create notifications from system logs

---

.circleci/config.yml
raiden/network/rpc/client.py
raiden/network/utils.py
raiden/tests/conftest.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
tools/parallel_tests.sh

Fixes: #6872
Fixes geth 1.10 incompatibility and ensures txs created by Raiden are replay protected (EIP-155).
(Also contains some fixes to the `tools/parallel_tests.sh` helper for macOS)

Make transactions replay proof

---

raiden.spec

Fixes: #5874 
The issue in setuptools was resolved so we can remove the hotfix I added.

Remove no longer necessary pyinstaller hidden import

---

raiden/settings.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/ui/startup.py

Allow switching between the two contract deployments on goerli and
default to the old/demo contracts. See
https://github.com/raiden-network/light-client/issues/2521 on why we
want to do this.
Closes https://github.com/raiden-network/raiden/issues/6862

Allow selection of unstable env/contracts

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/raiden_service.py
raiden/settings.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/integration/network/transport/test_web_rtc.py
raiden/tests/mocked/test_matrix_transport.py

The MatrixTransport is now able to handle additional metadata
for messages that will primarily contain specific matrix user-ids
to send message to via to-device.
If a message is passed to the transport without metadata,
to-device messages will be sent to all possible user-ids on all
matrix home-servers known to the transport.
WebRTC is being disabled in this commit (temporarily).
Resolves: #6850

Add optional AddressMetadata support in MatrixTransport

---

raiden/tests/integration/test_regression.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/unit/api/test_api.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/transfer.py

removes fix mes. Most of the time metadata are not needed to serve the test purpose. Address metadata are now created with capabilities in `create_route_state_for_route`

remove fix me metadata

---

raiden/network/pathfinding.py
raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/routing.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/test_pathfinding.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/utils/transfer.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

For a direct transfer, the node is not querying the PFS for a path. Since the main source of information for 
address-metadata is the Path-resource from the PFS, a direct transfer needs another means to retrieve the 
information. In this PR, the address-metadata endpoint of the PFS is accessed in order to 
get the address-metadata of the receiving node of a direct transfer.
Additionally, the sending nodes' address-metadata is injected in order for the receiver to 
interact with the sender easier.
Fixes: #6841

Query address-metadata from PFS endpoint before direct transfer

---

raiden/message_handler.py
raiden/raiden_event_handler.py
raiden/transfer/node.py

Some parts of the code had a long chain of if-elif that could be safely replaced by a mapping of types to methods. This PR does that to increase readability and maintainability of the code.

cleaning too-many-branches lint warning

---

raiden/routing.py
raiden/storage/serialization/serializer.py
raiden/tests/unit/test_pfs_integration.py

Fixes: #6943
Address metadata from a PFS path request response contains hex serialized addresses. Per our sandwich encoding convention, these addresses need to be deserialized before we do any further processing.

Fix serialization error

---

raiden/network/transport/matrix/transport.py
raiden/ui/app.py

This is necessary since we're currently use this list to construct user-ids on other homeservers in the to-device fallback communication method.

Always fetch list of available Matrix servers

---

raiden/tests/benchmark/_codespeed.py
raiden/tests/benchmark/conftest.py
raiden/tests/benchmark/test_mediated_transfer.py
raiden/tests/utils/transfer.py

This sets up a simple benchmark infrastructure, including posting results to a [Codespeed](https://github.com/tobami/codespeed) instance. See #6962.

Benchmarks

---

.pre-commit-config.yaml
Makefile
conftest.py
pyproject.toml
setup.cfg

Until now pytest needed to be invoked with the path to the tests (`raiden/tests`) in order for the top level `conftest.py` file to be read early enough for our custom CLI options to be enabled.
Also certain other hooks (e.g. temp path shortening on macOS) are configured there and only take effect when this file is read early enough.
Having to specify the path has been a long standing irritation for both old and new contributors.
This moves the top level conftest file to the project root so that it's read early enough in all cases.

Fix invoking pytest without path

---

.pre-commit-config.yaml
Makefile
tools/pre-commit/pre-commit-check-versions.py

We often have the problem that the tool versions specified in the pre-commit config drift out of sync with the general project
requirements.
Especially in the case of `mypy`, `isort` and `black` this can lead to annoying "edit wars" between the differing versions.
This adds a utility that checks that the versions match the requirements and adds it to the `lint` make target (thereby  ensuring out of sync versions will be caught by CI).

Add pre-commit config version check helper

---

.circleci/config.yml

Since #6991 a `conftest.py` file exists in the Raiden project root.
This seems to cause the scenario player tests to pick that up as the test root dir (since the SP repo is cloned into the Raiden checkout) and use the Raiden conftest file.
This produces unexpected results (infinite recursion).
The scenario player checkout is now done next to the Raiden repo, not inside it.

Explicitly set test root dir in scenario player tests

---

.pre-commit-config.yaml
tools/pre-commit/pre-commit-check-versions.py

- Update pre-commit/pre-commit-hooks to 3.4
- This splits out flake8 into it's own repo which means it can now be checked by our version check helper as well.
- Switch to using the official pylint repo instead of the deprecated mirror
- Update pre-commit/pygrep-hooks
- Add some rst mistake checkers

Update pre-commit hook versions

---

pyproject.toml

It's actually important since it indicates that the monkey patching
occured too late and things may break, as has recently started happening
on our CI.

Don't ignore gevent.monkey.MonkeyPatchWarning

---

docs/changelog.rst
docs/rest_api.rst

As of https://github.com/raiden-network/team/issues/874, we decided to move fully back from gitbook to readthedocs. This applies the improvements that were done on the gitbook documentation to the API part. 
In details, this restructures the sections by sorting them by the respective resources, applies several textual improvements and adds the missing API endpoints (contracts, shutdown and notifications).

Apply improvements from gitbook to API documentation

---

raiden/api/python.py
raiden/message_handler.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/raiden_service.py
raiden/tests/integration/api/rest/test_api_wrapper.py
raiden/tests/integration/api/rest/test_channel.py
raiden/tests/integration/api/rest/test_payments.py
raiden/tests/integration/api/rest/test_rest.py
raiden/tests/integration/api/test_pythonapi_regression.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_balance_proof_check.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/mocks.py
raiden/tests/utils/network.py
raiden/tests/utils/transfer.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/ui/app.py

For invalid or non-existent AddressMetadata in the `_send_raw`
method of the transport, a fallback was used where the message
was sent out to all possible user-ids on all known Matrix servers
in the federation. This was considered a possible security
vulnerability, since a malicious matrix server wouldn't have
to follow signature verification and could be eavesdropping.
The fallback feature is therefore removed, so that messages without
address-metadata will remain the retry-queue as long as there is no
WebRTC connection established.
Fixes: #6953
There are also 2 bugfixes included:
- fix the flaky `test_matrix_transport_handles_metadata`
Fixes: #6976
- Fix message-batching for differing UserIDs per receiver 
Fixes: #6993

Remove fallback send to-device to all possible UserIDs

---

.circleci/config.yml

This fixes CI runs until https://github.com/raiden-network/raiden/issues/7027 was implemented.

Disable scenario_player smoketest

---

raiden/tests/benchmark/conftest.py

Codespeed is then able to provide additional information like commit
logs, links to github etc.

tests: benchmark: use full git commit ID

---

raiden/transfer/mediated_transfer/initiator.py

This message will also be returned when the secret request was valid,
but the payment timed out nevertheless. Using a less specific but
correct error message is preferable.
Closes https://github.com/raiden-network/raiden/issues/7044

Fix "bad secret request message from target" msg

---

raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_transport.py

Due to the broken serialization, the python client did not set the
`avatar_url` for the capabilities server-side.
Fixes: #7047

Fix capabilities serialization in login()

---

docs/adr/template.rst

template.rst is just a template and shouldn't be included in
the docs, but sphinx will complain:
```    
raiden/docs/adr/template.rst: WARNING: document isn't included in any toctree
```    
So mark it as orphan to silence the warning.

Mark docs/adr/template.rst as orphan

---

raiden/tests/scenarios/ms1_simple_monitoring_snapshot.yaml

This has been useful when debugging multiple times. But digging it out
every time is cumbersome and others might want to use it, too. It is not
symlinked to the sp1/sp2 dirs, so it should not get picket up by the SP
CI.

Add MS1 scenario variant with snapshot

---

raiden/message_handler.py
raiden/messages/decode.py
raiden/messages/metadata.py
raiden/routing.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/transfer/test_source_routing.py
raiden/transfer/routes.py
raiden/transfer/state.py
raiden/utils/validation.py
setup.cfg

Fixes: #7049
Until now `RouteState` had no validation on the `address_to_metadata` field (unlike `RouteMetadata` which is used in the transport).
In cases where invalid metadata were present this would lead to stuck transfers that would need to wait for lock expiration.
Adding the validation now allows either to select a route with valid metadata for all hops or immediate user feedback that the transfer can't be performed.
See #7049 for more details.

Validate address metadata in RouteStates

---

raiden/messages/metadata.py

States should never be mutated when the mutation is not the cause
of a state-change.
The RouteState.address_to_metadata dictionary was passed to the
RouteMetadata message container, and the mutable object was altered
upon verification of the metadata signatures.
This could cause losing of invalid metadata in the senders state,
once the metadata was passed to other nodes.
Fixes #7061

Fix address-metadata state mutation in message verification

---

.circleci/config.yml
Makefile
docker/build.Dockerfile
raiden.spec
tools/pyinstaller_hooks/hook-av.py
tools/pyinstaller_hooks/runtime_gevent_monkey.py

Our bundled binaries seem to have been not working for some time (thanks @netcriptus for noticing).
We had two separate issues:
- The `av` dependency (via `aiortc`) wasn't being properly discovered by PyInstaller.
This has been fixed with a hook.
- On Linux stripping of the libraries apparently causes some corruption
See: https://github.com/pypa/manylinux/issues/119
Therefore stripping is disabled for now.
- The gevent runtime hook would attempt to start the aio event loop. This caused a warning about an already running loop.
This also fixes:
- Don't include unnecessary av libraries in the bundle
- Remove no longer used GETH_URL and SOLC_URL build args from the `bundle-docker` make target.
- On CI: Invoke the built binaries with `--help` as a minimal functionality sanity check.

Fix PyInstaller bundling

---

.circleci/config.yml

`pyenv` changed the behaviour of `pyenv init -` to no longer set the PATH
This fixes it.

Fix macOS CI build issue

---

raiden.spec

Pyinstaller used to remove libav binaries which we dont need but are a requirement for aiortc. As we remove aiortc for a short term we can remove the check. 
It also goes around a bug in pyinstaller own datastructe TOC by removing via list.remove and not the __sub__ operator

remove removing dependencies

---

Makefile
conftest.py
raiden.spec
raiden/network/transport/matrix/transport.py
raiden/tests/utils/transport.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
tools/pip-compile-wrapper.py
tools/pyinstaller_hooks/runtime_aiortc_pyav_stub.py

Add `av` replacement stub
We're using `aiortc` as our base library to provide WebRTC support in Raiden.
Even though we're using only data transfer features it has a non-optional dependency on the `av` library which provides audio / video codec support etc.
This library is problematic case of building binary bundles since it causes a whole lot of (system) libraries to be unnecessarily included in the bundle.
Among others these libraries are FFMpeg (libav, libx264, libx265), Vorbis etc.
There are two problems caused by this:
- The bundle size grows from ~20MB to ~70MB
- Some of those libraries are licensed under the GPL and can therefore not be distributed in an MIT licensed bundle
To solve all these problems this PR adds a stub library …

Add av replacement stub

---

raiden/network/rpc/client.py

Remove web3.py patches that are relevant to pre-5.x versions of web3.py.
Fixes #6009.

Remove web3.py patches that are relevant to pre-5.x versions of web3.py

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms1_simple_monitoring_snapshot.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Uses a Jinja template parameter for the gas price in the scenario files.
Requires https://github.com/raiden-network/scenario-player/commit/6172a91756026c4a018b812c822d2c22856cbf58 to function in a scenario run

Use gas_price from environment file

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms1_simple_monitoring_snapshot.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

This should fix the failing scenario-runs with the Jinja gas_price parameter.
Before, the double-quotes lead to an int being parsed as an explicit string in the scenario-player, which failed verification.

Fix yaml gas_price parsing

---

raiden/storage/serialization/schemas.py

raiden: storage: add missing type ContractSendChannelBatchUnlock

---

raiden/api/rest.py
raiden/tests/integration/api/rest/test_channel.py

Fixes: #7093
The withdraw API wasn't handling the error which was thrown when the address metadata could not get fetched from the PFS. This happens for example if the partner node is offline.

Handle `ServiceRequestFailed` errors in channel withdraw API

---

.circleci/config.yml

There's no "Raiden Context" anymore.
Fixes https://github.com/raiden-network/raiden/issues/7107

.circleci: fix deployment to digitalocean

---

raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/mocked/test_matrix_transport.py

Before, the retry-queues semaphore had to be acquired in order to
enqueue messages.
This caused the thought to be asynchronous enqueue() method and
all methods calling it to be dependent on successfully processing
all messages in the queues greenlet that processes the queue.
Effectively this resulted in a synchronous enqueue() call and could
cause the state-machine to block during long-running requests or retries
to the transport layer.
Fixes: #7120

Fix retry-queue's enqueue() blocked by semaphore

---

raiden/messages/metadata.py
raiden/transfer/state.py
raiden/utils/validation.py

Fixes: #7059 
- Clean up code validating address metadata, unify them in a base validation class.
- Circular import situation has been almost eliminated. One import still remains and will demand more investigation to eliminate.

cleanup validation class; improve circular import situation

---

raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml

Fixes: #7130
I don't think it's realistic to expect that every implementation handles fees exactly the same. Rounding differences and behavior of different big number libraries might differ in details and should not stop the scenarios from passing.
That said, I aimed for the minimal changes here. In my opinion it would be OK to allow a bigger error, but these changes should be enough to let the light client run those scenarios.

scenarios: Allow small balance deviations in mfee scenarios
