raiden-network/raiden

.circleci/config.yml
raiden/network/proxies/token_network.py
raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/cli/test_cli_production.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_udp.py
raiden/tests/integration/rpc/test_assumptions.py
raiden/tests/integration/test_pythonapi.py
raiden/tests/utils/genesis.py

Fix all open parity issues

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/udp/udp_transport.py
raiden/raiden_service.py
raiden/tasks.py
raiden/tests/integration/test_raidenservice.py

Monitoring messages initialization on restart

---

raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/rpc/smartcontract_proxy.py

Web3.py understands keyword arguments for smart contract methods.
I think we should use keyword arguments because some methods have
six or more arguments of the same type, and it's very easy to make
mistakes.
With keyword arguments, it's easier to tell `participant` and `partner` apart.
I've kwarged calls with more than one arguments.

Call smart contracts with kwargs

---

tools/scenario-player/example-scenarios/scenario-example-v2.yaml
tools/scenario-player/scenario_player/tasks/execution.py

[SP] Add wait_blocks task

---

tools/scenario-player/scenario_player/tasks/blockchain.py
tools/scenario-player/scenario_player/utils.py

This got accidentally reverted while rebasing #3686

Re-apply fix from #3703

---

raiden/network/proxies/token_network_registry.py

Remove unneeded comment. Better variable name

---

raiden/tests/integration/test_echo_node.py

I tried to simplify and remove the `gevent.sleep` from the test, however I'm not 100% sure if the result is better

simplified test for event transfer success

---

raiden/ui/app.py

Fix spacing in service registry error message

---

constraints.txt
requirements.txt

This might work for https://github.com/raiden-network/raiden/issues/3723

Upgrade raiden-contracts to fix the crash in production mode

---

raiden/app.py
raiden/network/pathfinding.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/unit/test_cli.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/utils/smartcontracts.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/utils/cli.py

- additional cli arguments for manual pfs configuration
- make sure the necessary config entries (eth address for ious) are always there
- some cleaning up and updates to unit tests
Closes #3676

More amendments to pfs integration

---

raiden/tests/conftest.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/utils/transport.py
tools/parallel_tests.sh

- Add pytest option to specify synapse base port
- Update parallel_tests tool to:
- Use above option
- Make mac compatible
- Use tmux if available to show parallel test output

Make parallel tests tool work

---

raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_startup.py
raiden/tests/utils/mocks.py
raiden/transfer/views.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/ui/startup.py

What this PR does:
- Broke up ui/appy.py in smaller functions and added tests for them. - #3677 
- Fixed the missing user deposit proxy issue. Fix #3731 
- Along with the upgrade to the new contracts this PR should also fix the production mode crash. Fix #3723
Still remaining to do:

Startup tests and fix for missing user deposit and production crash

---

raiden/tests/integration/network/proxies/__init__.py
raiden/utils/serialization.py

This is my try to fix some typing errors on the fees PR

Made serialization funcs generics [skip ci]

---

raiden/network/proxies/token_network.py

Remove unneeded comment

---

raiden/ui/cli.py

Adjust CLI transport arg comment on Matrix transport

---

raiden/storage/migrations/v20_to_v21.py
raiden/tests/unit/storage/migrations/test_v20_to_v21.py

Fix tokennetwork -> payment network mapping migration

---

raiden/exceptions.py
raiden/network/pathfinding.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/unit/test_pfs_integration.py
raiden/ui/startup.py

This is my proposal for how to handle IOU rejections, see my comment in #3461 for discussion.
Before this PR is merged, I will also add some documentation of the pfs integration and a unit test for the andling of iou rejections.
Closes #3461

Try to recover when the PFS has rejected our IOU

---

raiden/storage/migrations/v19_to_v20.py
raiden/tests/unit/storage/migrations/data/v19_statechanges.json
raiden/tests/unit/storage/migrations/test_v19_to_v20.py

Resolve issue in v19 migration

---

.circleci/config.yml
requirements-circleci.txt

I want to add a job in the build to make sure our `constraints.txt` does not contain unnecessary dependencies, this is just the ground work and should not change existing behavior.

Circle config changes

---

.circleci/config.yml
requirements-circleci.txt

Reverts raiden-network/raiden#3781 due to breaking MacOS release build

Revert "Circle config changes"

---

raiden/network/pathfinding.py
raiden/tests/unit/test_pfs_integration.py

The JSON message must hex encode all byte-typed values. This was not the
case for
* from
* to
* signature
Also move the IOU into it's own object as expected by the PFS instead of
adding all keys to the outermost JSON object.

Fix message to PFS

---

constraints.txt
raiden/settings.py
raiden/tests/unit/test_startup.py
raiden/ui/cli.py
raiden/ui/startup.py
requirements.txt

CONTRACTS_VERSION to 0.11.1 so that the deployments on Görli chain
is accessible.

Upgrade raiden-contracts to 0.18.0 and

---

docs/adr/0002-testing-strategy.rst
docs/adr/overview.rst
docs/adr/template.rst
docs/index.rst

It also adds a sidebar point for ADRs

Convert ADR dir to rst format

---

raiden/constants.py
raiden/storage/migrations/v19_to_v20.py
raiden/storage/sqlite.py
raiden/transfer/merkle_tree.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/utils.py
raiden/utils/__init__.py
raiden/utils/serialization.py
raiden/waiting.py

A self-standing PR for mypy work. Part of work for #3798

Some mypy work - 1

---

raiden/constants.py
raiden/messages.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/udp/healthcheck.py
raiden/network/transport/udp/udp_transport.py

Some small mypy fixes for the transport module.

Improve typing in transport module

---

raiden/tests/integration/long_running/test_settlement.py

test_automatic_secret_registration was using gevent.sleep to wait for a
locked transfer to be received by the target app, this added a race
condition which made the test flaky. Fixes #3825

Fixed test race condition

---

raiden/transfer/events.py
raiden/utils/__init__.py

Some more work for https://github.com/raiden-network/raiden/issues/3798
Specifically a fix in `utils/__init__.py`
and fixing all complains in `transfer/events.py`

Mypy work on transfer/events.py

---

Makefile
raiden/transfer/state_change.py
raiden/utils/serialization.py

mypy: Fix errors regarding Locksroot and TransactionHash

---

raiden/tests/integration/fixtures/blockchain.py
raiden/tests/utils/eth_node.py

Issue discovered by @ulope and based on his recommended fix.
Resolves #3661

Use local interface for geth/parity

---

constraints-dev.txt
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/state_change.py
raiden/utils/serialization.py

Work towards https://github.com/raiden-network/raiden/issues/3798.
Files:
- `state_change.py`
- `mediated_transfer/state.py`
- `mediated_transfer/events.py`

Mypy work - 3

---

Makefile
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/routing.py
raiden/settings.py
raiden/tests/unit/test_version_check.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/views.py

Remove mypy errors related to TokenNetwork*

---

raiden/tests/fixtures/variables.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/rpc/RpcWithStorageTest.sol
raiden/tests/integration/rpc/test_assumptions.py
raiden/tests/integration/rpc/test_assumptions_parity.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/smoketest.py
tools/startcluster.py

This adds a test for state pruning with parity, the next step is to add a test for geth an make sure both have the same behavior (raise an exception).
Partial work for #3778

State pruning test

---

raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/tests/unit/test_channelstate.py
raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/target.py

More work towards https://github.com/raiden-network/raiden/issues/3798

All complaints in and around transfer/channel.py are now addressed. - Mypy 4

---

raiden/transfer/node.py

Some wording fixes in is_transaction_effect_satisfied

---

raiden/tests/unit/test_accounts.py
raiden/ui/prompt.py

Fix unlock_account_with_passwordfile for empty password files

---

raiden/raiden_service.py
raiden/routing.py
raiden/settings.py

This fixes the last few mypy errors, that were left in the `raiden_service.py` module.

Fix mypy raiden service

---

raiden/constants.py
raiden/network/blockchain_service.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/utils/typing.py

This fixes all  mypy errors in `raiden_event_handler.py`.

Fix `raiden_event_handler.py` mypy errors

---

raiden/tests/integration/test_regression.py

integration test for #3915

---

raiden/tests/unit/test_startup.py
raiden/ui/app.py
raiden/ui/startup.py

Prompted by @hackaugusto 's comments [here](https://github.com/raiden-network/raiden/pull/3732#pullrequestreview-231218343)

Startup functions simplifications

---

Makefile
raiden/api/python.py
raiden/blockchain/events.py
raiden/blockchain/state.py
raiden/constants.py
raiden/network/pathfinding.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/routing.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/unit/test_startup.py
raiden/tests/unit/test_utils.py
raiden/tests/utils/factories.py
raiden/tests/utils/mocks.py
raiden/transfer/views.py
raiden/ui/startup.py
raiden/utils/__init__.py
raiden/utils/filters.py
raiden/utils/runnable.py
raiden/utils/typing.py
raiden/utils/upgrades.py
raiden/waiting.py

~Merge after https://github.com/raiden-network/raiden/pull/3916~ -> Done
This is the 6th iteration of mypy changes I am doing for https://github.com/raiden-network/raiden/issues/3798
The purpose is to do `mypy --ignore-missing-imports raiden/api ` without problems.

Address all mypy complaints under raiden/api directory - Mypy 6

---

raiden/tests/integration/cli/test_cli_production.py
raiden/tests/unit/test_startup.py
raiden/ui/app.py
raiden/ui/checks.py
raiden/ui/prompt.py
raiden/ui/startup.py
raiden/ui/sync.py

This just groups the checks into a module, it's an initial work towards simplifying the app.py

grouped ui checks in a module

---

docs/adr/0003-git-workflow.md
docs/adr/0003-git-workflow.rst
docs/adr/overview.rst

ADR: Git Workflow

---

raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/network/rpc/client.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/ui/checks.py
raiden/ui/startup.py

Pruned blocks close channel

---

Makefile
tools/genesis_builder.py

This is basically a left-over from #4004

Fix makefile paths after removal of scenario_player

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

Bump version v0.100.3-rc5

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_low_capacity.yaml
raiden/tests/scenarios/pfs7_simple_path_rewards.yaml

This PR adds some simple scenarios that should be run by the scenario player on a nightly basis.

Add simple scenarios for the services

---

raiden/network/pathfinding.py
raiden/routing.py
raiden/tests/unit/test_pfs_integration.py

Fix some types and fix all problems coming from that.

Fix types in pathfinding and routing

---

raiden/tests/fuzz/test_state_changes.py
raiden/tests/utils/factories.py

Uncomplete fuzz test of the mediator role, related issue: #1156. As it will probably take a while until we can resume work on the fuzz test and complete it, let's merge the part that has been done now.

Fuzz test for mediator role

---

raiden/transfer/architecture.py
raiden/transfer/events.py
raiden/transfer/identifiers.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/state.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/node.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/token_network.py
raiden/transfer/views.py

Add more type annotation in raiden.transfer

---

raiden/routing.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_tokennetwork.py

Uses direct routing when direct channel exists, no pfs request

---

raiden/tests/unit/test_startup.py
raiden/ui/app.py
raiden/ui/checks.py

Simplify run app

---

raiden/tests/utils/smoketest.py
raiden/ui/app.py

Add types to `run_app` and remove some unused code.

Add types to run_app

---

raiden/raiden_service.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/state_change.py

This removes some temporary objects that just get returned and also adds
type annotations to some functions

Cleanups to service and initiator manager

---

tools/test_and_report.sh

[skip-ci]
somehow, two typos were left in the test_and_report.sh script...

Fix two typos in script

---

Makefile

Helps knowing what's wrong in linting if black failed it

Add diff to black output

---

raiden/exceptions.py
raiden/network/rpc/client.py
raiden/network/rpc/transactions.py
raiden/tests/unit/test_cli.py
raiden/utils/__init__.py
raiden/utils/notifying_queue.py
raiden/utils/runnable.py
raiden/utils/serialization.py
raiden/utils/signing.py
raiden/utils/solc.py

More annotation

---

raiden/network/pathfinding.py

This appeared after merging #4043

Remove double import

---

raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/constants.py
raiden/exceptions.py
raiden/raiden_service.py
raiden/tests/integration/api/test_restapi.py
raiden/utils/__init__.py

~Merge after: #3817~
~Merge after: Feature: Allow inject secret-hash without a secret #3713~

Implemented sandwich encoding for secret/secrethash

---

raiden/tests/unit/test_utils.py
raiden/utils/signer.py

Add missing exception type in ec-recover wrapper

---

raiden/ui/prompt.py

It's annoying when one copies the address and it's not checksummed.

Show checksummed address in password promt

---

raiden/network/pathfinding.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/utils/mocks.py

Changes pfs payment from max fee to requested fee

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py

Improve transport logging and remove unused path in leave_unused_rooms

---

raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_presence.py

Fixes: #4108
Refs: raiden-network/raiden-services#365

Allow populating user to address mapping from server directory

---

raiden/accounts.py
raiden/network/utils.py
raiden/tests/unit/test_accounts.py
raiden/tests/unit/test_utils.py

Some platform-specific code was marked with `pragma: no cover` as we don't do windows or mac builds in the CI. Coverage increase:
`raiden.accounts` from 47% to 92%
`raiden.network.utils` from 33% to 95%
Closes #3876 
Closes #3933

Add unit tests and remove some unused functions

---

raiden/network/blockchain_service.py
raiden/network/discovery.py
raiden/network/proxies/discovery.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/user_deposit.py
raiden/network/rpc/client.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py
raiden/utils/__init__.py
raiden/utils/typing.py

This just adds missing typing to the proxies and make some of the existing more strict.

typing information for the proxies

---

raiden/network/pathfinding.py

Maybe run you branch with this and see how the IOU looks.

Log debug information when requesting PFS

---

raiden/messages.py

Follow up to @hackaugusto's feedback on #3969

Remove Optional from cmdid type definition

---

raiden/storage/serialization/fields.py
raiden/storage/serialization/types.py
raiden/tests/integration/network/transport/test_matrix_transport.py

Addressing Paul's feedback on #3969

Convert integer data types to strings

---

.circleci/config.yml
raiden/tests/README.rst
raiden/tests/conftest.py
raiden/ui/cli.py

Follow-up fixes to removing UDP

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

~~Please review but do not merge.~~

Bump version 0.100.3

---

.circleci/config.yml
.circleci/enforce_decreasing_lint_errors.sh

lint: enforce decreasing number of errors

---

raiden/tests/unit/test_messages.py
raiden/tests/utils/factories.py

Adds a unit test for the `raiden.message_handler` module and some extensions to the unit test factories written for it. This PR stays below the coverage goal since one method, `MessageHandler.handle_message_refundtransfer` can in its present form not be tested without excessive mocking. It will be better to refactor it into two or three units and test them separately later.
Unit test coverage increase:
`raiden.message_handler` module: 27% to 81%
Total: 51% to 52%

Unit test for MessageHandler class

---

raiden/network/pathfinding.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/unit/test_startup.py
raiden/tests/utils/mocks.py
raiden/ui/startup.py

Adds a check for synced contracts of pfs and client

---

constraints.txt
requirements.txt

Removes `pystun-patched-for-raiden` and `miniupnpc`.

Remove some unnecessary dependencies

---

raiden/constants.py
raiden/network/resolver/client.py
raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/storage/sqlite.py
raiden/storage/wal.py

This actually found a bug in ` raiden/network/resolver/client.py`.

Improve typing of RaidenService

---

raiden/utils/cli.py

Previously precedence between options given on the command line and set
in the config file was established by comparing the current value to
the option's default.
This breaks when the config file specifies a value that is different
from the default and the user then wanted to restore the value to the
default via the command line. In this case the cli option would be
silently ignored since it was impossible to distinguish the explicitly
given value from the baked-in default.

Fix precedence for CLI options / config file settings

---

raiden/tests/integration/rpc/assumptions/test_parity_rpc_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_call_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_filters_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/utils/smartcontracts.py

Makes the assumption tests a bit more consistent.

Use deploy_rpc_test_contract consistently in assumption tests

---

raiden/constants.py
raiden/network/transport/matrix/transport.py
raiden/storage/serialization/fields.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/storage/test_serialization.py
raiden/tests/unit/test_node_queue.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/transfer/mediated_transfer/test_events.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/tests/unit/transfer/test_channel.py
raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/identifiers.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py

Unique queue identifiers

---

raiden/storage/restore.py
raiden/storage/sqlite.py
raiden/tests/unit/test_upgrade.py

Fix balance proof query to find the latest properly

---

raiden/network/pathfinding.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/ui/startup.py

We need to make sure to always display properly hex encoded addresses.

Imporve PFS registry mismatch message

---

raiden/routing.py

Just some logging improvements

Add a general log to get_best_routes

---

raiden/tests/integration/cli/conftest.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py
raiden/ui/cli.py

Properly initialize OneToN address if not given by user

---

raiden/api/rest.py
raiden/connection_manager.py
raiden/encoding/format.py
raiden/network/pathfinding.py
raiden/network/rpc/client.py
raiden/network/transport/matrix/client.py
raiden/storage/versions.py
raiden/tasks.py
raiden/tests/unit/storage/test_versions.py
raiden/transfer/views.py
raiden/utils/cli.py
raiden/utils/echo_node.py
setup.cfg
tools/gas_cost_measures.py

This fixes the last errors thrown from mypy when running with the `check_untyped_defs` setting.
Fixes https://github.com/raiden-network/raiden/issues/4032

Enable mypy check_untyped_defs option

---

.circleci/config.yml

Build nightlies from develop instead of master

---

raiden/raiden_service.py

Use confirmation_blocks poperty in RaidenService

---

raiden/accounts.py
raiden/api/python.py
raiden/api/rest.py
raiden/encoding/format.py
raiden/exceptions.py
raiden/message_handler.py
raiden/network/rpc/client.py
raiden/network/transport/matrix/transport.py
raiden/tasks.py
raiden/tests/benchmark/utils.py
raiden/tests/conftest.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/api/utils.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/unit/test_accounts.py
raiden/tests/utils/eth_node.py
raiden/transfer/channel.py
raiden/ui/console.py
raiden/ui/prompt.py
raiden/ui/sync.py
raiden/utils/signing.py

This mostly updates format calls to f-strings

Run `pyupgrade` on codebase

---

docs/adr/0002-testing-strategy.rst
docs/adr/overview.rst

Was going through our docs and that page looked pretty bare so I added a short explanation.

Add an explanation of what ARD is in the ARD overview in the docs

---

raiden/encoding/messages.py
raiden/messages.py

For that the FeeUpdate message is used.
Part of #3542

Remove fee field in UpdatePFS message

---

raiden/tests/utils/network.py

Added node addresses and details of the opened channels. Otherwise we have to go through the logs and figure out which address is what.

Debugging info

---

raiden/app.py
raiden/blockchain_events_handler.py
raiden/constants.py
raiden/raiden_service.py
raiden/services.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/network/proxies/test_service_registry.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/unit/test_startup.py
raiden/tests/utils/mocks.py
raiden/tests/utils/network.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/utils/__init__.py

Not the user can define to not use the PFS but send balance updates
anyways.
Fixes #3735

Update flags for PFS

---

raiden/network/transport/matrix/transport.py

As talked about in RC (a while ago).

Lower log level of 'Existing room' matrix messages

---

raiden/constants.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_node_queue.py
raiden/tests/unit/transfer/test_node.py
raiden/transfer/channel.py
raiden/transfer/identifiers.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/mediated_transfer/target.py
raiden/transfer/node.py

Fix canonical identifier import

---

raiden/tests/unit/transfer/test_mediation_fee.py

It was meant to be like this from the start, but I must have messed that
up, somehow.

Move and rename mediation fee test file

---

raiden/utils/cli.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt

Testing out the new deps stuff, works nicely 💥

Update mypy to 0.710

---

raiden/raiden_service.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/state_change.py
raiden/ui/app.py
raiden/ui/cli.py

Use a simple quadratic rebalancing function, when the user enables it via the CLI.
The constants are arbitrary, and I'm open for suggestions.
Part of #3542

Calculate a quadratic rebalancing fee function

---

raiden/storage/sqlite.py
raiden/storage/utils.py
raiden/storage/wal.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/test_upgrade.py
raiden/tests/unit/test_wal.py

~Review/Merge after #4156~
This just delegates the time stamping with wall time to the database.

Removed explicit timestamps

---

raiden/storage/sqlite.py
raiden/storage/wal.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/test_upgrade.py
raiden/tests/unit/test_wal.py

~Review/Merge after #4240~
This allows state changes to be written in bulk

State change write in bulk

---

raiden/api/python.py
raiden/api/rest.py
raiden/connection_manager.py
raiden/exceptions.py
raiden/network/blockchain_service.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/raiden_service.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/test_balance_proof_check.py
raiden/tests/utils/smoketest.py

Resolve #4200 
Resolve #4178
Resolve #3516

handle pruned state in setTotalDeposit

---

raiden/exceptions.py
raiden/network/proxies/service_registry.py
raiden/tests/integration/network/proxies/test_service_registry.py

Resolves #4196 
Merge after: #4212

Handle pruned state in ServiceRegistry.set_url

---

raiden/api/python.py
raiden/blockchain_events_handler.py
raiden/message_handler.py
raiden/network/resolver/client.py
raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/storage/sqlite.py
raiden/storage/wal.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/test_messages.py
raiden/tests/unit/test_sqlite.py
raiden/tests/unit/test_wal.py
raiden/tests/utils/mocks.py
raiden/transfer/architecture.py
raiden/utils/cli.py

Review/Merge after: #4241
This is a preparation step to write state changes in batch

Write events from multiple state changes in bulk

---

tools/debugging/json-log-to-html.py

Some improvements that collected over time.

Improve json-log-to-html debug tool

---

raiden/messages.py

See
https://github.com/raiden-network/raiden/issues/490#issuecomment-506359327
[skip tests]

Remove outdated comment

---

raiden/network/pathfinding.py
raiden/tests/unit/test_pfs_integration.py

They might have increased since starting the Raiden client.
Closes #4100.

 Update PFS Fees when they are insufficient

---

raiden/network/pathfinding.py
raiden/tests/unit/test_pfs_integration.py

Adds check for pfs fee = 0 not to send iou

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml

Since the switch to PFS routing by default we need to set this.

Add explicit PFS to MS scenarios

---

docs/glossary.rst
raiden/api/rest.py
raiden/connection_manager.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/unit/transfer/test_channel.py
raiden/tests/unit/transfer/test_views.py
raiden/tests/utils/factories.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/state.py
raiden/transfer/views.py

- Fix definition of capacity
- Add `get_capacity` function to `channel` module
- change `calculate_imbalance_fees` to take the channel capacity as an input
The changes to the `UpdateFee` state change will be done in a different PR

Fix capacity calculation

---

raiden/raiden_service.py
raiden/storage/wal.py

I'm adding these log messages to help me debug the flakiness with `test_send_queued_messages`

Added initialization log messages

---

raiden/tests/utils/detect_failure.py

Otherwise the stacktraces will not be available independently in the CI.

Use logging instead of print

---

raiden/tests/scenarios/pfs7_simple_path_rewards.yaml

Changes pfs address to see iou to be sent

Change pfs7 scenario to non free pfs to assert iou sending

---

raiden/network/proxies/token_network.py
raiden/network/proxies/user_deposit.py
raiden/network/proxies/utils.py
raiden/tests/integration/fixtures/smartcontracts.py

State pruning in UserDeposit proxy

---

raiden/exceptions.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/network/proxies/utils.py
raiden/raiden_event_handler.py
raiden/tests/integration/network/proxies/test_token_network.py

Resolves #4201 
~~Merge after #4200~~

Handle pruned state in token_network.settle

---

raiden/api/v1/encoding.py
raiden/storage/serialization/cache.py
raiden/storage/serialization/fields.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

In the services we have problems with (de)serialization of timestamps, lets first see if the updates marshmallow packages help.

Update marshmallow versions

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

Bump version & update changelog

---

raiden/network/pathfinding.py
raiden/tests/scenarios/pfs7_simple_path_rewards.yaml

The hosted PFS nodes take a fee of 100 now, so update this.

Update PFS7 scenario and fix a user-visible output

---

.circleci/config.yml
raiden/tests/utils/ci.py

This was broken by https://github.com/raiden-network/raiden/pull/4320 , the PR also addresses the comment https://github.com/raiden-network/raiden/pull/4320#discussion_r301509617

fix persist artifact path

---

docs/rest_api.rst
raiden/api/python.py
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/api/v1/resources.py
raiden/exceptions.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/utils/smartcontracts.py
raiden/tests/utils/smoketest.py
raiden/utils/testnet.py

Add endpoint for token minting to the API

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/factories.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/mediator.py

Split and added some documentation to the function `is_channel_usable`

Is channel usable docstring

---

raiden/transfer/channel.py

follow up for https://github.com/raiden-network/raiden/pull/4289#discussion_r301235040

collapsed functions to check signature

---

raiden/network/proxies/token_network.py

Decreased indentation so that deposit happens on the latest block

Fix call to set total deposit in case block is pruned

---

raiden/ui/runners.py

It looks like somehow the run function for the Echo Node got lost.

Added missing run function [skip tests]

---

Makefile
raiden/transfer/node.py
tools/debugging/replay_wal.py

Fixes the script and add type checking

fixed replay_wal.py

---

raiden/tests/conftest.py

Adds a pytest hook to output 'FLAKY' every time a test marked as flaky fails.
Only works in verbose mode and when not using xdist.
This should prevent Circle CI from killing builds due to 'no output for 10 minutes' when long-running flaky tests are retried.

Give more feedback for flaky tests

---

raiden/tests/integration/long_running/test_stress.py

Log triming was necessary for Travis, because the stress test produced
logs larger than the file limit. With CircleCI the file limit is much
larger, so this hack can be removed.

Disable hack to trim logs

---

raiden/network/rpc/smartcontract_proxy.py
raiden/tests/integration/rpc/assumptions/test_rpc_call_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
raiden/tests/smart_contracts/RpcTest.sol

Extended the assumption tests to include both require and assert

Extended assumption test to asserts

---

raiden/tests/scenarios/pfs7_simple_path_rewards.yaml

closes https://github.com/raiden-network/scenario-player/issues/109

Changes pfs7 scenario to source routing

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

This will enable use to use `warn_unreachable = True`

Update mypy to 0.720

---

raiden/tests/integration/cli/test_cli_development.py

Pending investigation at #4419

Skipping test_cli_manual_account_selection

---

raiden/tests/utils/tests.py

The previous code was ignoring the fact that the folder is automatically
created by pytest. This meant that logs from the same run got split up.

Tiny improvement to the local logging folder

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py

Adds user_id and presence logging to transport.address_mgr.

---

raiden/utils/packing.py

This will cause mypy errors when proofs change, which are much easier to
fix than when we get signature mismatches.
This is part of
https://github.com/raiden-network/raiden-contracts/issues/1041

Use the packing functions from raiden-contracts

---

raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_low_capacity.yaml

Should help with the PFS6 problem in https://github.com/raiden-network/scenario-player/issues/149

Add waits into PFS5/6 scenarios

---

raiden/api/python.py
raiden/tests/integration/test_echo_node.py
raiden/utils/echo_node.py

This started out as a PR for adding more logging in order to get more info about the failure in https://github.com/raiden-network/raiden/issues/3750
At some point a matrix issue was found and fixed in https://github.com/raiden-network/raiden/pull/4495
Since then I cannot reproduce the issue. So I think it's best to close this and re-open the issue if it happens again.
Closes #3750

Cleanup echo node test

---

tools/debugging/json-log-to-html.py

Some improvements in the json-log-to-html tool that have collected over the last weeks or so.

Some json-log-to-html improvements

---

docs/changelog.rst
raiden/tests/unit/test_raiden_event_handler.py
raiden/tests/utils/mocks.py

Closed #4507 
~~⚠️ Merge after #4511~~

PFSFeedback event handler tests

---

raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/rpc/client.py
raiden/network/rpc/transactions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/utils/smartcontracts.py
raiden/utils/testnet.py

Should fix #4497 https://github.com/raiden-network/raiden/issues/3761

Use getTransactionReceipt in jsonrpcclient.poll()

---

raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/network/transport/test_matrix_transport.py

https://docs.pytest.org/en/4.6-maintenance/deprecations.html#message-parameter-of-pytest-raises
https://docs.pytest.org/en/4.6-maintenance/deprecations.html#pytest-config-global

Handle some pytest warnings for deprecated features in pytest 5

---

raiden/tests/unit/test_messages.py

Closes https://github.com/raiden-network/raiden/issues/4367.

Regression test: don't serialize internal function

---

raiden/network/rpc/client.py

fix for #4529

---

raiden/network/pathfinding.py
raiden/raiden_event_handler.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_raiden_event_handler.py

Fix typo in parameter of post_pfs_feedback

---

raiden/tests/integration/rpc/assumptions/test_geth_rpc_assumptions.py

See https://github.com/raiden-network/raiden/issues/4545.
[skip tests]

Skip flaky geth test

---

raiden/storage/wal.py

This allows mypy to infer `ChainState`.

Made SavedState generic

---

raiden/network/transport/matrix/transport.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/token_network.py
raiden/transfer/views.py
setup.cfg

Enable the check, otherwise we will regress.

Enable mypy disallow_untyped_defs on raiden.transfer module

---

raiden/blockchain/events.py
setup.cfg

Just enforcing a bit more typing.

Enable mypy for raiden.blockchain

---

raiden/tests/integration/test_echo_node.py

Restoring echo node tests

---

raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/unit/test_raiden_event_handler.py
raiden/tests/utils/network.py
raiden/transfer/architecture.py
raiden/transfer/mediated_transfer/tasks.py
setup.cfg

Also includes on not-test-related change in `TransferTask`, where I stumbled across a TODO while doing the test typing changes.

Improve mypy typing in tests

---

docs/changelog.rst
raiden/raiden_service.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/utils/network.py

Solving 4498 - Poll newly added blockchain filters after first alarm task run

---

raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
raiden/tests/unit/transfer/test_node.py
raiden/transfer/architecture.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/events.py
raiden/transfer/mediated_transfer/state_change.py
raiden/transfer/state_change.py

This just makes objects that don't need to be mutate into immutable classes.

StateChanges and Events made frozen

---

raiden/blockchain/events.py
raiden/blockchain/filters.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/utils.py
raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/tests/unit/blockchain/test_events.py
raiden/tests/unit/utils/test_filters.py

Think it makes more sense there.

Move raiden.utils.filter to raiden.blockchain.filter

---

raiden/network/proxies/payment_channel.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/rpc/client.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py
raiden/tests/utils/smartcontracts.py
raiden/utils/testnet.py
setup.cfg

Ref: https://github.com/raiden-network/raiden/issues/4033

Stricter mypy checks for raiden.network.proxies

---

raiden/tests/integration/test_regression.py

The test works fine, just the timeout for the second transfer is to
slow.
Fixes #4532

Fixes flaky #4532

---

docs/changelog.rst
raiden/api/python.py
raiden/storage/sqlite.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/unit/api/test_api_events.py

Fixes: #4561
Check https://github.com/raiden-network/raiden/issues/4561#issuecomment-520400128

Limit and offset should now work properly in the payment API event queries. 

---

Makefile
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

flaky broke `Ctrl-C` on pytest. Removing it.

Remove flaky

---

.github/pull_request_template.md

Also remove checkmarks from the top level bullet points.

Add changelog bullet point to pull request template

---

raiden/tests/scenarios/README.md

Fixes: #4570 
See issue #4570
The quality checklist that cannot be automatically verified.

Create scenario readme

---

docs/index.rst
docs/testing.rst

This adds some documentation regarding the testing system. It is just a first introduction, I may expand it later.

Added some documentation on testing

---

raiden/routing.py

Adds a log when route request fails

Adds better logging if route request fails

---

raiden/network/proxies/service_registry.py
raiden/tests/fixtures/constants.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/unit/test_channelstate.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/events.py
raiden/tests/utils/protocol.py
raiden/tests/utils/smartcontracts.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transfer.py
raiden/tests/utils/transport.py
raiden/utils/http.py
setup.cfg

Fixed the existing types in `raiden.tests`, this does not add typing to the missing bits and it does not touch `factories.py`.
This did catch a bug or two.

Fixed typing for the tests

---

.circleci/config.yml
raiden/constants.py

there is a new geth https://github.com/ethereum/go-ethereum/releases

Change geth version allowed to v1.9.2

---

docs/rest_api.rst

Fixes: Invalid JSON responses in API documentation
- Documentation update
- n/a

Fix JSON responses in documentation

---

raiden/tests/unit/test_cli.py
raiden/utils/ethereum_clients.py

Fixes: #4608 
Check description of issue.
- Safety
- Commits

Ignore patch version bumps in eth client supported checks

---

raiden/utils/http.py

spelling fix [skip tests]

---

raiden/blockchain/state.py
raiden/tests/integration/long_running/test_settlement.py

Cherry pick of the test changes from https://github.com/raiden-network/raiden/pull/4522

Simplify test batch unlock

---

raiden/tests/unit/transfer/test_state_diff.py
raiden/transfer/channel.py
raiden/transfer/state.py

This adds a few sanity checks to the channel and some of its related data structures.

Channel sanity check

---

raiden/network/pathfinding.py
raiden/tests/conftest.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_pfs_integration_refactored.py
raiden/tests/unit/test_startup.py
raiden/tests/utils/mocks.py

Test PFS integration refactoring

---

raiden/network/rpc/middleware.py

Follow up for #4645, removes some unused code.
- Safety
- Commits

Remove unused http_retry_with_backoff_middleware

---

CONTRIBUTING.md
raiden/tests/utils/factories.py

- Add documentation of `raiden.tests.utils.factories`
- Rewrite paragraph on fuzz tests.
Closes #4613

Some added documentation for the test suite

---

docs/overview_and_guide.rst

Changes infura token of example raiden start in docs

---

raiden/tests/unit/transfer/test_source_routing.py

Fixes: #4253 
When introducing source routing, one issue was found regarding checking if the channel had enough funds to cover both the transfer as well as the mediator fees. This PR adds unit tests to ensure we have no regression.

Add test for verifying if route selection takes both transfer amount as well as fees into account

---

README.md

Added the Raiden Wizard and Awesome Raiden to the Readme

Added the Raiden Wizard and Awesome Raiden [skip tests]

---

raiden/ui/app.py

Closes #4652
Adds info message for user, if default fees are used and provides info how to change that. 
- Safety
- Commits

add info message to user, when default fees are used

---

docs/changelog.rst

Add changelog entry for withdraw invalidation fix in PR 4685

---

raiden/tests/integration/test_raidenservice.py

Fixes: #4686
Merge after #4682
This adds an integration test for `RaidenService._initialize_channel_fees`
- Safety
- Commits

Add test for RaidenService._initialize_channel_fees 

---

raiden/app.py
raiden/blockchain/decode.py
raiden/raiden_service.py
raiden/settings.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/utils/network.py
raiden/ui/app.py

Refactor the configuration of mediation fees. This adds `MediationFeeConfig` to bundle all mediation fee settings.
- Safety
- Commits

Refactor mediation fee config

---

raiden/tests/scenarios/README.md

Add readme entry for the BF1 scenario to the scenarios README
Fixes https://github.com/raiden-network/raiden/issues/4701

add bf1 description to readme [skip tests]

---

docs/changelog.rst

Just a small changelog update.

Update changelog [skip tests]

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/pfs7_multiple_payments.yaml

Fixes: #4591 
I had some problems running the SP locally (not related to the scenario), so I am not a hundred percent sure this scenario works yet.
This scenario tests that the PFS can handle many capacity updates and that the correct amount of IOUs are created for a lot of requests.

Add scenario for multiple payments

---

raiden/tests/scenarios/README.md

Fixes https://github.com/raiden-network/raiden/issues/4733

Add README entries for pfs8 and pfs9 [skip tests]

---

raiden/tests/utils/factories.py

When creating a LockedTransferSignedState or LockedTransferUnsignedState
with the test factories, the locked_amount and transferred_amount of the
BalanceProof were set to the usual defaults of 0 and 10. Use the
transfer's amount as a default for locked_amount and 0 as a default for
the transferred_amount instead.

More sensible default values in test utils

---

raiden/api/rest.py

More typing for the REST API.
- Safety
- Commits
- Specs

Add more typing to rest API

---

raiden/settings.py

Fixes: #4745 
- Safety
- Commits
- Specs

Adds a min REI threshold of ~1.1.$

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/ms4_udc_too_low.yaml

This implements the first of the scenarios in https://github.com/raiden-network/raiden/issues/4593

add udc too low scenario [skip tests]

---

raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml

Fixes https://github.com/raiden-network/raiden/issues/4717

use udc deposit to match new MR price [skip tests]

---

raiden/network/proxies/token_network.py

Added some comments regarding lock usage in the token network proxy. Please make sure the underlying rationale is clear.
- Safety
- Commits
- Specs

Exnteded the comments on how locks are used by the TokenNetwork

---

docs/private_net_tutorial.rst
raiden/api/python.py
raiden/app.py
raiden/settings.py
raiden/tests/fixtures/blockchain.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/cli/test_cli_development.py
raiden/tests/integration/cli/test_cli_production.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/utils/smoketest.py
raiden/ui/cli.py
raiden/ui/console.py
raiden/ui/startup.py
tools/gas_cost_measures.py

as discussed today. This simplifies the codebase, and improves the code coverage.
Different contract_version's will be available on different releases.
It is a refactoring. This removes many `if` statements so the testing will be easier.  Another design choice is to make the same `raiden` client talk with many different contract_version's.  That adds complexity in the code.  On the other hand, the current approach incurs costs on maintaining multiple branches.
- Safety
- Commits
- Is it a user facing …

Unify {PRODUCTION,DEVELOPMENT}_CONTRACT_VERSION

---

raiden/app.py

Just fixes the formatting of two `node`  fields in the logs.
- Safety
- Commits
- Specs

Fix formatting of node name in logs

---

raiden/network/rpc/client.py

Parity will always return a receipt, even if the transaction is not
mined:
https://wiki.parity.io/JSONRPC-eth-module#eth_gettransactionreceipt
This means that if a transaction is not mined, there will be a receipt
with a value of `None` for the `blockNumber`. And an exception is raised
when that value is added to the confirmation block.
- Safety
- Commits
- Specs

Parity: Handle receipt of unmined transactions

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

Changes UDC balance in bf1 scenario [skip tests]

---

raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml

Fixes https://github.com/raiden-network/raiden/issues/4807

Fix wrong assertion and only return one path [skip tests]

---

raiden/network/pathfinding.py

Adds handling of no route found [test missing]

---

raiden/raiden_service.py

Just a paragraph explaining why there is a check for the existing payment id

Explain why there is a check for an existing payment [skip tests]

---

raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Fixes: https://github.com/raiden-network/raiden/issues/4817

Only use one path per request [skip tests]

---

raiden/tests/scenarios/ms4_udc_too_low.yaml

Fixes: https://github.com/raiden-network/raiden/issues/4831

Fix MS4: add tasks keyword [skip tests]

---

docs/index.rst
docs/proxies.rst

I'm adding some documents about the contract proxies.  This documentation is intended for Raiden implementors.
- Safety
- Commits
- Specs

Document Contract Proxies

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/mediated_transfer/mediator.py

Improve imbalance fee handling for edge cases
I'm pushing this early to avoid conflicts with @palango's work.
Follow-up todos:
* add one more edge case
* make tests more concise
Relates to https://github.com/raiden-network/raiden/issues/4858
- Safety
- Commits
- Specs

Improve imbalance fee handling for edge cases

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/client.py
raiden/tests/utils/factories.py

Followup to https://github.com/raiden-network/raiden/pull/4868. Contains test cleanup and one additional test for the interesting case that the negative imbalance fee makes a transfer fail.
Closes https://github.com/raiden-network/raiden/issues/4858
- Safety
- Commits
- Specs

Imbalance fee edge case test improvements

---

raiden/storage/ulid.py

Displays niceer representations of `ULID` in the logs.
- Safety
- Commits
- Specs

Pretty repr for ULID

---

raiden/raiden_service.py

Fixes: #2793
The transactions should not be handled serially during start up, this
incurs into a lot of delay for the node to finish the start up.
This will send the transactions in parallel during the startup:
This was fixed by: https://github.com/raiden-network/raiden/pull/2985
But https://github.com/raiden-network/raiden/pull/3522 reverted the change :( .
- Safety
- Commits
- Specs

Fix regression

---

docs/rest_api.rst

Fixes: #2523 
- Safety
- Commits
- Specs

Add documentation on the balance update delay after initiator return.

---

docs/rest_api.rst

Fixes: #3534 
- Safety
- Commits
- Specs

Add secret/secret_hash to payment API response

---

raiden/tests/conftest.py
raiden/ui/cli.py
raiden/utils/profiling/__init__.py
raiden/utils/profiling/constants.py
raiden/utils/profiling/cpu.py
raiden/utils/profiling/graph.py
raiden/utils/profiling/profiler.py
raiden/utils/profiling/sampler.py
raiden/utils/profiling/stack.py
raiden/utils/profiling/timer.py
raiden/utils/profiling/trace.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements-docs.txt
requirements/requirements.txt
setup.cfg

Investigating #4872
This adds a sampler profiler that produces flame graph data. I had to use a custom made tool because nothing else works with gevent.
- Safety
- Commits
- Specs

Utils to produce flamegraph data

---

raiden/api/python.py

Fixes: #3544
This just changes the waiting utility to correct one.
- Safety
- Commits
- Specs

Fix for #3544

---

docs/Token-Swap.md
docs/changelog.rst
docs/index.rst
docs/rest_api.rst
docs/token_swaps.rst

Atomic swaps docs

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml

Requires: raiden-network/scenario-player#340
Fixes: raiden-network/scenario-player#333

Update MS/BF scenarios to use new assert_events filters

---

raiden/network/pathfinding.py

Fix message wording in PFS connection and price advertising
- Safety
- Commits
- Specs

Fix message wording in PFS connection and price advertising

---

raiden/tests/unit/test_node_queue.py
raiden/tests/unit/transfer/test_node.py
raiden/tests/unit/transfer/test_source_routing.py
raiden/tests/utils/protocol.py
raiden/transfer/node.py

Part of #4735
This just updates `node.py`, the same need to be done for other handlers.
- Safety
- Commits
- Specs

Fix handlers in node.py to follow naming convention

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/mfee1_flat_fee.yaml

Part of #4748 
Adds scenarios for mediation fees
- Safety
- Commits
- Specs

Flat mediation fee scenario

---

docs/overview_and_guide.rst

Fix #4930
- Safety
- Commits
- Specs

Add documentation for normal log config and debug log disabling

---

docs/proxies.rst

This documents what I learned through
https://github.com/raiden-network/raiden/pull/4865
about the Proxy implementation work.
The change is purely about documentation.
- Safety
- Commits
- Specs

Some notes for proxy implementors

---

docs/index.rst
docs/raiden_services.rst

Fixes: #3607 
Adds some basic information about the services and their configuration to the user docs.
- Safety
- Commits
- Specs

Add user service docs

---

docs/proxies.rst
raiden/exceptions.py

This PR elaborates on what we do with exceptions.  @rakanalh and @hackaugusto explained a lot about exceptions to me in the last hour.
- Safety
- Commits
- Specs

Richer docs about exceptions

---

raiden/network/transport/matrix/transport.py
raiden/raiden_service.py
raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/test_recovery.py
raiden/tests/unit/test_pfs_integration.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
raiden/tests/unit/transfer/test_node.py
raiden/tests/unit/transfer/test_source_routing.py
raiden/tests/utils/factories.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/routes.py
raiden/transfer/state.py
raiden/transfer/state_change.py
raiden/transfer/views.py
raiden/utils/typing.py
raiden/waiting.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

fix #2298
- Safety
- Commits
- Specs

Added enum for NetworkState

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Fees will be tested in dedicated med fee scenarios
Fixes: #4890 
- Safety
- Commits
- Specs

Sets fees in all scenarios to 0.

---

docs/overview_and_guide.rst

Fixes: #3758.
Since we are not dealing with the so-called wormhole attack
right now. I'm documenting it in the security notices.
- Safety
- Commits
- Specs

Document "wormhole attack"

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/mfee2_proportional_fees.yaml

Adds scenario for proportional fees as part of https://github.com/raiden-network/raiden/issues/4748

Add proportional fees scenario [skip tests]

---

raiden/messages/healthcheck.py
raiden/messages/synchronization.py
raiden/messages/transfers.py

Just some drive-by fixes to docstrings.

Some fixes to docstrings [no-ci]

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/mfee4_combined_fees.yaml

Part of #4748
Adds a scenario with all fee components enabled.
- Safety
- Commits
- Specs

Add MFEE4 for combined mediation fees

---

raiden/network/rpc/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/utils/smartcontracts.py
raiden/ui/console.py

@LefterisJP You were trigger happy. Here are the requested changes.
- Safety
- Commits
- Specs

Follow up fixes for #4975

---

raiden/tests/scenarios/README.md

Added link the scenario example file

Added link the scenario example file [skip ci]

---

raiden/api/python.py
raiden/messages/monitoring_service.py
raiden/raiden_service.py
raiden/services.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/unit/test_messages.py
raiden/utils/packing.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Fixes #4980
Related contracts PR: raiden-network/raiden-contracts#1238
Supersedes https://github.com/raiden-network/raiden/pull/4981
- Safety
- Commits
- Specs

Rakanalh issue 4980

---

raiden/tests/scenarios/mfee4_combined_fees.yaml

Changes values in mfee4 to work

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Updates WebUI to v0.10.0. See WebUI releases for details.
- Safety
- Commits
- Specs

Update WebUI to v0.10.0

---

raiden/tests/scenarios/pfs4_use_best_path.yaml

Fixes: #5008 
- Safety
- Commits
- Specs

Adds a wait_blocks to pfs4 scenario

---

raiden/network/resolver/client.py

Fix resolver lint issues

---

raiden/tests/integration/test_raidenservice.py

Just a small cleanup after #5001.
- Safety
- Commits
- Specs

Remove print statement in test

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml

Update MS/BF scenarios with lower settle/reveal timeouts

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

Pass lower lock timeout to transfer than settle timeout

---

raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml

Adds mfee3 scenario, ran locally green

---

docs/changelog.rst
docs/conf.py
setup.py

Bump version to 0.200.0-rc1

---

raiden/tests/scenarios/mfee4_combined_fees.yaml

finally, mfee4 scenario working

---

.bumpversion_client.cfg

Bump bumpversion_client.cfg

---

raiden/tests/unit/transfer/test_node.py
raiden/transfer/node.py
raiden/transfer/state_change.py

Remove unused ActionNewTokenNetwork

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

Fixes: #4739 
This scenario adds a different transport server for each node which can be configured in the Scenario Player in this manner
https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml#L71-L75
- Safety
- Commits
- Specs

Adding different transport servers to each node in bf1 scenario

---

docs/changelog.rst
raiden/ui/sync.py

Fixes: #5042 
- Safety
- Commits
- Specs

Pass USER-AGENT header to etherscan

---

docs/index.rst
docs/private_net_tutorial.rst

Fix some warnings in the docs.
- Safety
- Commits
- Specs

Fix some warnings in docs

---

.circleci/config.yml

Fixes: #4960
Adds a build step to build the docs
- Safety
- Commits
- Specs

Add docs build to CI

---

raiden/network/pathfinding.py

Fix token network encoding in PFS log [skip tests]

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

Fixes: #5066
MERGE AFTER: https://github.com/raiden-network/raiden-transport/pull/38
- Safety
- Commits
- Specs

Add transport04 to BF1 scenario

---

raiden/network/transport/matrix/utils.py
setup.cfg

Adds more type annotations.
- Safety
- Commits
- Specs

Add type annotations to matrix/utils

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

We want to see if the matrix presence error also occurs when all nodes use the same matrix server
- Safety
- Commits
- Specs

Bf1 force to use tp04

---

raiden/network/transport/matrix/transport.py
setup.cfg

Part of #4033
Add more annotations to the matrix transport.
- Safety
- Commits
- Specs

Add type annotations to matrix transport

---

CONTRIBUTING.md

Instead of "dev: Ready for review" or "dev: Work in progress", we are using Draft PRs.
The contribution guide did not explain when to open a Draft PR, so reviewers were assigned to PRs that are not yet ready.
- Safety
- Commits
- Specs

Describe Draft PRs in the contribution guide

---

raiden/api/python.py
setup.cfg

Part of #4033 
More type annotations
- Safety
- Commits
- Specs

Type annotate python API

---

raiden/tests/unit/test_startup.py
raiden/ui/checks.py
raiden/ui/startup.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

This PR upgrades `raiden-contracts` to 0.33.1.
This PR upgrades the dependency files so `raiden-contracts 0.33.1` is used.
Since the new `raiden-contracts` contains new deployment files, I had to change some tests.
- Safety
- Commits

upgrade raiden-contracts to 0.33.1

---

raiden/tests/integration/api/test_restapi.py

Small fix in test for detecting bytes string

---

raiden/tests/unit/test_startup.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

This PR upgrades `raiden-contracts` from 0.33.1 to 0.33.2.  The new version provides ServiceRegistry that can be deprecated.
- Commits

requirements/deps upgrade raiden-contracts

---

raiden/tests/mocked/test_matrix_transport.py

To make the mocked tests work with the changes in #5116.

Extend matrix mock

---

raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/unit/transfer/mediated_transfer/test_mediation_fee.py
raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/unit/utils/test_mediation_fees.py
raiden/tests/utils/mediation_fees.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/mediated_transfer/mediator.py

To get the most effect of imbalance fees while avoiding negative total fees for mediations, we have to cap the mediation fees after summing up all fee components for both mediator channels.
- Safety
- Commits
- Specs

Cap sum of mediation fees for both channels

---

raiden/network/pathfinding.py
raiden/network/utils.py
raiden/utils/debugging.py
raiden/utils/echo_node.py
raiden/utils/gas_reserve.py
raiden/utils/runnable.py
raiden/utils/timeout.py
raiden/utils/typing.py
raiden/utils/upgrades.py
setup.cfg

Part of #4033 
Typecheck some more parts of `raiden.utils`.
- Safety
- Commits
- Specs

Enable type checking for more parts of raiden.utils

---

raiden/network/pathfinding.py
raiden/tests/integration/test_recovery.py

Just adds a log line to make it easier to find problems with rejected IOUs

Add a log when the PFS rejects an IOU

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Updates WebUI to v0.10.1

---

docs/private_net_tutorial.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Without this change,
https://github.com/raiden-network/scenario-player/pull/366
cannot be done.
A [bug fix in raiden-contracts](https://github.com/raiden-network/raiden-contracts/pull/1313) will remove a blocker for [smoke test in scenario player](https://github.com/raiden-network/scenario-player/pull/366).
Still work in progress because I haven't checked
As soon as this is merged, [the corresponding PR in services](https://github.com/raiden-network/raiden-services/pull/607) should be adjusted and merged quickly.
- Commits

Use raiden-contracts-0.33.3

---

raiden/tests/scenarios/bf1_basic_functionality.yaml

Change bf1 scenario back

---

raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml

Mfee2 will fail until https://github.com/raiden-network/scenario-player/pull/374 is merged.
* Wait after transfer to make balance check work
* Accept being off by 1 due to floating point accuracy in one assert.
Made possible by https://github.com/raiden-network/scenario-player/pull/374.
- Safety
- Commits
- Specs

Work around problems in mfee1 and mfee2

---

raiden/api/rest.py

Fix #5167 
- Safety
- Commits
- Specs

Correct the not implemented error strings in the API

---

raiden/network/transport/matrix/utils.py

Just added a few comments to clarify the login. Thanks @andrevmatos for the help

Comments regarding Matrix login

---

raiden/network/transport/matrix/transport.py

The function creates the room, renamed it to make it clear.

Renamed function [skip tests]

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt

Bump flake8 to 3.7.9

---

raiden/transfer/mediated_transfer/initiator.py

The checks get simpler when we return early on unusual error conditions.
- Safety
- Commits
- Specs

Refactor checks in `handle_secretrequest`

---

raiden/network/pathfinding.py

Fix #5151 
- Safety
- Commits
- Specs

If service registry address is not given quit with error

---

raiden/raiden_service.py

~~Fix #2278~~ Fix #2728.
See issue: #2728
- Safety
- Commits
- Specs

Add a warning if its the first time running raiden with this address

---

.github/auto_assign.yml

I'm on vacation starting tomorrow and @palango is back.

Update vacation status for auto assign bot

---

raiden/network/transport/matrix/transport.py

This flag was not being used.
- Safety
- Commits
- Specs

removed unused flag [skip tests]

---

raiden/network/rpc/client.py
raiden/network/rpc/smartcontract_proxy.py
raiden/tests/integration/rpc/test_client.py
raiden/tests/utils/client.py
tools/transfer_eth.py

Fixes: #4923 
- Safety
- Commits
- Specs

TransactionSlot - Protect against nonce reuse or no-use.

---

raiden/raiden_event_handler.py

Some minor logging adjustments.
- Safety
- Commits
- Specs

Prettify some log output

---

raiden/network/rpc/client.py

Added a check to make sure the slot is used only once, i.e.
send_transaction is called only once. And added a small docstring
explaining what are the cases this is protecting against.
- Safety
- Commits
- Specs

The nonce can be used only once.

---

raiden/storage/serialization/fields.py
raiden/storage/serialization/serializer.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

This is in preparation for https://github.com/raiden-network/raiden-services/issues/619
The newer version has some improvements for `DateTime` handling: https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst#300rc9-2019-07-31
- Safety
- Commits
- Specs

Update to marshmallow 3.2.2

---

tools/debugging/replay_wal.py

This adds
- a ready made helper function to print color coded presence status
- a ready made helper function to print channel balances
to `replay_wal.py`. Uncomment the respective lines in `replay_wal(...)`:
```python
```
if you want to use them.
Example output (sorry, no colors):
```
> ReceiveSecretReveal
sender='[Dan]'
secret='0x0acd6257009293684b9c12983a3ef3dc8b58fc3462ee55b3d676e3fbc2cf4f65'
secrethash='0x365edb94e9afed7342ed557f7f75bf956ac0598801ddb73233bbc56d5830bd23'
< SendSecretReveal
recipient='[Bob]'
canonical_identifier=CanonicalIdentifier(chain_identifier=0, token_network_address=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', channel_identifier=0)
message_identifier=13096693584191116042 …
```

Add two helpers to replay_wal.py

---

raiden/log_config.py
raiden/tests/unit/test_logging.py

Fixes: #5237 
- Safety
- Commits
- Specs

Redact secret from matrix log

---

raiden/transfer/token_network.py

Small change for something I noticed when looking into another issue and triggered my OCD.

Consistent use of if/elif in running state_transition based on type of StateChange

---

raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py

This just introduces a test to check when an exception is raised by the `User` class
- Safety
- Commits
- Specs

Added assumption tests for userid

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml

Fixes: #5208
See issue for a description of the scenario.
The scenario has not run successfully locally yet due to matrix bugs.

Add scenario for parallel txs from same node

---

raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/api/test_pythonapi.py

- Remove old skipped test about token swaps
- Add skip reason for test_try_secret_request_after_settle_channel
- Safety
- Commits
- Specs

Remove an old test and add reason for a skipped test

---

raiden/tests/integration/test_regression.py

Related to https://github.com/raiden-network/raiden/issues/5195
#PR review check list
- Safety
- Commits
- Specs

Skip test_regression_unfiltered_routes as flaky

---

raiden/tests/unit/test_cli.py

This should increase coverage to 100% for the raiden/utils/ethereum_clients.py module
Fix #3888
- Safety
- Commits
- Specs

Increase coverage of raiden/utils/ethereum_clients.py

---

.github/pull_request_template.md

Just moved the location of the Fixes Issue comment. It has been bothering me for a while.

PR template should explain what issue is fixed inside description

---

raiden/network/rpc/transactions.py
raiden/tests/unit/test_rpc.py

Fix #3939
- Safety
- Commits
- Specs

Increase test coverage for network/rpc/transactions.py

---

raiden/network/transport/matrix/utils.py

This is useful for debugging a user's presence when that user roams
- Safety
- Commits
- Specs

Logging Matrix userid and their presence

---

requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements-docs.txt

Upgraded the synapse server version used for our integration tests to match our testnet setting.
- Safety
- Commits
- Specs

upgraded matrix to 1.5.1

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py

Adds some more logging. These were useful when looking for the presence problem.
- Safety
- Commits
- Specs

Add some logging statements to matrix

---

raiden/tests/fuzz/test_state_changes.py

Fixes #5292 
See there for an explanation why the test is removed.

Remove the skipped test in test_state_changes.py

---

raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py

Adding assumption test.
- Safety
- Commits
- Specs

Added assumption test for the user directory search

---

.github/auto_assign.yml

Temporarily remove konradkonrad from auto-reviewers

---

raiden/tests/integration/api/test_restapi.py

Fixes: #5304 
Adds tests that were found out to be missing after a scenario written by @czepluch 
- Safety
- Commits
- Specs

Add some of the tests missing from the REST API

---

CONTRIBUTING.md

[skip tests]
Adds profiling docs.
- Safety
- Commits
- Specs

Add documentation on how the code can be profiled

---

raiden/network/transport/matrix/transport.py

This allows the room creation to happen in parallel during startup, this
is important if the Raiden node roammed Matrix server, meaning it may
have to create multiple new rooms to be able to communicate with its
partners.
- Safety
- Commits
- Specs

Concurrent whitelist during startup

---

raiden/tests/unit/test_runnable.py
raiden/utils/runnable.py

Fix #5327
- Safety
- Commits
- Specs

Add rawlink() to Runnable to comply with the greenlet interface

---

raiden/settings.py

Fixes: #5303 
- Safety
- Commits
- Specs

Update the URLs for the known matrix servers

---

tools/debugging/matrix_api_shell.py

This is based on code snippets by @ulope and was useful while debugging
for me.
[skip tests]
- Safety
- Commits
- Specs

Provide basic IPython shell with matrix login

---

.circleci/run_tests.sh
raiden/log_config.py
raiden/tests/unit/test_logging.py

The previous version did not do the file expansion, so the split logs script was never executed.
- Safety
- Commits
- Specs

Fixed file name expansion

---

raiden/transfer/mediated_transfer/mediator.py

Fix #5331
Function is removed in favour of the current code in
`mediate_transfer()` which does the same thing in a simpler way
- Safety
- Commits
- Specs

Remove unused function filter_used_routes

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml

The main point is getting the waits into the right places to avoid https://github.com/raiden-network/raiden-services/issues/639, https://github.com/raiden-network/raiden-services/issues/637 and https://github.com/raiden-network/raiden-services/issues/636.
- Safety
- Commits
- Specs

Fix problems in bf scenarios

---

.github/auto_assign.yml

Adjust reviewers

---

raiden/api/rest.py

Remove unused rest api function
- Safety
- Commits
- Specs

Remove unused rest api function

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

Bump version 0.200.0-rc2

---

raiden/network/transport/matrix/client.py
setup.cfg

Part of https://github.com/raiden-network/raiden/issues/4033
- Safety
- Commits
- Specs

Add typing to transport.matrix.client module

---

raiden/tests/integration/api/test_restapi.py

The internal events endpoint is not tested at all. This commit adds a
simple test to make sure it works.
If on the other hand we decide we don't want the endpoint I can also just remove it. But if we want it and it's there, there should at least be a test to make sure it works.
- Safety
- Commits
- Regression test for …

Add test for internal events rest api endpoint

---

raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/utils/factories.py

Fix matrix room selection

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/bf2_long_running.yaml

Fixes: #5177 
- Scenario introduces back the PR https://github.com/raiden-network/raiden/pull/2763
- The PR tries to mimic the users action of keeping the raiden node alive for a sufficiently long amount of time to check whether some bugs are introduced with a sufficiently dirty blockchain state.
- The PR does not yet introduce fees(of anykind) or interact with MS. Though it interacts with the PFS for routes.
- The scenario could be run independently by users/testers/developers to test out where it fails.
- Safety
- Commits
- Specs

Cosmins long running scenario with some config changes to adapt

---

raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py

See test docstring
Fixes: #5366 
- Safety
- Commits
- Specs

Test that overriding aliases by different users is not allowed

---

raiden/tests/scenarios/README.md
raiden/tests/scenarios/bf6_stress_hub_node.yaml

Fixes: #5324 
Currently I run into "no route" errors locally for this scenario during the 50 parallel transfers. This means that I haven't been able to successfully run the scenario yet, but as I suspect it being a problem with the PFS, I have opened a draft PR.

Add scenario for stressing hub node [skip tests]

---

raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/test_regression.py
raiden/tests/utils/protocol.py
raiden/tests/utils/transfer.py

Fix watch for unlock failures

---

raiden/network/proxies/token_network_registry.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_token_network_registry.py

This fixes a off-by-one error found while testing a fresh deployment.

Fix off by one registartion error

---

raiden/ui/cli.py
raiden/ui/runners.py

Just a small improvement for the error message.

Added information about target ethereum node [skip tests]

---

raiden/api/v1/encoding.py
raiden/api/v1/resources.py

Part of #4033
More type annotations. The module doesn't typecheck completely yet, but this leaves only two problems to be fixed.
- Safety
- Commits
- Specs

Add more typing in module api.v1.resources

---

raiden/tests/scenarios/pfs7_multiple_payments.yaml

Adding waits for PFS7

---

raiden/raiden_service.py

Fixes: #5392 
The error happens because we've broken database compatibility between 2 RCs. This should **NOT** happen with mainnet versions but if users try to run RCs where compatibility is broken, we should recommend them to use stable Raiden client versions.
- Safety
- Commits
- …

Notify users about serialization errors and recommend using stable versions

---

raiden/api/python.py
raiden/api/rest.py
raiden/exceptions.py
raiden/tests/integration/api/test_restapi.py

Fixes: #5383 
This PR fixes the problem above by curing the symptom by introducing `InvalidPaymentIdentifier` exception and raises that in case an invalid payment identifier is provided. This would prevent the error from taking place
- Safety
- Commits
- Specs

Big payment identifier

---

raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_transport.py

The displayname cache must be called before the call
validate_userid_signature. The validation is entirely based on the
displayname, and previously would do an RPC request if the displayname
was not available. The whole point of the display name cache is to avoid
these extra RPC calls, so it has to be called before the validation.
This fixes the ordering problem and additionally adds an assertion to
ensure that the error will not be repeated.

Fixed order in which the cache is used.

---

raiden/api/rest.py
raiden/api/v1/resources.py
setup.cfg

Part of #4033 
- Safety
- Commits
- Specs

Complete typing of module api.v1.resources

---

raiden/network/transport/matrix/client.py

As we wrote together, I just had to change
```py
rooms_invited_member_count=sum(
room["summary"].["m.invited_member_count"]
for room in response["rooms"]["join"].values()
),
```
to, because the fields don't seem to always exist 
```py
rooms_invited_member_count=sum(
room["summary"].get("m.invited_member_count", 0)
for room in response["rooms"]["join"].values()
),
```
- Safety
- Commits
- Specs

Add more matrix infos in debug logs

---

raiden/ui/checks.py
raiden/ui/cli.py

let the user know how to fix the problem in the error message

Added command line option to the error message

---

docs/api_walkthrough.rst
docs/red_eyes_mainnet_tutorial.rst
docs/rest_api.rst
raiden/api/v1/encoding.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/utils/smoketest.py

Fixes: #5395 
- Safety
- Commits
- Specs

API: Use our internal IntegerToString field for all int types

---

docs/changelog.rst

Add a changelog entry for bigint conversions

---

tools/debugging/mint.sh

There is one thing that has to be improved, `http` default timeout is to low since the endpoint waits for the transaction to be mined.

Tool to mint on multiple nodes

---

raiden/tests/scenarios/ci/sp2/pfs1_get_a_simple_path.yaml

Fixes: https://github.com/raiden-network/raiden/issues/5460
- Safety
- Commits
- Specs

Adapt asserts to changed scenario

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Adapts the WebUI to the changed typing of integers of the API.
- Safety
- Commits
- Specs

Updates WebUI to v0.10.4

---

raiden/tests/scenarios/ci/sp2/bf6_stress_hub_node.yaml
raiden/tests/scenarios/ci/sp2/bf7_long_path.yaml

Fixes: #5468 
- Safety
- Commits
- Specs

Changes reveal and settle timeout in bf6/7

---

raiden/tests/scenarios/ci/sp1/bf2_long_running.yaml

In our bf scenarios we should use the pfs with fee to cover a holistic test.
- Safety
- Commits
- Specs

Changes bf2 to use pfs with fee

---

raiden/network/utils.py

At first the function seems useless, added reference to the issue numbers that introduced the function.

Added docstring for `get_response_json`.

---

raiden/exceptions.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/cli/test_cli_development.py
raiden/tests/integration/cli/test_cli_production.py
raiden/tests/integration/cli/util.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/utils/network.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py

Fixes: #5445
- Check matrix response processing time, throw exception if it takes too long
- Update the sync token only after the response has been processed
Having dicts as the config options is a pain in the ass, we should work on https://github.com/raiden-network/raiden/issues/4069 after the release.
- Safety
- Commits
- Specs

Check matrix processing time

---

tools/debugging/channels_with_minimum_balance.py
tools/debugging/open_channels.py

This tool will order the opens and deposit to make sure they are executed in the best order.
Sample `json`:
```json
{
"nodes": {
"node0": {
"address": "0x5c11cc525590d9Ff8C7E4Af1704A39Df6c3884b5",
"endpoint": "http://127.0.0.1:5000"
},
"node1": {
"address": "0xa9FA88442c404716623155d150c526D8F1ae82E5",
"endpoint": "http://127.0.0.1:5001"
},
"node2": {
"address": "0x9df878E37C4B851bbe44841e72299F6f317C685C",
"endpoint": "http://127.0.0.1:5005"
}
},
"networks": {
"0xf9BA8aDF7F7024D7de8eB37b4c981CFFe3C88Ea7": [
{
"node1": "node0",
"minimum_capacity1": 1130220,
"node2": "node1",
"minimum_capacity2": 1130220
},
{
"node1": "node1",
"minimum_capacity1": 1130220,
"node2": "node2",
"minimum_capacity2": 1130220
}
]
}
}
```

tool to open channels

---

raiden/transfer/node.py

To me, this is easier to read than before. If you think this is just my personal preference and not a real improvement, please say so!
- Safety
- Commits
- Specs

Refactor `subdispatch_initiatortask`

---

raiden/network/transport/matrix/client.py

Removes some unused code.
- Safety
- Commits
- Specs

Remove unused post sync hook

---

tools/debugging/stress_test_transfers.py

This just adds timing information to the stress test script.

added the elapsed time to the stress script

---

raiden/ui/cli.py
raiden/utils/profiling/memory.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements-docs.txt
requirements/requirements.in
requirements/requirements.txt

Adds a new option `--log-memory-usage-interval` that (when enabled) logs the current memory usage.

Add memory reporting debugging option

---

raiden/tests/scenarios/ci/sp1/bf1_basic_functionality.yaml
raiden/tests/scenarios/ci/sp1/bf2_long_running.yaml
raiden/tests/scenarios/ci/sp1/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/ci/sp1/mfee1_flat_fee.yaml
raiden/tests/scenarios/ci/sp1/mfee2_proportional_fees.yaml
raiden/tests/scenarios/ci/sp1/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/ci/sp1/mfee4_combined_fees.yaml
raiden/tests/scenarios/ci/sp1/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ci/sp1/ms4_udc_too_low.yaml
raiden/tests/scenarios/ci/sp1/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/ci/sp1/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/ci/sp2/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/ci/sp2/bf5_join_and_leave.yaml
raiden/tests/scenarios/ci/sp2/bf6_stress_hub_node.yaml
raiden/tests/scenarios/ci/sp2/bf7_long_path.yaml
raiden/tests/scenarios/ci/sp2/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ci/sp2/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ci/sp2/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/ci/sp2/pfs2_simple_no_path.yaml
raiden/tests/scenarios/ci/sp2/pfs3_multiple_paths.yaml
raiden/tests/scenarios/ci/sp2/pfs4_use_best_path.yaml
raiden/tests/scenarios/ci/sp2/pfs7_multiple_payments.yaml
raiden/tests/scenarios/ci/sp2/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/ci/sp2/pfs9_partial_withdraw.yaml

By https://github.com/raiden-network/raiden/pull/5509 @ulope introduced a way to log memory usage during a scenario run. This PR adjusts all scenarios to that.
- Safety
- Commits
- Specs

Adds "log_memory_usage" to scenarios

---

raiden/ui/runners.py

This is necessary to fix race conditions. The RaidenService must be
stopped after the RestAPI since the former is required for the operation
of the later.

Make sure RaidenService is stopped after the RestAPI

---

raiden/storage/sqlite.py
raiden/waiting.py

Fixes the/one problem seen in https://github.com/raiden-network/raiden/issues/5498#issuecomment-566056875
This is done by making `get_state_changes` not get every event from the db on every invocation.
- Safety
- Commits
- Specs

Avoid getting all state changes in waiting_* functions

---

raiden/app.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/utils.py
raiden/settings.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_send_queued_messages.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/utils/network.py
raiden/ui/app.py
raiden/ui/cli.py

~~Merge after https://github.com/raiden-network/raiden/pull/5449~~
Add `MatrixTransportConfig` class, replace the config dict with it. This is the most basic refactoring, further improvements can be done afterwards.
- Safety
- Commits
- Specs

Matrix config

---

raiden/network/transport/matrix/client.py

Removes some unnecessary call indirection.
- Safety
- Commits
- Specs

Remove indirection in matrix client

---

raiden/network/transport/matrix/client.py

Removes some unused code.
- Safety
- Commits
- Specs

Matrix cleanup

---

raiden/tests/scenarios/ci/sp1/bf1_basic_functionality.yaml
raiden/tests/scenarios/ci/sp1/bf2_long_running.yaml
raiden/tests/scenarios/ci/sp1/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/ci/sp1/mfee1_flat_fee.yaml
raiden/tests/scenarios/ci/sp1/mfee2_proportional_fees.yaml
raiden/tests/scenarios/ci/sp1/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/ci/sp1/mfee4_combined_fees.yaml
raiden/tests/scenarios/ci/sp1/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ci/sp1/ms4_udc_too_low.yaml
raiden/tests/scenarios/ci/sp1/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/ci/sp1/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/ci/sp2/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/ci/sp2/bf5_join_and_leave.yaml
raiden/tests/scenarios/ci/sp2/bf6_stress_hub_node.yaml
raiden/tests/scenarios/ci/sp2/bf7_long_path.yaml
raiden/tests/scenarios/ci/sp2/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ci/sp2/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ci/sp2/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/ci/sp2/pfs2_simple_no_path.yaml
raiden/tests/scenarios/ci/sp2/pfs3_multiple_paths.yaml
raiden/tests/scenarios/ci/sp2/pfs4_use_best_path.yaml
raiden/tests/scenarios/ci/sp2/pfs7_multiple_payments.yaml
raiden/tests/scenarios/ci/sp2/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/ci/sp2/pfs9_partial_withdraw.yaml

Fixes: https://github.com/raiden-network/raiden/issues/5523

Remove memory logging level 2 [skip tests]

---

raiden/app.py
raiden/services.py
raiden/settings.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/unit/test_startup.py
raiden/ui/app.py
raiden/ui/startup.py

Work towards a strictly typed config.
- Safety
- Commits
- Specs

Add config class for services

---

raiden/blockchain/events.py

- made datetime non-optional
- remove the iteration over all event listeners in favor of local state
- logging only at the top of the poll function, this has the potential
of reducing the frequency the information is printed. But for that to
happen the ethereum node would have to be extremelly slow to serve the
filter request, in which case another greenlet has to be used anyways.

simplified logging for event pooling

---

raiden/ui/cli.py
raiden/utils/profiling/greenlets.py
raiden/utils/profiling/sampler.py
tools/debugging/stress_test_transfers.py

This just adds gevent switch tracing, te goal is to help to see if a thread is starving or blocking.

Added switch tracing

---

raiden/tests/fuzz/test_state_changes.py

Up to now, the test classes for the fuzz test had a single instance of `ChainState`. This PR changes it to a setup with multiple `ChainState` instances representing multiple Raiden nodes that will interact with each other in transfers, so we will not need to mock the interactions. The remaining parts of the fuzz tests will then be both easier to develop and more reliable.
Thanks to @pirapira for suggesting the use of multiple nodes.
Closes #4013

Multi node setup for fuzz test

---

requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

This fixes the latest problem with the scenario player.

Move 'objgraph' to normal dependencies

---

raiden/ui/app.py

Part of https://github.com/raiden-network/raiden/pull/5542

explicit arguments for setup_matrix

---

raiden/tests/unit/test_startup.py
raiden/ui/app.py
raiden/ui/startup.py

Part of https://github.com/raiden-network/raiden/pull/5542 to make the rebase easier

removed extraneous function

---

raiden/constants.py
raiden/raiden_service.py
raiden/storage/restore.py
raiden/storage/sqlite.py
raiden/storage/utils.py
raiden/storage/wal.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/unit/test_wal.py
raiden/tests/utils/factories.py
tools/debugging/stress_test_transfers.py

Snapshots were not working properly, my guess is because of the change to a single dispatch to a batch dispatch broke it. This re-works the logic to create an snapshot if the total number of state changes is greater than the target

Fix snapshotting

---

raiden/tests/unit/test_serialization.py
raiden/tests/utils/factories.py

Add roundtrip tests for all messages

---

raiden/blockchain/decode.py
raiden/blockchain/events.py
raiden/blockchain/filters.py
raiden/blockchain/state.py
raiden/blockchain_events_handler.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/proxy_manager.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/rpc/client.py
raiden/raiden_service.py
raiden/tasks.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/utils/network.py

Fixes: #2818
~Review after: #4943~
This is a big change, it is changing how the event polling is done by the Raiden client. I had to read the code from Parity and Geth to understand how the data is indexed, turns out that neither client have indexes and they always do a linear scan, and as an optimization bloom filters are used to reduce the number of blocks that are loaded.
This PR does a few things:
- Describes the above behavior in more detail in the code.
- Modeled the data structures so that only log polling based on smart contract address is supported in batch. This is necessary for performance reasons.
- Because of the above the filters have to be polled in sync, so a strategy to install and fetch filters in the same batch was introduced.
- The above changed both how the event …

Batch event polling

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Small improvements to the WebUI
- Safety
- Commits
- Specs

Updates WebUI to v0.11.0

---

raiden/connection_manager.py
raiden/network/proxies/token_network_registry.py
raiden/tests/integration/long_running/test_token_networks.py

Part of #5536
Fix some wrong comparisons of incompatible types.
- Safety
- Commits
- Specs

Fix comparisons between incompatible types

---

.github/auto_assign.yml

Make @LefterisJP selectable by the review bot again. 
- Safety
- Commits
- Specs

Add Lefteris back to list of reviewers

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py

Review/Merge after: #5275
This PR addresses the comments from #5116 
- Safety
- Commits
- Specs

Follow up to 5216

---

raiden/transfer/architecture.py

Step 1 of https://github.com/raiden-network/raiden/issues/5565
- Safety
- Commits
- Specs

Measure and log duration of state deepcopy

---

raiden/transfer/architecture.py

This reduces the time to copy our state from 1.3s to something between
0.02s and 0.08s.
- Safety
- Commits
- Specs

Use pickle instead of deepcopy (much faster!)

---

raiden/network/proxies/proxy_manager.py
raiden/network/rpc/client.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/ui/app.py
raiden/ui/checks.py
raiden/ui/sync.py

Move some methods around to give classes a single responsibility.
- Safety
- Commits
- Specs

Cleanup proxy manager

---

docs/changelog.rst
docs/rest_api.rst
raiden/api/rest.py
raiden/api/v1/encoding.py
raiden/raiden_service.py
raiden/tests/integration/api/test_restapi.py

Fixes: #5589 
- Safety
- Commits
- Specs

Include token_address in all events returned by the REST API

---

tools/debugging/stress_test_transfers.py

Only log after the HTTP response is checked.

stress test: fix log message [skip tests]

---

docs/changelog.rst
raiden/api/python.py
raiden/tests/integration/api/test_restapi.py

Fixes: #5591 
- Safety
- Commits
- Specs

REST API payment events can now be properly filtered by token_address

---

raiden/accounts.py
raiden/exceptions.py
raiden/log_config.py
raiden/tests/conftest.py
raiden/tests/unit/test_logging.py
raiden/tests/utils/smoketest.py
raiden/ui/cli.py
raiden/ui/prompt.py
raiden/utils/cli.py

Fixes: #5563
- Safety
- Commits
- Specs

Replace sys.exit() with exceptions and use specific error codes

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py

Fixes: #5535 
- Safety
- Commits
- Specs

Filter matrix events

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_matrix_transport.py

Merge-after: #5604
Fixes: #3512 
Prevent message batches exceeding max Matrix event size.

Respect Matrix max event size

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_matrix_transport.py

Reverts raiden-network/raiden#5613
This was prematurely merged. It is based on #5604 which wasn't approved yet.

Revert "Respect Matrix max event size"

---

docs/onboarding.rst

The gloabl queue is called unordered now [skip tests]

---

tools/README.md
tools/debugging/channels_with_minimum_balance_config.json
tools/debugging/stress_test_transfers_config.ini

I've added a short list of steps. Just let me know which steps need more elaboration.
Closes https://github.com/raiden-network/raiden/issues/5562.

Explain first time setup of stress test

---

tools/debugging/channels_with_minimum_balance.py

The partner node has to process the channel open before the deposit can
be done. This changes deposit greenlets, so that each will wait for the
channel to be available, and only after the deposit is requested.
It also changes the deposit to be done concurrently with the opening,
once the channel is available the deposit can be done, under some
circumstances it should be faster.

fix race condition on channel deposit

---

raiden/network/pathfinding.py

This is overly blocking, but avoids #5642 for now. A better
implementation will be done as part of https://github.com/raiden-network/raiden/issues/5647.
Closes https://github.com/raiden-network/raiden/issues/5642.
- Safety
- Commits
- Specs
- Is it a user …

Work around PFS race condition with semaphore

---

docs/private_net_tutorial.rst

There was a change in the CLI https://github.com/raiden-network/raiden/commit/4a86817e618323eba59c4955bfb06338bc52bcca so now all the contract addresses are pulled from the user deposit contract.
This PR updates the private networks setup guide to reflect these changes.
- Safety
- Commits
- …

Updates private network deployment guide

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py

Improve a type annotation.
- Safety
- Commits
- Specs

Fix type annotation

---

tools/debugging/extract_sp_exceptions.sh

This script does the following:
1. Figure out the run number of each of the existing scenarios
2. Download the logs for each of the nodes involved in the latest scenario run
3. Looks through the logs and searches for errors / exceptions and reports them
Fixes: #5636
In the Raiden root directory, to invoke:
```
./tools/debugging/extract_sp_exceptions.sh ./sp-nightly-dir # or whatever target directory you like
```
Quality check …

Download SP logs

---

raiden/ui/runners.py
setup.cfg

Part of https://github.com/raiden-network/raiden/issues/4033
- Safety
- Commits
- Specs

Add typing to module `raiden.runners`

---

raiden/storage/serialization/fields.py
raiden/storage/sqlite.py

Reverts raiden-network/raiden#5653

Revert "Remove monkey patching from `storage/sqlite.py`"

---

raiden/network/transport/matrix/client.py

We need to call sync every 30s or we'll be considered unreachable. The
old check does not catch all of those cases. Example:
0s: Sync started
20s: Sync returned
40s: Next sync started
The old check would check 40s - 20s <= 20s and succeed, but matrix will
see the node as offline for a while because the time between syncs is
greater than 30s.
The new check will notice that 40s - 0s > 20s and throws an exception.
Relates to https://github.com/raiden-network/raiden/issues/5635.
- Safety
- Commits
- Specs

Use time between syncs for timeout

---

raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_matrix_transport.py

The goal here is to know how long does it take for a presence change to propagate, this will then be added to the PFS with the idea of detecting why we are seeing 'Source not online' errors.

Added metadata about last reachability state change

---

raiden/network/transport/matrix/utils.py
raiden/network/utils.py
raiden/tests/unit/test_matrix_transport.py
raiden/tests/unit/test_utils.py

Fixes: #5626
In #5544 the algorithm to sort the available Matrix servers by response time was changed to only consider the first result.
As described in #5626, this caused some issues, namely:
- If a request failed (e.g. name resolution, network unreachable) that greenlet would return first, causing a false positive.
- The `make_client()` function that is using `sort_servers_closest()` has the option of falling back to a less optimal server in case the 'best' one (by response time) turned out to be unusable for some other reason. This was no longer possible with only one result.
This changes the algorithm back to return multiple results but still limit the worst case time we wait to gather those to a reasonable amount (7s currently), so that slow servers can't arbitrarily delay node …

Fix Matrix server sorting

---

raiden/tests/integration/test_integration_pfs.py

Fix test doc strings

---

raiden/api/python.py
raiden/api/v1/encoding.py
raiden/blockchain/decode.py
raiden/constants.py
raiden/message_handler.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/utils/smoketest.py
raiden/tests/utils/transfer.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/initiator.py
raiden/ui/app.py
raiden/waiting.py
setup.cfg

Fixes https://github.com/raiden-network/raiden/issues/5536
This lint option will prevent errors like these: https://github.com/raiden-network/raiden/pull/5669

mypy: enable strict equality check

---

tools/debugging/extract_sp_exceptions.sh

Mostly, download the logs from 2 servers and not 1.
Also separated the logs into their own date-prefixed directory
so that the base directory doesn't get polluted
- Safety
- Commits
- Specs

Improve the script to extract logs

---

raiden/storage/sqlite.py
raiden/ui/cli.py

This enables stack trace printing for threads that are holding the CPU.

enable gevent monitoring thread

---

raiden/tests/unit/test_matrix_transport.py

Tracked in https://github.com/raiden-network/raiden/issues/5678

Skip `test_sort_servers_closest`

---

tools/debugging/stress_test_transfers.py

A new process must not be started before the old one has completely
shutdown, this is necessary because Raiden forbids concurrent usage of
the same database for consistency reasons.

Bugfix: stress test wait for the Raiden shutdown

---

tools/debugging/extract_sp_exceptions.sh

- Downloads the latest SP log and looks for errors there
- Look for errors in stderr
- Look for "exception" in the JSON log.
- Safety
- Commits
- Specs

Extract SP logs - Part 2

---

raiden/utils/debugging.py

That exception is not propagated, which can leave the syste running in a
half shutdown state.

The monitor thread should not raise a grenlet exit

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/settings.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py

Also unify handling of both sync timings and remove unnecessary
defaults. Supporting defaults everywhere can make it too easy to fall
back to the default instead of using the configured values.
- Safety
- Commits
- Specs

Change sync timings (timeout=10s, latency=15s)

---

raiden/exceptions.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py

After https://github.com/raiden-network/raiden/pull/5710
- Don't spawn greenlets for presence updates
- Check the message queue max size 
- Safety
- Commits
- Specs

Less greenlets

---

raiden/utils/debugging.py

As seen in https://github.com/raiden-network/raiden/issues/5713

Initilize `Idle.before` properly

---

raiden/message_handler.py
raiden/messages/path_finding_service.py
raiden/messages/withdraw.py
raiden/tests/unit/test_serialization.py
raiden/tests/utils/factories.py

- Don't process duplicate messages on the same batch
- Force order of messages with a balance proof
- Run message handlers in threads because they may do IO

Message processing optimizations

---

.circleci/config.yml
Makefile
docker/build.Dockerfile
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

This resolves https://github.com/raiden-network/raiden/issues/4585
Fixes: https://github.com/raiden-network/raiden/issues/4585
Latest pip works fine for me on mac.

Update to latest pip

---

raiden/accounts.py
raiden/tests/fixtures/variables.py
raiden/tests/utils/eth_node.py
raiden/tests/utils/smoketest.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt
tools/startcluster.py

Update to latest raiden-contracts

---

raiden/utils/debugging.py

The variables were swapped around, the `while` was never be true.

bugfix, operators order was swapped [skip tests]

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

We accidentally changed max_token_networks to 1 in contracts version 0.34 so we need to change all the scenarios to use that.
- Safety
- Commits
- Specs

Changes scenarios to allowed token

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml

We should revert this when new contracts are deployed.
- Safety
- Commits
- Specs

Fix scenarios with MS interactions

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

The macholib change probably depends on whether `deps` is run on MacOS
or Linux.
- Safety
- Commits
- Specs

Update to raiden-contracts 0.35

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

This was necessary after the contracts update.
We should find a better solution to this. Maybe use the first token
registered in the TokenNetworkRegistry?
[skip tests]
- Safety
- Commits
- Specs

Update scenario token

---

raiden/tests/fuzz/test_state_changes.py
raiden/tests/integration/cli/conftest.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/utils/factories.py

This makes mypy and pylint now pick up those modules and produces a bunch of previously undetected violations.
These either need to be excluded or fixed.

Add missing `__init__.py` files inside the `raiden.tests` package

---

tools/debugging/extract_sp_exceptions.sh

* Remove port number
* Skip path segment `scenario-player`
* Use hostname instead of IP
[skip tests]
- Safety
- Commits
- Specs

Update SP logs URLs

---

raiden/api/python.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/utils/smoketest.py
raiden/ui/console.py

The test `test_token_registered_race` is flaky, while looking why that is the case I did this small changes to the proxies.

Small changes to proxies logging

---

raiden/utils/debugging.py

I might be masking other errors, but without this we are spamming stderr with IndexErrors (see https://github.com/raiden-network/raiden/issues/5738). Maybe @hackaugusto has a better idea what to do, here?
Closes https://github.com/raiden-network/raiden/issues/5738.
[skip tests]
- Safety
- Commits
- …

Avoid error when no idle measurement are available

---

tools/debugging/channels_with_minimum_balance.py

The assert was expecting on the wrong http response.

the open endpoint returns 201 and not 200

---

raiden/routing.py

Improves the message of the routing, including details about offline nodes, otherwise the error message will be generate from the state machine, which can be a bit more cryptic to understand.

Added info about offline nodes

---

raiden/blockchain_events_handler.py
raiden/connection_manager.py
raiden/network/transport/matrix/utils.py
raiden/raiden_service.py
raiden/ui/runners.py
raiden/utils/gevent.py
raiden/utils/runnable.py
raiden/utils/timeout.py

Add names to more greenlets.
This will make it easier to see what is happening in the switch monitor.

Add names to more greenlets

---

tools/debugging/extract_sp_exceptions.sh

Fixes formatting for me on macOS.
Also fixes the directory for scenario files.

Fix formatting and directory in SP error script [skip tests]

---

raiden/network/proxies/token_network_registry.py

Changes:
- Call to the token's total_supply.
- Check for the secret registry code.
- Checks for the current chain_id.
- Check for the participant deposit limit being greater than zero.
A few of my PRs have hit this error: https://github.com/raiden-network/raiden/issues/5744
I'm expanding the checks to try to find the problem.

Extended checks for the add_token

---

raiden/tests/unit/test_cli.py
raiden/ui/cli.py

On @LefterisJP 's request, add unit tests to the `cli` module where it makes sense. Some parts have been marked with `pragma: no cover` as it does not make sense to unit test the smoketest, or the launch of monitoring tools.
Unit test coverage increase on the module: 36% to 95%
Closes #3886

Unit tests for raiden.ui.cli

---

raiden/network/transport/matrix/client.py

Adds some more timing information

Log processing time for response queue

---

raiden/raiden_service.py

Just add the message as intended.

Add missing message to assertion [skip tests]

---

raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/unit/test_matrix_transport.py

When running under the DEVELOPMENT environment the transport will record
additional metrics and log those on `stop()`:
- Counters of how often messages are
- Passed to `sync_async()`
- Retried
- Passed to `on_messages()`
- The intervals between a message being passed to `send_async()` for the
first time and receiving a matching `Processed` message in return.

Add more performance logging to the MatrixTransport

---

raiden/network/transport/matrix/transport.py

During another PR's rebase I mistakenly left these attributes behind.

fix bad base conflict resolution

---

raiden/network/proxies/secret_registry.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/utils/formatting.py

Improves the logs of the proxies slightly

Fix block id logging

---

raiden/network/transport/matrix/client.py

Add more logging in `GMatrixClient.sync`.
Hopefully to help debugging the sync timeout issue.
(Also switches all occurrences of `time.time()` in the touched file to `time.monotonic()` to prevent errors caused by changing wall-time)

More logging in GMatrixClient.sync

---

raiden/network/transport/matrix/client.py

Hopefully, this will make all scenarios run without sync timeouts.
Closes https://github.com/raiden-network/raiden/issues/5789.

Allow first two syncs to be slow

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf5_join_and_leave.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Removing node managed from all scenarios

---

tools/debugging/extract_sp_exceptions.sh

- The log files are now compressed to speed up the download.
- Runs the multiple downloads concurrent, using the shell job control.

Speed up extract_sp_exceptions.sh

---

tools/debugging/sp-download-logs.sh

`sp-download-logs.sh user@server1 user@server2` will download the logs into the cwd

Added sp-download-logs.sh

---

raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py

This information is useful for debugging race conditions https://github.com/raiden-network/raiden/issues/5744

Block number and hash in the gas estimation msg

---

raiden/network/proxies/utils.py

These exceptions are expected to happen and are known/safe failure
conditions. They should not be logged as a critical level.
Fixes: #5788

Handle Recoverable exceptions separately

---

raiden/utils/debugging.py

The debugging code instantiates two traces, one installed by the monitor
thread and another used by our debugging code. Each instance installs a
new switch tracer and forwards the value to the previously installed
function. This means that if everything is working as expected both
Tracers will be updated with the same values, and therefore there should
be not discrepancies (There is an edge case, were the monitoring thread
would gain CPU time, *while* the trace callback is being executed, my
assumption is that this is synchronized, otherwise the code for a single
Tracer would already be wrong).
This changes the code as to check if the value differ, and the
assumption is that if this happened, then there is a problem with the
order of the function cleanup.
Because of the above, just in …

Detecting unexpected changes to the tracer greenlets

---

raiden/ui/runners.py

Disable gevent blocking check

---

raiden/tests/unit/test_cli.py
raiden/ui/cli.py
raiden/ui/runners.py

It wasn't useful any more, as both subclasses called `_start_services` anyways.

Remove MatrixRunner

---

tools/debugging/matrix/get_login.py

Useful when you want to log in to riot for debugging.

Add tiny script to print matrix login credentials

---

tools/debugging/matrix/get_login.py

Fix linting for last commit

---

raiden/tests/integration/test_recovery.py

Skip `test_recovery_happy_case` [skip tests]

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Update to raiden-contracts 0.36.0

---

.github/auto_assign.yml

konradkonrad returns as reviewer [skip tests]

---

raiden/api/v1/encoding.py
raiden/tests/integration/api/test_restapi.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

Fix some deprecation warnings, and update `marshmallow` on the way.

Fix deprecation warnings marshmallow

---

raiden/ui/runners.py

Log the signal that caused a shutdown.

Log stop signal

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport_assumptions.py
raiden/tests/mocked/test_matrix_transport.py

This will make it easier to use this in the services.

Improve API of `create_sync_filter`

---

.circleci/config.yml

Fixes https://github.com/raiden-network/raiden/issues/3693

Update solc for assumption tests

---

raiden/network/transport/matrix/transport.py
raiden/raiden_service.py

Fix whitelist healthcheck races

---

raiden/tests/integration/long_running/test_token_networks.py

See https://github.com/raiden-network/raiden/issues/5860.

Skip flaky test_participant_selection

---

MANIFEST.in

Fixes: #5852 
Add the correct requirements file to the manifest

Include correct requirements file in manifest

---

tools/debugging/stress_test_transfers.py

Without this check, the payments might only be completed from the
initiators point of view. When the target has not processed the payment
and we go to the next iteration, this can lead to error due to lack of
channel balance.
This implementation only works for the current stress test setup and
will need adaptation of we do different topologies.

Stress test: wait for target to regain balance

---

raiden/tests/integration/test_integration_pfs.py

Fixes: #5680 
This PR adds synchronisation between the apps, so that all operate on the same block when the assertions are run.

Sync apps in test_pfs_send_capacity_updates_on_deposit_and_withdraw

---

raiden/network/proxies/token_network.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/utils/network.py

Added test as part of https://github.com/raiden-network/raiden/issues/5447

Added test for concurrent deposits

---

raiden/network/rpc/client.py
raiden/tests/integration/test_regression_parity.py

pr review [skip tests]

---

raiden/raiden_service.py
raiden/tests/integration/test_integration_pfs.py

When processing a batch of state_changes we only want to update the PFS and the MS with the last relevant state_change per channel to reduce messages. 
Fixes: #5857

Only sending one ServiceUpdate-Message per batch of state changes

---

tools/debugging/stress_test_transfers.py

allow non-checksummed address in the stress test

---

raiden/utils/debugging.py

this is too verbose, ATM it is just cluterring the logs

remove the measurments from the idle logging

---

raiden/raiden_service.py

change in docstring and variable name

remove the word whitelist in raiden_service

---

raiden/api/rest.py
raiden/constants.py
raiden/raiden_service.py
raiden/settings.py
raiden/tests/fixtures/variables.py
raiden/tests/integration/api/fixtures.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/api/utils.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/utils/network.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py
raiden/ui/runners.py

First step of https://github.com/raiden-network/raiden/issues/5689
- Move REST API from runner to RaidenService
- Type config
- Fix integration test setup for the above changes

Refactor REST API

---

raiden/ui/runners.py

After #5904 there's only one runnable task left.

Cleanup NodeRunner

---

raiden/tests/utils/transport.py
setup.cfg

Fixes: https://github.com/raiden-network/raiden/issues/3727
Fixes the last remaining warnings, as far as I can tell.

Resolve warnings shown in pytest

---

raiden/utils/nursery.py
tools/debugging/matrix/generate_messages.py
tools/debugging/matrix/load_with_generate_messages.py
tools/debugging/plot/boxplot.py
tools/debugging/plot/line.py
tools/debugging/plot/scatter.py
tools/debugging/stress_test_transfers.py

This will create a few new fresh users, open a room among them, and send messages. The goal is to stress matrix and measure the time it takes for a message to propagate.

tool to stress synapse

---

raiden/constants.py
raiden/network/proxies/secret_registry.py
raiden/network/proxies/service_registry.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/proxies/user_deposit.py
raiden/network/proxies/utils.py
raiden/network/rpc/client.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/api/test_restapi.py
raiden/tests/integration/fixtures/blockchain.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/integration/rpc/assumptions/test_geth_rpc_assumptions.py
raiden/tests/integration/rpc/assumptions/test_parity_rpc_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_filters_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py
raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
raiden/tests/integration/rpc/test_client.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/utils/client.py
raiden/tests/utils/smartcontracts.py
raiden/tests/utils/smoketest.py
raiden/ui/console.py
raiden/utils/gas_reserve.py
raiden/utils/smart_contracts.py
raiden/utils/testnet.py
tools/transfer_eth.py

~~Review/Merge after #5879~~
This PR changes how transactions are sent, there are few improvements:
- explicit lifecycle using different types
- better logging
- less duplicate code (for the smart contract calls)

Transactions logging and lifecycle

---

raiden/tests/integration/network/proxies/test_secret_registry.py

Address the request from #5886

pr review #5886

---

raiden/network/proxies/token_network.py
raiden/network/proxies/utils.py

Extracts some changes from https://github.com/raiden-network/raiden/pull/5871 to see why that one fails.

Fix formatting of block identifiers

---

raiden/network/rpc/client.py

Remove unused function from RpcClient

---

raiden/api/v1/encoding.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/utils/cli.py
raiden/utils/http.py
raiden/utils/profiling/profiler.py
raiden/utils/profiling/sampler.py
raiden/utils/profiling/trace.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt
setup.cfg

Update to mypy 0.761

---

raiden/api/rest.py

This adds a check that only accepts requests new requests when the API
is not shutting down.
Some foundational work was done in https://github.com/raiden-network/raiden/pull/5904
Fixes: #5689

Fix race conditions on API shutdown

---

.github/auto_assign.yml

tmp disable ulope from autoreview

---

.github/auto_assign.yml

temporarily disable paul

---

raiden/utils/nursery.py
tools/debugging/stress_test_transfers.py

Fixes to bugs that prevents the stress test from running

Bugfix fix stress test

---

raiden/api/rest.py

I just saw 2 typos and wanted to fix those

Fixes some typos [skip tests]

---

raiden/utils/nursery.py

* Prevent processes being started with `shell=True`, as the nursery
would track the shell instead of the processes
* If processes do not terminate within 20s, kill them
* Show exit code for processes that did not shut down cleanly
[skip tests]

Small Janitor improvements

---

raiden/blockchain/events.py
raiden/network/proxies/token_network.py
raiden/network/rpc/client.py
raiden/raiden_service.py
raiden/storage/serialization/serializer.py
raiden/tests/conftest.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/mocked/test_matrix_transport.py
raiden/transfer/channel.py
raiden/ui/checks.py

Follow up with fixes requested on the PR reviews for #5970 #5631 and #5912

Pr reviews

---

raiden/network/transport/matrix/client.py
raiden/ui/cli.py

Fix typos in 'occurred' [skip tests]

---

raiden/tests/integration/long_running/test_token_networks.py

Remove unused function `estimate_blocktime`

---

raiden/utils/nursery.py

The callback has to be executed outside of the hub.

bugfix: would block forever exception raised on callback

---

raiden/network/proxies/secret_registry.py

Set correct tx hash in `register_secret_batch`

---

.circleci/config.yml
raiden/constants.py

This reverts commit 913bba2af815bbb260dbd4253d35070f23ad9822.

Revert "Update geth to v1.9.12"

---

raiden/network/rpc/client.py

As discussed in the planning meeting.

Increase gas margin from 10% to 50%

---

raiden/api/rest.py
raiden/messages/path_finding_service.py
raiden/network/proxies/token_network_registry.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py
raiden/ui/app.py
raiden/utils/cli.py
raiden/waiting.py
setup.cfg

Fixes: #4443
Enables mypy's `warn-unreachable`

Enable mypy `warn_unreachable` and fix warnings

---

raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/rpc/client.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/network/proxies/test_secret_registry.py
raiden/tests/unit/utils/test_filters.py
raiden/ui/checks.py

Fix mypy warnings related to `BlockNumber`

---

raiden/blockchain/events.py
raiden/blockchain/filters.py
raiden/network/proxies/custom_token.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/user_deposit.py
raiden/network/rpc/client.py
raiden/tasks.py
raiden/tests/unit/network/rpc/test_client.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py
raiden/utils/typing.py

Use more types from web3

---

.circleci/config.yml
raiden/tests/utils/transport.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

We've updated our test servers to this version.
Therefore the local tests should also use it.

Update synapse to 1.10.1

---

.circleci/config.yml

Add a production smoketest on parity to make tests symmetric

Add production smoketest on parity

---

.circleci/config.yml
raiden/blockchain/events.py
raiden/blockchain/filters.py
raiden/network/proxies/token.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/network/rpc/client.py
raiden/network/rpc/middleware.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/unit/utils/test_filters.py
raiden/tests/utils/smoketest.py
raiden/ui/app.py
raiden/ui/checks.py
raiden/ui/cli.py
raiden/ui/startup.py
raiden/ui/sync.py
raiden/utils/cli.py
raiden/utils/typing.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt
tools/startcluster.py

Fixes: #5999
This PR updates the `raiden-contracts` dependency. This also bumps `web3` which enables stricter type checks. The remaining typing issues are also fixed in this PR.

Update raiden-contracts, fix typing issues

---

docs/changelog.rst
docs/rest_api.rst
raiden/api/rest.py
raiden/api/rest_utils.py
raiden/api/v1/resources.py
raiden/app.py
raiden/raiden_service.py
raiden/tests/integration/cli/util.py
raiden/tests/utils/network.py
raiden/ui/app.py
raiden/ui/sync.py

Start the `APIServer` earlier and add a `/status` endpoint to query service availability and syncing progress.
Closes #5281

/status API endpoint

---

.circleci/config.yml
requirements/requirements-ci.txt
requirements/requirements-dev.txt

Adds the scenario player smoketest to be run in the scenario player tests in circle ci

add scenario player smoketest to raiden ci

---

pylintrc

enable pylint joinall check

---

raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/transfer/channel.py
raiden/transfer/mediated_transfer/initiator.py
raiden/transfer/mediated_transfer/initiator_manager.py
raiden/transfer/mediated_transfer/mediator.py

This is just an extra safety check for the lock expiration.

make sure initiator only unlocks if lock has not expired

---

docs/adr/0006-transport-mulitlayer-with-webRTC.rst
docs/adr/overview.rst

ADR for our transport decision to implement webRTC for short term improvements

Create ADR 0006-transport-mulitlayer-with-webRTC.rst

---

raiden/utils/nursery.py

Log args when process in janitor dies [skip tests]

---

raiden/network/transport/matrix/transport.py

#Description
The error happened after Anyblock was introduced into the federation and especially as the first server in the list.
Once there is a new first server in the list, broadcast rooms of this server will be used in the future. This leaves the node in an old public room with multiple addresses. By definition, these rooms (excluding broadcast rooms and it is not a broadcast room anymore) should be left automatically once multiple addresses are in a room.
Now the tricky part comes. Besides all the old addresses there are also the admin users of the servers in the room. These do not follow the Displayname/Username scheme.
When the room is inspected by the transport if there are multiple addresses in the room, they get extracted by Displayname. Obviously, the admin users do not have a …

Handle users with none extractable address out of display name

---

raiden/ui/runners.py

disable SIGPIPE handler

---

.bumpversion_client.cfg
docs/conf.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
setup.py

This bumps the version to `0.200.0-rc4`.
Please wait for and rebase on https://github.com/raiden-network/raiden/pull/6048

Bump version for release candidate 0.200.0-rc4

---

raiden/settings.py

Change production known servers url to mainnet testing RSBs

Change production known servers url to mainnet testing RSBs

---

.bumpversion_client.cfg
docs/conf.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
setup.py

- update contracts to `0.37.0b3`
- bump version to `0.200.0-rc5`

0.200.0-rc5

---

raiden/api/rest.py

Don't serve fallback HTML to WebUI json requests

---

.github/auto_assign.yml

- paul is on vacation
- ulope is back
[skip tests]

update auto assing

---

requirements/requirements-ci.txt

I accidentally removed macholib in https://github.com/raiden-network/raiden/pull/6047/files#diff-cedd943d509764d3d0882b6d3a72ceaeL81 :(
This fixes it.

Fix missing requirement

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

Release 0.200.0-rc7

---

README.md

fix typos [skip tests]

---

raiden/network/transport/matrix/transport.py

This PR lets retry queues only start if the transport is yet started. The corresponding error was described in #6071. The error happened due to `raiden_services.initialize_message_queue` run before `transport.start()`.
The condition that all retry queues should be started unconditionally was due to a race condition in the `transport.stop()` method which would then block forever. This is now removed by only wait for retry_queues to finish gracefully which have not been started yet.

Start Retry Queue only after transport is started

---

docker/Dockerfile

To run the latest raiden webui Version we'd like to use a more or less stable version.
--> Using the test env raiden version

[skip tests] Update Dockerfile

---

raiden/network/proxies/token.py

An unhandled case in `Token.transfer()` caused Raiden to crash. It happened when a token transfer with unsufficient balance is estimated. It resulted in an Unbound local error described in #6082.  
Fixes: #6082

fix token proxy

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py
setup.py

0.200.0rc8

---

raiden/message_handler.py

Using a dict is unnecessary for this.

Use a set instead of a dict to remove duplicates

---

raiden/network/proxies/user_deposit.py
raiden/network/proxies/utils.py
raiden/tests/integration/network/proxies/test_user_deposit.py

This does not have the usual amount of checks, but it is still better
than using the contract directly and it helps me to proceed with
https://github.com/raiden-network/scenario-player/issues/543.

Add withdraw functionality to UserDeposit proxy

---

raiden/network/rpc/client.py

This information is useful to figure why the gas estimation failed.

Include the approx. block if gas estimation fails

---

raiden/network/rpc/client.py

Just removes the outdated docs

Rpcclient outdated doc

---

.github/auto_assign.yml

re-add paul

---

pylintrc
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/api/rest/test_rest.py
raiden/tests/integration/long_running/test_stress.py
raiden/tests/integration/long_running/test_token_networks.py
raiden/tests/integration/test_regression.py
raiden/tests/mocked/test_matrix_transport.py
raiden/tests/unit/test_runnable.py
raiden/tests/utils/transfer.py
tools/pylint/gevent_checker.py

The goal here is avoid that this happens again: https://github.com/raiden-network/scenario-player/pull/550

Add lint for gevent waiting

---

raiden/exceptions.py

Added context for the values in the formatted exception msg.
[skip tests]

Clarified error message.

---

raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml

Part of #6158
After increasing the PFS cost, we need to adapt the UDC deposit as well.

Fix UDC deposits for BF3 and BF4

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml

Add margin to all deposits when pfs fee are used [skip tests]

---

raiden/network/rpc/client.py

Fixes #6138
Also corrects a comment

Fix error message for failing SC calls

---

raiden/utils/nursery.py

When the janitor reaches `__exit__`, it kills all nodes. We do not want
error messages for those, unless they fail at shutting down cleanly.
Closes https://github.com/raiden-network/scenario-player/issues/474.

Silence nodes killed by janitor

---

raiden/ui/cli.py

Thanks @karlb for noticing this.

Dont report ctrl-c as an error

---

raiden/network/proxies/README.md

This was in a separate hackmd file for input, it has not changed in
quite a while and the information is important to understand how the
proxies works.
related: https://github.com/raiden-network/raiden/issues/5488

Added docs about the proxy strategy

---

raiden/settings.py
raiden/tests/integration/cli/conftest.py
raiden/tests/integration/cli/test_cli_development.py
raiden/tests/integration/cli/test_cli_production.py
raiden/tests/utils/transport.py
raiden/ui/app.py
raiden/ui/console.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements-docs.in
requirements/requirements-docs.txt
requirements/requirements.in
requirements/requirements.txt

Merge-after: #6189 
We were stuck on ancient IPython 4.x
This also required to upgrade out ancient sphinx version but it seems
there are no incompatibilities caused by it.

Upgrade to IPython 7

---

LICENSE

Update LICENSE for 2020 [skip tests]

---

raiden/tasks.py

Makes min RDN message a bit clearer

---

raiden/transfer/mediated_transfer/initiator.py

Part of https://github.com/raiden-network/raiden/issues/6188

Add link to docs for fee limit error [skip tests]

---

README.md

Changing docs link and INFO

---

docs/changelog.rst
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Add the warning for low transfer amounts.

Updates WebUI to v0.11.1 [skip tests]

---

raiden/constants.py
raiden/tasks.py
raiden/ui/app.py

Just adds some missing spaces.

Add missing spaces [skip tests]

---

README.md

Adds correct release link [skip tests]

---

raiden/raiden_service.py
raiden/tests/integration/test_raidenservice.py

Resolves #6079 
Catch the `filelock.Timeout` and reraise it as `RaidenUnrecoverableError`

Catch `filelock.Timeout` exception

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Update `flask` and `flask-restful`

Update flask and flask-restful

---

docs/overview_and_guide.rst

It is a style fix in the documentation.

Properly stylize link to Infura

---

raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py

See https://github.com/raiden-network/raiden/issues/6261

Skip flaky test [skip tests]

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

Don't require `py-solc` and `py-geth`

---

raiden/network/rpc/client.py

This just enables the cache middleware used by the scenario player, the goal here is to consolidate the cache strategies.

Introduce simple cache middleware

---

Makefile
raiden/storage/serialization/types.py
raiden/transfer/mediated_transfer/mediation_fee.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Just two minor changes. See commit comments.

Update mypy & fix Makefile error

---

raiden/raiden_service.py

The rules on PFSFeeUpdates have been clarified in https://github.com/raiden-network/spec/pull/333 and are updated accordingly in this PR.
Closes #5897.

Update sending of PFSFeeUpdate and link to spec

---

requirements/requirements-dev.in

Remove `autopep8` depdendency

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Finally the redesigned WebUI is tested and ready for a release.

Updates WebUI to v1.0.0

---

requirements/requirements.in
requirements/requirements.txt

upgrade raiden-contracts dependency to 0.37.1

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Important fixes. See WebUI release for changes
https://github.com/raiden-network/webui/releases/tag/v1.0.1

Update WebUI to v1.0.1

---

raiden/settings.py

We moved the matrix server list to a new location.

Fix location of test matrix server list

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/ui/app.py

- Fix a wrong description in BF1 
- Make config creation a bit cleaner

Small fixes

---

raiden/tests/unit/test_channelstate.py
raiden/tests/unit/test_matrix_transport.py
raiden/transfer/architecture.py
raiden/transfer/mediated_transfer/mediator.py
raiden/transfer/views.py
requirements/requirements-dev.in
requirements/requirements-dev.txt
setup.cfg
tools/debugging/plot/line.py
tools/debugging/replay_wal.py
tools/process_results.py

Adds flake8-comprehensions package.
For now I ignore the warning about using `[]` instead of `list()` as we agreed on using those.

Add flake8-comprehensions

---

raiden/tests/integration/api/rest/test_payments.py
raiden/tests/integration/api/rest/test_rest.py

Cleanup API tests

---

raiden/api/python.py
raiden/tests/integration/api/test_pythonapi.py

Removes unused create_monitoring_request

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py

Merge master back to develop to use the right version number.

Merge master

---

tools/raiddit/README.md
tools/raiddit/generate_claims.py

Adapt Freds claim generator.
- Adds `chain_id` and `token_network_address` to the claims.
Part of https://github.com/raiden-network/raiddit/issues/31

Adapt Freds claim generator

---

raiden/claim.py
raiden/raiden_service.py
raiden/storage/serialization/types.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/transfer/test_claims.py
raiden/tests/utils/network.py
tools/raiddit/generate_claims.py

Read claims from file during startup.

Fred changes

---

raiden/claim.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/transfer/test_claims.py

- Handle claims file with no entries well
- Disable `claims` fixture by default

Handle no claims file properly

---

.circleci/config.yml

Update cache revision to fix build

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Adds the udc deposits and token on-chain balances to the header.

Update WebUI to v1.0.2

---

.circleci/config.yml
raiden/api/python.py
raiden/claim.py
raiden/network/proxies/payment_channel.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/fixtures/smartcontracts.py
raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/transfer/test_claims.py
raiden/tests/utils/factories.py
raiden/tests/utils/network.py
raiden/tests/utils/smoketest.py
raiden/transfer/state.py
raiden/transfer/views.py
raiden/ui/console.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
tools/raiddit/generate_claims.py

Fixes: https://github.com/raiden-network/raiddit/issues/37
- Use `raiddit` raiden-contracts (branch version)
- Pass `claim` arguments to proxy settle functions
- Introduce `EmptyClaim`
- Introduce a method stub in `views` module, to query a certain claim; this needs to be implemented (see `FIXME`)
Note: pushing this PR for review before I fixed tests, in order to synchronize with @palango

[Raiddit] Client claim settle

---

raiden/claim.py
raiden/raiden_service.py
raiden/tests/fixtures/variables.py

Increase settle_timeout again to make mediated payments work

---

raiden/tests/integration/network/proxies/test_payment_channel.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/integration/test_raiddit.py
raiden/tests/integration/transfer/test_refundtransfer.py

Adds a basic integration test to cover the basic raiddit functionality. Burning and settlement are still to be added.

Add integration test for basic functionality

---

.circleci/config.yml
raiden/tests/integration/api/rest/test_channel.py
raiden/tests/integration/api/rest/test_payments.py
raiden/tests/integration/api/rest/test_rest.py
raiden/tests/integration/api/test_pythonapi.py
raiden/tests/integration/api/test_pythonapi_regression.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/network/proxies/test_token_network.py
raiden/tests/integration/network/proxies/test_token_network_registry.py
raiden/tests/integration/test_balance_proof_check.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/test_regression_parity.py
raiden/tests/integration/transfer/test_claims.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py

Skip failing tests for now

---

.github/auto_assign.yml

Adapt reviewer list [skip tests]

---

raiden/api/python.py
raiden/network/proxies/token_network.py
raiden/network/proxies/token_network_registry.py
raiden/raiden_event_handler.py
raiden/raiden_service.py
raiden/tests/integration/api/rest/test_rest.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/integration/test_raiddit.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/unit/test_tokennetwork.py
raiden/tests/unit/transfer/test_channel.py
raiden/tests/unit/transfer/test_node.py
raiden/transfer/architecture.py
raiden/transfer/channel.py
raiden/transfer/events.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/utils/claim.py
raiden/utils/packing.py
raiden/waiting.py

Add burning and channel closing to raiddit test.

Add channel burning and closing to raiddit test

---

raiden/transfer/channel.py

Document disabled check

---

raiden/utils/claim.py

Make claim amounts chose-able.

Allow setting claim amounts

---

raiden/raiden_service.py

With these two bugs fixed, I get successful raiddit transfers when using a PFS.

Raiddit transfer fixes

---

raiden/constants.py
raiden/utils/claim.py
tools/raiddit/claims_to_network_json.py
tools/raiddit/generate_claims.py

- Add option to generate direct channel claims as well
- Add script to generate sigma.js topology file

Direct channels

---

docs/onboarding.rst
raiden/api/python.py
raiden/network/proxies/secret_registry.py
raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
raiden/ui/cli.py

https://github.com/raiden-network/raiden/search?q=%22the+the%22&unscoped_q=%22the+the%22

remove double the in codebase

---

raiden/tests/integration/rpc/assumptions/test_rpc_events_assumptions.py
raiden/tests/utils/smartcontracts.py

This is just an assumption test to exercise the corner case, the goal is to show that this is possible to happen, failure of this test is not a problem, since it only exists to demonstrate that a corner case exists, for this reason the test is skipped.

Added test for events happening in the deployment block

---

tools/debugging/matrix/get_login.py

* Update to new transport server names
* Allow password to be empty

Update matrix debugging get_login.py

---

raiden/tests/conftest.py

For unknown reasons, calling `setitimer` fails in some cases with
`signal.ItimerError: [Errno 22] Invalid argument`. Let's print the bad
argument to get a better idea of what's happening.
Examples of the error:
https://app.circleci.com/pipelines/github/raiden-network/raiden/9748/workflows/9bb81b94-d56f-4d64-ae58-1be7269dda42/jobs/139061
https://app.circleci.com/pipelines/github/raiden-network/raiden/9712/workflows/88b1b934-03f1-4f3f-abc7-497d540356bd/jobs/138133
https://app.circleci.com/pipelines/github/raiden-network/raiden/9781/workflows/1c89226b-cd54-42d9-b908-dd9eda75ea94/jobs/139924
https://app.circleci.com/pipelines/github/raiden-network/raiden/9771/workflows/d19e832a-2fdf-45e8-ac16-def56028c37b/jobs/139665
This is currently the most common flaky error on the develop branch.
Also …

Add output when setting itimer fails

---

.github/dependabot.yml

Let the bot create some more parallel PRs

Increase number of open dependabot PRs [skip tests]

---

raiden/transfer/mediated_transfer/mediator.py

Just improve a tiny type annotation.

Specify dict types in mediator [skip tests]

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/rtc/aio_queue.py
raiden/network/transport/matrix/rtc/web_rtc.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/tests/integration/network/transport/test_aiortc.py
raiden/tests/unit/test_matrix_transport.py
setup.cfg
tools/debugging/channels_with_minimum_balance.py
tools/debugging/matrix/generate_messages.py
tools/debugging/matrix/load_with_generate_messages.py
tools/debugging/stress_test_transfers.py

Refactor the transport - aiortc communication such that coroutines and greenlets are called directly and no queue is used.

refactor create channel to not use queue

---

raiden/api/python.py
raiden/message_handler.py
raiden/tests/unit/transfer/test_source_routing.py
raiden/tests/unit/transfer/test_views.py
raiden/transfer/architecture.py
raiden/transfer/mediated_transfer/tasks.py
raiden/transfer/views.py

Fixes: #4076
Make this an enum instead of using string values.

Make transfer role an enum

---

raiden/message_handler.py

* Move common code out of the cases
* remove outdated ignores
* return without assigning to intermediate variable

Refactor handle_message_lockedtransfer

---

raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
raiden/tests/utils/factories.py
setup.cfg

I was annoyed by the lack of testing when I tried to modify a test.

Add mypy typing to test_mediatorstate.py

---

raiden/transfer/mediated_transfer/mediator.py

There's less state carried through the function by returning early
whenever the result is clear. This is much easier to read for me, I hope
this is true for others, too.

Refactor mediate_transfer

---

raiden/api/python.py
raiden/api/rest.py
raiden/blockchain/events.py
raiden/blockchain/exceptions.py
raiden/blockchain/utils.py
raiden/constants.py
raiden/exceptions.py
raiden/network/transport/matrix/client.py

Remove dead code found by vulture

---

raiden/raiden_service.py
raiden/storage/wal.py
raiden/tests/unit/test_wal.py
raiden/tests/utils/mocks.py
raiden/transfer/architecture.py
tools/debugging/replay_wal.py

Fixes: #6524 
After #6484 the StateManager has no purpose any more and is removed in this PR.

Remove StateManager

---

raiden/routing.py
raiden/tests/integration/api/rest/test_rest.py
raiden/tests/integration/long_running/test_integration_events.py
raiden/tests/integration/long_running/test_settlement.py
raiden/tests/integration/test_integration_pfs.py
raiden/tests/integration/test_recovery.py
raiden/tests/integration/test_regression.py
raiden/tests/integration/transfer/test_mediatedtransfer.py
raiden/tests/integration/transfer/test_mediatedtransfer_events.py
raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
raiden/tests/integration/transfer/test_refundtransfer.py
raiden/tests/utils/transfer.py

Part of #6496
Remove more internal routing from tests.

Remove internal routing from tests

---

raiden/__main__.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/rtc/aiogevent.py
raiden/network/transport/matrix/rtc/web_rtc.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/settings.py
raiden/tests/conftest.py
raiden/tests/integration/api/rest/test_payments.py
raiden/tests/integration/conftest.py
raiden/tests/integration/network/transport/test_aiortc.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/network/transport/test_web_rtc.py
raiden/tests/unit/test_matrix_transport.py
raiden/tests/utils/transport.py
raiden/utils/capabilities.py
raiden/utils/runnable.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
setup.cfg
tools/debugging/channels_with_minimum_balance.py
tools/debugging/matrix/generate_messages.py
tools/debugging/matrix/load_with_generate_messages.py
tools/debugging/matrix/presence_report.py
tools/debugging/matrix/presence_update.py
tools/debugging/stress_test_transfers.py
tools/pyinstaller_hooks/runtime_gevent_monkey.py

This is WIP. This draft is used for reviewing purposes and not yet production ready.
This PR contains the introduction of using WebRTC on top of Matrix. It is implemented by using the `aiortc` package. To have a asyncio loop `aiogevent` is used.
The current design has two separated loops in the geventland und aiokingdom. The consumer and producer of events communicate via a queue passing data back and forth. Every time data needs to be send from gevent to aio it is wrapped into an event and passed via a queue.
On the other side a consumer is waiting to pick up a event and processing it.
- Upon joining a room start negotiating protocol via the private matrix room of between two participants
- creating web rtc channels
- always send message via webrtc, if there is no channel use matrix as a …

Web RTC MVP

---

docker/build.Dockerfile

Fixes: https://github.com/raiden-network/raiden/issues/6552

Add additional requires for aiortc

---

.pre-commit-config.yaml
raiden/tests/integration/cli/conftest.py
raiden/tests/utils/smoketest.py
tools/debugging/json-log-to-html.py

Required-for: raiden-network/scenario-player#601
- Add monitoring braodcast room to smoketest Matrix setup
Needed by the SP smoktest
- Drive-by fix: Add missing log level to json-log-to-html tool

Add monitoring braodcast room to smoketest Matrix setup

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt

This solves a problem with an old version in the SP repository.

Explicitly list `click` as a dependency

---

.github/auto_assign.yml

Light client for the time being.

Remove Paul from auto_assign bot [skip tests]

---

docs/changelog.rst
raiden/blockchain/decode.py
raiden/blockchain/state.py
raiden/constants.py
raiden/message_handler.py
raiden/network/transport/matrix/transport.py
raiden/network/transport/matrix/utils.py
raiden/raiden_service.py
raiden/settings.py
raiden/storage/sqlite.py
raiden/storage/wal.py
raiden/tests/integration/fixtures/raiden_network.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/tests/integration/test_raidenservice.py
raiden/tests/unit/test_matrix_presence.py
raiden/tests/unit/test_utils.py
raiden/tests/unit/test_wal.py
raiden/tests/utils/mocks.py
raiden/tests/utils/network.py
raiden/transfer/architecture.py
raiden/utils/capabilities.py
raiden/utils/typing.py
tools/debugging/replay_wal.py

Part of https://github.com/raiden-network/raiden/issues/6549
Backports fix and performance improvements for https://github.com/raiden-network/raiden/issues/6444 to master for next release.

State change fix & capabilities

---

.circleci/config.yml

After https://github.com/raiden-network/scenario-player/pull/621 we need to make some changes to run the SP test correctly.

Fix SP test, after changing package management

---

raiden/constants.py
raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/transport.py
raiden/settings.py
raiden/tests/conftest.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py
raiden/utils/capabilities.py

Backport raiden-network/raiden#6629 to master

Backport toDevice message support

---

.circleci/config.yml
raiden/tests/conftest.py
raiden/tests/utils/smoketest.py

use master branch of scenario player in ci

Circle config for master

---

docs/changelog.rst

add changelog entry for todevice message

Update changelog.rst toDevice Message

---

docs/changelog.rst

Changelog entry for Capabilities

Update Changelog for #6482 (Capabilities)

---

requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

This was accidentally backported from develop but isn't supposed to be included yet.

Remove aiortc

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/utils.py

This will ignore some of the MatrixRequestError that are not critical
but would crash the Raiden node during login, if not caught.
Fixes: #6584 
- Minor changes to how Raiden handles Matrix errors that are not critical

Ignore non-critical Matrix errors on login

---

.github/workflows/dependent-issues.yml

Allows issues / PR to be dependent / blocked by others.
See: https://github.com/marketplace/actions/dependent-issues

Add dependent issues action

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

WebUI release fixing the quick connect dialog to show an error if no pathfinding service is configured.

Update WebUI to v1.1.1

---

raiden/transfer/state.py

Before https://github.com/raiden-network/raiden/commit/922e4fdf0d54c150c1bada0d101f8085e04b68bd, Raiden could create inconsistent TokenNetworkRegistryStates. In addition to fixing that bug, we also need to be able to fix up the inconsistencies when reading old dbs. This is what is done in this commit.

Fix inconsistent states from <=v1.2.0 on read

---

docs/changelog.rst

The entries from the master branch were not added back to develop and
some other items were missing. Did I forget anything?

Update change log

---

raiden/api/python.py
raiden/constants.py
raiden/settings.py
raiden/ui/app.py
raiden/ui/cli.py
raiden/ui/runners.py
raiden/utils/cli.py

- Introduces a minimum reveal timeout setting, that also is checked in the CLI
- Allows for automatic config-file parsing of "external" click CLI option representations
Fixes: #6690, #5171, #6645

Fix config file parsing

---

.pre-commit-config.yaml
raiden/log_config.py
raiden/network/transport/matrix/utils.py
raiden/raiden_service.py
raiden/tests/utils/mediation_fees.py
raiden/tests/utils/smoketest.py
raiden/transfer/mediated_transfer/mediation_fee.py
raiden/transfer/mediated_transfer/mediator.py
raiden/ui/cli.py
raiden/utils/mediation_fees.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt

This updates the mypy dependency to
the latest version and will include typing changes
to comply with the latest version.
This will also fix the phony pre-commit error (see #6689)

Update mypy to latest version

---

raiden/tests/integration/long_running/test_settlement.py

`test_settled_lock` was flaky due to an unsynchronized state of the rpc client between the peers. One client has to call unlock and the other checks the balances. We need to give some time for the chainstate to update.

fix flaky test_settled_lock()

---

raiden/tests/integration/api/rest/test_api_wrapper.py
raiden/tests/integration/fixtures/blockchain.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

- Added tests for raiden api client. The api client wraps the raiden api, simplifying the usage of raiden for demos and applications build in python

Added raiden api client tests

---

raiden/network/transport/matrix/utils.py
raiden/tests/utils/transport.py

Change matrix device_id to RAIDEN

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml

This let's us test and adjust values quicker.
Dependent on https://github.com/raiden-network/scenario-player/pull/651

Use template values for waits in scenarios

---

raiden/network/transport/matrix/client.py
raiden/network/transport/matrix/utils.py

Disable all push notifications for a given user upon first login by enabling push rule `.m.rule.master`
Fixes: #6783

enable push rule '.m.rule.master' to disable all pushnotification

---

raiden/network/transport/matrix/client.py

it's `.m.rule.master` not `.m.master.rule`

Fix typo in disabling push notification

---

.circleci/config.yml

If merged, this closes https://github.com/raiden-network/raiden/issues/6782

Use xcode 12.3.0 in CI for MacOS

---

docs/adr/0007-drain-imbalance-fee.rst
docs/adr/0008-connection-manager-prevents-fast-sync.rst
docs/adr/0010-refunds.rst
docs/adr/0011-routing-with-token-swaps.rst
docs/adr/0012-token-swaps.rst
docs/adr/overview.rst

These documents should be easy to locate. Putting them here will surface
them when searching github or readthedocs.

Add more ADRs/discussion documents

---

raiden/tests/utils/synapse_config.yaml.template
raiden/tests/utils/transport.py
requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

In order to solve https://github.com/raiden-network/raiden-service-bundle/issues/252

upgrade synapse to 1.27.0

---

docs/onboarding.rst

Fixing 3 typos on onboarding documentation

fix small typos on onboaring documentation

---

raiden/network/transport/matrix/transport.py
raiden/tests/integration/network/transport/test_matrix_transport.py

Fixes: https://github.com/raiden-network/scenario-player/issues/661
Also add an integration test for the function.

Fix contract access in populate_services_addresses

---

.github/auto_assign.yml

Remove konradkonrad while on vacation

---

.github/auto_assign.yml

This was not intended as an upstream branch, but I guess now it doesn't matter anymore? :)

Add ezdac to autoassign

---

raiden/tests/scenarios/bf1_basic_functionality.yaml
raiden/tests/scenarios/bf2_long_running.yaml
raiden/tests/scenarios/bf3_multi_directional_payment.yaml
raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
raiden/tests/scenarios/bf6_stress_hub_node.yaml
raiden/tests/scenarios/bf7_long_path.yaml
raiden/tests/scenarios/mfee1_flat_fee.yaml
raiden/tests/scenarios/mfee2_proportional_fees.yaml
raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
raiden/tests/scenarios/mfee4_combined_fees.yaml
raiden/tests/scenarios/ms1_simple_monitoring.yaml
raiden/tests/scenarios/ms2_simple_monitoring.yaml
raiden/tests/scenarios/ms3_simple_monitoring.yaml
raiden/tests/scenarios/ms4_udc_too_low.yaml
raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
raiden/tests/scenarios/pfs2_simple_no_path.yaml
raiden/tests/scenarios/pfs3_multiple_paths.yaml
raiden/tests/scenarios/pfs4_use_best_path.yaml
raiden/tests/scenarios/pfs5_too_low_capacity.yaml
raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
raiden/tests/scenarios/pfs7_multiple_payments.yaml
raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
raiden/tests/scenarios/pfs9_partial_withdraw.yaml

Temporarily hardcode all scenarios to transport05 to test the presence
router.
Drop this commit before merging to develop.
[skip ci]

DONTMERGE Hardcode transport05

---

.github/auto_assign.yml

Add @konradkonrad to the auto assign bot configuration

Add konradkonrad after vacation

---

raiden/api/v1/encoding.py
raiden/network/transport/matrix/utils.py
raiden/raiden_event_handler.py
raiden/tests/unit/test_utils.py
raiden/utils/capabilities.py
requirements/requirements-docs.txt

Fixes: #6913
- This PR introduces the marshmallow serializer to take care of validation, serialization and deserialization in the Capabilities url

Marshmallow serialization of Capabilities

---

docs/changelog.rst
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.txt

Updates the WebUI to v1.2.1. This includes the UDC dialog and some bug fixes. See https://github.com/raiden-network/webui/releases/tag/v1.2.1

Update WebUI to v1.2.1

---

raiden/messages/metadata.py
raiden/network/transport/matrix/utils.py
raiden/tests/unit/transfer/test_source_routing.py

Fixes: #6954
This PR adds a feature that verifies the user identity using the user id and the displayname received from the PFS.

add displayname validation

---

requirements/requirements-ci.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt
requirements/requirements.txt

Version used by the RSB mainnet release

Update to matrix to 1.33.0

---

raiden/network/transport/matrix/rtc/web_rtc.py
raiden/network/transport/matrix/transport.py
raiden/tests/integration/fixtures/transport.py
raiden/tests/unit/fixtures.py
raiden/tests/unit/test_pfs_integration.py
raiden/utils/typing.py

add displayname and provide capabilities as avatar_url

---

.circleci/config.yml

.circleci: improve dependencies between parameterized jobs

---

.bumpversion_client.cfg
docs/changelog.rst
docs/conf.py

Release 2.0.0a1

---

raiden/tasks.py
raiden/tests/unit/test_startup.py

Fixes: https://github.com/raiden-network/scenario-player/issues/673

Add error handler for connection error on chain id check

---

docs/conf.py
docs/index.rst
docs/other/slow-network-test.rst
docs/raiden-api-1/api-tutorial/2-open-a-channel.inc.rst
docs/the-raiden-web-interface/close-channels-and-settle-payments.inc.rst

The first few commits are misc fixes for things I ran into while building the docs.
Note that I didn't include the new file in any toctree as I am not sure where to put it. Suggestions more than welcome.

Document preparing interfaces for "slow network" testing

---

docs/glossary.rst
docs/index.rst
docs/other/known-issues.rst
docs/testing.rst

This is the last PR for the missing changes from the Gitbook documentation (https://github.com/raiden-network/team/issues/874). This includes improvements to the Index, Known issues and Glossary.

Docs: Last missing improvements from gitbook

---

raiden/messages/decode.py
raiden/messages/metadata.py
raiden/tests/unit/test_serialization.py

Closes https://github.com/raiden-network/raiden/issues/7052.

Make address_metadata optional in RouteMetadata

---

docs/changelog.rst
docs/conf.py

Release 2.0.0a2

---

Makefile
raiden.spec
raiden/network/transport/matrix/transport.py
raiden/tests/utils/transport.py
requirements/requirements-ci.txt
requirements/requirements-dev.txt
requirements/requirements.in
requirements/requirements.txt
tools/pip-compile-wrapper.py

[WIP] Make aiortc optional

---

docs/conf.py

Bump version v2.0.0a2 -> v2.0.0rc0

---

raiden/message_handler.py

Before a failing PFS metadata query during handling a withdraw-request
could fail the node.
Now any error is caught, logged, and the `ReceiveWithdrawRequest`
passed to the state machine without any metadata for the sender.
Fixes: #7102

Add error handling for PFS metadata query in withdraw request handling

---

docs/changelog.rst
docs/conf.py

Release v2.0.0rc1

---

docs/conf.py

Release v2.0.0rc2

---

raiden/ui/cli.py

Fix help text for --gas-price.

---

raiden/constants.py

raiden: constants: update API doc URL

---

.bumpversion_client.cfg
docs/conf.py
raiden/messages/metadata.py
raiden/transfer/state.py
raiden/utils/validation.py

Release v2.0.0rc4

---

.bumpversion_client.cfg
docs/conf.py

Release v2.0.0

---

docs/custom-setups/private_net_tutorial.rst
docs/macos_install_guide.rst
docs/other/safe-usage.rst
docs/overview_and_guide.rst
docs/raiden-api-1/api-tutorial/1-join-a-token-network.inc.rst
docs/rest_api.rst
docs/the-raiden-web-interface/join-a-token-network.inc.rst
docs/using-raiden-on-mainnet/whitelisted-tokens-1.inc.rst

No big changes were necessary, but I could have easily missed something.
Closes https://github.com/raiden-network/raiden/issues/6981.

Prepare documentation for Bespin release

---

tools/transfer_eth.py

Just a little fix for a problem I encountered yesterday.

tools: Fix address conversion in `transfer_eth`
